;;; tree-sitter-ess-r-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tree-sitter-ess-r.el

(autoload 'tree-sitter-ess-r-using-r-faces "tree-sitter-ess-r" "\
Turn on tree-sitter-hl-mode with ess-r-mode faces." t)
(register-definition-prefixes "tree-sitter-ess-r" '("tree-sitter-ess-r-"))

;;; End of scraped data

(provide 'tree-sitter-ess-r-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tree-sitter-ess-r-autoloads.el ends here
