;;; org-sync-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-sync.el

(register-definition-prefixes "org-sync" '("org-sync"))


;;; Generated autoloads from org-sync-bb.el

(register-definition-prefixes "org-sync-bb" '("org-sync-bb-"))


;;; Generated autoloads from org-sync-github.el

(register-definition-prefixes "org-sync-github" '("org-sync-github-"))


;;; Generated autoloads from org-sync-gitlab.el

(register-definition-prefixes "org-sync-gitlab" '("org-sync-"))


;;; Generated autoloads from org-sync-redmine.el

(register-definition-prefixes "org-sync-redmine" '("org-sync-rmine-"))


;;; Generated autoloads from org-sync-rtm.el

(register-definition-prefixes "org-sync-rtm" '("org-sync-rtm-"))

;;; End of scraped data

(provide 'org-sync-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-sync-autoloads.el ends here
