language: python

before_install:
    - sudo add-apt-repository ppa:neovim-ppa/unstable -y
    - sudo apt-get -qq update
    - sudo apt-get install -y shellcheck
    - sudo apt-get install -y neovim

install:
    - pip install vim-vint

before_script: |
    git clone https://github.com/junegunn/vader.vim.git

script:
    - git ls-files | grep '.vim$' | xargs vint
    - git ls-files | grep '.sh$' | xargs shellcheck
    - ./test/run-tests.sh
