#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# e:xelatex

test "$#" -gt 0 && last_arg="${@: -1}"

final-tidy-latex "$last_arg"

# TODO This should only run if the \usepackage{fontspec} is not used
# because fontspec needs xelatex, and this bookify script only works
# with pdflatex.
latex-bookify "$last_arg"
# e:pdflatex-bookify

/usr/bin/pdflatex -interaction nonstopmode "$@"
