cd /root/.pen/documents/agenda;  "bible-search-phrase" "keep" "his" "commandments" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "bible-search-phrase" "keep" "his" "commandments" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search-phrase" "keep" "his" "commandments" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-search-phrase" "keep" "his" "commandments" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "bible-search-phrase" "keep" "his" "commandments" "#" "<==" "bash"
