cd /root/.pen/documents/notes;  "kjv" "Romans" "8" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "1" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "2" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "10" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "7" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "4" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "13" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "9" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "12" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "16" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "11" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "14" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "kjv" "Romans" "15" "#" "<==" "bash"
cd /root/notes;  "kjv" "Hebrews" "11:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes/ws/vimbible;  "kjv" "Hebrews" "#" "<==" "zsh"
cd /root/.pen/documents/notes/ws/vimbible;  "kjv" "1" "Cor" "#" "<==" "zsh"
cd /root/.pen/documents/notes/ws/vimbible;  "kjv" "Colossians" "#" "<==" "zsh"
