#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

set -xv


find . -name '*.html' | awk1 | while IFS=$'\n' read -r line; do
(
    exec 0</dev/null

    dn="$(dirname "$line")"
    cd "$dn"
    CWD="$(pwd)"
    bn="$(basename -- "$line")"
    mant="${bn%.*}"

    if ! test -f "${mant}.txt"; then
        echo "elinks-dump \"$CWD/$bn\" > \"${mant}.txt\""
        elinks-dump "$CWD/$bn" > "${mant}.txt"
    fi
)
done