#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f $HOME/.cargo/bin/htmlq || cargo install "htmlq" &>/dev/null

$HOME/.cargo/bin/htmlq "$@"
