#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

for fp in *.html; do
    slug="$(printf -- "%s\n" "$fp" | tr '\n' ' ' | sed 's/ $//' | sed 's/\.html$//' | slugify)"

    html2org "$fp" > "${slug}.org"
done
