cd /root/.emacs.d/host/pen.el/scripts;  "ead" "NO_CI" "#" "<==" "ead"
cd /usr/local/share/emacs/site-lisp;  "ead" "-z" "pdf" "#" "<==" "ead"
cd /usr/local/share/emacs/site-lisp;  "ead" "-z" "text/plain" "#" "<==" "ead"
cd /root/.emacs.d/host/pen.el/scripts;  "ead" "echo hi" "#" "<==" "ead"
cd /root/.emacs.d/host/pen.el/scripts;  "ead" "xt" "v" "#" "<==" "ead"
cd /root/.emacs.d/host/pen.el/src;  "ead" "-f" "\"H-" "#" "<==" "bash"
cd /usr/local/share/emacs/site-lisp;  "ead" "tv" "#" "<==" "ead"
cd /usr/local/share/emacs/site-lisp;  "ead" "-z" "tv" "#" "<==" "ead"
cd /usr/local/share/emacs/site-lisp;  "ead" "provide.*" "#" "<==" "ead"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ead" "pen-company-filetype-if-prefix" "#" "<==" "ead"
cd /usr/local/share/emacs/site-lisp;  "ead" "-z" "timer" "#" "<==" "ead"
cd /usr/local/share/emacs/site-lisp;  "ead" "-i" "auto-revert-mode-major-mode" "#" "<==" "ead"
cd /etc/apt;  "ead" "libtinfo5" "#" "<==" "ead"
cd /root/.emacs.d/host/pen.el;  "ead" "-f" "\"s-" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "ead" "-f" "\"s-" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "ead" "-f" "\"H-" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el;  "ead" "-f" "\"s-" "#" "<==" "bash"
