cd /;  "host-script" "-sn" "i" "scan" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "scan" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "host-script" "-sn" "alsamixer" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "host-script" "-sn" "cvlc" "/home/shane/dump/programs/httrack/mirrors/http-openhymnal-org-/openhymnal.org/Mp3/All_Who_Believe_And_Are_Baptized-Es_ist_das_Heil_uns_Kommen_her.mp3" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "acpi" "-b" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "acpi" "-b" "#" "<==" "withopts"
