cd /root/.pen/documents/notes;  "host-script" "-sn" "blueman-manager" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "blueman-manager" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "setup-keyboard" "-a" "megn" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "acpi" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "setup-keyboard" "-a" "megn" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "blueman-manager" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "setup-keyboard" "-a" "megn" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "alsamixer" "#" "<==" "withopts"
