cd /root/.pen/documents/notes;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "host-script" "-sn" "restart-network" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
