cd /root/.pen/documents/notes;  "host-script" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "acpi" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "host-script-force" "acpi" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "acpi" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "acpi" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "acpi" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "acpi" "-b" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/agenda;  "host-script" "-sn" "restart-network" "#" "<==" "withopts"
