cd /root/.pen/documents/notes;  "host-script" "-sn" "i" "scan" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "scan" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "timedatectl" "status" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "timedatectl" "status" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "timedatectl" "status" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "timedatectl" "status" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "timedatectl" "status" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "host-script" "-sn" "timedatectl" "set-local-rtc" "0" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "timedatectl" "set-timezone" "Pacific/Auckland" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "timedatectl" "set-timezone" "Pacific/Auckland" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "timedatectl" "status" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "scan" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "scan" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "restart-network" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "host-script" "-sn" "nmtui" "sudo" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "host-script" "-sn" "nmtui" "sudo" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "source-profile" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "source-profile" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "nmtui" "source-profile" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "acpi" "-b" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "acpi" "-b" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "gw" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
cd /;  "host-script" "-sn" "i" "scan" "#" "<==" "withopts"
cd /;  "host-script" "-srcp" "-sn" "nmtui" "#" "<==" "withopts"
