#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

{
if test -f "$1" && ! stdin_exists; then
    # Remove trailing whitespace but add a trailing space for org headers
    cat "$1" | sed -e 's/\s\+$//' \
        -e 's/^\(\*\+\)$/\1 /' | sponge "$1"
elif stdin_exists; then
    # Remove trailing whitespace but add a trailing space for org headers
    sed -e 's/\s\+$//' \
        -e 's/^\(\*\+\)$/\1 /'
fi
} | pavs
