#!/bin/bash
export TTY

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if test -f "$1"; then
    # Remove trailing whitespace but add a trailing space for org headers
    cat "$1" | sed -e 's/\s\+$//' \
        -e 's/^\(\*\+\)$/\1 /' | sponge "$1"
elif stdin_exists; then
    # Remove trailing whitespace but add a trailing space for org headers
    sed -e 's/\s\+$//' \
        -e 's/^\(\*\+\)$/\1 /'
fi
