#!/bin/bash
export TTY

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$NO_STDIN" = y ` # for notty. e.g. notty xt vim ` && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

function pad () { [ "$#" -gt 1 ] && [ -n "$2" ] && printf "%$2.${2#-}s" "$1"; }

# Usage examples:

# $ echo "!$(pad "foobar" 9)!"
# !   foobar!
# $ echo "!$(pad "foobar" -9)!"
# !foobar   !
# $ echo "!$(pad "foobar" 3)!"
# !foo!

if stdin_exists; then
    input="$(cat)"
    set -- "$input" "$@"
fi

pad "$@"
