cd /root/.pen/documents/notes;  "sh-games" "#" "<==" "sh-apps"
cd /root/.pen/documents/notes;  "sh-games" "#" "<==" "sh-apps"
cd /root/.pen/documents/notes;  "sh-games" "#" "<==" "sh-apps"
cd /root/.pen/documents/notes;  "sh-games" "#" "<==" "sh-apps"
cd /root/.pen/documents/notes;  "sh-games" "#" "<==" "sh-apps"
