#!/bin/bash
export TTY

# DEPRECATED

# . $SCRIPTS/lib/hs

# The problem with show-fds is an index doesn't exists for the pipes

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -toppid) {
        pid="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${pid:="$$"}"
fds="$(show-fds "$pid")"

grepfilter-transform.els "$fds" "$@"
