cd /volumes/home/shane/var/smulliga/source/git/tmewett/BrogueCE/bin;  "dbus-launch" "--autolaunch" "88ca5e7b2819c56ffc2ab2fc4af49881" "--binary-syntax" "--close-stderr" "#" "<==" "brogue"
cd /volumes/home/shane/var/smulliga/source/git/tmewett/BrogueCE/bin;  "dbus-launch" "--autolaunch" "88ca5e7b2819c56ffc2ab2fc4af49881" "--binary-syntax" "--close-stderr" "#" "<==" "brogue"
cd /volumes/home/shane/var/smulliga/source/git/tmewett/BrogueCE/bin;  "dbus-launch" "--autolaunch" "88ca5e7b2819c56ffc2ab2fc4af49881" "--binary-syntax" "--close-stderr" "#" "<==" "brogue"
cd /volumes/home/shane/var/smulliga/source/git/tmewett/BrogueCE/bin;  "dbus-launch" "--autolaunch" "88ca5e7b2819c56ffc2ab2fc4af49881" "--binary-syntax" "--close-stderr" "#" "<==" "brogue"
cd /volumes/home/shane/var/smulliga/source/git/tmewett/BrogueCE/bin;  "dbus-launch" "--autolaunch" "88ca5e7b2819c56ffc2ab2fc4af49881" "--binary-syntax" "--close-stderr" "#" "<==" "brogue"
cd /volumes/home/shane/var/smulliga/source/git/tmewett/BrogueCE/bin;  "dbus-launch" "--autolaunch" "88ca5e7b2819c56ffc2ab2fc4af49881" "--binary-syntax" "--close-stderr" "#" "<==" "brogue"
cd /root/notes;  "dbus-launch" "--autolaunch=88ca5e7b2819c56ffc2ab2fc4af49881" "--binary-syntax" "--close-stderr" "#" "<==" "emacs"
