;;; sideline-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sideline.el

(autoload 'sideline-mode "sideline" "\
Minor mode `sideline-mode'.

This is a minor mode.  If called interactively, toggle the
`Sideline mode' mode.  If the prefix argument is positive, enable
the mode,  and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `sideline-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-sideline-mode 'globalized-minor-mode t)
(defvar global-sideline-mode nil "\
Non-nil if Global Sideline mode is enabled.
See the `global-sideline-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-sideline-mode'.")
(custom-autoload 'global-sideline-mode "sideline" nil)
(autoload 'global-sideline-mode "sideline" "\
Toggle Sideline mode in all buffers.
With prefix ARG, enable Global Sideline mode if ARG is positive; otherwise,
disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Sideline mode is enabled in all buffers where `sideline--turn-on-sideline-mode'
would do it.

See `sideline-mode' for more information on Sideline mode.

(fn &optional ARG)" t)
(register-definition-prefixes "sideline" '("sideline-"))

;;; End of scraped data

(provide 'sideline-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sideline-autoloads.el ends here
