cd //;  "bis" "Father" "God" "#" "<==" "zsh"
cd //;  "bis" "Heavenly" "#" "<==" "zsh"
cd /;  "bis" "sphere" "#" "<==" "zsh"
cd /root/notes;  "bis" "Heavenly" "#" "<==" "tmux: server"
cd /root/notes;  "bis" "Heavenly" "#" "<==" "tmux: server"
cd /root/notes;  "bis" "Heavenly" "#" "<==" "tmux: server"
cd /root/.pen/documents/notes;  "bis" "alabaster" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bis" "alabaster" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bis" "alabaster" "#" "<==" "zsh"
cd /root/notes;  "bis" "Therefore," "if" "anyone" "#" "<==" "zsh"
cd /root/notes;  "bis" "Therefore," "if" "anyone" "#" "<==" "nvim"
cd /root/notes;  "bis" "Therefore," "if" "anyone" "#" "<==" "bash"
