cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Titus 3:9" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "1 Timothy 2:5" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "1 Timothy 1:4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "1 CORINTHIANS 1:30" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "EPHESIANS 6:12" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "ROMANS 10:9-10" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "De 6:4" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "1Co 3:7" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "1Pe 3:21" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "1Co 12:13" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "1Co 3:6" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Mt 28:19" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Ro 6:3" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Col 2:12" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Col 2:12" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Ga 3:27" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Ro 6:4,5" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Ac 22:16" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Ex 23:13" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "Ac 8:38,39" "#" "<==" "zsh"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "bible-tpop-lookup" "-c" "-m" "KJV" "1Co 11:23-" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ac 2:17" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ac 2:17" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ac 2:17" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jm 5:3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jm 5:3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Heb 10:20" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jm 5:3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jm 5:3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jm 5:3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jm 5:3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jm 5:3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Heb 10:20" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ro 7:25" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ac 2:17" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ac 2:31" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ro 1:3" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ro 7:5" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "bible-tpop-lookup" "-c" "-m" "KJV" "1 Cor 6:19," "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "bible-tpop-lookup" "-c" "-m" "KJV" "Rom 14:7-9" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "bible-tpop-lookup" "-c" "-m" "KJV" "Rom 8:14" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws;  "bible-tpop-lookup" "-c" "-m" "KJV" "Matthew 10:29-31" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Proverbs 12:11" "#" "<==" "bash"
