cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Corinthians 14:4" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Corinthians 14:2" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ephesians 6:18" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Romans 8:25" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Corinthians 14:22" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 2:17-21" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 2:17-21" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "bible-tpop-lookup" "-c" "-m" "KJV" "Romans 3:1-20" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Corinthians 14:2" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "1 Corinthians 14:22" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Romans 8:26-27" "#" "<==" "bash"
