cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Kings" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "John" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Isaiah 2:6-8" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "James 5:20" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Corinthians 1:23" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Luke 4:18-19" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "2 Corinthians 2:12" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "ESV" "Ge 1:20" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ps.33.6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ps.33.6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ps.33.6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ps.33.6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Rev 2:1" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Rev 2:1" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ps.33.6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ps.33.6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5-10" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 33:6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5-10" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 33:6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5-10" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 33:6" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "John 3:13" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "John 15:19" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Luke 12:2-3" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "ESV" "Genesis 1:23" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Isaiah 45:18" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Genesis 1:1" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 8:4-8" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "ESV" "Genesis 2:24" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Corinthians 7:10-11" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Ephesians 5:28-31" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Romans 7:2" "#" "<==" "bash"
cd /root/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 135:7" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "John 3:13" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "ESV" "Genesis 1:19" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 104:24-25" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Kings 4:33" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "KJV" "Genesis 1:30" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 148:10" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Kings 4:33" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el;  "bible-tpop-lookup" "-c" "-m" "ESV" "Genesis 1:10" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el;  "bible-tpop-lookup" "-c" "-m" "KJV" "Deuteronomy 32:4" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 104:14-17" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 104:14-17" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Daniel 2" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Deuteronomy 32:4" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 104:14-17" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Genesis 41" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I John 1:1" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 89:11-12" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Revelation of John 3:13" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I John 3:13" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "ESV" "Genesis 1:12" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Mark 4:28" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Isaiah 55:10-11" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Matthew 13:24-26" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Galatians 6:7" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Thessalonians 2:13-14" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Timothy 2:25" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Timothy 3:16" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Timothy 6:3" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Timothy 2:25" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Timothy 2:25" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Thessalonians 2:14" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 91" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 33:6" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I John 3:13" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Corinthians 12:9-11" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Mark 6:30-32" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "John 16" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Isaiah 48:3" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:5" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 33:6" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "NASB" "Matthew 4:7" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "NASB" "Matthew 8:3" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "bible-tpop-lookup" "-c" "-m" "NASB" "Exodus 29:32" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Peter 5:8" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Genesis 1:1" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "John 16" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "ESV" "Genesis 1:13" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Peter 1:21" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Corinthians 8:4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 81:11-13" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Deuteronomy 28:15-68" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Peter 4:11" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "II Corinthians 10:3" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Hebrews 11:6" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Hebrews 11:6" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Hebrews 11:6" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "ESV" "Genesis 1:14" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 2:30-31" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 2:30-31" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 3:15" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 104:19-20" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jeremiah 10:2" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 3:15" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 2:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Joel 2:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 2:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 2:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 2:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 2:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "/root/ pen/tmp/tf_temp6bngrB8 txt 2:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Joel 2:10" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Joel 2:30-31" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 2:19-20" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Jeremiah 33:20" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Amos 8:9" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Matthew 24:29" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Joel 2:30-31" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 74:16-17" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Revelation of John 6:12" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 104:19-20" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Revelation of John 16:8-9" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Deuteronomy 4:19" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Job 38:9" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Psalms 104:14-17" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Samuel 20:41" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 16:11" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "Acts 21:1" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-tpop-lookup" "-c" "-m" "KJV" "I Thessalonians 2:17" "#" "<==" "zsh"
