;;; slime-docker-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from slime-docker.el

(autoload 'slime-docker-start "slime-docker" "\
Start a Docker container and Lisp process in the container then connect to it.

If the slime-tramp contrib is also loaded (highly recommended),
this will also set up the appropriate tramp translations to view
and edit files in the spawned container.

PROGRAM and PROGRAM-ARGS are the filename and argument strings
  for the Lisp process.
IMAGE-NAME is a string naming the image that should be used to
  start the container.
IMAGE-TAG is a string nameing the tag to use. Defaults to
  \"latest\".
INIT is a function that should return a string to load and start
  Swank. The function will be called with a plist of all
  arguments passed to `slime-docker-start'
ENV an alist of environment variables to set in the docker
  container.
BUFFER the name of the buffer to use for the subprocess.
NAME a symbol to describe the Lisp implementation.
DIRECTORY set this as the working directory in the container.
RM if true, the container is removed when the process closes.
MOUNTS a list describing the voluments to mount into the
  container. It is of the form:
  (((HOST-PATH . CONTAINER-PATH) &key READ-ONLY) ... )
UID sets the UID of the Lisp process in the container.
GID sets the GID of the Lisp process in the container.
SLIME-MOUNT-PATH the location where to mount SLIME into the
  container defaults to
  /usr/local/share/common-lisp/source/slime/
SLIME-MOUNT-READ-ONLY if non-NIL, SLIME is mounted into the
  container as read-only. Defaults to T.
DOCKER-MACHINE if non-NIL, must be a string naming a machine name
  known to docker-machine. If provided, used to set appropriate
  environment variables for the docker process to communicate
  with the desired machine. Does not start the machine if it is
  currently not running.
DOCKER-COMMAND is the command to use when interacting with
  docker. Defaults to \"docker\". See
  `slime-docker-machine-ssh-agent-helper-path' if you are using
  docker-machine and would like to share your SSH Agent with the
  container.
DOCKER-MACHINE-SETENV if non-NIL, uses `setenv' to set Emacs
  environment with the necessary variables from
  docker-machine. Should be non-NIL if you expect tramp to work
  with images running in docker machine.
SECURITY-OPTS specifies --security-opt options when running
  'docker run'. Must be an alist where keys and values are
  strings. See README for note on using this with SBCL.
USERNS specifies the user namespace to use when starting the
  container. See the --userns option to 'docker run' for more
  information.
DNS specifies a list of DNS servers to use in the container. If
  you're on a laptop, it's recommended to set this value as
  Docker does not update a container's DNS info while it is
  running (for example if you change networks).
PORTS is a list of port specifications to open in the docker
  container. The port specifications are plists with the
  properties :ip, :host-port, and :container-port. :ip must be a
  string. :host-port and :container-port must be a number or a
  cons cell.

(fn &key (PROGRAM slime-docker-program) (PROGRAM-ARGS slime-docker-program-args) (DIRECTORY slime-docker-directory) NAME (BUFFER \"*docker-lisp*\") (IMAGE-NAME slime-docker-image-name) (IMAGE-TAG slime-docker-image-tag) (RM slime-docker-rm) (ENV slime-docker-env) (INIT \\='slime-docker--init-command) (MOUNTS slime-docker-mounts) (SLIME-MOUNT-PATH slime-docker-slime-mount-path) (SLIME-MOUNT-READ-ONLY slime-docker-slime-mount-read-only) (UID slime-docker-uid) (GID slime-docker-gid) (DOCKER-MACHINE slime-docker-docker-machine) (DOCKER-COMMAND slime-docker-docker-command) (DOCKER-MACHINE-SETENV t) (SECURITY-OPTS slime-docker-machine-security-opts) (USERNS slime-docker-userns) (DNS slime-docker-dns) (PORTS slime-docker-ports) (NETWORK slime-docker-network))")
(autoload 'slime-docker "slime-docker" "\
Launch a Lisp process in a Docker container and connect SLIME to it.

The normal entry point to slime-docker.el. Similar to `slime'
function. Tries to guess the correct Lisp to start based on
prefix arguments and the values of `slime-docker-implementations'
and `slime-docker-default-lisp'.

COMMAND is the command to run in the Docker container.

(fn &optional COMMAND)" t)
(register-definition-prefixes "slime-docker" '("slime-docker-"))

;;; End of scraped data

(provide 'slime-docker-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; slime-docker-autoloads.el ends here
