cd /root/notes;  "htop" "#" "<==" "tmux: server"
cd /root/notes;  "htop" "#" "<==" "tmux: server"
cd /root/notes;  "htop" "#" "<==" "tmux: server"
cd /root/notes;  "htop" "#" "<==" "tmux: server"
cd /root/notes;  "htop" "#" "<==" "tmux: server"
cd /root/notes;  "htop" "#" "<==" "tmux: server"
cd /root/.emacs.d/host/pen.el/src;  "htop" "#" "<==" "zsh"
cd /root/notes;  "htop" "#" "<==" "tmux: server"
