cd /volumes/home/shane/notes/ws/jobs;  "hb" "#" "<==" "zsh"
cd /root/notes;  "hb" "#" "<==" "bash"
cd /root/notes;  "hb" "#" "<==" "bash"
cd /root/notes;  "hb" "#" "<==" "bash"
cd /root/notes;  "hb" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "hb" "-hb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "hb" "-ec" "#" "<==" "zsh"
cd /root/notes;  "hb" "--help" "#" "<==" "zsh"
cd /root/notes;  "hb" "-h" "#" "<==" "man"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "-h" "#" "<==" "man"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "-h" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "--help" "#" "<==" "hb"
cd /root/.pen/documents/notes;  "hb" "-h" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "hb" "-h" "#" "<==" "man"
cd /root/.pen/documents/notes;  "hb" "-h" "#" "<==" "man"
cd /root/notes;  "hb" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "hb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "hb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "hb" "#" "<==" "zsh"
