#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "$1" && : "${fp:="$1"}"
: "${fp:="/dev/stdin"}"

convert "$1" -auto-level -threshold 50% PNG:-
