cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "6:47" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "6:47-51" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "6:45-47" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "6:40-45" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "6:40-47" "#" "<==" "zsh"
