cd /root/notes;  "John" "6:40" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "John" "6" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "John" "3:10" "#" "<==" "zsh"
cd /root/notes;  "John" "14:15" "#" "<==" "zsh"
cd /root/notes;  "John" "12:44-15" "#" "<==" "zsh"
cd /root/notes;  "John" "12:44-50" "#" "<==" "zsh"
cd /root/notes;  "John" "15:10" "#" "<==" "zsh"
cd /root/notes;  "John" "12:44" "#" "<==" "zsh"
