cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "10:16" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "10:16" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "11:52" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "11:51-52" "#" "<==" "zsh"
cd /root/notes;  "John" "16:33" "#" "<==" "zsh"
