cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "12:25:" "Whoever" "loves" "his" "life" "loses" "it," "and" "whoever" "hates" "his" "life" "in" "this" "world" "will" "keep" "it" "for" "eternal" "life." "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "12:25:" "Whoever" "loves" "his" "life" "loses" "it," "and" "whoever" "hates" "his" "life" "in" "this" "world" "will" "keep" "it" "for" "eternal" "life." "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "12:25:" "Whoever" "loves" "his" "life" "loses" "it," "and" "whoever" "hates" "his" "life" "in" "this" "world" "will" "keep" "it" "for" "eternal" "life." "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "John" "12:25" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "John" "7:17" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "John" "16:33" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "John" "10:10" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "John" "16:33" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "John" "8:32" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "John" "10:10" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "John" "16:33" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "John" "8:32" "#" "<==" "bash"
