cd /root/.emacs.d/host/pen.el/docs/theology;  "John" "3:36" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "John" "10:26-27" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "John" "6:35" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "John" "4:10" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "John" "4:34" "#" "<==" "zsh"
