;;; org-shoplist-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-shoplist.el

(autoload 'org-shoplist-init "org-shoplist" "\
Setting the todo-keywords for current file." t)
(autoload 'org-shoplist-unmark-all "org-shoplist" "\
Unmark all recipes which are marked with ‘ORG-SHOPLIST-KEYWORD’." t)
(autoload 'org-shoplist-recipe-set-factor "org-shoplist" "\
Set ‘FACTOR’ with property-name ‘ORG-SHOPLIST-FACTOR-PROPERTY-NAME’ on current recipe.

(fn FACTOR)" t)
(autoload 'org-shoplist-factor-down "org-shoplist" "\
Decrement the factor-property of current header." t)
(autoload 'org-shoplist-factor-up "org-shoplist" "\
Increment the factor-property of current header." t)
(register-definition-prefixes "org-shoplist" '("org-shoplist"))

;;; End of scraped data

(provide 'org-shoplist-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-shoplist-autoloads.el ends here
