cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/Perm" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/hereby" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/hereby" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "#" "<==" "nvim"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "nnv"
cd /root/.pen/documents/notes;  "bvi" "+/provided" "/volumes/home/shane/var/smulliga/source/git/tmux/tmux/grid.c" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "bvi" "+/designed" "/root/.emacs.d/host/pen.el/README.org" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "bvi" "+/designed" "/root/.emacs.d/host/pen.el/README.org" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "bvi" "+/designed" "/root/.emacs.d/host/pen.el/README.org" "#" "<==" "zsh"
