;;; theme-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from modus-operandi-deuteranopia-theme.el

(put 'modus-operandi-deuteranopia 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'modus))


;;; Generated autoloads from modus-operandi-theme.el

(put 'modus-operandi 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'modus))


;;; Generated autoloads from modus-operandi-tinted-theme.el

(put 'modus-operandi-tinted 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'modus))


;;; Generated autoloads from modus-operandi-tritanopia-theme.el

(put 'modus-operandi-tritanopia 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'modus))


;;; Generated autoloads from modus-vivendi-deuteranopia-theme.el

(put 'modus-vivendi-deuteranopia 'theme-properties (list :background-mode 'dark :kind 'color-scheme :family 'modus))


;;; Generated autoloads from modus-vivendi-theme.el

(put 'modus-vivendi 'theme-properties (list :background-mode 'dark :kind 'color-scheme :family 'modus))


;;; Generated autoloads from modus-vivendi-tinted-theme.el

(put 'modus-vivendi-tinted 'theme-properties (list :background-mode 'dark :kind 'color-scheme :family 'modus))


;;; Generated autoloads from modus-vivendi-tritanopia-theme.el

(put 'modus-vivendi-tritanopia 'theme-properties (list :background-mode 'dark :kind 'color-scheme :family 'modus))

;;; End of scraped data

(provide 'theme-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; theme-loaddefs.el ends here
