cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://github.com/mattn/go-sixel" "#" "<==" "o"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/2547ac3a92/mm.0uvQjS.html" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/2547ac3a92/mm.zRCVJk.html" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/2547ac3a92/mm.jhL1mD.html" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/484e8301c0/mm.iVlnKT.html" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/188b9b4e60/mm.NXyklK.html" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/2547ac3a92/mm.mTl3pw.html" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/2547ac3a92/mm.5wGqc6.html" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "o" "/root/.pen/file-store-by-hash/e876e76f48/mm.PVKeHz.html" "#" "<==" "bash"
