cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://www.colinurquhart.com/Article/19/Defeating-the-Leviathan-Spirit.aspx" "#" "<==" "o"
cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://www.youtube.com/watch?v=ROuwFJKVG8I" "#" "<==" "o"
cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://www.youtube.com/watch?v=tqtl-sXeTmA" "#" "<==" "o"
cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://github.com/qfpl/sv/blob/master/examples/src/Data/Sv/Example/TableTennis.hs" "#" "<==" "o"
cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://jesusisgodandlordministries.com/why-we-must-be-born-again/" "#" "<==" "o"
