cd /root/notes;  "o" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:Christ Loves All Nations]]" "#" "<==" "o"
cd /root/notes;  "o" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "o"
cd /root/notes;  "o" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "o"
cd /root/notes;  "o" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:admin@leithvalley.org.nz]]" "#" "<==" "o"
cd /root/notes;  "o" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:Leith Valley Church]]" "#" "<==" "o"
cd /root/notes;  "o" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:admin@leithvalley.org.nz]]" "#" "<==" "o"
cd /root/notes;  "o" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "o"
cd /root/notes;  "o" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "o"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "bash"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "bash"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "bash"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "bash"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "bash"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "bash"
cd /root/notes;  "o" "[[ebdb:\"267 Malvern Street\\nDunedin, Otago 9010\\nNew Zealand\"]]" "#" "<==" "zsh"
