cd /;  "o" "#" "<==" "zsh"
cd /;  "o" "https://www.reuters.com/technology/artificial-intelligence/openai-working-new-reasoning-technology-under-code-name-strawberry-2024-07-12/" "#" "<==" "o"
cd /;  "o" "#" "<==" "zsh"
cd /;  "o" "https://www.reuters.com/technology/artificial-intelligence/openai-working-new-reasoning-technology-under-code-name-strawberry-2024-07-12/" "#" "<==" "o"
cd /;  "o" "#" "<==" "zsh"
cd /;  "o" "https://www.reuters.com/technology/artificial-intelligence/openai-working-new-reasoning-technology-under-code-name-strawberry-2024-07-12/" "#" "<==" "o"
cd /;  "o" "#" "<==" "zsh"
cd /;  "o" "https://www.reuters.com/technology/artificial-intelligence/openai-working-new-reasoning-technology-under-code-name-strawberry-2024-07-12/" "#" "<==" "o"
cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://www.youtube.com/watch?v=xe9eg2G3tCk&ab_channel=ChaplaincyPlus" "#" "<==" "o"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "o" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "o" "https://www.youtube.com/watch?v=xe9eg2G3tCk&ab_channel=ChaplaincyPlus" "#" "<==" "o"
