cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://emacs.stackexchange.com/questions/87/how-do-i-search-info-for-help-on-a-given-keyword-or-function" "#" "<==" "o"
cd /root/.pen/documents/notes;  "o" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "https://emacs.stackexchange.com/questions/87/how-do-i-search-info-for-help-on-a-given-keyword-or-function" "#" "<==" "o"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/e2358974e3/TaxInvoice-BU107582.pdf" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "o" "/root/.pen/file-store-by-hash/e2358974e3/TaxInvoice-BU107582.pdf" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "o" "Music Data Base.xls" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "o" "Music Data Base.xls" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/file-store-by-hash/e2358974e3/TaxInvoice-BU107582.pdf" "#" "<==" "bash"
