cd /root/.pen/documents/notes;  "o" "Music Data Base.xls" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/file-store-by-hash/82409f1a92/FINAL 2023 Table Host Instructions.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/file-store-by-hash/f5e4c80e9c/Day 2.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/file-store-by-hash/f5e4c80e9c/Day 2.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/file-store-by-hash/82409f1a92/FINAL 2023 Table Host Instructions.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)/C. H. Spurgeon's Puritan Catechism - ATELIER313.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)/C. H. Spurgeon's Puritan Catechism - ATELIER313.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)/C. H. Spurgeon's Puritan Catechism - ATELIER313.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)/C. H. Spurgeon's Puritan Catechism - ATELIER313.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)/C. H. Spurgeon's Puritan Catechism - ATELIER313.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)/C. H. Spurgeon's Puritan Catechism - ATELIER313.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)/C. H. Spurgeon's Puritan Catechism - ATELIER313.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)/C. H. Spurgeon's Puritan Catechism - ATELIER313.pdf" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/J. C. Ryle/Holiness (5)/Holiness - J. C. Ryle.epub" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/ebooks/J. C. Ryle/Holiness (5)/Holiness - J. C. Ryle.epub" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "o" "/root/.pen/file-store-by-hash/82409f1a92/FINAL 2023 Table Host Instructions.pdf" "#" "<==" "bash"
cd /root/.pen/org-brain/past;  "o" "/root/.pen/file-store-by-hash/ccfafe0dd3/Payslip_20170704_305000049.PDF" "#" "<==" "bash"
cd /root/.pen/org-brain/past;  "o" "/root/.pen/file-store-by-hash/ccfafe0dd3/Payslip_20170704_305000049.PDF" "#" "<==" "bash"
cd /root/.pen/org-brain/past;  "o" "/root/.pen/file-store-by-hash/ccfafe0dd3/Payslip_20170704_305000049.PDF" "#" "<==" "bash"
cd /root/.pen/org-brain/past;  "o" "/root/.pen/file-store-by-hash/ccfafe0dd3/Payslip_20170704_305000049.PDF" "#" "<==" "bash"
cd /root/.pen/org-brain/past;  "o" "/root/.pen/file-store-by-hash/ccfafe0dd3/Payslip_20170704_305000049.PDF" "#" "<==" "bash"
cd /root/.pen/org-brain/past;  "o" "/root/.pen/file-store-by-hash/ccfafe0dd3/Payslip_20170704_305000049.PDF" "#" "<==" "bash"
cd /root/.pen/org-brain/past;  "o" "/root/.pen/file-store-by-hash/ccfafe0dd3/Payslip_20170704_305000049.PDF" "#" "<==" "bash"
