#!/bin/bash
export TTY

: "${dir:="$1"}"
: "${dir:="$(pwd)"}"

# exec 2>/dev/null

# . $SCRIPTS/lib/hs

# pat="$1"

cd "$dir"
find . \( -iname '*.md' -or -iname '*.markdown' -or -iname '*.org' -or -iname '*.adoc' -or -iname '*.rst' \) | sed 's=^\./==' | pa -E "fzf --sync | xa sp"