cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_ANZMGr_rand-9901_pid-564350.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_NU10tT_rand-14605_pid-339202.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_NU10tT_rand-14605_pid-339202.bin | timeout 4 eng2ipa" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_NU10tT_rand-14605_pid-339202.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_XdkyPD_rand-12679_pid-339994.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_XdkyPD_rand-12679_pid-339994.bin | timeout 4 eng2ipa" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_XdkyPD_rand-12679_pid-339994.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_XdkyPD_rand-12679_pid-339994.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_XdkyPD_rand-12679_pid-339994.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_XdkyPD_rand-12679_pid-339994.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 eng2ipa" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 xargs" "-l1" "sha" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 eng2ipa" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 f-irc" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_aCOt6q_rand-10047_pid-341154.bin | timeout 4 sttr" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_m0LTl3_rand-12366_pid-345408.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_a0VG4u_rand-32638_pid-346008.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_zRDn62_rand-28921_pid-348235.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_Xpt6qB_rand-12792_pid-350159.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_ib2xq8_rand-27527_pid-356301.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rVcjYp_rand-12775_pid-357518.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rVcjYp_rand-12775_pid-357518.bin | timeout 4 f-irc" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rVcjYp_rand-12775_pid-357518.bin | timeout 4 sttr" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_qZWgDD_rand-429_pid-358393.bin | filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_qZWgDD_rand-429_pid-358393.bin | eng2ipa" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_qZWgDD_rand-429_pid-358393.bin | scrape-emails" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_qZWgDD_rand-429_pid-358393.bin | filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_CHNoAO_rand-15280_pid-359965.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LgMMjW_rand-26962_pid-361313.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LgMMjW_rand-26962_pid-361313.bin | timeout 4 f-irc" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LgMMjW_rand-26962_pid-361313.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LgMMjW_rand-26962_pid-361313.bin | timeout 4 eng2ipa" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LgMMjW_rand-26962_pid-361313.bin | timeout 4 scrape-emails" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LgMMjW_rand-26962_pid-361313.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rpJIqt_rand-2363_pid-363050.bin | filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rpJIqt_rand-2363_pid-363050.bin | f-irc" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rpJIqt_rand-2363_pid-363050.bin | sttr" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rpJIqt_rand-2363_pid-363050.bin | filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rpJIqt_rand-2363_pid-363050.bin | eng2ipa" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_rpJIqt_rand-2363_pid-363050.bin | scrape-emails" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_2Y4SGR_rand-13176_pid-364903.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_2Y4SGR_rand-13176_pid-364903.bin | timeout 4 eng2ipa" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_2Y4SGR_rand-13176_pid-364903.bin | timeout 4 scrape-emails" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_2Y4SGR_rand-13176_pid-364903.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_2Y4SGR_rand-13176_pid-364903.bin | timeout 4 scrape-emails" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_2Y4SGR_rand-13176_pid-364903.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LngNXY_rand-16526_pid-368660.bin | timeout 4 filter-things.sh" "" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LngNXY_rand-16526_pid-368660.bin | timeout 4 ew" "" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LngNXY_rand-16526_pid-368660.bin | timeout 4 scrape-emails" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LngNXY_rand-16526_pid-368660.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_LngNXY_rand-16526_pid-368660.bin | timeout 4 scrape-emails" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_q2fJTX_rand-18200_pid-372067.bin | timeout 4 filter-things.sh" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_q2fJTX_rand-18200_pid-372067.bin | timeout 4 rosie-ips" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_q2fJTX_rand-18200_pid-372067.bin | timeout 4 rosie-extract-paths" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_q2fJTX_rand-18200_pid-372067.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/dump/tmp/scratchEKC2Yy.txt | timeout 4 rosie grep -o subs net.email" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/dump/tmp/scratchEKC2Yy.txt | timeout 4 rosie grep -o subs net.email" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_q2fJTX_rand-18200_pid-372067.bin | timeout 4 rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "fzf"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/dump/tmp/scratchEKC2Yy.txt | timeout 4 rosie grep -o subs net.email" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/dump/tmp/scratchEKC2Yy.txt | timeout 4 rosie grep -o subs net.email" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/dump/tmp/scratchEKC2Yy.txt | timeout 4 rosie grep -o subs net.email" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/dump/tmp/scratchEKC2Yy.txt | timeout 4 rosie grep -o subs net.email" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_JKSfj6_rand-1765_pid-381215.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_JKSfj6_rand-1765_pid-381215.bin | timeout 4 eng2ipa" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_JKSfj6_rand-1765_pid-381215.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_JKSfj6_rand-1765_pid-381215.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_JKSfj6_rand-1765_pid-381215.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_JKSfj6_rand-1765_pid-381215.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_MiYBLp_rand-16443_pid-392501.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_MiYBLp_rand-16443_pid-392501.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_MiYBLp_rand-16443_pid-392501.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_MiYBLp_rand-16443_pid-392501.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_MiYBLp_rand-16443_pid-392501.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_MiYBLp_rand-16443_pid-392501.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_MiYBLp_rand-16443_pid-392501.bin | timeout 4 rosie" "grep" "-o" "subs" "net.email" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_MiYBLp_rand-16443_pid-392501.bin | timeout 4 scrape-emails" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_BsxD9p_rand-12558_pid-398887.bin | timeout 4 filter-things.sh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/.pen/tmp/file_input_BsxD9p_rand-12558_pid-398887.bin | timeout 4 f-irc" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nh" "ocif" "-nd" "-E" "cat /root/dump/tmp/scratchEKC2Yy.txt | timeout 4 rosie grep -o subs net.email" "#" "<==" "zsh"
