* =Pen.el= (a holy OS)
Pen.el is an emacs-based operating system designed with holiness in mind.
It's a free and holy OS made with emacs, debian linux and docker.

/This project is not in a ready state/

It's holy because:
- This software is dedicated to supporting one's Christian faith
  - Facilitate:
    - Praying
    - Praising
    - Running churches
    - Maintaining holiness
    - Bible studies
- Features:
  - Bible software comparable to Logos / e-Sword.
  - Integrates lots of Christian resources.
  - Lots of scripts for working with Bible-verses etc.
    - Extracting Bible verses from websites, documents, etc.
    - Canonicalising Bible-refs
    - Formatting Bible passages in various ways.
    - etc.
- Policies:
  - Avoid AI fiction and ensure it is kept at a safe distance
  - Strict ban on proprietary software

** Aims
- Provide the user with free (but advanced) Bible study software, and
- Provide trustworthy Christian resources that are all offline.
- Make it easier to maintain one's Christian faith by eliminating all the distractions, yet being featureful and fun.
- Able to be the main operating system somebody uses (It's my main OS).

Using Pen.el, there should be no need to go online, as it should contain everything you need to be content with your computing.
The Bible-software is indented to be as featureful as any of the other options available, but completely free, and also low maintenance.

** Intended users
- emacs/linux savvy:
  - pastors,
  - church deacons,
  - chaplains,
  - theology students
  - anyone wanting software that respects a user's desire to remain holy

** Technical details
- It runs in a docker container.
- It's primarily text-based computing environment with emacs as the main component towards that end.

** Quick installation
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  git clone "https://github.com/semiosis/pen.el"

  mkdir -p ~/.pen

  # Add the scripts to the PATH
  echo export PATH="$(realpath .)/pen.el/scripts:\$PATH" >> ~/.profile

  # Add this to prevent C-s from freezing the terminal
  echo "stty stop undef 2>/dev/null; stty start undef 2>/dev/null" | tee -a ~/.zshrc >> ~/.bashrc

  # Source your .profile
  . ~/.profile

  # Run pen
  pen
#+END_SRC

** It's about holiness
#+BEGIN_SRC text -n :async :results verbatim code :lang text
  holiness
      The state of being holy.
      "a life of holiness and total devotion to
      God"

      Set-apart from the world, and drawing
      nearer to God.

      A life of discipline, focus, and attention
      to matters of righteous living.

      It is, as Paul states in Romans 12:1-2, a
      life fully presented to God in a way that
      transforms our lives to God's glory rather
      than conforming our lives to the ways of
      the world.

      Romans 12:1-2
        Therefore, I urge you, brothers and
        sisters, in view of God’s mercy, to
        offer your bodies as a living sacrifice,
        holy and pleasing to God—this is your
        true and proper worship. 2 Do not
        conform to the pattern of this world,
        but be transformed by the renewing of
        your mind. Then you will be able to test
        and approve what God’s will is—his good,
        pleasing and perfect will.
#+END_SRC

** Always pray
#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Ephesians 6:18
#+END_SRC

#+RESULTS:
#+begin_src text
Ephesians 6:18
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
With all prayer and petition pray at all times
in the Spirit, and with this in view, be on
the alert with all perseverance and petition
for all the saints,

(NASB)
#+end_src
