* =Pen.el= (a holy OS)
Pen.el is a free and holy OS based on emacs and debian.

It's free because it's both libre and gratis.
It's holy because:
- it's designed to be used by Christians who wish to maintain holiness in their computing
  - free from distraction
  - focused on God
  - reduce the cognitive dissonance when trying to remain focused on God while using a computer
  - support all areas of their Christian faith.
    - praying
    - praising
    - running churches and Bible-studies
    - maintaining holiness
  - integrates lots of Christian resources in a more powerful way than through websites

holiness
- set-apart for God

y:holiness

This project is purposed to support Christians with their
computing, including Bible-study, prayers, holiness, and otherwise just
enabling people to be focused on God, even while using a computer.

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  holiness
      The state of being holy.
      "a life of holiness and total devotion to
      God"

      Set-apart from the world, and drawing
      nearer to God.

      A life of discipline, focus, and attention
      to matters of righteous living.

      It is, as Paul states in Romans 12:1-2, a
      life fully presented to God in a way that
      transforms our lives to God's glory rather
      than conforming our lives to the ways of
      the world.

      Romans 12:1-2
        Therefore, I urge you, brothers and
        sisters, in view of God’s mercy, to
        offer your bodies as a living sacrifice,
        holy and pleasing to God—this is your
        true and proper worship. 2 Do not
        conform to the pattern of this world,
        but be transformed by the renewing of
        your mind. Then you will be able to test
        and approve what God’s will is—his good,
        pleasing and perfect will.
#+END_SRC

** Always pray
#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Ephesians 6:18
#+END_SRC

#+RESULTS:
#+begin_src text
Ephesians 6:18
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
With all prayer and petition pray at all times
in the Spirit, and with this in view, be on
the alert with all perseverance and petition
for all the saints,

(NASB)
#+end_src

#+BEGIN_SRC sh -n :sps bash :async :results none :lang text
  nem bible-search-pp pray | v
#+END_SRC

** Technical details
It runs as a docker container.

** Aims
The major aim of Pen.el is to be a holy
operating system, providing the user with free (but advanced) Bible study
software and trustworthy Christian resources that are all offline.

It's intended to be a self-sufficient computing environment, liberating the
user from the internet, and making it easier to maintain one's Christian faith by eliminating all the distractions,
yet being feature-full and fun.

# Included are all the benefits that come from using emacs.
# Pen.el is like an opinionated emacs distribution.

Pen.el is both an operating system and the Christian / Bible software that runs it.

Using Pen.el, there should be no need to go online, as it should contain everything you need to be content with your computing.
The Bible-software is indented to be as featureful as any of the other options available, but completely free, and also low maintenance.

It's also designed to be a Christian's operating system.

It's a project that has no forseeable expiry date.

** Intended users
- emacs/linux savvy pastors, chaplains
- theology students
- anyone wanting software that respects a user's desire to remain holy

** Quick installation
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  git clone "https://github.com/semiosis/pen.el"

  mkdir -p ~/.pen

  # Add the scripts to the PATH
  echo export PATH="$(realpath .)/pen.el/scripts:\$PATH" >> ~/.profile

  # Add this to prevent C-s from freezing the terminal
  echo "stty stop undef 2>/dev/null; stty start undef 2>/dev/null" | tee -a ~/.zshrc >> ~/.bashrc

  # Source your .profile
  . ~/.profile

  # Run pen
  pen
#+END_SRC
