;;; tracwiki-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tracwiki-mode.el

(autoload 'tracwiki-history-mode "tracwiki-mode" "\
History operation mode

(fn)" t)
(register-definition-prefixes "tracwiki-mode" '("trac"))

;;; End of scraped data

(provide 'tracwiki-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tracwiki-mode-autoloads.el ends here
