* Setup commands
** Setup and run scripts =@erik=
 https://gist.github.com/kinoc
 https://gist.github.com/kinoc/dca36b12b5e956688a9b92a87ba7c52c

** Model download
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  pip install "git+git://github.com/finetuneanon/transformers.git#egg=transformers"
  pip install gdown
  gdown "https://drive.google.com/uc?id=1VXXCMR_ETxOd3rxG4eXxS4-QA5NekB3H"
#+END_SRC

* TODO [#A] Set up the backend to GPT-j
$MYGIT/arrmansa/Basic-UI-for-GPT-J-6B-with-low-vram

https://drive.google.com/u/0/uc?id=1tboTvohQifN6f1JiSV8hnciyNKvj9pvm&export=download
$HOME/j6b_parts_ft_20210625.tar.gz

http://github.com/semiosis/pen.el/blob/master/scripts/gpt-j-complete.sh

** TODO Get someone to test it out

* Set up GPT-j
https://github.com/kingoflolz/mesh-transformer-jax/network/members

** TODO Mirror huggingface
$DUMP/programs/httrack/mirrors

$DUMP/programs/httrack/mirrors/https-huggingface-co-transformers-
$DUMP/programs/httrack/mirrors/https-transformer-huggingface-co-

** This worked for python3.8
https://github.com/finetuneanon/transformers

It's a fork of huggingface transformers with some new thing in it.

#+BEGIN_SRC sh -n :sps bash :async :results none
  msudo pip install "git+git://github.com/finetuneanon/transformers.git#egg=transformers"
#+END_SRC

*** I can check out the gpt-j branch
$MYGIT/finetuneanon/transformers

** This worked
#+BEGIN_SRC sh -n :sps bash :async :results none
  cd "$HOME"; gdown "https://drive.google.com/uc?id=1VXXCMR_ETxOd3rxG4eXxS4-QA5NekB3H"
#+END_SRC

=$HOME/neo_6b.tar=

So the neo_6b, is that j?

How do I use the tar file?

Look on huggingface for documentation.

Should I download the entire huggingface website and then search it?

** So now that I have it, what do I do with it?

