cd /root/.pen/documents/notes;  "prompts-details" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "prompts-details" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "prompts-details" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "prompts-details" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "prompts-details" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "prompts-details" "-csv" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "prompts-details" "-csv" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "prompts-details" "-csv" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "prompts-details" "-csv" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "prompts-details" "-csv" "#" "<==" "zsh"
