#!/bin/bash
export TTY

type="$@"

input_fp="$(cat | tf txt)"

cat "$input_fp" | sed "s/\\[\\[/\\n\\[\\[/g" | scrape "\\[\\[${type}.*\\](\\[.*\\])?\\]"
cat "$input_fp" | sed "s/\\[\\[/\\n\\[\\[/g" | scrape "\\[\\[${type}.*\\](\\[.*\\])?\\]"
