#!/bin/bash
export TTY

# This is for backquoting shell commands

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

# This certainly works
IFS= read -rd '' input < <(cat);typeset -p input &>/dev/null

if stdin_exists; then
    set -- "${input}" "$@"
fi

# But command substitution in cmd-nice-posix removes the trailing newlines
cmd-nice-posix "$@" | bs '$`'
