#!/bin/bash
export TTY

# This is for backquoting shell commands

. $SCRIPTS/lib/stdin_exists

# This certainly works
IFS= read -rd '' input < <(cat);typeset -p input &>/dev/null

if stdin_exists; then
    set -- "${input}" "$@"
fi

# But command substitution in cmd-nice-posix removes the trailing newlines
cmd-nice-posix "$@" | bs '$`'
