;;; org-static-blog-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-static-blog.el

(autoload 'org-static-blog-publish "org-static-blog" "\
Render all blog posts, the index, archive, tags, and RSS feed.
Only blog posts that changed since the HTML was created are
re-rendered.

With a prefix argument, all blog posts are re-rendered
unconditionally.

(fn &optional FORCE-RENDER)" t)
(autoload 'org-static-blog-publish-file "org-static-blog" "\
Publish a single POST-FILENAME.
The index, archive, tags, and RSS feed are not updated.

(fn POST-FILENAME)" t)
(autoload 'org-static-blog-create-new-post "org-static-blog" "\
Creates a new blog post.
Prompts for a title and proposes a file name. The file name is
only a suggestion; You can choose any other file name if you so
choose.

(fn &optional DRAFT)" t)
(autoload 'org-static-blog-create-new-draft "org-static-blog" "\
Creates a new blog draft.
Prompts for a title and proposes a file name. The file name is
only a suggestion; You can choose any other file name if you so
choose." t)
(autoload 'org-static-blog-mode "org-static-blog" "\
Blogging with org-mode and emacs.

(fn)" t)
(register-definition-prefixes "org-static-blog" '("concat-to-dir" "org-static-blog-"))

;;; End of scraped data

(provide 'org-static-blog-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-static-blog-autoloads.el ends here
