;;; addressbook-bookmark-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from addressbook-bookmark.el

(autoload 'addressbook-turn-on-mail-completion "addressbook-bookmark")
(autoload 'addressbook-bookmark-set-1 "addressbook-bookmark" "\
Add contact repetitively until user say no.

When CONTACT arg is provided add only contact CONTACT and exit.

(fn &optional CONTACT)")
(autoload 'addressbook-gnus-sum-bookmark "addressbook-bookmark" "\
Record an addressbook bookmark from a gnus summary buffer." t)
(autoload 'addressbook-mu4e-bookmark "addressbook-bookmark" "\
Record an addressbook bookmark from a mu4e view buffer." t)
(autoload 'addressbook-bmenu-edit "addressbook-bookmark" "\
Edit an addresbook bookmark entry from bmenu list." t)
(autoload 'addressbook-bookmark-jump "addressbook-bookmark" "\
Default handler to jump to an addressbook bookmark.

(fn BOOKMARK)")
(register-definition-prefixes "addressbook-bookmark" '("addressbook-"))

;;; End of scraped data

(provide 'addressbook-bookmark-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; addressbook-bookmark-autoloads.el ends here
