#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

IFS= read -r -d '' sh_code <<'HEREDOC'
cd /usr/local/share/vim/vim82/doc
grep -oRP "^:[^	]+	" | sed 's/^[^:]*::/:/' | cut -d "	" -f 1 | uniqnosort
HEREDOC

oci bash -c "$sh_code" | pavs