;;; hledger-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hledger-core.el

(register-definition-prefixes "hledger-core" '("hledger-"))


;;; Generated autoloads from hledger-defuns.el

(register-definition-prefixes "hledger-defuns" '("hledger-"))


;;; Generated autoloads from hledger-input.el

(register-definition-prefixes "hledger-input" '("hledger-"))


;;; Generated autoloads from hledger-mail.el

(autoload 'hledger-enable-reporting "hledger-mail" "\
Report every month on `hledger-reporting-day'.")
(register-definition-prefixes "hledger-mail" '("hledger-"))


;;; Generated autoloads from hledger-mode.el

(autoload 'hledger-company "hledger-mode" "\
Company backend for ‘hledger-mode’.
COMMAND, ARG and IGNORED the regular meanings.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(defvar hledger-mode-map (let ((map (make-keymap))) (define-key map (kbd "C-c C-i") 'hledger-append-clipboard-to-journal) (define-key map (kbd "C-c C-d") 'hledger-reschedule) (define-key map (kbd "C-c C-b") 'hledger-edit-amount) (define-key map (kbd "C-c C-p") 'hledger-backward-entry) (define-key map (kbd "C-c C-n") 'hledger-next-or-new-entry) (define-key map (kbd "RET") 'hledger-ret-command) (define-key map (kbd "<backtab>") 'hledger-backtab-command) map))
(autoload 'hledger-mode "hledger-mode" "\


(fn)" t)
(autoload 'hledger-view-mode "hledger-mode" "\


(fn)" t)
(register-definition-prefixes "hledger-mode" '("hledger-"))


;;; Generated autoloads from hledger-navigate.el

(register-definition-prefixes "hledger-navigate" '("hledger-"))


;;; Generated autoloads from hledger-reports.el

(autoload 'hledger-run-command "hledger-reports" "\
Run an hledger COMMAND.

(fn COMMAND)" t)
(register-definition-prefixes "hledger-reports" '("hledger-"))


;;; Generated autoloads from hledger-suggest.el

(register-definition-prefixes "hledger-suggest" '("hledger-suggest"))


;;; Generated autoloads from hledger-webservice.el

(register-definition-prefixes "hledger-webservice" '("hledger-"))

;;; End of scraped data

(provide 'hledger-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hledger-mode-autoloads.el ends here
