#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

example() {
    {
        date '+%B %d' --date='2 days ago'
        date '+%B %d' 
        date '+%B %d' --date='5 days ago'
        date '+%B %d' --date='1 day ago'
    } | visidata-sort-dates -d '%B %d'
}

example
