cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "spinner"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "spinner"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "spinner"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /dev/shm/ht-cache;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /dev/shm/ht-cache;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/.emacs.d/host/pen.el/src;  "lolcat" "#" "<==" "pen-pak"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/.emacs.d/host/pen.el/scripts;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/.emacs.d/host/pen.el/scripts;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
cd /root/repos/figlet-fonts;  "lolcat" "-f" "#" "<==" "penelfonts"
cd /root/notes;  "lolcat" "-f" "#" "<==" "pen-banner.sh"
