;;; helm-lsp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-lsp.el

(autoload 'helm-lsp-workspace-symbol "helm-lsp" "\
`helm' for lsp workspace/symbol.
When called with prefix ARG the default selection will be symbol at point.

(fn ARG)" t)
(autoload 'helm-lsp-global-workspace-symbol "helm-lsp" "\
`helm' for lsp workspace/symbol for all of the current workspaces.
When called with prefix ARG the default selection will be symbol at point.

(fn ARG)" t)
(autoload 'helm-lsp-code-actions "helm-lsp" "\
Show lsp code actions using helm." t)
(autoload 'helm-lsp-diagnostics "helm-lsp" "\
Diagnostics using `helm'

(fn ARG)" t)
(register-definition-prefixes "helm-lsp" '("helm-lsp-"))

;;; End of scraped data

(provide 'helm-lsp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-lsp-autoloads.el ends here
