#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

in-tty x -sh cli-chess \
    -e Online \
    -down \
    -e Create \
    -right \
    -down \
    -down \
    -e Top \
    -right \
    -down \
    -down \
    -down \
    -down \
    -down \
    -down \
    -down \
    -f1 \
    -i
