cd /root/.pen/documents/notes;  "Luke" "10:19" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Luke" "13:32-34" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "Luke" "12" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "Luke" "12:2-5" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Luke" "5:1" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Luke" "11:28" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Luke" "11:27-28" "#" "<==" "zsh"
