cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Rev" "1:17" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Rev" "19:16" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Rev" "1:7-8" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Rev" "3:21" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Rev" "5:13" "#" "<==" "zsh"
