;;; flymake-hledger-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-hledger.el

(autoload 'flymake-hledger-enable "flymake-hledger" "\
Enable checking the hledger journal in the current buffer." t)
(autoload 'flymake-hledger-check-buffer "flymake-hledger" "\
Start a hledger process on the current buffer and report to Flymake.
This function is meant to be added to `flymake-diagnostic-functions'.

REPORT-FN is Flymake's callback.

(fn REPORT-FN &rest _)")
(register-definition-prefixes "flymake-hledger" '("flymake-hledger-"))

;;; End of scraped data

(provide 'flymake-hledger-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-hledger-autoloads.el ends here
