;;; mu4e-alert-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mu4e-alert.el

(autoload 'mu4e-alert-set-default-style "mu4e-alert" "\
Set the default style for unread email notifications.

VALUE is the value to be used as the default style.

(fn VALUE)")
(autoload 'mu4e-alert-enable-mode-line-display "mu4e-alert" "\
Enable display of unread emails in mode-line." t)
(autoload 'mu4e-alert-enable-notifications "mu4e-alert" "\
Enable desktop notifications for unread emails." t)
(register-definition-prefixes "mu4e-alert" '("mu4e-alert-"))

;;; End of scraped data

(provide 'mu4e-alert-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mu4e-alert-autoloads.el ends here
