#!/bin/bash
export TTY

verbs=y
adjs=y
advs=y
nouns=y

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -n) {
        nouns=y
        shift
    }
    ;;

    -on) {
        verbs=n
        adjs=n
        advs=n
        nouns=y
        shift
    }
    ;;

    *) break;
esac; done

# . $SCRIPTS/lib/hs

if test -n "/usr/share/wordnet"; then
    : "${dir:="/usr/share/wordnet"}"
else
    test -d /root/repos/moos/wordnet-db || cd "$(gc "https://github.com/moos/wordnet-db")"
    dir=/root/repos/moos/wordnet-db/dict
fi

{
    test "$verbs" = y &&  cat1 "$dir/index.verb"
    test "$adjs"  = y &&  cat1 "$dir/index.adj"
    test "$advs"  = y &&  cat1 "$dir/index.adv"
    test "$nouns" = y &&  cat1 "$dir/index.noun"
} | sed "/^ /d" | cut -d ' ' -f 1 | tr _ ' ' | sort | uniq | pavs