#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

word="$1"

if test "$NOEMACS" = "y"; then
    "wordnet" "$word" "-over" "-synsn" "-synsv" "-synsa" "-synsr" "-simsv" "-antsn" "-antsv" "-antsa" "-antsr" "-famln" "-famlv" "-famla" "-famlr" "-hypen" "-hypev" "-hypon" "-hypov" "-treen" "-treev" "-coorn" "-coorv" "-derin" "-deriv" "-domnn" "-domnv" "-domna" "-domnr" "-domtn" "-domtv" "-domta" "-domtr" "-subsn" "-partn" "-membn" "-meron" "-hmern" "-sprtn" "-smemn" "-ssubn" "-holon" "-hholn" "-entav" "-framv" "-causv" "-perta" "-pertr" "-attrn" "-attra"
else
    e -e "(dictionary-search $(aqf-nice "$word"))"
fi

# /usr/bin/sdcv
# ifl define
