#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/dump/home/shane/notes/ws/blog/blog
#+HUGO_SECTION: ./posts

#+TITLE: Imaginary computing and virtual reality
#+DATE: <2021-09-13>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: gpt openai nlp imaginary pen imaginary

** Summary
I talk about the imaginary computing paradigm
based on LMs.

** Definitions
+ prompting :: The act of stoking a LM to perform a generation.

+ imagination :: The extrapolation of a language model's weights via prompting. The returned results of prompting.

Prompting pretrained LMs is a way to build
imaginary analogs to most software. It is for
this reason, that software may be defined
within only the imagination of a LM.
Therefore, we have a new computing paradigm
that may not be called 'virtual'.

+ virtual reality (wiki definition) :: A simulated experience that can be
    similar to or completely different from the real world. Applications of virtual
    reality include entertainment, education and business.

As you can see, in the above wiki definition, there is no mention of neural
networks, privacy and freedom. And there are strong indicators that virtual
reality is something which is constructed for you. Those are all key
differentiators to imaginary reality.

+ imaginary reality :: One distinction between imaginary and virtual reality is that
    virtual reality isn't really concerned so
    much with NNs for a lazily generated
    potential reality that is constructed as
    one's own mind prompts another through
    will. Also virtual reality is
    distinctively shared by others and
    engineered for agents to explore.
    Imaginary reality, on the other hand, is
    generated at will by a user and does not
    follow rules, nor is typically intended to
    be shared with others. Imaginary reality
    takes place within a walled garden of a
    single mind / imagination forming around
    another. The interpretation of the output
    of one mind/neural net as having been
    sensed and interpreted by another mind /
    NN, in real time.

+ pure imaginary reality :: This is one's personal introspective experience of
    their own imagination.

+ impure imaginary reality :: This is one's experience of another's
    imagination, whether that be another biological mind or a Neural Network.

** How does this affect =Pen.el=?
The imaginary internet and imaginary social
networks are becoming tangible, explorable and
interpretable.

=Pen.el= aims to give humans tools to make
sense of and interact in the imaginary
paradigm of computing.

There is a real distinction between virtual
and imaginary which must be made very clear,
to direct the evolution of =Pen.el= and associated projects.

Part of working in a new paradigm is the
necessity to form glossaries and ontologies
for naming functions and tools. Metaphor
historically has been a great tool for doing
this.

+ Cases in point:
  - Object-oriented programming
  - Microsoft Windows

** Imaginary analogs
*** Imaginary society
Glossary: