* TODO Continue trying to apply for jobs
- Build up a record of jobs which have been denied
  - To show Corrections

* TODO Consider asking Danish Delights for work

* 
e:$NOTES/ws/theology

* The LORD is One
#+BEGIN_SRC text -n :async :results verbatim code
  Deuteronomy 6:4: “ Hear, O Israel! The Lord is our God, the Lord is one!
  Deuteronomy 6:5: You shall love the Lord your God with all your heart and with all your soul and with all your might.
  Deuteronomy 6:6: These words, which I am commanding you today, shall be on your heart.
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  Mark 12:29: Jesus answered, “The foremost is, ‘  Hear, O Israel! The Lord our God is one Lord;
  Mark 12:30:  and you shall love the Lord your God with all your heart, and with all your soul, and with all your mind, and with all your strength.’
  Mark 12:31: The second is this, ‘ You shall love your neighbor as yourself.’ There is no other commandment greater than these.”
#+END_SRC

* John 5:24
#+BEGIN_SRC text -n :async :results verbatim code
  “Truly, truly, I say to you, the one who hears My word, and believes Him who
  sent Me, has eternal life, and does not come into judgment, but has passed out
  of death into life.
#+END_SRC

* A test can be a task or a trap
[[https://www.youtube.com/watch?v=sR4AT0LMJ5c][Why God Tests His People - YouTube]]

Well I just continue to submit to God and try to humble myself.

Please LORD God Most High and Jesus Christ my
King, my Saviour, my High Priest, and my God.

* Jesus is God, inasmuch as we are able to see, and God let the Fullness of Himself to dwell in Jesus
Now, it's fine to consider Jesus as God.
And it is healthy to do so.
Because to see God we look to Jesus.
Now I believe that truly.
The more I consider Jesus to be God, the faster I will come to knowledge of God the Father.

** Father God has sanctified (set apart as or declare holy; consecrate) Jesus Christ, then sent Him into the world
#+BEGIN_SRC text -n :async :results verbatim code
  John 10:36: Say ye of him, whom the Father hath sanctified, and sent into the world, Thou blasphemest; because I said, I am the Son of God?
#+END_SRC

** The status of Jesus Christ: Right hand of God
#+BEGIN_SRC text -n :async :results verbatim code
  Hebrews 1:1: God, after He spoke long ago to the fathers in the prophets in many portions and in many ways,
  Hebrews 1:2: in these last days has spoken to us in His Son, whom He appointed heir of all things, through whom also He made the world.
  Hebrews 1:3: And He is the radiance of His glory and the exact representation of His nature, and upholds all things by the word of His power. When He had made purification of sins, He sat down at the right hand of the Majesty on high,
  Hebrews 1:4: having become as much better than the angels, as He has inherited a more excellent name than they.
  Hebrews 1:5: For to which of the angels did He ever say,“  You are My Son, Today I have begotten You”? And again,“  I will be a Father to Him And He shall be a Son to Me”?
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  Hebrews 12:2: Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  I Peter 3:18: For Christ also died for sins once for all, the just for the unjust, so that He might bring us to God, having been put to death in the flesh, but made alive in the spirit;
  I Peter 3:19: in which also He went and made proclamation to the spirits now in prison,
  I Peter 3:20: who once were disobedient, when the patience of God kept waiting in the days of Noah, during the construction of the ark, in which a few, that is, eight persons, were brought safely through the water.
  I Peter 3:21: Corresponding to that, baptism now saves you-- not the removal of dirt from the flesh, but an appeal to God for a good conscience-- through the resurrection of Jesus Christ,
  I Peter 3:22: who is at the right hand of God, having gone into heaven, after angels and authorities and powers had been subjected to Him.
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  Acts 7:55: But he, being full of the Holy Ghost, looked up stedfastly into heaven, and saw the glory of God, and Jesus standing on the right hand of God,
  Acts 7:56: And said, Behold, I see the heavens opened, and the Son of man standing on the right hand of God.
  Acts 7:57: Then they cried out with a loud voice, and stopped their ears, and ran upon him with one accord,
  Acts 7:58: And cast him out of the city, and stoned him: and the witnesses laid down their clothes at a young man’s feet, whose name was Saul.
  Acts 7:59: And they stoned Stephen, calling upon God, and saying, Lord Jesus, receive my spirit.
  Acts 7:60: And he kneeled down, and cried with a loud voice, Lord, lay not this sin to their charge. And when he had said this, he fell asleep.
#+END_SRC

** Seven IAM statements
The Lord declared Himself to be God through His seven “I AM” statements.

- I am the bread of life. 6:35, 48, 51.
- I am the light of the world. 8:12; 9:5.
- I am the door of the sheep. 10:7, 9.
- I am the good shepherd. 10:11, 14.
- I am the resurrection and the life. 11:25.
- I am the way, the truth, and the life. 14:6.
- I am the true vine.

#+BEGIN_SRC text -n :async :results verbatim code
  John 6:35: And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst.
  John 8:58: Jesus said unto them, Verily, verily, I say unto you, Before Abraham was, I am.
  John 10:14: I am the good shepherd, and know my sheep, and am known of mine.
  John 10:36: Say ye of him, whom the Father hath sanctified, and sent into the world, Thou blasphemest; because I said, I am the Son of God?
  John 11:25: Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live:
  John 14:6: Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.
  John 15:1: I am the true vine, and my Father is the husbandman.
#+END_SRC

** Colossians 1:15-29
#+BEGIN_SRC text -n :async :results verbatim code
  Colossians 1:13: For He rescued us from the domain of darkness, and transferred us to the kingdom of His beloved Son,
  Colossians 1:14: in whom we have redemption, the forgiveness of sins.
  Colossians 1:15: He is the image of the invisible God, the firstborn of all creation.
  Colossians 1:16: For by Him all things were created, both in the heavens and on earth, visible and invisible, whether thrones or dominions or rulers or authorities-- all things have been created through Him and for Him.
  Colossians 1:17: He is before all things, and in Him all things hold together.
  Colossians 1:18: He is also head of the body, the church; and He is the beginning, the firstborn from the dead, so that He Himself will come to have first place in everything.
  Colossians 1:19: For it was the Father’s good pleasure for all the fullness to dwell in Him,
  Colossians 1:20: and through Him to reconcile all things to Himself, having made peace through the blood of His cross; through Him, I say, whether things on earth or things in heaven.
#+END_SRC

I guess then that God has ended the process of
creation by reconciling us to Him (God)
through Jesus?

** II Corinthians 4:6
#+BEGIN_SRC text -n :async :results verbatim code
  II Corinthians 4:6: For God, who said, “ Light shall shine out of darkness,” is the One who has shone in our hearts to give the Light of the knowledge of the glory of God in the face of Christ.
#+END_SRC

God who said Light shall shine out of darkness
is the One who enlightened us.

God shone in our hearts to reveal Himself in the face of Christ.

- Therefore, the more we look to Jesus Christ, and get an understanding of Jesus Christ, through the gospels, through His words,
  through doing what He commands, and through seeing God's glory as revealed in Jesus Christ, the more we see God.

Jesus Christ is so exalted that we see God through looking at Jesus.

# *** 
# Also, Jesus quotes Psalm 82 in saying that to those who the Word of God has come, they may be called =gods=, sons of the Most High.

# - My point being that Christ, being the image of the invisible God:

** John 10:28
Also, Jesus also chooses who he will give life to (bible verse somewhere)

#+BEGIN_SRC text -n :async :results verbatim code
  John 10:27: My sheep hear my voice, and I know them, and they follow me:
  John 10:28: And I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand.
  John 10:29: My Father, which gave them me, is greater than all; and no man is able to pluck them out of my Father’s hand.
  John 10:30: I and my Father are one.
#+END_SRC

** John 5:21
#+BEGIN_SRC text -n :async :results verbatim code
  John 5:21: For as the Father raiseth up the dead, and quickeneth them; even so the Son quickeneth whom he will.
#+END_SRC

** John 14:8-9
#+BEGIN_SRC text -n :async :results verbatim code
  John 14:8: Philip said to Him, “Lord, show us the Father, and it is enough for us.”
  John 14:9: Jesus said to him, “Have I been so long with you, and yet you have not come to know Me, Philip? He who has seen Me has seen the Father; how can you say, ‘ Show us the Father’?
  John 14:10: Do you not believe that I am in the Father, and the Father is in Me? The words that I say to you I do not speak on My own initiative, but the Father abiding in Me does His works.
  John 14:11: Believe Me that I am in the Father and the Father is in Me; otherwise believe because of the works themselves.
#+END_SRC

** John 20:17
#+BEGIN_SRC text -n :async :results verbatim code
  John 20:17: Jesus said to her, “Stop clinging to Me, for I have not yet ascended to the Father; but go to My brethren and say to them, ‘I ascend to My Father and your Father, and My God and your God.’”
#+END_SRC

** Psalms 35:23
#+BEGIN_SRC text -n :async :results verbatim code
  Psalms 35:23: Stir up Yourself, and awake to my right And to my cause, my God and my Lord. 
#+END_SRC

** John 20:28
#+BEGIN_SRC text -n :async :results verbatim code
  John 20:28: Thomas answered and said to Him, “My Lord and my God!”
#+END_SRC

Now because Jesus is one with God, Thomas can say this.

** John 20:31
#+BEGIN_SRC text -n :async :results verbatim code
  John 20:31: but these have been written so that you may believe that Jesus is the Christ, the Son of God; and that believing you may have life in His name.
#+END_SRC

* gods? - Jesus quotes this
- https://biblehub.com/text/psalms/82-1.htm

Psalm 82, which Jesus quotes, calls the people
in this congregation =gods=, sons of the Most
High, and says that the Most High is the one
who judges.

** John 10:34
#+BEGIN_SRC text -n :async :results verbatim code
  John 10:34: Jesus answered them, Is it not written in your law, I said, Ye are gods?
#+END_SRC

** 
#+BEGIN_SRC text -n :async :results verbatim code
  Psalms 82:1: God standeth in the congregation of the mighty; he judgeth among the gods. 
#+END_SRC

** Literal interpretation
#+BEGIN_SRC text -n :async :results verbatim code
  Psalms 82:1: God standeth in the congregation of the divine; he judgeth among God. 
#+END_SRC

** NASB
#+BEGIN_SRC text -n :async :results verbatim code
  Psalms 82:1: God takes His stand in His own congregation;He judges in the midst of the rulers.
#+END_SRC

** Psalms 82:1

#+BEGIN_SRC text -n :async :results verbatim code
  Psalms 82:6:I said, “ You are gods, And all of you are sons of the Most High. 
#+END_SRC

* God's character
** Psalms 9:10
And those who know Your name will put their
trust in You, For You, O Lord, have not
forsaken those who seek You.

** Psalms 103:13
Like as a father pitieth his children, so the Lord pitieth them that fear him.

* TODO Imitating Jesus, and following God's will
https://star.net.nz/the-word-for-today/what-you-werent-sent-to-do-2020_12_08

#+BEGIN_SRC text -n :async :results verbatim code
  Jesus said, 'As my Father has sent me, I also send you ' (John 20:21 NKJV)
#+END_SRC

(2) We were sent to do God's will, not our own.

#+BEGIN_SRC text -n :async :results verbatim code
  Jesus said, 'I have come...not to do my own will, but the will of him who sent me' (John 6:38 NKJV)
#+END_SRC

** We should do Jesus' will, actually, particularly because Jesus is our Lord
Jesus does His Father's will.
We do Jesus' will.
We can also do the will of the Father, Jesus' father, but first we must do what Jesus has commanded, I think.
