cd /root/.pen/documents/notes;  "2" "thessalonians" "2:7" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "2" "Corinthians" "12:8" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "2" "Corinthians" "12:7-8" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "2" "Timothy" "1:7-" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "2" "Timothy" "1:7-9" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "2" "Timothy" "1:7-10" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "2" "Corinthians" "3:9" "#" "<==" "zsh"
