#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# site="stackoverflow"
# while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
#     "") { shift; }; ;;
#     -u) {
#         site="askubuntu"
#         shift
#     }
#     ;;
# 
#     *) break;
# esac; done

CMD="$(cmd "$@")"
: ${CMD:="$(cmd "$@")"}

# sp -e "(sx-search-immediately $(aqf "$CMD") )"

# eval "sp -cip sx-search-immediately $CMD"

# eval "sp-ic sx-search-immediately $CMD"

query="$@"
sx-search-immediately-lang "$query"

# sp -e "(sx-search $(aqf "$site") $(aqf "$CMD") )"
# sp -e "(sx-search \"\" $(aqf "$CMD") )"