#!/bin/bash
export TTY

# docker-select-image | xargs -I{} bash -c 'docker save {} -o ~/{}.docker; echo saved to ~/{}.docker'

image="$(docker-select-image)"

slug="$(echo -n "$image" | slugify)"

docker save "$image" -o ~/$slug.docker.tar

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

# $SCRIPTS/merge-docker-save

if is_tty; then
    orogsp ~/$slug.docker.tar
else
    echo saved to ~/$slug.docker.tar
fi