#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

image_name="$1"
test -n "$image_name" || exit 1

slug="$(echo "$image_name" | tr -d '\n' | slugify)"

dffp="$HOME/dockerhub/Dockerfile_${slug}"

! test -f "$dffp" && elinks-dump-chrome "https://hub.docker.com/r/$image_name/dockerfile" | edm -m "V}}dGV{d" | tee "$dffp"

is_tty() { [ -t 1 ]; }

is_tty && vs "$dffp" || cat "$dffp"