;;; shr-tag-pre-highlight-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from shr-tag-pre-highlight.el

(register-definition-prefixes "shr-tag-pre-highlight" '("eww-display-html--override-shr-external-rendering-functions" "shr-tag-pre-highlight"))

;;; End of scraped data

(provide 'shr-tag-pre-highlight-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; shr-tag-pre-highlight-autoloads.el ends here
