#!/bin/bash
export TTY

# I have to detach the clients of the sessions

test -d "/root/.pen/tmp" && : "${TMPDIR:="/root/.pen/tmp"}"
test -d "/tmp" && : "${TMPDIR:="/tmp"}"

client="$(cat $TMPDIR/asciinema-client.txt)"
tmux detach-client -t "$client"