#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

test -f "/root/.local/bin/tmux" && : "${bin:="/root/.local/bin/tmux"}"
test -f "$HOME/local/bin/tmux" && : "${bin:="$HOME/local/bin/tmux"}"
test -f "/usr/bin/tmux" && : "${bin:="/usr/bin/tmux"}"
"$bin" "$@"
