* Law of Christ
#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Luke 8:21
#+END_SRC

#+RESULTS:
#+begin_src text
Luke 8:21
‾‾‾‾‾‾‾‾‾
But He answered and said to them, “My mother
and My brothers are these who hear the word of
God and do it.”

(NASB)
#+end_src

* TODO Make it so the Bible-mode buffers are renamed according to the Bible book, chapter and module

* TODO Talk to the Elders of Cornerstone
- Adson has suggested that I talk to the elders about the needs I have

When a person is baptised they are essentially married to Jesus.

** Faith is not without faithfulness
e:/volumes/home/shane/notes/ws/bible-studies/faith.org

The law of Christ is a covenant with Christ, and that law is faith in Christ which is faithful belief.
And the faithfulness involves love to Christ, which is following in His commandments, which is remaining in Him.
Now if a person believes God justifies the ungodly, but doesn't exercise faithfulness by following Christ's
commandments even when they are challenged then they are like the person in the parable who built his house on sand.
Can that so-called faith save? Their works may be all burned up but they may live, but that depends on whether there is any true
belief/faith in God remaining, but if a person gambled their eternal life by living an unfaithful life that they may lose their soul because their
belief may not save. It's up to God who He saves.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Romans 10:13-16
#+END_SRC

#+RESULTS:
#+begin_src text
Romans 10:13-16
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
for “Whoever will call on the name of the Lord
will be saved.” How then will they call on Him
in whom they have not believed?

How will they believe in Him whom they have
not heard?

And how will they hear without a preacher?

How will they preach unless they are sent?

Just as it is written, “How beautiful are the
feet of those who bring good news of good
things!” However, they did not all heed the
good news; for Isaiah says, “Lord, who has
believed our report?”

(NASB)
#+end_src

** Yes, an age-gap relationship is fine - I'd just need God to deliver it for me
God justifies the ungodly if we have faith in Him.
That means remaining faithful to Him.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Romans 4:19-22
#+END_SRC

#+RESULTS:
#+begin_src text
Romans 4:19-22
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Without becoming weak in faith he contemplated
his own body, now as good as dead since he was
about a hundred years old, and the deadness of
Sarah’s womb; yet, with respect to the promise
of God, he did not waver in unbelief but grew
strong in faith, giving glory to God, and
being fully assured that what God had
promised, He was able also to perform.

Therefore it was also credited to him as
righteousness.

(NASB)
#+end_src

** Pearl of Great Price - Jesus Christ then wife
e:/volumes/home/shane/notes/ws/bible-studies/pearl-of-great-price-Jesus-Christ.org

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  1 Corinthians 11:3
#+END_SRC

#+RESULTS:
#+begin_src text
1 Corinthians 11:3
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
But I want you to understand that Christ is
the head of every man, and the man is the head
of a woman, and God is the head of Christ.

(NASB)
#+end_src

** Following Jesus means working
#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Matthew 16:24-28
#+END_SRC

#+RESULTS:
#+begin_src text
Matthew 16:24-28
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Then said Jesus unto his disciples, If any man
will come after me, let him deny himself, and
take up his cross, and follow me.

For whosoever will save his life shall lose
it: and whosoever will lose his life for my
sake shall find it.

For what is a man profited, if he shall gain
the whole world, and lose his own soul?

or what shall a man give in exchange for his
soul?

For the Son of man shall come in the glory of
his Father with his angels; and then he shall
reward every man according to his works.

Verily I say unto you, There be some standing
here, which shall not taste of death, till
they see the Son of man coming in his kingdom.

(RLT)
#+end_src

** Hearing from God
#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  nasb James 3:17
#+END_SRC

#+RESULTS:
#+begin_src text
James 3:17
‾‾‾‾‾‾‾‾‾‾
But the wisdom from above is first pure, then
peaceable, gentle, reasonable, full of mercy
and good fruits, unwavering, without
hypocrisy.

(NASB)
#+end_src

** 
#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  nasb II John 1:9-11
#+END_SRC

#+RESULTS:
#+begin_src text
2 John 1:9-11
‾‾‾‾‾‾‾‾‾‾‾‾‾
Anyone who goes too far and does not abide in
the teaching of Christ, does not have God; the
one who abides in the teaching, he has both
the Father and the Son.

If anyone comes to you and does not bring this
teaching, do not receive him into your house,
and do not give him a greeting; for the one
who gives him a greeting participates in his
evil deeds.

(NASB)
#+end_src

I guess that I should not even give people a
greeting if they do not abide in the teaching
of Christ.

But I had spoken to Shibu about the teaching
of Christ and Shibu invited me into his
church.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  1 Corinthians 9:21
#+END_SRC

#+RESULTS:
#+begin_src text
1 Corinthians 9:21
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
To them that are without law, as without law,
(being not without law to God, but under the
law to Christ,) that I might gain them that
are without law.

(RLT)
#+end_src

This is a commandment:

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  bsb I John 4:21
#+END_SRC

#+RESULTS:
#+begin_src text
1 John 4:21
‾‾‾‾‾‾‾‾‾‾‾
And we have this commandment from Him: Whoever
loves God must love his brother as well.

(engbsb2020eb)
#+end_src

I am a bondservant of Jesus.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Romans 3:23
#+END_SRC

#+RESULTS:
#+begin_src text
Romans 3:23
‾‾‾‾‾‾‾‾‾‾‾
For all have sinned, and come short of the
glory of God;

(RLT)
#+end_src

We are under grace, yes.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  bsb Rom 6:14
#+END_SRC

#+RESULTS:
#+begin_src text
Romans 6:14
‾‾‾‾‾‾‾‾‾‾‾
For sin shall not be your master, because you
are not under law, but under grace.

(engbsb2020eb)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  I John 3:23-24
#+END_SRC

#+RESULTS:
#+begin_src text
1 John 3:23-24
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
And this is his commandment, That we should
believe on the name of his Son Jesus Christ,
and love one another, as he gave us
commandment.

And he that keepeth his commandments dwelleth
in him, and he in him.

And hereby we know that he abideth in us, by
the Spirit which he hath given us.

(RLT)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  nasb I John 3:13-15
#+END_SRC

#+RESULTS:
#+begin_src text
1 John 3:13-15
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Do not be surprised, brethren, if the world
hates you.

We know that we have passed out of death into
life, because we love the brethren.

He who does not love abides in death.

Everyone who hates his brother is a murderer;
and you know that no murderer has eternal life
abiding in him.

(NASB)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  bsb 1 Corinthians 9:21
#+END_SRC

#+RESULTS:
#+begin_src text
1 Corinthians 9:21
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
To those without the law I became like one
without the law (though I am not outside the
law of God but am under the law of Christ), to
win those without the law.

(engbsb2020eb)
#+end_src

Meeting yesterday, I feel as though Roly and Sam, if they were to excommunicate me from the church
then they would be pushing man's precepts / human laws onto me, which is even worse than making trying to put me under the Mosaic law.
The Mosaic law isn't bad. It's good. God's precepts are especially good.
But born-again Christians are under grace in the spirit of Christ, and are married / yoked to one another through Christ, bearing
one-another's burdens. We are under the law of Christ; we bear one another's burdens.
I have a burden.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  1 John 2:27
#+END_SRC

#+RESULTS:
#+begin_src text
1 John 2:27
‾‾‾‾‾‾‾‾‾‾‾
But the anointing which ye have received of
him abideth in you, and ye need not that any
man teach you: but as the same anointing
teacheth you of all things, and is truth, and
is no lie, and even as it hath taught you, ye
shall abide in him.

(RLT)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  I John 2:9
#+END_SRC

#+RESULTS:
#+begin_src text
1 John 2:9
‾‾‾‾‾‾‾‾‾‾
He that saith he is in the light, and hateth
his brother, is in darkness even until now.

(RLT)
#+end_src

** This is appropriate, too
[[sh:tpop nem II Corinthians 6]]

This chapter says a lot about being persecuted as a Christian.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  nasb II Corinthians 6:1-8
#+END_SRC

#+RESULTS:
#+begin_src text
2 Corinthians 6:1-8
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
And working together with Him, we also urge
you not to receive the grace of God in vain--
for He says, “At the acceptable time I
listened to you, And on the day of salvation I
helped you.” Behold, now is “the acceptable
time,” behold, now is “the day of salvation”--
giving no cause for offense in anything, so
that the ministry will not be discredited, but
in everything commending ourselves as servants
of God, in much endurance, in afflictions, in
hardships, in distresses, in beatings, in
imprisonments, in tumults, in labors, in
sleeplessness, in hunger, in purity, in
knowledge, in patience, in kindness, in the
Holy Spirit, in genuine love, in the word of
truth, in the power of God; by the weapons of
righteousness for the right hand and the left,
by glory and dishonor, by evil report and good
report; regarded as deceivers and yet true;

(NASB)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  nasb II Corinthians 6:14
#+END_SRC

#+RESULTS:
#+begin_src text
2 Corinthians 6:14
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Do not be bound together with unbelievers; for
what partnership have righteousness and
lawlessness, or what fellowship has light with
darkness?

(NASB)
#+end_src
