cd /root/.pen/documents/notes;  "Acts" "20:28" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "Acts" "2:38" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "Acts" "3:19" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "Acts" "3:19-20" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "Acts" "3:19-21" "#" "<==" "zsh"
