cd /root/notes;  "Acts" "28:28" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Acts" "26:17-18" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Acts" "22:21" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Acts" "14:27" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Acts" "8:12" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Acts" "19:8" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Acts" "20:25" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Acts" "28:31" "#" "<==" "zsh"
