#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

getpage() {
    page="$1"
    : "${page:="1"}"
    # meta-date elinks-dump ...
    elinks-dump "https://www.oneplace.com/ministries/insight-for-living/listen/?page=$page" | sed -e '0,/By Date/d' -e '/Previous Next/,$d' -e '/play-butto/d' | ved -gm IMG "ddA\\<C-v>\\<C-i>\\<C-c>Jj"
}

eval "$(meta-date)"
for i in $(seq 1 20); do
    getpage "$i" | awk 1
done | pavs

# 

# "https://www.oneplace.com/ministries/insight-for-living/listen/?page=1"
