#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

getpage() {
    page="$1"
    : "${page:="1"}"
    # meta-date elinks-dump ...
    # echo "$page" 1>&2
    paste \
        <(elinks-dump "https://www.oneplace.com/ministries/insight-for-living/listen/?page=$page" | sed -e '0,/By Date/d' -e '/Previous Next/,$d' -e '/play-butto/d' | ved -gm IMG "ddA\\<C-v>\\<C-i>\\<C-c>Jj") \
        <(elinks-dump -orefs "https://www.oneplace.com/ministries/insight-for-living/listen/?page=$page" | sed -e '0,/\/topics\//d' -e '/\/listen\/$/,$d' -e '/\/listen\/?/,$d' | uniqnosort | pavs)
}

eval "$(meta-date)"
eval "$(verbose-ci)"

for i in $(seq 1 20); do
    getpage "$i" | awk 1
done | pavs

# getpage 2 | awk 1 | pavs

# 

# "https://www.oneplace.com/ministries/insight-for-living/listen/?page=1"
