#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

dp=/volumes/home/shane/dump/programs/httrack/mirrors/https-www-desiringgod-org-/www.desiringgod.org/articles

cd "$dp"
htmls2txt
find . -name "*.html" | pavs

