;;; elfeed-autotag-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elfeed-autotag.el

(autoload 'elfeed-autotag "elfeed-autotag" "\
Setup auto-tagging rules." t)
(register-definition-prefixes "elfeed-autotag" '("elfeed-autotag-"))

;;; End of scraped data

(provide 'elfeed-autotag-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elfeed-autotag-autoloads.el ends here
