#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

pkg="$1"
test -n "$pkg" || exit 1

x -n -sh swipl -e "?- " -s "pack_install($pkg)." -c m -e "Y/n" -s Y -e "Create directory" -c m -e "?- " -c d -i