#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

. $SCRIPTS/lib/hs

# Example
# ocif curl "https://biblehub.com/interlinear/genesis/1-1.htm" | biblehub-interlinear-get-word-blocks-pipeline | sed '${/^$/d}' | ved-move-biblehub-interlinear-block-up

sed -z 's/\n\+$//' | ved -m "Gvipo\\<C-v>g_x{j\$lp" | sed -z "s/\n\\+$//"