cd /volumes/home/shane/notes/ws/problog/scratch;  "problog" "/volumes/home/shane/notes/ws/problog/scratch/noisy-or-coin.problog" "#" "<==" "pen-cr"
cd /root/.emacs.d/host/pen.el/src;  "problog" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "problog" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "problog" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "problog" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "problog" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "problog" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "problog" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "problog" "#" "<==" "bash"
