cd /root/.emacs.d/host/pen.el/scripts/container;  "node" "--version" "#" "<==" "zsh"
cd /root/.emacs.d/.cache/lsp/npm/vim-language-server/bin;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "#" "<==" "zsh"
cd /root/.emacs.d/.cache/lsp/npm/vim-language-server/bin;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "#" "<==" "zsh"
cd /root/notes;  "node" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "#" "<==" "zsh"
cd /root/notes;  "node" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "#" "<==" "vimls"
cd /root/.emacs.d/host/pen.el;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "#" "<==" "vimls"
cd /root/.emacs.d/host/pen.el;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "#" "<==" "vimls"
cd /root/.emacs.d/host/pen.el/scripts;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "--stdio" "#" "<==" "vimls"
cd /root/.emacs.d/host/pen.el;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "--stdio" "#" "<==" "vimls"
cd /root/.emacs.d/host/pen.el;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "--stdio" "#" "<==" "strace"
cd /root/.vim;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "--stdio" "#" "<==" "strace"
cd /root/.vim;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "--stdio" "#" "<==" "strace"
cd /root/.vim;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "--stdio" "#" "<==" "strace"
cd /root;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "--stdio" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el;  "node" "/root/.emacs.d/.cache/lsp/npm/vim-language-server/bin/vim-language-server" "--stdio" "#" "<==" "emacs"
