;;; path-headerline-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from path-headerline-mode.el

(defvar path-headerline-mode nil "\
Non-nil if Path-Headerline mode is enabled.
See the `path-headerline-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `path-headerline-mode'.")
(custom-autoload 'path-headerline-mode "path-headerline-mode" nil)
(autoload 'path-headerline-mode "path-headerline-mode" "\
Displaying file path on headerline.

This is a global minor mode.  If called interactively, toggle the
`Path-Headerline mode' mode.  If the prefix argument is positive,
enable the mode,  and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='path-headerline-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "path-headerline-mode" '("path-header-line-o" "ph--"))

;;; End of scraped data

(provide 'path-headerline-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; path-headerline-mode-autoloads.el ends here
