cd /root/.pen/documents;  "xdg-open" "/tmp/baca-09zlqoh4/index-3_1.jpg" "#" "<==" "baca"
cd /root/.pen/documents;  "xdg-open" "http://www.sacred-texts.com/bib/csj/csj046.htm" "#" "<==" "baca"
cd /root/.pen/documents;  "xdg-open" "http://www.sacred-texts.com/bib/csj/csj047.htm#fr_55" "#" "<==" "baca"
cd "/root/.pen/ebooks/John Schember/Quick Start Guide (2)";  "xdg-open" "https://manual.calibre-ebook.com" "#" "<==" "baca"
cd "/root/.pen/ebooks/John Schember/Quick Start Guide (2)";  "xdg-open" "https://manual.calibre-ebook.com/faq.html" "#" "<==" "baca"
cd "/root/.pen/ebooks/John Schember/Quick Start Guide (2)";  "xdg-open" "https://creativecommons.org/licenses/by-sa/4.0/deed.en_US" "#" "<==" "baca"
cd "/root/.pen/ebooks/John Schember/Quick Start Guide (2)";  "xdg-open" "https://manybooks.net/" "#" "<==" "baca"
cd "/root/.pen/ebooks/John Schember/Quick Start Guide (2)";  "xdg-open" "https://manual.calibre-ebook.com" "#" "<==" "baca"
cd /root/.pen/ebooks;  "xdg-open" "http://www.sacred-texts.com/bib/csj/csj012.htm" "#" "<==" "baca"
cd /root/.pen/ebooks;  "xdg-open" "http://www.sacred-texts.com/bib/csj/csj056.htm" "#" "<==" "baca"
