;;; helm-wordnet-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-wordnet.el

(autoload 'helm-wordnet-suggest "helm-wordnet" "\
Preconfigured `helm' for Dictionary lookup with Dictionary suggest." t)
(register-definition-prefixes "helm-wordnet" '("helm-wordnet"))

;;; End of scraped data

(provide 'helm-wordnet-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-wordnet-autoloads.el ends here
