;;; list-environment-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from list-environment.el

(autoload 'list-environment "list-environment" "\
List process environment in a tabulated view." t)
(register-definition-prefixes "list-environment" '("list-environment-"))

;;; End of scraped data

(provide 'list-environment-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; list-environment-autoloads.el ends here
