cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000001554" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87Jp+kyyB7Ez24Sij7x8F8L3j=fQk+ep7JE5SRuOxJQwcLg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAHf_wNJRCCgtYuWVyhJU_XToFLDdrVNFSN61M_S0X3Gw9SZ+Rw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000424c" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAD0RMY5X8P5D892wApiQgZXTice1Tz1E7VkmYdwXiZid80bBsw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:CAD0RMY5X8P5D892wApiQgZXTice1Tz1E7VkmYdwXiZid80bBsw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CAD0RMY5X8P5D892wApiQgZXTice1Tz1E7VkmYdwXiZid80bBsw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CACT87Johbb5vNv77of_jASbrDes0n91hea8uy69e+=o=YDU_Zg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:CACT87Johbb5vNv77of_jASbrDes0n91hea8uy69e+=o=YDU_Zg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CACT87Johbb5vNv77of_jASbrDes0n91hea8uy69e+=o=YDU_Zg@mail.gmail.com" "#" "<==" "emacs"
