cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003dcc" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAGRRG7WV12enttxESDRvAgQnDL3Mw12dqeJtd4W+Kzsm9q+ueA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CAGRRG7WV12enttxESDRvAgQnDL3Mw12dqeJtd4W+Kzsm9q+ueA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:CAGRRG7WV12enttxESDRvAgQnDL3Mw12dqeJtd4W+Kzsm9q+ueA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003d36" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CACT87JrgxLDYMY7L+x=-RmTShMkGo2cZhKh06ytzmt=XbFSphQ@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CACT87Jr1ZvbWE1h8zyc7qyYvBJTV8ki3s3FdTqt4FidXQamcNA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003e5c" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CANLS7uSPXaBALg7UgBaJLHc2wr3Yec57z9BXjOQfFn00Z9nheA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003e5c" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CANLS7uSPXaBALg7UgBaJLHc2wr3Yec57z9BXjOQfFn00Z9nheA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003df7" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=7" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=8" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=9" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=10" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=11" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=12" "--decrypt=true" "id:MEUPR01MB9383CDFBE6C8A0EB906F0E2CF6592@MEUPR01MB9383.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003e7d" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:7fd2e51da8e742740236d085b.a09104ac53.20240307034728.0d0d413a05.2150e560@mail144.atl241.mcsv.net" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003e7f" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:838c74247d76b2e16cd75a119.f0971fd6c4.20240307064927.51df8c104c.d9f353c9@mail148.suw12.mcsv.net" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003de8" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAND+YgqVNBwe3Y7EZoLGviGra1aDP7iAaHMOm2=c7_aj1gX3ww@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CAND+YgqVNBwe3Y7EZoLGviGra1aDP7iAaHMOm2=c7_aj1gX3ww@mail.gmail.com" "#" "<==" "emacs"
