cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--output=tags" "*" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "Mike Miller" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003cb4" "and (" "Mike Miller" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAP6sTSC+4MR2mDY-7uFeOFKzLYXaDMb4EKTAbA+TOtx35Y-ahQ@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JqK-=q2EDJehUdkM+a-oBCEUHTt1UW67_t2wi3PchgB0A@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAP6sTSA4_OxYxazZ1xQgBfXpVnzMC5vFU2iSEgh5Q8quCCVYbw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JoHcTfTJDQVR=G3ikqZj3HBW79qmbT9VWqPR2Md-NeroA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAP6sTSDhh=Fow+ifxKimySbfpaTv=RxA1iFd12aqWJ9pBrQudA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87Jr1fELchgO=zkwPRJ7aYmsD+8-Stx=eKomXdsD7HDk17w@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JoVKxXE_9w0E9NFxuNh9coYtP+Gf=UZzy66tEuV6t11+A@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAP6sTSD0=P1iv7vHEpHhqh=b09w8WzRJOHYjDNDFX8=EsLEXPQ@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003cb4" "and (" "Mike Miller" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAP6sTSC+4MR2mDY-7uFeOFKzLYXaDMb4EKTAbA+TOtx35Y-ahQ@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JqK-=q2EDJehUdkM+a-oBCEUHTt1UW67_t2wi3PchgB0A@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAP6sTSA4_OxYxazZ1xQgBfXpVnzMC5vFU2iSEgh5Q8quCCVYbw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JoHcTfTJDQVR=G3ikqZj3HBW79qmbT9VWqPR2Md-NeroA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAP6sTSDhh=Fow+ifxKimySbfpaTv=RxA1iFd12aqWJ9pBrQudA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87Jr1fELchgO=zkwPRJ7aYmsD+8-Stx=eKomXdsD7HDk17w@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003eac" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87Jr1DO6+4NGQtSx3_oad1YC2o6mmPaAaujaZnb82m=Y3fg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
