cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003b77" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=1" "--decrypt=true" "id:63.B1.16952.0A1A7A56@ib.mta1vrest.cc.prd.sparkpost" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003b6e" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrAfe_2hYgCg=yTUK0ZT+0YQdyA1g2EMdfB9E7Jhi+7Sw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrursTkrKwLjE3bUgQue+oaW=CbKHt0wy9Usp76vACMTQ@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87Jo_LL8ZSsJMYUMYiubVzhWrUXiF=QeE-smUxOAN0Z=REA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JqzDa6ozNEWqFp6sr5nvfocOZ8V_rNZKEtm4DCntzV6=w@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:e722439205e9418c95d1c56a0197db38@SYBPR01MB5824.ausprd01.prod.outlook.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JpMuBsKFpAAu+5DtTMgx3EknrWDs9cg7HWtLc2npYaSRQ@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000013d" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:ryu2UrpHGn056z3peIVpO0tCw5-a55_fAFV68JkUuTkwscsY38XoFCVG_O5wYcVmMfoM0Qf8uovKE578ZPViY0d2hB8vXnBb6nYTTzCVymE=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrRWMdApzqUORWgwMTTPZNYbrFgUfG5pN5one=Up=44Mw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JqOmsx0=9siaEsecknyg3pTL8F2KA6RMk8JdaXthRnM=g@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JruouVW9y5y7c7bmSN9sNBPxyyfO56B-v+X=WmQpA+JYQ@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:3de5wTGqMpkgDDXK-J2LM2etg2MP0CHL3ouEG4xj06ozaVTiZvCvzsT0i4UZAojdkaPrHEqwaFlUmfv2IYOHzBhIi6-tyezFH-vfnFnbG4M=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JqTt55hPEG4LKs9oFbG87kyaMJQU8fa9ojAgbCu-maT6A@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:A7YOi0ySkEu97LbhLEQCqBAQsWxbhxZHTOIndhxxcfcwUeMKEGihEhA4P4Iw4zUJZNfK352sa8eWeFpYG6aYDykROziA4msb8s-K7rkSajg=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87Jq79A9=enJ3tNzC5738ipob_Ae5sNVcEiZuu067r6KWdA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:IXlChsK7WwzIbk4TCd8YJF_EFoYDTTDASgbbP1-W1ZBnTJtk0CC4CDpbpl2oS-XLnFFhxFsoomvRy2dB-QyqzyRAcPFUOZ81KWEWiIGu1nU=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87Jqgc7b0LKW4L99p8w46mNJm5h5V9KOrjHu3B=6DbZb29Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:OEvdlrv-YI2bPlKEsfOa3ZvgqxuupaQghSN9bkp0192YJanp-wWcS6yV_jaXF8ncTjcV_x4d3L0UyYM9k_wUadSEPrPvtSG1_cxvznbnrxE=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JooLuqaU8iJT+8By0QoOJC5xL5945fa5LNn7Xz3-0BEDA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:Hygjf9TcZrLYQT6bG01LVmJ1m5k3EYZwAgSwkMdX05-8O9R4qWPfPuVngn2aA2slDKNNxFuG6PNFhiH2qOhOvfe7CCa7IOpUO-wOjoT6ecQ=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:pKPcKMRBrunPdB70i3sk5IE5ekiEJf1iSbUiJ54wXqs7Ms4aaGyZiVUAyeSG5gOGYJSh5EKEqv9Ew4oACIFzZFa_VV4hVJRNhcannHbuPd8=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87Jrawor5PW5FbF4trT0rSLGWTwM5PHNoEULNu8QX_HY-+g@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JqMA-sw6=VsRd__Y8Pri34LGivhNtuy_+Zd6NApDiEu=A@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:zd9VA7HCznSP_Quxj7P94-roGcN9QBgUZBi993ydKwqJrEZcD7OKc1E1ygfWatVHKVE-VShqDLPGasWVoIawwNVUj8GlBgkWtwkdSGaxAcw=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrQwUQXGw-QhPDeVswwXowuD5sHRVUDDxoUSt0=s49cLA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:74MxbvdfLy5WM1hjZNQCCEYei9JtRDr2CEQi_YHOM2saqM-Q1_OejlN23qY1s-Kdsqyeox9Vz7sjH-X02no2YlleGIuSBBZK0HLXp3LG7PI=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JqF3DdxJFkdzgAEoaUVyaY45O73eY9ZsiSyVa1wm45+iA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:HyJoKZOeQq4mzdzlXdc9ubsDdWLjgWzIwtQPy7okcEOCYPa9tJTECyZ6Pvs3Pl7mzNy8Ut_zB-T6RlGRpKLWkPrzQ4G4OWRFXiza3czwgjo=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:jmdEoLQGjM53ByNBIl5C6MK4g0z-MHhrgNNF2BHQkAMocJblRoSKXTUPApQVUgX3UoivmQLOdwgQ7fH6SyYIL-TUmsDCQrw1ONeMKhBus14=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JpPt9um5X5T4EJyB3+_pztkTJEy_nW7taf0ZYEAH8e2cw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
