cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000396e" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:MAp0VO4Mq6MK--_1S6PEk9Rm_HfbTIyc7QfthDGuawyD83UcXEXl-wLrg8NxtBjGH6ry5IIKkM-kiSoYbcOEUEomTwygYFJgSfDVbF8OC1M=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000396e" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:MAp0VO4Mq6MK--_1S6PEk9Rm_HfbTIyc7QfthDGuawyD83UcXEXl-wLrg8NxtBjGH6ry5IIKkM-kiSoYbcOEUEomTwygYFJgSfDVbF8OC1M=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000395c" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAHRRK8oyXcJxTK6NVaZMV7Q5EGUgWcp311CRNP3NepDTxDx7SA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrGRiUGrBnGd0zP8Y0SJMcYYDHZV65nHN_SFBWSqAWbvA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000395c" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAHRRK8oyXcJxTK6NVaZMV7Q5EGUgWcp311CRNP3NepDTxDx7SA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrGRiUGrBnGd0zP8Y0SJMcYYDHZV65nHN_SFBWSqAWbvA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000395c" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CAHRRK8oyXcJxTK6NVaZMV7Q5EGUgWcp311CRNP3NepDTxDx7SA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrGRiUGrBnGd0zP8Y0SJMcYYDHZV65nHN_SFBWSqAWbvA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003971" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:010f018c7951aba1-9587fc26-4623-4428-8f83-feb0f46c911b-000000@us-east-2.amazonses.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "Way Up prayer requests" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000038f3" "and (" "Way Up prayer requests" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CANLS7uTkKRJL3H-E5M2z2zJSy=wuZ9-5oxUVx95CQGQ-gjgQww@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "Way Up prayer requests" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000038f3" "and (" "Way Up prayer requests" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CANLS7uTkKRJL3H-E5M2z2zJSy=wuZ9-5oxUVx95CQGQ-gjgQww@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "config" "get" "user.name" "#" "<==" "emacs"
cd /root;  "notmuch" "config" "get" "user.primary_email" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "id:CANLS7uTkKRJL3H-E5M2z2zJSy=wuZ9-5oxUVx95CQGQ-gjgQww@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000038f3" "and (" "Way Up prayer requests" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CANLS7uTkKRJL3H-E5M2z2zJSy=wuZ9-5oxUVx95CQGQ-gjgQww@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "Way Up prayer requests" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003974" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:cm.0500082331138.tijdllhl.npiigjui.r@cmail20.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000396e" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:MAp0VO4Mq6MK--_1S6PEk9Rm_HfbTIyc7QfthDGuawyD83UcXEXl-wLrg8NxtBjGH6ry5IIKkM-kiSoYbcOEUEomTwygYFJgSfDVbF8OC1M=@protonmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000003974" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:cm.0500082331138.tijdllhl.npiigjui.r@cmail20.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000395a" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=2" "--decrypt=true" "id:0101018c6f277150-dd9b274f-c514-49f2-970c-57feb9979b1b-000000@us-west-2.amazonses.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000391a" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAC=A7PAzx=sD5BSUkf41Nk3jr4xDyhi+uLfNanTbM6rcuNkzzw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CAC=A7PAzx=sD5BSUkf41Nk3jr4xDyhi+uLfNanTbM6rcuNkzzw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CAC=A7PAzx=sD5BSUkf41Nk3jr4xDyhi+uLfNanTbM6rcuNkzzw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "FGBMFI Weekly Devotional" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000391a" "and (" "FGBMFI Weekly Devotional" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAC=A7PAzx=sD5BSUkf41Nk3jr4xDyhi+uLfNanTbM6rcuNkzzw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CAC=A7PAzx=sD5BSUkf41Nk3jr4xDyhi+uLfNanTbM6rcuNkzzw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000000021" "and (" "FGBMFI Weekly Devotional" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAC=A7PCTuSrm27SzDtzAzYkv1vHYKYUacgw8qdNNYnGRyJEYHQ@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CAC=A7PCTuSrm27SzDtzAzYkv1vHYKYUacgw8qdNNYnGRyJEYHQ@mail.gmail.com" "#" "<==" "emacs"
