cd /root;  "notmuch" "config" "get" "user.primary_email" "#" "<==" "emacs"
cd /root;  "notmuch" "count" "--exclude=false" "#" "<==" "emacs"
cd /root;  "notmuch" "count" "--exclude=true" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--output=tags" "*" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000004169" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:q1A45CTGEZqo4e1QwNhIIfPrFm9gmtQmizZRpB5uw7pWS0Lz7GaQqmvlAV82wcgQihV-qoWZoxHRTdP9OMeht5lLSah32mjOooQvBqEDCYcVExs0VFC0xWOroIJnXVEbRXsOQ3kAAQIA@t1.msgid.quoramail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000004169" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:q1A45CTGEZqo4e1QwNhIIfPrFm9gmtQmizZRpB5uw7pWS0Lz7GaQqmvlAV82wcgQihV-qoWZoxHRTdP9OMeht5lLSah32mjOooQvBqEDCYcVExs0VFC0xWOroIJnXVEbRXsOQ3kAAQIA@t1.msgid.quoramail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000004155" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:000000000000416f" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:mid-1713528900414e96897881054@email.biblestudytools.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000004171" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:ST7oMmosR0Gd3glvklBk-g@geopod-ismtpd-0" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000004176" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAGRRG7XtYbnpC5P4H4nkV1kXYb54Q8SKEXxj26UVA43BH7Axag@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAGRRG7XwGQdW4MpC0zNE9sU-pUTTPnaG3H-GRvBXEwdjnCma+w@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000004177" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:BD59W8o1C-UsGyf4hdehpPYwccVDfdAwMGz12RKbxx8XPLUgaCvdByqZHZsLuXYu5nc12LbPMLM1JISk3J8nw48baHdIc4TNVLcgn8evkkdnuaCR3m79jnrHYLyxJt1VYNV8K9iLcG5SEFolJ-c6AAECAA==@t1.msgid.quoramail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
