cd /root;  "notmuch" "count" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--body=false" "--format=sexp" "--format-version=5" "--sort=newest-first" "--entire-thread" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "count" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--body=false" "--format=sexp" "--format-version=5" "--sort=newest-first" "--entire-thread" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "reply" "--format=sexp" "--format-version=5" "--duplicate=1" "--decrypt=true" "--reply-to=sender" "id:NXS5LyHmSg6_guAxheCv7g@geopod-ismtpd-35" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:NXS5LyHmSg6_guAxheCv7g@geopod-ismtpd-35" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "id:CACT87JrJkb_PEhv_mQGvFTDrSE5w2bokQuub+qFn+-TXnG23Tw@mail.gmail.com" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrJkb_PEhv_mQGvFTDrSE5w2bokQuub+qFn+-TXnG23Tw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=1" "--decrypt=true" "id:trinity-087a1e8c-bd02-4cff-92e0-93728ed500dd-1703060648469@3c-app-mailcom-bs07" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=2" "--decrypt=true" "id:CACT87JrJkb_PEhv_mQGvFTDrSE5w2bokQuub+qFn+-TXnG23Tw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "id:CACT87JrJkb_PEhv_mQGvFTDrSE5w2bokQuub+qFn+-TXnG23Tw@mail.gmail.com" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CACT87JrJkb_PEhv_mQGvFTDrSE5w2bokQuub+qFn+-TXnG23Tw@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=1" "--decrypt=true" "id:trinity-087a1e8c-bd02-4cff-92e0-93728ed500dd-1703060648469@3c-app-mailcom-bs07" "#" "<==" "emacs"
cd /root;  "notmuch" "count" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--body=false" "--format=sexp" "--format-version=5" "--sort=newest-first" "--entire-thread" "tag:inbox" "#" "<==" "emacs"
