cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000049af" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CABLce4sw668tyW3Lgt0KyhP2AwNJgcKRJxUWZVY3LFd8bFD_DA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000049af" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CABLce4sw668tyW3Lgt0KyhP2AwNJgcKRJxUWZVY3LFd8bFD_DA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000049ae" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CABLce4vYWYfmZQRvzwA6odu1gTcB4ZcLiyY-rCFn8915VBdzdA@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000049ad" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=3" "--decrypt=true" "id:CABLce4sLMQ2_wu82GRW1Bv+6eH4nWNUgQXQE3=8ivBuWV=7U-w@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000049ac" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=7" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=8" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=7" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=8" "--decrypt=true" "id:CABLce4scsOMcy4rAiSiE8eiZvVOo_GgcV6L82dpoR0MecddDDg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:00000000000049ab" "and (" "tag:inbox" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CABLce4sU6X8-5opbqapBgDKFfhjNBv4YWBCb1x75SsKEuPmBLg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CABLce4sU6X8-5opbqapBgDKFfhjNBv4YWBCb1x75SsKEuPmBLg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:CABLce4sU6X8-5opbqapBgDKFfhjNBv4YWBCb1x75SsKEuPmBLg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=7" "--decrypt=true" "id:CABLce4sU6X8-5opbqapBgDKFfhjNBv4YWBCb1x75SsKEuPmBLg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "tag" "--batch" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CABLce4sU6X8-5opbqapBgDKFfhjNBv4YWBCb1x75SsKEuPmBLg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:CABLce4sU6X8-5opbqapBgDKFfhjNBv4YWBCb1x75SsKEuPmBLg@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "tag:inbox" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--output=tags" "*" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "letter" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--output=tags" "*" "#" "<==" "emacs"
cd /root;  "notmuch" "search" "--format=sexp" "--format-version=5" "--sort=newest-first" "judge" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=sexp" "--format-version=5" "--decrypt=true" "--exclude=false" "'" "thread:0000000000004484" "and (" "judge" ")" "'" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=4" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=5" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=6" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=7" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=8" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=9" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=10" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=11" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
cd /root;  "notmuch" "show" "--format=raw" "--part=12" "--decrypt=true" "id:CAJ9OOE2c=qpSxy_Sv5a0ZuWQO1WLgpi59Y4QOeFWFcWbboM4=Q@mail.gmail.com" "#" "<==" "emacs"
