cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "-e" "5" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "-e" "5" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "--excited" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "--bye" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "--excited" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "--excited" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "--excited" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "#" "<==" "zsh"
cd /root/repos/davidelettieri/sample-racket-language;  "runracketscript" "use-language.rkt" "#" "<==" "zsh"
cd /root/repos/davidelettieri/sample-racket-language;  "runracketscript" "use-language.rkt" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/myscript.rkt" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/use-racket-language.rkt" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/use-language.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/use-racket-language.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/use-racket-language.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "-e" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "-b" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscript" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/excitedness.rkt" "-b" "#" "<==" "zsh"
