cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ff" "https://www.youtube.com/watch?v=Vz8X_Ndnwl4"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ff" "https://www.youtube.com/watch?v=MEYSRQCfIHc&ab_channel=DesiringGod"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ff" "https://www.youtube.com/watch?v=MEYSRQCfIHc&ab_channel=DesiringGod"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ff" "https://www.youtube.com/watch?v=MEYSRQCfIHc&ab_channel=DesiringGod"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ff" "https://www.youtube.com/watch?v=MEYSRQCfIHc&ab_channel=DesiringGod"
