cd /root/.pen/documents/notes;  "ff" "https://boxbase.org/entries/2020/may/18/diy-io-monad/"
cd /root/.pen/documents/notes;  "ff" "https://boxbase.org/entries/2020/may/18/diy-io-monad/"
cd /root/.pen/documents/notes;  "ff" "https://boxbase.org/entries/2020/may/18/diy-io-monad/"
cd /root/.pen/documents/notes;  "ff" "https://boxbase.org/entries/2020/may/18/diy-io-monad/"
cd /;  "ff" "https://boxbase.org/entries/2020/may/18/diy-io-monad/"
cd /;  "ff" "https://boxbase.org/entries/2020/may/18/diy-io-monad/"
