cd /root/notes;  "ff" "prolog consult"
cd /root/notes;  "ff" "prolog make fact inside swipl repl"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20make%20fact%20inside%20swipl%20repl%22"
cd /root/notes;  "ff" "prolog make fact inside swipl repl"
cd /root/notes;  "ff" "prolog make fact inside swipl repl"
cd /root/notes;  "ff" "prolog make fact inside swipl repl"
cd /root/notes;  "ff" "prolog consult"
cd /root/notes;  "ff" "prolog consult"
cd /root/notes;  "ff" "prolog consult"
cd /root/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=\"prolog consult\""
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=\"prolog consult\""
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20make%20fact%20inside%20swipl%20repl%22"
cd /root/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20make%20fact%20inside%20swipl%20repl%22"
cd /root/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20make%20fact%20inside%20swipl%20repl%22"
cd /root/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22"
cd /root/.emacs.d/host/pen.el/config;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=vnoremap"
cd /root/.emacs.d/host/pen.el/config;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=vnoremap"
cd /root/.emacs.d/host/pen.el/src;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%3Aaround"
cd /root/.pen/documents/notes;  "ff" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=vim%20ssh%20scp%20save"
