cd /root/.emacs.d/host/pen.el/scripts/jstate;  "jstate-del" "a" "AA" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/jstate;  "jstate-del" "a" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/jstate;  "jstate-del" "a" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/jstate;  "jstate-del" "a" "#" "<==" "zsh"
cd /root/notes;  "jstate-del" "a" "#" "<==" "zsh"
cd /root/notes;  "jstate-del" "9" "#" "<==" "zsh"
cd /root/notes;  "jstate-del" "9" "#" "<==" "zsh"
cd /root/notes;  "jstate-del" "9" "#" "<==" "zsh"
cd /root/notes;  "jstate-del" "a" "#" "<==" "zsh"
