cd /root/.pen/documents/notes;  "timeit" "ssh" "-i" "~/.pen/host_key" "-o" "ControlMaster=auto" "-o" "ControlPath=~/ssh-controlpath-%r@%h:%p" "-o" "UserKnownHostsFile=/dev/null" "-o" "StrictHostKeyChecking=no" "-t" "shane@agia" "bash -l -c \"cd \\\"$HOME/.pen/documents/notes\\\"; . ~/.profile; export TERM=screen-256color; \\\"hello-world\\\"\"" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "ssh" "-i" "~/.pen/host_key" "-o" "ControlMaster=auto" "-o" "ControlPath=~/ssh-controlpath-%r@%h:%p" "-o" "UserKnownHostsFile=/dev/null" "-o" "StrictHostKeyChecking=no" "-t" "shane@agia" "bash -l -c \"cd \\\"$HOME/.pen/documents/notes\\\"; . ~/.profile; export TERM=screen-256color; \\\"hello-world\\\"\"" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "ssh" "-i" "~/.pen/host_key" "-o" "ControlMaster=auto" "-o" "ControlPath=~/ssh-controlpath-%r@%h:%p" "-o" "UserKnownHostsFile=/dev/null" "-o" "StrictHostKeyChecking=no" "-t" "shane@agia" "bash -l -c \"cd \\\"$HOME/.pen/documents/notes\\\"; . ~/.profile; export TERM=screen-256color; \\\"hello-world\\\"\"" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "timeit" "pen-cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
