;;; ess-r-insert-obj-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ess-r-insert-obj.el

(autoload 'ess-r-insert-obj-dt-name "ess-r-insert-obj" "\
Insert name of data.frame-like object." t)
(autoload 'ess-r-insert-obj-col-name "ess-r-insert-obj" "\
Insert column/variable name.

If called with a prefix, prompt for a data.frame-like object to search in.

With two \\[universal-argument] prefixes (i.e., when `current-prefix-arg' is (16)),
prompt for a data.frame-like object to search in." t)
(autoload 'ess-r-insert-obj-col-name-all "ess-r-insert-obj" "\
Insert names of all column/variable name.

If called with a prefix, prompt for a data.frame-like object to search in.

With two \\[universal-argument] prefixes (i.e., when `current-prefix-arg' is (16)),
prompt for a data.frame-like object to search in." t)
(autoload 'ess-r-insert-obj-value "ess-r-insert-obj" "\
Insert variable value.

If called with a prefix, prompt for a data.frame-like object or
column/variable to search in.

With a \\[universal-argument] prefix (i.e., when `current-prefix-arg' is (4)),
prompt for a column/variable object to search in.
With two \\[universal-argument] prefixes (i.e., when `current-prefix-arg' is (16)),
prompt for a data.frame-like object to search in." t)
(autoload 'ess-r-insert-obj-value-all "ess-r-insert-obj" "\
Insert all variable values.

If called with a prefix, prompt for a data.frame-like object or
column/variable to search in.

With a \\[universal-argument] prefix (i.e., when `current-prefix-arg' is (4)),
prompt for a column/variable object to search in.
With two \\[universal-argument] prefixes (i.e., when `current-prefix-arg' is (16)),
prompt for a data.frame-like object to search in." t)
(register-definition-prefixes "ess-r-insert-obj" '("ess-r-insert-obj-"))

;;; End of scraped data

(provide 'ess-r-insert-obj-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ess-r-insert-obj-autoloads.el ends here
