#!/bin/bash
export TTY

function displaytime {
  local T=$1
  local D=$((T/60/60/24))
  local H=$((T/60/60%24))
  local M=$((T/60%60))
  local S=$((T%60))
  (( $D > 0 )) && printf '%d days ' $D
  (( $H > 0 )) && printf '%d hrs ' $H
  (( $M > 0 )) && printf '%d min ' $M
  # (( $D > 0 || $H > 0 || $M > 0 )) && printf 'and '
  printf '%d sec\n' $S
}

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    awk1 | while IFS=$'\n' read -r line; do
        (
            exec 0</dev/null
            displaytime "$line"
        )
    done
else
    displaytime "$@"
fi
