;;; org-wc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-wc.el

(autoload 'org-word-count "org-wc" "\
Report the number of words in the Org mode buffer or selected region.

Ignores heading lines, blocks, comments, drawers, and links
depending on customizable variables in customization group org-wc.

LaTeX macros are counted as 1 word. 

(fn BEG END)" t)
(autoload 'org-wc-count-subtrees "org-wc" "\
Count words in each subtree, putting result as the property :org-wc on that heading." t)
(autoload 'org-wc-display "org-wc" "\
Show subtree word counts in the entire buffer.
With prefix argument, only show the total wordcount for the buffer or region
in the echo area.

Use \\[org-wc-remove-overlays] to remove the subtree times.

Ignores: heading lines,
         blocks,
         comments,
         drawers.
LaTeX macros are counted as 1 word.

(fn TOTAL-ONLY)" t)
(autoload 'org-wc-remove-overlays "org-wc" "\
Remove the occur highlights from the buffer.
BEG and END are ignored.  If NOREMOVE is nil, remove this function
from the `before-change-functions' in the current buffer.

(fn &optional BEG END NOREMOVE)" t)
(register-definition-prefixes "org-wc" '("org-w"))

;;; End of scraped data

(provide 'org-wc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-wc-autoloads.el ends here
