cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "/root/.emacs.d/host/pen.el/docs/theology/faith-and-judgement.tex" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "/root/.emacs.d/host/pen.el/docs/theology/faith-and-judgement.tex" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "latex-bookify" "/root/.emacs.d/host/pen.el/docs/theology/faith-and-judgement.tex" "#" "<==" "zsh"
cd /root/notes/ws/chemistry/reports;  "latex-bookify" "diagrams.tex" "#" "<==" "pdflatex"
cd /root/notes/ws/chemistry/reports;  "latex-bookify" "diagrams.tex" "#" "<==" "pdflatex"
