#!/bin/bash
export TTY

# I think that this program is useful for when there might be multiple different operations per line
# based on different information (machers) on each line.
# And a lot of dense information.
# But generally, I don't think it's going to improve my productivivty very much.
# And I think solutions would generally be better built in emacs.
# Also, I'd like to have ways of building new modes in emacs ultra quickly, like the term mode generator.

. $SCRIPTS/lib/hs
. $SCRIPTS/lib/stdin_exists

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/rat" || go install "github.com/ericfreese/rat@latest" &>/dev/null

# Examples:
# cd "$PENELD"; rat -m git.log -c 'git log --oneline --decorate --graph'
# cd "$PENELD"; rat -m git.refs -c 'git branch'
# cd "$PENELD"; rat -m git.status -c 'git status --short -uall'

if ! stdin_exists && test "$#" = 0; then
    # Either of these work to put it into default mode
    # exec < <(echo)
    # set -- --cmd=true "$@"

    # set -- --cmd="welcome-to-rat | tv" "$@"

    # Interestingly this script needs to be instant or will not appear.

    # Run it in advance
    fp="$(upd ocif -otf welcome-to-rat)"

    # The cache makes the symptoms go away.
    set -- --cmd="cat $fp" "$@"
# else
#     input_fp="$(cat | tf txt)"
#     exec < <(cat "$input_fp")
fi

# NO_NVC=y
# USE_PAGER=y

if test "$1" == "-h" || test "$1" == "--help"; then
    DO_HELP=y
fi

if test "$NO_NVC" = "y"; then
    if test "$USE_PAGER" = "y"; then
        if test "$DO_HELP" = "y"; then
            unbuffer ${GOPATH%%:*}/bin/rat "$@" | pavs
        else
            ${GOPATH%%:*}/bin/rat "$@" | pavs
        fi
    else
        ${GOPATH%%:*}/bin/rat "$@"
    fi
else
    nvc -2 ${GOPATH%%:*}/bin/rat "$@"
fi
