#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# https://www.biblegateway.com/passage/?search=Romans+6%3A23&version=ESV

biblegatewayify_bible_ref() {
    ref="$1"
    ref_encoded="$(printf -- "%s" "$ref" | biblegateway-canonicalise-ref | pen-urlencode)"
    echo "[[https://www.biblegateway.com/passage/?search=${ref_encoded}&version=ESV][$ref]]"
}

# newline
IFS="
"
awk 1 | while IFS="$IFS" read -r line; do
    (
        exec 0</dev/null
        biblegatewayify_bible_ref "$line"
    )
done
