#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

first_term="$1"
shift

otherterms="$@"
otherterms="$(printf -- "%s" "$otherterms" | sed 's/ /\.*/g')"

bible-search -l -m NASB "$first_term" | grep -P "$otherterms" | pavs
