#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -m) {
        module="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${module:="NASB"}"

# scrape-bible-references | 

s join ";" |
    xargs "diatheke" "-b" "$module" "-o" "w" "-f" "plain" "-k" |
    sed -z 's/\([0-9]:\) *\n/\1 /g' | sed 's/^\s*//' | pavs
