#!/bin/bash
export TTY

# Do it twice
sed -e 's/\([a-z]\)\./\1 /' -e 's/\./:/' |
    sed -e 's/\([a-z]\)\./\1 /' -e 's/\./:/' |
    sed 's/\([0-9]*[A-Z][a-z]\+ [0-9]\+:\)\([0-9]\+\)-\1\(.*\)/\1\2-\3/' |
    cat
    # canonicalise-bible-ref


