#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

bibleorgify_bible_ref() {
    ref="$1"
    ref_encoded="$(printf -- "%s" "$ref" | biblegateway-canonicalise-ref | pen-urlencode)"
    echo "[[bible:$ref][$ref]]"
}

# newline
IFS="
"
awk 1 | while IFS="$IFS" read -r line; do
    (
        exec 0</dev/null
        bibleorgify_bible_ref "$line"
    )
done
