#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# https://www.biblegateway.com/passage/?search=Romans+6%3A23&version=ESV

bibleorgify_strongs_code() {
    ref="$1"
    # TODO Also do some cleanup, such as removing asterisks from for example (H539 *'aman*)

    word="$(p "$ref" | sed 's/([GHgh][0-9]*\.\? \(.*\))/\1/')"
    ref="$(p "$ref" | sed 's/(\([GHgh][0-9]*\)\.\? .*)/\U\1/')"

    word="$(p "$word" | sed 's/\*//g')"
    echo "[[strongs:${ref}][($ref $word)]]"
}

# newline
IFS="
"
awk 1 | while IFS="$IFS" read -r line; do
    (
        exec 0</dev/null
        bibleorgify_strongs_code "$line"
    )
done
