#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

book="$(db-bible-book-list| sort -R | head -n 1)"
chapter="$(( 1 + $RANDOM % "$(db-bible-book-max-chapter "$book")" ))"
verse="$(( 1 + $RANDOM % "$(db-bible-book-chapter-max-verse "$book" "$chapter")" ))"

echo "$book $chapter:$verse" | pavs
