#!/bin/bash
export TTY

. $SCRIPTS/lib/hs
. $SCRIPTS/lib/stdin_exists

# Example:
# ocif curl "https://biblehub.com/interlinear/genesis/1-1.htm" | biblehub-interlinear-get-word-blocks-pipeline

# grep -q "Strong's Hebrew"
# grep -q "Strong's Greek"

if stdin_exists; then
    input_fp="$(tf txt)"
else
    url="$1"
    if ! test -n "$url"; then
        exit 1
    fi
    input_fp="$(ocif curl "$url" | tf txt)"
fi

if cat "$input_fp" | grep -q -P "Strong's Hebrew"; then
    : "${lang:="H"}"
elif cat "$input_fp" | grep -q -P "Strong's Greek"; then
    : "${lang:="G"}"
fi
: "${lang:=""}"

exec 0</dev/null

ub -E "$(cmd elinks-dump "$input_fp") | cat" | sed -z "s/   [0-9]\\+\\n\\n[0-9]\\+   /\\n/" | sed -z "s/1\\n\\n/\\n/" | tv |
    sed "s/   [0-9]\\+$//g" | sed "s/ / /g" |
    erase-trailing-whitespace | sed -e 's/^\s*//' | sed "s/ \\[e\\]$//" |
    sed "s/ \\+/ /g" | 
    ved "-m" "V/Click for Chapter\\<CR>ddd/IFrame\\<CR>VGd" |
    sed "/^ \\+$/{s/^.*$//}" | sed '/INS::INS/,$d' |
    erase-trailing-whitespace |
    sed 's/^[0-9]\+ \([^ ]\)/\1/' |
    sed 's/^\[e\] //' |
    sed "s/^\\([0-9]\\)/${lang}\\1/" |
    pen-aatr -k "\n\n" "fill-lines-to-longest-line" | max-double-spaced.sh | sed -z 's/\n\+$//' | 
    {
        if test "$ONELINED" = "y"; then
            pen-aatr -k "\n\n" "biblemode-onelineify-interlinear-block" | sed '/^$/d'
        else
            cat
        fi
    } | pavs
#  | make-all-lines-same-length