#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

sn="$(basename -- "$0")"

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    input="$(cat)"
    arg="$(printf -- "%s" "$input" | s join ' ')"
    set -- "$@" "$arg"

    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}

    unbuffer sph "$sn" -nem "$@"
    printf -- "%s" "$input"
    exit
fi

if ! inside-docker-p && docker-running-p; then

    if is_tty; then
        in-pen in-tm "$sn" "$@"
    else
        in-pen "$sn" "$@"
    fi

    exit "$?"
fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -g) {
        getverses=y
        shift
    }
    ;;

    -j) {
        getverses=n
        shift
    }
    ;;

    -m) {
        module="$2"
        shift
        shift
    }
    ;;

    -nem) {
        export NOEMACS=y
        shift
    }
    ;;

    -l) {
        searchtype=lucene
        shift
    }
    ;;

    *) break;
esac; done

: "${module:="NASB"}"
: "${searchtype:="phrase"}"
: "${getverses:="y"}"

# phrase search is much better
# : "${searchtype:="lucene"}"

query="$@"

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty && ! test "$NOEMACS" = y; then
    # pen-e -cip bible-search-lucene "$query" "$module"
    # pen-e -cip bible-search-phrase "$query" "$module"
    pen-e -cip bible-search "$query" "$module" "$searchtype"
else
    # phrase / lucene
    in-pen oci "diatheke" "-b" "$module" "-s" "$searchtype" "-o" "w" "-f" "phrase" "-k" "$query" |
        sed 's/^[^-]*-- //' | sed 's/ --.*//' | sed 's/ ; /\n/g' | sed '1{s/\([0-9]\)\([A-Z]\)/\1\n\2/}' | {
        if test "$getverses" = "y"; then
            bible-show-verses -m "$module" | cat
        else
            sed -z 's/\n$//'
        fi
    } | pavs
fi
