#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# . $SCRIPTS/lib/hs

sn="$(basename -- "$0")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -b|-book) {
        book="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    awk 1 | while IFS=$'\n' read -r module; do
        0</dev/null "$sn" "$module"
    done
    exit "$?"
fi

module="$@"

module="$(p "$module" | tr '[:upper:]' '[:lower:]')"
case "$module" in
    nasb) {
        module=NASB
    }
    ;;

    rlt) {
        module=RLT
    }
    ;;

    asv) {
        module=ASV
    }
    ;;

    maori) {
        module=Maori
    }
    ;;

    murdock) {
        module=Murdock
    }
    ;;

    irish|gaelic) {
        case "$book" in
            Mark) { module=ScotsGaelic; } ;;
            Matthew|John) { module=ManxGaelic; } ;;
            *|Luke) { module=IriODomhnuill; } ;;
        esac
    }
    ;;

    kjv) {
        module=KJV
    }
    ;;

    bsb) {
        module=engbsb2020eb
    }
    ;;

    *) {
        module="$(pen-rc-get default_bible_module)"
    }
    ;;

esac

echo "$module"
