#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    set -- "$(cat)" "$@"
fi

book="$1"
test -n "$book" || exit 1

cife "cife \"sqlite3 /root/.pen/refs.db 'select \\\`From Verse\\\` from refstable' | sed 's/\\\..*//' | uniqnosort\" | paste-stdin wrlp cif canonicalise-bible-book-title" | tsv-get -r "$book"
