#!/bin/bash
export TTY

# set -xv

: "${TMPDIR:="/root/.pen/tmp"}"
: "${TMPDIR:="/tmp"}"
export TMPDIR

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

# set -a # export the functions and variables

if ! test -n "$BORDER"; then
    if test "$EMACS_BABEL" = "y"; then
        set -- -nbd "$@"
    else
        set -- -bd "$@"
    fi
fi

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }
istty="$?"

is_stdout_pipe() { [[ -p /dev/stdout ]]; }
isstdoutpipe="$?"

if { ! test "$istty" = 0; } && { ! test "$isstdoutpipe" = 0; }; then
    # e.g. (pen-snc "1John")
    in-pen unbuffer xt in-tm "$sn" "$@" & disown
    exit "$?"
fi

if ! inside-docker-p && docker-running-p; then
    # Testing against the output pipe is necessary
    # Or this on host would not work: Romans 3:21-26 | cat
    if test "$istty" = 0 && { ! test "$isstdoutpipe" = 0; }; then
        in-pen in-tm "$sn" "$@"
    else
        in-pen "$sn" "$@"
    fi

    exit "$?"
fi

if test "$FAST" = "y"; then
    if test "$sn" = ebible; then
        module=NASB
    fi
    : "${module:="NASB"}"
else
    module="$(0</dev/null ocif canonicalise-bible-module "$sn")"
    : "${module:="NASB"}"
fi

format=plain

: "${BORDER:="y"}"
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -ttp) {
        USE_TTP=y
        shift
    }
    ;;

    -s) {
        SEARCH=y
        shift
    }
    ;;

    -bd) {
        BORDER=y
        shift
    }
    ;;

    -nbd) {
        BORDER=
        shift
    }
    ;;

    -cac) {
        format=internal
        CONCORDANCE=all
        CODES=y
        shift
    }
    ;;

    -codes) {
        : "${CONCORDANCE:="y"}"
        CODES=y
        shift
    }
    ;;

    -n) {
        VERSE_NUMBERS=y
        shift
    }
    ;;

    -c) {
        format=internal
        CONCORDANCE=y
        shift
    }
    ;;

    -ca) {
        format=internal
        CONCORDANCE=all
        shift
    }
    ;;

    -nem) {
        NOEMACS=y
        shift
    }
    ;;

    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    -m) {
        module="$2"
        shift
        shift
    }
    ;;

    -nottp) {
        USE_TTP=n
        shift
    }
    ;;

    *) break;
esac; done

if test "$ANNOTATED" = n; then
    format=plain
    CONCORDANCE=
elif test -n "$ANNOTATED"; then
    format=internal
    CONCORDANCE="$ANNOTATED"
fi

: "${USE_TTP:="y"}"

doublespacemax () {
    sed 's/\s\+$//' | sed ':a;N;$!ba;s/\n\n\+/\n\n/g'
}

if test "$SEARCH" = "y"; then
    bible-search -m "$module" -g "$@"
    exit "$?"
fi

# Remove quotes (don't use cmd)
: ${CMD:="$@"}

ref="$CMD"
: "${ref:="Genesis 1"}"

if ! test "$FAST" = "y"; then
    ref="$(echo "$ref" | cif canonicalise-bible-ref)"
fi

: "${maybemod:="$(printf -- "%s\n" "$ref" | sed -n '/(.*)/s/.*(\([^)]\+\)).*/\1/p')"}"
if test -n "$maybemod"; then
    module="$maybemod"
    ref="$(printf -- "%s\n" "$ref" | sed 's/ *(.*//')"
else
    : "${maybemod:="$(printf -- "%s\n" "$ref" | sed -n '/[0-9] [a-zA-Z]\+$/s/.* \([a-zA-Z]\+\)$/\1/p')"}"
    if test -n "$maybemod"; then
        module="$maybemod"
        ref="$(printf -- "%s\n" "$ref" | sed 's/ *[a-zA-Z]\+$//')"
    fi
fi

strongs_cmd=strongs-get-word
if test "$CONCORDANCE" = "all"; then
    strongs_cmd="strongs-get-word -f"
fi

IFS= read -r -d '' pipeline <<'HEREDOC'
    {
    if test "$FAST" = "y"; then
        echo "$ref" | udl
    else
        echo "$ref" | openbible-canonicalise-ref | udl
    fi
    {
    in-pen "diatheke" "-b" "$module" "-o" "w" "-f" "$format" "-k" "$ref" | sed 's/^.* [0-9]\+:[0-9]\+: *//' | pen-s remove-trailing-whitespace | sed '/^$/d' |
        if test "$CONCORDANCE" = "y" || test "$CONCORDANCE" = "all"; then
            sed -e 's/<w savlm="strong:\([^"]*\)">\([^<]*\)<\/w>/\2 \1/g' -e 's/\bstrong://g' |
            sed 's/<[^>]*>//g' |
            patm -r "[HG][0-9]+[a-z]?" "echo -n ✓; $strongs_cmd | tr '[:lower:]' '[:upper:]'" |
            sed 's/\( ✓\)\+\([^(]\)/\2/g' | sed 's/✓//g'
        else
            cat
        fi
    } | {
        if test "$USE_TTP" = "y"; then
            ttp
        else
            cat
        fi
    }
    } | sed '$s/\( *\)\(([^)]\+)\)$/\n\n\n\2/' | doublespacemax | {
        if test "$BORDER" = "y"; then
            sed 's/^/| /'
        else
            cat
        fi
    }
    # | pen-s remove-trailing-whitespace | pen-s join ' ' | sed 's/[0-9]: /&\n/g' | sed '/^$/d' | awk 'NR%2==0' | pavs
HEREDOC

# TODO Cache this pipeline
# I can also cache pipelines with the new pipe utility pipexec (for certain cases, anyway)
if is_tty && ! test "$NOEMACS" = y; then
    if test "$1"; then
        sp -cip bible-open =nil =nil "$module" "$ref"
    else
        sp -cip bible-open =nil =nil "$module"
    fi
else
    assignments="$(printf -- "%s\n" "$pipeline" | getvars -eval-pp)"
    assignments="$(eval "$assignments" | s join " ")"
    export -f doublespacemax
    output="$(ocif bash -c "$assignments $pipeline")"
    printf -- "%s\n" "$output" | pa -E "tf -sha txt | xa colvs -nls -num"
    # printf -- "%s\n" "$output" | pavs
fi
