#!/bin/bash
export TTY

# This works for:
# - openbible
# - biblegateway

canonicalise-bible-ref |
    sed -e 's/^III /3 /' -e 's/^II /2 /' -e 's/^I /1 /' \
        -e 's/Revelation of John/Revelation/'
