#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    io_fp="$(cat | tf txt)"
else
    io_fp="$(0</dev/null tf txt)"
fi

case "$sn" in
    canonicalise-bible-book-title.els) {
        fun_name=bible-canonicalise-ref-internal
    }
    ;;

    list-bible-book-titles-els) {
        fun_name=list-bible-book-titles-lines
    }
    ;;

    *) {
        fun_name="$sn"
    }
    ;;
esac

pen.els "$fun_name" "$io_fp" "$@" 2>/dev/null
ret="$?"

{
printf -- "%s" "$(cat "$io_fp")"
rm -f "$io_fp"
}

exit "$ret"
