cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-p-" "-O" "localhost" "#" "<==" "pen-n-list-open"
cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-p-" "-O" "localhost" "#" "<==" "pen-n-list-open"
cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-p-" "-O" "localhost" "#" "<==" "spin"
cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-p-" "-O" "localhost" "#" "<==" "spin"
cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-p-" "-O" "localhost" "#" "<==" "spin"
cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-p-" "-O" "localhost" "#" "<==" "spin"
cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-p-" "-O" "localhost" "#" "<==" "spin"
cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-p" "9845" "-O" "localhost" "#" "<==" "spin"
cd /root/.emacs.d/host/pen.el/src;  "nmap" "-sT" "-F" "-O" "localhost" "#" "<==" "spin"
cd /root/notes;  "nmap" "-sT" "-p" "9845" "-O" "localhost" "#" "<==" "spin"
cd /root/notes;  "nmap" "-sT" "-F" "-O" "localhost" "#" "<==" "spin"
