;;; docker-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from docker-compose.el

 (autoload 'docker-compose "docker-compose" nil t)
(register-definition-prefixes "docker-compose" '("docker-compose-"))


;;; Generated autoloads from docker-container.el

 (autoload 'docker-container-eshell "docker-container" nil t)
 (autoload 'docker-container-find-directory "docker-container" nil t)
 (autoload 'docker-container-find-file "docker-container" nil t)
 (autoload 'docker-container-shell "docker-container" nil t)
 (autoload 'docker-container-shell-env "docker-container" nil t)
 (autoload 'docker-container-vterm "docker-container" nil t)
 (autoload 'docker-container-vterm-env "docker-container" nil t)
 (autoload 'docker-containers "docker-container" nil t)
(register-definition-prefixes "docker-container" '("docker-container-"))


;;; Generated autoloads from docker-context.el

 (autoload 'docker-contexts "docker-context" nil t)
(register-definition-prefixes "docker-context" '("docker-context-"))


;;; Generated autoloads from docker-core.el

 (autoload 'docker "docker" nil t)
(register-definition-prefixes "docker-core" '("docker-"))


;;; Generated autoloads from docker-image.el

 (autoload 'docker-image-pull-one "docker-image" nil t)
 (autoload 'docker-images "docker-image" nil t)
(register-definition-prefixes "docker-image" '("docker-"))


;;; Generated autoloads from docker-network.el

 (autoload 'docker-networks "docker-network" nil t)
(register-definition-prefixes "docker-network" '("docker-network-"))


;;; Generated autoloads from docker-process.el

(register-definition-prefixes "docker-process" '("docker-"))


;;; Generated autoloads from docker-utils.el

(register-definition-prefixes "docker-utils" '("docker-"))


;;; Generated autoloads from docker-volume.el

 (autoload 'docker-volume-dired "docker-volume" nil t)
 (autoload 'docker-volumes "docker-volume" nil t)
(register-definition-prefixes "docker-volume" '("docker-volume-"))

;;; End of scraped data

(provide 'docker-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; docker-autoloads.el ends here
