cd /root/.pen/documents/notes;  "I" "John" "3:4" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "I" "Peter" "1:23-24" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "I" "Peter" "1:23-25" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "I" "Peter" "1:22-25" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "I" "Peter" "1:22-25" "#" "<==" "zsh" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "I" "Peter" "1:22-25" "#" "<==" "zsh"
