cd /root/.pen/documents/notes;  "I" "Corinthians" "15:58" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "I" "Corinthians" "2:12" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "I" "John" "2:15" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "I" "John" "2:14-18" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "I" "John" "2:14-19" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "I" "Corinthians" "6:9" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "I" "Corinthians" "6:9-10" "#" "<==" "zsh"
