cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "I" "Thessalonians" "3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "I" "John" "2:9" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "I" "John" "1:9" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "I" "John" "1:9" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "I" "John" "1:9" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "I" "Thessalonians" "3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "I" "Thessalonians" "3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "I" "Thessalonians" "3-5" "#" "<==" "bash"
