* Breaking Spiritual Gang-Stalking Prayer

Many people struggle with being pursued and
attacked by demons, humans out of body both
living and dead, and other entities that are
difficult to classify.

In some cases, entire teams of human agents
are at work against an individual’s life.

This is *especially true when a person comes
from a situation where they choose Jesus as
opposed to an evil mandate or office they were
appointed to by the powers of darkness* and/or
within their bloodline.

Gang stalking in the spirit can be executed by
ancestors, both living and dead, and by other
cult members, in addition to demons and other
entities (such as spirit children, clones,
hybrid spirits, synthetic spirits, and
composite entities).

This prayer will provide you with the language
to execute a heavenly court case to shut down
the activity.

** Prayer

Father in heaven, I come before you in the
mighty name of Jesus Christ and I declare that
your word says to come boldly before your
throne of grace to find mercy and grace to
help in time of need.

Lord, I have been pursued by my enemies which
lay claim to my life, and I am seeking a
judgment in my favour that will empower me to
walk out my mandates in Christ Jesus.

I call for a court to be set and I petition
Jesus Christ to provide the angels of the Lord
with the coordinates of my enemies which are
pursuing me to destroy me, to cause me to turn
from your truth, to control me, distract me,
or to detour me.

I pray that the angels of the Lord would use
the net of the Lord, and any other
technologies necessary, to capture those that
pursue me, for I call them indicted and I
summon them into the court of heaven now in
the name of Jesus Christ.

(Wait to perceive those that are brought into
the court before proceeding.)

I ask that all hidden documents, covenants,
contracts, agreements, certificates, oaths,
and vows that have been signed by me or any
part of me including what I will henceforth
identify as “the group”: clones, holograms,
merfolk, twins, copies, duplicates, replicas,
derivatives, walk-ins, parents, spouse(s), or
ancestors assigning legal rights to those that
persecute me, be produced for the court now.

I call for them to be weighed in the scales of
justice.

I invalidate every binding document that has
been fraudulently created or established
against me based on agreements obtained by me
or any part of me or “the group” under duress.

I furthermore invalidate every binding
document implicating me or any part of me or
“the group” executed by lying spirits that did
not fulfil their end of the bargain.

I repent for and renounce the creation of all
other documents that are left on behalf of me,
my parts, and “the group”.

I now call for the blood of Jesus to stamp
every document that has been presented before
the court empowering those that pursue and
persecute me.

I call for them to be nailed to the cross of
Jesus Christ and to be burned in his consuming
fire.

I call for all of the following elements that
have been used as access points to my life in
both the natural and the spirit to be
presented before the court and subsequently
burned with the fire of God: hair,
fingernails, blood samples, saliva, other
sources of DNA, cursed objects, fecal matter,
urine, evil sacred trees, ritual altars,
covenantal rings, heirlooms, tracking devices,
tridents, consent forms, and technologies.

I agree to specifically address anything else
that you require of me, Holy Spirit, that
would otherwise keep me bound to my
persecution.

Bring to the front of my mind any specific
agreements or sins I need to lay down now.

(Speak and verbally lay down any specific
issues the Holy Spirit brings to your
attention, even if you don’t fully understand.

Confess, repent for, and renounce everything
the Holy Spirit brings up.

If God reveals parts or alters doing ungodly
things, claim them as your humanity, forgive
them, repent for their sins, speak over them
remission of sins, renounce their works, call
them fired from their job, and call for the
angels of the Lord to escort these parts
before Jesus Christ for his redemption and
ministry.)

To those that have been summoned into the
court, I declare that my season of persecution
at your hands is now over.

It is written that as a man sows, so shall he
reap.

It is written that whoever destroys this
temple, the Lord will destroy.

In keeping with protocol, I separate human and
partially-human agents from non-human agents
within the court.

To the human and partially-human agents, I
offer up the gospel of Jesus Christ.

#+BEGIN_QUOTE
  Jesus Christ is the Son of God and the
  Creator.
  
  He is the firstborn among many brethren.
  
  He was born of a virgin, he died for our sins,
  and was raised again to life on the third day.
  
  He has ascended on high where he is seated at
  the right hand of the Father and ever lives to
  make intercession for the saints.
  
  He is the payment for our sins, and should you
  choose him, you will be justified freely by
  grace through the redemption that is found in
  him.
  
  His suffering will atone for your sins.
  
  If you do not choose him, you will receive in
  your own members the judgement for your sins
  and impropriety.
#+END_QUOTE

Choose now.

I pray Lord God, that as they make their
decisions, your stream of living water flows
through the courtroom to separate out humanity
from those that exist as composite entities.

I pray that your sword would sever devices,
demons, blinders, artificial intelligence,
programs, holographic technologies, quantum
interfaces, and other defilements that would
otherwise inhibit a decision for Jesus to be
made by those present in the court, thus
revealing the true conviction of their
humanity and not the instruments of their
bondage.

Lord I appeal to you to judge and judge
justly, and to have your angels escort those
that have not chosen Jesus and all non-human
agents to the place determined for them, such
that they cannot any longer take or receive
assignments against me to destroy my life and
deviate me from my heavenly mandates.

I furthermore establish an automation on my
freedom such that every reset is overcome in
accordance with this judgment.

In this, I declare complete freedom and
autonomy for my body (respiratory system,
digestive system, cardiovascular system, renal
system, endocrine system, nervous system,
musculoskeletal system, exocrine system,
glymphatic system, lymphatic system, immune
system, and sexual system) soul, spirit,
heart, decisions, worship, destiny, offices,
business, and relationships.

I praise you now for freedom, newness of life,
and empowerment from you, Holy Spirit.

I thank you for setting me free and I pray
that barricades would now be set up preventing
all attempts at retaliatory efforts.

In doing so I activate your Word on behalf of
my life and the lives of my loved ones.

I declare, Lord God, that you are my shield,
buckler, rear guard, strong tower, and
fortress.

I put my trust and faith in you, Lord Jesus.

I seal this prayer to a realm of timelessness
and anchor it to every realm, age, timeline,
dimension, planet, cosmos and universe, past,
present, and future, to infinity, and from the
beginning, across eternity.

Amen.
