# This docker-compose file is for future versions of Pen.el and is not needed to run it currently

version: "3.9"
services:
  pen:
    image: semiosis/pen.el:latest
    # Add mosh and ssh? - not possible/easy with docker containers.
    ports:
      # web interface
      - "7681:7681"
  semantic:
    image: "docker.pkg.github.com/github/semantic/semantic:latest"
    restart: always
  duckling:
    image: rasa/duckling:0.1.6.5
    restart: always
    ports:
      - 8000:8000
  # docker pull returntocorp/semgrep:latest
  semgrep:
    image: returntocorp/semgrep:latest
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: datahike
      POSTGRES_PASSWORD: clojure
      POSTGRES_DB: "pg-example"
    ports:
      - "5437:5432"
    volumes:
      - /tmp/datahike_example/data:/var/lib/postgresql/data
  # spacy-services:
  #   # $OPENSEMS/docker-compose.yml
  #   image: opensemanticsearch/spacy-services
  #   restart: always
  #   build:
  #     context: src/spacy-services.deb/src/spacy-services/