;;; flycheck-nimsuggest-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-nimsuggest.el

(add-hook 'nimsuggest-mode-hook 'flycheck-nimsuggest-setup)
(autoload 'flycheck-nimsuggest-start "flycheck-nimsuggest" "\
Start nimsuggest’s ‘chk’ method syntax check with CHECKER.

CALLBACK is the status callback passed by Flycheck.

(fn CHECKER CALLBACK)")
(autoload 'flycheck-nimsuggest-setup "flycheck-nimsuggest" "\
Setup flycheck configuration for nimsuggest.")
(register-definition-prefixes "flycheck-nimsuggest" '("flycheck-nimsuggest-"))

;;; End of scraped data

(provide 'flycheck-nimsuggest-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-nimsuggest-autoloads.el ends here
