#!/bin/bash
export TTY

# export UPDATE=y

statement="$@"
: "${statement:="Love the Lord your God with all your heart, soul, mind and strength, and love your neighbour as yourself."}"

n=1
echo "$n"
echo
echo "$statement"
echo

while :; do
    statement="$(penf --pool pf-most-important-thing/1 "$statement")"
    n="$((n + 1))"
    echo "$n"
    echo
    echo "$statement"
    echo
done
