#!/bin/bash
export TTY

# penelfonts -f smbraille.tlf NL-SH

IFS= read -r -d '' nlsh_logo <<HEREDOC
 [0;1;35;95m⡷[0;1;31;91m⣸[0m [0;1;33;93m⡇[0m     [0;1;34;94m⢎⡑[0m [0;1;35;95m⣇[0;1;31;91m⣸[0m
 [0;1;31;91m⠇[0;1;33;93m⠹[0m [0;1;32;92m⠧⠤[0m [0;1;36;96m⠉[0;1;34;94m⠉[0m [0;1;35;95m⠢⠜[0m [0;1;31;91m⠇[0;1;33;93m⠸[0m
HEREDOC

echo
printf -- "%s\n" "$nlsh_logo"
