#!/bin/bash

: "${NLPCLOUD_API_KEY:="$PEN_LM_KEY"}"

if test -s $HOME/.pen/nlpcloud_api_key; then
    : "${NLPCLOUD_API_KEY:="$(cat $HOME/.pen/nlpcloud_api_key)"}"
fi

test -n "$NLPCLOUD_API_KEY" || {
    echo "NLPCLOUD_API_KEY not given to script"
    exit 1
}

export NLPCLOUD_API_KEY

export PEN_PROMPT
export PEN_MODEL
export PEN_MIN_TOKENS
export PEN_MAX_TOKENS
export PEN_MIN_GENERATED_TOKENS
export PEN_MAX_GENERATED_TOKENS
export PEN_ENGINE_MIN_TOKENS
export PEN_ENGINE_MAX_TOKENS
export PEN_ENGINE_MAX_GENERATED_TOKENS
export PEN_TEMPERATURE
export PEN_TOP_P
export PEN_TOP_K
export PEN_STOP_SEQUENCE
export PEN_N_COMPLETIONS
export PEN_REPETITION_PENALTY
export PEN_LENGTH_PENALTY
export PEN_TRAILING_WHITESPACE

: "${PEN_N_COMPLETIONS:="4"}"

sedstop="$(printf -- "%s" "$PEN_STOP_SEQUENCE" | sed -z 's/\\/\\\\/g')"

# pen-nlpcloud.py "$@" | sed -z "s~${PEN_STOP_SEQUENCE}.*~~"

# Interestingly, nlpcloud has this issue where the start of the response is stripped

pen_nlpcloud() {
    if printf -- "%s\n" "$PEN_FLAGS" | grep -q -P '<nlpcloud-begin-newline>'; then
        echo
    fi

    # cmd-nice-jq is very slow. Find a faster, reliable solution.
    # Or use python

    # \"maxTokens\": $PEN_ENGINE_MAX_GENERATED_TOKENS,

    curl "https://api.nlpcloud.io/v1/$PEN_MODEL/generation" \
    -H "Authorization: Token $NLPCLOUD_API_KEY" \
    -H "Content-Type: application/json" \
    -X POST -d "{
        \"text\": $(cmd-nice-jq "$PEN_PROMPT"),
        \"num_return_sequences\": $PEN_N_COMPLETIONS,
        \"top_k\": $PEN_TOP_K,
        \"top_p\": $PEN_TOP_P,
        \"length_no_input\": true,
        \"remove_input\": true,
        \"end_sequence\": $(cmd-nice-jq "$PEN_STOP_SEQUENCE"),
        \"min_length\": $PEN_MIN_GENERATED_TOKENS,
        \"max_length\": $PEN_MAX_GENERATED_TOKENS,
        \"repetition_penalty\": $PEN_REPETITION_PENALTY,
        \"temperature\": $PEN_TEMPERATURE
    }"

    # https://docs.nlpcloud.io/#generation
}

mkdir -p ~/.pen
pen_nlpcloud "$@" > pen-log nlpcloud-temp.txt &>/dev/null

# This is how errors are shown
# {"detail":"Your end_sequence token is not supported"}

# The part below here is untested

cat ~/.pen/temp/nlpcloud-temp.txt | jq -r .generated_text