#!/bin/bash

: "${HF_API_KEY:="$PEN_LM_KEY"}"

if test -s $HOME/.pen/hf_api_key; then
    : "${HF_API_KEY:="$(cat $HOME/.pen/hf_api_key)"}"
fi

test -n "$HF_API_KEY" || {
    echo "HF_API_KEY not given to script"
    exit 1
}

: "${PEN_REPETITION_PENALTY:="1.0"}"

export HF_API_KEY

if test "$PEN_N_COMPLETIONS" -gt 4; then
    PEN_N_COMPLETIONS=4
fi

export PEN_PROMPT
export PEN_MODEL
export PEN_MAX_TOKENS
export PEN_TEMPERATURE
export PEN_REPETITION_PENALTY
export PEN_TOP_P
export PEN_STOP_SEQUENCE
export PEN_N_COMPLETIONS
export PEN_MODE

: "${PEN_N_COMPLETIONS:="4"}"

sedstop="$(printf -- "%s" "$PEN_STOP_SEQUENCE" | sed -z 's/\\/\\\\/g')"

# pen-hf.py "$@" | sed -z "s~${PEN_STOP_SEQUENCE}.*~~"

{
# printf -- "%s" "$PEN_PROMPT"
pen-hf.py "$@" | pen-log hf-temp | sed -z "s~${sedstop}$~~"
} | pen-log hf