cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis 8:20-22 # <== Genesis" "#" "<==" "sbcl"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "I Peter 1:22-25 # \"<==\" zsh" "#" "<==" "sbcl"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
