cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "2" "#" "<==" "sbcl"
cd /root/.pen/documents/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "2 Thes" "#" "<==" "sbcl"
cd /root/.pen/documents/notes/ws;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Matt \"5:14,16\"" "#" "<==" "sbcl"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
