cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /root/.emacs.d/host/pen.el/scripts/bible-mode-scripts;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Ps" "#" "<==" "sbcl"
cd /root/.emacs.d/host/pen.el/scripts/bible-mode-scripts;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl"
cd /root/.emacs.d/host/pen.el/scripts/bible-mode-scripts;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Pr" "#" "<==" "sbcl"
cd /root/.emacs.d/host/pen.el/scripts/bible-mode-scripts;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Heb" "#" "<==" "sbcl"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "II Thessalonians" "#" "<==" "sbcl"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "\"Revelation of John\"" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "1 Thessalonians" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "I Thessalonians" "#" "<==" "sbcl"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "I shx Thessalonians" "#" "<==" "sbcl"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
