cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /root/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/.emacs.d/host/pen.el/src;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Philippians" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl"
cd /;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "Job" "#" "<==" "sbcl"
cd /root/.pen/documents/websites;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/websites;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/websites;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
