cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "I Samual" "#" "<==" "sbcl"
cd /root/.pen/documents/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "I Samual" "#" "<==" "sbcl"
cd /root/.pen/documents/notes;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/bible-mode-scripts/canonicalise-bible-book-title.cl" "I Samual" "#" "<==" "sbcl"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
