cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /volumes/home/shane/var/smulliga/source/git/ciel-lang/CIEL;  "ros" "-L" "sbcl" "-Q" "-l" "/root/.sbclrc" "run" "--" "--non-interactive" "--eval" "(ql:quickload :deploy)" "--eval" "(ql:quickload \"cl+ssl\")" "--load" "ciel.asd" "--load" "build-config.lisp" "--eval" "(ql:quickload :swank)" "--eval" "(push :deploy-console *features*)" "--eval" "(ql:quickload :ciel)" "--eval" "(ql:quickload :ciel/repl)" "--eval" "(asdf:make :ciel/repl)" "--eval" "(quit)" "#" "<==" "sbcl"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "tmux-shell"
cd /;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "ros" "roswell-internal-use" "version" "confdir" "#" "<==" "emacs"
