;;; babashka-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from babashka.el

(autoload 'babashka-tasks "babashka" "\
Run Babashka tasks for project or any path.


Find bb.edn in current dir or its parents, and show a menu to select and run
a task.

When called with interactive ARG prompts for directory.

(fn ARG)" t)
(autoload 'babashka-project-tasks "babashka" "\
Run a Babashka task from the bb.edn file in the project's root directory.

This command is intended to be used as a `project-switch-project' command
by adding it to `project-switch-commands'.

For example by evaling:

(add-to-list \\='project-switch-commands
  \\='(babashka-project-tasks \"Babashka task\" \"t\"))" t)
(register-definition-prefixes "babashka" '("babashka-"))

;;; End of scraped data

(provide 'babashka-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; babashka-autoloads.el ends here
