#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# xterm inside Pen.el has sixel support

# I have to disable readline for sixel

xt -xt cterm -ct-nem norl guild-of-thieves -vmode sixel