#!/bin/bash
export TTY

# TODO First, unlinkify
# Secondly,relinkify

# scrape-bible-references -v   # verses only

grepfilter "wrlp org-unclink -t biblegateway" filter-org-links | 
    grepfilter "wrlp biblegatewayify-bible-ref" "scrape-bible-references -v"
