#!/bin/bash
export TTY

# TODO First, unlinkify
# Secondly,relinkify

# scrape-bible-references -v   # verses only

strongs-codes-unlinkify | 
    grepfilter "wrlp blueletterbibleify-strongs-code" "scrape-strongs-codes"
