cd /root/notes;  "Genesis" "32:30" "#" "<==" "pen-ci"
cd /;  "Genesis" "32:30" "#" "<==" "pen-ci"
cd /;  "Genesis" "32:30" "#" "<==" "pen-ci"
cd /;  "Genesis" "32:30" "#" "<==" "pen-ci"
cd /;  "Genesis" "32:30" "#" "<==" "pen-ci"
cd /;  "Genesis" "32:30" "#" "<==" "pen-ci"
cd /root/notes;  "Genesis" "32:30" "#" "<==" "pen-ci"
