;;; helm-org-multi-wiki-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-org-multi-wiki.el

(autoload 'helm-org-multi-wiki-def-create-entry-action "helm-org-multi-wiki" "\
Define a command to create an entry in NAMESPACE via the dummy source.

This function is only provided as a utility.

(fn NAMESPACE)" nil t)
(autoload 'helm-org-multi-wiki "helm-org-multi-wiki" "\
Visit an entry or create a new entry.

NAMESPACES are are a list of namespaces.
It can be a list of symbols or a symbol.

If FIRST is given, it will be the default namespace in which an
entry is created.

(fn &optional NAMESPACES &key FIRST)" t)
(autoload 'helm-org-multi-wiki-all "helm-org-multi-wiki" "\
Run `helm-org-multi-wiki' on all configured directories." t)
(autoload 'helm-org-multi-wiki-insert-link "helm-org-multi-wiki" "\
Insert a link or converts the region to a link.

FIRST is the default namespace when you create a non-existent
entry.

(fn &key FIRST)" t)
(register-definition-prefixes "helm-org-multi-wiki" '("helm-org-multi-wiki-"))

;;; End of scraped data

(provide 'helm-org-multi-wiki-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-org-multi-wiki-autoloads.el ends here
