cd /root/.emacs.d/host/pen.el/scripts;  "lem" "#" "<==" "zsh"
cd /root/.roswell/local-projects/lem-project/lem;  "lem" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "get-bible-book-chapter.cl" "#" "<==" "zsh"
cd /root/.roswell/local-projects/lem-project/lem/contrib/tetris;  "lem" "/root/.roswell/local-projects/lem-project/lem/contrib/tetris/tetris.lisp" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "lem" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "#" "<==" "zsh"
