;;; company-ledger-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-ledger.el

(autoload 'company-ledger "company-ledger" "\
Fuzzy company back-end for ledger, beancount and other ledger-like modes.
Provide completion info based on COMMAND and ARG.  IGNORED, not used.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-ledger" '("company-ledger-"))

;;; End of scraped data

(provide 'company-ledger-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-ledger-autoloads.el ends here
