cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "2" "Tim" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "2" "Tim" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "2" "Tim" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "canonicalise-bible-book-title" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "canonicalise-bible-book-title" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "canonicalise-bible-book-title" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "canonicalise-bible-book-title" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "canonicalise-bible-book-title" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "canonicalise-bible-book-title" "#" "<==" "zsh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /root/notes;  "canonicalise-bible-book-title" "#" "<==" "emacs"
cd /root/notes;  "canonicalise-bible-book-title" "#" "<==" "emacs"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /;  "canonicalise-bible-book-title" "#" "<==" "sh"
cd /root/.pen/documents;  "canonicalise-bible-book-title" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "2" "Tim" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "2" "Tim." "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "2" "Tim." "3" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "2" "Tim." "3:6-9" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "2" "Tim." "3:6-9" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "canonicalise-bible-book-title" "#" "<==" "canonicalise-bi"
