* TODO Support these common annotation facilities in pen.el
+ Original source :: http://www.hunter.cuny.edu/rwc/handouts/the-writing-process-1/invention/Annotating-a-Text/

- HIGHLIGHTING/UNDERLINING
  - Most common form of annotating texts.
    - Seriously don't overuse this.
- PARAPHRASE/SUMMARY OF MAIN IDEAS
  - Going beyond locating important ideas to
    being able to capture their meaning through
    paraphrase is a way of solidifying your
    understanding of these ideas.
    
    It’s also excellent preparation for any
    writing you may have to do based on your
    reading.
    
    A series of brief notes in the margins
    beside important ideas gives you a handy
    summary right on the pages of the text
    itself, and if you can take the substance of
    a sentence or paragraph and condense it into
    a few words, you should have little trouble
    clearly demonstrating your understanding of
    the ideas in question in your own writing.
- DESCRIPTIVE OUTLINE
  - Shows the organization of a piece of writing, breaking it down to show
    where ideas are introduced and where they are developed. A descriptive
    outline allows you to see not only where the main ideas are but also where
    the details, facts, explanations, and other kinds of support for those
    ideas are located.
- COMMENTS/RESPONSES
  - You can use annotation to go beyond
    understanding a text’s meaning and
    organization by noting your
    reactions—agreement/disagreement, questions,
    related personal experience, connection to
    ideas from other texts, class discussions,
    etc.
    
    This is an excellent way to begin
    formulating your own ideas for writing
    assignments based on the text or on any of
    the ideas it contains.