cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin3" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin2" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin2" "--out" "/tmp/stdout" "--" "vim" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin2" "--out" "/tmp/stdout" "--" "nano" "/root/repos/bubbletea/nil_renderer.go" "#" "<==" "zsh"
