cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "vim" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "nano" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "nano" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "nano" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/repos/mitsuhiko/teetty;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/repos/mitsuhiko/teetty;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/repos/mitsuhiko/teetty;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/repos/mitsuhiko/teetty;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/repos/mitsuhiko/teetty;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/repos/mitsuhiko/teetty;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/repos/mitsuhiko/teetty;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/repos/mitsuhiko/teetty;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "teetty" "--in" "/tmp/stdin" "--out" "/tmp/stdout" "--" "python" "#" "<==" "zsh"
