https://www.heidelberg-catechism.com/en/lords-days/1.html

* 1. Q.  What is your only comfort in life and death?
That I am not my own, 1
but belong with body and soul,
both in life and in death, 2
to my faithful Saviour Jesus Christ. 3
He has fully paid for all my sins
with his precious blood, 4
and has set me free
from all the power of the devil. 5
He also preserves me in such a way 6
that without the will of my heavenly Father
not a hair can fall from my head; 7
indeed, all things must work together
for my salvation. 8
Therefore, by his Holy Spirit
he also assures me
of eternal life 9
and makes me heartily willing and ready
from now on to live for him. 10

- 1. 1 Cor 6:19,20
- 2. Rom 14:7-9.
- 3. 1 Cor 3:23; Tit 2:14.
- 4. 1 Pet 1:18, 19; 1 Jn 1:7; 2:2.
- 5. Jn 8:34-36; Heb 2:14, 15; 1 Jn 3:8.
- 6. Jn 6:39, 40; 10:27-30; 2 Thess 3:3; 1 Pet 1:5.
- 7. Mt 10:29-31; Lk 21:16-18.
- 8. Rom 8:28.
- 9. Rom 8:15, 16; 2 Cor 1:21, 22; 5:5; Eph 1:13, 14.
- 10. Rom 8:14.

* 2.  Q.  What do you need to know in order to live and die in the joy of this comfort?
First,
how great my sins and misery are; 1
second,
how I am delivered
from all my sins and misery; 2
third,
how I am to be thankful to God
for such deliverance. 3

- 1. Rom 3:9, 10; 1 Jn 1:10.
- 2. Jn 17:3; Acts 4:12; 10:43.
- 3. Mt 5:16; Rom 6:13; Eph 5:8-10; 1 Pet 2:9, 10.
