cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "pdflatex" "-interaction" "nonstopmode" "-output-directory" "./" "README.tex" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "pdflatex" "-interaction" "nonstopmode" "-output-directory" "./" "README.tex" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "pdflatex" "-interaction" "nonstopmode" "-output-directory" "./" "README.tex" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "pdflatex" "-interaction" "nonstopmode" "-output-directory" "./" "README.tex" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "pdflatex" "-interaction" "nonstopmode" "-output-directory" "./" "README.tex" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "pdflatex" "-interaction" "nonstopmode" "-output-directory" "./" "README.tex" "#" "<==" "emacs"
