cd /root/.pen/documents/notes;  "recode" "html.." "#" "<==" "web"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "recode" "html.." "#" "<==" "web"
cd /root/.pen/documents/notes;  "recode" "html.." "#" "<==" "web"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "recode" "html.." "#" "<==" "web"
cd /root/.pen/documents/notes;  "recode" "html.." "#" "<==" "web"
cd /root/.pen/documents/notes;  "recode" "html.." "#" "<==" "web"
cd /root/.pen/documents/notes;  "recode" "html.." "#" "<==" "web"
