cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts/christian-resources;  "ved" "-g" "-pat" "IMG" "ddA\\<C-v>\\<C-i>\\<C-c>Jj" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "ved" "-m" "/Genesis\\<CR>/\\<5\\>\\<CR>\"ayyggVGd\"aP" "#" "<==" "vedm"
cd /root/.pen/documents/notes;  "ved" "-m" "/Genesis\\<CR>/\\<5\\>\\<CR>\"ayyggVGd\"aP" "#" "<==" "vedm"
