cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Psalm" "31" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Psalm" "31" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "Jesus" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "-g" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "gospel" "-g" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "-g" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "-g" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "-g" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "-g" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "-g" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "-g" "gospel" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "-g" "babylon" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "-" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "-g" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "-g" "Psalm" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "-g" "Psalms" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "Psalm" "#" "<==" "zsh"
cd /root/.emacs.d/manual-packages/bible-mode;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "proverb" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-m" "KJV" "Ezra" "#" "<==" "kjv"
cd /root/.pen/documents/notes;  "bible-search" "-m" "KJV" "-g" "Ezra" "#" "<==" "kjv"
cd /root/.pen/documents/notes;  "bible-search" "-m" "KJV" "-g" "Ezra" "#" "<==" "kjv"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "-g" "Ezra" "#" "<==" "nasb"
cd /root/.pen/documents/notes;  "bible-search" "-m" "KJV" "-g" "Ezra" "#" "<==" "kjv"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "-g" "Ezra" "#" "<==" "nasb"
cd /root/.pen/documents/notes;  "bible-search" "-m" "KJV" "-g" "Ezra" "#" "<==" "kjv"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "-g" "Ezra" "#" "<==" "nasb"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "-g" "Ezra" "10:1" "#" "<==" "nasb"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "Ezra" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "Ezra" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "-g" "Ezra" "#" "<==" "nasb"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "Lord" "Jesus" "Christ" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "Lord" "Jesus" "Christ" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-l" "-m" "NASB" "Lord" "Jesus" "Christ" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-l" "-m" "NASB" "Lord" "Jesus" "Christ" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "Lord" "Jesus" "Christ" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "bible-search" "-g" "-m" "NASB" "Lord" "Jesus" "Christ" "#" "<==" "zsh"
cd /root/notes;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/src;  "bible-search" "-m" "NASB" "-g" "living" "God" "#" "<==" "nasb"
cd /root/.emacs.d/host/pen.el/scripts;  "bible-search" "-m" "NASB" "-g" "preach the gospel" "#" "<==" "nasb"
cd /;  "bible-search" "-m" "NASB" "-g" "preach the gospel" "#" "<==" "nasb"
cd /root/notes;  "bible-search" "-m" "NASB" "-g" "preach the gospel" "#" "<==" "nasb"
cd /;  "bible-search" "-m" "NASB" "-g" "preach the gospel" "#" "<==" "nasb"
cd /root/notes;  "bible-search" "-m" "NASB" "-g" "preach the gospel" "#" "<==" "nasb"
cd /root/.pen/glossaries;  "bible-search" "-m" "NASB" "-g" "Holy" "One" "of" "Israel" "#" "<==" "nasb"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "-g" "tree" "of" "life" "#" "<==" "nasb"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "-g" "Holy" "One" "of" "Israel" "#" "<==" "nasb"
cd /root/.pen/documents/notes;  "bible-search" "-m" "NASB" "-g" "tree" "of" "life" "#" "<==" "nasb"
