#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

bin=$MYGIT/hackertarget/nmap-csv-xlsx/nmap-xml-to-csv.py

test -f "$bin" || {
    gc "https://github.com/hackertarget/nmap-csv-xlsx"
} &>/dev/null

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists; then
    xmlfp="$(tf xml)"
    set -- "$@" "$xmlfp"
fi

mypython "$bin"  "$@"
