#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/whosthere" || go install "github.com/whosthere/whosthere@latest" &>/dev/null

${GOPATH%%:*}/bin/whosthere "$@"
