cd /root/.pen/documents/notes;  "task" "rc.color=off" "rc._forcecolor=off" "rc.defaultwidth=0" "show" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "--version" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=status:pending -WAITING limit:page" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.color=off" "rc._forcecolor=off" "rc.defaultwidth=0" "show" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "--version" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=status:pending -WAITING limit:page" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.color=off" "rc._forcecolor=off" "rc.defaultwidth=0" "show" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "--version" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=status:pending -WAITING limit:page" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "task" "rc.color=off" "rc._forcecolor=off" "rc.defaultwidth=0" "show" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "--version" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=status:pending -WAITING limit:page" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=status:pending -WAITING limit:page" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.color=off" "rc._forcecolor=off" "rc.defaultwidth=0" "show" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "--version" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=(status:pending or status:waiting) page:limit" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=(status:pending or status:waiting) page:limit" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=status:pending -WAITING limit:page" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.color=off" "rc._forcecolor=off" "rc.defaultwidth=0" "show" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "--version" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context..read" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "_get" "rc.context." "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.columns" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "show" "rc.defaultwidth=0" "report.next.labels" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=(status:pending or status:waiting) page:limit" "export" "next" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "context" "#" "<==" "taskwarrior-tui"
cd /root/.pen/documents/notes;  "task" "summary" "#" "<==" "taskwarrior-tui"
