;;; org-roam-ql-ql-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-roam-ql-ql.el

(autoload 'org-roam-ql-ql-buffer-from-roam-buffer "org-roam-ql-ql" "\
Convert a roam buffer to org-ql buffer." t)
(autoload 'org-roam-ql-ql-roam-buffer-from-agenda-buffer "org-roam-ql-ql" "\
Convert a agenda reusult to a roam-buffer." t)
(autoload 'org-roam-ql-ql-init "org-roam-ql-ql" "\
Integrate `org-roam-ql' into `org-ql'.")
(register-definition-prefixes "org-roam-ql-ql" '("org-roam-ql-ql--"))

;;; End of scraped data

(provide 'org-roam-ql-ql-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-roam-ql-ql-autoloads.el ends here
