cd /root/.pen/documents/agenda;  "ebible" "-m" "ESV" "Psalms 92:9" "#" "<==" "withopts"
cd /root/.pen/documents/agenda;  "ebible" "-m" "ESV" "Psalms 92:1" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Ps 92:9-11" "#" "<==" "Ps"
cd /root/.pen/documents/agenda;  "ebible" "-m" "ESV" "Matthew 25:8" "#" "<==" "Matthew"
cd /root/.pen/documents/agenda;  "ebible" "-m" "ESV" "Ezekiel 46:15" "#" "<==" "Ezekiel"
cd /root/.pen/documents/agenda;  "ebible" "-m" "ESV" "Ezekiel 46:15" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 28:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "ESV" "Matthew 28:7" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 28:1-6" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Cor 15:14" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6:7" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 8" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 8" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 8:31-36" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 10:22" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 21:27" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 16:28" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:27-28" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "I Corinthians 4-8" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "I Corinthians 4-8" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "ESV" "Psalm 37:4" "#" "<==" "Psalm"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 6:33" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 11:1" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Jn 3:3-8" "#" "<==" "Jn"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "ESV" "John 3:15" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 6:4" "#" "<==" "Romans"
