cd /;  "ebible" "-m" "ESV" "2 Peter 2:5" "#" "<==" "2"
cd /;  "ebible" "-m" "ESV" "2 Peter 2:5" "#" "<==" "2"
cd /;  "ebible" "-m" "ESV" "2 Peter 2:5" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 1:9" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matt 12:3" "#" "<==" "Matt"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matt 12:3" "#" "<==" "Matt"
cd /;  "ebible" "-m" "ESV" "Deut 25:5-10" "#" "<==" "Deut"
cd /;  "ebible" "-m" "ESV" "Deut 25:5-10" "#" "<==" "Deut"
cd //;  "ebible" "-m" "ESV" "-nem" "Deuteronomy 25:5-10" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:1" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:1" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 17:1-3" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 8:18" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 22:3-5" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:35" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:33" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:31" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:25" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:24" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:21" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "Luke 20:19" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 1:3" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 1:3" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Genesis 6:2" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 25:1" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Deuteronomy 32:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 8:47" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews \"1:1\\e2\\80\\932\"" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews \"1:1\\e2\\80\\932\"" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 1:1-2" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5:30" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 11:28" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "James 1:22" "#" "<==" "James"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Corinthians 7:39" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Corinthians 7:39" "#" "<==" "1"
cd /;  "ebible" "-m" "ESV" "Matt 23" "#" "<==" "Matt"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:17-18" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:17-18" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "James 3-5" "#" "<==" "James"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "James 3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "James 3-5" "#" "<==" "James"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "James 3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "James 3-5" "#" "<==" "James"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "James 3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "James 3-5" "#" "<==" "James"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "James 3-5" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 23:2" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 23:2-3" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 7:1" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "James 3-5" "#" "<==" "James"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "James 3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Acts 15-16" "#" "<==" "Acts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "Acts 15-16" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:17-18" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:17-18" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 5:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:17-18" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:17-18" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:5" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:5" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:7" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:8" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:9" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:10" "#" "<==" "withopts"
