cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 9:1" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 9:2" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 9:3" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:1" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:2" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:7" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:12" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:13" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:14" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:15" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:16" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:17" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:18" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:19" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 3:20" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 8" "#" "<==" "Romans"
cd /;  "ebible" "-nbd" "-m" "NASB" "Romans 8:1" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Isaiah 40" "#" "<==" "Isaiah"
cd /;  "ebible" "-nbd" "-m" "NASB" "Romans 8" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "Isaiah 40" "#" "<==" "sh"
