cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 3:3-9" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 3:6-9" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 3:6-9" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 3:1-5" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 2:19" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 11:8-12" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 11:8" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 11:8" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Peter 4:8" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Prov 10:12" "#" "<==" "Prov"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Prov 10:12" "#" "<==" "Prov"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Col 3:14" "#" "<==" "Col"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Prov 17:9" "#" "<==" "Prov"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1Pet 1:22" "#" "<==" "1Pet"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 3:17" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 3:18" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 3:19" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 2:2" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Thessalonians 2:11" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 4:21-22" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 3:6-9" "#" "<==" "Galatians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Galatians 3:6-9" "#" "<==" "Galatians"
cd /volumes/home/shane/notes;  "ebible" "-m" "ESV" "John 3:16-17" "#" "<==" "John"
cd /volumes/home/shane/notes;  "ebible" "-m" "ESV" "Hebrews 7:25" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 8" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 7" "#" "<==" "Hebrews"
cd /;  "ebible" "-bd" "-m" "ESV" "Galatians 5:19-21" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "ESV" "Galatians 5:19-21" "#" "<==" "sh"
cd /;  "ebible" "-m" "ESV" "Romans 9" "#" "<==" "Romans"
cd /;  "ebible" "-nbd" "-m" "ESV" "Deuteronomy 23:7" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 2:18" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 2:18" "#" "<==" "withopts"
cd /;  "ebible" "-nbd" "-m" "ESV" "Genesis 1:2" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "ESV" "Gen 15:6" "#" "<==" "Gen"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "II Thessalonians 2:11-13" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isa 9:6" "#" "<==" "Isa"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5:30" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 5:30" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 13:7" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Joshua 6" "#" "<==" "Joshua"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Deut 28:1-19" "#" "<==" "Deut"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Deuteronomy 28:1-19" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Deuteronomy 28:1-19" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Deuteronomy 28:1-19" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Deuteronomy 28:1-19" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 12:22-24" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 12:22-24" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 122" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 12" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 6:27" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 6:29" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 7:17" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 7:17-19" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 7:17-18" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 7:17-19" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Deuteronomy 23:7" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "KJV" "Genesis 36:9" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 36:9" "#" "<==" "Genesis"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 9:13" "#" "<==" "Romans"
