cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Romans 8:1" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Revelation 13" "#" "<==" "Revelation"
cd /;  "ebible" "-nbd" "-m" "NASB" "Matthew 7:13-14" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 2" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 12" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 17" "#" "<==" "John"
cd /;  "ebible" "-nbd" "-m" "NASB" "Matthew 12:33-37" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 17" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 8:31-32" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 12" "#" "<==" "Romans"
