cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation 22:14-15" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Corinthians 6:9-20" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "-nem" "Revelation of John 22:14-15" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Timothy 1:9" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Corinthians 6:9-20" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:19-21" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation 22:15" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ephesians 5:5" "#" "<==" "Ephesians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Timothy 1:8" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Timothy 1" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Timothy 1:8-10" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Timothy 1:8-11" "#" "<==" "1"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Matthew 5:14-16" "#" "<==" "Matthew"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Matthew 5:14" "#" "<==" "Matthew"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Romans 1:27" "#" "<==" "Romans"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Romans 1" "#" "<==" "Romans"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Romans 1" "#" "<==" "Romans"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Romans 1:24-32" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Romans 11" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Matthew 12:33-37" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Hebrews 1:3" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Psalm 89:14" "#" "<==" "Psalm"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Luke 7" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Luke 7:8-9" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Luke 7:47-50" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Hebrews 11:8" "#" "<==" "Hebrews"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Leviticus 19:27" "#" "<==" "Leviticus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 15:18" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Hebrews 11:8" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Hebrews 11:1" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 17:20" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Ephesians 2:8" "#" "<==" "Ephesians"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 18:3" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "2 Chronicles 7:14" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Romans 14:23" "#" "<==" "Romans"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-c" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Romans 3:13" "#" "<==" "withopts"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Romans 3:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 13" "#" "<==" "Acts"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 5:14" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 5:16" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 5:16" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 5:16" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Ephesians 2:10" "#" "<==" "Ephesians"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Daniel 12:3" "#" "<==" "Daniel"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 5:19" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 10:8" "#" "<==" "Matthew"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Matthew 5:20" "#" "<==" "Matthew"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "I John 3:4-9" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 6:15" "#" "<==" "Matthew"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "ESV" "Genesis 12:1-3" "#" "<==" "Genesis"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 14:25-27" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Matthew 19:29" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Luke 14:25-34" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Luke 14:25-34" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "-nem" "Luke 14:25-34" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 3:16" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 3:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 3:15" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalms 119:160" "#" "<==" "Psalms"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "John 12:25" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 6:19-21" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Matthew 7:3-5" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:19" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:20" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:21" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:22" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:21" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:14" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 5:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 5:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 5:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 5:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 5:12" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 5:13" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:42" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:43" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:44" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:43" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:42" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:42" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:43" "#" "<==" "withopts"
cd /volumes/home/shane/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalms 51:9-11" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 10:43" "#" "<==" "withopts"
cd /;  "ebible" "-m" "ESV" "Matthew 24" "#" "<==" "Matthew"
cd //;  "ebible" "-m" "ESV" "Daniel 7" "#" "<==" "Daniel"
cd /;  "ebible" "-m" "ESV" "Psalm 51" "#" "<==" "Psalm"
cd /;  "ebible" "-m" "ESV" "Mark 8:38" "#" "<==" "Mark"
cd /;  "ebible" "-m" "ESV" "Psalm 110:1" "#" "<==" "Psalm"
