cd /root/notes;  "ebible" "-m" "ESV" "Psalms 11:5" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 11:5" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 15:22-23" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Proverbs 28:9" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 28:9" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Colossians 1:19-20" "#" "<==" "Colossians"
cd /root/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:9-12" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "Jeremiah 13:23" "#" "<==" "Jeremiah"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 1:24-32" "#" "<==" "Romans"
