cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Proverbs 12:11" "#" "<==" "Proverbs"
cd /;  "ebible" "-m" "ESV" "Revelation of John 12" "#" "<==" "Revelation"
cd /;  "ebible" "-m" "ESV" "I Thess" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1Th 5:12-14" "#" "<==" "1Th"
cd //;  "ebible" "-m" "ESV" "I Thessalonians 5:4-5" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "1Th 5:23-24" "#" "<==" "1Th"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "1Th 5:23-24" "#" "<==" "1Th"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "-nem" "I Thessalonians 5:23-24" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1Th 5:23-24" "#" "<==" "1Th"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "-nem" "I Thessalonians 5:23-24" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "ESV" "Ps 95:11" "#" "<==" "Ps"
cd /root/notes;  "ebible" "-m" "ESV" "Matt 11:28-29" "#" "<==" "Matt"
cd /root/notes;  "ebible" "-m" "ESV" "1Pet 1:20" "#" "<==" "1Pet"
cd /root/notes;  "ebible" "-m" "ESV" "Hebrews 4:1" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Rev 14:13" "#" "<==" "Rev"
cd /root/notes;  "ebible" "-m" "ESV" "Heb 4:3-4" "#" "<==" "Heb"
cd /root/notes;  "ebible" "-m" "ESV" "1Pet 4:1-2" "#" "<==" "1Pet"
cd /root/notes;  "ebible" "-m" "ESV" "1Pet 4:1-2" "#" "<==" "1Pet"
cd /root/notes;  "ebible" "-m" "ESV" "Heb 10:12" "#" "<==" "Heb"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "John 19:30" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "John 19:30" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Heb 1:3" "#" "<==" "Heb"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-c" "-m" "KJV" "Heb 4:1-11" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalms 37:21" "#" "<==" "Psalms"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Psalms 37:25-26" "#" "<==" "Psalms"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalms 37:25-26" "#" "<==" "Psalms"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Proverbs 3:6" "#" "<==" "Proverbs"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalms 33:4" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "KJV" "1Th 5:14" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "KJV" "1Th 5:13" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "KJV" "1Th 5:12" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "KJV" "Matthew 28:1-6" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "KJV" "1P 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "KJV" "Jn 3:25" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "KJV" "Jn 3:19" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 8:2" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-c" "-m" "KJV" "Romans 8:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 4" "#" "<==" "Galatians"
