cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:16" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:16" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:18" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-18" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-20" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-22" "#" "<==" "Exodus"
cd /;  "ebible" "-m" "ESV" "Mark 1:21-28" "#" "<==" "Mark"
cd /;  "ebible" "-m" "ESV" "Mark 1:21-28" "#" "<==" "Mark"
cd /;  "ebible" "-m" "ESV" "Mark 1:21-28" "#" "<==" "Mark"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-24" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-26" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-28" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-30" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-32" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Exodus 14:14-32" "#" "<==" "Exodus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Mark 1:21-28" "#" "<==" "Mark"
cd /root/notes;  "ebible" "-m" "ESV" "James 4:11-12" "#" "<==" "James"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 15:14-17" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 3:28-31" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ephesians 2:8-9" "#" "<==" "Ephesians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ephesians 2:8-10" "#" "<==" "Ephesians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 3:16-17" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 5:9-11" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalms 32:1" "#" "<==" "Psalms"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalms 32:11" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 John 3:5" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 3:3-7" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 John 3:5" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Thessalonians 5:23" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 17:3" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Peter 3:17-18" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "James 4:12" "#" "<==" "James"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 14:23-24" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 7:16-20" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Peter 3:17-21" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 John 4:19" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "James 2:14-26" "#" "<==" "James"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Lk 24:24-27" "#" "<==" "Lk"
