cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Jeremiah 29:13" "#" "<==" "Jeremiah"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Jeremiah 29:13-14" "#" "<==" "Jeremiah"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 7:3-5" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 3:12" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Peter 2:11" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 1:17" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 2:11" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Peter 1:1" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 11:13" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "ESV" "Jeremiah 29:14" "#" "<==" "Jeremiah"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 1:2" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 1:2-3" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 4:5" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Numbers 14:18-19" "#" "<==" "Numbers"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Numbers 14:18" "#" "<==" "Numbers"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Genesis 4:3" "#" "<==" "Genesis"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Genesis 4:4" "#" "<==" "Genesis"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Ephesians 1:14-16" "#" "<==" "Ephesians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Ephesians 1:13-14" "#" "<==" "Ephesians"
cd /root/notes;  "ebible" "-m" "ESV" "I John 3:9" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 4:7" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:1" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:4" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:18" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 14:12" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Hebrews 9:14" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 19:4" "#" "<==" "Acts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 8:11" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "I John 4:8" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 2:29" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 3:7" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 19:21" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 5:48" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Jude 1:4" "#" "<==" "Jude"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Revelation 2:5" "#" "<==" "Revelation"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Revelation 2:4" "#" "<==" "Revelation"
cd /root/notes;  "ebible" "-m" "ESV" "John 10:17" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 10:17" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 15:13" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 10:18" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 22:42" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 17:26-27" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 7:7" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Philippians 3:8-11" "#" "<==" "Philippians"
