cd /root/notes;  "ebible" "-m" "ESV" "John 16:26-27" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 8:42" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 7:22-23" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 8:3" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Galatians 4:9" "#" "<==" "Galatians"
cd /root/notes;  "ebible" "-m" "ESV" "I John 4:21" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 4:32" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Galatians 4:6" "#" "<==" "Galatians"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 3:3-6" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 3:21-28" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "John 14:1" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 78:21-22" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "John 10:24-38" "#" "<==" "John"
