cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "1 John 3:17-18" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Mark 1:14-15" "#" "<==" "Mark"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 6:24" "#" "<==" "Matthew"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "RLT" "I John 4:21" "#" "<==" "I"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "RLT" "I John 4:18" "#" "<==" "I"
cd /;  "ebible" "-nbd" "-m" "RLT" "Ephesians 5:13" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Ephesians 5:8-20" "#" "<==" "Ephesians"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Luke 8:17" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "John 14:6" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Gal 6:2" "#" "<==" "Gal"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Rom 8:2" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Rom 6:14" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Rom 6:14" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Rom 6:14" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "I John 2:9" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "1 John 2:27" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Deuteronomy 28:13" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Deuteronomy 28:13-14" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Deuteronomy 28" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Deuteronomy 30:6" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Deuteronomy 30:7" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Deuteronomy 30:7" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Deuteronomy 30:6-8" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Jude 1:4" "#" "<==" "Jude"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 23:10" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 23:8" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 28:19-20" "#" "<==" "Matthew"
cd /volumes/home/shane/notes/ws/bible-studies;  "ebible" "-m" "RLT" "Matthew 28:19-20" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Nehemiah 9:21" "#" "<==" "Nehemiah"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "I John 4:21" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "1 Corinthians 9:21" "#" "<==" "1"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "I John 3:23-24" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "I John 3:13-15" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "II John 1:9-11" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 23:9-10" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 23:9-11" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 23:9-12" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 23:9-13" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 23:8-9" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 23:7-8" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "II Corinthians 6:14-18" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "II Corinthians 6" "#" "<==" "II"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "II Corinthians 6" "#" "<==" "II"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "II Corinthians 6" "#" "<==" "II"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "II Corinthians 6:14" "#" "<==" "II"
cd /root/.pen/documents/notes/ws/churches/cornerstone;  "ebible" "-m" "RLT" "II Corinthians 6:8" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "John 15:15" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Psalm 37:27" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Habakkuk 2:2-3" "#" "<==" "Habakkuk"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 19:21-24" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Acts 2:45" "#" "<==" "Acts"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Luke 12:33" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "Matthew 6:24" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "1 John 3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "RLT" "1 Timothy 6:17" "#" "<==" "1"
