cd /root/notes;  "ebible" "-m" "ESV" "John 6:44" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 26:14" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Acts 21:40" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Acts 22:2" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Acts 9:7" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Acts 9:4-5" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Zech 12:2" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Zech 2:8" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "1Cor 10:22" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Acts 22:7-9" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Prov 13:15" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Prov 13:15" "#" "<==" "Prov"
cd /root/notes;  "ebible" "-m" "ESV" "Psalm \"37:23,24\"" "#" "<==" "Psalm"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 19:24" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 18:17-19" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 9:6-8" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "Hebrews 11:13" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 19:24" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "Deut 14:1" "#" "<==" "Deut"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 18:1" "#" "<==" "Genesis"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Genesis 18:20-23" "#" "<==" "Genesis"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Genesis 18:32-33" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 18:25-26" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "Isaiah 63:10" "#" "<==" "Isaiah"
cd /root/notes;  "ebible" "-m" "ESV" "II Samuel 23:2" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "II Samuel 23:2-4" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 18:1-5" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 18:25" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "II Peter 1:5-11" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "John 5:37-38" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 63:10" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Is 35:8" "#" "<==" "Is"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Samuel 23:2" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Deut 14:1" "#" "<==" "Deut"
cd /root/notes;  "ebible" "-m" "ESV" "II Tim 1:12-16" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "Isaiah 59:2" "#" "<==" "Isaiah"
