cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "" "-nem" "Luke 5:27-39" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "" "-nem" "Luke 5:27-39" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "" "-nem" "Gen 1-3" "#" "<==" "cmdx"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "cmdx"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Luke 5:27-39" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Pro 3:7-8" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Luke 5:27-39" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Pro 3:7-8" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Luke 5:27-39" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Luke 5:27-39" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Pro 3:7-8" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Pro 3:7-8" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Gen 1-3" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Luke 5:27-39" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Luke 5:27-39" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/be-joyful-2;  "ebible" "-m" "NASB" "-nem" "Ps 59:1-8" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/advice-on-dating;  "ebible" "-m" "NASB" "-nem" "Proverbs 3:7-8" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Lev 18-20" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Lev 18-20" "#" "<==" "tmux: server"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/broken-arrows;  "ebible" "-m" "NASB" "-nem" "Pro 5:7-14" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/broken-arrows;  "ebible" "-m" "NASB" "-nem" "Ps 33:1-12" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/vision.org.au/the-word-for-today-reading/become-a-conduit-2;  "ebible" "-m" "NASB" "-nem" "2 Corinthians 9:7-8" "#" "<==" "bash"
cd /root/.pen/documents/devotionals/the-word-for-today-reading/begin-to-say-what-god-says;  "ebible" "-m" "NASB" "-nem" "1 Kings 12-13" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Matt 24:26-35" "#" "<==" "tmux: server"
