cd /root/.pen/tmp;  "ebible" "-m" "ESV" "Romans 5:1" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 5:1" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 10:9" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ephesians 2:9" "#" "<==" "Ephesians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 8:4-6" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Colossians 3:5" "#" "<==" "Colossians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Corinthians 6:9" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "James 2:18-19" "#" "<==" "James"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Mark 8:27-38" "#" "<==" "Mark"
cd /root/.emacs.d/straight/repos/org-verse;  "ebible" "-m" "ESV" "John 7:7" "#" "<==" "John"
cd /root/.emacs.d/straight/repos/org-verse;  "ebible" "-m" "ESV" "John 7:7" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Corinthians 7:19" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Galatians 6:15" "#" "<==" "Galatians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Galatians 5:6" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation of John 19:4" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 7:10" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 7:14" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation of John 7:17" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation of John 7:9" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 22:3" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 1:12" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I John 3:24" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 15:13" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I John 4:16" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 8:31" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 15:7" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Corinthians 13:13" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 26" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Timothy 1:17" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Jude 1:25" "#" "<==" "Jude"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Eph 3:20-21" "#" "<==" "Eph"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1Chr 29:11" "#" "<==" "1Chr"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Rev 19:1" "#" "<==" "Rev"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1Tim 6:15-16" "#" "<==" "1Tim"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Rev 17:14" "#" "<==" "Rev"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 17:3" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Jude 1:25" "#" "<==" "Jude"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Ephesians 3:20-21" "#" "<==" "Ephesians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Chronicles 29:11" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Revelation of John 19:1" "#" "<==" "Revelation"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Timothy 6:15-16" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Revelation of John 17:14" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 3:20" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 4:3" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 26:5" "#" "<==" "Genesis"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 19:1-10" "#" "<==" "Luke"
cd /;  "ebible" "-m" "ESV" "2 Corinthians 11" "#" "<==" "2"
