cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 14:4" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 14:4" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 5:19" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 7:18" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 7:16-18" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 6:24" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 3:10-13" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-c" "-m" "KJV" "I Corinthians 7:19" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 3:21" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 3:21-29" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 3:21" "#" "<==" "Galatians"
cd /root/.pen/documents/notes/ws;  "ebible" "-m" "ESV" "Romans 14:1-14" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws;  "ebible" "-m" "ESV" "Romans 14:22-23" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws;  "ebible" "-m" "ESV" "Romans 14:17-18" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws;  "ebible" "-m" "ESV" "Romans 14:10-14" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws;  "ebible" "-m" "ESV" "Romans 13:9-10" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws;  "ebible" "-m" "ESV" "Romans 3:20" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 3:3" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 10:14" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I John 4:17" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Romans 14:4" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 23:23" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 5:3-4" "#" "<==" "Galatians"
cd /root/notes;  "ebible" "-m" "ESV" "Jude 1:4" "#" "<==" "Jude"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 2:17" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 2:11-13" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 2:13" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 2:11-12" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 2:14" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 2:14-16" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "James 1:22" "#" "<==" "James"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 3:28" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 3:28-29" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 1:14" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Titus 3:3" "#" "<==" "Titus"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 1:14-15" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 1:14-16" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Hebrews 11:31" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "ESV" "Philippians 2:8" "#" "<==" "Philippians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 5:1" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 5:1-2" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 3:28-29" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 1:5-6" "#" "<==" "Luke"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 7:19" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 5:6" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 13" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 13" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 13:8" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 8:3-4" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 2:6-7" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Peter 1:13" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 7:6" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 7:6-7" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Corinthians 3:4-6" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Peter 4:16-17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Job 1:8-12" "#" "<==" "Job"
