cd /root/notes;  "ebible" "-m" "NASB" "Genesis 8:1" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 7:7" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Romans 8:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Romans 8:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 8" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Romans 8:11" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "I John 5:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Romans 8:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Romans 8:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Romans 8:2" "#" "<==" "fast"
cd /;  "ebible" "-m" "NASB" "Psalm 57" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "James 2:13" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "James 2:21-23" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "James 4:11" "#" "<==" "sh"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "I Peter 1:10" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "I Peter 1:21" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "I Peter 3:9" "#" "<==" "fast"
cd /;  "ebible" "-m" "NASB" "Genesis 1:27" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "Mark 7:12" "#" "<==" "Mark"
cd /root/notes;  "ebible" "-m" "NASB" "Mark 7:12" "#" "<==" "Mark"
cd /;  "ebible" "-m" "NASB" "Mark 11:22-26" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "John 20:31" "#" "<==" "sh"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Esther 2:6" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Esther 2:16" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Revelation 12:1-6" "#" "<==" "Revelation"
