cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Philippians 2:9-11" "#" "<==" "Philippians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Numbers 11:29" "#" "<==" "Numbers"
cd /root/notes;  "ebible" "-m" "ESV" "I John 3:8" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "James 4:12" "#" "<==" "James"
cd /root/notes;  "ebible" "-m" "ESV" "Rom 14:4" "#" "<==" "Rom"
cd /root/notes;  "ebible" "-m" "ESV" "Rom 2:1" "#" "<==" "Rom"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 26:2" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Matt 10:28" "#" "<==" "Matt"
cd /root/notes;  "ebible" "-m" "ESV" "Isa 33:22" "#" "<==" "Isa"
cd /root/notes;  "ebible" "-m" "ESV" "Heb 7:25" "#" "<==" "Heb"
cd /root/notes;  "ebible" "-m" "ESV" "Jas 5:9" "#" "<==" "Jas"
cd /root/notes;  "ebible" "-m" "ESV" "Rom 14:13" "#" "<==" "Rom"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 12:5" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Rom 9:20" "#" "<==" "Rom"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 12:5" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Job 38:2" "#" "<==" "Job"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Rom 9:20" "#" "<==" "Rom"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Matt 10:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Exodus 34-40" "#" "<==" "Exodus"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "Exodus 34-40" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 4:8" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 3:5-7" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "Hebrews 1:14" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 34:7" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "Mark 9:23" "#" "<==" "Mark"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 10" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ro 10:12-14" "#" "<==" "Ro"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ro 10:13" "#" "<==" "Ro"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 1:14" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Isaiah 43:19" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Mark 9:23" "#" "<==" "Mark"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalms 34:7" "#" "<==" "Psalms"
