cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "Psalm 119:105" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "2 Corinthians 5:10" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "1 John 4:1" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "1 John 4:1-2" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "1 John 4:1-3" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I John 4:14-15" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 11:21-23" "#" "<==" "Romans"
cd /;  "ebible" "-nbd" "-m" "NASB" "2 Corinthians 7:10" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "Acts 26:20" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 3:4" "#" "<==" "Romans"
