cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Mark 10:17-31" "#" "<==" "Mark"
cd /root/notes;  "ebible" "-m" "ESV" "Hebrews 1:13-14" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:2" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:3" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:4" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:5" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:6" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:7" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:8" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:8" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:12" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:19" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:17" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 1:12" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "II John 1:8" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Colossians 3:23-25" "#" "<==" "Colossians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Luke 6:35" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Luke 6:35-36" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Revelation of John 11:18" "#" "<==" "Revelation"
cd /root/notes;  "ebible" "-m" "ESV" "John 16:13" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 1:5" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 8:9" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "John 3:8" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 4:1-11" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 3:15-17" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Ephesians 6:17" "#" "<==" "Ephesians"
cd /root/notes;  "ebible" "-c" "-m" "KJV" "Genesis 1:18" "#" "<==" "withopts"
