cd /root/notes;  "ebible" "-m" "NASB" "Romans 12:21-26" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /;  "ebible" "-m" "NASB" "Isaiah 56:7" "#" "<==" "sh"
cd ;  "ebible" "-m" "NASB" " " "#" "<==" "Matthew"
cd /;  "ebible" "-m" "NASB" "Matthew 7:21-28" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "Matthew 7" "#" "<==" "Matthew"
cd /;  "ebible" "-m" "NASB" "Matthew 7:1-5" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Matthew 7:12" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "James 2" "#" "<==" "tmux: server"
cd /;  "ebible" "-m" "NASB" "James 2:13" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "James 2:24" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Luke 9:23" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "Matthew 18" "#" "<==" "tmux: server"
cd /;  "ebible" "-m" "NASB" "Matthew 18:26" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Matthew 18:4" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Matthew 20:25-28" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "2 Peter 3" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "2 Peter 3:11" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "1 John 3:3" "#" "<==" "sh"
