cd /root/notes;  "ebible" "-m" "ESV" "Galatians 6" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 26:18" "#" "<==" "Acts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I John \"2:15-17]]\"" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 3:22" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 3:21-24" "#" "<==" "I"
cd /;  "ebible" "-m" "ESV" "1 Corinthians 7:30-31" "#" "<==" "1"
cd /;  "ebible" "-m" "ESV" "1 Corinthians 7:29-31" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 7:29-31" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 7:33-35" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 7:33-35" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 9:25-27" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 11:32" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 7:38" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 7:37-38" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalm 16" "#" "<==" "Psalm"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 10:10" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Revelation of John 2:7" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 15:25-28" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 12:24" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I John 1:7" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Revelation of John 12:10" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 2:4" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 3:23" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 1:30" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 3:4" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Jeremiah 17:8" "#" "<==" "Jeremiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Jeremiah 17:1-8" "#" "<==" "Jeremiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Jeremiah 17:6-8" "#" "<==" "Jeremiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Jeremiah 17:5-8" "#" "<==" "Jeremiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 10:25-37" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Job 23:1-17" "#" "<==" "Job"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 14:21" "#" "<==" "John"
