cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Psalm 40:6-8" "#" "<==" "Psalm"
cd /;  "ebible" "-m" "ESV" "1 John 3:12" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Genesis \"4:3\\e2\\80\\935\"" "#" "<==" "Genesis"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Genesis 4:3-5" "#" "<==" "Genesis"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Acts 5:5" "#" "<==" "Acts"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Acts 5:11" "#" "<==" "Acts"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Acts 5:3-5" "#" "<==" "Acts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 5:1-5" "#" "<==" "Acts"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Deuteronomy 22:5" "#" "<==" "Deuteronomy"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "1 Corinthians 11:30-32" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Romans 3:25" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Isaiah 43" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Proverbs 3:5-6" "#" "<==" "Proverbs"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Deuteronomy 29:29" "#" "<==" "Deuteronomy"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Jeremiah 29:11" "#" "<==" "Jeremiah"
cd /root/.emacs.d/host/pen.el/docs;  "ebible" "-m" "ESV" "Ephesians 2:12-13" "#" "<==" "Ephesians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Deuteronomy 6:9" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:13-14" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Acts 7-11" "#" "<==" "Acts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "Acts 7-11" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Exodus 8-17" "#" "<==" "Exodus"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "Exodus 8-17" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:11" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:36" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:23" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:24" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Exodus 16:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Exodus 16:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Exodus 16:36" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Exodus 16:36" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Exodus 16:35" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:13-14" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Corinthians 11" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:10" "#" "<==" "Romans"
