cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Cor 6" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Corinthians 6:19-20" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Acts 1:8" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Mark 16:17" "#" "<==" "Mark"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Mark 1:23-26" "#" "<==" "Mark"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 10:25-37" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 24:9-13" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Luke 10:25-30" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Luke 10:25-27" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Luke 10:25-28" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Luke 10:25-28" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Isaiah 58" "#" "<==" "Isaiah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Isaiah 58" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Philippians 4:6-7" "#" "<==" "Philippians"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Hebrews 4:16" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 John 4:1" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 John 4:1-3" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 John 3:21" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 6:23" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 6:22-23" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 14:7" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 14:10" "#" "<==" "John"
