cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Timothy 1:7" "#" "<==" "2"
cd /root/notes;  "ebible" "-m" "ESV" "Galatians 5:22" "#" "<==" "Galatians"
cd /root/notes;  "ebible" "-m" "ESV" "Galatians 5:22-23" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 4:6-7" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 4:6" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Ephesians 4:4-5" "#" "<==" "Ephesians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Timothy 5:10" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Timothy 5:9-10" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 13:14" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 13:8" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 22:16" "#" "<==" "Acts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Corinthians 6:11" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Titus 3:5" "#" "<==" "Titus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Titus 3:5-7" "#" "<==" "Titus"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 13:9" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 4:17" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Isaiah 54:17" "#" "<==" "Isaiah"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 6:3-4" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Romans 14-16" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Romans 14:1" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Romans 14:1" "#" "<==" "Romans"
