cd /root/.pen/documents;  "ebible" "-m" "NASB" "Genesis 1:16" "#" "<==" "fast"
cd /root/.pen/documents;  "ebible" "-m" "NASB" "Genesis 1:19" "#" "<==" "fast"
cd /root/.pen/documents;  "ebible" "-m" "NASB" "Genesis 1:20" "#" "<==" "fast"
cd /root/.pen/documents;  "ebible" "-m" "NASB" "Genesis 1:21" "#" "<==" "fast"
cd /root/.pen/documents;  "ebible" "-m" "NASB" "Genesis 1:22" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "John 4:24" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "John 4:21" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "John 4:18" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "John 4:14" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "John 4:10" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "John 4:29" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "John 4:34" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "IriODomhnuill" "Luke 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "IriODomhnuill" "Luke 1:14" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Colossians 3:14" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Colossians 3:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "KJV" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "KJV" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "KJV" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "KJV" "#" "<==" "fast"
cd /root/.emacs.d/elpa/counsel-20210802.931;  "ebible" "-m" "NASB" "Genesis 1:14" "#" "<==" "fast"
cd /root/.emacs.d/elpa/counsel-20210802.931;  "ebible" "-m" "NASB" "Genesis 1:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "" "#" "<==" "1Kgs"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "NASB" "Genesis 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 1:10" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 1:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 1:7" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 1:8" "#" "<==" "fast"
