cd /root/notes;  "ebible" "-m" "ESV" "I Peter 5:1-5" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 5:1" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 5:2" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 8:16-17" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "1 Peter 4:11" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "1 PETER 4:12-19" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "1 PETER 4:12-19" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "1 PETER 4:11-19" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "1 PETER 4:12-19" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "1 Peter 2:9" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "2 Thessalonians 1:8" "#" "<==" "2"
cd /root/notes;  "ebible" "-m" "ESV" "2 Thessalonians 1:7-8" "#" "<==" "2"
cd /root/notes;  "ebible" "-m" "ESV" "2 Thessalonians 1:6-8" "#" "<==" "2"
cd /root/notes;  "ebible" "-m" "ESV" "2 Thessalonians 1:5-8" "#" "<==" "2"
cd /root/notes;  "ebible" "-m" "ESV" "James 1:20-22" "#" "<==" "James"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 5:21" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 1:30" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 1:30" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 5:21" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 5:21" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 4:11-12" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 3:27-31" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Hebrews 6:10" "#" "<==" "Hebrews"
cd /;  "ebible" "-m" "ESV" "Psalms 25:8" "#" "<==" "Psalms"
cd /;  "ebible" "-m" "ESV" "Psalms 25:8-14" "#" "<==" "Psalms"
cd /;  "ebible" "-m" "ESV" "Psalms 25:14" "#" "<==" "Psalms"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 6:10" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalms 25:14" "#" "<==" "Psalms"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "James 4:4-8" "#" "<==" "James"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "James 4:4-5" "#" "<==" "James"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Peter 3:18" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Peter 3:18-20" "#" "<==" "I"
cd /;  "ebible" "-m" "ESV" "I Peter 3" "#" "<==" "I"
cd //;  "ebible" "-m" "ESV" "2 Corinthians 5:11-21" "#" "<==" "2"
cd //;  "ebible" "-m" "ESV" "Ephesians 2:1-3" "#" "<==" "Ephesians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 2:11" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 28:19-20" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 11:21" "#" "<==" "Acts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 13:35" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 15:8" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 14:33" "#" "<==" "Luke"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 14:27" "#" "<==" "Luke"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 14:26" "#" "<==" "Luke"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Mark 13:13" "#" "<==" "Mark"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I John 2:15" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 14:25-33" "#" "<==" "Luke"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Phil 3:14" "#" "<==" "Phil"
cd /;  "ebible" "-m" "ESV" "Philippians 3:14" "#" "<==" "Philippians"
cd //;  "ebible" "-m" "ESV" "Philippians 3:13-14" "#" "<==" "Philippians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Philippians 3:7" "#" "<==" "Philippians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Philippians 3:7-8" "#" "<==" "Philippians"
cd /;  "ebible" "-m" "ESV" "Philippians 3:20-21" "#" "<==" "Philippians"
cd /;  "ebible" "-m" "ESV" "Hebrews 10:14" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 3:18" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 3:13" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews \"11:24=5\"" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 11:25" "#" "<==" "Hebrews"
cd /;  "ebible" "-m" "ESV" "III John 1:4-8" "#" "<==" "III"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Timothy 1:5" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Timothy 1:3" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Philippians 2:15" "#" "<==" "Philippians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 1:12" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 3:23-24" "#" "<==" "Colossians"
cd /;  "ebible" "-m" "ESV" "Colossians 3:23-24" "#" "<==" "Colossians"
cd //;  "ebible" "-m" "ESV" "Colossians 3:23-25" "#" "<==" "Colossians"
cd //;  "ebible" "-m" "ESV" "Colossians 3:22-25" "#" "<==" "Colossians"
cd /;  "ebible" "-m" "ESV" "Psalm 110:4" "#" "<==" "Psalm"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalm 82" "#" "<==" "Psalm"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalms 82:5-8" "#" "<==" "Psalms"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalms 82:1-8" "#" "<==" "Psalms"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 7" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Ps 110:4" "#" "<==" "Ps"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 7:28" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 11:27" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 11:27" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 11:22-32" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 3:16-17" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 19:19" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 19:20" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 19:20" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation of John 19:19" "#" "<==" "Revelation"
cd /;  "ebible" "-m" "ESV" "Psalms 82:6-8" "#" "<==" "Psalms"
cd /;  "ebible" "-m" "ESV" "Hebrews 2:11" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 2:11" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 4:1" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 4:1-2" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 4:1-3" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 10:5-6" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Timothy 1:5" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Gal 2:15-16" "#" "<==" "Gal"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 4:11-12" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 4:15" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 4:8" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 5:6-11" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 13:9" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Cor 4:14" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Cor 4:12" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Cor 4:8" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Cor 5:1-3" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Cor 5:5" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Cor 5:15" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 5:18" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 6:1" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 6" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 6:4-8" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Cor 7:1" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Cor 7:10" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 7:10" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Cor 7:15" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 2:15" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 2:15-16" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 4:9-12" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Rom 3:24-25" "#" "<==" "Rom"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I John 3:22" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 13:21Hebrews 13:16" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 13:21" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 11:6" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 11:5" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 10:36-39" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Thessalonians 4:1" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Thessalonians 2:4" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 1:10" "#" "<==" "Colossians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Ephesians 5:10" "#" "<==" "Ephesians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 1:10" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Corinthians 5:9" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 8:8" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Ephesians 2:8" "#" "<==" "Ephesians"
cd /;  "ebible" "-m" "ESV" "Ephesians 2:8-9" "#" "<==" "Ephesians"
cd /;  "ebible" "-m" "ESV" "Matthew 21:21" "#" "<==" "Matthew"
cd /;  "ebible" "-m" "ESV" "I John 4:17" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 3:21-31" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Romans 4:20-25" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Romans 6:16-18" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "James 4:4" "#" "<==" "James"
cd /;  "ebible" "-m" "ESV" "James 4:4-5" "#" "<==" "James"
cd /;  "ebible" "-m" "ESV" "James 4:4" "#" "<==" "James"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 10:6" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 10:5-6" "#" "<==" "2"
cd /;  "ebible" "-m" "ESV" "II Corinthians 10:5-18" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ro 4:2" "#" "<==" "Ro"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ga 2:16" "#" "<==" "Ga"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 3:36" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 3:32-36" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 3:32-40" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 3:36" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Peter 1:22" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 John 5:14" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 John 5:14-15" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 John 3:22" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 John 3:22-23" "#" "<==" "1"
cd /;  "ebible" "-m" "ESV" "I John 4:17" "#" "<==" "I"
cd /;  "ebible" "-m" "ESV" "Romans 4:11-12" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Luke 15:7" "#" "<==" "Luke"
