cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 8:36" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Psalm 19:1" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 4:18-25" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 4:15-17" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 4:11-14" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Romans 13:1-7" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hosea 6:3" "#" "<==" "Hosea"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Jeremiah 31:34" "#" "<==" "Jeremiah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Jeremiah 31:33-34" "#" "<==" "Jeremiah"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 6:3-4" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Timothy 6:3-4" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 6:1" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 6:-4" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 6:2-4" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 1:3-5" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "II Tim 4:3-4" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "II Tim 4:6-7" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "I Tim 4:6-7" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Titus 1:13-14" "#" "<==" "Titus"
cd /root/notes;  "ebible" "-m" "ESV" "II Peter 2:10-13" "#" "<==" "II"
cd /;  "ebible" "-m" "ESV" "Acts 17" "#" "<==" "Acts"
cd /;  "ebible" "-m" "ESV" "Acts 17" "#" "<==" "Acts"
