cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Corinthians 4:11-15" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 1:3-5" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 1:18--20" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 1:18-20" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 17:17" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "II Corinthians 4:18" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "Hebrews 11:7" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Exodus 12:1-2" "#" "<==" "Exodus"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Peter 3:21" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "John 8:55" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "John 8:4" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "John 8:44" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "1 John 5:10" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "I John 5:6" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "I John 5:9-13" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "I John 5:20" "#" "<==" "I"
