cd /root/notes;  "ebible" "-m" "ESV" "I Kings 11:19" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Kings 19:11" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Jeremiah 17:9" "#" "<==" "Jeremiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Nehemiah 13:14" "#" "<==" "Nehemiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Nehemiah 13:22" "#" "<==" "Nehemiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Nehemiah 13:30" "#" "<==" "Nehemiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Nehemiah 13:30-31" "#" "<==" "Nehemiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 64:6" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 64:5" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 64:6" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 64:5-6" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 64:6" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Phil 4:18" "#" "<==" "Phil"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 13:16" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 11:6" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Timothy 1:5" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 25:23" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "2 Corinthians 5:10" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Ephesians 6:8" "#" "<==" "Ephesians"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 25:6-6" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 25:6-7" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 25:21" "#" "<==" "Psalms"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 5:29" "#" "<==" "Acts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 12:12" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Mark 3:4" "#" "<==" "Mark"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Mark 3:4-5" "#" "<==" "Mark"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Proverbs 3:29-35" "#" "<==" "Proverbs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Proverbs 3:29-30" "#" "<==" "Proverbs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 13:10" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "1 Corinthians 16:14" "#" "<==" "1"
cd /;  "ebible" "-m" "ESV" "I Corinthians 16:14" "#" "<==" "I"
cd //;  "ebible" "-m" "ESV" "I Corinthians 16:13-14" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 16:13-14" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Timothy 2:13-15" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Philippians 3:3" "#" "<==" "Philippians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 2:11" "#" "<==" "Colossians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 2:11-15" "#" "<==" "Colossians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 2:11-12" "#" "<==" "Colossians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 8:39" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 3:7-9" "#" "<==" "Galatians"
