cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 8:42" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 8:41-2" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 8:42" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Peter 4:19" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Peter 3:17" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalms 11:5" "#" "<==" "Psalms"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:8" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:7" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:10" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:9-10" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:10" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:12-14" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Peter 4:5-10" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Peter 4:10-11" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 6:38" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 10:17-21" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 14:31" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Peter 4:1-5" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Peter 4:1-6" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "II John 1:7" "#" "<==" "II"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:1-10" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:1" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:1-10" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:1" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Mark 12:17" "#" "<==" "Mark"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Mark 15:14" "#" "<==" "Mark"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 23:3" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 13:21" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Philippians 2:13" "#" "<==" "Philippians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 2:8" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "ESV" "Ephesians 1:21" "#" "<==" "Ephesians"
cd /root/notes;  "ebible" "-m" "ESV" "Ephesians 1:20-21" "#" "<==" "Ephesians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Philippians 2:3-5" "#" "<==" "Philippians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 4:12-13" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 4:10" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Philippians 2:3" "#" "<==" "Philippians"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 24:16" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 24:14-16" "#" "<==" "Acts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 13:10" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 8:1" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 8:3-4" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Isaiah 42:8" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Isaiah 55:11" "#" "<==" "Isaiah"
cd /root/notes;  "ebible" "-m" "ESV" "Philippians 3:21" "#" "<==" "Philippians"
cd /root/notes;  "ebible" "-m" "ESV" "Jude 1:4" "#" "<==" "Jude"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 15:45" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 15:45" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "John 5:21" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Gen 2:7" "#" "<==" "Gen"
cd /root/notes;  "ebible" "-m" "ESV" "John 5:21" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Rom 8:2" "#" "<==" "Rom"
cd /root/notes;  "ebible" "-m" "ESV" "John 14:6" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 6:33" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 5:21" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-c" "-m" "KJV" "Titus 1:2" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-c" "-m" "KJV" "Isaiah 32:6," "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-c" "-m" "KJV" "Romans 1:18" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-c" "-m" "KJV" "II Timothy 2:16" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 12:29" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 12:28-29" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 14:7" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 9:20-21" "#" "<==" "Revelation"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 6:3-4" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Romans 14-16" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Romans 14:10-18" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 14:18" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Romans 14:12" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 14:18" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 14:18" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 14:12" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 14:18" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 14:18" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 11:6" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 15:18" "#" "<==" "John"
