cd /root/notes;  "ebible" "-m" "ESV" "Romans 5:1-5" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "John 10:9" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "James 4:6" "#" "<==" "James"
cd /root/notes;  "ebible" "-m" "ESV" "James 4:6-7" "#" "<==" "James"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 1:23" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 8:11" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "I Peter 1:22-25" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Thessalonians 4:2-8" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Peter 1:5-10" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "I Timothy 2:12" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 14:34" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 14:33-34" "#" "<==" "I"
