cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "I Corinthians 14-16" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "I Corinthians 14-16" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "I Corinthians 14:31-33" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Corinthians 3:17" "#" "<==" "II"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "II Corinthians 3-7" "#" "<==" "II"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "II Corinthians 3-7" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "ESV" "II Corinthians 3:6" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "II Corinthians 3:18" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "II Corinthians 3:7" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "II Corinthians 3:7-9" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "II Corinthians 3:6-9" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers/deliverance;  "ebible" "-m" "ESV" "Zechariah 2:5" "#" "<==" "Zechariah"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers/deliverance;  "ebible" "-m" "ESV" "Psalm 149:9" "#" "<==" "Psalm"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:31-32" "#" "<==" "Matthew"
