cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 6:47" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:27" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:46" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:47" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:42" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:43" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:42" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:43" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:45" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:47" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:47" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:46" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Thessalonians 2:13-15" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:5" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:7" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:8" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:8" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:13" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalm 5:5" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Corinthians 1:30-31" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Corinthians 1:30-31" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 10:10" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Galatians 6:14" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Thessalonians 4:3" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Thessalonians 2:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:11" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Thessalonians 2:5" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I Corinthians 1:30-31" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalm 5:5" "#" "<==" "Psalm"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Corinthians 1" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "II Timothy 3:15" "#" "<==" "II"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 8:30" "#" "<==" "Romans"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "James 1-2" "#" "<==" "James"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "James 1-2" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "James 1:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "James 1:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "James 1:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "James 1:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "James 1:6" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "James 1:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Acts 26:18" "#" "<==" "Acts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "James 1-2" "#" "<==" "James"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "James 1-2" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 10:10" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalms 31:23" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 1:26" "#" "<==" "Genesis"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "2 Cronicals" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "2 Cron 36:13" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "2 Cronicles 36:13" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "2 Chronicles 36:13" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Romans 2:4" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 3:13" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "ESV" "Genesis 4:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 5:2" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 5:3" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 5:4" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 5:5" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 5:6" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 5:7" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 5:8" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 5:9" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Cor 5" "#" "<==" "2"
