cd /root/notes;  "ebible" "-m" "ESV" "II Corinthians 3:15-18" "#" "<==" "II"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Proverbs 5:21" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 20:35" "#" "<==" "Acts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 John 3:20-24" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 John 3:24" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 John 1:9" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Proverbs 6:32" "#" "<==" "Proverbs"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Col 1:17" "#" "<==" "Col"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Prov 3:19" "#" "<==" "Prov"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Ps 104:24" "#" "<==" "Ps"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Proverbs 8:22-32" "#" "<==" "Proverbs"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 1:1-2" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Job 28:26-28" "#" "<==" "Job"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Proverbs 14:26" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:3" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:33-35" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "II Corinthians 3-7" "#" "<==" "II"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "II Corinthians 3-7" "#" "<==" "bash"
