cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "I Thessalonians 3-5" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "I Thessalonians 3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:23-24" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "II Thessalonians 1-2" "#" "<==" "II"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "II Thessalonians 1-2" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "II Thessalonians 1:8" "#" "<==" "II"
cd /;  "ebible" "-m" "ESV" "John 4" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Isaiah 2:6-8" "#" "<==" "Isaiah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matt 16:18-19" "#" "<==" "Matt"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "-nem" "Matthew 16:18-19" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 21" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matt 16:18-19" "#" "<==" "Matt"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "II Timothy 3:16-17" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 7:22-28" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 2:9" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 1:9" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 1:9" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 1:9" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Proverbs 28:13" "#" "<==" "Proverbs"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Proverbs 28:9" "#" "<==" "Proverbs"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Ps 32:5" "#" "<==" "Ps"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:23-24" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "I Thessalonians 3-5" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "I Thessalonians 3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "1Cor 4:4" "#" "<==" "1Cor"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "1 Cor 4:4" "#" "<==" "1"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "1 Cor 4:4" "#" "<==" "1"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "I Thessalonians 3-5" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "I Thessalonians 3-5" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "I Thessalonians 3-5" "#" "<==" "I"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "I Thessalonians 3-5" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Corinthians 6:20" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 12:1" "#" "<==" "Romans"
