cd /root/notes;  "ebible" "-m" "ESV" "Galatians 5:17" "#" "<==" "Galatians"
cd /root/notes;  "ebible" "-m" "ESV" "Galatians 5:17-18" "#" "<==" "Galatians"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Psalms 57:1" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "II Corinthians 9:6-9" "#" "<==" "II"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 5:3" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 5:3" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "John 13:6-7" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 4:3" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "John 1:13" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 13:6-9" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 13:12-16" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 13:34-35" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I John 4:7" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I John 4:6-112" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "I John 4:6-12" "#" "<==" "I"
