cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Psalm 40:3" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalm 40:3" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalm 40:3" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalm 40:3" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Mark 10:18" "#" "<==" "Mark"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:15" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:16" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:15" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:17" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:18" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:19" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:19" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:19" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:20" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:21" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:22" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:22" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:22" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:23" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:24" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:25" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:26" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:27" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:29" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:28" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:29" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:30" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:31" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Mark 10:32" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 2:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:2" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:3" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:4" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:31" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:2" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:3" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 3" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Ps 53:1-3" "#" "<==" "Ps"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalms 53:1-3" "#" "<==" "Psalms"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Leviticus 17:11" "#" "<==" "Leviticus"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 9:22" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 1:29" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 John 3:5" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 John 2:2" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Hebrews 9:26" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Peter 3:18" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 53:5" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Mark 10:45" "#" "<==" "Mark"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 3:25" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Peter 2:24" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 15:3" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "NASB" "Romans 10:2" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "NASB" "Romans 10:3" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "NASB" "Romans 10:4" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "NASB" "Romans 10:5" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "NASB" "Romans 10:4" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "NASB" "Romans 10:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:15-16" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Acts 12-14" "#" "<==" "Acts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "Acts 12-14" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Acts 12:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Acts 12:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 12:13-15" "#" "<==" "Acts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:3" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:38" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:39" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:39" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:38" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:38" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:39" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:39" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Acts 13:40" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 12:44-50" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Exodus 14:21-22" "#" "<==" "Exodus"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Exodus 14:21-22" "#" "<==" "Exodus"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Exodus 14:21-22" "#" "<==" "Exodus"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 5:45" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Deut 18:15-19" "#" "<==" "Deut"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 2:20" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 5:20" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Colossians 3:3-4" "#" "<==" "Colossians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 1:1-3" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 2:25" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 3:16" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 3:15" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 5:11-13" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 John 3:2" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Corinthians 1:4-8" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 6:39" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalm 110" "#" "<==" "Psalm"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-c" "-m" "ESV" "Matthew 22:14" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "II Thessalonians 2" "#" "<==" "II"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 17:19" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 17:18" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Corinthians 2:11" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Corinthians 2:11-12" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 5:6" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Peter 1:8 NLT" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Peter 1:8" "#" "<==" "1"
cd /;  "ebible" "-bd" "-m" "ESV" "1 Peter 1:8" "#" "<==" "sh"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Matthew 5:15-16" "#" "<==" "Matthew"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "James 1-2" "#" "<==" "James"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "James 1-2" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Luke 11:28" "#" "<==" "Luke"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "Gal 5:1" "#" "<==" "Gal"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Acts 12-14" "#" "<==" "Acts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "-nem" "Acts 12-14" "#" "<==" "bash"
