cd /root/notes;  "ebible" "-m" "ESV" "2 Kings 24:17" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Kings 24:17" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 15:14" "#" "<==" "Matthew"
cd /;  "ebible" "-m" "ESV" "Matthew 15:14" "#" "<==" "Matthew"
cd //;  "ebible" "-m" "ESV" "Matthew 15:10-20" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Proverbs 4:21-23" "#" "<==" "Proverbs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Romans 14:4" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 14:4" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 14:4-18" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "Jude 1:4" "#" "<==" "Jude"
cd /root/notes;  "ebible" "-m" "ESV" "Ephesians 6:9" "#" "<==" "Ephesians"
cd /root/notes;  "ebible" "-m" "ESV" "Ephesians 6:9" "#" "<==" "Ephesians"
cd /root/notes;  "ebible" "-m" "ESV" "John 15:20" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 12:42" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 1:7" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 1:29-31" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 1:28-31" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 3:7" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 8:13" "#" "<==" "Proverbs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 7:17-20" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 7:15-20" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 12:33-35" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 12:48-50" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 12:30" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 23:8-11" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 22:9" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 22:8-9" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 7:1-3" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 7:1-4" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 7:1-5" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 7:1-6" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 7:1-7" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation 7:1-8" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Thessalonians 1:9-10" "#" "<==" "1"
cd /;  "ebible" "-m" "ESV" "1 Thessalonians 1:9-10" "#" "<==" "1"
cd //;  "ebible" "-m" "ESV" "I Thessalonians 4:3-8" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 5:14" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 5:14-15" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Genesis 35:2-3" "#" "<==" "Genesis"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Joshua 24:23" "#" "<==" "Joshua"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 8:3-7" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 35:2" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 35:2-3" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "Joshua 24:15" "#" "<==" "Joshua"
cd /root/notes;  "ebible" "-m" "ESV" "Revelation of John 16:13-15" "#" "<==" "Revelation"
cd /root/notes;  "ebible" "-m" "ESV" "Revelation of John 9:20-21" "#" "<==" "Revelation"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 17:30" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 17:30-32" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "I Thessalonians 5:23" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:18" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:4" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:1" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:5" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "John 8:42" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Jude 1:4" "#" "<==" "Jude"
cd /root/notes;  "ebible" "-m" "ESV" "Jude 1:8" "#" "<==" "Jude"
cd /;  "ebible" "-m" "ESV" "I Corinthians 8:3-7" "#" "<==" "I"
cd /;  "ebible" "-m" "ESV" "Acts 17:30-32" "#" "<==" "Acts"
cd //;  "ebible" "-m" "ESV" "Acts 17:29-31" "#" "<==" "Acts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 17:29-32" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 82:6" "#" "<==" "Psalms"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 2:18" "#" "<==" "Colossians"
cd /root/notes;  "ebible" "-m" "ESV" "Psalms 82:6-8" "#" "<==" "Psalms"
cd /root/notes;  "ebible" "-m" "ESV" "John 10:34-38" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Deut 6:13" "#" "<==" "Deut"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matt 4:9-10" "#" "<==" "Matt"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matt 14:33" "#" "<==" "Matt"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Heb 1:6" "#" "<==" "Heb"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Rev 1:17" "#" "<==" "Rev"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 20:28" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 1:1-3" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matt 28:18" "#" "<==" "Matt"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 21:17" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Rom 8:35-39" "#" "<==" "Rom"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Phil 2:9-11" "#" "<==" "Phil"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 20:28" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 1:24" "#" "<==" "Acts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Rev 19:16" "#" "<==" "Rev"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 2:11" "#" "<==" "Luke"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Rev 1:7-8" "#" "<==" "Rev"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 1:3" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Heb 1:2-3" "#" "<==" "Heb"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matt 8:23-27" "#" "<==" "Matt"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Isaiah 9:6" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matt 9:1-8" "#" "<==" "Matt"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 1:4" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 5:21" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Rev 3:21" "#" "<==" "Rev"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Rev 5:13" "#" "<==" "Rev"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 10:27-33" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalm 2:8" "#" "<==" "Psalm"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 2:9" "#" "<==" "Colossians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 2:9-10" "#" "<==" "Colossians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalms 91:5-7" "#" "<==" "Psalms"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Proverbs 30:4" "#" "<==" "Proverbs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 3:16-17" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 3:13-17" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 3:5-8" "#" "<==" "Colossians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 1:18" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalms 91:5-8" "#" "<==" "Psalms"
cd /;  "ebible" "-m" "ESV" "Revelation of John 14:7" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 5:23" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 5:22-23" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 8:14-21" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 3:9" "#" "<==" "1"
cd /;  "ebible" "-m" "ESV" "Proverbs 16:6" "#" "<==" "Proverbs"
cd /;  "ebible" "-m" "ESV" "Proverbs 14:27" "#" "<==" "Proverbs"
cd /;  "ebible" "-m" "ESV" "Proverbs 23:17" "#" "<==" "Proverbs"
cd /;  "ebible" "-m" "ESV" "Acts 9:31" "#" "<==" "Acts"
cd /;  "ebible" "-m" "ESV" "Proverbs 8:13" "#" "<==" "Proverbs"
cd /;  "ebible" "-m" "ESV" "Matthew 12:30" "#" "<==" "Matthew"
cd //;  "ebible" "-m" "ESV" "Matthew 12:28-30" "#" "<==" "Matthew"
cd //;  "ebible" "-m" "ESV" "Matthew 13:37-43" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 3:3" "#" "<==" "Galatians"
