cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Psalm 142:2" "#" "<==" "Psalm"
cd /root/notes;  "ebible" "-m" "ESV" "Genesis 28:15" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "ESV" "John 13:1" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 13:1" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "II Corinthians 9:6" "#" "<==" "II"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "II Corinthians 9:7" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 9:15-16" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "James 4:6" "#" "<==" "James"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 6:14" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 6:14-15" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 6:12-15" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 9:5" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:1" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I John 5:1-2" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Galatians 3:11" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 12:1-2" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 6:15" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 6:14-15" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 6:8-15" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 5:47-48" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 5:44-48" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 6:1-4" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 6:10" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 6:12" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 7:21" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 7:24-27" "#" "<==" "Matthew"
