cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 15:26" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 32:30" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 32:30" "#" "<==" "Genesis"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "KJV" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "KJV" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "KJV" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "KJV" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Exodus" "#" "<==" "Exodus"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /;  "ebible" "-m" "NASB" "Genesis 32:30" "#" "<==" "Genesis"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /;  "ebible" "-nbd" "-m" "NASB" "Matthew 26:13" "#" "<==" "sh"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 1:9" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 1:9" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:7" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:6" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:5" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:5" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:8" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:7" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:6" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Romans 2:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Romans 2:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:7" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:7" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:5" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:9" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Genesis 1:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:2" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:3" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:6" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:6" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:7" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:8" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:7" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:8" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /;  "ebible" "-nbd" "-m" "NASB" "1 John 1:5-10" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "I John 1" "#" "<==" "I"
cd /;  "ebible" "-nbd" "-m" "NASB" "I John 2:4-6" "#" "<==" "sh"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Romans" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:8" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:7" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 1:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-ca" "-m" "NASB" "Hebrews 2:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:7" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:8" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 2:4" "#" "<==" "fast"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:7" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:7" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:7" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:7" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-bd" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "in-tm"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-bd" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "in-tm"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-bd" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "in-tm"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-bd" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "in-tm"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-bd" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "in-tm"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-bd" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "in-tm"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-bd" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "in-tm"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "bash"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:5" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:3" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:2" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:2" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:6" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:6" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:3" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:7" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:8" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:1" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:2" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:3" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:4" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 22:7" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 21:8" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 21:1" "#" "<==" "fast"
cd /root/.pen/glossaries;  "ebible" "-c" "-m" "NASB" "Revelation of John 21:2" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:10" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:11" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:8" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:10" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:7" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:13" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:12" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:14" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:11" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:10" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:9" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:8" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:12" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:4" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Hebrews 3:6" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "NASB" "Hebrews 3:6" "#" "<==" "Hebrews"
cd /root/notes;  "ebible" "-m" "NASB" "Hebrews 3:6" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/scripts;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Hebrews 3:6" "#" "<==" "fast"
cd /root/notes;  "ebible" "-nbd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Genesis 1:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Genesis 1:7" "#" "<==" "fast"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "tmux: server"
cd /root/notes;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "sh"
cd //;  "ebible" "-m" "NASB" "-nem" "Romans 3:21-26" "#" "<==" "bash"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "sh"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "bash"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "shx"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "shx"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "shx"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "in-tty"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "in-tty"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "in-tty"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "sh"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "sh"
cd /;  "ebible" "-bd" "-m" "NASB" "Romans 3:21-26" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Romans" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "I Thessalonians" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "NASB" "I Thessalonians" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "NASB" "II Thessalonians" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "NASB" "II Thessalonians" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "NASB" "I Thessalonians" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "NASB" "Nehemiah" "#" "<==" "Nehemiah"
cd /root/notes;  "ebible" "-m" "NASB" "Nehemiah" "#" "<==" "Nehemiah"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 1:18" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 3:6" "#" "<==" "sh"
cd /root/.emacs.d/host/pen.el/scripts;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/scripts;  "ebible" "-m" "NASB" "Romans 3:21-26" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "II Thessalonians" "#" "<==" "II"
cd /root/notes;  "ebible" "-m" "NASB" "Romans" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "NASB" "Titus" "#" "<==" "Titus"
cd /root/notes;  "ebible" "-m" "NASB" "Titus" "#" "<==" "Titus"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 6:35" "#" "<==" "sh"
cd /;  "ebible" "-bd" "-m" "NASB" "John 6:35" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 5:22" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 5:22-24" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 5:21-24" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 7:18" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 7:37-39" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "Matthew 11:27" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "Psalm 22" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "Psalm 22" "#" "<==" "Psalm"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 32:30" "#" "<==" "Genesis"
cd /root/notes;  "ebible" "-m" "NASB" "Psalm 22" "#" "<==" "Psalm"
cd /;  "ebible" "-nbd" "-m" "NASB" "Psalms 22:8" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "I Peter 3:9" "#" "<==" "I"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "Matthew 5:38-48" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "Matthew 5:38" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "NASB" "Matthew 5:38-39" "#" "<==" "Matthew"
