cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 8:31-32" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 16:14" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 13:39" "#" "<==" "Acts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 6:16-18" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 6:16-18" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Psalm 35:27" "#" "<==" "Psalm"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Colossians 2:16-17" "#" "<==" "Colossians"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Matthew 16:24" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 16:25" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Ps 102:28" "#" "<==" "Ps"
cd /root/notes;  "ebible" "-m" "ESV" "Ps 89:50" "#" "<==" "Ps"
cd /root/notes;  "ebible" "-m" "ESV" "Ps 135:14" "#" "<==" "Ps"
cd /root/notes;  "ebible" "-m" "ESV" "Ps 135:1" "#" "<==" "Ps"
cd /root/notes;  "ebible" "-m" "ESV" "Mark 8:35" "#" "<==" "Mark"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 14:22" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 14:21-22" "#" "<==" "Acts"
