cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Luke 15" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Rom 7:25" "#" "<==" "Rom"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "Isaiah 63" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "Isaiah 64" "#" "<==" "Isaiah"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 6:1" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "NASB" "Genesis 8:1" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "NASB" "Isaiah 64:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 7" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "1 John 4:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "1 John 4:16-17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Rom 7:25" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 8:32" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "Romans 8" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "Romans 8:32-39" "#" "<==" "Romans"
