cd /;  "ebible" "-m" "ESV" "Psalms 91:1-8" "#" "<==" "Psalms"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I John 4:17" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Rom 5:6" "#" "<==" "Rom"
cd /root/notes;  "ebible" "-m" "ESV" "Rom 8:7" "#" "<==" "Rom"
cd /root/notes;  "ebible" "-m" "ESV" "Eph 2:1" "#" "<==" "Eph"
cd /root/notes;  "ebible" "-m" "ESV" "Eph 2:1" "#" "<==" "Eph"
cd /root/notes;  "ebible" "-m" "ESV" "Eph 2:5" "#" "<==" "Eph"
cd /root/notes;  "ebible" "-m" "ESV" "Titus 3:3-5" "#" "<==" "Titus"
cd /root/notes;  "ebible" "-m" "ESV" "John 6:44" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 6:44-51" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "John 6:44-51" "#" "<==" "John"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 10:29-31" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 16:33" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Proverbs 18:18" "#" "<==" "Proverbs"
cd /root/notes;  "ebible" "-m" "ESV" "Acts 1:26" "#" "<==" "Acts"
cd /root/notes;  "ebible" "-m" "ESV" "Isaiah 57:21" "#" "<==" "Isaiah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Isaiah 57:21" "#" "<==" "Isaiah"
cd /root/notes;  "ebible" "-m" "ESV" "Deuteronomy 22:25" "#" "<==" "Deuteronomy"
cd /root/notes;  "ebible" "-m" "ESV" "Deuteronomy 22:27" "#" "<==" "Deuteronomy"
cd /root/notes;  "ebible" "-m" "ESV" "Deuteronomy 22:26-27" "#" "<==" "Deuteronomy"
cd /root/notes;  "ebible" "-m" "ESV" "Deuteronomy 22:25-27" "#" "<==" "Deuteronomy"
cd /root/notes;  "ebible" "-m" "ESV" "Deuteronomy 22:24" "#" "<==" "Deuteronomy"
cd /root/notes;  "ebible" "-m" "ESV" "Deuteronomy 22:23-24" "#" "<==" "Deuteronomy"
cd /root/notes;  "ebible" "-m" "ESV" "Deuteronomy 22:13-29" "#" "<==" "Deuteronomy"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 2:52" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 2:52" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 2:50-52" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 2:50-52" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "Luke 2:52" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 2:52" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 2:52" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 2:41-52" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Galatians 3:7-9" "#" "<==" "Galatians"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 4:2" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I John 4:2-3" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "James 2" "#" "<==" "James"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "James 2:22-26" "#" "<==" "James"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Rom 9:22" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Rom 9:22-23" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Rom 9:22-24" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Rom 9:20-24" "#" "<==" "Rom"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 19:11-16" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 10:13" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 10:9-13" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 10:8-13" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalms 83:18" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalms 83:17-18" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 2:2" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 2:1-2" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 2:11" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 28:17" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 28:16-17" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "1 Peter 4:7" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "1 Peter 4:7-11" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1 Peter 4:7-11" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Jas 5:8-9" "#" "<==" "Jas"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1Pet 1:13" "#" "<==" "1Pet"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "1Pet 5:8" "#" "<==" "1Pet"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2Tim 4:5" "#" "<==" "2Tim"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 21:34" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Heb 10:25" "#" "<==" "Heb"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Heb 10:24-25" "#" "<==" "Heb"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Cor. 4:15" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Ex 15:2" "#" "<==" "Ex"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Acts 2:22" "#" "<==" "Acts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 2:22" "#" "<==" "Genesis"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Revelation of John 2:22" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 2:22" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matt 2:22" "#" "<==" "Matt"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Mark 2:22" "#" "<==" "Mark"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Luke 2:22" "#" "<==" "Luke"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Galatians 2:22" "#" "<==" "Galatians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Exodus 2:22" "#" "<==" "Exodus"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Leviticus 2:22" "#" "<==" "Leviticus"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 4" "#" "<==" "Romans"
