cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "ESV" "I John 4:6" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "ESV" "I John 4:9" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "Proverbs 15:3" "#" "<==" "Proverbs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "-nem" "Luke 16-20" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "-nem" "Luke 16-20" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "NASB" "Matthew 5:7-8" "#" "<==" "Matthew"
cd //;  "ebible" "-m" "ESV" "-nem" "Matthew 5:7-8" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "Genesis 27-28" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-c" "-m" "ESV" "Genesis 22:5" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Isaiah 54:17" "#" "<==" "Isaiah"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Isaiah 54:16-17" "#" "<==" "Isaiah"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "ebible" "-m" "ESV" "-nem" "Genesis 27-28" "#" "<==" "bash"
