cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Rom 7:23-25" "#" "<==" "Rom"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 1:9" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 8:1-4" "#" "<==" "Romans"
cd /root/notes;  "ebible" "-m" "ESV" "2 Chronicles 7:14" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 2:7-11" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "John 2:7-11" "#" "<==" "John"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:6" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:6" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:6" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:11" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:11" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:11" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:11" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:11" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:12" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:12" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "NASB" "John 2:12" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Revelation of John 3:9" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-c" "-m" "KJV" "Rev 2:9" "#" "<==" "withopts"
cd /root/notes;  "ebible" "-m" "ESV" "Revelation of John 2:9" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Isa 60:14" "#" "<==" "Isa"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Isa 49:23" "#" "<==" "Isa"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Isa 60:14" "#" "<==" "Isa"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-c" "-m" "KJV" "Isa 45:14" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-c" "-m" "KJV" "Isa 43:4" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-c" "-m" "KJV" "Zech 8:20-23" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-c" "-m" "KJV" "Acts 16:37-39" "#" "<==" "withopts"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-c" "-m" "KJV" "1Sam 2:36" "#" "<==" "withopts"
