cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Corinthians \"10:5-6]]\"" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 2:11" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 2:11-16" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "I Corinthians 2:16" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Hebrews 12:11" "#" "<==" "Hebrews"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Thessalonians 1:8-12" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Thessalonians 1:7-12" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Thessalonians 1:6-12" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Thessalonians 1:5-12" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Thessalonians 1:4-12" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Thessalonians 1:1-12" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Thessalonians 1:1-2" "#" "<==" "II"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "II Thessalonians 1:3" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 14:17-20" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 19:23-26" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Ephesians 3:5" "#" "<==" "Ephesians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "1 Corinthians 2:4" "#" "<==" "1"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Peter 1:19" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Ephesians 2:20-22" "#" "<==" "Ephesians"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians \"2:4,5\"" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Corinthians 15" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 13:8" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 13:10" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 Corinthians 13:4-8" "#" "<==" "1"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Jeremiah 33:3" "#" "<==" "Jeremiah"
cd /;  "ebible" "-m" "ESV" "Matthew 7:9-12" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 5:45" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 8:13" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 8:14" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Exodus 20:13" "#" "<==" "Exodus"
cd /;  "ebible" "-m" "ESV" "Romans 14:18-21" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "John 6:29" "#" "<==" "John"
cd /;  "ebible" "-m" "ESV" "Ex 20:2-3" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:4-6" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:7" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:8-11" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:12" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:13" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:14" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:15" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:16" "#" "<==" "Ex"
cd /;  "ebible" "-m" "ESV" "Ex 20:17" "#" "<==" "Ex"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 14:22" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Romans 14:18" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Romans 14:22" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Romans 14:14-15" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Romans 14:12" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Ephesians 4:28" "#" "<==" "Ephesians"
cd /;  "ebible" "-m" "ESV" "Romans 14:23" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Romans 14:16" "#" "<==" "Romans"
