cd //;  "ebible" "-m" "NASB" "John 20:1" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "1 Corinthians 9:21" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "1 Corinthians 9:20-21" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Revelation 14:12" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "1 John 4:4" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Habakkuk 2:4" "#" "<==" "Habakkuk"
cd /root/.pen/documents/agenda;  "ebible" "-m" "NASB" "Romans" "#" "<==" "Romans"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 1:1-4" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "John 1:1-4" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 11:11-13" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 11" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Matthew 11:1" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Matthew 11:2" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Matthew 11:4" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-c" "-m" "NASB" "Matthew 11:5" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Daniel 2:47" "#" "<==" "Daniel"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "2 Peter 1:4" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "2 Peter 1:4" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Habakkuk 2:4" "#" "<==" "Habakkuk"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 13:34" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 13:34-35" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 5:5" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 5:4-5" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Cor 13" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Psalms 96:4-5" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Joshua 22:22" "#" "<==" "Joshua"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Psalms 82:1" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 5:17-20" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 17" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 17" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 15:9-12" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 5:46" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "1 Corinthians 9:21" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "1 Corinthians 9:21" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 19:7-12" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 19:7" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 19:7-8" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Corinthians 3:15" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Corinthians 3:15-16" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Corinthians 3:14-16" "#" "<==" "II"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "2 Corinthians 3" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "II Corinthians 4:11" "#" "<==" "II"
