cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Hosea 2:20" "#" "<==" "Hosea"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "Revelation 14:12" "#" "<==" "Revelation"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "NASB" "John 17:4" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 18:3-4" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 18:1-4" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 18:1-5" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Psalm 82:8" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 18:21-23" "#" "<==" "Matthew"
cd /root/.pen/documents/bible-notes/verse;  "ebible" "-m" "NASB" "Philippians 1:6" "#" "<==" "Philippians"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "John 6:40" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "1 John 5:12" "#" "<==" "1"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 7:21-23" "#" "<==" "Matthew"
