cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Genesis 1:4" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Genesis 1:14" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:8" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:10" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:10" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:12" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:15" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:11" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:12" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:16" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:17" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:19" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Genesis 1:26" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 11:7" "#" "<==" "Hebrews"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:1" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:6" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:8" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:8" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:9" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:10" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:25" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:12" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:15" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:19" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-m" "ESV" "Hebrews 11:20" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 10:41" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Corinthians 3:14" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 11:18" "#" "<==" "Revelation"
cd /root/.emacs.d/host/pen.el/src;  "ebible" "-ca" "-m" "ESV" "Hebrews 11:14" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Samuel 26:23" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 11:1" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Hebrews 11:6" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 17:19" "#" "<==" "Genesis"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Genesis 22:2" "#" "<==" "Genesis"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "I Samuel 26:23" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 12:7" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 12:5-8" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 12:11-13" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 12:5-21" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Matthew 12:7" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 4:16" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 4:14-16" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Deuteronomy 18:21-22" "#" "<==" "Deuteronomy"
cd /root/.pen/documents/notes;  "ebible" "-m" "IriODomhnuill" "Luke 24:23" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "IriODomhnuill" "Luke 24:13" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "IriODomhnuill" "Luke 24:23" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "IriODomhnuill" "Luke 24:20" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "IriODomhnuill" "Luke 24:21" "#" "<==" "withopts"
cd /root/.pen/documents/notes;  "ebible" "-m" "IriODomhnuill" "Luke 24:13" "#" "<==" "withopts"
cd /root/.emacs.d/host/pen.el;  "ebible" "-m" "ESV" "Romans 10:17" "#" "<==" "Romans"
