cd /root/notes;  "ebible" "-c" "-m" "NASB" "Romans 7:11" "#" "<==" "fast"
cd /;  "ebible" "-m" "NASB" "Isaiah 55:8-9" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Isaiah 55:8-9" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "Isaiah 55:8-9" "#" "<==" "Isaiah"
cd /root/notes;  "ebible" "-m" "NASB" "Isaiah 55:8-9" "#" "<==" "Isaiah"
cd /root/notes;  "ebible" "-m" "NASB" "Isaiah 55:8-9" "#" "<==" "Isaiah"
cd /;  "ebible" "-m" "NASB" "Isaiah 55:8-9" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Romans 1:21" "#" "<==" "sh"
cd /root/notes;  "ebible" "-m" "NASB" "Ezekiel 36" "#" "<==" "Ezekiel"
cd /;  "ebible" "-m" "NASB" "Ezekiel 36:23-29" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "1 John 1:9-10" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Titus 3:5" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Ephesians 5:26" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Ephesians 5:25-27" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "John 15:3" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Ezekiel 3:18-19" "#" "<==" "sh"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Genesis 3:3" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Genesis 3:4" "#" "<==" "fast"
cd /;  "ebible" "-m" "NASB" "Ephesians 2:6" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Ephesians 2:5-6" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Ephesians 2:4-6" "#" "<==" "sh"
cd /;  "ebible" "-m" "NASB" "Ephesians 2:4-7" "#" "<==" "sh"
