cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 6:12" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 10:23" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 10:24" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 10:19-21" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 10:19-21" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "I Corinthians 10:31-33" "#" "<==" "I"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew \"14:28-31]]\"" "#" "<==" "Matthew"
cd /root/notes;  "ebible" "-m" "ESV" "Matthew 14:28-31" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "James 1:22" "#" "<==" "James"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "James 1:21-24" "#" "<==" "James"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Romans 4:20-22" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "James 1:21-24" "#" "<==" "James"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "James 1:21-24" "#" "<==" "James"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "1 John 4:18" "#" "<==" "1"
cd /root/notes;  "ebible" "-m" "ESV" "Romans 12:20" "#" "<==" "Romans"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew 7:2" "#" "<==" "Matthew"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "ebible" "-m" "ESV" "Matthew \"5:14-20]]\"" "#" "<==" "Matthew"
