cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "I Corinthians 10:3-4" "#" "<==" "I"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "2 Corinthians 13:11-14" "#" "<==" "2"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "II Corinthians 13:11-14" "#" "<==" "II"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "II Corinthians 5:14-17" "#" "<==" "II"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "-nem" "II Corinthians 5:14-17" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Zechariah 4" "#" "<==" "Zechariah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Zechariah 4:6" "#" "<==" "Zechariah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Zechariah 4:6-10" "#" "<==" "Zechariah"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Zechariah 4:6" "#" "<==" "Zechariah"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "ebible" "-m" "ESV" "Zechariah 4:6" "#" "<==" "Zechariah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Psalm 139" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5:24" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5:24" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Jn 5:26: For as the Father has life in \"himself,\" so he has granted the Son also to have life in himself." "#" "<==" "Jn"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5:26" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5:27" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5:26-29" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 3:8" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 3:8" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Revelation of John 3:10" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 15:20" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 14:24" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 14:23" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 14:23-24" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 12:48" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 8:52" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 8:51" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 5:47" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 6:47" "#" "<==" "Luke"
