cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Peter 2:14" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Peter 2:12-14" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Peter 2:12-16" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Peter 2:12-15" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Peter 2:12-16" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Peter 2:10-16" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "2 Peter 2:9-16" "#" "<==" "2"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 1:16" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Romans 1:16" "#" "<==" "Romans"
cd /;  "ebible" "-m" "ESV" "Isaiah 53:5" "#" "<==" "Isaiah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Isaiah 53:5" "#" "<==" "Isaiah"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 8:31-32" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "John 13:35" "#" "<==" "John"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 9:23-24" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 14:26" "#" "<==" "Luke"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Luke 14:27" "#" "<==" "Luke"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 13:34-35" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Ephesians 2:8-9" "#" "<==" "Ephesians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "John 14:12" "#" "<==" "John"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Philippians 2:13" "#" "<==" "Philippians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Philippians 2:12-13" "#" "<==" "Philippians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Philippians 2" "#" "<==" "Philippians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Philippians 2:1-13" "#" "<==" "Philippians"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Matthew 4:17" "#" "<==" "Matthew"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Lk 5:27-39" "#" "<==" "Lk"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Ro 2:6-8" "#" "<==" "Ro"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6:22" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6:22-23" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6:22" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6:23" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6:23" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6:21" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6:20" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Romans 6" "#" "<==" "Romans"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Timothy 1:6-7" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Cor. 1:22" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Cor. 1:22" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Cor 1:22" "#" "<==" "2"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "2 Cor 1:21-22" "#" "<==" "2"
cd /root/notes;  "ebible" "-m" "ESV" "Titus 3:5" "#" "<==" "Titus"
cd /root/notes;  "ebible" "-m" "ESV" "Titus 3:5-6" "#" "<==" "Titus"
cd /root/notes;  "ebible" "-m" "ESV" "Titus 3:5-7" "#" "<==" "Titus"
cd /root/notes;  "ebible" "-m" "ESV" "Titus 3:4-7" "#" "<==" "Titus"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Titus 3" "#" "<==" "Titus"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Titus 3:3-8" "#" "<==" "Titus"
cd /root/.emacs.d/host/pen.el/docs/theology;  "ebible" "-m" "ESV" "Luke 11:13" "#" "<==" "Luke"
cd /root/notes;  "ebible" "-m" "ESV" "I John 3:10" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "ESV" "Song of Solomon 3" "#" "<==" "Song"
