cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Psalm 27" "#" "<==" "Psalm"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Psalm 27" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Matthew 16" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Thessalonians 5:5" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Thessalonians 5:5" "#" "<==" "shx"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Thessalonians 5:5" "#" "<==" "shx"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Thessalonians 5:5" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Thessalonians 5:5" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Thessalonians 5:5" "#" "<==" "zsh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 3:1" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 3:13" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "1 John 3:1" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "1 John 3:13" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 4:1" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 4:3" "#" "<==" "sh"
cd /;  "ebible" "-bd" "-m" "NASB" "1 John 3:1" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "John 4:5" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "1 John 5:19" "#" "<==" "sh"
cd /;  "ebible" "-nbd" "-m" "NASB" "Romans 1:17" "#" "<==" "sh"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Psalms 27:1" "#" "<==" "fast"
cd /root/notes;  "ebible" "-c" "-m" "NASB" "Psalms 27:6" "#" "<==" "fast"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Revelation 8" "#" "<==" "Revelation"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I shx Thessalonians 5:5" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Thessalonians 5:5" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "I Thessalonians 5:5" "#" "<==" "I"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 3" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 3" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 3" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 3" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 3" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "ebible" "-m" "NASB" "Romans 3" "#" "<==" "Romans"
