;;; lsp-python-ms-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lsp-python-ms.el

(autoload 'lsp-python-ms-update-server "lsp-python-ms" "\
Update Microsoft Python Language Server.

On Windows, if the server is running, the updating will fail.
After stopping or killing the process, retry to update." t)
(register-definition-prefixes "lsp-python-ms" '("lsp-python-ms-"))

;;; End of scraped data

(provide 'lsp-python-ms-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-python-ms-autoloads.el ends here
