cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "acpi" "-b" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "acpi" "-b" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "acpi" "-b" "#" "<==" "zsh"
cd /;  "acpi" "-b" "#" "<==" "zsh"
cd /;  "acpi" "-b" "#" "<==" "zsh"
cd /;  "acpi" "-b" "#" "<==" "withopts"
cd /;  "acpi" "-b" "#" "<==" "zsh"
cd /;  "acpi" "-b" "#" "<==" "zsh"
