;;; eldoc-cmake-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eldoc-cmake.el

(autoload 'eldoc-cmake-enable "eldoc-cmake" "\
Enable eldoc support for a CMake file.")
(register-definition-prefixes "eldoc-cmake" '("eldoc-cmake--"))

;;; End of scraped data

(provide 'eldoc-cmake-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eldoc-cmake-autoloads.el ends here
