#+BRAIN_PARENTS: index

[[chrome:bipjeffers.bandcamp.com]]

* TODO Keep praying for Bip Jeffers
:PROPERTIES:
:ID:       d5b6b461-5404-4b79-ad24-f7450c28165f
:END:

Dear Heavenly Father, Jehovah God, LORD God Almighty,
and Jesus Christ my Lord, and Holy Spirit my Comforter,
please, God, heal, protect and comfort Bip, your child.
Please, God, deliver him from that spirit which is trying to lead him into darkness.
Please, God, You have promised to take care of him.
Bip believes in You, Jesus.
He believes he is a sinner in need of a Saviour, and he believes in you.
Please, God, restore to him a sound mind, and push back that darkness.
Please, God, lead him to repentance and help him to take steps drawing
closer to You, drawing closer to Jesus Christ.
Please, God, help him take steps towards walking in relationship
with Jesus Christ, Your Son.
While he is in New Zealand, please take care of him,
and even after that, LORD God, and to when he is home in heaven
with you.
In Jesus Christ's name I ask,
AMEN!!
Hallelujah!

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  John 10:27-30
#+END_SRC

#+RESULTS:
#+begin_src text
John 10:27-30
‾‾‾‾‾‾‾‾‾‾‾‾‾
My sheep hear My voice, and I know them, and
they follow Me; and I give eternal life to
them, and they will never perish; and no one
will snatch them out of My hand.

My Father, who has given them to Me, is
greater than all; and no one is able to snatch
them out of the Father’s hand.

I and the Father are one.”

(NASB)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  John 17:11
#+END_SRC

#+RESULTS:
#+begin_src text
John 17:11
‾‾‾‾‾‾‾‾‾‾
I am no longer in the world; and yet they
themselves are in the world, and I come to
You.

Holy Father, keep them in Your name, the name
which You have given Me, that they may be one
even as We are.

(NASB)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  John 17:15
#+END_SRC

#+RESULTS:
#+begin_src text
John 17:15
‾‾‾‾‾‾‾‾‾‾
I do not ask You to take them out of the
world, but to keep them from the evil one.

(NASB)
#+end_src

