cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "ylt" "John" "3:32-36" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "Rom" "1:17-18" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "1Thess" "1:9-10" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "Rev" "21:8" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "Heb" "2:3" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "Heb" "2:1-3" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "Heb" "2:1-4" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "Heb" "10:29" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nod" "Hab" "2:4" "#" "<==" "zsh"
