
# This configuration file lets you define new commands
# or change the shortcut or triggering keys of built-in verbs.
# You can change the colors of broot too.
#
# Configuration documentation is available at https://dystroy.org/broot
#

#####################
# user defined verbs:

# If $EDITOR isn't set on your computer, you should either set it
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# Example:
#  execution = "/usr/bin/nvim {file}"

# https://dystroy.org/broot/documentation/configuration/#shortcuts-and-verb-search

# Can't override enter because it's used for multiple things.
# - edit with xdg-open
# - focus
# Therefore, how to disable xdg-open?

# modal = true

# [[verbs]]
# invocation = "edit"
# key = "enter"
# # C-m doesn't work.
# # But 'enter' does
# # key = "ctrl-M"
# leave_broot = false
# shortcut = "e"
# execution = "vs {file}"

[[verbs]]
invocation = "edit"
key = "ctrl-J"
leave_broot = false
shortcut = "nw"
execution = "tm -d nw -args vs {file}"

[[verbs]]
invocation = "vim"
key = "alt-v"
leave_broot = false
shortcut = "nw"
execution = "tm -d nw -args cmd-nice-pavs {file}"

[[verbs]]
invocation = "emacs"
key = "alt-e"
leave_broot = false
shortcut = "nw"
execution = "tm -d nw -args pin {file}"

[[verbs]]
invocation = "emacs"
key = "alt-s"
leave_broot = false
shortcut = "sph"
execution = "tm -d sph -args zcd {file}"

[[verbs]]
invocation = "emacs-spv"
key = "alt-shift-s"
leave_broot = false
shortcut = "spv"
execution = "tm -d spv -args zcd {file}"

[[verbs]]
key = "ctrl-p"
leave_broot = false
execution = ":line_up"

[[verbs]]
key = "ctrl-n"
leave_broot = false
execution = ":line_down"

[[verbs]]
invocation = "create {subpath}"
# execution = "nw $EDITOR {directory}/{subpath}"
execution = "nw vs {directory}/{subpath}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
[[verbs]]
name = "view"
invocation = "view"
execution = "nw $PAGER {file}"

#####################
# Skin

# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values
# Note that some of those colors might not correcly
# render on terminals with low capabilities
#
# [skin]
# default = "gray(20) gray(1)"
# tree = "rgb(89, 73, 101) none"
# file = "gray(21) none"
# directory = "rgb(255, 152, 0) none bold"
# exe = "rgb(17, 164, 181) none"
# link = "Magenta none"
# pruning = "rgb(89, 73, 101) none Italic"
# permissions = "gray(12) none "
# owner = "gray(12) none "
# group = "gray(12) none "
# selected_line = "none gray(3)"
# char_match = "yellow none"
# file_error = "Red none"
# flag_label = "gray(16) none"
# flag_value = "rgb(255, 152, 0) none bold"
# input = "White none"
# status_error = "Red gray(2)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) gray(3)"
# status_italic = "rgb(255, 152, 0) None"
# status_bold = "rgb(255, 152, 0) None bold"
# status_code = "ansi(229) gray(5)"
# status_ellipsis = "gray(19) gray(1)"
# scrollbar_track = "rgb(80, 50, 0) none"
# scrollbar_thumb = "rgb(255, 187, 0) none"
# help_paragraph = "gray(20) none"
# help_bold = "rgb(255, 187, 0) none bold"
# help_italic = "Magenta rgb(30, 30, 40) italic"
# help_code = "gray(21) gray(3)"
# help_headers = "rgb(255, 187, 0) none"

# You may find other skins on
#  https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds

