#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

if ! stdin_exists; then
    argstr="$@"
    exec < <(printf -- "%s" "$argstr")
fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -d) {
        mode=domainname
        shift
    }
    ;;

    *) break;
esac; done

{
case "$mode" in
    domainname) {
        rosie grep -o subs net.fqdn_practical | sed 's/^www\.//'
    }
    ;;

    *) {
        rosie grep -o subs net.url_common
    }
    ;;
esac
} | sed "/\/\/www.youtube.com/{s~/embed/~/watch?v=~}"
