;;; consult-org-roam-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-org-roam.el

(autoload 'consult-org-roam-search "consult-org-roam" "\
Search org-roam directory using `consult-ripgrep' with live-preview.
With an option for INITIAL input when called non-interactively.

(fn &optional INITIAL)" t)
(autoload 'consult-org-roam-backlinks "consult-org-roam" "\
Select from list of all notes that link to the current note.
If OTHER-WINDOW, visit the NODE in another window.

(fn &optional OTHER-WINDOW)" t)
(autoload 'consult-org-roam-forward-links "consult-org-roam" "\
Select a forward link contained in the current buffer.
If OTHER-WINDOW, visit the NODE in another window.

(fn &optional OTHER-WINDOW)" t)
(autoload 'consult-org-roam-file-find "consult-org-roam" "\
Find org-roam node with preview, if ARG open in other window.

(fn ARG)" t)
(defvar consult-org-roam-mode nil "\
Non-nil if Consult-Org-Roam mode is enabled.
See the `consult-org-roam-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `consult-org-roam-mode'.")
(custom-autoload 'consult-org-roam-mode "consult-org-roam" nil)
(autoload 'consult-org-roam-mode "consult-org-roam" "\
Toggle `consult-org-roam-mode' to integrate consult with org-roam.
By enabling `consult-org-roam-mode' the functions `org-roam-node-read' and
`org-roam-ref-read' are overriden by consults-org-roam's equivalents. Optional
argument ARG indicates whether the mode should be enabled or disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "consult-org-roam" '("consult-org-roam-"))


;;; Generated autoloads from consult-org-roam-buffer.el

(register-definition-prefixes "consult-org-roam-buffer" '("consult-org-roam-" "org-roam-buffer-source"))

;;; End of scraped data

(provide 'consult-org-roam-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-org-roam-autoloads.el ends here
