cd /root/.pen/documents/notes;  "Romans" "7" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Romans" "9:5" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Romans" "9:4" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Romans" "9" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Romans" "9:30-33" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Romans" "8:4-14" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Romans" "8:4" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Romans" "8:9" "#" "<==" "zsh"
