cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "Romans" "2:25-29" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "Romans" "4:11-12" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "Romans" "9:8" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "Romans" "9:6-8" "#" "<==" "zsh"
cd /root/notes;  "Romans" "2:4" "#" "<==" "zsh"
