cd /root/.pen/documents/notes;  "Romans" "3:27-28" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "Romans" "3:25-27" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "Romans" "7:22" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "Romans" "13:10" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "Romans" "13:8" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "Romans" "12:19" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "Romans" "7:9-10" "#" "<==" "bash"
