cd /root/notes;  "Romans" "#" "<==" "pen-slmenu"
cd /root/notes;  "Romans" "#" "<==" "pen-slmenu"
cd /root/notes;  "Romans" "#" "<==" "pen-slmenu"
cd /root/notes;  "Romans" "#" "<==" "pen-slmenu"
cd /root;  "Romans" "#" "<==" "pen-slmenu"
