#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

sn="$(basename -- "$0")"

if ! inside-docker-p; then
    # in-pen "$sn" "$@"
    # pen tm new -s "$sn" "$sn" "$@"
    pen tm "$sn" "$@"
    exit
fi

test -f "/usr/local/bin/cli-chess" || pyf "cli-chess" &>/dev/null

: "${LICHESS_TOKEN:="$(oci pen-rc .lichess_token)"}"

if test -n "$LICHESS_TOKEN"; then
    set -- --token "$LICHESS_TOKEN" "$@"
fi

/usr/local/bin/cli-chess "$@"
