cd "/root/.pen/ebooks/Unknown/And-He-Will (12)";  "chrome" "https://pdf2md.morethan.io/" "#" "<==" "pen-any2org"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "chrome" "https://pdf2md.morethan.io/" "#" "<==" "pen-any2org"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "chrome" "https://pdf2md.morethan.io/" "#" "<==" "pen-any2org"
cd "/root/.pen/ebooks/ATELIER313/C. H. Spurgeon's Puritan Catechism (11)";  "chrome" "https://pdf2md.morethan.io/" "#" "<==" "pen-any2org"
cd "/root/.pen/ebooks/John Foxe/Foxe's Book of Martyrs (14)";  "chrome" "https://pdf2md.morethan.io/" "#" "<==" "pen-any2org"
