;;; itail-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from itail.el

(autoload 'itail "itail" "\
Tail file FILE in itail mode.  Supports remote tailing through tramp 

(fn FILE &optional LINES)" t)
(register-definition-prefixes "itail" '("itail-"))

;;; End of scraped data

(provide 'itail-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; itail-autoloads.el ends here
