((calibredb-set-metadata-dispatch nil)
 (emoji--command-Emoji nil)
 (emoji--command-Emoji\ >\ Activities nil)
 (emoji--command-Emoji\ >\ Animals\ &\ Nature nil)
 (emoji--command-Emoji\ >\ Animals\ &\ Nature\ >\ animal nil)
 (emoji--command-Emoji\ >\ Body nil)
 (emoji--command-Emoji\ >\ Body\ >\ hand nil)
 (emoji--command-Emoji\ >\ Food\ &\ Drink nil)
 (emoji--command-Emoji\ >\ Food\ &\ Drink\ >\ dishware nil)
 (emoji--command-Emoji\ >\ Food\ &\ Drink\ >\ food nil)
 (emoji--command-Emoji\ >\ Food\ &\ Drink\ >\ food\ >\ marine nil)
 (emoji--command-Emoji\ >\ Smileys nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ smiling nil)
 (git-timemachine-help nil)
 (magit-branch nil)
 (magit-diff
  ("--no-ext-diff" "--stat"))
 (magit-log
  ("-n256" "--graph" "--decorate"))
 (magit-reset nil)
 (notmuch-search-mode-transient nil)
 (notmuch-search-stash-transient nil)
 (notmuch-search-transient nil)
 (notmuch-show-part-transient nil)
 (notmuch-show-stash-transient nil))
