;;; org-ivy-search-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-ivy-search.el

(autoload 'org-ivy-search-view "org-ivy-search" "\
Incremental `org-search-view' with initial-input KEYWORD.

(fn &optional KEYWORD)" t)
(register-definition-prefixes "org-ivy-search" '("org-ivy-search-"))

;;; End of scraped data

(provide 'org-ivy-search-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-ivy-search-autoloads.el ends here
