cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_iqPH53_rand-17954_pid-1813111" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(432)---bash(1813420)---zsh(1813424)---man(1813509)---pstree(1813583)" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Exodus 15:1\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_zfVn7t_rand-23885_pid-1841915" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "cd $NOTES;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\"" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "pl" "cd $NOTES;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "/tmp/fifo_xc_WC71QA_rand-29354_pid-1986947" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "cd $NOTES;  \"diatheke\" \"-b\" \"StrongsGreek\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"721b\" \"#\" \"<==\" \"strongs-get-wor\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd $NOTES;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd $NOTES;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd $PENCONF/documents/notes;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\" \"#\" \"<==\" \"zsh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd $PENCONF/documents/notes;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\" \"#\" \"<==\" \"zsh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd $PENCONF/documents/notes;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\" \"#\" \"<==\" \"zsh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd $PENCONF/documents/notes;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\" \"#\" \"<==\" \"zsh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd $PENCONF/documents/notes;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\" \"#\" \"<==\" \"zsh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd $PENCONF/documents/notes;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\" \"#\" \"<==\" \"zsh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_AhIytl_rand-16853_pid-2000977" "#" "<==" ""
cd /root/notes;  "pl" "cd $PENCONF/documents/notes;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\" \"#\" \"<==\" \"zsh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_wao9Qi_rand-29507_pid-2003142" "#" "<==" ""
cd /root/notes;  "pl" "cd $PENCONF/documents/notes;  \"diatheke\" \"-b\" \"NASB\" \"-o\" \"w\" \"-f\" \"internal\" \"-k\" \"Ephesians 1\" \"#\" \"<==\" \"in-pen\" \"#\" \"<==\" \"zsh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "λ	l*	03BB	0955	GREEK SMALL LETTER LAMDA" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "pl" "\\blambda\\b" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/src;  "pl" "\\bbible-term-greek-get-word\\b" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/src;  "pl" "\\bbible-term-greek-get-word\\b" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/prompts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/prompts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/prompts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/prompts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/prompts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/prompts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/prompts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/prompts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/prompts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/prompts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "no-timeout" "#" "<==" ""
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Hebrews 1:1\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
