cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e sp" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: sp" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (find-file \\\"/root/.emacs.d/host/pen.el/scripts/container/sp\\\")(sit-for 0.2)(run-mode-hooks major-mode)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---sh(624202)-+-awk(624205)
                                      |-man(624203)---pstree(624364)
                                      \`-sed(624204)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---sh(710264)-+-awk(710268)
                                      |-man(710265)---pstree(710437)
                                      \`-sed(710267)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---zsh(711333)-+-awk(711337)
                                       |-man(711335)---pstree(711508)
                                       \`-sed(711336)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config;  "pl" "run.sh(1)---emacs(19524)---sh(763006)-+-awk(763009)
                                      |-man(763007)---pstree(763181)
                                      \`-sed(763008)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config;  "pl" "run.sh(1)---emacs(19524)---zsh(764080)-+-awk(764084)
                                       |-man(764082)---pstree(764253)
                                       \`-sed(764083)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---sh(1016526)-+-awk(1016529)
                                       |-man(1016527)---pstree(1016686)
                                       \`-sed(1016528)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---sh(1021459)-+-awk(1021463)
                                       |-man(1021461)---pstree(1021628)
                                       \`-sed(1021462)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---zsh(1022483)-+-awk(1022487)
                                        |-man(1022485)---pstree(1022653)
                                        \`-sed(1022486)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---zsh(1036610)-+-awk(1036614)
                                        |-man(1036612)---pstree(1036780)
                                        \`-sed(1036613)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---sh(1042651)-+-awk(1042654)
                                       |-man(1042652)---pstree(1042820)
                                       \`-sed(1042653)" "#" "<==" ""
cd /root/notes;  "pl" "cd /;  \"ebible\" \"-m\" \"NASB\" \"1 Corinthians 6:2-6\" \"#\" \"<==\" \"sh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd /;  \"ebible\" \"-m\" \"NASB\" \"1 Corinthians 6:2-6\" \"#\" \"<==\" \"sh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd /;  \"ebible\" \"-m\" \"NASB\" \"1 Corinthians 6:2-6\" \"#\" \"<==\" \"sh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd /;  \"ebible\" \"-m\" \"NASB\" \"1 Corinthians 6:2-6\" \"#\" \"<==\" \"sh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd /;  \"ebible\" \"-m\" \"NASB\" \"1 Corinthians 6:2-6\" \"#\" \"<==\" \"sh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd /;  \"ebible\" \"-m\" \"NASB\" \"1 Corinthians 6:2-6\" \"#\" \"<==\" \"sh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "cd /;  \"ebible\" \"-m\" \"NASB\" \"1 Corinthians 6:2-6\" \"#\" \"<==\" \"sh\"" "#" "<==" "zsh"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Romans 10\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Hosea\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(19524)---sh(3928154)-+-awk(3928157)
                                       |-man(3928155)---pstree(3928236)
                                       \`-sed(3928156)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(2836)---bash(1366562)---zsh(1366570)---sh-general(1366893)---sh-dir(1367037)---zsh(1367125)---vs(1390776)---pen-vs(1390778)---vim(1390873)---vim(1390875)---man(3930719)---pstree(3930793)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(2836)---bash(3931329)---zsh(3931334)---man(3931418)---pstree(3931492)" "#" "<==" ""
