cd /root/repos/bubbletea;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e options.go" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "-e \"(progn (ignore-errors (find-file \\\"/root/repos/bubbletea/options.go\\\")(sit-for 0.2)(run-mode-hooks major-mode)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/repos/bubbletea;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "ask_log" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.lY2gMTD\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/scripts\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "arbitrate_pen" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.PdxVyBB\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/scripts\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e lsp-rust.el" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "-e \"(progn (ignore-errors (find-file \\\"/root/.emacs.d/host/pen.el/src/lsp-rust.el\\\")(sit-for 0.2)(run-mode-hooks major-mode)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe;  "pl" "." "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe;  "pl" "/volumes/home/shane/var/smulliga/source/git/ua-kxie/circe" "#" "<==" "pen-ux"
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe;  "pl" "/volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/src;  "pl" "https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/src;  "pl" "https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/src;  "pl" "https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/src;  "pl" "https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/src;  "pl" "https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/src;  "pl" "https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/src;  "pl" "https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/ua-kxie/circe/src;  "pl" "https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /root/repos/rust-analyzer;  "pl" "Cloning https://github.com/rust-analyzer/rust-analyzer" "#" "<==" ""
cd /root/notes;  "pl" "bible-random-verse" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Obadiah 1\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "bible-random-verse" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Obadiah 1\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "lsp-racket" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.KvCXMRb\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/src\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "lsp-common" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.Lvk1ugz\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/src\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Romans 8:1\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
