cd /root/repos/tmux/tmux;  "pl" "grid" "#" "<==" "pen-find-and-gr"
cd /root/repos/tmux/tmux;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.vfNeutp\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/repos/tmux/tmux\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/repos/tmux/tmux;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Acts 2:48\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Acts 2:48\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Acts 2:38\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Hebrews\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"John\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_6U7I9C_rand-4431_pid-1509891" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdout_mCEK7Q_rand-28846_pid-1509951" "#" "<==" ""
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Revelation of John\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Romans 8:1\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Romans 8:1\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
