cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_cqsKDW_rand-30633_pid-283954" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_FPvhCH_rand-32003_pid-311262" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_22iLcp_rand-21471_pid-311860" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_1KtpVe_rand-3549_pid-313530" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_c2y0VV_rand-20069_pid-321270" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_H5witU_rand-9904_pid-411555" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_OaOmVq_rand-773_pid-412338" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_FuVvFD_rand-10192_pid-413447" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_l4NADq_rand-9950_pid-417876" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/PacktPublishing/R-Programming-By-Example/Chapter01;  "pl" "/tmp/fifo_tm_stdin_NPNkNr_rand-26536_pid-420684" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/PacktPublishing/R-Programming-By-Example/Chapter01;  "pl" "/tmp/fifo_tm_stdin_bHa9md_rand-6203_pid-422691" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/PacktPublishing/R-Programming-By-Example/Chapter01;  "pl" "/tmp/fifo_tm_stdin_kPlkOO_rand-14227_pid-423907" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "max-input-char-length" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/tmp/fifo_tm_stdin_xCpYXI_rand-30992_pid-427243" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/tmp/fifo_tm_stdout_mBcndU_rand-9888_pid-427381" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_tngTyj_rand-19650_pid-444646" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_Y0dxh9_rand-10355_pid-446628" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_0BbaBD_rand-11336_pid-449079" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_h0Gky6_rand-11939_pid-456380" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "tmwr" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.UmVzKz0\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/scripts\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_moXhe7_rand-8404_pid-462688" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_effMYd_rand-23854_pid-465552" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_PxXlSH_rand-14559_pid-473550" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_X5rhin_rand-27531_pid-474222" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_zNXjok_rand-5278_pid-476556" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_0ZsbhK_rand-11847_pid-477792" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(418)---bash(479120)---zsh(479125)---man(479217)---pstree(479292)" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/PacktPublishing/R-Programming-By-Example/Chapter01;  "pl" "/tmp/fifo_tm_stdin_w7btUw_rand-32336_pid-509451" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/PacktPublishing/R-Programming-By-Example/Chapter01;  "pl" "/tmp/fifo_tm_stdin_1V0wUA_rand-20144_pid-511975" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/PacktPublishing/R-Programming-By-Example/Chapter01;  "pl" "/tmp/fifo_tm_stdin_U4VVi7_rand-29044_pid-515112" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Matthew 7\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_8hkPST_rand-8758_pid-730735" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/crates/genie-rec/src;  "pl" "/tmp/fifo_tm_stdin_JZtRJH_rand-22687_pid-799866" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/crates/genie-rec/src;  "pl" "/tmp/fifo_tm_stdin_QbmdWF_rand-13346_pid-800935" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/PacktPublishing/R-Programming-By-Example/Chapter02;  "pl" "/tmp/fifo_tm_stdin_nZaBE2_rand-9679_pid-824570" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/PacktPublishing/R-Programming-By-Example/Chapter02;  "pl" "/tmp/fifo_tm_stdin_5a0Vyh_rand-7068_pid-827280" "#" "<==" ""
cd /;  "pl" "no-timeout" "#" "<==" ""
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (pen-kill-emacs t)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (pen-kill-emacs t)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"John 13\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_IQxG6a_rand-12722_pid-279846" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_TE52FM_rand-10483_pid-288036" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_kj1ORI_rand-14942_pid-292126" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/" "#" "<==" ""
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_S9oqha_rand-10120_pid-348722" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_nVoNLW_rand-8664_pid-352809" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "pen-load-config" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.E6gcDMN\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/src\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_L4UYNI_rand-10578_pid-440902" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_xa3YDK_rand-19806_pid-445146" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_OvNnrk_rand-12941_pid-540885" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_ipv3Rm_rand-24979_pid-664544" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_oOEhlO_rand-18018_pid-900411" "#" "<==" ""
cd /;  "pl" "no-timeout" "#" "<==" ""
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd //;  "pl" "OP: q" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd //;  "pl" "OP: running" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "OP: c" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "OP: running" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "" "#" "<==" "pen-e"
cd //;  "pl" "-e \"(progn (ignore-errors (pen-kill-emacs t)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "OP: running" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/root/.emacs.d" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/" "#" "<==" ""
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "no-timeout" "#" "<==" ""
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "OP: q" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "OP: running" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "OP: c" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "OP: running" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "" "#" "<==" "pen-e"
cd //;  "pl" "-e \"(progn (ignore-errors (pen-kill-emacs t)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "OP: running" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd //;  "pl" "OP: running" "#" "<==" "pen-e"
cd //;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd //;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd //;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "run.sh(1)---tmux: server(1889)---bash(259282)---zsh(259287)---man(259380)---pstree(259455)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(1889)---bash(270702)---zsh(270707)---man(270800)---pstree(270875)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(1889)---bash(271503)---zsh(271508)---man(271601)---pstree(271676)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(1889)---bash(272481)---zsh(272486)---man(272578)---pstree(272653)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(1889)---bash(277778)---zsh(277783)---man(277877)---pstree(277952)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(1889)---bash(277778)---zsh(277783)---man(278368)---pstree(278443)" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "" "#" "<==" "eww"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "google.com" "#" "<==" "eww"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "OP: " "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "OP: c" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "OP: running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(setq eww-no-external-handler nil)(let ((force-eww t)) (eww \\\"google.com\\\"))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "OP: running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "" "#" "<==" "eww"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "google.com" "#" "<==" "eww"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "OP: " "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "OP: c" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "OP: running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(setq eww-no-external-handler nil)(let ((force-eww t)) (eww \\\"google.com\\\"))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "OP: running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_Gw0lX1_rand-26582_pid-312232" "#" "<==" ""
cd /root/notes;  "pl" "" "#" "<==" "eww"
cd /root/notes;  "pl" "google.com" "#" "<==" "eww"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(setq eww-no-external-handler nil)(let ((force-eww t)) (eww \\\"google.com\\\"))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/notes;  "pl" "" "#" "<==" "eww"
cd /root/notes;  "pl" "google.com" "#" "<==" "eww"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(setq eww-no-external-handler nil)(let ((force-eww t)) (eww \\\"google.com\\\"))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=extern%20crate" "#" "<==" "eww"
cd /root/notes;  "pl" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=extern crate" "#" "<==" "eww"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(setq eww-no-external-handler nil)(let ((force-eww t)) (eww \\\"http://www.google.com/search?ie=utf-8&oe=utf-8&q=extern crate\\\"))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "OP: ia" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e ia" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "OP: c" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "OP: running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "-e \"(progn (ignore-errors (ignore-errors (package-install 'smalltalk-mode))(pen-revert-and-quit-emacsclient-without-killing-server)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "OP: running" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/sl4m/gnu_smalltalk_koans;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e /root/.emacs.d/host/pen.el/scripts/with-exponential-backoff" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "-e \"(progn (ignore-errors (find-file \\\"/root/.emacs.d/host/pen.el/scripts/with-exponential-backoff\\\")(sit-for 0.2)(run-mode-hooks major-mode)(get-buffer-create \\\"*scratch*\\\")(goto-line 45)(move-to-column 0)))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e /root/.emacs.d/host/pen.el/scripts/pvipe" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (find-file \\\"/root/.emacs.d/host/pen.el/scripts/pvipe\\\")(sit-for 0.2)(run-mode-hooks major-mode)(get-buffer-create \\\"*scratch*\\\")(goto-line 6)(move-to-column 5)))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
