cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "no-timeout" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Luke 17\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Daniel 12:10\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "." "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "xsh" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.AEWSONQ\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/scripts\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "xshcode" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e /root/.emacs.d/host/pen.el/scripts/xsh" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (find-file \\\"/root/.emacs.d/host/pen.el/scripts/xsh\\\")(sit-for 0.2)(run-mode-hooks major-mode)(get-buffer-create \\\"*scratch*\\\")(goto-line 64)(move-to-column 3)))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "xshcode" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "xshcode" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "zrepl /root/.cargo/bin/rustlings \"\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /" "#" "<==" ""
cd /root/notes;  "pl" "cd /" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "zrepl /root/.cargo/bin/rustlings \"\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "zrepl $HOME/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "zrepl /root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "zrepl /root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "zrepl /root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "pwd" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "." "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "nvc /root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "nvc -pak /root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "." "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "-pak /root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "." "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "." "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "." "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "." "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "/root/.cargo/bin/rustlings 'watch'" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "/root/.cargo/bin/rustlings 'watch'" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "/root/.cargo/bin/rustlings 'watch'" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/examples;  "pl" "sps" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "sps pin exercises" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "sps pin exercises" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "sps pin exercises" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "sps pin exercises" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "sps pen exercises" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "sps pin \`pwd\`/exercises" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "sps pin \`pwd\`/exercises" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings 'watch'" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings 'watch'" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /root/notes;  "pl" "unset CWD" "#" "<==" ""
cd /root/notes;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /root/notes;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "unset CWD" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "/root/.cargo/bin/rustlings 'watch'" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "unset CWD" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "/root/.cargo/bin/rustlings \"$@\"" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "unset CWD" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings;  "pl" "/root/.cargo/bin/rustlings 'hint' 'variables1'" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Joshua 7\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Daniel 9\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.pen/documents/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Romans 5\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_6tYrW5_rand-7534_pid-779076" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Hebrews 12\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Daniel 12\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "FilterWithFzf" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.d0DiRrL\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/config\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Isaiah 43\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
