cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_JOoSCY_rand-29165_pid-988143" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_rNDEXh_rand-13915_pid-999087" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_4GAaKZ_rand-5586_pid-1000775" "#" "<==" ""
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Hebrews\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Genesis\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"I Timothy 5\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
