cd /;  "pl" "no-timeout" "#" "<==" ""
cd /;  "pl" "no-timeout" "#" "<==" ""
cd /;  "pl" "no-timeout" "#" "<==" ""
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/" "#" "<==" ""
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e pen-digraphs.el" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "-e \"(progn (ignore-errors (find-file \\\"/root/.emacs.d/host/pen.el/src/pen-digraphs.el\\\")(sit-for 0.2)(run-mode-hooks major-mode)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "\\bhelm-do-grep-ag\\b" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el;  "pl" "\\bevil-insert-digraph\\b" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el;  "pl" "\\bschema-run\\b" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_SVmooV_rand-28073_pid-2641801" "#" "<==" ""
cd /root/.emacs.d/host/pen.el;  "pl" "\\bgreek-digraph-select\\b" "#" "<==" "pen-find-and-gr"
cd /root/notes;  "pl" "Ά	A%	0386	0902	GREEK CAPITAL LETTER ALPHA WITH TONOS" "#" "<==" "bash"
cd /root/notes;  "pl" "/root/.emacs.d" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/" "#" "<==" ""
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/.emacs.d;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e k" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: k" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "2650662
2038437" "#" "<==" "pen-e"
cd /root/notes;  "pl" "https://www.thegospelcoalition.org/article/how-i-gleaned-hope-from-the-darkest-psalm/" "#" "<==" "ff"
cd /root/notes;  "pl" "https://www.thegospelcoalition.org/article/how-i-gleaned-hope-from-the-darkest-psalm/" "#" "<==" "ff"
cd /root/notes;  "pl" "https://www.thegospelcoalition.org/article/how-i-gleaned-hope-from-the-darkest-psalm/" "#" "<==" "ff"
cd /root/notes;  "pl" "https://www.thegospelcoalition.org/article/how-i-gleaned-hope-from-the-darkest-psalm/" "#" "<==" "ff"
cd /root/notes;  "pl" "https://www.thegospelcoalition.org/article/how-i-gleaned-hope-from-the-darkest-psalm/" "#" "<==" "ff"
cd /root/.emacs.d/host/pen.el/src;  "pl" " TH Þ  222  ss ß  223  a\! à  224  a' á  225  a> â  226  a? ã  227  a: ä  228" "#" "<==" "bash"
cd /root/notes;  "pl" "㈧	8c	3227	12839	PARENTHESIZED IDEOGRAPH EIGHT" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config/vim-bundles;  "pl" "FilterWithFzf" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el;  "pl" "FilterWithFzf" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.WgWZaMv\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/config;  "pl" "/tmp/fifo_tm_stdin_Yuqv7f_rand-1905_pid-2753997" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config;  "pl" "/tmp/fifo_tm_stdout_kOxPLA_rand-15290_pid-2754056" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config;  "pl" "/tmp/fifo_tm_stdin_OSHMtm_rand-4332_pid-2754286" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config;  "pl" "/tmp/fifo_tm_stdout_aUAz8a_rand-32024_pid-2754345" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config;  "pl" "/tmp/fifo_tm_stdin_F15ohf_rand-15036_pid-2754571" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config;  "pl" "/tmp/fifo_tm_stdout_ywvL2V_rand-18538_pid-2754630" "#" "<==" ""
cd /root/dump/tmp;  "pl" "run.sh(1)---tmux: server(661314)---bash(2755541)---zsh(2755546)---man(2755630)---pstree(2755632)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Job 22:22\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2827318)---zsh(2827323)---man(2827407)---pstree(2827409)" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "parallel" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.8iD6aPN\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/scripts\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/config;  "pl" "serialsplit" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(661314)---bash(2837743)---zsh(2837748)---man(2837834)---pstree(2837836)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(661314)---bash(2837743)---zsh(2837748)---man(2838571)---pstree(2838573)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "GY_CMD" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.rHneeGH\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/scripts\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2842942)---zsh(2842947)---man(2843031)---pstree(2843105)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2842942)---zsh(2842947)---man(2843822)---pstree(2843899)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2842942)---zsh(2842947)---man(2844115)---pstree(2844156)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2842942)---zsh(2842947)---man(2844314)---pstree(2844391)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2842942)---zsh(2842947)---man(2844611)---pstree(2844652)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2842942)---zsh(2842947)---man(2844870)---pstree(2844911)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2842942)---zsh(2842947)---man(2845129)---pstree(2845170)" "#" "<==" ""
cd /root/notes;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2848624)---zsh(2848632)---man(2853246)---pstree(2853297)" "#" "<==" ""
cd /root/notes;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2855094)---zsh(2855099)---man(2859766)---pstree(2859817)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2855094)---zsh(2855099)---man(2859901)---pstree(2859952)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts/container;  "pl" "run.sh(1)---tmux: server(661314)---bash(2862393)---zsh(2862398)---man(2862481)---pstree(2862555)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts/container;  "pl" "run.sh(1)---tmux: server(661314)---bash(2862393)---zsh(2862398)---man(2863120)---pstree(2863194)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts/container;  "pl" "run.sh(1)---tmux: server(661314)---bash(2863537)---zsh(2863542)---man(2863626)---pstree(2863700)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(661314)---bash(2841433)---zsh(2841438)---man(2863945)---pstree(2864019)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(661314)---bash(2864389)---zsh(2864394)-+-man(2864477)---pstree(2864613)
                                                                \`-vs(2864478)---pen-vs(2864483)---pen-vs(2864588)-+-pen-dos2unix(2864590)---dos2unix(2864596)
                                                                                                                  \`-tr(2864589)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2866354)---zsh(2866359)---man(2866452)---pstree(2866526)" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(661314)---bash(2869249)---zsh(2869254)---man(2869339)---pstree(2869413)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "⥍	U+294D UP BARB LEFT DOWN BARB RIGHT HARPOON" "#" "<==" "zsh"
cd /root/notes;  "pl" "ℳ	U+2133 SCRIPT CAPITAL M" "#" "<==" "bash"
cd /root/notes;  "pl" "ℳ	U+2133 SCRIPT CAPITAL M" "#" "<==" "bash"
cd /root/notes;  "pl" "ℳ	U+2133 SCRIPT CAPITAL M" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "pl" "text/plain" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "text/plain" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "text/plain" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "text/plain" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "text/x-lisp" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el/config/bash" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el/config/bash" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el/config/bash/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(661314)---bash(3167516)---zsh(3167521)---man(3167609)---pstree(3167683)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "wayback" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(661314)---bash(3170967)---zsh(3170972)---man(3171062)---pstree(3171136)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(661314)---bash(3170967)---zsh(3170972)---man(3171461)---pstree(3171535)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---tmux: server(661314)---bash(3170967)---zsh(3170972)-+-man(3171790)---pstree(3171926)
                                                                \`-vs(3171791)---pen-vs(3171796)---pen-vs(3171901)-+-pen-dos2unix(3171903)---dos2unix(3171904)
                                                                                                                  \`-tr(3171902)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.emacs.d/host/pen.el/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el;  "pl" "/root/dump" "#" "<==" ""
cd /root/.emacs.d/host/pen.el;  "pl" "/root/dump" "#" "<==" "pen-ux"
cd /root/.emacs.d/host/pen.el;  "pl" "/root/dump/" "#" "<==" ""
cd /root/.emacs.d/host/khala/doc;  "pl" "text/plain" "#" "<==" ""
cd /root/.emacs.d/host/khala/doc;  "pl" "text/plain" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "/root/.pen/ebooks/Derek Prince/They Shall Expel Demons (9)/They Shall Expel Demons - Derek Prince.epub" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "scripts/open: Unhandled file type:" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "application/epub+zip" "#" "<==" "o"
cd /root/.emacs.d/host/pen.el/src;  "pl" "using rifle" "#" "<==" "o"
