cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'pen-show-alarm-clock-list 'l)(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'pen-show-alarm-clock-list 'l)(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(dictionary-search \\\"stubbornness\\\")(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(dired-cmd \\\"dired-ls\\\" \\\".\\\" \\\"--dired -alh\\\")(dired-git-info-mode 0)(dired-hide-details-mode 1)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" ""
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" ""
cd /root/.pen;  "pl" "run.sh(1)---tmux: server(438)---bash(539432)---zsh(539437)---zsh(539606)---man(539609)---pstree(539684)" "#" "<==" ""
cd /root/.pen;  "pl" "run.sh(1)---tmux: server(438)---bash(539432)---zsh(539437)---man(539766)---pstree(539841)" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_udqstK_rand-19238_pid-571524" "#" "<==" ""
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/word;  "pl" "-ft" "#" "<==" "pen-cr"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "\"/volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc/gpio-pins-layout.png\"" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "\"/volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc/gpio-pins-layout.png\"" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "\"/volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc/gpio-pins-layout.png\"" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "\"/volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc/pi3_gpio.png\"" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-mime"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "image/png" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc;  "pl" "\"/volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/doc/pi3_gpio.png\"" "#" "<==" "pen-win"
cd /volumes/home/shane/var/smulliga/source/git/zhiyihuang/C-examples/hzy_math;  "pl" "no handler for /tmp/tf_temp_94d8ed4c13.txt" "#" "<==" "pen-cr"
