cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Ephesians 4\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Ephesians 4\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Luke 21\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Matthew 24\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_G4Lq8E_rand-14174_pid-916616" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_3wOu5z_rand-19107_pid-1520584" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_LOJqcM_rand-3224_pid-1534422" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_5pdAlG_rand-27555_pid-1544061" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_mV2OaA_rand-7008_pid-1544295" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_VggPQU_rand-8766_pid-1551225" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_MnMY5a_rand-714_pid-1551459" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_kweTeS_rand-5521_pid-1585025" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_YVkSQz_rand-14815_pid-1603385" "#" "<==" ""
