cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Ephesians 6\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(456)---bash(256805)---zsh(256810)---man(256926)---pstree(257000)" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_zgW4xy_rand-17352_pid-259350" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_JlhJgc_rand-14452_pid-260156" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_6gQN23_rand-21524_pid-260640" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "/tmp/fifo_tm_stdin_Tq6HEX_rand-15981_pid-262708" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(1655)---sh(267914)-+-awk(267917)
                                     |-man(267915)---pstree(268009)
                                     \`-sed(267916)" "#" "<==" ""
cd /root/notes;  "pl" "https://www.patheos.com/blogs/keithgiles/2019/01/love-is-a-person/" "#" "<==" "eww"
cd /root/notes;  "pl" "https://www.patheos.com/blogs/keithgiles/2019/01/love-is-a-person/" "#" "<==" "eww"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(setq eww-no-external-handler nil)(let ((force-eww t)) (eww \\\"https://www.patheos.com/blogs/keithgiles/2019/01/love-is-a-person/\\\"))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_8PN5vz_rand-20145_pid-320110" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_49U7zX_rand-27729_pid-325518" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_U4FR2y_rand-14831_pid-329509" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_UqJgSB_rand-29567_pid-440663" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(1655)---sh(456400)-+-awk(456403)
                                     |-man(456401)---pstree(456510)
                                     \`-sed(456402)" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "run.sh(1)---emacs(1655)---sh(457211)-+-awk(457214)
                                     |-man(457212)---pstree(457316)
                                     \`-sed(457213)" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/scripts/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "cat" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.MMirpXg\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/src\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
