cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: test" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: test" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/src;  "pl" "snippets" "#" "<==" "pen-find-and-gr"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "-e \"(progn (ignore-errors (progn (find-file \\\"/tmp/emacs-stdin-.BbLvZJN\\\" )(set-visited-file-name nil)(rename-buffer \\\"*stdin*\\\"  t)(message (str (frame-terminal)))(ignore-errors (cd \\\"/root/.emacs.d/host/pen.el/src\\\")(grep-mode)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (pen-kill-emacs t)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (pen-kill-emacs t)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" ""
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config" "#" "<==" "pen-ux"
cd /root/notes;  "pl" "/root/.emacs.d/host/pen.el/config/" "#" "<==" ""
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: q" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (pen-kill-emacs t)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: q" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (pen-kill-emacs t)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e sd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-rc-set"
cd /;  "pl" "n-workers: 2" "#" "<==" ""
cd /;  "pl" "n-workers" "#" "<==" ""
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "OP: sd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Romans 3\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Genesis 2:22\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -e" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "OP: " "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "" "#" "<==" "pen-e"
cd /;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_5qo6Yg_rand-28286_pid-198124" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdout_BZ6OPK_rand-12893_pid-198184" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Romans\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el;  "pl" "\\bfind-file\\b" "#" "<==" "pen-find-and-gr"
cd /root/notes;  "pl" "https://youtubetranscript.com/?v=https://www.youtube.com/watch?v=UYiuM43u0Q4" "#" "<==" ""
cd /root/notes;  "pl" "https://youtubetranscript.com/?v=https://www.youtube.com/watch?v=UYiuM43u0Q4" "#" "<==" ""
cd /root/notes;  "pl" "https://youtubetranscript.com/?v=https://www.youtube.com/watch?v=UYiuM43u0Q4" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_V7KrKS_rand-31951_pid-273028" "#" "<==" ""
cd /root/notes;  "pl" "https://youtubetranscript.com/?v=https://www.youtube.com/watch?v=UYiuM43u0Q4" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_3h7RKD_rand-13552_pid-277809" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdout_INDefO_rand-18167_pid-277869" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_A1cVVh_rand-21993_pid-279515" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdout_XsHmoA_rand-8982_pid-279575" "#" "<==" ""
cd /root/notes;  "pl" "run.sh(1)---tmux: server(429)---bash(285609)---zsh(285614)---man(285781)---pstree(285856)" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_psHdsO_rand-30369_pid-293671" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_iDGfmd_rand-2836_pid-296364" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"Romans\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "/tmp/fifo_tm_stdin_fEFjfl_rand-28289_pid-319148" "#" "<==" ""
cd /root/notes;  "pl" "/tmp/fifo_xc_4eoG8l_rand-568_pid-330075" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "no-timeout" "#" "<==" ""
cd /root/.emacs.d/host/pen.el/scripts;  "pl" "no-timeout" "#" "<==" ""
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -D" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e -cip" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: " "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: c" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
cd /root/notes;  "pl" "" "#" "<==" "pen-e"
cd /root/notes;  "pl" "-e \"(progn (ignore-errors (message (str (frame-terminal)))(funcall-interactively 'bible-open nil nil \\\"NASB\\\" \\\"I Kings 18\\\")(recenter-top-bottom)(get-buffer-create \\\"*scratch*\\\")))\"" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VERSION: 28" "#" "<==" "pen-e"
cd /root/notes;  "pl" "INVOCATION: /root/.emacs.d/host/pen.el/scripts/pen-e running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "SERVER_NAME: DEFAULT" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_VARIANT: pen-emacsd" "#" "<==" "pen-e"
cd /root/notes;  "pl" "OP: running" "#" "<==" "pen-e"
cd /root/notes;  "pl" "EMACS_USER_DIRECTORY: /root/.emacs.d" "#" "<==" "pen-e"
