cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "-q" "test" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "-q" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "touch" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "ocif" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "tm-unbuffer" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "in-pen" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "in-pen" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "ocif" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "tm-unbuffer" "#" "<==" "man"
cd /volumes/home/shane/var/smulliga/source/git/rosie-pattern-language/rosie/rpl;  "info" "-q" "rosie" "#" "<==" "man"
cd /volumes/home/shane/var/smulliga/source/git/rosie-pattern-language/rosie/rpl;  "info" "-q" "rosie" "#" "<==" "man"
cd /volumes/home/shane/var/smulliga/source/git/rosie-pattern-language/rosie/rpl;  "info" "-q" "vim" "#" "<==" "man"
cd /volumes/home/shane/var/smulliga/source/git/rosie-pattern-language/rosie/rpl;  "info" "-q" "vim" "#" "<==" "man"
cd /volumes/home/shane/var/smulliga/source/git/rosie-pattern-language/rosie/rpl;  "info" "-q" "vim" "#" "<==" "man"
cd /volumes/home/shane/var/smulliga/source/git/rosie-pattern-language/rosie/rpl;  "info" "-q" "vim" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "tmux" "#" "<==" "man"
cd /root/.emacs.d/host/pen.el;  "info" "-q" "tmux" "#" "<==" "man"
