cd /root/.pen/documents/notes;  "info" "m4" "#" "<==" "zsh"
cd /;  "info" "m4" "#" "<==" "sh"
cd /;  "info" "m4" "#" "<==" "sh"
cd /root/notes;  "info" "m4" "#" "<==" "tmux: server"
cd /root/notes;  "info" "(m4) Define" "#" "<==" "tmux: server"
cd /root/.pen/documents/notes;  "info" "(m4) Define" "#" "<==" "zsh"
cd /root/notes;  "info" "(m4) Define" "#" "<==" "tmux: server"
cd /root/notes;  "info" "(m4) Define" "#" "<==" "tmux: server"
cd /root/.pen/documents/notes;  "info" "(m4) Define" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "info" "(m4) Define" "#" "<==" "zsh"
cd /root/notes;  "info" "(m4) Define" "#" "<==" "tmux: server"
cd /;  "info" "(m4) Define" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "info" "(m4) Define" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "info" "(m4) Define" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "info" "(m4)" "#" "<==" "zsh"
cd /;  "info" "m4" "#" "<==" "sh"
cd /;  "info" "m4" "#" "<==" "sh"
cd /;  "info" "(m4) Builtin" "#" "<==" "in-tm"
cd /;  "info" "(m4) Builtin" "#" "<==" "sh"
cd /;  "info" "(m4) Builtin" "#" "<==" "in-tm"
cd /;  "info" "(m4) Macro index" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "(m4) Macro index" "#" "<==" "m4"
cd /root/.emacs.d/host/pen.el/scripts;  "info" "(m4) Macro index" "#" "<==" "m4"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "m4"
cd /root/.pen/documents/notes;  "info" "(m4) Macro index" "#" "<==" "m4"
