cd /;  "info" "date" "#" "<==" "zsh"
cd /;  "info" "date" "#" "<==" "zsh"
cd /;  "info" "date" "#" "<==" "zsh"
cd /;  "info" "Denote" "#" "<==" "zsh"
cd /;  "info" "date" "#" "<==" "zsh"
cd /;  "info" "dirname" "#" "<==" "zsh"
