;;; helm-wikipedia-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-wikipedia.el

(autoload 'helm-wikipedia-suggest "helm-wikipedia" "\
Preconfigured `helm' for Wikipedia lookup with Wikipedia suggest." t)
(register-definition-prefixes "helm-wikipedia" '("helm-"))

;;; End of scraped data

(provide 'helm-wikipedia-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-wikipedia-autoloads.el ends here
