;;; elfeed-goodies-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elfeed-goodies.el

(autoload 'elfeed-goodies/setup "elfeed-goodies" "\
Setup Elfeed with extras:

* Adaptive header bar and entries.
* Header bar using powerline.
* Split pane view via popwin." t)
(register-definition-prefixes "elfeed-goodies" '("elfeed-goodies/powerline-default-separator"))


;;; Generated autoloads from elfeed-goodies-logging.el

(autoload 'elfeed-goodies/toggle-logs "elfeed-goodies-logging" "\
Toggle the display of Elfeed logs in a popup window." t)
(register-definition-prefixes "elfeed-goodies-logging" '("elfeed-goodies/log-window-"))


;;; Generated autoloads from elfeed-goodies-new-entry-hooks.el

(register-definition-prefixes "elfeed-goodies-new-entry-hooks" '("elfeed-goodies/"))


;;; Generated autoloads from elfeed-goodies-search-mode.el

(register-definition-prefixes "elfeed-goodies-search-mode" '("-elfeed/" "-pad-string-to" "elfeed-goodies/" "search-header/"))


;;; Generated autoloads from elfeed-goodies-show-mode.el

(register-definition-prefixes "elfeed-goodies-show-mode" '("elfeed-goodies/"))


;;; Generated autoloads from elfeed-goodies-split-pane.el

(register-definition-prefixes "elfeed-goodies-split-pane" '("elfeed-"))

;;; End of scraped data

(provide 'elfeed-goodies-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elfeed-goodies-autoloads.el ends here
