;;; docker-api-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from docker-api-connection.el

(register-definition-prefixes "docker-api-connection" '("docker-api-"))


;;; Generated autoloads from docker-api-containers.el

(register-definition-prefixes "docker-api-containers" '("docker-api-container"))


;;; Generated autoloads from docker-api-images.el

(register-definition-prefixes "docker-api-images" '("docker-api-image"))


;;; Generated autoloads from docker-api-networks.el

(register-definition-prefixes "docker-api-networks" '("docker-api-network"))


;;; Generated autoloads from docker-api-volumes.el

(register-definition-prefixes "docker-api-volumes" '("docker-api-volume"))

;;; End of scraped data

(provide 'docker-api-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; docker-api-autoloads.el ends here
