cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "#" "<==" "pen-emacsclient"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-nta" "" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "-e" "(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-nta" "" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "-e" "(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "-e" "(dired \"/volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight\")" "#" "<==" "pen-emacsclient"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "emacsclient" "-a" "" "-s" "/root/.emacs.d/server/pen-emacsd-1" "-e" "(pen-eval-for-host \"/tmp/eval-output-pen-emacsd-1-850b2be2-4e8c-11ee-90e8-3b38cb5cb49e.txt\" \"~/.pen/pool/available/pen-emacsd-1\" (pen-list2str (pen-batch (pen-single-generation (pen-force ((do-pen-update nil) (pen-force-engine nil) (max-generated-tokens 300) (force-temperature nil) (force-stop-sequence nil)) (pf-imagine-a-man-page/1 \"source\" :no-select-result t :prompt-hist-id nil :include-prompt nil :no-gen nil :variadic-var nil :override-prompt nil :inject-gen-start nil))))))" "#" "<==" "pen-emacsclient"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "emacsclient" "-t" "-a" "" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-emacsclient"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-c" "-a" "" "#" "<==" "pen-emacsclient"
cd /root/notes;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /root/notes;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "#" "<==" "pen-emacsclient"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-nta" "" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "-e" "(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-nta" "" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "-e" "(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
