cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "#" "<==" "pen-emacsclient"
cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "#" "<==" "pen-emacsclient"
cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "#" "<==" "pen-emacsclient"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/DEFAULT" "-e" "(progn (ignore-errors (find-file \"/root/.emacs.d/host/pen.el/src/pen-faces.el\")(sit-for 0.2)(run-mode-hooks major-mode)(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/DEFAULT" "-e" "(progn (ignore-errors (progn (find-file \"/tmp/emacs-stdin-.odODTax\" )(set-visited-file-name nil)(rename-buffer \"*stdin*\"  t)(message (str (frame-terminal)))(ignore-errors (cd \"/root/.emacs.d/host/pen.el/src\")(grep-mode)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "#" "<==" "pen-emacsclient"
cd /;  "emacsclient" "-a" "" "-s" "/root/.emacs.d/server/DEFAULT" "-e" "(pen-eval-for-host \"/tmp/eval-output-DEFAULT-065351ee-5099-11ee-a7a6-77703da6d4c5.txt\" \"~/.pen/pool/available/DEFAULT\" (progn (pen-sn \"pen-shutdown\")(kill-emacs)))" "#" "<==" "pen-emacsclient"
cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "#" "<==" "pen-emacsclient"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-nta" "" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "-e" "(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-nta" "" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "-e" "(progn (ignore-errors (message (str (frame-terminal)))(progn (try (delete-frame)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/DEFAULT" "-e" "(progn (ignore-errors (progn (find-file \"/tmp/emacs-stdin-.mcvpbIi\" )(set-visited-file-name nil)(rename-buffer \"*stdin*\"  t)(message (str (frame-terminal)))(ignore-errors (cd \"/root/.emacs.d/host/pen.el/src\")(grep-mode)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-c" "-a" "" "#" "<==" "pen-emacsclient"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "pen-e"
cd /root/notes;  "emacsclient" "-s" "/root/.emacs.d/server/DEFAULT" "-a" "" "-t" "#" "<==" "pen-emacsclient"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "false" "-e" "t" "-s" "/root/.emacs.d/server/DEFAULT" "#" "<==" "pen-e"
cd /root/.emacs.d/host/pen.el/src;  "emacsclient" "-a" "" "-t" "-s" "/root/.emacs.d/server/DEFAULT" "-e" "(progn (ignore-errors (progn (find-file \"/tmp/emacs-stdin-.l9Lc6Zd\" )(set-visited-file-name nil)(rename-buffer \"*stdin*\"  t)(message (str (frame-terminal)))(ignore-errors (cd \"/root/.emacs.d/host/pen.el/src\")(grep-mode)))(get-buffer-create \"*scratch*\")))" "#" "<==" "pen-e"
