cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "emacsclient"
cd /;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "emacsclient"
cd /root/.pen/documents/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "emacsclient"
cd /;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "emacsclient"
cd /;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/.emacs.d/host/pen.el;  "emacs" "--quick" "--script" "/root/.emacs.d/host/pen.el/scripts/emacs-script-test3" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "emacs" "--quick" "--script" "/root/.emacs.d/host/pen.el/scripts/emacs-script-test3" "hi" "tehere" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "emacs" "--quick" "--script" "/root/.emacs.d/host/pen.el/scripts/emacs-script-test3" "hi" "tehere" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "emacs" "--quick" "--script" "/root/.emacs.d/host/pen.el/scripts/emacs-script-test3" "hi" "tehere" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "emacs" "--quick" "--script" "/root/.emacs.d/host/pen.el/scripts/emacs-script-test3" "hi" "tehere" "#" "<==" "zsh"
