cd /root/.emacs.d/host/pen.el/scripts;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/.emacs.d/host/pen.el/scripts;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/.emacs.d/host/pen.el/scripts;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "emacsclient"
cd /;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-2" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/pen-emacsd-1" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/notes;  "emacs" "-nw" "-Q" "#" "<==" "zsh"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "-nw" "--debug-init" "-Q" "#" "<==" "zsh"
cd /root/notes;  "emacs" "-nw" "--debug-init" "-Q" "#" "<==" "zsh"
cd /root/notes;  "emacs" "-nw" "--debug-init" "-Q" "#" "<==" "zsh"
cd /root/notes;  "emacs" "-nw" "--debug-init" "-Q" "#" "<==" "zsh"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/.emacs.d/host/pen.el/scripts;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/.emacs.d/host/pen.el/scripts;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/.emacs.d/host/pen.el/scripts;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/.emacs.d/host/pen.el/src;  "emacs" "-nw" "--debug-init" "-Q" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
cd /root/notes;  "emacs" "--daemon=/root/.emacs.d/server/DEFAULT" "#" "<==" "emacsclient"
