cd /root/.pen/documents/notes;  "tmux-list-sockets" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "tmux-list-sockets" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "tmux-list-sockets" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "tmux-list-sockets" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "tmux-list-sockets" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "tmux-list-sockets" "#" "<==" "zsh"
