cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/notes;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/.emacs.d/host/pen.el/scripts;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/.emacs.d/host/pen.el/scripts;  "vimhelp" "+/HEBREW" "digraph-table" "#" "<==" "hebrew-digraphs"
cd /root/.emacs.d/host/pen.el/src;  "vimhelp" "digraph-table" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "vimhelp" "digraph-table" "#" "<==" "zsh"
