#!/bin/bash
export TTY

sed -e 's/|/┃/g' \
    -e 's/--/━━/g' \
    -e 's/+/∘/g' \
    -e "s/'/┆/g" \
    -e 's/- /┄┄/g' \
    -e 's/^∘ /∘┄/g' \
    -e 's/[┄━] /┄┄/g' \
    -e 's/━-∘/━━∘/g' \
    -e 's/┄-∘/┄┄∘/g'