#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/usr/local/bin/graph-easy" && : "${bin:="/usr/local/bin/graph-easy"}"
test -f "$bin" || plf Graph::Easy &>/dev/null
test -f "/usr/local/bin/graph-easy" && : "${bin:="/usr/local/bin/graph-easy"}"

"$bin" "$@"
