#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

test -f "/usr/local/bin/graph-easy" && : "${bin:="/usr/local/bin/graph-easy"}"
test -f "$bin" || plf Graph::Easy &>/dev/null
test -f "/usr/local/bin/graph-easy" && : "${bin:="/usr/local/bin/graph-easy"}"

"$bin" "$@"
