cd /;  "m4" "#" "<==" "zsh"
cd /;  "m4" "#" "<==" "zsh"
cd /;  "m4" "#" "<==" "zsh"
cd /;  "m4" "#" "<==" "zsh"
cd /etc/mail;  "m4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "/etc/mail/sendmail.mc" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "/etc/mail/sendmail.mc" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "/etc/mail/sendmail.mc" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "/etc/mail/sendmail.mc" "#" "<==" "zsh"
cd /etc/mail;  "m4" "/etc/mail/sendmail.mc" "#" "<==" "pen-cr"
cd /etc/mail;  "m4" "/etc/mail/sendmail.mc" "#" "<==" "pen-cr"
cd /etc/mail;  "m4" "/etc/mail/sendmail.mc" "#" "<==" "pen-cr"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "zsh"
