cd /root/notes;  "m4" "#" "<==" "zsh"
cd /;  "m4" "#" "<==" "in-tm"
cd /;  "m4" "#" "<==" "in-tm"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "upd"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "upd"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "m4" "--help" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "m4" "--help" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "m4" "-h" "macros" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "m4" "-h" "macros" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "-h" "macros" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "-h" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "m4" "-h" "#" "<==" "zsh"
