#!/bin/bash
export TTY

IFS= read -r -d '' SHCODE <<'HEREDOC'
Function or algorithm:
```
(defun f (n)
HEREDOC

for e in SHCODE; do
    eval val=\${$e}
    # val="$(printf -- "%s" "$val")"
    envstring+=" $e=$(cmd-nice-posix "$val") "
done
envstring="export $envstring; "
echo "$envstring" | tv
# cmd-nice-posix export foo "$shcode" bar | tv
