cd /root/.pen/documents/notes;  "hide-cursor" "tmux-choose-window" "-t" "localhost" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "hide-cursor" "tmux-choose-window" "-t" "localhost" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "hide-cursor" "tmux-choose-window" "-t" "localhost" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "hide-cursor" "tmux-choose-window" "-t" "localhost" "#" "<==" "tmux-shell"
cd /root/.pen/documents/notes;  "hide-cursor" "tmux-choose-window" "-t" "localhost" "#" "<==" "tmux-shell"
