cd /root/.pen/documents/notes;  "meli" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "meli" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "meli" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "meli" "#" "<==" "zsh"
cd /root/notes;  "meli" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "meli" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "meli" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "meli" "#" "<==" "zsh"
