#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

test -f "/root/.local/bin/pgcli" && : "${bin:="/root/.local/bin/pgcli"}"
test -f "/usr/local/bin/pgcli" && : "${bin:="/usr/local/bin/pgcli"}"
 
test -f "$bin" || pyf "pgcli" &>/dev/null

"$bin" "$@"
