;;; helm-gitlab-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-gitlab.el

(autoload 'helm-gitlab-projects "helm-gitlab" "\
List Gitlab projects using Helm interface." t)
(autoload 'helm-gitlab-project-issues "helm-gitlab" "\
List Gitlab projects using Helm interface." t)
(autoload 'helm-gitlab-issues "helm-gitlab" "\
List Gitlab issues using Helm interface." t)
(register-definition-prefixes "helm-gitlab" '("helm-gitlab--"))

;;; End of scraped data

(provide 'helm-gitlab-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-gitlab-autoloads.el ends here
