#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# e:visor-apl-show-pronounciation

# TODO Do variants of APL dialects:
# - gnu-apl
# - K

: "${dialect:="$1"}"
: "${dialect:="gnu-apl"}"

case "$dialect" in
    gnu-apl) {
        sed -e 's/≢/≢‹›/g' \
            -e 's/\//\/‹›/g'
    }
    ;;

    K) {
        sed -e 's/≢/≢‹›/g' \
            -e 's/\//\/‹reduce›/g'
        :
    }
    ;;

    *)
esac

