#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

age() {
    fileMod="$(stat -c %Y -- "$1")"
    if test -n "$fileMod"; then
        echo $(( $(date +%s) - fileMod ))
    else
        return $?
    fi
}

age "$@"
