#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# This will only work when apt is not in a bad state
# sudo apt remove "$@"

# This works more often
sudo dpkg -P "$@"

# If nothing works, do this:
# sudo rm -rf /var/lib/dpkg/info/libapache2-mod-dnssd.*
# sudo rm -rf /var/lib/dpkg/info/$1.*
