#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -l) {
        pen-show-alarm-clock-list "$@"
        exit $?
        shift
    }
    ;;

    *) break;
esac; done

pen-alarm-set "$@"
