#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -l) {
        shift
        pen-show-alarm-clock-list "$@"
        exit $?
    }
    ;;

    *) break;
esac; done

#                          hour min am/pm
# example 1: pen-alarm-set    8  30 am    # 
# example 2: pen-alarm-set                # No arguments sets interactively
pen-alarm-set "$@"
