#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -once) {
        once=y
        shift
    }
    ;;

    *) break;
esac; done

# (alarm-clock-set "1:34" "Shower and go to Anak")

# sps vlc -l "$@"

exec 1> >(lolcat -f)
exec 2> >(lolcat -f)

if test "$once" = "y"; then
    echo "WAKE UP!!" | toilet
    mplayer "$@"
else
    while :; do
        echo "WAKE UP!!" | toilet
        mplayer "$@"
        sleep 5
    done
fi
