#!/bin/bash
export TTY

# penelfonts -f dietcola Apostrophe

# The dark blue symbolises fiction
# The dark red seams symbolise reality

IFS= read -r -d '' apo_logo <<'HEREDOC'
                                                               
          /\                                                   
      _  / |                    /                    /         
     (  /  |  . .-.  .-._.. ---/---).--..-._..-.    /-.   .-.  
      `/.__|_.' /  )(   )/ \  /   /    (   ) /  )  /   |./.-'_ 
  .:' /    |   /`-'  `-'/ ._)/   /      `-' /`-'_.'    |(__.'  
 (__.'     `-'/        /                   /                   
                                                               
HEREDOC

echo
printf -- "%s\n" "$apo_logo" | pen-his -b dblue -f dred