#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nv) {
        USE_NVC=y
        shift
    }
    ;;

    *) break;
esac; done

export USE_NVC

person="$@"

# test -n "$person" || {
#     echo "Person name required as parameter." 12    
#     exit 1
# }

if test -n "$person"; then
    pen -ic "(progn (apostrophe-start-chatbot-from-name $(cmd-nice-posix "$person" t))(delete-other-windows))"
else
    pen -ic "(progn (call-interactively 'apostrophe-start-chatbot-from-name)(delete-other-windows))"
fi
