#!/bin/bash
export TTY

# Apostrophe
# Version 1.0, bash

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nv) {
        USE_NVC=y
        shift
    }
    ;;

    *) break;
esac; done

export USE_NVC

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

# test -n "$person" || {
#     echo "Person name required as parameter." 12
#     exit 1
# }

person="$@"

if stdin_exists; then
    text="$(cat)"
    pen -ic "(progn (apostrophe-start-chatbot-from-selection $(cmd-nice-posix "$text"))(delete-other-windows))"
elif test -n "$person"; then
    exec <&1
    pen -ic "(progn (upd (apostrophe-start-chatbot-from-name $(cmd-nice-posix "$person") t))(delete-other-windows))"
else
    pen -ic "(progn (call-interactively 'apostrophe-start-chatbot-from-name)(delete-other-windows))"
fi
