#!/bin/bash
export TTY

sn="$(basename "$0")"

# Apostrophe
# Version 1.0, bash

# Apostrophe is a figure of speech in which a speaker directly addresses someone
# (or something) that is not present or cannot respond in reality. ... An
# apostrophe is often introduced by the exclamation "O," as when Juliet cries
# out: "O Romeo, Romeo, Wherefore art thou Romeo?"

FRAMETYPE=tty

apostrophe-logo 1>&2

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nv) {
        USE_NVC=y
        shift
    }
    ;;

    -human|-talk-to-human) {
        PEN_ENGINE=Human
        shift
    }
    ;;

    -engine) {
        PEN_ENGINE="$2"
        shift
        shift
    }
    ;;

    -temp|-temperature) {
        export PEN_TEMPERATURE="$2"
        shift
        shift
    }
    ;;

    -tty|-nw|-t) {
        export PEN_USE_GUI=n
        FRAMETYPE=tty
        shift
    }
    ;;

    -gui) {
        export PEN_USE_GUI=y
        FRAMETYPE=gui
        shift
    }
    ;;

    *) break;
esac; done

export USE_NVC
export PEN_UPDATE
export PEN_ENGINE

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

# test -n "$person" || {
#     echo "Person name required as parameter." 12
#     exit 1
# }

person="$@"

# PEN_USE_GUI is unset by design apparently

if test -z "$person"; then
    {
        echo "$sn, for the moment, needs requires you to name a person in its arguments"
        echo "For example:"
        echo "$ $sn \"Amber Heard\""
    } 1>&2
    exit 1
fi

if stdin_exists; then
    text="$(cat)"
    # Rather than specifying directly to the prompt function,
    # this value is taken up and remembered for future prompting within the apostrophe
    pen -nn -frametype "$FRAMETYPE" --pool -ic "(pen-engine \"Human\" (progn (apostrophe-start-chatbot-from-selection $(cmd-nice-posix "$text"))(delete-other-windows)))"
elif test -n "$person"; then
    exec <&1
    pen -nn -frametype "$FRAMETYPE" --pool -ic "(pen-engine \"Human\" (progn (upd (apostrophe-start-chatbot-from-name $(cmd-nice-posix "$person") t))(delete-other-windows)))"
else
    pen -nn -frametype "$FRAMETYPE" --pool -ic "(pen-engine \"Human\" (progn (call-interactively 'apostrophe-start-chatbot-from-name)(delete-other-windows)))"
fi
