#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

argsstring="$@"

if printf -- "%s\n" "$argsstring" | grep -q -P -- '--?h'; then
    ${GOPATH%%:*}/bin/ascii-image-converter "$@" | pavs
else
    ${GOPATH%%:*}/bin/ascii-image-converter "$@"
fi

