#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

argsstring="$@"

if printf -- "%s\n" "$argsstring" | grep -q -P -- '--?h'; then
    ${GOPATH%%:*}/bin/ascii-image-converter "$@" | pavs
else
    ${GOPATH%%:*}/bin/ascii-image-converter "$@"
fi

