#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# awk-calc "($width/100) * $client_width"
# awk-calc "(50/100) * 160"

equation="$@"
test -n "$equation" || exit 1

echo "$(awk "BEGIN {print ($equation)}")"
