#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

filter="$@"

(
if test -n "$filter"; then
    tail -f ~/bash-messages.txt | sed "s=${filter}=="
else
    tail -f ~/bash-messages.txt
fi
) | sed 's= "#" = # ='