#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "$1" || exit 1

fp="$1"

{
bash -c "compgen -A variable"
bash -c "source \"$fp\" &> /dev/null; compgen -A variable"
} | sort | uniq -u | pavs