#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

case "$sn" in
    bible-book) {
        book=Genesis
    }
    ;;

    *)
        book="$sn"
esac

nasb "$book" "$@"
