#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

if inside-docker-p; then
    in-tm pen-e -ic bible-open
else
    if docker-running-p; then
        nvt sp -ic bible-open
    else
        # sp -ic bible-open
        sp -cip bible-open =nil =nil NASB "$@"
    fi
fi


# in-pen sp -ic bible-open
