#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    input="$(cat)"
    arg="$(printf -- "%s" "$input" | s join ' ')"
    set -- "$@" "$arg"

    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}

    unbuffer sph "$sn" -nem "$@"
    printf -- "%s" "$input"
    exit
fi

if ! inside-docker-p && docker-running-p; then

    if is_tty; then
        in-pen in-tm "$sn" "$@"
    else
        in-pen "$sn" "$@"
    fi

    exit "$?"
fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -g) {
        getverses=y
        shift
    }
    ;;

    -j) {
        getverses=n
        shift
    }
    ;;

    -m) {
        module="$2"
        shift
        shift
    }
    ;;

    -nem) {
        export NOEMACS=y
        shift
    }
    ;;

    -l) {
        searchtype=lucene
        shift
    }
    ;;

    *) break;
esac; done

: "${module:="NASB"}"
: "${searchtype:="phrase"}"
: "${getverses:="y"}"

# phrase search is much better
# : "${searchtype:="lucene"}"

query="$@"

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty && ! test "$NOEMACS" = y; then
    # pen-e -cip bible-search-lucene "$query" "$module"
    # pen-e -cip bible-search-phrase "$query" "$module"
    pen-e -cip bible-search "$query" "$module" "$searchtype"
else
    # phrase / lucene
    in-pen oci "diatheke" "-b" "$module" "-s" "$searchtype" "-o" "w" "-f" "phrase" "-k" "$query" |
        sed 's/^[^-]*-- //' | sed 's/ --.*//' | sed 's/ ; /\n/g' | sed '1{s/\([0-9]\)\([A-Z]\)/\1\n\2/}' | {
        if test "$getverses" = "y"; then
            tv | bible-show-verses -m "$module"
        else
            sed -z 's/\n$//'
        fi
    } | pavs
fi
