#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

if inside-docker-p; then
    :
else
    if docker-running-p; then
        nvt sp -ic bible-open
    else
        nvt sp -ic bible-open
    fi
fi


# in-pen sp -ic bible-open
