#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -H) {
        height="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

test "$#" -gt 0 && last_arg="${@: -1}"
fp="$last_arg"
rp="$(realpath "$fp")"
dn="$(dirname "$rp")"
cd "$dn"
bn="$(basename -- "$fp")"
ext="${bn##*.}"
fn="${bn%.*}"
mant="${fn%.*}"


cd "$dn"

new_fn="${mant}-1bit.txt"

if ! test -n "$height"; then
    eval `resize`
    height="$(( LINES - 3 ))"
fi

ascii-image-converter "$rp" --braille -H "$height" --dither > "$new_fn"
cat "$new_fn" | pavs
