#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# cargo install --locked --features clipboard broot

: "${bin_fp:="$(test-and-echo -f "/root/.cargo/bin/broot")"}"
: "${bin_fp:="$(test-and-echo -f "$HOME/local/bin/broot")"}"
: "${bin_fp:="$(test-and-echo -f "/usr/local/bin/broot")"}"

"$bin_fp" "$@"
