#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# https://stackoverflow.com/questions/40775930/using-beautifulsoup-to-modify-html

from bs4 import BeautifulSoup
import os
import sys
sys.path.append('/root/.elinks')
import devtools
import rules

# beautifulsoup actually modifies html just with the initial parse

base = os.path.dirname(os.path.abspath(__file__))
url = '/volumes/home/shane/dump/programs/httrack/mirrors/https-www-sermonindex-net-modules-articles-index-php/www.sermonindex.net/modules/articles/index0ad0.html'
html = open(os.path.join(base, url))

soup = BeautifulSoup(html, 'html.parser')

# html = devtools.modifier(url, html)
# html = devtools.replacer(url, html)

from shanepy import *
myembed(globals(), locals())

# soup = BeautifulSoup(html, 'html.parser')

# for i in soup.find('div', {"id":None}).findChildren():
#     i.replace_with('##')

# with open("example_modified.html", "wb") as f_output:
#     f_output.write(soup.prettify("utf-8"))  
