#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

. $SCRIPTS/lib/hs

# diatheke-tui uses cacaview

feh "$@"

# CMD="$(cmd "$@")"
# : ${CMD:="$(cmd "$@")"}
# 
# nw -E "unbuffer timg $CMD | less -rS"
