#!/bin/bash
export TTY

# https://www.baeldung.com/linux/calculators-cli
# calc is a straightforward command-line calculator that provides a basic means of performing arithmetic
# calculations.                                                                                                    5
# 
# Its pros lie in its simplicity and ease of use, making it a quick solution for basic math operations.
# However, it lacks advanced mathematical functions, interactive capabilities, and constants commonly
# needed in calculations.
# First, let’s install calc via apt-get and sudo:

# EXAMPLE:
# ; x=2
# ; y=3
# ; (x^2)+(y^3)
# ; 31

# . $SCRIPTS/lib/hs

if test "$#" -eq 0; then
    USE_RLWRAP=y
    # THis is necessary because rlwrap doesn't like vim opening in the same TTY
    export PAGER=sps-v
fi

if test "$USE_RLWRAP" = "y"; then
    nvc rl /usr/bin/calc "$@"
else
    nvc /usr/bin/calc "$@"
fi
