#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# Not finished

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty; then
    /usr/bin/catppt "$@"
else
    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}
    in-tty -E "/usr/bin/catppt $CMD | pavs"
fi

