#!/bin/bash
export TTY

# Chann.el
# Version 1.0, bash

# The practice of channeling - a person's body being taken over by a spirit for
# the purpose of communication - has been around for millennia.

# chann.el v1.0
# - Run a chatbot that sees only a terminal (program independent)
#   - The chatbot may have multiple personalities. i.e. a Mad-Hatter's Tea-Party
# chann.el v2.0
# - Give an AGI control of a terminal

# http://github.com/semiosis/channel/blob/master/README.md

# Examples:
# channel "March Hare, the Hatter and the Dormouse" "Mad Tea-Party group"
# channel "March Hare, the Hatter and the Dormouse" "Mad Tea-Party group" madteaparty "Mad Tea-Party group"
# channel -who "March Hare, the Hatter and the Dormouse" -on-behalf-of "Mad Tea-Party group" madteaparty "Mad Tea-Party group"

# Without an explicit command to connect to, run a madteaparty client

sn="$(basename "$0")"
if test -f $HOME/.emacs.d/host/pen.el/scripts/$sn && ! test "$HOME/.emacs.d/host/pen.el/scripts" = "$(dirname "$0")"; then
    $HOME/.emacs.d/host/pen.el/scripts/$sn "$@"
    exit "$?"
fi

inside-docker-p() {
    test -f /.dockerenv
}

if { ! inside-docker-p; }; then
    pen sh "$sn" "$@"
    exit "$?"
fi

channel-logo 1>&2

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -who) {
        who="$2"
        shift
        shift
    }
    ;;

    -on-behalf-of) {
        on_behalf_of="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${who:="$1"}"
: "${on_behalf_of:="$2"}"
: "${on_behalf_of:="$who"}"

# pen-eterm madteaparty "$on_behalf_of" "$@"

FRAMETYPE=tty
pen -nn -frametype "$FRAMETYPE" --pool -ic "(progn (upd (channel-chatbot-from-name $(cmd-nice-posix "$who") t))(delete-other-windows))"