#!/bin/bash
export TTY

# channel v1.0
# - Run a chatbot that sees only a terminal (program independent)
# channel v2.0
# - Give an AGI control of a terminal

# http://github.com/mullikine/channel/blob/master/README.md