#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

bin=$HOME/.local/bin/chd

if ! test -f "$bin"; then
(
    cd /root
    wget "https://www.muppetlabs.com/~breadbox/pub/software/chd-1.1.tar.gz"
    tar zxf chd-1.1.tar.gz
    cd chd-1.1 
    make
    cp -a chd ~/.local/bin
    rm -rf /root/chd-1.1
    rm ~/chd-1.1.tar.gz 
)
fi

"$bin" "$@"
