#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# But it requires youtube-dl, which I refuse to use

url="$@"

python /usr/share/mkchromecast/mkchromecast.py --encoder-backend ffmpeg --alsa-device hw:2,1 -y "$url" --video