#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -c) {
        do_continue=y
        shift
    }
    ;;

    *) break;
esac; done

: "${dp:="$1"}"
: "${dp:="$DUMP/programs/httrack/mirrors/https-www-truthnetwork-com-/www.truthnetwork.com/show"}"

cd "$dp"
FAST=y find . -type f -empty -exec cmdx rm -- {} \; | cat

htmls2txt -p index.html -c

{
find "$dp" -name index.txt | awk1 | while IFS=$'\n' read -r fp; do
    (
        if test "$do_continue" = "y"; then
            :
        else
            exec 0</dev/null
            cmdx cat "$fp" |
            sed '0,/Transcript.*BETA/d' |
                sed '/COVERED TOPICS/,/IMG/d' |
                sed '/Whisper/,$d' |
                sed -z 's/^\n*//g' |
                sed -z 's/\n*$//g' |
                sponge "$fp"
        fi
    )
done
}

# $HOME/.pen/documents/devotionals/jeffvines

# | pavs
