#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -rmtm) {
        rm_tmux=y
        shift
    }
    ;;

    *) break;
esac; done

(
if test "$rm_tmux" = "y"; then
    sed -z 's/\n\[ .*//'
else
    cat
fi
) | sed -e 's/[▒▄]/ /g' \
    -e 's/[┌┐┘└│├─┤┬┴┼╰╯╭╮🟠⃘]/ /g' \
    -e 's/ ·\+$//g' |
sed -e ':loop' -e 's/^\( *\) · /\1   /g' -e 't loop' |
sed -e 's/\( ·\)\+ *$//g' ` # jupyter tui ` \
    -e 's/\( ·\)\+ *$/ /g' ` # jupyter tui ` \
    -e 's/\s\+$//g' ` # remove trailing whitespace ` |
    -e '/^\~$/d' ` # vim ` \
    sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba'


# -e 's/^  \(· \)\+//g' ` # jupyter tui ` \
# -e 's/^ \(· \)\+/ /g' ` # jupyter tui ` \

# piping into cat here breaks it. It creates a race
# condition with the outer cat, or something. Do not do
# this.
# | cat   