#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -c) {
        do_continue=y
        shift
    }
    ;;

    *) break;
esac; done

: "${dp:="$1"}"
: "${dp:="$DUMP/programs/httrack/mirrors/https-www-truthnetwork-com-/www.truthnetwork.com/show"}"

cd "$dp"
remove-empty-files-here

htmls2txt -p index.html -c

{
find "$dp" -name index.txt | awk 1 | while IFS=$'\n' read -r fp; do
    fn=$(basename -- "$fp")
    dn=$(dirname "$fp")
    ext="${fn##*.}"
    mant="${fn%.*}"

    (
        if test "$do_continue" = "y"; then
            :
        else
            exec 0</dev/null
            cmdx cat "$fp" |
            clean-truthnetwork-transcript |
                sponge "$fp"
        fi
    )
done
}

# $HOME/.pen/documents/devotionals/jeffvines

# | pavs
