#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || go install github.com/ajeetdsouza/clidle@latest &>/dev/null

${GOPATH%%:*}/bin/clidle "$@"
