#!/bin/bash
export TTY

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists; then
    fp="$(pen-tf formatted clj clj)"
fi

: "${fp:="$1"}"

test -f "$fp" || exit 1

clojure -Sdeps '{:deps {cljfmt {:mvn/version "0.6.4"}}}' \
  -m cljfmt.main fix "$fp" &>/dev/null

cat "$fp"