#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# gc https://github.com/veltman/clmystery

td=/volumes/home/shane/var/smulliga/source/git/veltman/clmystery
test -d "$td" && : "${dp:="$td"}"
td=$MYGIT/veltman/clmystery
test -d "$td" && : "${dp:="$td"}"

# zcd $MYGIT/veltman/clmystery
br-txt "$dp"
