#!/bin/sh

# cmd - print the arguments given to this script

cmd() {
    for var in "$@"
    do
        printf "'%s' " "$(printf %s "$var" | sed "s/'/'\\\\''/g")";
    done | sed 's/ $//'
}

cmd "$@"
