#!/bin/sh

# cmd - print the arguments given to this script

# https://mullikine.github.io/posts/missing-posix-shell-functions-cmd-and-myeval/

cmd() {
    for var in "$@"
    do
        if test "$var" = '|'; then
            printf -- "%s" '| '
        else
            # trailing newlines are removed for arguments. Fix this
            printf "'%s' " "$(printf %s "$var" | sed "s/'/'\\\\''/g")";
        fi
    done | sed 's/ $//'
}

cmd "$@"
