#!/bin/bash
export TTY

cmd-nice() {
    for var in "$@"
    do
        printf '"%s" ' "$(printf %s "$var" | sed 's/\(\\\)\([^"]\|$\)/\1\1\2/g' | sed 's/\(\\*\)"/\1\1\\"/g')";
    done | sed 's/ $//'
}

cmd-nice "$@"
