#!/bin/sh
export TTY

# cmd-unonelineify-safe is used for an eval. Therefore, I must properly escape contained single quotes

cmd_unonelineify_safe() {
    for var in "$@"
    do
        printf "'%s' " "$(printf %s "$var" | pen-str unonelineify-safe | sed "s/'/'\\\\''/g")";
    done | sed 's/ $//'
}

cmd_unonelineify_safe "$@"
