#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# run-b64 J2VjaG8nICdoaSc=
# run-b64 "$(cmd-b64 echo hi)"
# eval "$(cmd-b64 -mk echo hi)"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -mk) {
        make_run=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$make_run" = "y"; then
    echo "run-b64 $(cmd "$@" | base64 -w 0)"
else
    cmd "$@" | base64 -w 0
fi

