#!/bin/bash
export TTY

# cmd for "sp -cip"

test "$#" -eq 0 && exit 0

printf -- "%s" "$(
for (( i = 1; i < $#; i++ )); do
    eval ARG=\${$i}
    printf -- "%s" "$ARG" | q-cip
    printf ' '
done
eval ARG=\${$i}
printf -- "%s" "$ARG" | q-cip
)"
