#!/bin/sh
export TTY

cmd_unonelineify_safe() {
    for var in "$@"
    do
        printf "'%s' " "$(printf %s "$var" | pen-str unonelineify-safe)";
    done | sed 's/ $//'
}

cmd_unonelineify_safe "$@"
