#!/bin/bash
export TTY

# Purpose: echo and run

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -sps) {
        do_sps=y
        shift
    }
    ;;

    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    *) break;
esac; done

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if test "$DO_EXEC" = "y"; then
    CMD="$1"
else
    CMD="$(cmd "$@")"
fi

if test "$do_sps" = y; then
    {
    echo -n "exec: " | hls red
    echo "$CMD" | awk 1 | mnm | hls blue
    eval "$CMD"
    } | sps pavs
# elif is_tty; then
#     {
#     echo -n "exec: "
#     cmd_nice "$@" | awk 1
# 
#     "$@"
#     } | tless
else
    {
    echo -n "exec: " | hls red
    echo "$CMD" | awk 1 | hls blue
    } 1>&2

    eval "$CMD"
fi
