#!/bin/bash
export TTY

# Purpose: echo and run

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -sps) {
        do_sps=y
        shift
    }
    ;;

    -fast) {
        FAST=y
        shift
    }
    ;;

    *) break;
esac; done

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if test "$FAST" = "y"; then
    cmd_nice() {
        cm="$@"
        printf -- "%s\n" "$cm"
        return "$?"
    }
else
    cmd_nice() {
        cmd-nice "$@"
        return "$?"
    }
fi

if test "$do_sps" = y; then
    {
    echo -n "exec: "
    cmd_nice "$@" | awk 1

    "$@"
    } | sps pavs
elif is_tty; then
    {
    echo -n "exec: "
    cmd_nice "$@" | awk 1

    "$@"
    } | pavs
else
    {
    echo -n "exec: " | hls red
    cmd_nice "$@" | awk 1 | hls blue
    } 1>&2

    "$@"
fi
