#!/bin/bash
export TTY

# https://raw.githubusercontent.com/mithrandie/csvq/master/README.md

. $SCRIPTS/lib/hs

# cat /root/.pen/cross_references.tsv | csvq -f tsv 'select * from stdin limit 10' | v

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || go install github.com/mithrandie/csvq@latest &>/dev/null

${GOPATH%%:*}/bin/csvq "$@"
