#!/bin/bash
export TTY

# ct vim /

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    -nv) {
        export USE_NVC=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$#" -eq 0; then
    set -- sh
fi

if test "$DO_EXEC" = "y"; then
    CMD="$1"
else
    CMD="$(cmd-nice-posix "$@")"
fi

inside-docker-p() {
    test -f /.dockerenv
}

if inside-docker-p; then
    : ${CWD:="$(pwd)"}
else
    CWD=/
fi

docker_maybe() {
    if inside-docker-p; then
        "$@"
    else
        cterm-docker "$@"
    fi
}

: "${USER:="$(pen-readln "host username")"}"

# This runs in the docker to the host
docker_maybe ssh \
    -i "~/.pen/host_key" \
    -o ControlMaster=auto \
    -o ControlPath="~/ssh-controlpath-%r@%h:%p" \
    -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no \
    -t $USER@$(hostname) \
    "bash -l -c $(cmd-nice-posix ". ~/.profile; cd $(cmd-nice-posix "$CWD"); $CMD")"
