#!/bin/bash
export TTY

# nsfa needs to be created from within elisp

export USE_NEOVIM

: ${modename:="$1"}
# script="$(pen-nsfa "$@")"
bufname="$(p term "$@" | slugify | cut -c 1-30)"

# neovim cant be run inside emacs without compromising cursor position

# elisp="(pen-term \"$script\" t $modename)$elisp"
elisp="(pen-term (pen-nsfa $(cmd-nice-posix "$(cmd-nice-posix "$@")")) t $(cmd-nice-posix "$modename") $(cmd-nice-posix "$bufname"))$elisp"

# oresp -sh "$@"
pente "$elisp"
