#!/bin/bash
export TTY

# ct vim /

CMD="$(cmd "$@")"
: ${CMD:="$(cmd "$@")"}

inside-docker-p() {
    test -f /.dockerenv
}

if inside-docker-p; then
    cterm-docker "$@"
else
    # This runs in the docker to the host
    cterm-docker ssh \
        -o ControlMaster=auto \
        -o ControlPath="~/ssh-controlpath-%r@%h:%p" \
        -o UserKnownHostsFile=/dev/null \
        -o StrictHostKeyChecking=no \
        -t $USER@$(hostname) \
        "bash -l -c $(cmd-nice-posix ". ~/.profile; $CMD")"
fi
