#!/bin/bash
export TTY

# Example:
# Run cterm on the host.

# ctermh vim /

CMD="$(cmd "$@")"
: ${CMD:="$(cmd "$@")"}

# This runs in the docker to the host
cterm ssh \
    -M \
    -o ControlPath="~/ssh-controlpath-%r@%h:%p" \
    -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no \
    -t $USER@$(hostname) \
    "bash -l -c $(cmd-nice ". ~/.profile; $CMD")"
