#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    --help) {
        shift
        set -- -h "$@"
    }
    ;;

    *) break;
esac; done

cd ~/repos/cwc

if test "$#" -eq 0; then
    zcd .
    exit "$?"
fi

strace $HOME/repos/cwc/src/cwc "$@" | pavs
