#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nano) {
        nanoseconds=y
        shift
    }
    ;;

    -mili) {
        miliseconds=y
        shift
    }
    ;;
    *) break;
esac; done


if test "$miliseconds" = "y"; then
    date +%s.%N "$@" | sed 's/^\([0-9]\+\)\.\([0-9]\{3\}\).*/\1\2/'
elif test "$nanoseconds" = "y"; then
    date +%s.%N "$@"
else
    date +%s "$@"
fi
