#!/bin/bash
export TTY

# http://go2linux.garron.me/shell-command-convert-binary-octal-decimal-hexadecimal/

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    IFS= read -rd '' input < <(cat /dev/stdin)
else
    input="$1"
fi

echo "obase=16;$input" | bc
