#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

is_emacs_shell() {
    [[ $INSIDE_EMACS == *,comint ]] || [[ $INSIDE_EMACS == *,eshell ]];
}

is_tty() {
    # If stout is a tty
    [ -t 1 ] && ! test "$TERM" = "dumb" && ! is_emacs_shell;
}

if is_tty && ! test "$INSIDE_NEOVIM" = y; then
    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}

    sn="$(basename -- "$0")"

    if yn "Watch?\n\tnvc watch $sn $CMD"; then
        nvc watch -n 5 "$sn" "$@"
    else
        /bin/df "$@" | pavs
    fi
else
    /bin/df "$@" | pavs
fi
