#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty && ! test "$INSIDE_NEOVIM" = y; then
    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}

    sn="$(basename -- "$0")"

    if yn "Watch?\n\tnvc watch $sn $CMD"; then
        nvc watch -n 5 "$sn" "$@"
    else
        /bin/df "$@" | pavs
    fi
else
    /bin/df "$@" | pavs
fi
