#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# $SCRIPTS/diatheke-list-bibles

test -f /usr/bin/diatheke || agi diatheke &>/dev/null

/usr/bin/diatheke "$@"
