#!/bin/bash
export TTY

# Also see: withopts

# . $SCRIPTS/lib/hs

# vim +/"displayopts" "$PENELD/config/zsh/zshrc"

# if test "$NOEMACS" = "y"; then
#     printf -- "%s\n" "NOEMACS" | hls nearblack 1>&2
# fi

if test "$#" = 0; then
    set -- DEBUG BORDER FAST NOEMACS NO_CI PREFER_GUI DECORATED COLUMNATED ONELINED "$@"
fi

is_stdout_pipe() {
    # If stout is a pipe
    [[ -p /dev/stdout ]]
}

if is_stdout_pipe; then
    envq "$@" | awk 1
else
    # envq "$@" | awk 1 | hls nearblack 1>&2
    envq -j "$@" | awk 1 | vimcat | cat 1>&2
fi

# 'envq' -f 'DEBUG' 'BORDER' 'FAST' 'NOEMACS' 'NO_CI' | cat
# 'envq' 'NOEMACS' 'NO_CI' | cat
# 'envq' 'NOEMACS' | cat
