#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -cd) {
        cd "$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

fn="$1"
test -n "$fn" || exit 1

x=`pwd`
if test -e "$fn"; then
    printf -- "%s\n" "$(pwd)/$fn"
    exit 0
fi

found=
while [ "$x" != "/" ] ; do
    x=`dirname "$x"`
    out="$(find "$x" -maxdepth 1 -name "$fn")"
    if test -n "$out"; then
        printf -- "%s\n" "$out"
        found=1
    fi
done
test -n "$found"
