#!/bin/bash
export TTY

sn="$(basename -- "$0")"

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

# Perhaps I could extend this to do a list of files
if stdin_exists; then
    url="$(cat | head -n 1)"
    set -- "$url" "$@"
fi

url="$1"
test -n "$1" || exit 1

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

is_stdout_pipe() {
    # If stout is a pipe
    [[ -p /dev/stdout ]]
}

if is_stdout_pipe || test "$sn" = downloaded; then
    dir="$HOME/downloads/"
    mkdir -p "$dir"
    cd "$dir"
    # Make a slugged fn?
    fn="$(basename "$url")"
    if ! test -f "$fn"; then
        wget -c "$url" -O "$fn"
    fi
    rp="$(realpath "$fn")"
    echo "$rp"
    exit "$?"
fi

if ! is_tty; then
    sps "$sn" "$@"
    exit "$?"
fi

dir="$HOME/downloads/"
mkdir -p "$dir"
cd "$dir"
CWD="$dir" zrepl -cm wget -c "$url"
