#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

url="$1"
test -n "$1" || exit 1

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if ! is_tty; then
    sps "$@"
    exit "$?"
fi

dir="$HOME/downloads/"
mkdir -p "$dir"
cd "$dir"
CWD="$dir" zrepl -cm wget -c "$url"
