#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

test -f $HOME/.cargo/bin/dua || cargo install dua-cli --no-default-features --features tui-crossplatform &>/dev/null

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty; then
    $HOME/.cargo/bin/dua interactive "$@"
else
    $HOME/.cargo/bin/dua "$@"
fi
