#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

url="$@"

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if ! test -n "$url"; then
    echo "dump-clean: No url / name as first arg" | hls red
    exit 1
fi

if ! stdin_exists; then
    echo "dump-clean: No html stdin" | hls red
    exit 1
fi

input_fp="$(cat | tf txt)"

if pl "$rp" | grep -q -P 'christianityworks.co.nz.*fresh'; then
    :
    exit "$?"
fi
