#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

url="$@"

. $SCRIPTS/lib/stdin_exists

if ! test -n "$url"; then
    echo "dump-clean: No url / name as first arg" | hls red
    exit 1
fi

dump_url() {
    d_url="$1"
    test -n "$d_url" || return 1

    if printf -- "%s\n" "$d_url" | url-needs-chrome; then
        0</dev/null elinks-dump-chrome "$d_url" | cat
    else
        0</dev/null elinks-dump "$d_url" | cat
    fi
    return 0
}

if ! stdin_exists; then
    exec < <(dump_url "$url")
fi

input_fp="$(cat | tf txt)"

if printf -- "%s\n" "$url" | grep -q -P 'christianityworks.co.nz.*fresh'; then
    cat "$input_fp" | clean-christianityworks-co-nz-fresh | sponge "$input_fp"
fi

cat "$input_fp" | pavs
