#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f $HOME/.cargo/bin/dust || cargo install du-dust &>/dev/null

$HOME/.cargo/bin/dust "$@"
