#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

case "$sn" in
    bl|ebible) {
        # default
        module=NASB
    }
    ;;

    nasb) {
        module=NASB
    }
    ;;

    kjv) {
        module=KJV
    }
    ;;

    bsb) {
        module=engbsb2020eb
    }
    ;;

    *) {
        module="$sn"
    }
    ;;
esac

: "${module:="NASB"}"

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty; then
    if test "$1"; then
        ref="$@"
        sp -cip bible-open =nil =nil "$module" "$ref"
    else
        sp -cip bible-open =nil =nil "$module"
    fi
else
    {
    echo "$@" | udl
    "diatheke" "-b" "$module" "-o" "w" "-f" "plain" "-k" "$@" | sed 's/^.* [0-9]\+:[0-9]\+: *//' | pen-s remove-trailing-whitespace | sed '/^$/d' | ttp
    } | pavs
    # | pen-s remove-trailing-whitespace | pen-s join ' ' | sed 's/[0-9]: /&\n/g' | sed '/^$/d' | awk 'NR%2==0' | pavs
fi
