#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

case "$sn" in
    bl|ebible) {
        # default
        module=NASB
    }
    ;;

    nasb) {
        module=NASB
    }
    ;;

    kjv) {
        module=KJV
    }
    ;;

    bsb) {
        module=engbsb2020eb
    }
    ;;

    *) {
        module="$sn"
    }
    ;;
esac

: "${module:="NASB"}"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -ttp) {
        USE_TTP=y
        shift
        shift
    }
    ;;

    -nottp) {
        USE_TTP=n
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${USE_TTP:="y"}"

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

doublespacemax () {
    sed ':a;N;$!ba;s/\n\n/\n/g'
}

if is_tty; then
    if test "$1"; then
        ref="$@"
        sp -cip bible-open =nil =nil "$module" "$ref"
    else
        sp -cip bible-open =nil =nil "$module"
    fi
else
    {
    echo "$@" | udl
    "diatheke" "-b" "$module" "-o" "w" "-f" "plain" "-k" "$@" | sed 's/^.* [0-9]\+:[0-9]\+: *//' | pen-s remove-trailing-whitespace | sed '/^$/d' | sed '$s/\( *\)\(([^)]\+)\)$/\n\n\2/' | doublespacemax | {
        if test "$USE_TTP" = "y"; then
            ttp
        else
            cat
        fi
    }
    } | pavs
    # | pen-s remove-trailing-whitespace | pen-s join ' ' | sed 's/[0-9]: /&\n/g' | sed '/^$/d' | awk 'NR%2==0' | pavs
fi
