#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -n) {
        window_name="$2"
        shift
        shift
    }
    ;;

    -t) {
        export USE_TOR=y
    }
    ;;

    -w) {
        WAITTIME="$2"
        shift
        shift
    }
    ;;

    -refs) {
        KEEP_REFS=y
        shift
    }
    ;;

    *) break;
esac; done

export WAITTIME
export KEEP_REFS

url="$1"
test -n "$url" || exit 1

# I get an iframe from dockerhub when I use https
url="$(p "$url" | sed '/hub.docker.com/s/^https/http/')"

oci -f -nd dom-dump "$url" | tf html | xa elinks-dump