#!/bin/bash
export TTY

test -f "/root/emacs-lsp-plain-pen.el" && : "${script_fp:="/root/emacs-lsp-plain-pen.el"}"
test -f "/root/emacs-lsp-plain.el" && : "${script_fp:="/root/emacs-lsp-plain.el"}"
: "${script_fp:="/root/emacs-lsp-plain.el"}"

test -f "$script_fp" || ocif curl -s "https://raw.githubusercontent.com/emacs-lsp/lsp-mode/master/scripts/lsp-start-plain.el" > "$script_fp"

/usr/local/bin/emacs -nw -q -l "$script_fp" -l /root/.emacs.d/host/pen.el/src/pen-enable-mouse.el "$@"