#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# test -f $HOME/.cargo/bin/emacs-lsp-booster || cargo install "emacs-lsp-booster" &>/dev/null
#  v +/"# emacs lsp booster (for performance)" "$PENELD/scripts/setup.sh"

$HOME/.cargo/bin/emacs-lsp-booster "$@"
