#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# showsize() {
#     ns `resize`
# }
# 
# # This seems to execute after teetty quits
# trap showsize SIGWINCH

/usr/local/bin/emacs "$@"
