#!/bin/bash
export TTY

# Because, otherwise, I may get this issue:
# Boostrapping emacs worker test... /usr/local/bin/emacsclient: Invalid permissions on parent directory of socket: /root/.pen/tmp/emacs0/test
export TMPDIR=/tmp

# . $SCRIPTS/lib/hs

: "${NOCOLOR:=""}"
if test "$NOCOLOR" = "y"; then
    /usr/local/bin/emacs --color=never "$@"
else
    /usr/local/bin/emacs "$@"
fi
