#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# Start a process inside emacs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$DO_EXEC" = "y"; then
    CMD="$1"
else
    CMD="$(cmd-nice-posix "$@")"
fi

. $SCRIPTS/lib/stdin_exists

# TODO Make stdin go into snfa
# if stdin_exists || printf -- "%s\n" "$CMD" | grep -q -P ' '; then
#     CMD="$(nsfa "$CMD")"
# 
#     exec <&1
# fi

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty; then
    cmd-nice x -sh "$(cmd sp -e "(pen-start-process $(cmd-nice-posix "$CMD"))")" -e "When done with this frame" -sl 0.5 -m '<' -sl 0.5 -m '>' -i
else
    cmd-nice sp -e "(pen-start-process $(cmd-nice-posix "$CMD"))" +ofq "(current-buffer-name)" | cat
fi
