#!/bin/bash
export TTY

# trap '' HUP
# eval `pen-tm-resize`
# exec <&1
# exec <`tm-tty`

# This gets permission denied
# exec `tm-tty`>&1;

# This appears to work (but only if stderr is still bound to the tty)
exec 1>&2;

# It actually might not be possible to turn a command with stdout to a pipe into a command with a tty

# Hmm. A tty needs to be assigned, actually, because it may not exist.
# etty nem John 15:18-27 | cat
# The thing is, the tty still exists sometimes.
# Alternatively, 

#TMUX= tmux new "$@"

"$@"
