#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# extractcpx extract The\ Anarchy\ of\ King\ Stephen.aoe2campaign
/volumes/home/shane/var/smulliga/source/git/SiegeEngineers/genie-rs/target/debug/examples/extractcpx extract "$@"