#!/bin/bash
export TTY

# Example:
# cat $PENELD/scripts/bible-mode-scripts/pen.els | f-point-out-parentheses | v

sed 'a\\' | fill-lines-to-longest-line | vsed 's/\([()]\)./\1^/g' | erase-trailing-whitespace