#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

fargs=()
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    --) {
        shift
        break
    }
    ;;

    *) {
        fargs+=("$1")
        shift
    }
    ;;

esac; done

bin_arg="$1"
shift

"$bin_arg" "${fargs[@]}" "$@"