#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

fargs=()
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    --) {
        shift
        break
    }
    ;;

    *) {
        fargs+=("$1")
        shift
    }
    ;;

esac; done

bin_arg="$1"
shift

"$bin_arg" "${fargs[@]}" "$@"