#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

input_fp="$(cat | tf txt)"

longest_line="$(cat "$input_fp" | awk ' { if ( length > x ) { x = length; y = $0 } }END{ print y }')"
len_ll="$(printf -- "%s" "$longest_line" | wc -c)"

cat "$input_fp" | awk '{printf "%-'$len_ll's\n", $0}'
rm -f "$input_fp"
