#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -test-filter) {
        test_filter="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if ! stdin_exists; then
    if test "$#" -gt 0; then
        exec < <(args-to-lines "$@")
    else
        exit 1
    fi
fi


urls="$(eval "$test_filter")"
test -n "$urls" && echo "$urls"
test -n "$urls"
