#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -test-filter|-tfi) {
        test_filter="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

. $SCRIPTS/lib/stdin_exists

if ! stdin_exists; then
    if test "$#" -gt 0; then
        exec < <(args-to-lines "$@")
    else
        exit 1
    fi
fi


urls="$(eval "$test_filter")"
test -n "$urls" && echo "$urls"
test -n "$urls"
