#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

input_fp="$(cat | tf txt)"

urls="$(cat "$input_fp" | rosie-urls)"
urls_links="$(cat "$input_fp" | scrape "\\[\\[http.*\\]\\[.*\\]\\]")"

printf -- "%s\n" "$urls"
printf -- "%s\n" "$urls_links"
