#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# Put the result into a file and open it in vim (i.e. let the results be editable).
# finaledit elinks-dump "https://www.noser.com/techblog/virtual-pty-tty-uart-listener-pitfalls-on-linux-socat/"

. $SCRIPTS/lib/hs

test "$#" -eq 0 && exit 1

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -ofp) {
        output_fp=y
        shift
    }
    ;;

    -cat) {
        cat_fp=y
        shift
    }
    ;;

    *) break;
esac; done

is_stdout_pipe() {
    # If stout is a pipe
    [[ -p /dev/stdout ]]
}
is_stdout_pipe
ispipe="$?"

fp="$(tfsha "$@")"

if test "$cat_fp" = "y"; then
    cat "$fp"
elif test "$output_fp" = "y"; then
    echo "$fp"
else
    if test "$ispipe" -eq 0; then
        export VIM_NOCATOUT=y

        (
        trap '' HUP
        odn in-tty v "$fp"
        ) &>/dev/null

        cat "$fp"
    else
        v "$fp"
    fi
fi
