#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/flapioca" || go install github.com/kbrgl/flapioca@latest &>/dev/null

while :; do
    ${GOPATH%%:*}/bin/flapioca "$@"
    pak -m "Press any key to restart"
done
