#!/bin/bash
export TTY

# Meant to be used as an editor

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

last_arg="${@: -1}"

if is_tty; then
    # pool pen-e "$@"

    if printf -- "%s\n" "$last_arg" | grep -q -P '\.(csv|tsv)$'; then
        fpvd "$@"
    else
        v "$@"
    fi
else
    # pen-sps -w pin "$@"
    # pen-sps -w pool pen-e "$@"

    # This recalls in a new tmux window
    pen-sps -w fpvd-editor "$@"
fi
