#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f ${GOPATH%%:*}/bin/frangipanni || cr $MYGIT/birchb1024/frangipanni

${GOPATH%%:*}/bin/frangipanni "$@" | pavs
