#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

digraphs="$(cat /usr/local/share/vim/vim82/doc/digraph.txt | sed "0,/\\*digraph-table\\*/d" | sed -n '/.*\t.*\t.*\t.*\t.*/p')"

awk1 | while read -n1 c; do
    found="$(printf -- "%s\n" "$digraphs" | lgrep "^$c")"
    if test -n "$found"; then
        echo "$found"
    else
        echo "$c"
    fi
done
