#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# need gcc-10 for the -fanalyzer option

remove_deprecated_args() {
    sed "s/'-fanalyzer'//"
}

eval "set -- $(cmd "$@" | remove_deprecated_args)"

/usr/bin/gcc "$@"
