#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || go install github.com/dundee/gdu/v5/cmd/gdu@latest &>/dev/null

${GOPATH%%:*}/bin/gdu "$@"
