#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

fp="$1"

test -d "$NOTES/ws/jobs" && dn="$NOTES/ws/jobs"
test -d "/volumes/home/shane/notes/ws/jobs" && dn="/volumes/home/shane/notes/ws/jobs"

if test -f "$fp"; then
    check-maybe-misused-words "$fp"
    org2pdf "$fp"
else
    cd "$dn"
    : "${fp:="$(readlink "cv-newest.org")"}"
    bn="$(basename "$fp")"
    mant="${bn%.*}"

    fp="$dn/${mant}.org"
    check-maybe-misused-words "$fp"
    org2pdf "$fp"
fi

is_tty() { [ -t 1 ]; }

if pl "$mant" | grep -q -P '^cv-'; then
    ln -sf "$dn/${mant}.pdf" cv-newest.pdf
fi

if is_tty; then
    z "$dn/${mant}.pdf"
else
    echo "$dn/${mant}.pdf"
fi