#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

video_id="$1"
# 9bZkp7q19f0
key="$(myrc-get youtube_key)"

test -n "$video_id" || exit 1
test -n "$key" || exit 1

ocif -nd curl -s "https://www.googleapis.com/youtube/v3/videos?id=${video_id}&part=contentDetails&key=${key}"