#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

book="$1"
chapter="$2"

# cmd vedm "/$book\\<CR>/\<$chapter\>\\<CR>\"ayyggVGd\"aP"
# cat /root/.pen/documents/notes/ws/peniel/Bible-chapter-titles.txt | vedm "/$book\\<CR>/\<$chapter\>\\<CR>\"ayyggVGd\"aP"

cat /root/.pen/documents/notes/ws/peniel/Bible-chapter-titles.txt | vedm "/$book\\<CR>/\<$chapter\>\\<CR>\"ayyggVGd\"aP"
