#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

book="$1"
chapter="$2"

# cmd vedm "/$book\\<CR>/\<$chapter\>\\<CR>\"ayyggVGd\"aP"
# cat /root/.pen/documents/notes/ws/peniel/Bible-chapter-titles.txt | vedm "/$book\\<CR>/\<$chapter\>\\<CR>\"ayyggVGd\"aP"

cat /root/.pen/documents/notes/ws/peniel/Bible-chapter-titles.txt | vedm "/$book\\<CR>/\<$chapter\>\\<CR>\"ayyggVGd\"aP"
