#!/bin/sh

lang="$1"
test -n "$lang" || exit 1

case "$lang" in
    cpp|c++) {
        ext=cpp
    }
    ;;

    bash|sh) {
        ext=sh
    }
    ;;

    hs|haskell) {
        ext=hs
    }
    ;;

    python) {
        ext=py
    }
    ;;

    clojure) {
        ext=clj
    }
    ;;

    scala) {
        ext=scala
    }
    ;;

    f-sharp) {
        ext=fs
    }
    ;;

    *) {
        ext="$(oci orspe -getval "(get-ext-for-lang $(aqf-nice "$lang"))")"
    }
    ;;
esac

: "${ext:="txt"}"

printf -- "%s\n" "$ext"