#!/bin/bash
export TTY

# Automatically cache
if ! test "$CI_CACHED" = "y"; then sn="$(basename -- "$0")"; cif "$sn" "$@"; exit "$?"; fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -eval-pp) {
        eval_pp=y
        shift
    }
    ;;

    *) break;
esac; done

# Scrape the var names from a bash input
scrape "\$\\{?[a-zA-Z_]+" | sed -e 's/^\$//' -e 's/{//' | uniqnosort | {
    if test "$eval_pp" = "y"; then
        sed 's/.*/printf -- "%s\\\\n" \"&=\\"$&\\";\";/'
    else
        cat
    fi
}
