#!/bin/bash
export TTY

. $PENELD/scripts/debug.sh

# Automatically cache
# -fretry is needed because this calls the same cif command and the retry timeout needs to be disabled
if ! test "$NO_CI" = y && ! test "$INSIDE_CI" = "y"; then sn="$(basename -- "$0")"; cif -fretry "$sn" "$@" 2>/tmp/getvars-debug.txt; exit "$?"; fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -eval-pp) {
        eval_pp=y
        shift
    }
    ;;

    *) break;
esac; done

# Scrape the var names from a bash input
scrape "\$\\{?[a-zA-Z_]+" | sed -e 's/^\$//' -e 's/{//' | uniqnosort | {
    if test "$eval_pp" = "y"; then
        sed 's/.*/printf -- "%s\\\\n" \"&=\\"$&\\";\";/'
    else
        cat
    fi
}
