#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

opt="$1"
case "$opt" in
    help) {
        do_pager=y
    }
    ;;

    *)
esac

if test "$do_pager" = "y"; then
    /usr/local/go/bin/go "$@" | pavs
else
    /usr/local/go/bin/go "$@"
fi
