#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

opt="$1"
case "$opt" in
    help) {
        do_pager=y
    }
    ;;

    *)
esac

if test "$1" = install && ! internet-connected-p; then
    exit 1
fi

if test "$do_pager" = "y"; then
    /usr/local/go/bin/go "$@" | pavs
else
    /usr/local/go/bin/go "$@"
fi
