#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

script_fp="$1"
rp="$(realpath "$script_fp")"
dn="$(dirname "$rp")"

# gomod_fp="$(cd "$dn"; dominating-file go.mod | head -n 1)"
# I want a way of avoiding having to cd into the directory
# but setting gomod_fp didn't do the job
# go run -modfile "$gomod_fp" "$@"

cd "$dn"

go run "$@"
