#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

test -f $MYGIT/jarun/googler/googler || ( gc "https://github.com/jarun/googler" | cat; ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -tor) {
        USETOR=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$USETOR" = "y"; then
    my-torify mypython $MYGIT/jarun/googler/googler "$@"
else
    $MYGIT/jarun/googler/googler "$@"
fi
