#!/bin/bash
export TTY

# go language server

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || go install golang.org/x/tools/gopls@latest &>/dev/null
 
# arbitrate ${GOPATH%%:*}/bin/gopls "$@"
${GOPATH%%:*}/bin/gopls "$@"
