#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || ( go install github.com/x-motemen/gore/cmd/gore@latest; go install github.com/mdempsky/gocode@latest; ) &>/dev/null

${GOPATH%%:*}/bin/gore "$@"
