#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || ( go install github.com/x-motemen/gore/cmd/gore@latest; go install github.com/mdempsky/gocode@latest; ) &>/dev/null

${GOPATH%%:*}/bin/gore "$@"
