#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

set -o pipefail

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty; then
    /bin/grep "$@" | pavs
else
    /bin/grep "$@"
fi

