#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# This is a chicken and egg problem
# I can't get it from proc, sadly.
# Does bash provide the information?
fds="$(show-fds)"

grepfilter-transform.els "$fds" "$@"
