#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# e.g. grepfilter slugify "rosie grep -o subs net.ipv4"

input_fp="$(cat | tf txt)"

transformer="$1"
test -n "$transformer" || exit 1
shift

matcher="$1"
test -n "$matcher" || exit 1
shift
