#!/bin/bash
export TTY

. $SCRIPTS/lib/hs
. $SCRIPTS/lib/stdin_exists

eat=n
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -eat) {
        eat=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$eat" = "n"; then
    set -- --no-start-anchor --no-end-anchor "$@"
fi

if stdin_exists; then
    input="$(cat)"
    nlines="$(p "$input" | awk 1 | wc -l)"

    if test "$nlines" = 1; then
        cases="$input"
    else
        cases="$(p "$input" | q -l | s join ' ')"
    fi

    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}

    eval "$HOME/.cargo/bin/grex $CMD $cases" | awk 1
else
    $HOME/.cargo/bin/grex "$@" | awk 1
fi
