#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# eval `resize`
# echo "$COLUMNS" | tv &>/dev/null

test "$#" -gt 0 && last_arg="${@: -1}"

if test "$last_arg" == "--help"; then
    ${GOPATH%%:*}/bin/gum "$@" | pen-strip-ansi | pavs
    exit "$?"
fi

# ${GOPATH%%:*}/bin/gum "$@"
# exit "$?"

subcommand="$1"
shift
case "$subcommand" in
    # table) {
    #     # Calculate the column widths to use from the terminal COLUMNS.
    #     echo "$COLUMNS" | tv &>/dev/null
    #     # TODO Do this inside gum.bb instead
    #     ${GOPATH%%:*}/bin/gum "$subcommand" -w "$COLUMNS" "$@"
    # }
    # ;;

    write) {
        # nvc -2 ${GOPATH%%:*}/bin/gum "$subcommand" "$@"
        # TMUX= nvt -2 ${GOPATH%%:*}/bin/gum "$subcommand" "$@"
        ${GOPATH%%:*}/bin/gum "$subcommand" "$@"
    }
    ;;

    *) {
        ${GOPATH%%:*}/bin/gum "$subcommand" "$@"
    }
    ;;
esac
