#!/bin/bash
export TTY

sn="$(basename "$0")"

if ! inside-tmux-p; then
    # I must also cat into in-tm
    # Make a new command for this purpose (capture stdin and send to container, then pipe into a new command)
    in-tm "$0" "$@"
    exit "$?"
fi

# Guru
# Version 1.0, bash

FRAMETYPE=tty

guru-logo Guru 1>&2

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nv) {
        USE_NVC=y
        shift
    }
    ;;

    -human|-talk-to-human) {
        PEN_ENGINE=Human
        shift
    }
    ;;

    -engine) {
        PEN_ENGINE="$2"
        shift
        shift
    }
    ;;

    -temp|-temperature) {
        export PEN_TEMPERATURE="$2"
        shift
        shift
    }
    ;;

    -tty|-nw|-t) {
        export PEN_USE_GUI=n
        FRAMETYPE=tty
        shift
    }
    ;;

    -context) {
        context="$2"
        shift
        shift
    }
    ;;

    -subject) {
        subject="$2"
        shift
        shift
    }
    ;;

    -win) {
        context="$(pen-tm cap-pane -nohist)"
        shift
    }
    ;;

    -sps) {
        do_split=y
        shift
    }
    ;;

    -gui) {
        export PEN_USE_GUI=y
        FRAMETYPE=gui
        shift
    }
    ;;

    *) break;
esac; done

if test "$do_split" = "y"; then
    if test -n "$context"; then
        pen-sps $0 -context "$context"
    else
        pen-sps $0
    fi
    exit "$?"
fi

export USE_NVC
export PEN_UPDATE
export PEN_ENGINE

PEN_ENGINE_ELISP="$PEN_ENGINE"

if test "$PEN_ENGINE" = nil; then
    PEN_ENGINE_ELISP=nil
elif test -n "$PEN_ENGINE"; then
    PEN_ENGINE_ELISP="\"$PEN_ENGINE\""
else
    PEN_ENGINE_ELISP=nil
fi

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

# test -n "$person" || {
#     echo "Person name required as parameter." 12
#     exit 1
# }

# if ! stdin_exists && test "$#" -eq 0; then
#     person="$(pen-readln "Chatbot name")"
# else
#     person="$@"
# fi

# PEN_USE_GUI is unset by design apparently

maybe_subject="$@"
if test -n "$maybe_subject"; then
    subject="$maybe_subject"
fi

if stdin_exists && ! test -n "$context"; then
    context="$(cat)"
    exec <&1
fi

if test -n "$context"; then
    if ! test -n "$subject"; then
        subject="$(echo "$context" | pen-str words 20 | penf --pool pf-get-language-1shot/1)"
    fi

    if test -z "$subject"; then
        subject="General knowledge"
    fi

    # Rather than specifying directly to the prompt function,
    # this value is taken up and remembered for future prompting within the apostrophe

    # Perhaps I should actually not use the pool
    # pen -nn -frametype "$FRAMETYPE" --pool -ic "(pen-engine $PEN_ENGINE_ELISP (progn (upd (guru $(cmd-nice-posix "$context") $(cmd-nice-posix "$subject")))(delete-other-windows)))"

    pen -nn -frametype "$FRAMETYPE" -ic "(pen-engine $PEN_ENGINE_ELISP (progn (upd (guru $(cmd-nice-posix "$context") $(cmd-nice-posix "$subject")))(delete-other-windows)))"
else
    if test -n "$subject"; then
        pen -nn -frametype "$FRAMETYPE" -ic "(pen-engine $PEN_ENGINE_ELISP (progn (upd (guru nil $(cmd-nice-posix "$subject")))(delete-other-windows)))"
    else
        pen -nn -frametype "$FRAMETYPE" -ic "(pen-engine $PEN_ENGINE_ELISP (progn (upd (call-interactively 'guru))(delete-other-windows)))"
    fi
fi