#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "$HOME/.local/bin/harlequin" || pyf "harlequin" &>/dev/null

$HOME/.local/bin/harlequin "$@"
