#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

if test "$#" -gt 0; then
    while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
        "") { shift; }; ;;
        -s) {
            /usr/bin/crc32 <(printf -- "%s" "$2")
            shift
            shift
        }
        ;;

        -sa) {
            shift
            /usr/bin/crc32 <(printf -- "%s" "$@")
            shift "$#"
            exit "$?"
        }
        ;;

        -f) {
            /usr/bin/crc32 "$2"
            shift
            shift
        }
        ;;

        *) {
            /usr/bin/crc32 "$1"
            shift
        }
        ;;

        *) break;
    esac; done
elif stdin_exists; then
    ( /usr/bin/crc32 <(cat) )
else
    /usr/bin/crc32 "$@"
fi
