#!/bin/bash
export TTY

# Total length = max-mant-len + 6

input="$(cat)"
maxmantlen="$1"
: "${maxmantlen:="15"}"

hash="$(p "$input" | pen-sha)"
name="$(p "$input" | cut -c1-$maxmantlen)-$hash"
strl=$(echo -n "$input" | wc -m)
if test "$strl" -gt "$maxmantlen"; then
    echo -n "$name"
else
    echo -n "$hash"
fi
