#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;

    -e|-ec|--editconf) {
        v /root/.config/hexabyte/config.toml
        exit "$?"
    }
    ;;

    -h|--help) {
        hexabyte --help | pavs
        exit "$?"
    }
    ;;

    *) break;
esac; done

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    input_fp="$(cat | tf txt)"
    exec 0<&1
    hexabyte "$input_fp" "$@"
    exit "$?"
fi

hexabyte "$@"
