#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

hebrew_chars="$(0</dev/null digraph-list HEBREW)"

# echo "אבגדהכמ" | tpop hebrew-letters-explain

grep -o . | while IFS=$'\n' read -r char; do
    (
    exec 0</dev/null
    line="$(printf -- "%s\n" "$hebrew_chars" | grep -P "^$char")"
    if test -n "$line"; then
        echo "$char $line"
    else
        echo -n "$char"
    fi
    :
    )
done | pavs
