#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    *=*) {
        envname="$(p "$opt" | pen-mcut -d= -f1)"
        histfile="$(p "$opt" | pen-mcut -d= -f2)"
        shift
    }
    ;;

    *) break;
esac; done

cmdname="$1"
case "$cmdname" in
    litecli) {
        envname=SQLITE_HISTORY
    }
    ;;

    *)
esac

SQLITE_HISTORY="$histfile"
export SQLITE_HISTORY

"$@"
