#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

iforcat() {
    fargs=()
    while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
        --) {
            shift
            break;
        }
        ;;

        *) {
            fargs+=("$1")
            shift
        }
        ;;
    esac; done

    if "${fargs[@]}"; then
        "$@"
    else
        cat
    fi
}

iforcat "$@"
