#!/bin/bash
export TTY

if ! { inside-docker-p && test -n ~/pen_user.txt; }; then
    if test "$NOEMACS" = "y"; then
        set -- env NOEMACS=y "$@"
    fi
    
    pen sh "$@"
    exit "$?"
fi

"$@"
