#!/bin/bash
export TTY

if ! in-pen-p; then
    if test -n "$PREFER_GUI"; then
        set -- env PREFER_GUI="$PREFER_GUI" "$@"
    fi

    if test -n "$NOEMACS"; then
        set -- env NOEMACS="$NOEMACS" "$@"
    fi

    pen sh "$@"
    exit "$?"
fi

"$@"
