#!/bin/bash
export TTY

# test
# tmux run -b "echo hi | in-tty pa -tf"

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

. $PENEL_DIR/scripts/utils.sh

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    -ifnopipe|-upo) {
        unless_pipe_out=y
        shift
    }
    ;;

    *) break;
esac; done

CMD="$(cmd "$@")"

# test:
# nem bible-search disciple | v

if test "$unless_pipe_out" = y && test "$ispipe" = 0; then
    # echo pipingout | hls red 1>&2
    eval "$CMD"
elif test "$istty" = 0; then
    # echo is tty | hls red 1>&2
    eval "$CMD"
elif test "$istty_stderr" = 0; then
    # echo is tty stderr | hls red 1>&2
    if test "$hasstdin" = 0; then
        (
        exec 1>&2
        eval "$CMD"
        )
    else
        (
        exec <&2
        exec 1>&2
        eval "$CMD"
        )
    fi
else
    # echo tpop 1>&2
    tpop -E "$CMD"
fi
