#!/bin/bash
export TTY

in-tm() {
    while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
        "") { shift; }; ;;
        -n) {
            session_name="$2"
            shift
            shift
        }
        ;;

        *) break;
    esac; done

    if test "$PEN_NO_TM" = "y"; then
        "$@"
    elif inside-docker-p && inside-tmux-p; then
        "$@"
    elif test "$PEN_USE_GUI" = "y"; then
        "$@"
    else
        if test -n "$session_name"; then
            pen-tm init-or-attach -d "$@"
        else
            pen-tm init-or-attach -d -n "$session_name" "$@"
        fi
    fi
}

in-tm "$@"
