#!/bin/bash
export TTY

# test
# tmux run -b "echo hi | in-tty pa -tf"

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }
is_tty_stderr() { [ -t 2 ] && ! test "$TERM" = "dumb"; }

CMD="$(cmd "$@")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

if is_tty; then
    # echo is tty 1>&2
    eval "$CMD"
# elif is_tty_stderr; then
#     echo is tty stderr 1>&2
#     (
#     exec <&2
#     exec 1>&2
#     eval "$CMD"
#     )
else
    # echo tpop 1>&2
    tpop -E "$CMD"
fi
