#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# TODO Make it so the info script also has a query mode
# v +/"m4) {" "$PENELD/scripts/container/man"
# How to do that?
# j:Info-find-file

info_exists() {
    content="$(/usr/bin/info -o /dev/stdout "$@")"
    test -n "$content"
}

sn="$(basename -- "$0")"

. $PENEL_DIR/scripts/utils.sh

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -q) {
        # Query if a tut exists
        query=y
        shift
    }
    ;;

    *) break;
esac; done

# agi info
if ! in-pen-p; then
    if test "$has_stdout" = y; then
        ocif in-pen "$sn" "$@" | pavs
    else
        in-pen in-tm "$sn" "$@"
    fi
    exit "$?"
fi

: "${bin:="/usr/bin/info"}"

query="$@"

if test "$has_stdout" = y; then
    "$bin" "$query" -o - | pavs
elif test "$sn" = binfo; then
    nvc "$bin" "$query"
else
    einfo "$query"
fi
# if test -f "$bin"; then
#     nvc "$bin" "$query"
# else
#     einfo "$query"
# fi
