#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# https://www.howtogeek.com/411366/how-to-copy-files-with-the-install-command-on-linux/

/usr/bin/install "$@"
