#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# emacs-based fuzzy finder
# - pipe in the list
# - output one item

input_fp="$(cat | tf txt)"
output_fp="$(echo -n | tf txt)"

elisp="(progn (save-window-excursion (switch-to-buffer \"*scratch*\") (write-to-file (let ((ivy-height 100) (ivy-display-style 'plain) (ivy-display-function 'ivy-posframe-display)) (ivy-completing-read \"ivy: \" (str2lines (cat \"$input_fp\")))) \"$output_fp\"))(delete-frame))"

pen-e -e "$elisp"
cat "$output_fp"
