#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# jq-showschema-old "$@" | sed 's/\.\([a-z-]\+\)/\.\["\1"\]/g'
# jq-show-schema-values-quine "$@" | sed 's/\.\([a-z-]\+\)/\.\["\1"\]/g'
# vim +/"\"Tarzan\"|(Tarzan)" "$NOTES/ws/regular-expressions-regex/best-trick.org"
jq-show-schema-values-quine "$@" | sed -e 's/\.\(\([a-z]\+\)\|\([a-z-]\+\)\)/\.\["\3"\2\]/g' -e 's/\[""\([a-z]\+\)\]/\1/g' -e 's/\]\.\[/][/g'