#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# jq-showschema-old "$@" | sed 's/\.\([a-z-]\+\)/\.\["\1"\]/g'
# jq-show-schema-values-quine "$@" | sed 's/\.\([a-z-]\+\)/\.\["\1"\]/g'
# vim +/"\"Tarzan\"|(Tarzan)" "$NOTES/ws/regular-expressions-regex/best-trick.org"
jq-show-schema-values-quine "$@" | sed -e 's/\.\(\([a-z]\+\)\|\([a-z-]\+\)\)/\.\["\3"\2\]/g' -e 's/\[""\([a-z]\+\)\]/\1/g' -e 's/\]\.\[/][/g'