#!/bin/bash

jq -r '[path(..)|map(if type=="number" then "[]" else tostring end)|join(".")|split(".[]")|join("[]")]|unique|map("."+.)|.[]' |
    sed 's/\.\([a-zA-Z0-9]\+-[a-zA-Z0-9-]\+\)/."\1"/g' |
    uniqnosort

# sed "s=\.\([a-zA-Z]*[^a-zA-Z\.]\+[a-zA-Z]*\)=\.\"\1\"=g"
# s/\.\([^a-zA-Z[\].]\+\)/\."\1"/g

# If it has a 
