#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/jqp" || go install github.com/noahgorstein/jqp@latest &>/dev/null

${GOPATH%%:*}/bin/jqp "$@"
