#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/jqp" || go install github.com/noahgorstein/jqp@latest &>/dev/null

${GOPATH%%:*}/bin/jqp "$@"
