#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

test -f $HOME/.cargo/bin/jt || cargo install "jt" &>/dev/null

if test "$#" -eq 0; then
    unbuffer $HOME/.cargo/bin/jt | less -rS
else
    $HOME/.cargo/bin/jt "$@"
fi
