#!/bin/bash
export TTY

# Things relating to key bindings

opt="$1"
case "$opt" in
    f8) {
        date-short

        exit $?

        shift
    }
    ;;

    template) {
        :
    }
    ;;

    *)
esac
