#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# list installed libraries
# ldconfig -v

set -o pipefail

/usr/sbin/ldconfig "$@" | pavs
