#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# list installed libraries
# ldconfig -v

set -o pipefail

test -f /usr/sbin/ldconfig && : "${bin:="/usr/sbin/ldconfig"}"
test -f /sbin/ldconfig && : "${bin:="/sbin/ldconfig"}"

"$bin" "$@" | pavs
