#!/bin/bash
export TTY

# https://lem-project.github.io/lem-page/usage/usage/
# https://lem-project.github.io/lem-page/installation/configuration/

# export TERM=xterm-256color

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# This works but

# --rm 
# docker run -ti -v `pwd`:/app 40ants/lem:latest

$HOME/.roswell/bin/lem-ncurses "$@"
