#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/lf" || env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest &>/dev/null

${GOPATH%%:*}/bin/lf "$@"
