#!/bin/bash
export TTY

cat /root/.pen/documents/english-kjv.txt | sed 's/[^a-zA-Ze]/\r\n/g' | dos2unix | sed '/^$/d' | sort | uniq | tr '[:upper:]' '[:lower:]' | sort | uniq | sed -n '/.../p' | pavs
