#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/usr/local/bin/litecli" || pyf "litecli" &>/dev/null

# export PAGER=fpvd
# export PAGER=litecli-editor
# vim +/"pager = litecli-editor" "$HOME/.config/litecli/config"

/usr/local/bin/litecli "$@"
