#!/bin/sh

# Example of usage:
# export PEN_PROMPTS_DIR=$MYGIT/semiosis/prompts
# lm-complete translate-to.prompt French Goodnight
# or:
# echo French | lm-complete translate-to.prompt Goodnight

test -n "$PEN_LM_COMMAND" || {
    echo "PEN_LM_COMMAND not supplied"
    exit 1
}

: "${PEN_MAX_TOKENS:="60"}"
: "${PEN_TEMPERATURE:="0.8"}"
: "${PEN_TOP_P:="1"}"
: "${PEN_PROMPT:="Once upon a time"}"

export PEN_MAX_TOKENS
export PEN_TEMPERATURE
export PEN_TOP_P
export PEN_PROMPT

# This file expects the PEN_PROMPTS_DIR

# Update caches (would override PEN_CACHE)
if "$UPDATE" = y; then
    PEN_CACHE=
fi

# if PEN_CACHE==y then pen.el has indicated this should be cached/memoised.
# This is handled by `pen-ci`
export PEN_CACHE

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists; then
    # stdin becomes the first argument after the .prompt path
    set -- "$(cat)" "$@"
fi

# pen-ci will possibly cache/memoize the command
pen-ci "$PEN_LM_COMMAND" "$@"