#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# I might want to actually configure printers,
# even, say, a printer that generates a file rather than print to a physical printing device.

lp-stub-showcmd -bn lp "$@"

# /usr/bin/lp "$@"
