#!/bin/bash
export TTY

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$NO_STDIN" = y ` # for notty. e.g. notty xt vim ` && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    if is_tty; then
        xargs ls -1dt --color=tty -A --
    else
        cat
    fi
else
    if is_tty; then
        ls -1dt --color=tty -A -- "$@"
    else
        printf -- "%s\n" "$@"
    fi
fi
