#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/usr/local/bin/lyricy" || pyf "lyricy" &>/dev/null

/usr/local/bin/lyricy "$@"
