#!/bin/bash
export TTY

# Mad Tea-Party
# Version 1.0, bash

# Mad Tea-Party is a sandbox for language-model-powered chatbots and human interaction.
# AI personalities may be created and join the IRC server, interact inside of channels, etc.
# Human users may subsume AI personalities.

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -join) {
        irc_channel_name="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

pen-x \
    -sh "adduser pen" \
    -e "New password" -s pen -c m \
    -e "Retype" -s pen -c m \
    -e "Full Name" -s Pen -c m \
    -c m \
    -c m \
    -c m \
    -c m \
    -e correct -s Y -c m \
    -i
