#!/bin/bash
export TTY

MAKEFILE="$1"

: ${MAKEFILE:="Makefile"}

make -prRn "$MAKEFILE" : 2>/dev/null  | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$'