#!/bin/bash
export TTY

if [ -t 0 ] && test -f "$1"; then
    exec < <(cat "$1")
fi

pandoc -f markdown -t org |
    sed '/:PROPERTIES/d' |
    sed '/:CUSTOM_ID:/d' |
    sed '/:END:/d' |
    sed 's/\\_/_/g' | pa -E "tf org | xa og"
