#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    tf_in="$(tf md || echo /dev/null)"
    set -- "$tf_in" "$@"
fi

fp="$1"

td_md="$(mktemp -t -d td_mdXXXXXX || echo /dev/null)"

fn=$(basename "$fp")
dn=$(dirname "$fp")
ext="${fn##*.}"
mant="${fn%.*}"

cp -a "$fp" "$td_md"
cd "$td_md"

# echo "$td_md"
# exit 0

newfn="${mant}.txt"

# echo "$newfn"
# exit 1

pandoc -f markdown -t plain "$fn" -o "$newfn"

nrp="$(realpath "$newfn")"

# pwd
# realpath "$newfn"
# echo "$nrp"
# exit 1

is_tty() { [ -t 1 ]; }

if is_tty; then
    exec <&1
    vs "$nrp"
else
    cat "$nrp"
fi
