#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -dt|-date) {
        : "${date:="$2"}"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${date:="$(date +%d.%m.%y)"}"

test -n "$date" || exit 1

EXTRA_METADATA="${EXTRA_METADATA}_${date}"

export EXTRA_METADATA
"$@"
