#!/bin/bash
export TTY

export UPDATE=y

statement="$@"
: "${statement:="The best things in life are free."}"
while :; do
    statement="$(pen -u pf-most-important-thing/1 "$statement")"
    echo "$statement"

    echo
done