#!/bin/bash
export TTY

export UPDATE=y

statement="$@"
: "${statement:="Love the Lord your God with all your heart, soul and mind, and love your neighbour as yourself."}"

if ! test "$#" -gt 0; then
    echo "$statement"
    echo
fi

while :; do
    statement="$(pen --pool pf-most-important-thing/1 "$statement")"
    echo "$statement"
    echo
done
