#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# This replaces text inside and also renames files based on a sed
# command

test "$#" -gt 1 || exit 1

sed_cmd="$1"
shift

ms "$sed_cmd" "$@"
rename "$sed_cmd" "$@"