#!/bin/bash
export TTY

sudoargs=()
sudoenvs=()
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -u) {
        sudoargs=( "$opt" "$2" "${sudoargs[@]}" )
        shift
        shift
    }
    ;;

    -h) {
        sudoenvs=( "HOME=$HOME" "${sudoenvs[@]}" )
        shift
    }
    ;;

    *) break;
esac; done

hasdashes() {
    cmd "$@" | grep -q -P '(^| )--( |$)'
}

before_dashes() {
    eval "set -- $(cmd "$@" | sed -e "s/^-- .*//"  -e "s/ -- .*//" -e "s/ --$//")"
    printf -- "%s" "$(cmd "$@")"

    return 0
}

after_dashes() {
    eval "set -- $(cmd "$@" | sed -e "s/.* -- //" -e "s/.* --$//" -e "s/^-- //")"
    printf -- "%s" "$(cmd "$@")"

    return 0
}

if hasdashes "$@"; then
    eval /usr/bin/sudo "${sudoargs[@]}" -H -E $(before_dashes "$@") env "PATH=$PATH"  "${sudoenvs[@]}" $(after_dashes "$@")
else
    # Specify HOME to env to force preservation of the HOME variable
    /usr/bin/sudo "${sudoargs[@]}" -H -E env "PATH=$PATH" "${sudoenvs[@]}" "$@"
fi