#!/bin/bash
export TTY

. $PENELD/scripts/utils.sh

if stdin_exists && test "$#" -eq 0; then
    input_fp="$(cat | tf sh)"

    # if test "$ispipe" = 0; then
    #     bash "$input_fp"
    # else
    #     # exec 2>&0;
    #     
    # fi

    bash "$input_fp"
else
    eval "$(cmd "$@")"
fi
