#!/bin/bash
export TTY

. $PENELD/scripts/utils.sh

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -dohs) {
        DO_HS=y
        shift
    }
    ;;

    -tv) {
        DO_TV=y
        shift
    }
    ;;

    -tvnw|-tvsp[hvs]) {
        DO_TV=y
        TV_TYPE="$(printf -- "%s" "$opt" | sed 's/^-tv//')"
        shift
    }
    ;;

    -nw|-sp[hvs]) {
        DO_TV=y
        TV_TYPE="$(printf -- "%s" "$opt" | sed 's/^-//')"
        shift
    }
    ;;

    *) break;
esac; done

: "${TV_TYPE:="-sps"}"

if test "$DO_HS" = "y"; then
    . $SCRIPTS/lib/hs
fi

if stdin_exists && test "$#" -eq 0; then
    input_fp="$(cat | tf sh)"

    # if test "$ispipe" = 0; then
    #     bash "$input_fp"
    # else
    #     # exec 2>&0;
    #     
    # fi

    bash "$input_fp"
else
    while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
        -E) {
            DO_EXEC=y
            shift
        }
        ;;

        *) break;
    esac; done

    if test "$DO_EXEC" = "y"; then
        CMD="$1"
    else
        CMD="$(cmd "$@")"
    fi

    if test "$DO_TV" = "y"; then
        echo "$CMD" | tv "-$TV_TYPE" &>/dev/null
    fi
    eval "$CMD"
fi
