#!/bin/bash
export TTY

. $PENELD/scripts/utils.sh

if stdin_exists && test "$#" -eq 0; then
    input_fp="$(cat | tf sh)"

    # if test "$ispipe" = 0; then
    #     bash "$input_fp"
    # else
    #     # exec 2>&0;
    #     
    # fi

    bash "$input_fp"
else
    while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
        -E) {
            DO_EXEC=y
            shift
        }
        ;;

        *) break;
    esac; done

    if test "$DO_EXEC" = "y"; then
        CMD="$1"
    else
        CMD="$(cmd "$@")"
    fi

    eval "$CMD"
fi
