#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# TODO Have also a search mechanism for mygit.

test -d "/home/shane/source/git" && : "${dp:="/home/shane/source/git"}"
test -d "/volumes/home/shane/var/smulliga/source/git" && : "${dp:="/volumes/home/shane/var/smulliga/source/git"}"

zcd "$dp"
