#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nv) {
        NEOVIM=y
        shift
    }
    ;;

    -nnv) {
        NEOVIM=n
        shift
    }
    ;;

    *) break;
esac; done

: "${NEOVIM:="y"}"

if test "$NEOVIM" = "y"; then
    # nvc /bin/nano "$@"
    nvc /bin/nano -m "$@"
else
    # nvc /bin/nano "$@"
    /bin/nano -m "$@"
fi

:

