#!/bin/bash

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$DO_EXEC" = "y"; then
    CMD="$1"
else
    CMD="$(cmd "$@")"
fi

slug="$(echo "$CMD" | tr -d '\n' | slugify | cut -c -40)"

tf_new_script="/tmp/nsfa-$slug.sh"
echo "$tf_new_script" | ds -s last-nsfa
rm -f "$tf_new_script"

IFS= read -r -d '' scriptcode <<'HEREDOC'
: ${TTY:="$(tm-tty)"}
export TTY
stty stop undef 2>/dev/null; stty start undef 2>/dev/null;
HEREDOC

printf -- "%s\n" "$scriptcode" >> "$tf_new_script"
export PATH=$HOME/scripts:$PATH

if test -n "$CWD" && test -d "$CWD"; then
    cmd-nice cd "$CWD" | awk 1 >> "$tf_new_script"
fi

printf -- "%s\n" "$CMD" >> "$tf_new_script"
chmod a+x "$tf_new_script"
echo -n "$tf_new_script"
