#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

is_stdout_pipe() {
    # If stout is a pipe
    [[ -p /dev/stdout ]]
}

fp="$PEN/documents/Christianity/Nicene-Creed.txt"

if is_stdout_pipe; then
    cat "$fp"
else
    v "$fp"
fi