#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

withopts nem -- "$@"

# export NOEMACS=y
# 
# is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }
# 
# if is_tty && test "$#" -eq 0; then
#     zsh
# else
#     "$@"
# fi
