#!/bin/bash
export TTY

# Emacs uses this command through the 'alert' package

pen-rc-test notify || exit 0

# Instead of using display-message, change the name of the session?
set -m
# tmux display-message "$@" &>/dev/null & disown
tm-notify "$@" &>/dev/null & disown

# Doesn't work in docker
# /usr/bin/notify-send -t 500 "$@"
