#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# /usr/bin/notmuch "$@"

opt="$1"
case "$opt" in
    show|search) {
        do_pagify=y
    }
    ;;

    *)
esac

if test "$do_pagify" = "y"; then
    spin -t /usr/local/bin/notmuch "$@" | pavs
else
    spin -t /usr/local/bin/notmuch "$@"
fi
