#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# Test the speed of nvim:
# nvim -u $HOME/.nvimrc -c "call TermAndQuit(\"bash\")" -c "call GeneralSyntax()" -c "call NumberSyntax()" -c "normal! i"

# neovim is horrible -- never use it
# You can't even do ":!vi ~/.vimrc"
# It doesn't have a tty for ! commands.

# nvim changed my cursor from block into line

extra_commands="silent! echom"
if pen-rc-test -f black_and_white; then
    extra_commands+="|call BWSyntax()"
fi

test -f "/usr/local/bin/nvim" && : "${bin:="/usr/local/bin/nvim"}"
test -f "/usr/bin/nvim" && : "${bin:="/usr/bin/nvim"}"
"$bin" -u $HOME/.nvimrc -c "$extra_commands" "$@"

# alt nvim "$@"
