#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# neovim is horrible -- never use it
# You can't even do ":!vi ~/.vimrc"
# It doesn't have a tty for ! commands.

# nvim changed my cursor from block into line

test -f "/usr/local/bin/nvim" && : "${bin:="/usr/local/bin/nvim"}"
test -f "/usr/bin/nvim" && : "${bin:="/usr/bin/nvim"}"
"$bin" "$@"

# alt nvim "$@"
