#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# Test the speed of nvim:
# nvim -u $HOME/.nvimrc -c "call TermAndQuit(\"bash\")" -c "call GeneralSyntax()" -c "call NumberSyntax()" -c "normal! i"

# neovim is horrible -- never use it
# You can't even do ":!vi ~/.vimrc"
# It doesn't have a tty for ! commands.

# nvim changed my cursor from block into line

test -f "/usr/local/bin/nvim" && : "${bin:="/usr/local/bin/nvim"}"
test -f "/usr/bin/nvim" && : "${bin:="/usr/bin/nvim"}"
"$bin" "$@"

# alt nvim "$@"
