#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

fp="$1"
test -f "$fp" || exit 1

if printf -- "%s\n" "$fp" | xa file | grep -q SQLite; then
    # edbi "$fp"
    litecli "$fp"
else
    printf -- "%s\n" "$fp" | xa file
    pak
fi
