#!/bin/bash
export TTY

# oc -g makes a google link

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -nc) {
        NOCACHE=y
        shift
    }
    ;;

    -b|-bn) {
        BASENAME=y
        shift
    }
    ;;

    -u) {
        UPDATE=y
        shift
    }
    ;;

    -l) {
        NEWLINE=y
        shift
    }
    ;;

    -m) {
        exec 1> >(orgurl2mdurl)
        shift
    }
    ;;

    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$DO_EXEC" = "y"; then
    CMD="$1"
else
    CMD="$(cmd-nice "$@")"
fi

export UPDATE
export BASENAME

if test "$NEWLINE" = "y"; then
    exec 1> >(awk 1)
fi

if test "$NOCACHE" = "y"; then
    eval "org clink $CMD"
else
    # ci -meta "$BASENAME" org clink "$@"
    eval "ci -meta \"$BASENAME\" org clink $CMD"
fi
