#!/bin/bash

: "${OPENAI_API_KEY:="$PEN_LM_KEY"}"

if test -s $HOME/.pen/openai_api_key; then
    : "${OPENAI_API_KEY:="$(cat $HOME/.pen/openai_api_key)"}"
fi

test -n "$OPENAI_API_KEY" || {
    echo "OPENAI_API_KEY not given to script"
    exit 1
}

export OPENAI_API_KEY

$MYGIT/openai/openai-python/examples/semanticsearch/semanticsearch.py "$@"