#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# See if anything here is useful
# https://github.com/CrazyPython/gpt3-cli

yq() {
    command yq "$@" 2>/dev/null
}

# TODO Ensure that this never debugs the output, because I don't want to display the key

last_arg="${@: -1}"
if test "$last_arg" = "-h"; then
    /usr/local/bin/openai "$@" |& pavs
    exit $?
fi

: "${OPENAI_API_KEY:="$(cat $HOME/.myrc.yaml | yq -r '.openai_api_key')"}"; export OPENAI_API_KEY

/usr/local/bin/openai "$@" |
    hc "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" |
    pavs
