#!/bin/bash
export TTY

# Pipe into this to pipe into numpy
# Just use opy

. $SCRIPTS/lib/hs

sn="$(basename "$0")"

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    if test "$iscsv" = "y"; then
        infp="$(tf csv)"
    else
        infp="$(tf tsv)"
    fi

    set -- "$infp" "$@"
    exec <&2
fi

opy -show "$@" "$sn"
