#!/bin/bash
export TTY

fp="$1"
test -f "$fp" || exit 1
rp="$(realpath "$fp")"

sn="$(basename -- "$0")"

: "${VANILLA:="y"}"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nov) {
        VANILLA=n
        shift
    }
    ;;

    *) break;
esac; done

case "$sn" in
    org2pdf) {
        f=org-latex-export-to-pdf
    }
    ;;

    org2html) {
        f=org-html-export-to-html
    }
    ;;

    *)
esac

# This is fast but to export with custom latex options, I should use the main emacs instead

echo "Running $sn through emacs" 1>&2

if test "$VANILLA" = "y"; then
    unbuffer x -shE "emacs -nw -Q $(aqf-nice "$fp")" -e UU -m : -s "(setq org-export-with-broken-links t)" -c m -m x -s "$f" -c m -sl 2 -m x -s kill-emacs -c m -i &>/dev/null
else
    unbuffer x -shE "emacs -nw -Q $(aqf-nice "$fp")" -e UU -m : -s "(setq org-export-with-broken-links t)" -c m -m x -s "$f" -c m -sl 2 -m x -s kill-emacs -c m -i &>/dev/null
fi

echo "Running $sn through emacs... done!" 1>&2