#!/bin/bash
export TTY

# Shadow.flf

IFS= read -r -d '' paracosm_logo <<'HEREDOC'
  __ \    _` |   __|  _` |   __|   _ \    __|  __ `__ \
  |   |  (   |  |    (   |  (     (   | \__ \  |   |   |
  .__/  \__,_| _|   \__,_| \___| \___/  ____/ _|  _|  _|
 _|
             Your Own World in Plain Text!
HEREDOC

echo
printf -- "%s\n" "$paracosm_logo" | hls dred