#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

sel="$(in-tty -E "cat $PENCONF/documents/notes/ws/lists/peniel/passage-titles.org | fzf")"

if test -n "$sel"; then
    sel="$(p "$sel" | sed -e 's/^\[\[bible://' -e 's/\]\[.*//')"
    nasb -E "$sel"
fi