#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

input="$(cat)"
output="$(printf -- "%s\n" "$input" | "$@")"

printf -- "%s\n" "$input" | awk 1 | paste - <(printf -- "%s\n" "$output")
