#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# e:xelatex

test "$#" -gt 0 && last_arg="${@: -1}"

final-tidy-latex "$last_arg"

/usr/bin/pdflatex -interaction nonstopmode "$@"
