#!/bin/bash
export TTY

shopt -s nullglob

# for fp in $(glob '*.pdf'); do
# for fp in *.pdf; do
# for fp in $(find . -name '*.pdf' | q -lf | s join); do
find . -iname '*.pdf' | awk 1 | while IFS=$'\n' read -r fp; do
(
    exec 0</dev/null
    echo "$fp" 1>&2

    fn=$(basename "$fp")
    dn=$(dirname "$fp")
    (
        cd "$dn"
        ext="${fn##*.}"
        mant="${fn%.*}"
        
        if ! test -f "${mant}.txt" || ! test -s "${mant}.txt"; then
            ebook-convert "$fn" "${mant}.epub"
        fi
    )
)
done
