#!/bin/bash

# See also extended glob script: e:eg

# bash globs are not the best because of nullglob madness
shopt -s nullglob
# However bash globs have double star
shopt -s globstar

glob="$1"
# Change the () and ' ' into ? which is a wildcard
glob="$(printf -- "%s" "$glob" | tr "[' ()]" '?')"

cmd="eval printf -- \"%s\\\\\\n\" $(cmd "$glob")"

out="$(eval "$cmd")"

if test -n "$out"; then
    printf -- "%s\n" "$out"
fi

test -n "$out"
