#!/bin/bash
export TTY

# $MYGIT/charmbracelet/glow/glow "$@"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nc) {
        nocolor=y
        shift
    }
    ;;

    -f) {
        force_color=y
        shift
    }
    ;;

    *) break;
esac; done

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    input_fp="$(cat | tf md)"
    set -- "$@" "$input_fp"
    exec <&2
    exec <`tm-tty` `# see etty` 
fi

unbuffer_maybe() {
    if test "$nocolor" = "y"; then
        "$@" | pavs
    elif test "$force_color" = "y"; then
        unbuffer "$@"
    else
        "$@"
    fi
}

unbuffer_maybe ~/repos/glow/glow "$@" | s remove-leading-and-trailing-newlines | pa -E "less -rS"
