#!/bin/bash
export TTY

sn="$(basename "$0")"

export LINES

WINCMD="sph -p 90"
# WINCMD="spv -p 30"

pattern=
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    -nv) {
        NEOVIM=y
        shift
    }
    ;;

    -sph) {
        WINCMD="sph -p 90"
        shift
    }
    ;;

    -spv) {
        WINCMD="spv -p 10"
        shift
    }
    ;;

    -|-in) {
        STDIN_EXISTS=y
        shift
    }
    ;;

    ## This does not work
    ++*) { # pattern
        pattern="$(printf -- "%s" "$opt" | sed 's/^++//' | chomp)"

        vimpat+="+/\(\\<$pattern\\>\( -[^ ]\+\)* [^-]\)\@<=."

        # vimopts_end+=" -c startinsert "
        vimopts_end+=" -c StartAppend "
        shift
    }
    ;;

    +/*) { # pattern
        pattern="$(printf -- "%s" "$opt" | sed 's=^+/==' | chomp)"

        vimpat+="+/$pattern"

        vimopts_end+=" -c StartAppend "

        shift
    }
    ;;

    *) break;
esac; done

stdin_exists() {
    ! [ -t 0 ]
}
stdin_exists && STDIN_EXISTS=y

tf_stdin="$(pen-ux tf stdin txt 0</dev/null || echo /dev/null)"

if test "$STDIN_EXISTS" = "y"; then
    cat > "$tf_stdin"
fi

exec 0</dev/null

: ${CMD:="$(cmd "$@")"}
: "${CMD:="cat | less -rS"}"

printf -- "%s\n" "$CMD" | pen-ds -s rtcmd_init

if test "$STDIN_EXISTS" = "y"; then
    CMD="cat $(cmd "$tf_stdin") | $CMD"
fi

qfd() {
    pen-esc "\"\$" | sed 's/^.*$/"&"/'
}

cmdparas="$(echo -e -n "$CMD" | qfd | pen-esc '`')"

printf -- "%s\n" "$cmdparas" | pen-ds -s rtcmd_cmdparas

CREATED_PANE_ID="$(eval "pen-tm -f -d $WINCMD $(test "$NEOVIM" = "y" && p "-nvt") -pakf -safe -d -P $cmdparas" | pen-scrape '%[0-9]+')"

TMUX= eval "pen-tm -f -d spv -pakf -safe -d -t '$CREATED_PANE_ID' $cmdparas"

exec <`pen-tm-tty` `# see etty`

echo -e "$CMD" | pen-v "$vimpat" -ft sh -rt "cat | pen-tm -f -S -tout rs $(test "$NEOVIM" = "y" && p "-nv") -xargs -pakf -safe -t '$CREATED_PANE_ID'" -pc "set ls=0" $vimopts_end