#!/bin/bash
# export TTY="$(tty)"

export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

# export FZF_DEFAULT_COMMAND='rg --hidden --no-ignore --files'
# export FZF_DEFAULT_COMMAND="find . -maxdepth 1 -printf '%P\n'"


# The =fzf= wrapper must not change the command line arguments.
# This is so utilities making use of fzf continue to work.
# Change options with the pen-mfz script.


# ls -la /proc/$$/fd > /tmp/yo.txt

# Kernel update broke fzf
# https://github.com/junegunn/fzf/issues/1486#start-of-content

unset CWD

# free bindings
# alt-q # taken
# alt-x
# alt-y
# ctrl-alt-a
# ctrl-alt-b
# ctrl-alt-c # taken
# ctrl-alt-d
# ctrl-alt-e
# ctrl-alt-f # taken
# ctrl-alt-g
# ctrl-alt-h
# ctrl-alt-i
# ctrl-alt-j
# ctrl-alt-k
# ctrl-alt-l
# ctrl-alt-m
# ctrl-alt-n
# ctrl-alt-o
# ctrl-alt-p
# ctrl-alt-q
# ctrl-alt-r
# ctrl-alt-s
# ctrl-alt-t
# ctrl-alt-u
# ctrl-alt-v
# ctrl-alt-w
# ctrl-alt-x # taken
# ctrl-alt-y
# ctrl-alt-z


# This is so we have LINES and COLUMNS to play with
# eval `resize`

# {q}  --  current query string
#  {}  --  current file
# {+}  --  selected files
#          missing a way to select ALL the input. instead, capture the
#          input into a variable. actually, capture to a file so fzf
#          streams the input.

preview_hidden=y
do_sort=y

# preview_opts="right:30%"
preview_opts="up:30%"

minimise=n

MULTI=y
COMPLETE_WITH_PREVIEW=n

CMD="$(cmd-nice-posix "$@")"
: ${CMD:="$(cmd-nice-posix "$@")"}

opts=""

bindings=""
#bindings+="ctrl-a:select-all+accept,"
bindings+="alt-a:select-all,"
bindings+="f1:abort,"
# bindings+="alt-f1:abort," # there is no alt-f1 annoyingly
bindings+="alt-u:deselect-all,"
bindings+="ctrl-k:kill-line,"
bindings+="alt-k:jump,"
bindings+="tab:toggle-preview,"

# But right (and C-M-Right) is used to move along the pattern at the
# top, not just the results list
# bindings+="right:toggle,"
bindings+="ctrl-alt-f:toggle,"
bindings+="alt-z:toggle,"
bindings+="ctrl-j:toggle,"
bindings+="ctrl-alt-x:up+toggle,"
bindings+="ctrl-alt-c:down+toggle,"

bindings+="up:up,"
bindings+="down:down,"
bindings+="ctrl-p:toggle+up,"
bindings+="ctrl-n:toggle+down,"
bindings+="change:top," # triggered whenever the query string is changed.
# alt-0 doesn't work.
# bindings+="alt-0:top,"
bindings+="alt-t:top,"
# No function to go to the last result
# bindings+="alt-4:bottom,"

mfie="pen-pl {+}" # 'multi' field index expression

# This comes from pen-mfz script
if test "$FZF_PREPEND_DIR" = "y"; then
    mfie="$mfie | prepend-string $(cmd-nice-posix "$CWD/")"
fi

mfl="$mfie | q -l | tr -d '\n'"
bindings+="alt-r:execute-silent($mfie | awk 1 | head -n 1 | pen-ux drn | pen-tm -f -S -tout spv -xargs ranger),"
bindings+="alt-o:execute-silent($mfie | awk 1 | head -n 1 | q -l -f | pen-tm -S -tout nw -xargs o),"
bindings+="alt-y:toggle-all,"
bindings+="alt-g:execute-silent(tmux run -b \"pen-tsk M-y M-c M-y; sleep 0.2; unbuffer pen-xc | pen-tv &>/dev/null\"),"
bindings+="alt-l:execute-silent($mfie | pen-tm -f -S -tout spv v),"
bindings+="alt-e:execute-silent($mfl | pen-tm -f -S -tout spv -xargs pin),"
bindings+="alt-v:execute-silent($mfl | pen-tm -f -S -tout sps -xargs v),"
bindings+="alt-q:execute-silent($mfl | pen-tm -f -S -tout spv -xargs edit-with),"
bindings+="alt-s:execute-silent($mfl | pen-umn | head -n 1 | pen-ux drn | xargs pen-tm -d spv -c),"
bindings+="alt-h:execute-silent($mfl | pen-umn | head -n 1 | pen-ux drn | xargs pen-tm -d sph -c),"
bindings+="alt-w:execute-silent(pen-tm -f -d spv 'v '$tf_input),"
bindings+="alt-f:execute-silent($mfie | fzf-thing),"
bindings+="alt-i:execute-silent($mfie | awk 1 | $preview | pen-tm -f -S -i spv -noerror 'pen-mfz -nm'),"
bindings+="alt-p:execute-silent($mfie | fzf-thing)," # this should put the preview in a new window
bindings+="alt-n:execute-silent($mfie | pen-ux fn | pen-xc),"
bindings+="alt-d:execute-silent($mfie | awk 1 | xargs -l1 dirname | pen-xc -i -n),"
bindings+="alt-c:execute-silent($mfie | pen-umn | chomp | sed 's/#[^#]\+$//' | sed 's/\s\+$//' | pen-xc -i -n),"
bindings+="alt-m:execute-silent($mfie | pen-mnm | chomp | pen-xc -i -n),"
bindings+="alt-j:execute-silent($mfie | awk 1 | $preview | head -n 1 | chomp | pen-xc -i)," # copy first result of preview
bindings="$(p "$bindings" | sed 's/.$//')"

opts+=" --bind=$(cmd-nice-posix "$bindings") "

eval "fzf --algo=v2 $opts $CMD"
