#!/bin/bash

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

# Completely optional
name="$1"
ext="$2"
: "${ext:="txt"}"

fp="$(mktemp -t "tf_${name}XXXXXXX.${ext}" 2>/dev/null || :)"

if stdin_exists; then
    cat > "$fp"
fi

echo "$fp"