#!/bin/bash
export TTY

test "$#" -gt 0 && last_arg="${@: -1}"

# If a symlink, then do this. Unfortunately, sponge overwrites symlinks
if test -h "$last_arg"; then
    tf_thing="$(0</dev/null pen-tf sponge || echo /dev/null)"
    cp -aL "$last_arg" "$tf_thing"

    test "$#" -gt 0 && set -- "${@:1:$(($#-1))}" # shift last arg
    set -- "$@" "$tf_thing"

    sponge "$@"
    ret="$?"

    0</dev/null cat "$tf_thing" > "$last_arg"
    trap "rm \"$tf_thing\" 2>/dev/null" 0
    exit "$ret"
else
    sponge "$@"
fi
