#!/bin/bash
export TTY

# Don't actually use this script until this is finished.
# Also, this seems like a big task, so it's very far down the pipeline

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# Run the preprocessor on any opened file
# expand-bash-preprocessor

export BASH_ENV=$HOME/.scriptrc
# bash "$@"
cmd bash <(echo "echo \$0") "$@"

test "$#" -gt 0 && last_arg="${@: -1}"

bash -c ". $lastarg"
# $HOME/.scriptrc
