#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# apply

# exp is a bash expression containing the variable e
# In evaluation the value for e is provided

exp="$1"
shift

for (( i = 1; i <= $#; i++ )); do
    eval e=\${$i}
    eval "$exp" | awk 1
done

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    awk 1 | while IFS=$'\n' read -r e; do
        eval "$exp" | awk 1
    done
fi
