#!/bin/bash
export TTY

IFS= read -r -d '' substitutions <<HEREDOC
s=.*/semiosis/=/root/.emacs.d/host/=;
HEREDOC

normalise_paths() {
    while IFS=$'\n' read -r line; do realpath "$line"; done
}

if command -v yq &>/dev/null; then
    substitutions="$substitutions;$(cat ~/.pen/pen.yaml | yq -r ".volumes[]" | awk 1 | normalise_paths | sed -e 's%\(.*\)%s=\1=/volumes\1=%' -e 's/$/;/')"
    substitutions="$substitutions;$(cat ~/.pen/pen.yaml | yq -r ".volumes[]" | awk 1 | sed -e 's%\(.*\)%s=\1=/volumes\1=%' -e 's/$/;/')"
else
    substitutions="$substitutions;$(cat ~/.pen/volumes.txt | awk 1 | normalise_paths | sed -e 's%\(.*\)%s=\1=/volumes\1=%' -e 's/$/;/')"
    substitutions="$substitutions;$(cat ~/.pen/volumes.txt | awk 1 | sed -e 's%\(.*\)%s=\1=/volumes\1=%' -e 's/$/;/')"
fi

substitutions="$(p "$substitutions" | tr -d '\n' | sed 's/;;/;/g')"

convert_path() {
    sed -e "$substitutions" | sed 's=/volumes/volumes/=/volumes/=g'
}

current_path="$(cat)"
local_path="$(p "$current_path" | convert_path)"

if ! test "$current_path" = "$local_path"; then
    echo "$local_path"
else
    echo "$current_path"
fi

