#!/bin/bash

shopt -s nullglob
shopt -s globstar

glob="$1"
# Change the () into ? which is a wildcard
glob="$(printf -- "%s" "$glob" | tr '[()]' '?')"
echo "$glob" 1>&2

cmd="eval printf -- \"%s\\\\\\n\" $(cmd "$1")"

out="$(eval "$cmd")"

if test -n "$out"; then
    printf -- "%s\n" "$out"
fi

test -n "$out"
