#!/bin/bash
export TTY

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if ! stdin_exists; then
    argstr="$@"
    exec < <(printf -- "%s" "$argstr")
fi

{
    # e:$HOME/blog/posts/thy-kingdom-come.org
    sed 's%< youtube \([^ ]\+\) >%https://www.youtube.com/watch?v=\1%'
} | {
    # Rosie URLs does not cut off the youtube times
    rosie-urls "$@"
    # if test -f ${GOPATH%%:*}/bin/xurls; then
    #     ${GOPATH%%:*}/bin/xurls "$@"
    # else
    #     rosie-urls "$@"
    # fi
} | {
    sed "s/youtu\\.be\\//youtube.com\\/watch\\?v=/" |
    sed "/\\?v=.*\\?t=/s/\\?t/\&t/"
} | {
    sed "/\/\/www.youtube.com/{s~/embed/~/watch?v=~}" |
    sed "/\/\/www.youtube.com/{s=\&ab.*==}" |
    sed "s=^http://www.google.com/url?q\===" | sed "s/&sa=.*//" |
    sed "s=^http.\\?://webcache\\.googleusercontent\\.com/search?q\\=cache:==" |
    sed-pcre "s/(?<!(m\/url|earch|forum|watch|ylist))\?.*//" |
    sed 's/&fbcli.*//' |
    sed "s=\\\n$=="
}
