#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -ssh) {
        SSH_TO_HOST=y
        shift
    }
    ;;

    -ssh-to-host) {
        SSH_TO_HOST="$2"
        shift
        shift
    }
    ;;

    -cwd) {
        CWD="$2"
        shift
        shift
    }
    ;;

    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    -cmd) {
        CMD="$2"
        shift
        shift
    }
    ;;

    -user) {
        PEN_USER="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

if test "$DO_EXEC" = "y"; then
    CMD="$1"
else
    : ${CMD:="$(cmd-nice-posix "$@")"}
fi

: ${CWD:="$(pwd)"}
: ${PEN_USER:="$(whoami)"}

hn="$(hostname)"
hn="$(p "$hn" | sed 's/^pen-//')"

if test "$SSH_TO_HOST" = "y"; then
    ssh \
        -i "~/.pen/host_key" \
        -o ControlMaster=auto \
        -o ControlPath="~/ssh-controlpath-%r@%h:%p" \
        -o UserKnownHostsFile=/dev/null \
        -o StrictHostKeyChecking=no \
        -t $PEN_USER@$hn \
        "bash -l -c $(cmd-nice-posix ". ~/.profile; cd $(cmd-nice-posix "$CWD"); $CMD")"
else
    cd "$CWD"
    eval "$CMD"
fi