#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -h) {
        here=y
        shift
    }
    ;;

    *) break;
esac; done

func_trap() {
    kill "$$"
}
trap func_trap INT

if test "$here" = "y"; then
    echo "loading video..."
    echo "Use \`C-c\` to kill asciinema or \`F1 x\` to kill the window via tmux"
    asciinema play "$@"
else
    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}
    pen-tm -d nw -notrapint -sw "echo loading video...; pen-asciinema-play -h $CMD"
fi
