#!/bin/bash
export TTY

IFS= read -r -d '' substitutions <<HEREDOC
s=.*/semiosis/=/root/.emacs.d/host/=;
HEREDOC

if command -v yq &>/dev/null; then
    substitutions="$substitutions;$(cat ~/.pen/pen.yaml | yq -r ".volumes[]" | awk 1 | sed -e 's%\(.*\)%s=\1=/volumes\1=%' -e 's/$/;/' | tr -d '\n')"
else
    substitutions="$substitutions;$(cat ~/.pen/volumes.txt | awk 1 | sed -e 's%\(.*\)%s=\1=/volumes\1=%' -e 's/$/;/' | tr -d '\n')"
fi

convert_path() {
    sed -e "$substitutions"
}

current_path="$(cat)"
local_path="$(p "$current_path" | convert_path)"

if ! test "$current_path" = "$local_path"; then
    echo "$local_path"
else
    echo "$current_path"
fi

