#!/bin/bash
export TTY

exec 2>/dev/null
{
if test -d "$PROMPTS"; then
    cd "$PROMPTS"
    find . -name '*.prompt' | while read line; do 
        cat "$line" | ( yq . || : ) | ( jq-showschema-keys || : )
    done | uniqnosort
fi
} | pen-pavs