#!/bin/bash
export TTY

slug="$(printf -- "%s\n" "$@" | tr '\n' ' ' | sed 's/ $//' | slugify | cut -c -20)"

if test "$TERM" = "dumb"; then
    "$@"
else
    unset TMUx
    tmux attach -t "tmwr-$slug" || tmux new -s "tmwr-$slug" "$@"
fi
