#!/bin/bash
export TTY

PEN_TIMEOUT="$1"
shift

: "${PEN_NO_TIMEOUT:="$(0</dev/null pen-rc-get no-timeout)"}"
: "${PEN_TIMEOUT:="$(0</dev/null pen-rc-get timeout)"}"

if test "$PEN_NO_TIMEOUT" = "y"; then
    "$@"
else
    timeout "$PEN_TIMEOUT" "$@"
    ret="$?"
    case "$ret" in
        124) {
            0</dev/null cmd1 "$@" >> ~/.pen/timeouts.txt
        }
        ;;

        *)
    esac
    exit "$ret"
fi