#!/bin/bash

# play-bottle-pop &

y_chars="Yy"
n_chars="Nn"
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -N|-carefully) {
        allowed_re="^[YN]$"
        shift
    }
    ;;

    -y|-y-chars) {
        y_chars="$2"
        shift
        shift
    }
    ;;

    -n|-n-chars) {
        n_chars="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

allowed_re="^[${y_chars}/${n_chars}]$"

message="$@"

: ${message:="Are you sure?"}

exec 1>&2

echo
message="$(printf -- "%s" "$message" | his -f lgreen '.*')"
echo -e " $message"
echo

allowed_re="$(printf -- "%s" "$allowed_re")"
allowed_re_color="$(printf -- "%s" "$allowed_re" | his -r -f dred '.*')"

if test "$YN_DEFAULT" = "y"; then
    echo y
    exit 0
fi

if test "$YN_DEFAULT" = "n"; then
    echo n
    exit 1
fi

while :; do
    read -p " $allowed_re_color: " -n 1 -r
    echo
    [[ $REPLY =~ $allowed_re ]] && break
done
echo

[[ $REPLY =~ ^[$y_chars]$ ]]
