#!/bin/bash

# z-repl "raco pkg install "

# use "x"

sn="$(basename "$0")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    -0) {
        start=y
        shift
    }
    ;;

    -cm) {
        cm=y
        shift
    }
    ;;

    -cme) {
        cm=y
        post_exit=y
        shift
    }
    ;;

    -nocl) {
        nocl=y
        shift
    }
    ;;

    -cd) {
        CWD="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

case "$sn" in
    zre) {
        CMD="$1"
    }
    ;;

    zrs) {
        CMD="$1 "
    }
    ;;

    *) {
        : ${CMD:="$(cmd-nice-posix "$@")"}
    }
    ;;
esac

# cmd="$@"

tf_command="$(pen-ux tf command)"
trap "rm \"$tf_command\" 2>/dev/null" 0

printf -- "%s" "$CMD " >> "$tf_command"

if test "$post_exit" = "y"; then
    printf -- "%s" "; exit \"\$?\" " >> "$tf_command"
fi

: "${CWD:="$(pwd)"}"

# For some reason the sleep is required for
# cr /root/.pen/documents/haskell-test/app/Main.hs

if test "$start" = "y"; then
    CWD="$CWD" pen-x -c l -e "»" -s ' ' -sf "$tf_command" -c a -i
elif test "$cm" = "y"; then
    if test "$nocl" = "y"; then
        CWD="$CWD" pen-x -e "»" -sf "$tf_command" -sl 0.5 -c m -i
    else
        CWD="$CWD" pen-x -c l -e "»" -sf "$tf_command" -sl 0.5 -c m -i
    fi
else
    if test "$nocl" = "y"; then
        CWD="$CWD" pen-x -e "»" -sf "$tf_command" -sl 0.5 -i
    else
        CWD="$CWD" pen-x -c l -e "»" -sf "$tf_command" -sl 0.5 -i
    fi
fi
