#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# apply

. $SCRIPTS/lib/stdin_exists
stdin_exists
hasstdin="$?"

# . $PENEL_DIR/scripts/utils.sh

if test "$hasstdin" = 0; then
    IFS='' read -d '' -r input
fi

f="$1"
shift

for (( i = 1; i <= $#; i++ )); do
    eval ARG=\${$i}

    # # obscure case, but here is an example
    # echo hi | pen-apply -1 v -num -nc
    if test "$hasstdin" = 0; then
        printf -- "%s" "$input" | "$f" "$ARG"
    else
        ARG="$(cmd "$ARG")"
        eval "$f $ARG"
    fi
done
