#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# pip install --upgrade --force-reinstall "$@"
# pip3 install --upgrade --force-reinstall "$@"
# pip3.8 install --upgrade --force-reinstall "$@"
pipx install "$@"
