#!/bin/bash

# This operates on single quotes, not double

# cmd - print the arguments given to this script

# https://mullikine.github.io/posts/missing-posix-shell-functions-cmd-and-myeval/

# POSIX-compliant
p () {
    {
        i=1
        while [ "$i" -lt "$#" ]; do
            eval ARG=\${$i}
            printf -- "%s " "$ARG"
            i=$((i + 1))
        done
        eval ARG=\${$i}
        printf -- "%s" "$ARG"
    } | sed 's/\\n/\n/g'
}

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists; then
    # bashism
    IFS= read -rd '' in < <(cat);typeset -p in &>/dev/null

    set -- "$in" "$@"
fi

cmd() {
    for var in "$@"
    do
        printf "%s " "$(printf %s "$var" | sed "s/'/'\\\\''/g")";
    done | sed 's/ $//'
}

cmd "$@"
