#!/bin/bash
export TTY

stdin_exists() {
    ! [ -t 0 ]
}

# Sometimes, we need to also encode ASCII characters
# see e:youtube-get-subtitles
# https://www.w3schools.com/tags/ref_urlencode.ASP
urlencode_dash() {
    sed 's=-=%2D=g'
}

# alt -q urlencode &>/dev/null || agi gridsite-clients &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -z) {
        nolines=y
        shift
    }
    ;;

    *) break;
esac; done

if stdin_exists; then
    if test "$nolines" = "y"; then
        /usr/bin/urlencode "$(cat)"
    else
        awk 1 | while IFS=$'\n' read -r line; do
            /usr/bin/urlencode "$line"
        done
    fi
else
    /usr/bin/urlencode "$@"
fi

# python:
# import urllib
# urllib.parse.quote("yo hodsfkl")