#!/bin/bash
export TTY

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

pager() {
    if is_tty; then
        xc -i -
    else
        cat
    fi
}

vc_opt="$1"
shift
case "$vc_opt" in
    online) {
        # Bash
        : >/dev/tcp/8.8.8.8/53
    }
    ;;

    *)
esac
