#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename "$0")"

case "$sn" in
    pen-ssh-host) {
        bin=zsh
    }
    ;;

    *) {
        bin="$sn"
    }
    ;;
esac

pen-ssh-host "$bin" "$@"
