#!/bin/bash
export TTY

time="$1"
shift

: "${PEN_NO_TIMEOUT:="$(pen-rc-get no-timeout)"}"

if test "$PEN_NO_TIMEOUT" = "y"; then
    "$@"
else
    timeout "$time" "$@"
    ret="$?"
    case "$ret" in
        124) {
            cmd1 "$@" >> ~/.pen/timeouts.txt
        }
        ;;

        *)
    esac
    exit "$ret"
fi