#!/bin/bash
export TTY

# $MYGIT/charmbracelet/glow/glow "$@"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nc) {
        nocolor=y
        shift
    }
    ;;

    -f) {
        force_color=y
        shift
    }
    ;;

    -d) {
        mode=default
        shift
    }
    ;;

    *) break;
esac; done

. $SCRIPTS/lib/stdin_exists
stdin_exists
hasstdin="$?"

if test "$hasstdin" = 0; then
    input_fp="$(cat | tf md)"
    set -- "$@" "$input_fp"
    exec <&2
    # exec <`tm-tty` `# see etty` 
    # echo hi
    # pak
    # exit
fi

clean_output() {
    s remove-leading-and-trailing-newlines
}

fix_ansi() {
    if test "$nocolor" = "y"; then
        unbuffer "$@" | strip-ansi | clean_output | pavs
    elif test "$force_color" = "y"; then
        unbuffer "$@" | clean_output | less -rS
    else
        unbuffer "$@" | strip-ansi | clean_output | pavs
    fi
}

test -f "$HOME/repos/glow/glow" && : "${bin:="$HOME/repos/glow/glow"}"
test -f "${GOPATH%%:*}/bin/glow" && : "${bin:="${GOPATH%%:*}/bin/glow"}"

glowbin() {
    fix_ansi "$bin" "$@"
}

if test "$hasstdin" = 1 && test "$#" = 0; then
    mode=default
fi

case "$mode" in
    default) {
        "$bin" "$@"
        exit "$?"
    }
    ;;

    *)
esac

glowbin "$@"
