#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# "%f:%l:%c: %m"

# TODO Prompt an entire file
# TODO Create this capability

# pen-ci -f -a penf -u -nj --pool correct-english-spelling-and-grammar-1
# pen-ci -f -a penf -u -nj --pool pf-correct-the-syntax/2 code

pen-tvipe
