#!/bin/bash
export TTY

# hdc actually asks for less directly, which is annoyying
# So I need to make PATH state which points to a different less

# export PAGER=sps-v-keep
export EDITOR=sps-v-keep
# export EDITOR=nw-v-keep

if ! inside-docker-p; then
    pen sh hdc "$@"
    exit "$?"
fi

if ! inside-tmux-p; then
    in-tm hdc "$@"
    exit "$?"
fi

thing="$@"

if ! test -f /tmp/hdc-less/less; then
    mkdir -p /tmp/hdc-less/
    ln -sf `which hdc-less` /tmp/hdc-less/less
fi

export PATH="/tmp/hdc-less/:$PATH"

if test -n "$thing"; then
    pen-x -allowtm -sh /root/.cabal/bin/hdc -e ">" -s "$thing" -c m -i
else
    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}

    eval "/root/.cabal/bin/hdc $CMD"
fi
