#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

op=filter
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -f) {
        op=filter
        shift
    }
    ;;

    -1) {
        op=1ary
        shift
    }
    ;;

    -be) {
        op=bash_expression
        shift
    }
    ;;

    *) break;
esac; done

case "$op" in
    filter) {
        pen-apply-f "$@"
    }
    ;;

    1ary) {
        pen-apply-1 "$@"
    }
    ;;

    bash_expression) {
        # example
        # echo "hello\nthere" | map -be 'echo "[$(cmd-nice-posix "$e")]"' | s join .

        pen-apply-be "$@"
    }
    ;;

    *)
esac
