#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -s) {
        WHITESPACE=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$WHITESPACE" = "y"; then
    sed -e "s/\(.\)/\1\\\s*/g" -e "s/...$//"
else
    sed -e "s/\(.\)/\1.*/g" -e "s/..$//"
fi