#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null
sn="$(basename -- "$0")"

if ! in-pen-p; then
    in-pen "$sn"
else
    test -d /root/.pen/emacs-tcp-server-ports || exit 1

    sn="$(printf -- "%s" "$sn" | sed 's=-tcp$==')"

    for worker in /root/.pen/emacs-tcp-server-ports/*; do
        bn="$(basename -- "$worker")"
        pen-e -D "$bn" -e-tcp "($sn)"
    done
fi
