#!/usr/bin/python3

from aixapi import AIxResource
import os


class AIXInterface:
    __resource = None

    def __init__(self, resource):
        """
        Initializes an instance of AIXInterface.
        Initialize the class and then call one of the functions.
        :param resource: an instance of AIxResource
        """
        assert type(resource) == AIxResource
        self.__resource = resource

    def prompt_completion(self):
        """
        Sends a simple push notification.
        :return: the result of the call to push
        """
        response = self.__resource.compose("Hello!")
        return response


if __name__ == "__main__":
    # Get your API Key at apps.aixsolutionsgroup.com
    api_key = os.environ.get["AIX_API_KEY"]
    aix_resource = AIxResource(api_key)

    example_instance = AIXInterface(aix_resource)

    prompt_completion = example_instance.prompt_completion()
    gpt_response = str(prompt_completion.get("data", dict()).get("text"))

    print("-" * 250)

    print(gpt_response)
<