#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# Also see:
# e:/root/.emacs.d/host/pen.el/scripts/nohup

# This is a nohup script which is good for fzf preview - it reconnects to the
# command, and if the command finishes, collects the output

trap '' HUP

"$@"
