#!/bin/bash
export TTY

# Simply export stdin as the overlay, for another command

IFS= read -rd '' PEN_OVERLAY < <(cat);typeset -p PEN_OVERLAY &>/dev/null
export PEN_OVERLAY

"$@"


#          *     ,MMM8&&&.            *
#               MMMM88&&&&&    .
#              MMMM88&&&&&&&
#  *           MMM88&&&&&&&&
#              MMM88&&&&&&&&
#              'MMM88&&&&&&'
#                'MMM8&&&'      *
#       |\___/|
#       )     (             .              '
#      =\     /=
#        )===(       *
#       /     \
#       |     |
#      /       \
#      \       /
# _/\_/\_/\__  _/_/\_/\_/\_/\_/\_/\_/\_/\_/\_
# |  |  |  |( (  |  |  |  |  |  |  |  |  |  |
# |  |  |  | ) ) |  |  |  |  |  |  |  |  |  |
# |  |  |  |(_(  |  |  |  |  |  |  |  |  |  |
# |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
# |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
