#!/bin/bash
export TTY

EMACSD=/root/.emacs.d

for d in \
$EMACSD/host/pen.el \
$EMACSD/host/pen-contrib.el \
/root/.emacs.d/elpa-light \
/root/.emacs.d/elpa-full \
$EMACSD/host/openai-api.el; do

    find "$d" -type f -name '*.el'
done | pen-mnm | pavs