#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

test "$#" -gt 0 && last_arg="${@: -1}"

if stdin_exists && ! test -f "$last_arg"; then
    fzf "$@"

elif test -f "$last_arg"; then
    test "$#" -gt 0 && set -- "${@:1:$(($#-1))}" # shift last arg

    cat1 "$last_arg" | fzf "$@"
fi