#!/bin/bash

# pen-nsfa - new script from args

# This will return the path to a new script in
# the =tmp= directory which when executed will
# execute =echo hi=.
#
# =pen-nsfa= is used by =comint-quick=, which
# will is used to create =comint= modes for, for example, =nlsh=.
#
# See =nlsh-os=.

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    -resize|-rs) {
        resize=y
        shift
    }
    ;;

    *) break;
esac; done

: ${CWD:="$(pwd)"}

if test "$DO_EXEC" = "y"; then
    CMD="$1"
else
    CMD="$(cmd "$@")"
fi

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    STDIN_EXISTS=y
    input_fp="$(cat | tf txt)"
fi

slug="$(echo "$CMD--$CWD" | tr -d '\n' | slugify | cut -c -40)"

tf_new_script="/tmp/nsfa-$slug.sh"
rm -f "$tf_new_script"

# stty stop and undef are used to prevent C-s from hanging the program.
IFS= read -r -d '' scriptcode <<HEREDOC
#!/bin/bash
$(test -n "$PEN_NO_TM" && printf -- "%s\n" "export PEN_NO_TM=\"$PEN_NO_TM\"")
$(test -n "$PEN_USE_GUI" && printf -- "%s\n" "export PEN_USE_GUI=\"$PEN_USE_GUI\"")
$(test -n "$TMUX" && printf -- "%s\n" "export TMUX=\"$TMUX\"")
stty stop undef 2>/dev/null; stty start undef 2>/dev/null;
HEREDOC

printf -- "%s\n" "$scriptcode" >> "$tf_new_script"
export PATH=$HOME/scripts:$HOME/scripts/container:$PATH

if test "$STDIN_EXISTS" = "y"; then
    echo "exec < <(cat \"$input_fp\")" | awk 1  >> "$tf_new_script"
fi

if test "$resize" = "y"; then
    printf -- "%s\n" 'eval `resize`'  >> "$tf_new_script"
fi

CWD="$(printf -- "%s" "$CWD" | sed "s=^~=$HOME=")"
if test -n "$CWD" && test -d "$CWD"; then
    printf -- "%s\n" "export CWD=$(cmd-nice "$CWD")" | awk 1 >> "$tf_new_script"
    cmd cd "$CWD" | awk 1 >> "$tf_new_script"
fi

IFS= read -r -d '' termtest <<'HEREDOC'
if printf -- "%s\n" "$TERM" | grep -q -P 'eterm'; then
    export TERM=screen-256color
fi
HEREDOC

printf -- "%s\n" "$termtest" | awk 1 >> "$tf_new_script"
printf -- "%s\n" "$CMD \"\$@\"" >> "$tf_new_script"
chmod a+x "$tf_new_script"
echo -n "$tf_new_script"
