#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

sn="$(basename "$0")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -sn) {
        sn="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

pen-e-ic -sn "$sn" -Eargs "$@"