#!/bin/sh

# Can probably take back out the semicolon
# -e "s/<pen-semicolon>/;/g" \
# Can't encode dashes because it breaks slugs
# -e "s/<pen-dash>/-/g" \

# cat
sed -e "s/<pen-notnewline>/\\\\n/g" \
    -e "s/<pen-dollar>/\$/g" \
    -e "s/<pen-backtick>/\`/g" \
    -e "s/<pen-bang>/!/g" \
    -e "s/<pen-doublequote>/\"/g" \
    -e "s/<pen-colon>/:/g" \
    -e "s/<pen-empty>//g" \
    -e "s/<pen-singlequote>/'/g" \
    -e "s/<pen-dnl>/\\n\\n/g" \
    -e "s/<pen-newline>/\\n/g" \
    -e "s/<pen-nl>/\\n/g" \
    -e "s/<pen-backslash>/\\\\/g"