#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# env | xt -d v

sn="$(basename "$0")"
cmd-onelineify-safe "$sn" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null | awk 1 >> "/tmp/$sn.txt"

term_env_arr=()

if pen-rc-test truecolor; then
    term_env_arr=(env COLORTERM=truecolor TERM="xterm-24bit" EMACS_TERM_TYPE="xterm-24bit")
fi

"${term_env_arr[@]}" /usr/local/bin/emacsclient "$@"
