#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -n) {
        LINES="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

eval `pen-tm-resize`

pen-umn | awk 1 | while IFS=$'\n' read -r line; do
    if [ -f "$line" ]; then
        if test -n "$LINES"; then
            pen-scope.sh "$line" | head -n $LINES
        else
            cat "$line"
        fi
    elif [ -d "$line" ]; then
        pen-dirinfo "$line" | xsv table
    else
        echo "$line"
    fi
done
