#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

key="$1"
key="$(p "$key" | sed 's/^\.//')"
jkey=".$key"

# value="$2"

if pen-rc-test "$key"; then
    pen-rc-set "$key" off
else
    pen-rc-set "$key" on
fi
ret="$?"

pen-rc-get "$key" | hls blue 1>&2

exit "$ret"

# test -n "$key" && test "$(pen-rc "$key")" = true
