#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# This is a nohup script which is good for fzf preview - it reconnects to the
# command, and if the command finishes, collects the output

trap '' HUP

"$@"
