#!/bin/bash

shopt -s nullglob
# ugh... using sentinels is a pain. Just select one.
# Just take the first one
# SOCKET="$(basename "$(shopt -s nullglob; cd $HOME/.pen/pool/available; ls pen-emacsd-* | shuf -n 1)")"

# Wait until free clients

# TODO Use e:with-exponential-backoff

while test -z "$SOCKET"; do
    # ls ~/.pen/pool/available/pen-emacsd-* | pen-tv &>/dev/null

    for socket_fp in ~/.pen/pool/available/pen-emacsd-*; do
        SOCKET="$(basename "$socket_fp")"
        echo "$SOCKET" >> /tmp/d.txt
        break
    done
    if test -n "$SOCKET"; then
        break
    fi
    echo
    echo "$(date-ts-hr)"
    ns "Waiting for socket..." 1>&2
    echo "Waiting for socket..." 1>&2
    sleep 1
done

test -z "$SOCKET" && exit 1
test "$SOCKET" = DEFAULT && exit 1
rm -f ~/.pen/pool/available/$SOCKET

: "${SOCKET:="DEFAULT"}"

export SOCKET
echo "pool selected $SOCKET" | hls red 1>&2

# Do stuff
"$@"

touch ~/.pen/pool/available/$SOCKET
