#!/bin/bash
export TTY

is_tty() {
    # If stout is a tty
    [ -t 1 ] && ! test "$TERM" = "dumb"
}

echo "$TERM" | tv &>/dev/null

: "${EDITOR:="vim"}"
export EDITOR

pager() {
    if is_tty; then
        vim -
    else
        cat
    fi
}

pager "$@"
