#!/bin/bash
export TTY

# Because, otherwise, I may get this issue:
# Boostrapping emacs worker test... /usr/local/bin/emacsclient: Invalid permissions on parent directory of socket: /root/.pen/tmp/emacs0/test
export TMPDIR=/tmp

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# env | xt -d v

sn="$(basename "$0")"
cmd-onelineify-safe "$sn" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null | awk 1 >> "/tmp/$sn.txt"

term_env_arr=()

if pen-rc-test truecolor; then
    term_env_arr=(env COLORTERM=truecolor TERM="xterm-24bit" EMACS_TERM_TYPE="xterm-24bit")
fi

# cmd "${term_env_arr[@]}" /usr/local/bin/emacsclient "$@" | tv &>/dev/null
# cmd "${term_env_arr[@]}" /usr/local/bin/emacsclient "$@" 1>&2

"${term_env_arr[@]}" /usr/local/bin/emacsclient "$@"
