#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -fp) {
        yaml_file="$2"
        shift
        shift
    }
    ;;

    -runtime) {
        yaml_file="/tmp/pen.yaml"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${yaml_file:="~/.pen/pen.yaml"}"

# pen-rc-set n-daemons 10

key="$1"
test -n "$key" || exit 1
shift

value="$1"
test -n "$value" || exit 1
shift

# ns "$value"

key="$(printf -- "%s" "$key" | qne)"

if printf -- "%s\n" "$value" | grep -q -P '[ "$#]'; then
    value="$(p "$value" | q)"
else
    value="$(printf -- "%s" "$value" | qne)"
fi

sed -i "/^$key: \([^ ]\+\)/{s/^\($key: \)\(.*\)$/\1$value/}" "$yaml_file"
