#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

(
penelfonts -f smbraille.tlf Genesis 32:30 | lolcat -f | sed 's/^/         /'
echo
ocif Genesis 32:30 | sed '1,2d' | lolcat -f | sed 's/^/     /'
echo
) | less -rS
