#!/bin/bash
export TTY

test -f "/root/.pen/efm-langserver-config.yaml" && : "${efm_config:="/root/.pen/efm-langserver-config.yaml"}"
test -f "/root/.emacs.d/host/pen.el/config/efm-langserver-config.yaml" && : "${efm_config:="/root/.emacs.d/host/pen.el/config/efm-langserver-config.yaml"}"
test -f "/root/.emacs.d/pen.el/config/efm-langserver-config.yaml" && : "${efm_config:="/root/.emacs.d/pen.el/config/efm-langserver-config.yaml"}"

ln -sf "$efm_config" $HOME/.config/efm-langserver/config.yaml

unbuffer pen-e sa &>/dev/null &>/dev/null &

efm-langserver "$@"