#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

alt -q ag &>/dev/null || agi silversearcher-ag &>/dev/null

exec 2>/dev/null
/usr/bin/ag -f "$@"
