#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

test "$#" -gt 0 && last_arg="${@: -1}"

if test "$#" -gt 0 && ! stdin_exists && test -f "$last_arg"; then

    test "$#" -gt 0 && set -- "${@:1:$(($#-1))}" # shift last arg
    # exec < "$last_arg"
    exec < <(cat "$last_arg")
fi

CMD="$(cmd "$@")"
: ${CMD:="-r $(cmd ".")"}

# * Annoyingly this seems to not deal well with free values
# json2yaml
# Converting 'mullikine' to yaml would result in 'mullikine', I think.

# pen-str chomp | pen-rtcmd ++yq -E "yq $CMD | json2yaml | vs"
chomp | pen-rtcmd ++yqy -E "yqy $CMD | vs"
