#!/bin/bash

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# https://www.visidata.org/install/

# Run a command like M-x
# https://www.visidata.org/docs/plugins/
# Use "space" - it's like spacemacs.

# Delete a column
# https://github.com/saulpw/visidata/issues/1366
# As you noted you can use - (hyphen) to hide the column. This is good enough
# for most of my use cases, but to actually delete the column you'll need to
# open the columns sheet SHIFT+C and press delete (d) on the column you want to
# remove +1

# I should be able to cat into vd
# There should be no errors. vd might already be ok.

# It still doesn't treat piped input particularly well I should extend
# vd

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nh) {
        shift
        set -- --header=0 "$@"
    }
    ;;

    -csv) {
        iscsv=y
        shift
    }
    ;;

    *) break;
esac; done

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -2) {
        # precmd="TERM=xterm-2color "
        precmd="export TERM=screen-2color; "
        # precmd="TERM=vt100 "
        shift
    }
    ;;

    *) break;
esac; done

eval `resize`

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists; then
    if test "$iscsv" = "y"; then
        infp="$(tf csv)"
    else
        infp="$(tf tsv)"
    fi

    set -- "$infp" "$@"
    exec <&2
fi

if is_tty; then
    visidata "$@"
else
    cat
fi
