#!/bin/bash
export TTY

sn="$(basename "$0")"

case "$sn" in
    *do-index-full) {
        reindex_full=y
    }
    ;;

    *)
esac

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -g) {
        dogit=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$reindex_full" = "y"; then
    :
else
    set -- -f "$@"

    # man glimpseindex
    # -f     incremental  indexing.   glimpseindex scans all files and adds
    #              to the index only those files that were  created  or  modified
    #              after the current index was built.
fi

# cd $HOME/OneDrive
# find `pwd` -type f | files2text-mirror

# upd do-index-full

{
    cat $NOTES/files.txt | umn | files-only.sh | awk 1
} | files2text-mirror

(
cd "$MIRRORD$MYGIT"; find . -type d -name 'vendor' -exec rm -rf {} \;
)
CMD="$(cmd-nice "$@")"
: ${CMD:="$(cmd-nice "$@")"}


# This would include $MYGIT and other large directories. Therefore, it's
# not possible
# eval "glimpseindex $CMD -o $NOTES $MIRRORD $(cat $NOTES/directories.org | umn | dirs-only.sh | s join ' ')"

eval "glimpseindex $CMD -o $NOTES $MIRRORD"
