#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$DO_EXEC" = "y"; then
    CMD="$1"
    export GY_CMD="$CMD"
    eval "$CMD"
else
    CMD="$(cmd-nice "$@")"
    export GY_CMD="$CMD"
    "$@"
fi
