#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    IFS= read -rd '' input < <(cat /dev/stdin)
else
    input="$1"
fi

num="$(LC_CTYPE=C printf -- '%d' "'$input")"

printf -- "%s" "$num"
