#!/bin/bash
export TTY

# https:/articles/copilot/

# Make it so all sites without a file extension or fragment identifier on the end should have /
# Don't change this.
# http://www.learndatalogtoday.org/chapter/0
# Require more than one [^.#?/][^.#?/]\+

manual_redirect() {
    sed -e '/\/\/[^\/]*.[^\/]*\/\(.*\/\)*[^.#?/][^.#?/]\+\(#.*\|$\)/{s=\(#.*\|$\)=/\1=;}' \
        -e '/https:\/\/l.facebook.com\/l.php?u=/{s~https://l.facebook.com/l.php?u=~~;}' \
        -e '/\/\/jessmart.in\/.*[^/]$/{s=$=/=;}'  \
        -e '/https:\/\/www.unisonweb.org\/.*[^/]$/{s=$=/=;}' \
        -e '/\/web.archive.org\/web.*http.*github.com\//{s=.*web.archive.org/web/[^/]*/==;}' \
        -e '/\/deepai.org/s/\/$//' \
        -e '/\/[^.]*.guildofarchivists.org\/.*\/$/{s=\/$==;}'  \
        -e '/\/www.bschaatsbergen.com/s/\/$//' \
        -e '/\/arxiv.org/s/\/$//' \
        -e '/\/wiki.haskell.org/s/\/$//' \
        -e '/\/en.wikibooks.org/s/\/$//' \
        -e '/\/news.ycombinator.com\/news/s/\/$//' \
        -e '/\/programming-idioms.org/s/\/$//' \
        -e '/artandpopularculture.com/s/\/$//' \
        -e '/\/www.schoolofhaskell.com/s/\/$//' \
        -e '/\/www.metalevel.at/s/\/$//' \
        -e '/\/www.metalevel.at/s/\/#/#/' \
        -e '/\/.*\.github.io/s/\/$//' \
        -e '/\/.*\.github.io/s/\/#.*//' \
        -e '/wikipedia.org/s/\/$//' \
        -e '/cppreference.com/s/\/$//' \
        -e '/wikipedia.org/s/\/#.*//' \
        -e '/http:\/\/google/s/http:/https:/' \
        -e '/https\?:\/\/www\.google\.com\/url?q=/s/https\?:\/\/www\.google\.com\/url?q=\(.*\)&sa=.*/\1/' \
        -e '/.*clojure.org/s/\/$//' \
        -e '/.*clojuredocs.org/s/\/$//' \
        -e '/jsvine.github.io/s=jsvine.github.io/basics/=jsvine.github.io/intro-to-visidata/basics/=' \
        -e '/jsvine.github.io/s=jsvine.github.io/advanced/=jsvine.github.io/intro-to-visidata/advanced/=' \
        -e '/jsvine.github.io/s=jsvine.github.io/intermediate/=jsvine.github.io/intro-to-visidata/intermediate/=' \
        -e '/.*haskell.org/s/\/$//' \
        -e '/.*dwarffortresswiki.org/s/\/$//' \
        -e '/.*haskell.org/s/\/#.*//'

        # sed '/.*fandom.com/s/\/$//'
        # sed '/.*jsvine.github.io.*[^/]$/s/$/\//' | \
}

# newline
IFS="
"
manual_redirect | awk1 | while IFS="$IFS" read -r line; do
    (
    exec 0</dev/null

    if is-200 "$line"; then
        echo "$line"
    else
        if printf -- "%s\n" "$line" | grep -q -P '/$'; then
            # Remove trailing slash
            new_line="$(printf -- "%s" "$line" | sed 's/\/$//')"
        elif printf -- "%s\n" "$line" | grep -q -P '/$'; then
            # Add trailing slash
            new_line="$(printf -- "%s" "$line" | sed 's=$=/=')"
        fi
        if is-200 "$new_line"; then
            echo "$new_line"
        else
            echo "$line"
        fi
    fi

    )
done

# I tried curl-get-redirect for google searches but google doesn't provide the information

# https://web.archive.org/web/20161230180206/
# https://web.archive.org/web/20161230180206/https://github.com/unisonweb/unison/blob/master/unison-src/searchengine.u
