#!/bin/bash
export TTY

stdin_exists() {
    ! [ -t 0 ]
}

if stdin_exists; then
    fp="$(pen-tf txt)"
else
    echo "requires stdin" 1>&2
    exit 1
fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -[a-z0-9]*) {
        varname="$(p "$opt" | pen-mcut -d- -f2)"
        contents="$2"
        shift
        shift
        varname="$(p "$varname" | sed 's/\s\+//g')"                                        # no spaces
        varname="$(p "$varname" | sed -e 's/\(.*\)/\L\1/')"                                # lowercase
        varname="$(p "$varname" | pen-fuzzify-regex -s)"                                       # let params match fields with spaces

        cat "$fp" | ptw replace-substring -i -m "<$varname>" -r "$contents" | sponge "$fp" # perform variable replacement
        cat "$fp" | sed 's/\(\b1 [a-zA-Z]\+\)s\b/\1/g' | pen-sponge "$fp"                      # fix singular plural
        cat "$fp" | sed 's/""/"/g' | pen-sponge "$fp"                                          # fix CSV double quote
    }
    ;;

    *) break;
esac; done

cat "$fp"
