#!/bin/bash
export TTY

# since this may be called from the system, from tabnine,
# redirect to firefox

url="$1"

runexit() {
    "$@" &>/dev/null &
    disown
    exit 0
}

case "$url" in
    *app.tabnine.com*) {
        runexit unbuffer firefox "$@"
    }
    ;;

    *.csv) {
        runexit download-file "$@"
    }
    ;;

    *)
esac

# Not handled
exit 1
