#!/bin/bash
export TTY

tf_pipe_buffer="$(0</dev/null pen-tf pipe_buffer txt || echo /dev/null)"

cat > "$tf_pipe_buffer"

exec 3>&1

: ${TTY:="$(pen-tm-tty)"}

exec 0<"$TTY"
exec 1>"$TTY"

# Consider running a different pen instance if available
# emacs -nw -Q "$tf_pipe_buffer"
export PEN_NO_TM=y
pen -notm -nw "$tf_pipe_buffer"

exec 1>&3

cat "$tf_pipe_buffer"

trap "rm $(cmd "$tf_pipe_buffer") 2>/dev/null" 0
