#!/bin/bash
export TTY

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    fp="$(tf txt)"
    exec <&2
    set -- "$@" "$fp"
elif test "$#" -eq 0; then
    v "$@"
    exit "$?"
fi

test "$#" -gt 0 && last_arg="${@: -1}"

if test -f "$1"; then
    fp="$1"
    shift
elif test -f "$last_arg"; then
    fp="$last_arg"
    test "$#" -gt 0 && set -- "${@:1:$(($#-1))}" # shift last arg
fi

if test -f "$fp"; then
    rp="$(realpath "$fp")"
    dn="$(dirname "$rp")"
    bn="$(basename -- "$rp")"

    cp -a "$fp" "$dn/keep_$bn"
    v "$@" "$dn/keep_$bn"
else
    v "$@"
fi
