#!/bin/bash
export TTY

# pipe into this

. $SCRIPTS/lib/stdin_exists

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -f) {
        fp="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

{
if test -f "$fp"; then
    # cmd sha256sum "$fp" 1>&2
    sha256sum "$fp" | str field 1
elif stdin_exists; then
    sha256sum | str field 1
else
    echo -n "$@" | sha256sum | str field 1
fi
} | cut -c1-10
