#!/bin/bash
export TTY
cd "$PENEL_DIR"
{
pwd

echo scripts/
scripts_loc="$(find scripts -type f | while read -r line; do cat "$line" | awk 1; done | wc -l)"
echo
echo src/
src_loc="$(find src -type f | while read -r line; do cat "$line" | awk 1; done | wc -l)"
echo
echo khala/
cd "$MYGIT/semiosis/khala"
khala_loc="$(find src -type f | while read -r line; do cat "$line" | awk 1; done | wc -l)"
echo
echo pensieve/
cd "$MYGIT/semiosis/pensieve"
pensieve_loc="$(find src -type f | while read -r line; do cat "$line" | awk 1; done | wc -l)"
} | pen-pavs
