#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -e) {
        USE_EMACS=y
        shift
    }
    ;;

    -cl) {
        VIPE_CLEAR=y
        shift
    }
    ;;

    -wintype) {
        WINTYPE="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done
: "${WINTYPE:="sps"}"

export VIPE_CLEAR

vipe_cmd="$1"
# eipe
: "${vipe_cmd:="vipe"}"
if test "$USE_EMACS" = "y"; then
    export WINTYPE
    pen-teipe "$@"
else
    pen-tm vipe -wintype "$WINTYPE" "$@"
fi
