#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# env | xt -d v

# sn="$(basename "$0")"
# cmd-onelineify-safe "$sn" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null | awk 1 >> "/tmp/$sn.txt"

# export COLORTERM=truecolor
# export TERM="xterm-24bit"
# export EMACS_TERM_TYPE="$TERM"

echo "$COLORTERM $TERM" | tv

/usr/local/bin/emacsclient "$@"
