#!/bin/bash

input_fp="$(pen-tf txt)"

interp="$1"
shift

name="$1"
shift

test "$interp" = nil && interp=sh
test "$interp" = "c++" && interp=cpp
test "$interp" = rosie && interp=rpl
test "$interp" = elasticsearch && interp=es
test "$interp" = cucumber && interp=feature
test "$interp" = gherkin && interp=feature

postprocess() {
    sed 's/^\(\s*\)#+/,\1#+/' | sed 's/^/  /' | awk 1
}

if test -n "$name"; then
    echo "#+NAME: $name"
fi

case "$interp" in
    brain-description) {
        echo "#+BEGIN_SRC text -n :async :results verbatim code"
        cat "$input_fp" | postprocess
        echo -n "#+END_SRC"
    }
    ;;

    *) {
        echo "#+BEGIN_SRC $interp -n :async :results verbatim code"
        cat "$input_fp" | postprocess
        echo -n "#+END_SRC"
    }
    ;;
esac
