#!/bin/bash

: "${OPENAI_API_KEY:="$PEN_LM_KEY"}"

if test -s $HOME/.pen/openai_api_key; then
    : "${OPENAI_API_KEY:="$(cat $HOME/.pen/openai_api_key)"}"
fi

test -n "$OPENAI_API_KEY" || {
    echo "OPENAI_API_KEY not given to script"
    exit 1
}

export OPENAI_API_KEY

openai() {
    python3 `which openai` "$@"
}

# This only really uses the env vars
if test "$LM_COMPLETE_DEBUG" = "y"; then
    pen-openai-complete "$@"
else
    pen-openai-complete "$@" | pen-log openai-temp
fi

# openai "$@" | pen-log openai-temp