#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

sn="$(basename "$0")"

case "$sn" in
    pen-ssh-host) {
        bin=zsh
    }
    ;;

    *) {
        bin="$sn"
    }
    ;;
esac

pen-ssh-host "$bin" "$@"
