#!/bin/bash
export TTY

sn="$(basename -- "$0")"
sn="$(p "$sn" | sed 's/^pen-//')"
( hs "$(basename "$sn")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -noz) {
        nozrepl=y
        shift
    }
    ;;

    -nof) {
        nofzf=y
        shift
    }
    ;;

    -onestatement) {
        onestatement=y
        shift
    }
    ;;

    -sexp) {
        onestatement=y
        sexp_output=y
        shift
    }
    ;;

    -fp) {
        shift
        hsq "$@"
        exit "$?"
    }
    ;;

    *) break;
esac; done

is_stdout_pipe() {
    # If stout is a pipe
    [[ -p /dev/stdout ]]
}
is_stdout_pipe
ispipe="$?"

CMD="$(cmd-nice "$@")"

{
case "$CMD" in
    pyi|"py i") {
        hsqc py i | awk 1
        hsqc pyi | awk 1
    }
    ;;

    *) {
        hsqc "$@"
    }
    ;;
esac
} | {
    if test "$onestatement" = "y"; then
        sed "s/cd \\([^;]\\+\\); \\+\\(.*\\)/indir \\1 zrepl \\2/" | cmd-lispify
    else
        cat
    fi
} | {
    if test "$sexp_output" = "y"; then
        sed "s/\\(.*\\)/(\\1)/"
    else
        cat
    fi
} | {
    if test "$nofzf" = "y"; then
        pavs
    else
        {
            mfz +s -m -nv | awk 1 | mnm | hsqf-clean
        } | while IFS=$'\n' read -r line; do
            exec <&1
            # eval "$line"
            # sps -E "$line"
            # sps zrepl -E "$line"
            if test "$nozrepl" = "y"; then
                eval "$line"
            else
                nw zrepl -E "$line"
            fi
            break
        done
    fi
}
