#!/bin/bash

# This operates on double quotes

# cmd - print the arguments given to this script

# https://mullikine.github.io/posts/missing-posix-shell-functions-cmd-and-myeval/

# POSIX-compliant
p () {
    {
        i=1
        while [ "$i" -lt "$#" ]; do
            eval ARG=\${$i}
            printf -- "%s " "$ARG"
            i=$((i + 1))
        done
        eval ARG=\${$i}
        printf -- "%s" "$ARG"
    } | sed 's/\\n/\n/g'
}

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    # bashism
    IFS= read -rd '' in < <(cat);typeset -p in &>/dev/null

    set -- "$in" "$@"
fi

cmd-nice-jq() {
    for var in "$@"
    do
        printf '%s ' "$(printf %s "$var" | pen-q-jq | sed -e 's/^"//' -e 's/"$//')";
    done | sed 's/ $//'
}

cmd-nice-jq "$@"
