#!/bin/bash

: "${GOOSE_API_KEY:="$PEN_LM_KEY"}"

if test -s $HOME/.pen/goose_api_key; then
    : "${GOOSE_API_KEY:="$(cat $HOME/.pen/goose_api_key)"}"
fi

test -n "$GOOSE_API_KEY" || {
    echo "GOOSE_API_KEY not given to script"
    exit 1
}

export GOOSE_API_KEY

# This only really uses the env vars
pen-goose.py "$@" | pen-log goose-temp