#!/bin/bash
export TTY

# https://www.youtube.com/watch?v=dumUElmlVJA

inside-docker-p() {
    test -f /.dockerenv
}

use_comint=y
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nd) {
        export NO_DOCKER=y
        shift
    }
    ;;

    -s) {
        export SILENT=y
        shift
    }
    ;;

    -d) {
        export DEBUG=y
        shift
    }
    ;;

    *) break;
esac; done

if { ! test "$NO_DOCKER" = y; } && { ! inside-docker-p; }; then
    # pen sh nvc ii "$@"
    pen sh pensieve "$@"
    exit "$?"
fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -pf-list) {
        # Function for listing files and dirs
        pf_list_function="$2"
        shift
        shift
    }
    ;;

    -pf-gen) {
        # Function for generating file contents
        pf_gen_function="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${pf_list_function:="pf-list-subdirectories/1"}"
: "${pf_gen_function:="pf-generate-the-contents-of-a-new-file/6"}"

dir="$1"
shift

dir="$(realpath "dir")"

test -d ~/.emacs/host/pensieve && : "${pensieve_dir:=~/.emacs/host/pensieve}"
: "${pensieve_dir:="/root/repos/pensieve"}"

# In container
cd "$pensieve_dir"
lein run pensieve "$dir"

## ruse
# cd $MYGIT/ahungry/ruse
# mkdir -p /tmp/dog-pics
# lein run dog /tmp/dog-pics