#!/bin/bash
export TTY

# Don't actually use this script until this is finished.
# Also, this seems like a big task, so it's very far down the pipeline

# . $SCRIPTS/lib/hs

# Run the preprocessor on any opened file
# expand-bash-preprocessor

# export BASH_ENV=$HOME/.scriptrc

# bash "$@"
# cmd bash <(echo "echo \$0") "$@"

newscript="$(0</dev/null tf sh)"

scriptname="$1"
shift
wp="$(which "$scriptname")"

if test -f "$wp"; then
    cat "$wp" | expand-bash-preprocessor > "$newscript"

    bash -c ". ${newscript}" -- "$@"
else
    # https://unix.stackexchange.com/a/250792
    bash --rcfile "$PENELD/scripts/lib/pash" -- "$@"
fi
