#!/usr/bin/python3

from aixapi import AIxResource
import os

# Get your API Key at apps.aixsolutionsgroup.com

if __name__ == "__main__":
    api_key = os.environ.get("AIX_API_KEY")
    aix_resource = AIxResource(api_key)
    print(str(aix_resource.compose(os.environ.get("PEN_PROMPT")).get("data", dict()).get("text")))