#!/bin/bash
export TTY

# export PEN_PROXY=localhost:9837 PEN_LM_COMPLETE=openai-complete.sh; shx pen-test-lm-complete

export PEN_LM_COMMAND="openai-complete.sh"
export PEN_UPDATE=""
export PEN_PROXY_REPONSE=""
export PEN_USER_AGENT="emacs/pen"
export PEN_MIN_TOKENS="0"
export PEN_MAX_TOKENS="206"
export PEN_MIN_GENERATED_TOKENS="3"
export PEN_MAX_GENERATED_TOKENS="64"
export PEN_APPROXIMATE_PROMPT_LENGTH="142"
export PEN_ENGINE_MIN_TOKENS="0"
export PEN_ENGINE_MAX_TOKENS="2049"
export PEN_ENGINE_MAX_GENERATED_TOKENS="4096"
export PEN_TEMPERATURE="0.7"
export PEN_TOP_P="1"
export PEN_TOP_K="10"
export PEN_PROMPT="This is a tweet sentiment classifier\\n\\nTweet<pen-colon> <pen-doublequote>I loved the new Batman movie<pen-bang><pen-doublequote>      \\nSentiment<pen-colon> Positive\\n###\\nTweet<pen-colon> <pen-doublequote>I hate it when my phone battery dies.<pen-doublequote>\\nSentiment<pen-colon> Negative\\n###\\nTweet<pen-colon> <pen-doublequote>My day has been 👍<pen-doublequote>\\nSentiment<pen-colon> Positive\\n###\\nTweet<pen-colon> <pen-doublequote>This is the link to the article<pen-doublequote>\\nSentiment<pen-colon> Neutral\\n###\\nTweet<pen-colon> <pen-doublequote>Overall, it was disappointing.<pen-doublequote>\\nSentiment<pen-colon>"
export PEN_PAYLOADS=""
export PEN_FLAGS=""
export PEN_STOP_SEQUENCE="<pen-newline>"
export PEN_STOP_SEQUENCES="[<pen-doublequote><pen-backslash>n<pen-doublequote>,<pen-doublequote><pen-backslash>n<pen-doublequote>,<pen-doublequote><delim><pen-doublequote>]"
export PEN_N_COMPLETIONS="10"
export PEN_ENGINE_MAX_N_COMPLETIONS="10"
export PEN_COLLECT_FROM_POS="346"
export PEN_END_POS="346"
export PEN_SEARCH_THRESHOLD=""
export PEN_TRAILING_WHITESPACE=""
export PEN_MODE=""
export PEN_GEN_UUID="163df8e3-443c-48fb-852f-5451027bc96b"
export PEN_GEN_TIME="1643707250.073039"
export PEN_GEN_DATE="01.02.22"
: "${PEN_GEN_DIR:="/root/.pen/results/results_1643707250.073039_01.02.22_163df8e3-443c-48fb-852f-5451027bc96b"}"
export PEN_GEN_DIR

lm-complete