#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

if ! stdin_exists && test -f "$1"; then
    exec < "$1"
fi

# This will do things like compile anchors

yaml2json | json2yaml | pa -E "tf yml | xa e"
