#!/bin/bash
export TTY

PEN_PAGER="less"

export NOAUTOCHDIR=y

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

is_stdout_pipe() {
    # If stout is a pipe
    [[ -p /dev/stdout ]]
}

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

is_tty
istty="$?"

stdin_exists
hasstdin="$?"

is_stdout_pipe
ispipe="$?"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -tout) {
        force_tty_out=y
        shift
    }
    ;;

    *) break;
esac; done

# These checks appear to have done the job regarding fork bombs
if { ! test "$istty" = 0; } && { ! test "$force_tty_out" = y; }; then
    cat
    exit $?
fi

if ! test "$hasstdin" = 0; then
    echo "pa does not have stdin" | hls red 1>&2
    exit 1
fi

pattern=
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -v) {
        PEN_PAGER=v
        shift
    }
    ;;

    -E) {
        PEN_PAGER="$2"
        shift
        shift
    }
    ;;

    -e|-p) {
        shift
        PEN_PAGER="$(cmd "$@")"
        shift "$#"
    }
    ;;

    -l) {
        PEN_PAGER="tless +F -S"
        shift
    }
    ;;

    -tf) {
        open_as_file=y
        shift
    }
    ;;

    -x) {
        ext="$2"
        shift
        shift

        PEN_PAGER="pen-tf pager $ext | xa r"
    }
    ;;

    -sp) {
        PEN_PAGER=sp
        shift
    }
    ;;

    -sp) {
        PEN_PAGER="sp"
        shift
    }
    ;;

    -vs) {
        PEN_PAGER="vs"
        shift
    }
    ;;

    -vd) {
        PEN_PAGER="fpvd"
        shift
    }
    ;;

    -ln|-lnano) {
        PEN_PAGER="EDITOR=nano less -S"
        shift
    }
    ;;

    -lv) {
        PEN_PAGER="EDITOR=v less -S"
        shift
    }
    ;;

    -lvs) {
        PEN_PAGER="EDITOR=vs less -S"
        shift
    }
    ;;

    +/*) { # pattern
        pattern="$(p "$opt" | mcut -d+/ -f2 | s chomp)"

        shift
    }
    ;;

    *) break;
esac; done

test "$#" -gt 0 && last_arg="${@: -1}"
: ${defaultcommand:="$last_arg"}
: ${defaultcommand:="cat"}

open_fp() {
    fp="$1"
    shift

    CMD="$(cmd "$@")"
    if test "$open_as_file" = "y"; then
        # etty
        exec <&1

        # in-tty -E "${PEN_PAGER} ${CMD} \"$inputfp\""

        eval "${PEN_PAGER} ${CMD} \"$inputfp\""
    else
        cat "$inputfp" | eval "${PEN_PAGER} ${CMD}"
    fi
}

pager() {
    if test "$ispipe" = 0; then
        cat
    elif { test "$istty" = 0 || test "$force_tty_out" = y; } && test "$hasstdin" = 0; then
        inputfp="$(pen-tf pager txt)"
        if test -s "$inputfp"; then
            if test -n "$pattern"; then
                open_fp "$inputfp" +/"$pattern"
            else
                open_fp "$inputfp"
            fi
        fi
    else
        $defaultcommand
    fi
}

pen-dos2unix | pager "$@"
