#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -wintype) {
        wintype="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done
: "${wintype:="sps"}"

vipe_cmd="$1"
# eipe
: "${vipe_cmd:="vipe"}"

# echo start | pen-tv &>/dev/null

# This is hanging for pen-eipe when emacs is started with run.sh
# Therefore, pen-eipe is simply not finishing.
# Well, actually pen-eipe *does* finish.

if pen-tm session-exists human; then
    pen-tm -sout -vipe "$wintype" -t human: "$vipe_cmd" | cat
else
    pen-tm -sout -vipe "$wintype" "$vipe_cmd" | cat
fi

# pen-tm -w -sout -vipe spv "$vipe_cmd" | cat

# echo end | pen-tv &>/dev/null
