#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

: "${BROWSER:="sps-lg"}"

if test "$BROWSER" = pen-browser || test "$BROWSER" = browser; then
    export BROWSER=nw-lg
fi

# If handled with something else, abort browser
pen-handle-url "$@" && exit "$?"

"$BROWSER" "$@"
