#!/bin/bash
export TTY

# http://go2linux.garron.me/shell-command-convert-binary-octal-decimal-hexadecimal/

stdin_exists() {
    ! [ -t 0 ] && read -t 0
}

if stdin_exists; then
    IFS= read -rd '' input < <(cat /dev/stdin)
else
    input="$1"
fi

echo "obase=8;$input" | bc