#!/bin/bash
export TTY

: ${CWD:="$(pwd)"}
: ${CMD:="$(cmd-nice-posix "$@")"}
: ${PEN_USER:="$(whoami)"}

if test "$SSH_TO_HOST" = "y"; then
    ssh \
        -i "~/.pen/host_key" \
        -o ControlMaster=auto \
        -o ControlPath="~/ssh-controlpath-%r@%h:%p" \
        -o UserKnownHostsFile=/dev/null \
        -o StrictHostKeyChecking=no \
        -t $PEN_USER@$(hostname) \
        "bash -l -c $(cmd-nice-posix ". ~/.profile; cd $(cmd-nice-posix "$CWD"); $CMD")"
else
    cd "$CWD"
    eval "$CMD"
fi