#!/bin/bash
export TTY

. $PENELD/scripts/utils.sh

# Test its speed
# nonvc slmenu

# Don't detach by default because most of the time I will open a TUI
# : "${detach:="y"}"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -d) {
        detach=y
        shift
    }
    ;;

    -nd) {
        detach=
        shift
    }
    ;;

    -i|-initial-input) {
        initial_input="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

exec 3>&0

if ! stdin_exists 2>/dev/null; then
    exec < <(list-executables|awk 1|uniqnosort)
fi

if test -z "$LINES"; then
    eval `resize`
fi

result="$(
    if test "$LINES" -gt "5" || ! command -v slmenu; then
        if test "$#" -eq 0; then
            set -- -q "'${initial_input}" "$@"
        fi
        pen-fzf "$@" | cat
    else
        /usr/local/bin/slmenu $LINES "$@"
    fi
)"

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

exec 0>&3

is_stdout_pipe() {
    # If stout is a pipe
    [[ -p /dev/stdout ]]
}

if is_stdout_pipe; then
    printf -- "%s\n" "$result"
elif is_tty; then
    if test "$detach" = "y"; then
        # DO NOT unset TMUX.
        test -n "$result" && tmux run -b "unbuffer $result > /dev/null"
    else
        test -n "$result" && eval "$result"
    fi
else
    printf -- "%s\n" "$result"
fi
# pak
