#!/bin/bash
export TTY

# ( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

export VIPIFY

is_tty() {
    [[ -t 1 ]]
}

stdin_exists() {
    ! [ -t 0 ]
}

export VIPIFY=y

if test -n "$1"; then
    : ${CMD:="$(cmd-nice "$@")"}
    export EDITOR="$CMD"
fi

if is_tty; then
    /usr/bin/vipe "$@"
else
    if stdin_exists; then
        /usr/bin/vipe "$@"
    else
        tf_zle="$(mktemp ${TMPDIR}/tf_zleXXXXXX || echo /dev/null)"
        exec 3>&1
        exec 1>/dev/tty
        vim "$tf_zle"
        exec 1>&3
        cat "$tf_zle"
    fi
fi
