#!/bin/bash

: "${HUMAN_API_KEY:="$PEN_LM_KEY"}"

if test -s $HOME/.pen/human_api_key; then
    : "${HUMAN_API_KEY:="$(cat $HOME/.pen/human_api_key)"}"
fi

# test -n "$HUMAN_API_KEY" || {
#     echo "HUMAN_API_KEY not given to script"
#     exit 1
# }

: "${PEN_REPETITION_PENALTY:="1.0"}"

export HUMAN_API_KEY

if test -z "$PEN_N_COMPLETIONS" || test "$PEN_N_COMPLETIONS" -gt 4; then
    PEN_N_COMPLETIONS=4
fi

# JSON
export PEN_PROMPT
export PEN_PROMPT_FULL
export PEN_SUFFIX
export PEN_PAYLOADS
export PEN_MODEL
export PEN_MAX_TOKENS
export PEN_TEMPERATURE
export PEN_REPETITION_PENALTY
export PEN_TOP_P
export PEN_STOP_SEQUENCE
export PEN_N_COMPLETIONS
export PEN_MODE
export PEN_GEN_UUID
export PEN_GEN_TIME

: "${PEN_N_COMPLETIONS:="4"}"

sedstop="$(printf -- "%s" "$PEN_STOP_SEQUENCE" | sed -z 's/\\/\\\\/g')"

# pen-human.py "$@" | sed -z "s~${PEN_STOP_SEQUENCE}.*~~"

{
# printf -- "%s" "$PEN_PROMPT"
pen-human.py "$@" | pen-log human-temp | sed -z "s~${sedstop}$~~"
} | pen-log human