#!/bin/bash
export TTY

: ${EDITOR:="v"}
export EDITOR

ff="$(ux mkfifo xc)"

#IFS= read -rd '' output < <(xc - | tm -soak -bout nw -n edit-x-clipboard vipe | cat)
#printf -- "%s" "$output" | xc

export EDITOR=v

IFS= read -rd '' input < <(xc - | vipe | soak);typeset -p input &>/dev/null
ret="$?"
if test "$ret" -eq 0; then
    printf -- "%s" "$input" | xc
fi
