#!/bin/bash
export TTY

# A sorting library for Pen.el

sn="$(basename "$0")"

sn="$(p "$sn" | sed 's/^pen-//')"

case "$sn" in
    *) {
        f="$1"
        shift
    }
esac

case "$f" in
    line-length) {
        # perl sort with custom comparator
        awk 1 | perl -e 'print sort { length($a) <=> length($b) } <>'

        # I need the awk 1 for the folowing to not have a bug:
        # pen-els list-bible-book-titles-lines | pen-sort line-length
        # The problem was that if there is no final line ending the last item is joined to the second-to-last item
    }
    ;;
    
    line-length-desc) {
        # perl sort with custom comparator
        awk 1 | perl -e 'print sort { length($b) <=> length($a) } <>'
    }
    ;;
    
    path-depth) {
        # perl sort with custom comparator
        perl -e 'print sort { ($a =~ tr!/!!) <=> ($b =~ tr!/!!) } <>'
    }
    ;;

    *)
esac