#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

CMD="$(cmd "$@")"
: ${CMD:="$(cmd "$@")"}

extra_commands="silent! echom"

# This is zippy
# extra_commands+="|windo call GeneralSyntax()"
# This is slow
# extra_commands+="|windo call GeneralSyntax()|au BufEnter * call GeneralSyntax()"

# I just needed to finish it all off with a redraw! (note the !)
# windo set nofoldenable
# windo normal! zr
# windo set foldmethod=diff foldenable foldminlines=0
cmd="vimdiff -c \"set noswapfile\" -c \"syntax off\" -c $(cmd-nice-posix "$extra_commands") -c \"wincmd w | windo set foldmethod=diff foldenable foldminlines=0\" -c \"normal! zM\" -c \"redraw!\" -c 'norm ]c[c' $CMD"

eval "$cmd"