#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

#CMD="$(cmd "$@")"

#: ${CMD:="$(cmd "$@")"}
#eval "tm -f -S -tout sps -fargs r preview $CMD"

tm -f -S -tout sps -fargs r preview "$@"
