#!/bin/bash

: "${AIX_API_KEY:="$PEN_LM_KEY"}"

if test -s $HOME/.pen/aix_api_key; then
    : "${AIX_API_KEY:="$(cat $HOME/.pen/aix_api_key)"}"
fi

test -n "$AIX_API_KEY" || {
    echo "AIX_API_KEY not given to script"
    exit 1
}

export AIX_API_KEY

export PEN_ENGINE
export PEN_MAX_TOKENS
export PEN_TEMPERATURE
export PEN_TOP_P
export PEN_STOP_SEQUENCE

pen-aix.py "$@"
