#!/bin/bash
export TTY

# From tmux, press `F1 M-x` to end the asciinema session

pen-detach-asciinema-tmux-sessions

x_session="$(cat /tmp/asciinema-x-session.txt)"
user_session="$(cat /tmp/asciinema-user-session.txt)"

CALLER_TARGET="$(tmux display -p "#{session_name}")"

if test -n "$TMUX" && test "$CALLER_TARGET" = "$user_session"; then
    tmux switch-client -t "$x_session:"
    tmux kill-session -t "$user_session"
fi

if test -n "$x_session"; then
    # cmd="unset TTY; pen-x -s \"TMUX= tmux attach -t ${x_session}:\" -c m -s.2 -c d -e \"<enter>\" -c m -e \"»\" -s.2 -f1 -s L -s.2 -e \"»\" -x \"tmux kill-session -t $x_session:\" -exit"
    cmd="unset TTY; pen-x -s \"TMUX= tmux attach -t ${x_session}:\" -c m -s.2 -c d -e \"<enter>\" -c m -e \"»\" -s.2 -x \"tm-xturls\" -s.2 -x \"tmux kill-session -t $x_session:\" -exit"
    tmux new-session -d -A -s "cinema-ender" \; respawnp -k -t "cinema-ender:1" "$cmd"
fi

# now use pen-x to upload the asciinema recording and copy the url
