#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test "$#" -gt 0 || exit 1

bin="$1"
shift

if pen-ssh-host which "$bin"; then
    pen-ssh-host "$bin" "$@"
else
    "$bin" "$@"
fi
