#!/bin/bash
export TTY

: ${SEDOPTS:="-u"}

# . $HOME/.shell_environment
# . $HOME/.shellrc
export PEN=/root/.pen
export PENCONF="$HOME/.pen"
export DUMP="$HOME/dump"
export REPOS="$HOME/repos"
export NOTES="/root/notes"

unset EMACSD_BUILTIN
test -d "/root/.emacs.d" && : "${EMACSD_BUILTIN:="/root/.emacs.d"}"
export EMACSD_BUILTIN

unset EMACSD
test -d "/root/.emacs.d/host" && : "${EMACSD:="/root/.emacs.d/host"}"
test -d "/root/.emacs.d" && : "${EMACSD:="/root/.emacs.d"}"
export EMACSD

export GOPATH="$HOME/go"
export GOBIN="$HOME/go/bin"
export TMPDIR="/tmp"
export GLOSSARIES="$PENCONF/glossaries"
export PENELD="$EMACSD/pen.el"
export PEN_SCRIPTS="$PENELD/scripts"
export PROMPTSD="$EMACSD/prompts"
export PROMPTS="$PROMPTSD/prompts"
export MIRRORD=/root/text-mirror
export BROWSER="eww -x"
export MYGIT=/volumes/home/shane/var/smulliga/source/git

sn="$(basename "$0")"

# Use arrays here

unminimise() {
    sed $SEDOPTS -e "s#\$DUMP#${DUMP/}#g" \
                 -e "s#\$NOTES#${NOTES}#g" \
                 -e "s#\$PROMPTS#${PROMPTS}#g" \
                 -e "s#\$EMACSD#${EMACSD}#g" \
                 -e "s#\$EMACSD_BUILTIN#${EMACSD_BUILTIN}#g" \
                 -e "s#\$TMP#${TMP}#g" \
                 -e "s#\$HOME#${HOME}#g" \
                 -e "s#\$PENELD#${PENELD}#g" \
                 -e "s#\$MIRRORD#${MIRRORD}#g" \
                 -e "s#\$MYGIT#${MYGIT}#g" \
                 -e "s#\$PENCONF#${PENCONF}#g" \
                 -e "s#\$PEN#${PEN}#g" \
                 -e "s#\$GLOSSARIES#${GLOSSARIES}#g" \
                 -e "s#\${GOPATH%%:\*}#${GOPATH%%:\*}#g" \
                 -e "s#\$PEN_SCRIPTS#${PEN_SCRIPTS}#g" \
                 -e "s#^~/#${HOME}/#g" \
                 -e "s#^~\$#${HOME}#g" \
                 | cat
}

minimise() {
    sed $SEDOPTS -e "s#${HOME}${HOME}#${HOME}#g" \
                 -e "s#${NOTES}#\$NOTES#g" \
                 -e "s#${PENELD}#\$PENELD#g" \
                 -e "s#${MIRRORD}#\$MIRRORD#g" \
                 -e "s#${MYGIT}#\$MYGIT#g" \
                 -e "s#${PENCONF}#\$PENCONF#g" \
                 -e "s#${PEN}#\$PEN#g" \
                 -e "s#${GLOSSARIES}#\$GLOSSARIES#g" \
                 -e "s#^/home/[a-zA-Z]\+#$HOME#g" \
                 -e "s#^/root#$HOME#g" \
                 -e "s#\([\"' =]\)/home/[a-zA-Z]\+#\1$HOME#g" \
                 -e "s#^/Users/[^/]\+#\$HOME#g" \
                 -e "s#\([\"' =]\)/Users/[a-zA-Z]\+#\1$HOME#g" \
                 -e "s#${DUMP}#\$DUMP#g" \
                 -e "s#${PROMPTS}#\$PROMPTS#g" \
                 -e "s#${EMACSD}#\$EMACSD#g" \
                 -e "s#${EMACSD_BUILTIN}#\$EMACSD_BUILTIN#g" \
                 -e "s#${TMP}#\$TMP#g" \
                 -e "s#${PEN_SCRIPTS}#\$PEN_SCRIPTS#g" \
                 -e "s#${GOPATH%%:*}#\${GOPATH%%:\*}#g" \
                 -e "s#${HOME}#\$HOME#g" \
                 | cat
}

if test "$1" = "-x" || test "$sn" = "pen-umn"; then
    unminimise
elif test "$sn" = "m" || test "$sn" = "pen-mnm"; then
    unminimise | minimise
else
    cat
fi
