#!/bin/bash
export TTY

: ${EDITOR:="v"}
export EDITOR

ff="$(ux mkfifo xc)"

#IFS= read -rd '' output < <(xc - | tm -soak -bout nw -n edit-x-clipboard vipe | cat)
#printf -- "%s" "$output" | xc

export EDITOR=v

xc - | vipe | soak | xc
