#!/bin/bash
export TTY

# https:/articles/copilot/

# Make it so all sites without a file extension or fragment identifier on the end should have /
# Don't change this.
# http://www.learndatalogtoday.org/chapter/0
# Require more than one [^.#?/][^.#?/]\+

sed '/\/\/[^\/]*.[^\/]*\/\(.*\/\)*[^.#?/][^.#?/]\+\(#.*\|$\)/{s=\(#.*\|$\)=/\1=;}' |  \
    sed '/https:\/\/l.facebook.com\/l.php?u=/{s~https://l.facebook.com/l.php?u=~~;}' |  \
    sed '/\/\/jessmart.in\/.*[^/]$/{s=$=/=;}' |  \
    sed '/https:\/\/www.unisonweb.org\/.*[^/]$/{s=$=/=;}' | \
    sed '/\/web.archive.org\/web.*http.*github.com\//{s=.*web.archive.org/web/[^/]*/==;}' | \
    sed '/\/deepai.org/s/\/$//' | \
    sed '/\/[^.]*.guildofarchivists.org\/.*\/$/{s=\/$==;}' |  \
    sed '/\/www.bschaatsbergen.com/s/\/$//' | \
    sed '/\/arxiv.org/s/\/$//' | \
    sed '/\/wiki.haskell.org/s/\/$//' | \
    sed '/\/en.wikibooks.org/s/\/$//' | \
    sed '/\/news.ycombinator.com\/news/s/\/$//' | \
    sed '/\/programming-idioms.org/s/\/$//' | \
    sed '/artandpopularculture.com/s/\/$//' | \
    sed '/\/www.schoolofhaskell.com/s/\/$//' | \
    sed '/\/www.metalevel.at/s/\/$//' | \
    sed '/\/www.metalevel.at/s/\/#/#/' | \
    sed '/\/en.bitcoin.it/s/\/$//' | \
    sed '/\/.*\.github.io/s/\/$//' | \
    sed '/\/.*\.github.io/s/\/#.*//' | \
    sed '/wikipedia.org/s/\/$//' | \
    sed '/wikipedia.org/s/\/#.*//' | \
    sed '/http:\/\/google/s/http:/https:/' | \
    sed '/https\?:\/\/www\.google\.com\/url?q=/s/https\?:\/\/www\.google\.com\/url?q=\(.*\)&sa.*=/\1/' | \
    sed '/.*haskell.org/s/\/$//' | \
    sed '/.*haskell.org/s/\/#.*//'

# I tried curl-get-redirect for google searches but google doesn't provide the information

# https://web.archive.org/web/20161230180206/
# https://web.archive.org/web/20161230180206/https://github.com/unisonweb/unison/blob/master/unison-src/searchengine.u
