#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# wfind . -type d

# find things at this depth
# wfind / | u dirsuffix

first_arg="$1"
first_arg="$(realpath "$first_arg")"


shift

eval "find $(cmd "$first_arg") -mindepth 1 -maxdepth 1" "$@"