#!/bin/sh

# Can probably take back out the semicolon
# -e "s/<pen-semicolon>/;/g" \
# Can't encode dashes because it breaks slugs
# -e "s/-/<pen-dash>/g" \

# cat
sed -e "s/\\\\n/<pen-notnewline>/g" \
    -e "s/\\$/<pen-dollar>/g" \
    -e "s/\`/<pen-backtick>/g" \
    -e "s/\\\\/<pen-backslash>/g" \
    -e "s/!/<pen-bang>/g" \
    -e "s/\"/<pen-doublequote>/g" \
    -e "s/:/<pen-colon>/g" \
    -e "s/'/<pen-singlequote>/g" | sed -z "s/\\n\\n/<pen-dnl>/"
