#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# test -f "${GOPATH%%:*}/bin/up" || go get -u github.com/akavel/up
test -f "${GOPATH%%:*}/bin/up" || go install github.com/akavel/up@latest

${GOPATH%%:*}/bin/up "$@"
