#!/bin/bash
export TTY

# Frustratingly, this cant be named racket-langserver

. $SCRIPTS/lib/hs

# raco pkg update --batch racket-langserver

# arbitrate "racket" "--lib" "racket-langserver" "$@"
"racket" "--lib" "racket-langserver" "$@"
