#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -l) {
        loop=y
        shift
        shift
    }
    ;;

    -d) {
        default="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

prompt_message="$1"

# if test -n "$prompt_message"; then
#     read -ep "$prompt_message: " query
# fi
code=0

if test "$loop" = "y"; then
    # When ^D is used, read ends up with the exit code "1"
    while ! test "$code" -eq 1; do
        read -ep "$prompt_message: " query 1>&2
        if test -z "$query" && test -n "$default"; then
            query="$default"
        fi
        code="$?"
        printf -- "%s\\n" "$query"
    done
else
    read -ep "$prompt_message: " query 1>&2
    if test -z "$query" && test -n "$default"; then
        query="$default"
    fi
    printf -- "%s\\n" "$query"
fi
