#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -xml) {
        TO_XML=y
        shift
    }
    ;;

    -t) {
        export USE_TOR=y
        shift
    }
    ;;

    -w) {
        WAITTIME="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

export UPDATE

URL="$1"
test -n "$URL" || exit 1

case "$URL" in
    *quora.com*) {
        : "${WAITTIME:="4000"}"
    }
    ;;

    *ryanong.co.uk*) {
        : "${WAITTIME:="4000"}"
    }
    ;;

    *clojuredocs.org*) {
        : "${WAITTIME:="4000"}"
    }
    ;;

    *)
esac

: "${WAITTIME:="2000"}"

# 0</dev/null pen-ci 
# 2</dev/null

run_cmd() {
    cmd1 bash -c "2>/dev/null pen-chromium --no-sandbox --headless --ignore-certificate-errors --disable-gpu --virtual-time-budget=$WAITTIME --dump-dom $(cmd-nice-posix "$URL")" 1>&2
    bash -c "2>/dev/null pen-chromium --no-sandbox --headless --ignore-certificate-errors --disable-gpu --virtual-time-budget=$WAITTIME --dump-dom $(cmd-nice-posix "$URL")"
}

get_dom() {
    output=
    until test -n "$output" || test "$WAITTIME" -gt 20000; do
        echo "Attempting with WAITTIME=$WAITTIME" 1>&2
        export WAITTIME
        output="$(run_cmd)"
        WAITTIME="$((WAITTIME * 2))"
    done
    echo "$output"
}

# bash -c "2>/dev/null pen-chromium --no-sandbox --headless --ignore-certificate-errors --disable-gpu --virtual-time-budget=$WAITTIME $(test "$USE_TOR" = "y" && echo "--proxy-server=\"socks5://127.0.0.1:9050\"") --dump-dom $(cmd-nice-posix "$URL")" | {

get_capture() {
    get_dom | {
        # This fixes pirate bay in eww. It separates adjacent links for avy.
        sed 's/<a / <a /g'
    } | {
        if test "$TO_XML" = "y"; then
            html2xhtml
        else
            cat
        fi
    }
}

capture="$(get_capture)"

if printf -- "%s\n" "$capture" | grep -q -P 'Verifying you are human'; then
    if tpop-yn "Page needs CAPCHA. Open Chrome?"; then
        browsh "$URL"
        capture="$(UPDATE=y get_capture)"
        # TODO Find a way to get the actual DOM from browsh. Because it doesn't make chome start working again
        # So while browsing browsh, I should be able to dump the DOM.
    fi
fi
printf -- "%s\n" "$capture" | pavs