#!/bin/bash
export TTY
cd "$PENEL_DIR"
{
pwd

echo scripts/
scripts_loc="$(find scripts -type f | while read -r line; do cat "$line" | awk 1; done | wc -l)"
pl "$scripts_loc"
echo
echo src/
src_loc="$(find src -type f | while read -r line; do cat "$line" | awk 1; done | wc -l)"
pl "$src_loc"
echo
echo khala/
cd "/root/.emacs.d/host/khala"
khala_loc="$(find src -type f | while read -r line; do cat "$line" | awk 1; done | wc -l)"
pl "$khala_loc"
echo
echo pensieve/
cd "/root/.emacs.d/host/pensieve"
pensieve_loc="$(find src -type f | while read -r line; do cat "$line" | awk 1; done | wc -l)"
pl "$pensieve_loc"

echo "$scripts_loc+$src_loc+$khala_loc+$pensieve_loc" | bc
} | pen-pavs
