#!/bin/bash
export TTY

if test -n "$TMUX"; then
    server="$(echo "$TMUX" | cut -d , -f 1 | xargs basename)"
    # : ${server:="Pen"}
else
    server="$(basename "$(pen-glob /tmp/tmux-*/*)")"
fi
echo "$server"
test -n "$server"