#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -nrq) {
        no_remove_query=y
        shift
    }
    ;;

    *) break;
esac; done

if ! stdin_exists; then
    argstr="$@"
    exec < <(printf -- "%s" "$argstr")
fi

# options such as -d are passed to rosie-urls

{
    # e:$HOME/blog/posts/thy-kingdom-come.org
    sed 's%< youtube \([^ ]\+\) >%https://www.youtube.com/watch?v=\1%'
} | {
    # Rosie URLs does not cut off the youtube times
    rosie-urls "$@"
    # if test -f ${GOPATH%%:*}/bin/xurls; then
    #     ${GOPATH%%:*}/bin/xurls "$@"
    # else
    #     rosie-urls "$@"
    # fi
} | {
    sed "s/youtu\\.be\\//youtube.com\\/watch\\?v=/" |
    sed "/\\?v=.*\\?t=/s/\\?t/\&t/"
} | {
    sed "/\/\/www.youtube.com/{s~/embed/~/watch?v=~}" |
    sed "/\/\/www.youtube.com/{s=\&ab.*==}" |
    sed "s=^http://www.google.com/url?q\===" | sed "s/&sa=.*//" |
    sed "s=^http.\\?://webcache\\.googleusercontent\\.com/search?q\\=cache:=="
} | {
    if test "$no_remove_query" = "y"; then
        cat
    else
        sed-pcre "s/(?<!(m\/url|earch|forum|watch|ylist))\?.*//"
    fi
} | {
    sed 's/&fbcli.*//' |
    sed "s=\\\n$=="
}
