#!/bin/bash

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists; then
    fp="$(cat)"
fi

: "${fp:="$1"}"

if test -f "$fp"; then
    rp="$(realpath "$fp")"
else
    # Probably URL
    rp="$fp"
fi

{
td_thing="$(mktemp -t -d td_thingXXXXXX || echo /dev/null)"
cd "$td_thing"

if test -f "$rp"; then
    cp -a "$rp" old
elif ! test -f "$rp" && printf -- "%s\n" "$rp" | grep -q -P '^https?://'; then
    wget "$rp" -O old
fi

if test -f old; then
    if file --mime-type -Lb old | grep -q -P '/vnd.microsoft.icon'; then
        icotool -x old
        mv "$(ls old_1*)" new.png
        convert "new.png" -resize 800x600\> ./new.jpg
    elif file --mime-type -Lb old | grep -q -P '/gif'; then
        convert "old[0]" -resize 800x600\> ./new.jpg
    else
        convert old -resize 800x600\> ./new.jpg
    fi
fi
} &>/dev/null

if test -f "new.jpg"; then
    echo "$(pwd)/new.jpg"
fi
