#!/bin/sh

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}
if stdin_exists; then
    tf_thing="$(0</dev/null pen-tf thing || echo /dev/null)"
    # This chomp prevents hangs when piping a single space into a prompt function
    cat | sed -z 's/^\s*$//' > "$tf_thing"
    sha="$(sha1sum "$tf_thing" | awk '{print $1}')"
fi

cache_file_path="/tmp/pen-$(printf -- "%s\n" "$@" | tr '\n' ' ' | sed 's/ $//' | slugify)$sha.txt"

# ci means "cache it"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -a) {
        asynchronous=y
        shift
    }
    ;;

    -f) {
        force_on=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$force_on" = y || test "$PEN_CACHE" = "y"; then
    if test -f "$cache_file_path"; then
        cat "$cache_file_path"
    else
        if test "$asynchronous" = "y"; then
            # TODO Put a delay before this is allowed to run again

            if stdin_exists; then
                set -m
                CMD="$(cmd "$@")"
                cmd1 sh -c "cat $tf_thing | $CMD > $cache_file_path" >> /tmp/lsp2.log
                sh -c "cat $tf_thing | $CMD > $cache_file_path" &
            else
                "$@" > "$cache_file_path"
            fi
        else
            "$@" > "$cache_file_path"
        fi
    fi
else
    "$@"
fi
