#!/bin/bash
export TTY

sn="$(basename -- "$0")"

if ! { inside-docker-p && test -n ~/pen_user.txt; }; then
    pen sh "$sn" "$@"
    exit "$?"
fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        DO_EXEC=y
        shift
    }
    ;;

    -fa) {
        font="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

if test "$DO_EXEC" = "y"; then
    CMD="$1"
else
    CMD="$(cmd "$@")"
fi

: ${CMD:="zsh"}

statusfile=$(mktemp)

if test -n "$font"; then
    fargs=()
    fargs=( -fa "$font" "${fargs[@]}" )
fi
xterm -ls -fs 11 "${fargs[@]}" -e ". $HOME/.xterm-sh-rc; $CMD; echo \$? > $statusfile"
exit $(cat $statusfile && rm $statusfile)
