#!/bin/bash
export TTY

# pipe into this

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -f) {
        fp="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

{
if test -f "$fp"; then
    # cmd sha256sum "$fp" 1>&2
    sha256sum "$fp" | str field 1
elif stdin_exists; then
    sha256sum | str field 1
else
    echo -n "$@" | sha256sum | str field 1
fi
} | cut -c1-10
