#!/bin/bash

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

# Completely optional
if test "$#" -eq 1; then
    name="temp"
    ext="$1"
elif test "$#" -eq 2; then
    name="$1"
    ext="$2"
else
    name="temp"
    ext="txt"
fi
: "${ext:="txt"}"

fp="$(mktemp -t "tf_${name}XXXXXXX.${ext}" 2>/dev/null || :)"

# TODO
# Use ~/.pen first
# TMPDIR=$NOTES/programs/tf

if stdin_exists; then
    cat > "$fp"
    fp_sha="$(sha "$fp")"
    fp_sha="/tmp/tf_${name}_${fp_sha}.${ext}"
    mv "$fp" "$fp_sha"
    fp="$fp_sha"
fi

echo "$fp"
