#!/bin/bash
export TTY

sn="$(basename "$0")"

if ! test "$CI_CACHED" = "y"; then ocif "$sn" "$@" | pavs; exit "$?"; fi

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

export UPDATE

url="$1"
test -n "$url" || exit 1

url="$(p "$url" | xurls)"
url="$(p "$url" | sed 's/?t=*//')"

transcript_dir="$DUMP$NOTES/ws/youtube/transcripts"
subs_dir="$DUMP$NOTES/ws/youtube/subs"

cd "$subs_dir"

youtube-get-subtitles "$url"
exit "$?"

# clean-subs is used in yt-subs.sh

raw="$(
    oci yt-subs.sh "$url" |
        grep -i -P "\\.(en|fr).*\\." |
        head -n 1 | awk 1 |
        while IFS=$'\n' read -r line; do
            # echo "$line" 1>&2
            cat "$line"
        done
)"

if test -n "$raw"; then
    printf -- "%s" "$raw" |
        tr -s '\n' ' ' |
        sed 's/^\s\+//' |
        htmldecode | pen-pretty-paragraph | {
            if test "$sn" = "readsubs"; then
                cat
            else
                pen-tf txt
            fi
        } | pen-pavs
fi
