#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename "$0")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -sn) {
        sn="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

pen-e-ic -sn "$sn" -Eargs "$@"