#!/bin/bash
export TTY

mode=by_char
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -s) {
        mode=whitespace_separation
        shift
    }
    ;;

    -c) {
        mode=by_char
        shift
    }
    ;;

    -w) {
        mode=by_word
        shift
    }
    ;;

    *) break;
esac; done

if test "$mode" = "whitespace_separation"; then
    sed -e "s/\(.\)/\1\\\s*/g" -e "s/...$//"
elif test "$mode" = "by_char"; then
    sed -e "s/\(.\)/\1.*/g" -e "s/..$//"
elif test "$mode" = "by_word"; then
    sed -e "s/\( \+\)/\1.*/g"
fi