#!/bin/sh

# Can probably take back out the semicolon
# -e "s/<pen-semicolon>/;/g" \

# cat
sed -e "s/<pen-notnewline>/\\\\n/g" \
    -e "s/<pen-dollar>/\$/g" \
    -e "s/<pen-backtick>/\`/g" \
    -e "s/<pen-doublequote>/\"/g" \
    -e "s/<pen-colon>/;/g" \
    -e "s/<pen-singlequote>/'/g"