#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# "%f:%l:%c: %m"

# TODO Prompt an entire file
# TODO Create this capability

# pen-ci -f -a penf -u -nj --pool correct-english-spelling-and-grammar-1
# pen-ci -f -a penf -u -nj --pool pf-correct-the-syntax/2 code

# This opens infinite eipes when I open a text file LOL

# # export EDITOR=sps-w-pin
# export EDITOR=pen-eipe
# pen-tvipe

# So I'll just 'cat' for the moment

cat

# pen-tvipe
