#!/bin/bash
export TTY

url="$@"
test -n "$url" || exit 1

exec 0</dev/null

case "$url" in
    *arxiv.org/*) {
        fp="$(pen-tf txt)"
        0</dev/null arxiv-summary "$url" > "$fp"
        sps -E cat "$fp" | pen-str summary
    }
    ;;

    *) {
        # unbuffer rdrview "$url" | pen-str summary | cat
        # rdrview "$url" | pen-str summary | cat
        # ub -E "$(cmd rdrview "$url" | cat)" | pen-str summary | cat
        unbuffer bash -c "PAGER=cat rdrview \"$url\" | pen-str summary"
        # cmd unbuffer bash -c "rdrview \"$url\" | pen-str summary" | tv
        # which unbuffer
        # unbuffer /usr/local/bin/rdrview "$url" | pen-str summary | cat
    }
    ;;
esac