#!/bin/bash
export TTY

# pen-rc-get n-daemons

key="$1"

val="$(yq -r ".[$(cmd-nice-posix "$key")]" ~/.pen/pen.yaml)"

if test -f "/tmp/pen.yaml"; then
    runtime_val="$(yq -r ".[$(cmd-nice-posix "$key")]" /tmp/pen.yaml)"
fi

if test -n "$runtime_val"; then
    printf -- "%s" "$runtime_val"
else
    printf -- "%s" "$val"
fi