#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# "%f:%l:%c: %m"

# TODO Prompt an entire file
# TODO Create this capability

# pen-ci -f -a penf -u -nj --pool pf-generic-completion-50-tokens/1

# export EDITOR=sps-w-pin
export EDITOR=pen-eipe
pen-tvipe
# pen-tvipe
