#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# apply

# exp is a bash expression containing the variable e
# In evaluation the value for e is provided

exp="$1"
shift

for (( i = 1; i <= $#; i++ )); do
    eval e=\${$i}
    eval "$exp" | awk 1
done

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    awk 1 | while IFS=$'\n' read -r e; do
        eval "$exp" | awk 1
    done
fi
