#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

exec 0</dev/null

pat="$1"
test -n "$pat" || exit 1
ext="$2"
: "${ext:="*"}"

rg() {
    command rg --no-heading --line-buffered -b -g "$@"
}

{
    rg "**/*.$ext"  "$pat"
} | pen-sort line-length | pen-sort path-depth | pavs
