#!/bin/bash
export TTY

wd="$(pwd)"

if test "$wd" = "$HOME"; then
    wd="$HOME/notes"
    cd "$wd"
fi

paths="directories.*"
paths="$(shopt -s nullglob; shopt -s extglob; eval printf -- "%s\\\n" "$paths" | qargs)" # expand
printf -- "%s\n" "$paths" | xargs cat1 | scrape-dirs-fast.sh | pen-print-line-if-directory-exists | mnm
