#!/bin/bash
export TTY

IFS= read -r -d '' desktop_file <<HEREDOC
[Desktop Entry]
Type=Application
Name=Iceweasel
Comment=Web browser
Terminal=false
Exec=surf
Categories=Network;WebBrowser
HEREDOC

mkdir -p ~/.local/share/applications/
printf -- "%s\n" "$desktop_file" > ~/.local/share/applications/iceweasel.desktop
xdg-settings set default-web-browser iceweasel.desktop
xdg-mime default iceweasel.desktop 'x-scheme-handler/http'
xdg-mime default iceweasel.desktop 'x-scheme-handler/https'

iceweasel "$@"
