#!/bin/bash
export TTY

# Hidden terminal

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -pet) {
        in_pet=y
        shift
    }
    ;;

    -pet-in) {
        pet_in=y
        shift
    }
    ;;

    *) break;
esac; done

: "${DISPLAY:=":0"}"
export DISPLAY

# pen sh pen-tm ns -a -np -n human bash
if test "$in_pet" = "y"; then
    pen sh pen-xt -hidden pen-tm ns -a -np -n human zsh
elif test "$pet_in" = "y"; then
    pen sh pen-xt -hidden pen-tm ns -a -np -n human pet
else
    pen sh pen-xt -hidden pet pen-tm ns -a -np -n human zsh
fi