#!/bin/bash

exec 2>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -cd) {
        cdinto=y
        shift
    }
    ;;

    -c) {
        charwise=y
        shift
    }
    ;;

    -font|-f) {
        font="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

text="$@"
: "${text:="Pen.el"}"

! test -d "$fontdir" && { maybepath="/root/repos/figlet-fonts"; test -d "$maybepath" && : "${fontdir:="$maybepath"}"; }
! test -d "$fontdir" && { maybepath="$MYGIT/xero/figlet-fonts"; test -d "$maybepath" && : "${fontdir:="$maybepath"}"; }
! test -d "$fontdir" && { maybepath="$MYGIT/figlet-fonts"; test -d "$maybepath" && : "${fontdir:="$maybepath"}"; }

test -d "$fontdir" || exit 1
cd "$fontdir"

if test "$cdinto" = "y"; then
    pwd
    zcd .
    exit "$?"
fi

(

if test -n "$font"; then
    if ! test "$charwise" = "y"; then
        # echo "$font"
        echo "$text" | toilet -f "$font";
    else
        for (( i=0; i<${#text}; i++ )); do
            echo "${text:$i:1}"
        done
    fi
else
    if ! test "$charwise" = "y"; then
        for bn in *; do
            echo "$bn"
            # echo "$text" | toilet -f "$bn" --gay;
            echo "$text" | toilet -f "$bn";
            echo
        done
    else
        for (( i=0; i<${#text}; i++ )); do
            echo "${text:$i:1}"
        done
    fi
fi

) | lolcat -f | less -rS
