#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

vipe_cmd="$@"
: "${vipe_cmd:="pen-f filter-with-fzf"}"

# CMD="bash -c $(cmd "$vipe_cmd")"

toggle-tmux-popup -x C -y C -w 90% -h 90% "$vipe_cmd" | cat
