#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# instance of pinwand:
# https://bpa.st/about

# echo "foo" | curl -X POST http://localhost:8000/curl -F 'raw=<-'
# Paste URL:   http://localhost:8000/OE
# Raw URL:     http://localhost:8000/raw/GU
# Removal URL: http://localhost:8000/remove/GQBHGJYKRWIS34D6FNU6CJ3B5M
# € curl http://localhost:8000/raw/GU
# foo%

curl "https://bpa.st/+emacs-lisp"