#!/bin/bash
export TTY

# find-thing, in order:
# - symbol from elisp
# - program on the path (i.e. shell scripts)

funcname="$1"

# pen sh in-tm pen-e -e "(find-file \"/root/.emacs.d/host/khala/project.clj\")(pen-cider-go-to-symbol \"mount-pensieve\")"

if test -n "$funcname"; then
    pen sh in-tm pen-e -e "(find-function '$funcname)"
else
    # pen sh in-tm pen-e -e "(call-interactively 'handle-fz-sym)"
    pen sh in-tm pen-e -e "(call-interactively 'find-function)"
fi
