#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

. $SCRIPTS/lib/stdin_exists

{
    if stdin_exists; then
        cat
    fi

    file_fp="$1"
    if test -f "$file_fp"; then
        0</dev/null cat "$file_fp"
    elif test -d "$file_fp"; then
        (
            cd "$file_fp"
            F fng | sed "s=^=$file_fp/="

            # find "$file_fp" -type f
        )
    fi
} | {
    umn | files-only.sh | awk 1
} | files2text-mirror

