#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

/usr/local/bin/problog dt "$@" 2>/dev/null | pavs

# Example:
# problog dt /volumes/home/shane/notes/ws/problog/scratch/umbrella.problog
# /home/shane/dump/programs/httrack/mirrors/https-dtai-cs-kuleuven-be-problog-/dtai.cs.kuleuven.be/problog/tutorial/dtproblog/01_umbrella.html
