#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

cd "$PROMPTS"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -csv) {
        to_csv=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$to_csv" = "y"; then
    echo filename,title,vars,filter,conversation,external,in development,needs work;
fi

find . -mindepth 1 -maxdepth 1 -name '*.prompt' -type f | sed 's=^./==' | awk 1 | while IFS=$'\n' read -r line; do
(
    exec 0</dev/null
    echo "$line" | hls green 1>&2
    echo -n "$line,"
    # oci -E "cat $(aqf "$line") | yq -r \"[.title,(.vars | join(\\\":\\\")),.filter,.conversation,.external,.[\\\"in-development\\\"]] | @csv\""
    eval "cat $(cmd "$line") | VERBOSE=y prompts-details-get-row" |
        sed 's/,,/,_,/g'
) | awk 1
done | pavs
