#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

if test -f "$1"; then
    fp="$1"
    shift
else
    exit
fi

(
exec 2>/dev/null
pvd --play "$fp" --batch --output /tmp/pvd_out.txt
cat /tmp/pvd_out.txt
) | pavs
