#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# # TODO Finish this
# # fargs=()
# 
# while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
#     "") { shift; }; ;;
#     -w) {
#         window_name="$2"
#         extraargs=( "$opt" "$2" "${extraargs[@]}" )
#         shift
#         shift
#     }
#     ;;
# 
#     *) break;
# esac; done

vipe_cmd="$@"
: "${vipe_cmd:="vvipe"}"

# CMD="bash -c $(cmd "$vipe_cmd")"

toggle-tmux-popup -x M+1 -y M+1 -w 90% -h 30% "$vipe_cmd" | cat
