#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

vipe_cmd="$@"
: "${vipe_cmd:="vvipe"}"

toggle-tmux-popup -x M+1 -y M+1 -w 90% -h 30% "$vipe_cmd" | cat
