#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/usr/local/bin/pylsp" || pip3.8 install python-lsp-server &>/dev/null

/usr/local/bin/pylsp "$@"
