#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

package_name="$1"
test -n "$package_name" || exit 1

Rscript -e "install.packages('$package_name', repos = 'https://cloud.r-project.org')"