#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -h|--help) {
        do_help=y
        shift
    }
    ;;

    *) break;
esac; done

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty && test "$#" -eq 0; then
    do_nvc=y
fi

if test "$do_help" = "y"; then
    /usr/bin/racket -h "$@" | pavs
else
    if test "$do_nvc" = "y"; then
        nvc /usr/bin/racket "$@"
    else
        /usr/bin/racket "$@"
    fi
fi
