* Scripts
** Currently in use
*** =chomp= - Remove surrounding whitespace

*** =wrlp= - While Read Line Pipe
This script is a lot like xargs but pipes input linewise through a command.

*** =awk 1= is used to ensure that input and output text finishes with a
newline.

*** =clean-repl=
This will be used for imaginary-mode

It's used to remove the REPL prompt (not LM prompt) from a generation
and copy the actual line of code.

*** =cmd=
Print the arguments given to this script.

*** =json2yaml= - This converts json to yaml
- stdin is json
- stdout is yaml

This is used by =tidy-prompt=.

*** =loop=
This script loops the script given as arguments

For example:
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  # Every second, output "hi"
  loop -s 1 echo hi
#+END_SRC

It's used to loop =lm-complete= to provide a
stream of continuations to =fz-pen-counsel=.

*** =pen-nsfa= - new script from args

#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  pen-nsfa echo hi
#+END_SRC

This will return the path to a new script in
the =tmp= directory which when executed will
execute =echo hi=.

=pen-nsfa= is used by =comint-quick=, which
will is used to create =comint= modes for, for example, =nlsh=.

See =nlsh-os=.

*** =tidy-prompt=
This is a bash pipeline command for standardising a prompt

Example:

#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  cat grammar-correction.prompt | tidy-prompt | sponge grammar-correction.prompt
#+END_SRC

** In-development
*** =get-ext-for-lang=
Given the name of a language, return the associated file extension.

This is used for imaginary interpreter when saving generations to a
file.
*** =ii= - imaginary interpreter
This is a REPL, which given a the name of a programming language will
provide imaginary interaction.
