#!/bin/bash
export TTY

stdin_exists() {
    ! [ -t 0 ]
}

sn="$(basename -- "$0")"
cmdname="$(printf -- "%s" "$sn" | sed 's/^rt//')"

test "$#" -gt 0 && last_arg="${@: -1}"
fp="$last_arg"
shift

if { ! stdin_exists; } && test -n "$fp" && test -f "$fp"; then
    cmd_prefix+="cat $(aqf "$fp") | "
fi

# : ${CMD:="-n \"s/.* /\U&/ip\""}

# s chomp | rtcmd "+/\(\\<sed\\>\( -[^ ]\+\)* [^-]\)\@<=." -E "sed $CMD | vi -"

# s chomp | eval "rtcmd ++sed sed $CMD"

: "${cmdname:="sed"}"
: ${CMD:="-n \"s/.* /&/ip\""}

CMD="$(cmd "$@")"
case "$cmdname" in
    sed) {
        : ${CMD:="-n \"s/.* /&/ip\""}
    }
    ;;

    *) {
        : ${CMD:="\"\""}
    }
    ;;
esac

if stdin_exists; then
    s chomp | rtcmd "++$cmdname" -E "$cmdname $CMD | v -nls"
else
    rtcmd ++$cmdname -E "$cmd_prefix $cmdname $CMD | v -nls"
fi
