#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

fp="$1"
rp="$(realpath "$fp")"
rp_slug="$(printf -- "%s\n" "$rp" | tr '\n' ' ' | sed 's/ $//' | slugify)"

fn=$(basename -- "$fp")
dn=$(dirname "$fp")
ext="${fn##*.}"
mant="${fn%.*}"

cd "$dn"

test -d "$TMPDIR" || exit 1

td_pita_pl="$TMPDIR/$rp_slug"
trap "rmdir \"$td_pita_pl\" 2>/dev/null" 0

IFS= read -r -d '' PITA_HEAD <<HEREDOC
:- use_module(library(pita)).
:- pita.
:- begin_lpad.
HEREDOC

IFS= read -r -d '' PITA_FOOT <<HEREDOC
:- end_lpad.
HEREDOC

new_fp="$td_pita_pl/${mant}.pl"

mkdir -p "$td_pita_pl"
cd "$td_pita_pl"

printf -- "%s\n" "$PITA_HEAD" > "${mant}.pl"
cat "$rp" | awk 1 >> "${mant}.pl"
printf -- "%s\n" "$PITA_FOOT" >> "${mant}.pl"

sps -d v "$new_fp"
nvt x -sh swipl -e "?-" -s "[$mant]." -c m -c l -s "prob(,P)." -c a -c f -c f -c f -c f -c f -i
