#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/root/.cargo/bin/rust-analyzer" && : "${bin:="/root/.cargo/bin/rust-analyzer"}"
test -f "/root/.local/bin/rust-analyzer" && : "${bin:="/root/.local/bin/rust-analyzer"}"
 
test -f "$bin" || cargo install "rust-analyzer" &>/dev/null

arbitrate "$bin" "$@"
