#!/bin/bash
export TTY

# This keeps getting replaced
# mkimmutable rust-analyzer

parent="$(ps -o comm= $PPID)"
( hs "$(basename "$0")" "$@" "#" "<==" "$parent" 0</dev/null ) &>/dev/null

test -f "/root/.cargo/bin/rust-analyzer" && : "${bin:="/root/.cargo/bin/rust-analyzer"}"
# test -f "/root/.local/bin/rust-analyzer" && : "${bin:="/root/.local/bin/rust-analyzer"}"
 
test -f "$bin" || rustup toolchain install nightly --component rust-analyzer-preview &>/dev/null

arbitrate "$bin" "$@"
