#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

if ! inside-docker-p; then
    in-pen "$sn" "$@"
    exit "$?"
fi

if ! inside-tmux-p; then
    in-tm "$sn" "$@"
    exit "$?"
fi

test -f $HOME/.cargo/bin/rustlings || {
    # cd "$(gc "http://github.com/rust-lang/rustlings")"
    # cd $MYGIT/rust-lang/rustlings
    cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings
    cargo install --force --path .
}

unset CWD

cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings
bin=/root/.cargo/bin/rustlings

opt="$1"
shift
case "$opt" in
    hint) {
        "$bin" "$opt" "$@" | pavs
        exit "$?"
    }
    ;;

    watch) {
        "$bin" "$opt" "$@"
        exit "$?"
    }
    ;;

    *)
esac

set -- "$opt" "$@"

# sps pin `pwd`/exercises

IFS= read -r -d '' xshcode <<"HEREDOC"
unset CWD
cd /volumes/home/shane/var/smulliga/source/git/rust-lang/rustlings
"$bin" "\$@"
HEREDOC

printf -- "%s\n" "$xshcode" | xsh -zsh "$@"
