#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

test -f $HOME/.cargo/bin/rustup || cargo install "rustup" &>/dev/null

# Remove 'scripts' so rustup replaces binaries such as:
# /root/.cargo/bin/rust-analyzer
# in te correct place

$HOME/.cargo/bin/rustup "$@"
