#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# export RUST_BACKTRACE=1
export RUST_BACKTRACE=full

# tve /root/.cargo/bin/rust-analyzer "$@"
tve /root/.local/bin/rust-analyzer "$@"
