#!/bin/bash
export TTY

( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# https://grep.app/search?q=ros.%2Asbcl.%2A--&regexp=true

ros -L sbcl -Q -l /root/.sbclrc run -- "$@"

# It's not easy to load libraries via Quicklisp. Because sbcl --script doesn't read .sbclrc, and don't load Quicklisp even if it's installed.
# i.e. #!/usr/bin/env -S sbcl-ql --script

# speedup (I haven't figured it out yet)
# https://fukamachi.hashnode.dev/day-4-roswell-how-to-make-roswell-scripts-faster
# ros -L sbcl -Q -m hello -l /root/.sbclrc run -- "$@"
