#!/bin/bash
export TTY

( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# https://grep.app/search?q=ros.%2Asbcl.%2A--&regexp=true

ros -L sbcl -Q -l /root/.sbclrc run -- "$@"

# speedup (I haven't figured it out yet)
# https://fukamachi.hashnode.dev/day-4-roswell-how-to-make-roswell-scripts-faster
# ros -L sbcl -Q -m hello -l /root/.sbclrc run -- "$@"
