#!/bin/bash
export TTY

( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# https://grep.app/search?q=ros.%2Asbcl.%2A--&regexp=true

ros -L sbcl -Q -l /root/.sbclrc run -- "$@"
