#!/bin/bash
export TTY

# Installed through ros

script="/root/.roswell/lisp/quicklisp/setup.lisp"

bin=sbcl
# eval "rlwrap -H \"$histfile\" -f \"$compfile\" $bin --load \"$script\""
# rlwrap -H "$histfile" -f "$compfile" $bin --load "$script" "$@"

# bin_path=~/.roswell/bin/
# /root/.emacs.d/host/pen.el/scripts/ros-compile

$bin --load "$script" "$@"

# sbcl-ql replaces this:
# ;; #!sbcl --script
