#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/usr/bin/sc" || agi "sc" &>/dev/null

export TERM=xterm-256color

nvc /usr/bin/sc "$@"
# nvc -2 /usr/bin/sc "$@"
