#!/bin/bash
export TTY

# TODO Start by generating all the desired regexes for all
# bible references.

# sed -n 's/.*\(Psalms\?\)\( [0-9]\+\)\?\(:[0-9]\+\)\?.*/\1\2\3/p' | uniqnosort

input_fp="$(cat | tf txt)"
{
cat "$input_fp" | sed -n 's/.*\(Psalms\?\).*/\1/pI'
cat "$input_fp" | sed -n 's/.*\(Psalms\?\)\( [0-9]\+\)\?.*/\1\2/pI'
cat "$input_fp" | sed -n 's/.*\(Psalms\?\)\( [0-9]\+\)\?\(:[0-9]\+\)\?.*/\1\2\3/pI'
} | uniqnosort
rm "$input_fp"