#!/bin/bash
export TTY

# TODO Start by generating all the desired regexes for all
# bible references.

# $EMACSD/config/my-bible-mode.el
# $DUMP/tmp/scratch0Ppvf4.txt

# sed -n 's/.*\(Psalms\?\)\( [0-9]\+\)\?\(:[0-9]\+\)\?.*/\1\2\3/p' | uniqnosort

# cat $PENEL_DIR/src/pen-avy.el | scrape-bible-references

# I need to combine a lot of seds
# use sed's -f script-file

input_fp="$(cat | tf txt)"
{
cat "$input_fp" | sed -n 's/.*\(Psalms\?\).*/\1/pI'
cat "$input_fp" | sed -n 's/.*\(Psalms\?\)\( [0-9]\+\)\?.*/\1\2/pI'
cat "$input_fp" | sed -n 's/.*\(Psalms\?\)\( [0-9]\+\)\?\(:[0-9]\+\)\?.*/\1\2\3/pI'
} | uniqnosort
rm "$input_fp"