#!/bin/bash
export TTY

input_fp="$(cat | tf txt)"

title="$(cat "$input_fp" | perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si')"

if printf -- "%s\n" "$title" | grep -q -P '^Star$'; then
    title="$(cat "$input_fp" | perl -l -0777 -ne 'print $1 if /<meta property="og:title" content="\s*(.*?)\s*">/si')"
elif printf -- "%s\n" "$title" | grep -q -P ' - YouTube$'; then
    title="$(cat "$input_fp" | perl -l -0777 -ne 'print $1 if /<meta property="og:title" content="\s*(.*?)\s*">/si')"
    channel="$(cat "$input_fp" | xurls | scrape "http://www.youtube.com/@.*" | head -n 1 | cut -d "@" -f 2)"
    if test -n "$channel"; then
        title="$title (@$channel)"
    fi
fi

echo "$title"

rm "$input_fp"