#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

word="$1"

e -e "(dictionary-search $(aqf-nice "$word"))"

# wordnut "$@"
# /usr/bin/sdcv
# ifl define
