#!/bin/bash
export TTY

# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

# g  sh-arcatelier-go
# r  sh-arcatelier-rc
# F  sh-arcatelier-files
# I  arcatelier-get-issue-description
# J  arcatelier jargon

read -r -d '' options <<HEREDOC
.  EDIT
G  glossary.txt
o  zcd arcatelier
d  sh-arcatelier-dir
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear


    # w) cmd="list-wiki-files-below $MYGIT/fortescue-autonomy" ;;
    # r) cmd="sh-arcatelier-rc" ;;
    # F) cmd="sh-arcatelier-files" ;;
    # I) cmd="arcatelier-get-issue-description" ;;
    # J) cmd="vs $NOTES/ws/arcatelier/jargon.txt" ;;

case "$d" in
    .) cmd="v $0" ;;
    G) cmd="vs $HOME/notes/ws/arcatelier/glossary.txt" ;;
    o) cmd="zcd $NOTES/ws/arcatelier" ;;
    d) cmd="sh-arcatelier-dir" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
