#!/bin/bash
export TTY

# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
m  machine-learning
M  music
l  melee
e  emacs
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    m) cmd="CWD=$HOME/notes/ws/machine-learning zsh" ;;
    M) cmd="CWD=$HOME/notes/ws/music zsh" ;;
    l) cmd="CWD=$HOME/notes/ws/melee zsh" ;;
    e) cmd="CWD=$HOME/notes/ws/emacs zsh" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
