#!/bin/bash
export TTY

# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
p	localhost_scratch:perspective.org.0
HEREDOC

echo "sh-tmux-hydra" | udl | pen-hls green
echo "$options" | pen-hls dgrey

read -n1 d; test "$d" = "" && read -n1 d

# exec <`tm-tty`
# exec 1> /dev/tty
