#!/bin/bash
export TTY

# Don't put 'clear' here. When run from zsh, you don't really want
# to clear. Instead, put it before calling from elsewhere, i.e in sh-tmux
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
t  tabs file
r  sp $HOME/notes2018/ws/rest/scratch.restclient
f  sh-newfile
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    t) cmd="new-tabs-file" ;;
    r) cmd="sp $HOME/notes2018/ws/rest/scratch.restclient" ;;
    f) cmd="sh-newfile" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
