#!/bin/bash
export TTY

# This should return the path to the selection

# clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
,  zcd $HOME/sh-source
a  conda
p  pyenv
k  ghcup-env
K  sdkman -- for installing/using kotlin
z  pen-fzf
n  nix
o  fz-poetry-activate
HEREDOC

{
echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey
} 1>&2

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) {
        sph v "$0"
        cmd="echo"
    } ;;

    ,) {
        #exec <`tm-tty`
        #exec 1>&0
        #exec 2>&0
        cmd="cmd zcd $HOME/sh-source | tf sh"
        # eval "$cmd"
        # exit
    } ;;

    # a) cmd="printf -- "%s" $(cmd-nice-posix "$HOME/sh-source/conda-init")" ;;
    a) cmd="printf -- "%s" $(cmd-nice-posix "$HOME/sh-source/miniconda3.sh")" ;;
    p) cmd="printf -- "%s" $(cmd-nice-posix "$HOME/sh-source/pyenv.sh")" ;;
    k) cmd="printf -- "%s" $(cmd-nice-posix "$HOME/sh-source/ghcup-env")" ;;
    K) cmd="printf -- "%s" $(cmd-nice-posix "$HOME/sh-source/sdkman.sh")" ;;
    n) cmd="printf -- "%s" $(cmd-nice-posix "$HOME/sh-source/nix.sh")" ;;
    o) cmd="printf -- "%s" $(cmd-nice-posix "$SCRIPTS/fz-poetry-activate")" ;;
    z) cmd="find /home/shane/sh-source -maxdepth 1 \( -type f -o -type l \) | mnm | fzf" ;;
esac

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd" | pen-mnm
