#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# Use this inside vim inside org-mode
# e.g.
# echo "John 20:22" | shorg

. $SCRIPTS/lib/stdin_exists

{
if stdin_exists; then
    in-pen wrlp -E "nbd onelined decorated sh - | cat"
else
    in-pen nbd onelined decorated "$@" | cat
fi
} | pavs
