#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# Use this inside vim inside org-mode
# e.g.
# echo "John 20:22" | shorg

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

{
if stdin_exists; then
    awk1 | while IFS=$'\n' read -r line; do
    (
        exec 0</dev/null
        echo "$line" | nbd onelined decorated sh - | cat
    )
    done
else
    nbd onelined decorated "$@" | cat
fi
} | pavs
