#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# Use this inside vim inside org-mode
# e.g.
# echo "John 20:22" | shorg

awk1 | while IFS=$'\n' read -r line; do
(
    exec 0</dev/null
    echo "$line" | nbd onelined decorated sh - | cat
)
done