#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

fp="$1"
test -f "$fp" || exit 1

if test "$NO_SIXEL" = "y"; then
    win ie "$fp"
    exit
fi

# TODO Use imagemagick to give the image a background

convert_maybe_to_bw() {
    if pen-rc-test -f black_and_white; then
        pic-to-black-and-white "$@"
    else
        cat "$@"
    fi
}

if has-alpha-channel-p "$fp"; then
    input_fp="$(cat "$fp" | tf bin)"

    ans="$(qa -message "Image has alpha. Use:" \
              -b black-bg \
              -w white-bg \
              -c checkered-bg)"

    case "$ans" in
        black-bg) {
            cat "$input_fp" | pic-make-alpha-into-black | sponge "$input_fp"
            cat "$input_fp" | convert_maybe_to_bw | pic-convert-to-sixel
        } ;;
        white-bg) {
            cat "$input_fp" | pic-make-alpha-into-white | sponge "$input_fp"
            cat "$input_fp" | convert_maybe_to_bw | pic-convert-to-sixel
        } ;;
        checkered-bg) {
            # format="$(cat "$input_fp" | pic-get-format)"
            # geometry="$(cat "$input_fp" | pic-get-size)"
            cat "$input_fp" | pic-add-checkerboard | sponge "$input_fp"
            cat "$input_fp" | convert_maybe_to_bw | pic-convert-to-sixel
        } ;;
        *) ;;
    esac
else
    convert_maybe_to_bw "$fp" | convert /dev/stdin -geometry 800x480 -colors 16 sixel:- | less -rS
fi
