#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -ls) {
        ls=y
        shift
    }
    ;;

    *) break;
esac; done

# I need to supply the pid of the host script when calling show-fds, if I want to capture the result
# i.e. fds="$(show-fds "$$")"
pid="$1"
: "${pid:="$$"}"

if test "$ls" = "y"; then
    ls -la "/proc/$pid/fd" 2>/dev/null
else
    ls -la "/proc/$pid/fd" 2>/dev/null | grep -oP "[0-9]+ -> .*" | sed 's/ -> / /'
fi