#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null
# https://jakewharton.com/peeking-at-colorful-command-line-output/

# sed -r -e 's/\x0d/\\r/g' -e 's/\x1b\[/\\e\[/g'
sed -r -e 's/\x1b\[/\\e\[/g'