#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -ls) {
        ls=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$ls" = "y"; then
    ls -la /proc/$$/fd 2>/dev/null
else
    ls -la /proc/$$/fd 2>/dev/null | grep -oP "[0-9]+ -> .*" | sed 's/ -> / /'
fi