#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# e21 shx "$@"

. $PENEL_DIR/scripts/utils.sh

if stdin_exists; then
    ts -i '[%H:%M:%.S]'
else
    {
    exec 2>&1;
    export PS4='+	"$(basename $0)"	${LINENO}	 '
    if test -f "$1"; then
        bash -x "$@" 
    else
        "$@"
    fi
    } | ts -i '[%H:%M:%.S]'
fi