#!/bin/bash
export TTY

# example:
# ln -sf single-cmd-auto-pavs-2 dfh
# dfh

. $SCRIPTS/lib/hs

fsn="$(basename -- "$0")"

sn="${fsn:0:2}" 
paras="${fsn:2}" 

cmd "$sn" -"$paras" | awk 1 | hls red 1>&2
"$sn" -"$paras" | pavs
