#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# fp="$1"
# 
# if pl "$fp" | grep -i -q -P '\.md$'; then
#     ${GOPATH%%:*}/bin/slides "$@"
# else
#     ${GOPATH%%:*}/bin/slides "$@"
#     exit 1
# fi

${GOPATH%%:*}/bin/slides "$@"
