#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || go install -v github.com/noperator/sol/cmd/sol@latest &>/dev/null
 
${GOPATH%%:*}/bin/sol "$@"
