#!/bin/bash
export TTY

getinput() {
    if test -f "$1"; then
        cat "$1"
    else
        cat
    fi
}

lang="$(getinput "$@" | sp -aft +ooq "(buffer-language)" +e "(kill-buffer)" | cat)" 2>/dev/null
printf -- "%s\n" "$lang"