#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# 314 seems to be the number to make lolcat wheel around modulo
# for i in $(seq 1 314); do echo "$message"; done | lolcat -f

tput civis
message="$@"
: "${message:="LOADING..."}"

colourwheel="$(for i in $(seq 1 314); do echo "$message"; done | lolcat -f)"

i=1
while :; do
    colored="$(echo "$colourwheel" | awk 1 | sed -n "${i}p" )"
    # clear
    printf -- "%s" "[H"
    printf -- "%s" "[44m"
    printf -- "%s" "$colored" | sed -u 's=\(.\)\(\[38\)=\1[44m\1\2=g'

    i=$(( (i + 1) % 314 ))
    if test "$i" = 0; then
        i=1
    fi
    sleep 0.1
    # sleep 0.3
done
tput cnorm
