#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# Trap to kill subprocesses is almost useless here because the spinner is a
# popup

. $SCRIPTS/lib/stdin_exists

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -t) {
        TMUX_SPINNER=y
        shift
    }
    ;;

    -f) {
        export FORCE_NEW_TPOP=y
        shift
    }
    ;;

    *) break;
esac; done

if stdin_exists; then
    input="$(cat)"
    exec < <(printf -- "%s" "$input")
fi

if test "$FORCE_NEW_TPOP" = "y"; then
    tmux-close-popup
fi

# TODO Make the tmux spinner
if test "$TMUX_SPINNER" = "y"; then
    "$@"
    exit "$?"
fi

extraargs=()
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -b) {
        extraargs=( -b "${extraargs[@]}" )
        shift
    }
    ;;

    -time) {
        extraargs=( "$opt" "$2" "${extraargs[@]}" )
        shift
        shift
    }
    ;;

    -m) {
        message="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${message:="$1"}"

if pen-tm session-exists popup; then
    "$@"
    exit "$?"
fi

# 1 is the message and it's usually taken from the first
# command in the command arguments
spinner-start "${extraargs[@]}" -m "$message"
# spinner-start-emacs

"$@"
ret="$?"

spinner-stop
# spinner-stop-emacs
exit "$ret"