#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

exec 0</dev/null

test -d "/root/.pen/tmp" && : "${TMPDIR:="/root/.pen/tmp"}"
test -d "/tmp" && : "${TMPDIR:="/tmp"}"

client_tty="$(cat "$TMPDIR/spinner_client_tty.txt")"

if test -n "$client_tty"; then
    tmux popup -C -c "$client_tty"
else
    tmux popup -C
fi
tmux kill-session -t popup:
