#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# I should not always use pavs because sqlite has a ui
# e.g.
# cd "$PENELD/config/databases"; make-new-db emacs-operations

/usr/bin/sqlite3 -separator $'\t' "$@"

# | pavs
