#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# I should not always use pavs because sqlite has a ui
# e.g.
# cd "$PENELD/config/databases"; make-new-db emacs-operations

# https://stackoverflow.com/questions/5071601/how-do-i-use-regex-in-a-sqlite-query

/usr/bin/sqlite3 -separator $'\t' -cmd ".load /usr/lib/sqlite3/pcre.so" "$@"

# | pavs
