#!/bin/bash
export TTY

# Make sure to only use sshpass for websites like https://magneticscrolls.net/
# and not for anything where I do not want the password remembered

# Nevertheless, I disable the remembering of the passwords
# . $SCRIPTS/lib/hs

test -f "/usr/bin/sshpass" || agi "sshpass" &>/dev/null

/usr/bin/sshpass "$@"
