#!/bin/bash
export TTY

test -d "/root/.pen/tmp" && : "${TMPDIR:="/root/.pen/tmp"}"
test -d "/tmp" && : "${TMPDIR:="/tmp"}"

if test -f $TMPDIR/stdincap; then
    in="$(cat $TMPDIR/stdincap)"
    exec < <(printf -- "%s" "$in")
    rm -f $TMPDIR/stdincap
fi

"$@"
