#!/bin/bash
export TTY

: "${TMPDIR:="/root/.pen/tmp"}"
: "${TMPDIR:="/tmp"}"

if test -f $TMPDIR/stdincap; then
    in="$(cat $TMPDIR/stdincap)"
    exec < <(printf -- "%s" "$in")
    rm -f $TMPDIR/stdincap
fi

"$@"
