#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
    code="$(cat)"
else
    code="$1"
fi

test -n "$code" || exit
# code="${code#G}"

codes=(G25 G26 G40 G166 G225 G227 G228 G281 G286 G386 G746 G757 G758 G907 G1035
    G1080 G1110 G1258 G1411 G1781 G1785 G1799 G2198 G2222 G2424 G2588 G2730
    G2962 G2919 G2316 G2413 G2842 G3056 G3140 G3340 G3404 G3439 G3772 G3962
    G4102 G4151 G4982 G5087 G5204 G5368 G5457 G5479 G5485 G5547 G5590

    H1 H430 H410 H1121 H8544 H4687 H5921 H6440 H6942 H8034 H8130)
value="\<${code}\>"

if [[ ${codes[@]} =~ $value ]]; then

    if [[ $code =~ G.* ]]; then
        module=StrongsGreek
        code="${code#G}"
    else
        module=StrongsHebrew
        code="${code#H}"
    fi

    out="$(
"diatheke" "-b" "$module" "-o" "w" "-f" "internal" "-k" "$code" |
    sed -n 1p | sed 's/ \+/ /g' | cut -d ' ' -f 3
)"
printf -- "%s" "($out)"
fi
