#!/bin/bash
export TTY

# The purpose of this is, when executed, to show to the user
# how it was called. (sn, stdin, args)
#
# Example:
# nohup bash -c "echo hi | stub-showcmd 1 2 4"

. $SCRIPTS/lib/hs
. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    input="$(cat)"
fi

sn="$(basename -- "$0")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -bn) {
        bn="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

CMD="$(cmd "$@")"
: ${CMD:="$(cmd "$@")"}

{
    if test -n "$bn"; then
        echo "Stub script: $sn"
        echo "Invocation: $bn $CMD"
    else
        echo "Invocaton: $sn $CMD"
    fi
if test -n "$input"; then
    echo "Has stdin. Formatted in org:" | udl
    echo "$input" | pen-org-template-gen -basic text "stdin for {$sn $CMD}"
else
    echo "No stdin."
fi
} | intty -nw v
