#!/bin/bash
export TTY

if test "$(whoami)" = root && printf -- "%s\n" "$1" | grep -q -P '^-'; then
    "$@"
else
    export ISSUDO=y

    if test "$1 $2" = "apt update" && ! test "$3" = "--allow-unauthenticated"; then
        shift
        shift
        set -- apt update --allow-unauthenticated --allow-insecure-repositories "$@"
    fi

    /usr/bin/sudo "$@"
fi
