#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

test -f "/usr/local/bin/syn" || pyf "synonym-cli" &>/dev/null

/usr/local/bin/syn "$@" | {
    strip-ansi | 
    strip-unicode |
    sed 's/^\s*//' |
    sed '/^$/d' |
    sed '/thesaurus.com/d'
} | pavs
