#!/bin/bash

apostrophe "John Dee" "" "John Dee was an English mathematician, astronomer, astrologer, teacher, occultist, and alchemist. He was the court astronomer for, and advisor to, Elizabeth I, and spent much of his time on alchemy, divination and Hermetic philosophy. As an antiquarian, he had one of the largest libraries in England at the time."