#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f $HOME/.cargo/bin/taskwarrior-tui || cargo install taskwarrior-tui &>/dev/null

nvc $HOME/.cargo/bin/taskwarrior-tui "$@"
