#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# prepare taskwarrior, initial setup
# task rc.confirmation=off || echo 0

/usr/local/bin/task "$@"
