#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

dp=/root/repos/helmut/
fp=/root/repos/helmut/tcvt/tcvt.py
test -d "$dp"  || mkdir -p "$dp"
test -d "$dp/tcvt"  || {
    cd "$dp"
    git clone "git://git.subdivi.de/~helmut/tcvt.git" tcvt
}
test -f "$fp" || exit 1
python3.10 "$fp" "$@"
