#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# update-rust 

test -f $HOME/.cargo/bin/teetty || cargo install "teetty" &>/dev/null

export RUST_BACKTRACE=1

# showsize() {
#     ns `resize`
# }
# 
# # This seems to execute after teetty quits
# trap showsize SIGWINCH

$HOME/.cargo/bin/teetty "$@"
