#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# Connect to it like a server.
# mkrepl --in /tmp/stdin --out /tmp/stdout

# update-rust 

test -f $HOME/.cargo/bin/teetty || cargo install "teetty" &>/dev/null

export RUST_BACKTRACE=1

# showsize() {
#     ns `resize`
# }
# 
# # This seems to execute after teetty quits
# trap showsize SIGWINCH

$HOME/.cargo/bin/teetty "$@"
