#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f $HOME/.cargo/bin/termusic-server || cargo install "termusic-server" &>/dev/null

$HOME/.cargo/bin/termusic-server "$@"
