#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

. $SCRIPTS/lib/stdin_exists

# TODO Make an easy way to run this sed pipeline on only a part of the file
# Actually 'ved' might be good for this (vim sed)

if stdin_exists; then
    sed 's/^\s//' | sed 's/, \?/,/g' | sed 's/,$//' |
        sed 's/,/\n/g' | sort | sed 's/^/\t/' | sed 's/$/,/' |
        tee \
          >(grep -P -v '[#=]' > "$TMPDIR/terminfo-expand-first.txt") \
          >(grep '#' > "$TMPDIR/terminfo-expand-hash.txt") \
          >(grep '=' > "$TMPDIR/terminfo-expand-equals.txt") \
          > "$TMPDIR/terminfo-expand-all.txt"
    {
        cat "$TMPDIR/terminfo-expand-first.txt"
        cat "$TMPDIR/terminfo-expand-hash.txt"
        cat "$TMPDIR/terminfo-expand-equals.txt"
    } | pavs
elif test -f "$1"; then
    :
else
    echo "Please provide .ti file" | hls red 1>&2
    exit 1
fi
