#!/bin/bash

: "${AIX_API_KEY:="$PEN_LM_KEY"}"

if test -s $HOME/.pen/aix_api_key; then
    : "${AIX_API_KEY:="$(cat $HOME/.pen/aix_api_key)"}"
fi

test -n "$AIX_API_KEY" || {
    echo "AIX_API_KEY not given to script"
    exit 1
}

export AIX_API_KEY

if test -z "$PEN_N_COMPLETIONS" || test "$PEN_N_COMPLETIONS" -gt 4; then
    PEN_N_COMPLETIONS=4
fi

export PEN_PROMPT="#!/usr/bin/python3\n\nfrom"
export PEN_MODEL="GPT-J-6B"
export PEN_MIN_TOKENS=0
export PEN_MAX_TOKENS=409
export PEN_MIN_GENERATED_TOKENS=3
export PEN_MAX_GENERATED_TOKENS=50
export PEN_ENGINE_MIN_TOKENS=1
export PEN_ENGINE_MAX_TOKENS=2048
export PEN_ENGINE_MIN_GENERATED_TOKENS=1
export PEN_ENGINE_MAX_GENERATED_TOKENS=4096
export PEN_TEMPERATURE=0.3
export PEN_TOP_P=1.0
export PEN_TOP_K=10
export PEN_STOP_SEQUENCE="###"
export PEN_N_COMPLETIONS=5
export PEN_TRAILING_WHITESPACE

: "${PEN_N_COMPLETIONS:="4"}"

sedstop="$(printf -- "%s" "$PEN_STOP_SEQUENCE" | sed -z 's/\\/\\\\/g')"

# pen-aix.py "$@" | sed -z "s~${PEN_STOP_SEQUENCE}.*~~"

# Interestingly, AIx has this issue where the start of the response is stripped

pen_aix() {
    if printf -- "%s\n" "$PEN_FLAGS" | grep -q -P '<aix-begin-newline>'; then
        echo
    fi
    pen-aix.py "$@"
}

if test "$PEN_N_COMPLETIONS" = 1; then
    {
    printf -- "%s" "$PEN_PROMPT$PEN_TRAILING_WHITESPACE"
    pen_aix "$@" | pen-log aix-temp | sed -z "s~${sedstop}$~~"
    } | pen-log aix
else
    for i in $(seq 1 "$PEN_N_COMPLETIONS"); do
        echo "===== Completion $i ====="
        # The openai api will add the prompt. So emulate it
        {
        printf -- "%s" "$PEN_PROMPT$PEN_TRAILING_WHITESPACE"
        pen_aix "$@" | pen-log aix-temp | sed -z "s~${sedstop}$~~"
        } | awk 1
    done | pen-log aix
fi