#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/usr/local/bin/textual-paint" || pyf "textual-paint" &>/dev/null

/usr/local/bin/textual-paint "$@"
