#!/bin/sh

# This is a bash pipeline command for standardising a prompt
# Example:
# cat grammar-correction.prompt | tidy-prompt | pen-sponge grammar-correction.prompt

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    yq . | json2yaml
elif test -f "$1"; then
    cat "$1" | yq . | json2yaml | pen-sponge "$1"
fi
