#!/bin/bash
export TTY

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists; then
    yq . | json2yaml
elif test -f "$1"; then
    cat "$1" | yq . | json2yaml | sponge "$1"
fi
