#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f /usr/local/bin/tiv || (
    cd "$(gc "http://github.com/stefanhaustein/TerminalImageViewer")"
    make
    sudo make install
)

/usr/local/bin/tiv "$@"
