#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

test -f /usr/local/bin/tiv || (
    cd "$(gc "http://github.com/stefanhaustein/TerminalImageViewer")"
    make
    sudo make install
)

/usr/local/bin/tiv "$@"
