#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -m) {
        module="$2"
        shift
        shift
    }
    ;;

    # -kvj, -bsb, -nasb
    -*) {
        module="$(p "$opt" | pen-mcut -d- -f2)"
        shift
    }
    ;;

    *) break;
esac; done

case "$sn" in
    tm-bible-book) {
        if is_tty; then
            : "${book:="$1"}"
            : "${book:="$(list-bible-books | mfz -num -nv)"}"
            if test -z "$book"; then
                exit
            fi
        else
            book=Genesis
        fi
    }
    ;;

    *)
        book="$sn"
esac

book="$(printf -- "%s" "$book" | sed 's/^tm-//')"
: "${book:="Romans"}"

nchapters="$(get-bible-book-chapter "$book")"

test -n "$nchapters" || exit

: "${module:="nasb"}"

# if test "$nchapters" = "1"; then
#     "$module $book $i | cvs"
#     exit
# fi

for i in $(seq 1 $nchapters); do
    name="$(printf -- "%s\n" "$book" | tr '\n' ' ' | sed 's/ $//') $i"
    tmux neww -n "$name" "$module $book $i | cvs"
done

for i in $(seq $nchapters -1 1); do
    tmux previous-window
done

tmux next-window
