#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -t) {
        delay="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

input_fp="$(0</dev/null tf txt)"

if stdin_exists; then
    awk 1 > "$input_fp"
fi

if test "$#" -gt 0; then
    # cmd-nice "$@" >> "$input_fp"
    printf -- "%s\n" "$@" >> "$input_fp"
fi

slug="$(cat "$input_fp" | tr '\n' ' ' | sed 's/ $//' | cut -c -30)"

# I could technically animate the notifications
: "${delay:="10"}"
paneid="$(tmux neww -P -d -n "N($delay:${slug})" "cat $input_fp; sleep $delay")"

tmux setw -t "$paneid" window-status-format '#[bg=colour237]#[fg=colour240]#I #F#[bg=colour237]#[fg=colour250]#W'
