#!/bin/bash
export TTY

: "${TMUX_PANE:="$(tmux-pane-id)"}"
export TMUX_PANE

dn="$1"
bn="$(basename "$dn")"

# New window with a new session - reattachable
tm -d -te nw -hlgreen -R -nopakf -n "$bn" -c "$CWD" REPEAT_COMMAND=y tm ns -ah -hlred -r -l -s -c "$dn"