#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

: "${window_id:="$1"}"
: "${window_id:=$(tmux display-message -p '#{window_id}')}"

# This should

# - firstly need a command which wraps a pane in a tmux inside a new window?
# Yeah, I probably need to do that.
# - do it inside a new tmux session? I need to, I think.
# - but I still have to rely on linking the pane. I can't link a pane with tmux, sadly.
# - I have to link the entire window

TMUX= tmux new-window "tmux-attach-window $window_id"