#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/root/local/bin" && : "${bin:="/root/local/bin"}"
test -f "/usr/bin/tmux" && : "${bin:="/usr/bin/tmux"}"
"$bin" "$@"
