#!/bin/bash
export TTY

tmux source /root/.emacs.d/host/pen.el/config/tmux-colour.conf

# This works, but I also need to select and unselect them to make them update
tmux list-windows | rev | s field 1 | grep @ | rev | awk1 | while IFS=$'\n' read -r window_id; do
    tmux setw -t "$window_id" window-status-format "#[fg=colour081]#I #[fg=colour075]#W"
done