#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

: "${date:="$(date +%d.%m.%y)"}"
export EXTRA_METADATA="${EXTRA_METADATA}_${date}"

echo "EXTRA_METADATA:$EXTRA_METADATA" 1>&2
"$@"
