#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

. $PENELD/scripts/utils.sh

test -d ~/repos/figlet-fonts && cd ~/repos/figlet-fonts
test -d ~/figlet-fonts && cd ~/figlet-fonts

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -w) {
        cols="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${cols:="$COLUMNS"}"
: "${cols:="80"}"

if test "$#" -eq 0; then
    if ! test "$istty_stderr" = 0; then
        tpop -E "figlet -w "$cols" | cat" | cat
        exit "$?"
    fi

    if ! stdin_exists; then
        exec < <(readln input)
    fi

    input="$(cat)"

    font="$(0</dev/null ls | nonvc mfz -P -po "up:80%" -pscript "echo $(aqf-nice "$input") | /usr/bin/figlet -w "$cols" -f {} | lolcat -f ")"

    # TODO Make it so the font is previewed in fzf

    CMD="$(cmd "$@")"
    : ${CMD:="$(cmd "$@")"}

    finalcmd="printf -- \"%s\" $(aqf "$input") | figlet -w "$cols" -t -f \"$font\" $CMD"


    if test "$isstdoutpipe" = 0; then
        eval "$finalcmd" | cat
    else
        printf -- "%s\n" "$finalcmd" | xc -n | vimcat 1>&2
        eval "$finalcmd" | lolcat 1>&2
    fi

    exit "$?"
fi

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -h) {
        do_help=y
        shift
    }
    ;;

    *) break;
esac; done

if test "$do_help" = "y"; then
    /usr/bin/figlet -h | pavs

    exit "$?"
fi

unicode-to-ascii | /usr/bin/figlet -w "$cols" "$@"
