#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

fp="$1"
shift

if { ! stdin_exists; } && test -n "$fp"; then
    cmd_prefix+="cat $(aqf "$fp") | "
fi

rtcmd "+/\(\"\.\)\@<=\"" -E "$cmd_prefix remarshal -if toml -of yaml | yq -r \".\" | vi -"
