#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# . $SCRIPTS/lib/hs

# tpop -nos -h 5 sout yn "$@"

message="$@"
# Remove trailing spaces
message="$(printf -- "%s" "$message" | s remove-trailing-whitespace)"
len=${#message} 
shortest_len=21
if test "$len" -lt "$shortest_len"; then
    len="$shortest_len"
fi

tpop -nos -w "$(( len + 4 ))" -h 7 sout yn -cl "$message"