#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -r) {
        reverse=y
        shift
    }
    ;;

    *) break;
esac; done

. $SCRIPTS/lib/stdin_exists

key="$1"
test -n "$key" || exit 1
shift

if ! stdin_exists; then
    last_arg="${@: -1}"

    if ! test -f "$last_arg"; then
        exit 1
    fi

    exec < <(cat "$last_arg")
fi

# awk -F"\t" "/$key/{print \$2}"

if test "$reverse" = "y"; then
    awk -F"\t" -v key="$key" "\$2 == key { print \$1; }"
else
    awk -F"\t" -v key="$key" "\$1 == key { print \$2; }"
fi

# Regex
# awk -F"\t" -v key="$key" "\$1 ~ key { print \$2; }"
