#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

test "$#" -gt 0 && last_arg="${@: -1}"

if stdin_exists; then
    tsv2csv.py "$@" | /usr/bin/dos2unix
elif test "$#" -gt 0 && test -f "$last_arg"; then
    cat "$last_arg" | tsv2csv.py "$@" | /usr/bin/dos2unix
fi

