#!/bin/bash
export TTY

# This is to be used like `man`

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

opt="$1"
shift
case "$opt" in
    m4) {
        "https://mbreen.com/m4.html"
    }
    ;;

    template) {
        :
    }
    ;;

    *)
esac
 