#!/bin/bash
export TTY

# This is to be used like `man`.
# Actually, in 'man' I should first check to see if there is a 'tut' and then ask what I want to do.

# . $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -q) {
        # Query if a tut exists
        query=y
        shift
    }
    ;;

    *) break;
esac; done

opt="$@"

hastut() {
    if test "$query" = "y"; then
        echo "Tutorial for ${opt} exists." | hls blue 1>&2
        :
        exit "$?"
    else
        "$@"
        exit "$?"
    fi
}

notut() {
    if test "$query" = "y"; then
        false
        exit "$?"
    else
        "$@"
        exit "$?"
    fi
}

case "$opt" in
    m4) {
        hastut eww "https://mbreen.com/m4.html"
    }
    ;;

    *) {
        notut man "$@"
    }
    ;;
esac