#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

# Like tv but handles many

# Without stdin,
# - open a ranger to a new temporary directory, based on the name/slugified arguments

# With stdin,
# - make a new tempfile inside the temporary directory containing the stdin

slug="$(printf -- "%s\n" "$@" | tr '\n' ' ' | sed 's/ $//' | slugify | cut -c -50)"

. $SCRIPTS/lib/stdin_exists

if stdin_exists; then
    :
fi
