#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || go install github.com/maaslalani/typer@latest &>/dev/null

${GOPATH%%:*}/bin/typer "$@"
