#!/bin/bash
export TTY

# If this breaks because of expect not being available, it might be because anaconda tclsh8.6 is in the path
# This maybe because of the gnome-terminal default command

# TODO: make it execute the arguments while clearing stderr
# Because by default unbuffer mixes stderr into stdout

# This is an important option used by tm-unbuffer

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: ${CMD:="$(cmd "$@")"}

/usr/bin/unbuffer bash -c "$CMD" 2>/dev/null
