#!/bin/bash
export TTY

a=()
for arg in "$@"; do case "$arg" in
    -*) {
        a+="$arg"
        shift
    }
    ;;
    *) break ;;
esac; done

/usr/bin/unbuffer "${a[@]}" env -S IN_UNBUFFER=y "$@"
