#!/bin/bash
export TTY

# https://www.baeldung.com/linux/sync-files-continuously-one-way
# https://www.baeldung.com/linux/synchronize-linux-directories/

. $SCRIPTS/lib/hs

test -f /usr/bin/unison || agi unison &>/dev/null

/usr/bin/unison "$@"
