#!/bin/bash
export TTY

url="$1"

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists && ! test -n "$url"; then
    url="$(cat)"
fi

curl-firefox -s -I "$url" | grep -q "HTTP.*200"