#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

opt="$1"
shift
case "$opt" in
    pen-emacsd-*) {
        export SOCKET="$opt"
    }
    ;;

    pen[0-9]*) {
        opt="$(p "$opt" | sed 's/^pen//')"
        export SOCKET="pen-emacsd-$opt"
    }
    ;;

    nvlinks|browsh|elinks|w3m|ew3m|eww|nvw3m) {
        export BROWSER="$opt"
    }
    ;;

    *)
esac

if test "$#" -eq 0; then
    zsh
else
    "$@"
fi
