#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

test -f "/usr/bin/valgrind" || agi "valgrind" &>/dev/null

nvt -pak /usr/bin/valgrind "$@"
