#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# Examples:
# - vertify sed "$@"
# - vertify perl "$@"

transpose-characters.sh | "$@" | transpose-characters.sh