#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

fp="$1"
test -f "$fp" || exit 1

rp="$(realpath "$fp")"
fn=$(basename -- "$fp")
dn=$(dirname "$fp")
ext="${fn##*.}"
mant="${fn%.*}"

slug="$(printf -- "%s\n" "$fn" | tr '\n' ' ' | sed 's/ $//' | slugify)"

dir="$(td "book_$slug")"

unzip -d "$dir" "$rp" &>/dev/null || exit 1
zcd "$dir"
exit

cd "$dir"

# This is the order
cat OEBPS/content.opf |
    grep "<itemref " |
    grep -o "\"[^\"]\+\"" |
    urldecode | uq -l |
        pavs

# This is an alist of file path to id
cat OEBPS/content.opf |
    grep "<item " |
    grep -o "\"[^\"]\+\" id=\"[^\"]\+\"" |
    urldecode | sed 's/^"\([^"]\+\)" id="\([^"]\+\)"/\2\t\1/' |
    grep -P ".xhtml$" |
        pavs

test -d "$dir" && rm -rf "$dir"
