#!/bin/bash
export TTY
export DISPLAY

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

# Do this to remove the annoying message from vim
if stdin_exists; then
    IFS= read -rd '' contents < <(cat);typeset -p contents &>/dev/null
    if test -n "$contents"; then
        printf -- "%s" "$contents" | /usr/bin/vim "$@"
    fi
else
    /usr/bin/vim "$@"
fi
