#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

## vim already has a black and white mode which might be useful,
## so don't disable it with cat

if pen-rc-test -f black_and_white; then
    export BLACK_AND_WHITE="y"

    # TODO Implement 'rev' for AnsiHighlight
    # since it seems that vimcat isn't outputting it
fi

if pen-rc-test -f black_and_white; then
    # Do this especially if INSIDE_EMACS
    export TERM=screen-2color
    extra_commands+="|call BWSyntax()"
else
    extra_commands+="|call GeneralSyntax()"
fi

infp="/tmp/vimcat-in-$$"
outfp="/tmp/vimcat-out-$$"

cat > "$infp"

# The -c here used to be a --cmd. It seems that
# that is why ansivim had stopped working,
# because --cmd stopped working
unbuffer vim -E -X -R -i NONE -c "silent! echo$extra_commands" "$@" -c "visual | call AnsiHighlight(\"$outfp\") | q" -- "$infp" &>/dev/null

cat "$outfp" | (
    if test "$BLACK_AND_WHITE" = "y"; then
        cat

        # Just remove it?
        # sed 's=\[22;24;25;27;28;39;48;5;236m==g' |
        # sed 's=\[22;24;25;27;28;39;49m==g'
    else
        # normal text colour
        sed 's=\[22;24;25;27;28;39;48;5;236m=[22;24;25;27;28;38;5;60;49;48;5;236m=g' |
        sed 's=\[22;24;25;27;28;39;49m=[22;24;25;27;28;38;5;60;49m=g'
    fi
)
