#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# This is great for opening xls files
# With multiple sheets.

pen-python /usr/local/bin/vd "$@"
