#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# vertical sed
# ------------
# example:
# cat `which vsed` | vsed 's/bo/__/g' | pavs

transpose-characters.sh | sed "$@" | transpose-characters.sh

