#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -e) {
        EDITOR="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${EDITOR:="v -ac -nsl"}"

export EDITOR

vipe "$@"
