#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -e) {
        EDITOR="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: "${EDITOR:="v -ac -nsl"}"

export EDITOR

vipe "$@"
