#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# github author/repo may need adjustment
test -f "${GOPATH%%:*}/bin/up" || go install github.com/antonmedv/walk@latest &>/dev/null

# nvc env EDITOR="zrepl -0 xc -P" ${GOPATH%%:*}/bin/walk "$@"
nvt env EDITOR="zcdf" ${GOPATH%%:*}/bin/walk "$@"
# nvt env EDITOR="cmdv" ${GOPATH%%:*}/bin/walk "$@"
