#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

bin=/usr/local/bin/wayback_machine_downloader 
test -f "$bin" || { 
    gem install wayback_machine_downloader
}
test -f "$bin" || exit

cd /root/.pen/documents/websites

"$bin" "$@"

# Follow up with converting to text
# htmls2txt -p "index.php*"
