#!/bin/bash
export TTY

sn="$(basename -- "$0")"

# Also see: displayopts

# TODO Consider serialising many variables into an environment variable

# . $SCRIPTS/lib/hs

case "$sn" in
    wo|withopts) {
        :
    }
    ;;

    *) {
        withopts "$sn" -- "$@"
        exit "$?"
    }
    ;;
esac

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;

    --) {
        shift
        break
    }
    ;;

    *) {
        shift

        case "$opt" in
            debug) {
                export DEBUG=y
            }
            ;;

            van|vanilla) {
                export VANILLA=y
            }
            ;;

            nov|novan|novanilla) {
                export VANILLA=n
            }
            ;;

            nbd|nobd) {
                export BORDER=n
            }
            ;;

            onelined) {
                export ONELINED=y
            }
            ;;

            decorated) {
                export DECORATED=y
            }
            ;;

            detailed) {
                export DETAILED=y
            }
            ;;

            columnated) {
                export COLUMNATED=y
            }
            ;;

            manually) {
                export DO_MANUAL_TOUCHUP=y
            }
            ;;

            batch) {
                export DO_BATCH=y
            }
            ;;

            nup) {
                export UPDATE=n
                export FORCE_RETRY=n
            }
            ;;

            -2|bw|baw) {
                export BLACK_AND_WHITE=y
            }
            ;;

            # Can't use -no2 to represent b&w because no2 disables stderr
            nobw) {
                export BLACK_AND_WHITE=n
            }
            ;;

            as|das|autostart) {
                export NO_AUTO_START=n
            }
            ;;

            screen-2color) {
                export TERM=screen-2color
            }
            ;;

            nas|noautostart) {
                export NO_AUTO_START=y
            }
            ;;

            fast) {
                export FAST=y
            }
            ;;

            gui) {
                export PREFER_GUI=y
            }
            ;;

            tui) {
                export PREFER_GUI=n
            }
            ;;

            nem|noem) {
                export NOEMACS=y
            }
            ;;

            nnv|nonvc) {
                export NO_NVC=y
            }
            ;;

            nci|noci) {
                export NO_CI=y
            }
            ;;

            nrl|norl) {
                export NO_RL=y
            }
            ;;

            sth) {
                export SSH_HOST_ALLOWED=y
            }
            ;;

            nsth|nosth) {
                export SSH_HOST_ALLOWED=n
            }
            ;;

            *) {
                echo Unknown option "'$opt'" | hls red 1>&2
            }
            ;;
        esac
    }
    ;;

    *) break;
esac; done

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty && test "$#" -eq 0; then
    zsh
else
    "$@"
fi
