#!/bin/sh

# While Read Line Pipe
# --------------------
# This script is a lot like xargs
# awk 1 is used to ensure that input and output text finishes with a newline

CMD="$(cmd "$@")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

# newline
IFS="
"

awk 1 | {
    while IFS="$IFS" read -r line; do
        (
            exec 0</dev/null
            if test -n "$line"; then
                if test "$DEBUG" = "y"; then
                    printf -- "%s" "$line" 1>&2
                fi

                printf -- "%s" "$line" | eval "$CMD" | awk 1
            else
                echo
            fi
        )
    done
}
