#!/bin/sh

# While Read Line Pipe
# --------------------
# This script is a lot like xargs
# awk 1 is used to ensure that input and output text finishes with a newline

CMD="$(cmd "$@")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

awk 1 | {
    while IFS=$'\n' read -r line; do
        if test -n "$line"; then
            printf -- "%s" "$line" | eval "$CMD" | awk 1
        else
            echo
        fi
    done
}
