#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# e:pdflatex

test "$#" -gt 0 && last_arg="${@: -1}"

if test -f "$last_arg"; then
    test "$#" -gt 0 && set -- "${@:1:$(($#-1))}" # shift last arg
    sed -i "s/\\\\begin{tabular}{ll}/\\\\begin{tabular}{p{0.45\\\\linewidth} | p{0.45\\\\linewidth}}/" "$last_arg"
    sed -i "s/\\\\begin{tabular}{lll}/\\\\begin{tabular}{p{0.30\\\\linewidth} | p{0.30\\\\linewidth} | p{0.30\\\\linewidth}}/" "$last_arg"
    sed -i "s/\\\\begin{tabular}{llll}/\\\\begin{tabular}{p{0.23\\\\linewidth} | p{0.23\\\\linewidth} | p{0.23\\\\linewidth} | p{0.23\\\\linewidth}}/" "$last_arg"

    /usr/bin/xelatex -interaction nonstopmode "$@" "$last_arg"
    exit "$?"
fi

/usr/bin/xelatex "$@"
