#!/bin/bash
export TTY

unset TMUX
unset PEN_TMUX
unset TMUX_PANE

. $SCRIPTS/lib/hs

# vt340 has sixel

test -f "/usr/local/bin/xterm" && : "${bin:="/usr/local/bin/xterm"}"
test -f "/usr/bin/xterm" && : "${bin:="/usr/bin/xterm"}"

"$bin" -ti vt340 "$@"
