#!/bin/bash
export TTY

# set -xv

: "${UP:="y"}"
: "${DOWN:="y"}"
: "${EXTENDED_MODE:="n"}"
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -u) {
        DOWN=n
        UP=y
        shift
    }
    ;;

    -d) {
        DOWN=y
        UP=n
        shift
    }
    ;;

    -x) {
        EXTENDED_MODE=y
        shift
    }
    ;;

    -r) {
        RIGHT=y
        shift
    }
    ;;

    *) break;
esac; done

# A right click is an up without a down in non-extended mode
if test "$RIGHT" = "y" && ! test "$EXTENDED_MODE" = y; then
    DOWN=n
    UP=y
fi

x="$1"; : ${x:="1"}
y="$2"; : ${y:="1"}

if [ -n "$3" ]; then
    TTY="$3"
fi

: ${TTY:="$(tty)"}

pen-chr () {
	printf "\\$(printf '%03o' "$1")"
}

if test "$EXTENDED_MODE" = "y"; then
    leftnum=0
    rightnum=2

    # left-up is 0...m
    # left-down 0...M
    # right-up is 2...m
    # right-down doesn't exist

    x="$(( x + 1))"
    y="$(( y + 1))"

    if test "$RIGHT" = "y"; then
        # mousedown_code=""
        # This is needed for pen inside host tmux
        mousedown_code="$(echo -n -e "\e[<$rightnum"; printf -- "%s" ";$x;${y}M")"
        mouseup_code="$(echo -n -e "\e[<$rightnum"; printf -- "%s" ";$x;${y}m")"
    else
        mousedown_code="$(echo -n -e "\e[<$leftnum"; printf -- "%s" ";$x;${y}M")"
        mouseup_code="$(echo -n -e "\e[<$leftnum"; printf -- "%s" ";$x;${y}m")"
    fi

else
    # j:xterm-mouse--read-number-from-terminal

    x="$(pen-chr $(( 33 + $x )) )"
    y="$(pen-chr $(( 33 + $y )) )"
    mousedown="$(pen-chr 32)" # ' '
    mouseup="$(pen-chr 35)" # '#'

    mousedown_code="$(echo -n -e "\e[M$mousedown"; printf -- "%s" "$x$y")"
    mouseup_code="$(echo -n -e "\e[M$mouseup"; printf -- "%s" "$x$y")"
fi

if test "$UP" = "n"; then
    code="$mousedown_code"
elif test "$DOWN" = "n"; then
    code="$mouseup_code"
else
    code="$mousedown_code$mouseup_code"
fi

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if is_tty; then
    printf -- "%s" "$code" | showansi | hls purple
else
    printf -- "%s" "$code"
fi