#!/bin/bash
export TTY

# See also Y

( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

term="$@"

odn orspe -e "(goto-glossary-definition $(cmd-nice-posix "$term"))"
