#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# Execute this?

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: ${CMD:="$(cmd "$@")"}

wd="$(pwd)"
yn "execute this in '$wd'?\n\n$CMD" && eval "$CMD"
