#!/bin/bash
export TTY

sn="$(basename -- "$0")"

case "$sn" in
    zcdf) {
        do_zreplf=y
    }
    ;;

    *)
esac

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -f|-zreplf) {
        do_zreplf=y
        shift
    }
    ;;

    *) break;
esac; done

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

fp="$1"
: ${fp:="$(pwd)"}

if test "$fp" = "/"; then
    dn="/"
else
    dn="$(p "$fp" | pen-ux dn | pen-ux rp)"
fi

if is_tty; then
    if test "$do_zreplf" = "y"; then
        rp="$(realpath "$fp")"
        fn=$(basename -- "$rp")
        dn=$(dirname "$rp")
        ext="${fn##*.}"
        mant="${fn%.*}"

        zrepl -cd "$dn" -0 "$fn"
    else
        CWD="$dn" zsh
    fi
else
    echo "$dn"
fi
