#!/bin/bash

# z-repl "raco pkg install "

# use "x"

sn="$(basename "$0")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    -cm) {
        cm=y
        shift
    }
    ;;

    *) break;
esac; done

case "$sn" in
    zre) {
        CMD="$1"
    }
    ;;

    zrs) {
        CMD="$1 "
    }
    ;;

    *) {
        : ${CMD:="$(cmd-nice-posix "$@")"}
    }
    ;;
esac

# cmd="$@"

tf_command="$(pen-ux tf command)"
trap "rm \"$tf_command\" 2>/dev/null" 0

printf -- "%s" "$CMD " >> "$tf_command"

: "${CWD:="$(pwd)"}"

if test "$cm" = "y"; then
    CWD="$CWD" pen-x -c l -sf "$tf_command" -c m -i
else
    CWD="$CWD" pen-x -c l -sf "$tf_command" -i
fi