cd /root/notes;  "termdbms" "-p" "/tmp/zshbdhrtj" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "-p" "/tmp/zshJTMdlg" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "-p" "/tmp/tf_temp_fdf07c52ad.csv" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "-p" "/tmp/tf_temp_25af2dccaa.csv" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "-p" "/root/.pen/cross_references.csv" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "/root/.pen/refs.db" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "-p" "/root/.pen/refs.db" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "-p" "/root/.pen/refs.db" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "-p" "/root/.pen/refs.db" "#" "<==" "zsh"
cd /root/notes;  "termdbms" "-p" "/root/.pen/refs.db" "#" "<==" "zsh"
