#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# ggh -q "select .* from .*" -r -flang SQL

: "${n:="1"}"
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -n) {
        n="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

# pip3.10 install requests

ocif python3.10 "$(which grepgithub.py)" "$@" -n "$n" -m | pavs
