#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

# pip3.10 install bs4
# pip3.10 install html5lib
# pip3.10 install lxml

# python3.10 $HOME/repos/popovicn/grepgithub/grepgithub.py "$@" | strip-ansi | pavs
python3.10 $HOME/repos/popovicn/grepgithub/grepgithub.py -m -json -q "$@" | strip-ansi | pavs
