cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Colossians" "3:23-24" "#" "<==" "zsh"
cd /;  "Colossians" "3:23-24" "#" "<==" "zsh"
cd //;  "Colossians" "3:23-25" "#" "<==" "zsh"
cd //;  "Colossians" "3:22-25" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Colossians" "1:10" "#" "<==" "zsh"
