cd /;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/container;  "docker" "image" "ls" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--filter" "dangling=true" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "volume" "ls" "--format=[{{ json .Name }},{{ json .Driver }},{{ json .Name }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "context" "ls" "--format=[{{ json .Name }},{{ json .Name }},{{ json .Description }},{{ json .DockerEndpoint }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "container" "ls" "--all" "--format=[{{ json .Names }},{{ json .ID }},{{ json .Image }},{{ json .Command }},{{ json .CreatedAt }},{{ json .Status }},{{ json .Ports }},{{ json .Names }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "image" "ls" "--format=[[{{ json .Repository }},{{ json .Tag }},{{ json .ID }}],{{ json .Repository }},{{ json .Tag }},{{ json .ID }},{{ json .CreatedAt }},{{ json .Size }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "docker" "network" "ls" "--format=[{{ json .ID }},{{ json .ID }},{{ json .Name }},{{ json .Driver }},{{ json .Scope }}]" "#" "<==" "emacs"
