cd /volumes/home/shane/var/smulliga/source/git/neovim/neovim;  "nvim" "/volumes/home/shane/var/smulliga/source/git/neovim/neovim/.git-blame-ignore-revs" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/neovim/neovim;  "nvim" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/neovim/neovim;  "nvim" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/neovim/neovim;  "nvim" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/neovim/neovim;  "nvim" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/config/nvim;  "nvim" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/config/nvim;  "nvim" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/config/nvim;  "nvim" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/config/nvim;  "nvim" "/etc/host" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/config/nvim;  "nvim" "/etc/hosts" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/config/nvim;  "nvim" "/root/.vimrc" "#" "<==" "zsh"
cd /root/notes;  "nvim" "#" "<==" "zsh"
cd /root/.pen/documents/devotionals;  "nvim" "-u" "/root/.nvimrc" "-c" "call TermAndQuit(\" 'ncdu' '.'\")" "-c" "call GeneralSyntax()" "-c" "call NumberSyntax()" "-c" "normal\! i" "#" "<==" "pen-nvc"
cd /root/.pen/documents/devotionals;  "nvim" "-u" "/root/.nvimrc" "-c" "call TermAndQuit(\" 'ncdu' '.'\")" "-c" "call GeneralSyntax()" "-c" "call NumberSyntax()" "-c" "normal\! i" "#" "<==" "pen-nvc"
cd /root/.pen/documents/devotionals;  "nvim" "-u" "/root/.nvimrc" "-c" "call TermAndQuit(\" 'ncdu' '.'\")" "-c" "call GeneralSyntax()" "-c" "call NumberSyntax()" "-c" "normal\! i" "#" "<==" "pen-nvc"
