;;; matlab-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cedet-matlab.el

(autoload 'matlab-cedet-setup "cedet-matlab" "\
Setup support for CEDET tools for use with MATLAB." t)


;;; Generated autoloads from company-matlab-shell.el

(autoload 'company-matlab-shell "company-matlab-shell" "\
A `company-mode' completion backend for `matlab-shell'.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-matlab-shell" '("company-matlab-shell-"))


;;; Generated autoloads from linemark.el

(autoload 'enable-visual-studio-bookmarks "linemark" "\
Bind the viss bookmark functions to F2 related keys.
\\<global-map>
\\[viss-bookmark-toggle]     - To=ggle a bookmark on this line.
\\[viss-bookmark-next-buffer]   - Move to the next bookmark.
\\[viss-bookmark-prev-buffer]   - Move to the previous bookmark.
\\[viss-bookmark-clear-all-buffer] - Clear all bookmarks." t)
(register-definition-prefixes "linemark" '("linemark-" "viss-bookmark-"))


;;; Generated autoloads from matlab.el

(autoload 'matlab-is-matlab-file "matlab" "\
Enter `matlab-mode' when file content looks like a MATLAB *.m
file or for empty files *.m files when `matlab-mode-for-new-mfiles'
indicates as such.")
(add-to-list 'magic-mode-alist '(matlab-is-matlab-file . matlab-mode))
(autoload 'matlab-mode "matlab" "\
MATLAB(R) mode is a major mode for editing MATLAB dot-m files.
\\<matlab-mode-map>
Convenient editing commands are:
 \\[matlab-comment-region]   - Comment/Uncomment out a region of code.
 \\[matlab-fill-comment-line] - Fill the current comment line.
 \\[matlab-fill-region] - Fill code and comments in region.
 \\[matlab-complete-symbol]   - Symbol completion of matlab symbolsbased on the local syntax.

Convenient navigation commands are:
 \\[matlab-beginning-of-command]   - Move to the beginning of a command.
 \\[matlab-end-of-command]   - Move to the end of a command.

Convenient template insertion commands:
 \\[tempo-template-matlab-function] - Insert a function definition.
 \\[tempo-template-matlab-if] - Insert an IF END block.
 \\[tempo-template-matlab-for] - Insert a FOR END block.
 \\[tempo-template-matlab-switch] - Insert a SWITCH END statement.
 \\[matlab-insert-next-case] - Insert the next CASE condition in a SWITCH.
 \\[matlab-insert-end-block] - Insert a matched END statement.  With optional ARG, reindent.
 \\[matlab-stringify-region] - Convert plain text in region to a string with correctly quoted chars.

Variables:
  `matlab-indent-level'         Level to indent blocks.
  `matlab-continuation-indent-level' Level to indent after ... continuation
  `matlab-case-indent-level'            Level to unindent case statements.
  `matlab-indent-past-arg1-functions'
                                Regexp of functions to indent past the first
                                  argument on continuation lines.
  `matlab-maximum-indents'      List of maximum indents during lineups.
  `matlab-comment-column'       Goal column for on-line comments.
  `fill-column'                 Column used in auto-fill.
  `matlab-indent-function-body' If non-nil, indents body of MATLAB functions.
  `matlab-functions-have-end'   If non-nil, MATLAB functions terminate with end.
  `matlab-fill-code'            Non-nil, auto-fill code in auto-fill-mode.
  `matlab-fill-strings'         Non-nil, auto-fill strings in auto-fill-mode.
  `matlab-verify-on-save-flag'  Non-nil, enable code checks on save.
  `matlab-vers-on-startup'      If t, show version on start-up.
  `matlab-handle-simulink'      If t, enable simulink keyword highlighting.

All Key Bindings:
\\{matlab-mode-map}

(fn)" t)
(register-definition-prefixes "matlab" '("gud-matlab-debug-active" "matlab-" "ml-fl-anchor-limit"))


;;; Generated autoloads from matlab-cgen.el

 (autoload 'matlab-insert-map-fcn "matlab-cgen" "Keymap for C-c C-c in matlab-mode" t 'keymap)
(autoload 'matlab-generate-latex "matlab-cgen" "\
Convert a MATLAB M file into a Latex document for printing.
Author: Uwe Brauer oub@eucmos.sim.ucm.es
Created: 14 Feb 2002" t)
(register-definition-prefixes "matlab-cgen" '("matlab-"))


;;; Generated autoloads from matlab-compat.el

(register-definition-prefixes "matlab-compat" '("matlab-"))


;;; Generated autoloads from matlab-complete.el

(autoload 'matlab-property-function "matlab-complete" "\
Regexp of all builtin functions that take property lists." nil t)
(autoload 'matlab-complete-symbol "matlab-complete" "\
Complete a partially typed symbol in a MATLAB mode buffer.

(fn &optional ARG)" t)
(register-definition-prefixes "matlab-complete" '("matlab-"))


;;; Generated autoloads from matlab-maint.el

(autoload 'matlab-maint-minor-mode "matlab-maint" "\
Minor mode for matlab-mode maintainrs.

This is a minor mode.  If called interactively, toggle the
`Matlab-Maint minor mode' mode.  If the prefix argument is
positive, enable the mode,  and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `matlab-maint-minor-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-matlab-maint-minor-mode 'globalized-minor-mode t)
(defvar global-matlab-maint-minor-mode nil "\
Non-nil if Global Matlab-Maint minor mode is enabled.
See the `global-matlab-maint-minor-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-matlab-maint-minor-mode'.")
(custom-autoload 'global-matlab-maint-minor-mode "matlab-maint" nil)
(autoload 'global-matlab-maint-minor-mode "matlab-maint" "\
Toggle Matlab-Maint minor mode in all buffers.
With prefix ARG, enable Global Matlab-Maint minor mode if ARG is
positive; otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Matlab-Maint minor mode is enabled in all buffers where `(lambda nil
Should we turn on in this buffer? Only if in the project. (let ((dir
(expand-file-name default-directory)) (ml (file-name-directory
(expand-file-name (locate-library matlab))))) (when (string= ml
(substring dir 0 (min (length dir) (length ml))))
(matlab-maint-minor-mode 1))))' would do it.

See `matlab-maint-minor-mode' for more information on Matlab-Maint
minor mode.

(fn &optional ARG)" t)
(register-definition-prefixes "matlab-maint" '("matlab-maint-"))


;;; Generated autoloads from matlab-netshell.el

(autoload 'matlab-netshell-server-active-p "matlab-netshell" "\
Return non-nil if there is an active MATLAB netshell server.")
(autoload 'matlab-netshell-server-start "matlab-netshell" "\
Start the MATLAB netshell server." t)
(register-definition-prefixes "matlab-netshell" '("matlab-netshell-"))


;;; Generated autoloads from matlab-publish.el

(register-definition-prefixes "matlab-publish" '("matlab-"))


;;; Generated autoloads from matlab-scan.el

(register-definition-prefixes "matlab-scan" '("matlab-" "mlf-"))


;;; Generated autoloads from matlab-shell.el

(autoload 'matlab-mode-determine-matlabroot "matlab-shell" "\
Return the MATLABROOT for the 'matlab-shell-command'.")
(autoload 'matlab-shell "matlab-shell" "\
Create a buffer with MATLAB running as a subprocess.

MATLAB shell cannot work on the MS Windows platform because MATLAB is not
a console application." t)
(register-definition-prefixes "matlab-shell" '("gud-matlab-marker-regexp-prefix" "matlab-"))


;;; Generated autoloads from matlab-shell-gud.el

(autoload 'matlab-shell-mode-gud-enable-bindings "matlab-shell-gud" "\
Enable GUD features for `matlab-shell' in the current buffer.")
(autoload 'matlab-shell-gud-startup "matlab-shell-gud" "\
Configure GUD when a new `matlab-shell' is initialized.")
(autoload 'mlg-reset-breakpoints "matlab-shell-gud" "\
Remove all cached breakpoints.")
(autoload 'matlab-shell-gud-minor-mode "matlab-shell-gud" "\
Minor mode activated when `matlab-shell' K>> prompt is active.

This minor mode makes MATLAB buffers read only so simple keystrokes
activate debug commands.  It also enables tooltips to appear when the
mouse hovers over a symbol when debugging.
\\<matlab-shell-gud-minor-mode-map>
Debug commands are:
 \\[matlab-shell-gud-mode-edit]  - Edit file (toggle read-only)
            Allows editing file without causing MATLAB to exit debug mode.
 \\[mlgud-break]        - Add breakpoint (ebstop in FILE at point)
 \\[mlgud-remove]        - Remove breakpoint (ebclear in FILE at point)
 \\[mlgud-list-breakpoints]        - List breakpoints (ebstatus)
 \\[mlgud-step]        - Step (dbstep in)
 \\[mlgud-next]        - Next (dbstep)
 \\[mlgud-finish]        - Finish function (dbstep out)
 \\[mlgud-cont]        - Continue (dbcont)
 \\[matlab-shell-gud-show-symbol-value]        - Evaluate expression
 \\[mlg-show-stack]        - Where am I (ebstack)
 \\[mlgud-stop-subjob]        - Quit (dbquit)

This is a minor mode.  If called interactively, toggle the
`Matlab-Shell-Gud minor mode' mode.  If the prefix argument is
positive, enable the mode,  and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `matlab-shell-gud-minor-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-matlab-shell-gud-minor-mode 'globalized-minor-mode t)
(defvar global-matlab-shell-gud-minor-mode nil "\
Non-nil if Global Matlab-Shell-Gud minor mode is enabled.
See the `global-matlab-shell-gud-minor-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-matlab-shell-gud-minor-mode'.")
(custom-autoload 'global-matlab-shell-gud-minor-mode "matlab-shell-gud" nil)
(autoload 'global-matlab-shell-gud-minor-mode "matlab-shell-gud" "\
Toggle Matlab-Shell-Gud minor mode in all buffers.
With prefix ARG, enable Global Matlab-Shell-Gud minor mode if ARG is
positive; otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Matlab-Shell-Gud minor mode is enabled in all buffers where `(lambda
nil Should we turn on in this buffer? Only if in a MATLAB mode. (when
(eq major-mode 'matlab-mode) (matlab-shell-gud-minor-mode 1)))' would
do it.

See `matlab-shell-gud-minor-mode' for more information on
Matlab-Shell-Gud minor mode.

(fn &optional ARG)" t)
(autoload 'matlab-shell-inactive-gud-minor-mode "matlab-shell-gud" "\
Minor mode activated when `matlab-shell' K>> prompt is inactive.

\\<matlab-shell-inactive-gud-minor-mode-map>
Debug commands are:
 \\[mlgud-break]        - Add breakpoint (ebstop in FILE at point)
 \\[mlgud-remove]        - Remove breakpoint (ebclear in FILE at point)
 \\[mlgud-list-breakpoints]        - List breakpoints (ebstatus)

This is a minor mode.  If called interactively, toggle the
`Matlab-Shell-Inactive-Gud minor mode' mode.  If the prefix
argument is positive, enable the mode,  and if it is zero or
negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `matlab-shell-inactive-gud-minor-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-matlab-shell-inactive-gud-minor-mode 'globalized-minor-mode t)
(defvar global-matlab-shell-inactive-gud-minor-mode nil "\
Non-nil if Global Matlab-Shell-Inactive-Gud minor mode is enabled.
See the `global-matlab-shell-inactive-gud-minor-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-matlab-shell-inactive-gud-minor-mode'.")
(custom-autoload 'global-matlab-shell-inactive-gud-minor-mode "matlab-shell-gud" nil)
(autoload 'global-matlab-shell-inactive-gud-minor-mode "matlab-shell-gud" "\
Toggle Matlab-Shell-Inactive-Gud minor mode in all buffers.
With prefix ARG, enable Global Matlab-Shell-Inactive-Gud minor mode if
ARG is positive; otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Matlab-Shell-Inactive-Gud minor mode is enabled in all buffers where
`(lambda nil Should we turn on in this buffer? Only if in a MATLAB
mode. (when (eq major-mode 'matlab-mode)
(matlab-shell-inactive-gud-minor-mode 1)))' would do it.

See `matlab-shell-inactive-gud-minor-mode' for more information on
Matlab-Shell-Inactive-Gud minor mode.

(fn &optional ARG)" t)
(register-definition-prefixes "matlab-shell-gud" '("gud-matlab-" "matlab-" "mlg-"))


;;; Generated autoloads from matlab-syntax.el

(register-definition-prefixes "matlab-syntax" '("matlab-"))


;;; Generated autoloads from matlab-topic.el

(autoload 'matlab-shell-help-mode "matlab-topic" "\
Major mode for viewing MATLAB help text.
Entry to this mode runs the normal hook `matlab-shell-help-mode-hook'.

Commands:
\\{matlab-shell-help-mode-map}

(fn)" t)
(register-definition-prefixes "matlab-topic" '("matlab-shell-"))


;;; Generated autoloads from mlgud.el

(defvar mlgud-tooltip-mode nil "\
Non-nil if Mlgud-Tooltip mode is enabled.
See the `mlgud-tooltip-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `mlgud-tooltip-mode'.")
(custom-autoload 'mlgud-tooltip-mode "mlgud" nil)
(autoload 'mlgud-tooltip-mode "mlgud" "\
Toggle the display of MLGUD tooltips.
With a prefix argument ARG, enable the feature if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
it if ARG is omitted or nil.

(fn &optional ARG)" t)
(register-definition-prefixes "mlgud" '("mlgud-"))


;;; Generated autoloads from mlint.el

(autoload 'mlint-minor-mode "mlint" "\
Toggle mlint minor mode, a mode for showing mlint errors.
With prefix ARG, turn mlint minor mode on iff ARG is positive.
\\{mlint-minor-mode-map\\}

(fn &optional ARG)" t)
(register-definition-prefixes "mlint" '("mlint-"))


;;; Generated autoloads from semantic-matlab.el

(autoload 'semantic-default-matlab-setup "semantic-matlab" "\
Set up a buffer for parsing of MATLAB files.")
(register-definition-prefixes "semantic-matlab" '("matlab-semantic-" "semantic-"))


;;; Generated autoloads from semanticdb-matlab.el

(register-definition-prefixes "semanticdb-matlab" '("semantic"))


;;; Generated autoloads from srecode-matlab.el

(autoload 'srecode-semantic-handle-:matlab "srecode-matlab" "\
Add macros into the dictionary DICT based on the current MATLAB buffer.
Adds the following:
FILE_SYMBOL - The file name as a symbol.
FILE_DOC_SYMBOL - The file name as a symbol for doc strings.
PACKAGE - The package this file is in, or empty if none.
FILE_CLASS - Show section if filename should be a class.
FILE_FUNCTION - Show setion if filename is a function.

On class prediction - when filling in an empty file, if the filename and
directory it is in match, for example @foo/foo.m then foo should be a classdef.

(fn DICT)")


;;; Generated autoloads from tlc.el

(autoload 'tlc-mode "tlc" "\


(fn)" t)
(add-to-list 'auto-mode-alist '("\\.tlc\\'" . tlc-mode))
(register-definition-prefixes "tlc" '("tlc-"))

;;; End of scraped data

(provide 'matlab-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; matlab-mode-autoloads.el ends here
