cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/extract-digits-from-year.rkt" "2018" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/extract-digits-from-year.rkt" "2018" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/extract-digits-from-year.rkt" "20aa" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/extract-digits-from-year.rkt" "20ab" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/event-language-demo.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/event-language-demo.rkt" "40" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/match-language-demo.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/typed-racket-demo.rkt" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/typed-racket-demo.rkt" "5.3" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "runracketscriptmain" "/root/.emacs.d/host/pen.el/scripts/racket-scripts/typed-racket-demo.rkt" "5.3" "#" "<==" "zsh"
