cd /root/notes;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/notes;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/notes;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/notes;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/notes;  "rosie" "grep" "-o" "subs" "net.fqdn_practical" "#" "<==" "rosie-urls"
cd /root/notes/ws/problog;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
