cd /;  "rosie" "match" "all.things" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.fqdn_practical" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.fqdn_practical" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.fqdn_practical" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.emacs.d/host/pen.el/docs/theology;  "rosie" "grep" "-o" "subs" "net.fqdn_practical" "#" "<==" "rosie-urls"
cd /root/.pen/documents/notes;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.pen/documents/notes;  "rosie" "grep" "-o" "subs" "net.url_common" "#" "<==" "rosie-urls"
cd /root/.pen/documents/notes;  "rosie" "grep" "-o" "subs" "net.fqdn_practical" "#" "<==" "rosie-urls"
