cd /root/.pen/documents/agenda;  "agenda-string" "Go to dentist again" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Go to dentist" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Ad-hoc" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Go to dentist" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Ad-hoc" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Go to dentist again" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Go to dentist again" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Daily Prayer" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Daily Prayer" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Daily Prayer" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Daily Prayer" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Daily Prayer" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Daily Prayer" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Daily Prayer" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "prayers" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Visit Bill (William) Berry in…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Go to dentist" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Ad-hoc" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "contemplation" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Recurring" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/org-brain/people;  "agenda-string" "Mega-man" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "agenda-string" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "agenda-string" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Meet Debbie at corrections" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Deliverance from trial" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "prayers" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Bible-study with Adson - different day" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Ad-hoc" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Church" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Cell group" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watson's house" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watson's house" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Cell group" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Church" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Recurring" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "contemplation" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "rebukes" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "declarations" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Recurring" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Cell group" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Cell group" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Cell group" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Church" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Recurring" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "contemplation" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Jesus clean me" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "contemplation" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "mum" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "rebukes" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "declarations" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "rebukes" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "declarations" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "contemplation" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "declarations" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "declarations" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "declarations" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "agenda-string" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "agenda-string" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "agenda" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso…" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "agenda-string" "Equippers night at John Watso" "#" "<==" "zsh"
