#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

if test "$1" == "--help"; then
    do_pager=y
fi

test -f $REPOS/ddgr/ddgr || (
    cd "$REPOS"
    git clone "https://github.com/jarun/ddgr"
    cd ddgr
    make
)

if test "$do_pager" = "y"; then
    $REPOS/ddgr/ddgr  "$@" | pavs
else
    $REPOS/ddgr/ddgr "$@"
fi
