#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

. $HOME/repos/sh-source/nvm-node

sn_nvm_bin="$(printf -- "%s" "$sn" | which -a "$sn" | grep ".nvm/versions/node" | head -n 1)"
test -f "$sn_nvm_bin" || npm install -g download-gist &>/dev/null
sn_nvm_bin="$(printf -- "%s" "$sn" | which -a "$sn" | grep ".nvm/versions/node" | head -n 1)"

if ! test -f "$sn_nvm_bin"; then
    exit 1
fi

"$sn_nvm_bin" "$@"
