#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

sn="$(basename -- "$0")"

. $HOME/sh-source/nvm-node

sn_nvm_bin="$(printf -- "%s" "$sn" | which -a "$sn" | grep ".nvm/versions/node" | head -n 1)"
test -f "$sn_nvm_bin" || npm install -g download-gist &>/dev/null
sn_nvm_bin="$(printf -- "%s" "$sn" | which -a "$sn" | grep ".nvm/versions/node" | head -n 1)"

if ! test -f "$sn_nvm_bin"; then
    exit 1
fi

"$sn_nvm_bin" "$@"
