#!/bin/bash
export TTY

# decorative ls

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

if is_tty; then
    opts=" --color=always "
fi

eval "/bin/ls $opts -A -F $(cmd "$@") | sed 's/[*=>@]$//'"