#!/bin/bash
export TTY

awk 1 | while IFS=$'\n' read -r url; do
    redirect="$(0</dev/null curl-get-redirect "$url")"
    if test -n "$redirect"; then
        printf -- "%s\n" "$redirect"
    else
        printf -- "%s\n" "$url"
    fi
done
