#!/bin/bash
export TTY

. $SCRIPTS/lib/stdin_exists

stdin_exists
hasstdin="$?"

# . $PENEL_DIR/scripts/utils.sh

# Perhaps this should actually use pipeexec
# cat file | filter sed1 sed2 sed3
# filter fp sed1 sed2 sed3

if test -f "$1" || ! test "$hasstdin" = 0; then
    cat1 "$1" | eval "$f"
elif test -n "$1" && test "$hasstdin" = 0; then
    f="$1"
    shift

    cat1 "$@" | eval "$f"
else
    # TODO treat each argument0
    "$@"
fi
