#!/bin/bash
export TTY

# This will use the host git to run git commands, if ssh to host is available

if pen-rc-test host-ssh-master; then
    SSH_HOST_ALLOWED=y
else
    SSH_HOST_ALLOWED=n
fi
export SSH_HOST_ALLOWED

# It's important to disable tty for git. less will still function
export USE_TTY=n
export SSH_HOST_CHOWN=y
export USE_PROFILE=n
export SSH_EXPORTS="GIT_PAGER=less"
pen-ssh-host git "$@"
