#!/bin/bash
export TTY

( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

# This will use the host git to run git commands, if ssh to host is available

if ! test -n "$SSH_HOST_ALLOWED" && pen-rc-test host-ssh-master; then
    : "${SSH_HOST_ALLOWED:="y"}"
else
    : "${SSH_HOST_ALLOWED:="n"}"
fi
export SSH_HOST_ALLOWED

# if test "$SSH_HOST_ALLOWED" = "n"; then
#     alt "$sn" "$@"
#     exit "$?"
# fi

# It's important to disable tty for git. less will still function
export USE_TTY=n
export SSH_HOST_CHOWN=y
: "${USE_PROFILE:="y"}"
export USE_PROFILE
# export SSH_EXPORTS="GIT_PAGER=less"
export SSH_EXPORTS="GIT_PAGER=pen-pager"
case "$(pwd)" in
    *) {
        pen-ssh-host "$sn" "$@"
    }
    ;;
esac
