#!/bin/bash
export TTY

( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -srcp|-srcprofile) {
        do_profile=y
        shift
    }
    ;;

    -2) {
        do_screen_2color=y
        shift
    }
    ;;

    -sn) {
        sn="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

fargs=()

if test "$do_profile" = "y"; then
    fargs+=(source-profile)
fi

if test "$do_screen_2color" = "y"; then
    fargs+=(screen-2color)
fi

fargs+=("$sn" "$@")

# This will use the host git to run git commands, if ssh to host is available

if ! test -n "$SSH_HOST_ALLOWED" && pen-rc-test host-ssh-master; then
    : "${SSH_HOST_ALLOWED:="y"}"
else
    : "${SSH_HOST_ALLOWED:="n"}"
fi
export SSH_HOST_ALLOWED

# if test "$SSH_HOST_ALLOWED" = "n"; then
#     alt "$sn" "$@"
#     exit "$?"
# fi

# It's important to disable tty for git. less will still function
export USE_TTY=n
export SSH_HOST_CHOWN=y
: "${USE_PROFILE:="y"}"
export USE_PROFILE
# export SSH_EXPORTS="GIT_PAGER=less"
export SSH_EXPORTS="GIT_PAGER=pen-pager"
case "$(pwd)" in
    *) {
        pen-ssh-host "${fargs[@]}"
    }
    ;;
esac
