#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# . $SCRIPTS/lib/hs

sn="$(basename -- "$0")"

# It's currently buggy with real-docker

pen-cterm-ssh -v "$sn" "$@" | cat