#!/bin/bash
export TTY

# https://docs.helix-editor.com/keymap.html
# https://docs.helix-editor.com/remapping.html

# elinks-dump "https://docs.helix-editor.com/keymap.html"

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    +*:*) {
        line="$(p "$opt" | mcut -d'[+:]' -f2)"
        col="$(p "$opt" | mcut -d'[+:]' -f3)"

        shift
    }
    ;;

    +[0-9]*) {
        line="$(p "$opt" | mcut -d+ -f2)"

        shift
    }
    ;;

    -line) {
        line="$2"
        shift
        shift
    }
    ;;

    -col) {
        col="$2"
        shift
        shift
    }
    ;;

    -norm) {
        norm="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

# export PAGER=less
# export EDITOR=vim

# (
# cd ~/.config/helix
# ln -sf $MYGIT/helix-editor/helix/runtime/
# )
# export HELIX_RUNTIME=$MYGIT/helix-editor/helix/runtime/
export HELIX_RUNTIME=~/repos/helix/runtime

# truecolour support is not available in pen
# because I need a new tmux version

# $HOME/programs/helix-23.05-x86_64-linux/hx "$@"
export TERM=screen-256color
# export TERM=screen-2color

# hx doesn't respect TERM
# nvc -2 $HOME/.cargo/bin/hx "$@"

CMD="$(cmd "$@")"
: ${CMD:="$(cmd "$@")"}

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

if stdin_exists; then
     eval "$HOME/.cargo/bin/hx $CMD"
     exit "$?"
fi

if test -n "$line"; then
    if test -n "$col"; then
        # col="$((col - 1))"
        x -shE "$HOME/.cargo/bin/hx $CMD" -e NOR -s ":goto $line" -c m -s "$(pen-s rs $col l)" -s "$norm" -i
    else
        x -shE "$HOME/.cargo/bin/hx $CMD" -e NOR -s ":goto $line" -c m -s "$norm" -i
    fi
else
    x -shE "$HOME/.cargo/bin/hx $CMD" -e NOR -s "$norm" -i
fi

# $HOME/.cargo/bin/hx -c "$HOME/.config/helix/config.toml" "$@"
# $HOME/.cargo/bin/hx -c "$HOME/.config/helix/config.toml" "$@"
# $HOME/.cargo/bin/hx "$@"
