#!/bin/bash
export TTY

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

npm_path="$(which npm | grep /root/.nvm/)"

if test -n "$npm_path"; then
    "$npm_path" "$@"
fi
