#!/bin/bash
export TTY

# Updating the library recently fixed some issues. It's worth doing this
# py f pdfminer

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -mkfp) {
        make_txt_fp=y
        shift
    }
    ;;

    *) break;
esac; done

is_stdout_pipe() {
    [[ -p /dev/stdout ]]
}

# Calibre uses this
# pdftohtml -enc UTF-8 -noframes -p -nomerge -nodrm src.pdf index.html

if is_stdout_pipe; then
    pdf2txt.py "$@" | c ascify | {
        # Some book generate tabs instead of spaces
        sed 's/	\+/ /g' | sed 's/ \+/ /g' | sed 's/ . . ./.../g' | sed 's//\n&\n/g'
    }
else
    # arguments is a list of file paths

    while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
        "") { shift; }; ;;
        *) {
            if test -f "$opt"; then
                (
                    fp="$opt"
                    fn=$(basename -- "$fp")
                    dn=$(dirname "$fp")
                    ext="${fn##*.}"
                    mant="${fn%.*}"

                    cd "$dn"
                    if ! test -f "${mant}.txt"; then
                        pdf2txt.py "$fn" > "${mant}.txt"
                    fi
                    v "${mant}.txt"
                )
            fi
            shift
        }
        ;;
    esac; done

    # pdf2txt.py "$@"
fi
