#!/bin/bash
export TTY

num="$1"
shift

test -n "$num" || exit 1

if printf -- "%s\n" "$num" | grep -q -P '^pen-emacsd-'; then
    SOCKET="$num"
else
    SOCKET="pen-emacsd-$num"
fi

pen-e -D "$SOCKET" "$@"