#!/bin/bash
export TTY

# for i in sh-*; do sed -i 's/read -n1 d/&; test "$d" = "" \&\& read -n1 d/' "$i" ; done

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
G  org-brain-visualize-reset-map infogetics
F  org-brain-visualize-reset-map "information retrieval"
O  org-brain-visualize-reset-map ideation
T org-brain-visualize-reset-map "nlp tasks"
Vi  org-brain-visualize-reset-map index
z  fz-brains
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey

IFS="" read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    G) cmd="org-brain-visualize-reset-map infogetics" ;;
    F) cmd="org-brain-visualize-reset-map 'information retrieval'" ;;
    O) cmd="org-brain-visualize-reset-map ideation" ;;
    T) cmd="org-brain-visualize-reset-map 'nlp tasks'" ;;
    V|i) cmd="org-brain-visualize-reset-map index" ;;
    z) cmd="fz-brains" ;;
    
esac
echo
echo "$cmd" | pen-hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"