#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
f flow-errors-since 10 min ago | v +G
g git lexicon logs
HEREDOC

echo "$0" | udl | hls green
echo "$options" | hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    f) { cmd="flow-errors-since 10 min ago | v +G"; }; ;;
    g) { cmd="cl-get-logs-for-container $(ci -meta \"$(cl-platform)\" cl-list-all-containers | grep \"^lexicon.*git\\$\") | v"; }; ;;
    
esac
echo
echo "$cmd" | hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
