#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
a  easciimation
e  cli-chess
B  moon-buggy
m  myman
^  endless-sky
b  brogue
4  tetris
t  tetris-rs
T  etetris-vt100
X  etetris-xterm
S  snake
s  csol (solitaire)
w  minesweeper
C  chenvaders
o  project-cosmos
c  pacman4console
g  gorched
h  hhgttg
D  dwarf fortress
i  ninvaders
=  midnight-commander
k  sudoku
H  killersheep
u  erubikscube
r  rubiks_cube 
R  nrubik
z  fz-run $NOTES/ws/fuzzy/games.txt
Z  v $NOTES/ws/fuzzy/games.txt
HEREDOC

echo "$0" | udl | hls green
echo "$options" | hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    a) cmd="easciimation" ;;
    e) cmd="cli-chess" ;;
    B) cmd="moon-buggy" ;;
    m) cmd="myman" ;;
    \^) cmd="endless-sky" ;;
    b) cmd="brogue" ;;
    4) cmd="etetris" ;;
    t) cmd="tetris-rs" ;;
    T) cmd="etetris-vt100" ;;
    X) cmd="etetris-xterm" ;;
    S) cmd="snake" ;;
    s) cmd="csol" ;;
    w) cmd="minesweeper" ;;
    C) cmd="chenvaders" ;;
    # C) cmd="e-calibredb" ;;
    o) cmd="project-cosmos" ;;
    c) cmd="pacman4console" ;;
    g) cmd="gorched" ;;
    h) cmd="nvc hhgttg" ;;
    D) cmd="df-bay12" ;;
    i) cmd="ninvaders" ;;
    k) cmd="nvt sudoku" ;;
    H) cmd="killersheep" ;;
    u) cmd="erubikscube" ;;
    r) cmd="rubiks_cube" ;;
    R) cmd="nrubik" ;;
    z) cmd="fz-run $NOTES/ws/fuzzy/games.txt" ;;
    Z) cmd="v $NOTES/ws/fuzzy/games.txt" ;;
esac
echo
echo "$cmd" | hls nearblack
eval "$cmd"
