#!/bin/bash
export TTY

# for i in sh-*; do sed -i 's/read -n1 d/&; test "$d" = "" \&\& read -n1 d/' "$i" ; done

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
d  dir
k  ghci
p  haskell-playground
K  sp -sh ghci
n  ghci -norc
N  sp -sh ghci -norc
f  ghci -full
F  sp -sh ghci -full
P  sp-ghci $REPOS/haskell-playground
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey

IFS="" read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    # ghci no longer exists globally
    # k) cmd="cd $NOTES; ghci" ;;
    k) cmd="cd $REPOS/haskell-playground/scratch; ghci" ;;
    p) cmd="cd $NOTES; haskell-playground" ;;
    K) cmd="cd $NOTES; sp -sh ghci" ;;
    n) cmd="cd $NOTES; ghcin" ;;
    N) cmd="cd $NOTES; sp -sh ghcin" ;;
    f) cmd="cd $NOTES; ghci -full" ;;
    F) cmd="cd $NOTES; sp -sh ghci -full" ;;
    P) cmd="sp-ghci $REPOS/haskell-playground" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"