#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

read -r -d '' options <<HEREDOC
.  EDIT
HEREDOC

echo "$0" | udl | hls green
echo "$options" | pen-mnm | hls dgrey

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
esac
echo
echo "$cmd" | hls nearblack

eval "$cmd"