#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

read -r -d '' options <<HEREDOC
.  EDIT
e  zcd $MYGIT/infogetics
r  zcd $HOME/org-brains/infogetics
w  zcd $MYGIT/infogetics/infogetics.github.io
hb zcd $MYGIT/infogetics/infogetics-hugo
a  zcd $MYGIT/infogetics/infogetics-hugo/posts
k  zcd $MYGIT/infogetics/infogetics-haskell
HEREDOC

echo "$0" | udl | hls green
echo "$options" | pen-mnm | hls dgrey

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    e) cmd="zcd $MYGIT/infogetics" ;;
    r) cmd="zcd $HOME/org-brains/infogetics" ;;
    w) cmd="zcd $MYGIT/infogetics/infogetics.github.io" ;;
    h|b) cmd="zcd $MYGIT/infogetics/infogetics-hugo" ;;
    a) cmd="zcd $MYGIT/infogetics/infogetics-hugo/posts" ;;
    k) cmd="zcd $MYGIT/infogetics/infogetics-haskell" ;;
esac
echo
echo "$cmd" | hls nearblack

eval "$cmd"