#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

read -r -d '' options <<HEREDOC
.  EDIT
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

eval "$cmd"