#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
r  zrepl "raco pkg install " 
c  zrepl "sudo cpanm " 
n  zrepl "npm install -g " 
l  zrepl "l " 
HEREDOC

echo "$0" | udl | hls green
echo "$options" | hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    r) cmd="zrepl \"raco pkg install \"" ;;
    c) cmd="zrepl \"sudo cpanm \"" ;;
    n) cmd="zrepl \"npm install -g \"" ;;
    l) cmd="zrepl \"l \"" ;;
esac
echo
echo "$cmd" | hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
