#!/bin/bash
export TTY

# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
c    killall compton
d    sh-docker
v    killall vlc
f    fix-lag.sh
V    killall vim nvim
-91  kill -9 -1
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    c) cmd="killall compton" ;;
    v) cmd="killall vlc" ;;
    d) cmd="sh-docker" ;;
    f) cmd="fix-lag.sh" ;;
    -|1|9) cmd="kill -9 -1 " ;;
    V) cmd="killall vim nvim" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"