#!/bin/bash
export TTY

# for i in sh-*; do sed -i 's/read -n1 d/&; test "$d" = "" \&\& read -n1 d/' "$i" ; done

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
d  dir
i  vd <(ifconfig -a) <(ifconfig)
a  arp-tablist
n  route -n
D  sudo dhclient -v
T  nmtui
m  mitm \$(read cmd; echo "\$cmd")
p  mitmproxy -p 8080
b  ebluetooth
B  TERM=xterm-2color btscanner
R  sudo /etc/init.d/networking restart; sudo /etc/init.d/network-manager restart; sudo sed -i "s/^\\(nameserver \\)127.0.0.53$/\\18.8.8.8/" /etc/resolv.conf
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey

IFS="" read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    d) cmd="sh-dir" ;;
    i) cmd="vd <(ifconfig -a) <(ifconfig)" ;;
    a) cmd="arp-tablist" ;;
    n) cmd="route -n | pa -vs" ;;
    D) cmd="sudo dhclient -v 2>&1 | pa -vs" ;;
    T) cmd="nmtui" ;;
    m) cmd="rlwrap rlmitm" ;;
    p) cmd="mitmproxy -p 8080" ;;
    b) cmd="ebluetooth" ;;
    B) cmd="TERM=xterm-2color btscanner" ;;
    R) cmd="sudo /etc/init.d/networking restart; sudo /etc/init.d/network-manager restart; sudo sed -i \"s/^\\\\(nameserver \\\\)127.0.0.53$/\\\\18.8.8.8/\" /etc/resolv.conf" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"