#!/bin/bash
unset TTY
export TTY

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
g  google
G  golang
y  python
c  c
t  turtle
b  problog
m  megaparsack
j  javascript
h  github
HEREDOC

echo "$0" | udl | hls green
echo "$options" | pen-mnm | hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    g) cmd="pg google" ;;
    G) cmd="pg golang" ;;
    y) cmd="pg python" ;;
    c) cmd="pg c" ;;
    t) cmd="pg turtle" ;;
    b) cmd="pg problog" ;;
    m) cmd="pg megaparsack" ;;
    j) cmd="pg javascript" ;;
    h) cmd="pg github" ;;
esac
echo
echo "$cmd" | hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
