#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
s  pen-tm cat | pen-tm -S -tout nw siq
a  pen-tm cat | pen-tm -S -tout nw aiq
z  fz-rtcmd
HEREDOC

echo "$0" | udl | hls green
echo "$options" | pen-mnm | hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    s) {
        set -m
        bash -c "sleep 0.2; pen-tm cat | pen-tm -S -tout nw siq" & disown
        exit 0
    }
    ;;

    a) {
        set -m
        bash -c "sleep 0.2; pen-tm cat | pen-tm -S -tout nw aiq" & disown
        exit 0
    }
    ;;

esac
echo
echo "$cmd" | hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"