#!/bin/bash
export TTY

# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
2  xpti2
3  xpti3
c  calc
HEREDOC

echo "$0" | udl | hls green
echo "$options" | hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    2) cmd="pen-tm sel localhost_current_repls:xpti2" ;;
    3) cmd="pen-tm sel localhost_current_repls:xpti3" ;;
    3) cmd="rlr ma calc" ;;

esac
echo
echo "$cmd" | hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
