#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

# t  zcd ~/.emacs.d/host/openai-classification-training-data
read -r -d '' options <<HEREDOC
.  EDIT
e  zcd ~/.emacs.d/host/efm-langserver
S  zcd ~/.emacs.d/host
d  zcd ~/.pen/documents
n  zcd ~/notes
7  zcd ~/.emacs.d/host/channel
C  zcd ~/.emacs.d/host/creation
Y  zcd ~/.emacs.d/host/yas-snippets
P  zcd ~/.emacs.d/host/pensieve
r  zcd ~/.emacs.d/host/rhizome
u  zcd $HOME/.emacs.d/host/pen-ethereum-development-ide
l  zcd ~/.emacs.d/host/ilambda
x  zcd ~/.emacs.d/host/examplary
D  zcd ~/.emacs.d/host/dni
w  sp ~/.emacs.d/host/pen.el/src/pen.el
pq zcd ~/.emacs.d/host/pen.el
v  zcd ~/.emacs.d/host/metaverses
V  zcd ~/.emacs.d/host/protoverses
H  zcd ~/.emacs.d/host/imaginary-programming-thesis
s  zcd ~/.emacs.d/host/pen.el/scripts
c  zcd ~/.emacs.d/host/pen.el/src
X  sp ~/.emacs.d/host/pen.el/src/pen-examplary.el
d  zcd ~/.emacs.d/host/prompt-design-patterns
t  zcd ~/.emacs.d/host/personalities
I  zcd ~/.emacs.d/host/incarnations
T  zcd ~/.emacs.d/host/tomes
o  zcd ~/.emacs.d/host/prompts
O  zcd ~/.emacs.d/host/openai-complete-clj
m  zcd ~/.emacs.d/host/engines
n  zcd ~/.emacs.d/host/interpreters
k  zcd ~/.emacs.d/host/ink.el
K  zcd ~/.emacs.d/host/khala
g  zcd ~/.emacs.d/host/glossaries
y  zcd ~/.emacs.d/host/semiosis
j  zcd ~/.emacs.d/host/pen-contrib.el
i  zcd ~/.emacs.d/host/openai-api.el
hb zcd ~/.emacs.d/host/semiosis-hugo
a  zcd ~/.emacs.d/host/semiosis-hugo/posts
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    e) cmd="zcd ~/.emacs.d/host/efm-langserver" ;;
    S) cmd="zcd ~/.emacs.d/host" ;;
    d) cmd="zcd ~/.pen/documents" ;;
    n) cmd="zcd ~/notes" ;;
    7) cmd="zcd ~/.emacs.d/host/channel" ;;
    C) cmd="zcd ~/.emacs.d/host/creation" ;;
    Y) cmd="zcd ~/.emacs.d/host/yas-snippets" ;;
    P) cmd="zcd ~/.emacs.d/host/pensieve" ;;
    r) cmd="zcd ~/.emacs.d/host/rhizome" ;;
    u) cmd="zcd $HOME/.emacs.d/host/pen-ethereum-development-ide" ;;
    l) cmd="zcd ~/.emacs.d/host/ilambda" ;;
    x) cmd="zcd ~/.emacs.d/host/examplary" ;;
    D) cmd="zcd ~/.emacs.d/host/dni" ;;
    w) cmd="sp ~/.emacs.d/host/pen.el/src/pen.el" ;;
    p|q) cmd="zcd ~/.emacs.d/host/pen.el" ;;
    v) cmd="zcd ~/.emacs.d/host/metaverses" ;;
    V) cmd="zcd ~/.emacs.d/host/protoverses" ;;
    H) cmd="zcd ~/.emacs.d/host/imaginary-programming-thesis" ;;
    s) cmd="zcd ~/.emacs.d/host/pen.el/scripts" ;;
    c) cmd="zcd ~/.emacs.d/host/pen.el/src" ;;
    X) cmd="sp ~/.emacs.d/host/pen.el/src/pen-examplary.el" ;;
    o) cmd="zcd ~/.emacs.d/host/prompts" ;;
    O) cmd="zcd ~/.emacs.d/host/openai-complete-clj" ;;
    m) cmd="zcd ~/.emacs.d/host/engines" ;;
    n) cmd="zcd ~/.emacs.d/host/interpreters" ;;
    k) cmd="zcd ~/.emacs.d/host/ink.el" ;;
    K) cmd="zcd ~/.emacs.d/host/khala" ;;
    g) cmd="zcd ~/.emacs.d/host/glossaries" ;;
    y) cmd="zcd ~/.emacs.d/host/semiosis" ;;
    j) cmd="zcd ~/.emacs.d/host/pen-contrib.el" ;;
    i) cmd="zcd ~/.emacs.d/host/openai-api.el" ;;
    d) cmd="zcd ~/.emacs.d/host/prompt-design-patterns" ;;
    t) cmd="zcd ~/.emacs.d/host/personalities" ;;
    I) cmd="zcd ~/.emacs.d/host/incarnations" ;;
    T) cmd="zcd ~/.emacs.d/host/tomes" ;;
    # t) cmd="zcd ~/.emacs.d/host/openai-classification-training-data" ;;
    h|b) cmd="zcd ~/.emacs.d/host/semiosis-hugo" ;;
    a) cmd="zcd ~/.emacs.d/host/semiosis-hugo/posts" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

eval "$cmd"
