#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

# g  gh
read -r -d '' options <<HEREDOC
.  EDIT
h  hoogle
/  google
s  zrs
HEREDOC

echo "$0" | udl | hls green
echo "$options" | pen-mnm | hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

# g) cmd="xs gh" ;;
case "$d" in
    .) cmd="v $0" ;;
    # h) cmd="ehg" ;;
    h) cmd="rlr hoogle" ;;
    s) cmd="zrs egr" ;;
    \/) cmd="v $HOME/notes2018/ws/google/searches.org" ;;
esac
echo
echo "$cmd" | hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"