#!/bin/bash
export TTY

# exec 1> >(pen-mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

# g  sh-takaheai-go
# r  sh-takaheai-rc
# F  sh-takaheai-files
# I  takaheai-get-issue-description
# J  takaheai jargon

read -r -d '' options <<HEREDOC
.  EDIT
G  glossary.txt
o  zcd takaheai
d  sh-takaheai-dir
e  sh-takaheai-exec
HEREDOC

echo "$0" | udl | pen-hls green
echo "$options" | pen-mnm | pen-hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear


    # w) cmd="list-wiki-files-below $MYGIT/fortescue-autonomy" ;;
    # r) cmd="sh-takaheai-rc" ;;
    # F) cmd="sh-takaheai-files" ;;
    # I) cmd="takaheai-get-issue-description" ;;
    # J) cmd="vs $NOTES/ws/takaheai/jargon.txt" ;;

case "$d" in
    .) cmd="v $0" ;;
    G) cmd="vs $HOME/notes/ws/takaheai/glossary.txt" ;;
    o) cmd="zcd $NOTES/ws/takaheai" ;;
    d) cmd="sh-takaheai-dir" ;;
    e) cmd="sh-takaheai-exec" ;;
esac
echo
echo "$cmd" | pen-hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
