#!/bin/bash
export TTY

clear
# exec 1> >(pen-mnm)

read -r -d '' options <<HEREDOC
.  EDIT
B branch
HEREDOC

echo "$0" | udl | hls green
echo "$options" | hls dgrey

read -n1 d; test "$d" = "" && read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    B) cmd="pen-vc branch | pen-xc" ;;
esac
echo
echo "$cmd" | hls nearblack

# exec <`tm-tty`
# exec 1> /dev/tty
eval "$cmd"
