#!/bin/bash
export TTY

is_tty() { [ -t 1 ] && ! test "$TERM" = "dumb"; }

if ! test "$VIPIFY" = y && ! is_tty; then
    # tm vipe -wintype spv "vipify sttr"
    pfilter "vipify sttr"
else
    if test "$VIPIFY" = "y"; then
        cat "$1" | /root/go/bin/sttr
        pen-tm -te -d capture - | strip-ansi | tac | sed '/^$/,/═/d' | sed '/═/,$d' | tac | sponge "$1"
    else
        # The first argument is the transformation function
        /root/go/bin/sttr "$@"
    fi
fi
