#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

mkdir -p ~/.pen/elpa-light
mkdir -p ~/.pen/elpa-full

# unison -batch=true /root/.emacs.d/elpa-full /root/.pen/elpa-full

unison -batch=true /root/.emacs.d/elpa-light /root/.pen/elpa-light

# rsync -rtlphx /root/.emacs.d/elpa-full/ /root/.pen/elpa-full
# rsync -rtlphx /root/.pen/elpa-full/ /root/.emacs.d/elpa-full 
# 
# rsync -rtlphx /root/.emacs.d/elpa-light/ /root/.pen/elpa-light
# rsync -rtlphx /root/.pen/elpa-light/ /root/.emacs.d/elpa-light 