#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null
# See also 'timg'

lsix /usr/share/doc/asciidoc/doc/images/tiger.png
show-pic /usr/share/doc/asciidoc/doc/images/tiger.png
