#!/bin/bash
export TTY

unset TMUX

pak_on_error=y
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -c) {
        cwd="$2"
        shift
        shift
    }
    ;;

    -pak) {
        use_pak=y
        shift
    }
    ;;

    -nopae) {
        pak_on_error=n
        shift
    }
    ;;

    *) break;
esac; done

: ${CWD:="$(pwd)"}

CMD="$(cmd "$@")"
: ${CMD:="$(cmd "$@")"}

if test "$use_pak" = "y"; then
    tmux new -c "$CWD" bash -c "$CMD; pen-pak"
else
    if test "$pak_on_error" = "y"; then
        tmux new -c "$CWD" bash -c "$CMD || ( pwd; pen-pak )"
    else
        tmux new -c "$CWD" bash -c "$CMD"
    fi
fi
