#!/bin/bash
export TTY

stdin_exists() {
    ! [ -t 0 ] && ! test "$(readlink /proc/$$/fd/0)" = /dev/null
}

if stdin_exists; then
    cut -d'/' -f3 | cut -d':' -f1
else
    printf -- "%s\n" "$1" | cut -d'/' -f3 | cut -d':' -f1
fi