#!/bin/bash
export TTY
export DISPLAY
# ( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

. $SCRIPTS/lib/stdin_exists

test -f "/usr/local/bin/vim" && : "${bin:="/usr/local/bin/vim"}"
test -f "/usr/bin/vim" && : "${bin:="/usr/bin/vim"}"

# Do this to remove the annoying message from vim
if stdin_exists; then
    IFS= read -rd '' contents < <(cat);typeset -p contents &>/dev/null
    if test -n "$contents"; then
        printf -- "%s" "$contents" | "$bin" "$@"
    fi
else
    "$bin" "$@"
fi
