#!/bin/bash
export TTY
export DISPLAY
# ( hs "$(basename -- "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

stdin_exists() {
    {
    ! [ -t 0 ] && \
    ! test "$(readlink /proc/$$/fd/0)" = /dev/null  && \
    ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
    } &>/dev/null
}

test -f "/usr/local/bin/vim" && : "${bin:="/usr/local/bin/vim"}"
test -f "/usr/bin/vim" && : "${bin:="/usr/bin/vim"}"

# Do this to remove the annoying message from vim
if stdin_exists; then
    IFS= read -rd '' contents < <(cat);typeset -p contents &>/dev/null
    if test -n "$contents"; then
        printf -- "%s" "$contents" | "$bin" "$@"
    fi
else
    "$bin" "$@"
fi
