#!/bin/bash
export TTY

# Examples
# vime "\"yo\""
# vime "strftime(\"%c\")"
# vime "getcompletion('', 'filetype')"
# vime "execute('scriptnames')"

. $SCRIPTS/lib/stdin_exists

eval_vim_expr() {
    vim_expr="$1"

    vim -u NONE -es '+:source $HOME/.emacs.d/pen.el/config/utils.vim' "+:call Insert($vim_expr))" '+:wq! /dev/stdout'
}

if stdin_exists; then
    awk 1 | while IFS=$'\n' read -r line; do
        0</dev/null eval_vim_expr "$line"
    done
fi

if [ -n "$1" ]; then
    eval_vim_expr "$1"
fi
