#!/bin/bash
export TTY

# Examples
# vime "\"yo\""
# vime "strftime(\"%c\")"
# vime "getcompletion('', 'filetype')"
# vime "execute('scriptnames')"

stdin_exists() {
    ! [ -t 0 ] && \
        ! test "$(readlink /proc/$$/fd/0)" = /dev/null && \
        ! test "$(readlink /proc/$$/fd/0)" = "$(readlink /proc/$$/fd/1)"
    # stdin may be redirected to the tty, but  will continue to say false (due to a bash bug)
    # So test to make sure 0 does not point to 1
}

eval_vim_expr() {
    vim_expr="$1"

    vim -u NONE -es '+:source $HOME/var/smulliga/source/git/config/vim/utils.vim' "+:call Insert($vim_expr))" '+:wq! /dev/stdout'
}

if stdin_exists; then
    awk1 | while IFS=$'\n' read -r line; do
        eval_vim_expr "$line"
    done
fi

if [ -n "$1" ]; then
    eval_vim_expr "$1"
fi