cd /root/.pen/documents/notes;  "hsqf" "pl" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "pl" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "pl" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "pl" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "bazel" "#" "<==" "hsqf"
