cd /root/.pen/documents/custom-repl;  "pen-hsqf" "new-project" "#" "<==" "hsqf"
cd /root/.pen/documents/custom-repl;  "pen-hsqf" "new-project" "#" "<==" "hsqf" "#" "<==" "bash"
cd /root/.pen/documents/custom-repl;  "pen-hsqf" "new-project" "#" "<==" "hsqf" "#" "<==" "bash" "#" "<==" "bash"
cd /root/.pen/documents/custom-repl;  "pen-hsqf" "new-project" "#" "<==" "hsqf" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "pen-hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/custom-repl;  "pen-hsqf" "new-project" "#" "<==" "hsqf" "#" "<==" "zsh"
cd /root/.pen/documents/custom-repl;  "hsqf" "new-project" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "new-project" "#" "<==" "hsqf"
cd /root/.pen/documents/monadic-parser;  "hsqf" "new-project" "#" "<==" "hsqf"
cd /root/.emacs.d/host/pen.el/scripts;  "hsqf" "new-project" "#" "<==" "hsqf"
cd /root/.pen/documents/custom-repl;  "hsqf" "new-project" "#" "<==" "hsqf"
cd /root/.pen/documents/custom-repl;  "hsqf" "new-project" "#" "<==" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/custom-repl;  "hsqf" "new-project" "#" "<==" "hsqf"
cd /root/.pen/documents/custom-repl;  "hsqf" "new-project" "#" "<==" "hsqf"
cd /root/.pen/documents/custom-repl;  "hsqf" "new-project" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "hsqf" "#" "<==" "hsqf"
cd /root/.pen/documents/custom-repl;  "hsqf" "new-project" "#" "<==" "hsqf"
cd /root/notes;  "hsqf" "docker" "#" "<==" "hsqf"
cd /root/notes;  "hsqf" "docker" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "vs" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "v" "#" "<==" "hsqf"
cd /root/.emacs.d/host/pen.el/scripts;  "hsqf" "xdg-open" "#" "<==" "hsqf"
cd /root/.emacs.d/host/pen.el/scripts;  "hsqf" "r" "#" "<==" "hsqf"
cd /root/.emacs.d/host/pen.el/scripts;  "hsqf" "pen-r" "#" "<==" "hsqf"
cd /root/.emacs.d/host/pen.el/scripts;  "hsqf" "scope" "#" "<==" "hsqf"
cd /root/.emacs.d/host/pen.el/scripts;  "hsqf" "xs" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "docker" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "docker" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "docker" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "docker" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "docker" "#" "<==" "hsqf"
cd /root/.pen/documents/notes;  "hsqf" "docker" "#" "<==" "hsqf"
