cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=lsTLx7XVooQ" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=_07ktacEGo8" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=qZ4O-1VYv4c" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=p1AClpOsm5g" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=p1AClpOsm5g" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=bX77k_0vqpg" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=VkNP1TdsllU&t=767" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "https://en.wikipedia.org/wiki/Gaelic_type" "-q" "-O" "/root/.pen/tmp/vLMio4E/0" "#" "<==" "vim"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "wget" "-qO-" "https://www.youtube.com/watch?v=x8SUqf8oHQE" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "wget" "-qO-" "https://www.youtube.com/watch?v=uagYLHGicTg" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/docs/theology;  "wget" "-qO-" "https://youtu.be/D70xSncZBDI" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "wget" "-qO-" "https://www.youtube.com/watch?v=E9B-6Nq6t9g" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=kdXXd2cNunw" "#" "<==" "pen-ci"
