cd /root/.emacs.d/host/pen.el/docs/theology;  "wget" "-qO-" "https://www.youtube.com/watch?v=l8pCbtLeXzc" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://www.youtube.com/watch?v=Cf7EA8w_vQc" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=0g2ExGC1GaE" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=MERQ0P6O0CE" "#" "<==" "pen-ci"
cd /;  "wget" "-qO-" "https://www.youtube.com/watch?v=MERQ0P6O0CE" "#" "<==" "pen-ci"
cd /;  "wget" "-qO-" "https://www.youtube.com/watch?v=L4PSTgzgQuA" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://www.youtube.com/watch?v=X-saQr3m4Vs" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/docs/theology;  "wget" "-qO-" "https://www.youtube.com/watch?v=pXVCdbOdydM" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=ZrZlMtHf6Yw" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=ZrZlMtHf6Yw" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://www.youtube.com/watch?v=-93JpZxJsXs" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://www.youtube.com/watch?v=Y76Nez0dI7A" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "https://www.praisecharts.com/songs/details/20064/be-the-center-sheet-music" "-q" "-O" "/root/.pen/tmp/vaofmO3/3" "#" "<==" "vim"
