cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=ncXu2NpgtAw" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=hcxCRyu3nyg" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/docs/theology;  "wget" "-qO-" "https://www.bibletools.org/index.cfm/fuseaction/Lexicon.show/ID/G570/apaistia.htm" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://www.gotquestions.org/age-differences-relationships.html" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://www.desiringgod.org/interviews/can-i-marry-a-woman-half-my-age" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/docs/theology;  "wget" "-qO-" "https://youtu.be/qu8QxxIF4UE" "#" "<==" "pen-ci"
cd /root/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=qu8QxxIF4UE" "#" "<==" "pen-ci"
