cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://www.ligonier.org/learn/devotionals/outside-camp" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=l3jTRB5B9zM" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://youtube.com/watch?v=EMuKmfvgJxc&t=526" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://heidelblog.net/2014/02/a-brief-outline-of-luthers-bondage-of-the-will/" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://firmisrael.org/learn/meaning-of-amen-and-hebrew-word-faith/" "#" "<==" "pen-ci"
