cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=XBm4tLzuap0" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=-JHV75MENqk&list=PLWm5GJd97QanKOltldtA-F3g-XPaVchUa" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=ZENr0gC3f_w" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/docs/theology;  "wget" "-qO-" "https://youtu.be/0y-hQrI_sTA" "#" "<==" "pen-ci"
cd /;  "wget" "-qO-" "https://www.youtube.com/watch?v=TWPoQN8PO9E" "#" "<==" "pen-ci"
