cd /root/common-lisp;  "wget" "https://asdf.common-lisp.dev/archives/asdf-3.3.5.tar.gz" "#" "<==" "zsh"
cd /root/notes;  "wget" "-qO-" "https://biblehub.com/interlinear/john/3-16.htm" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=8bkYHEJXx-k" "#" "<==" "pen-ci"
cd /;  "wget" "-qO-" "https://www.youtube.com/watch?v=QX013_tz4rM" "#" "<==" "pen-ci"
cd /root/notes;  "wget" "-qO-" "https://www.youtube.com/watch?v=D4x6Svur63o" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes/ws/baptist;  "wget" "https://baptiststudiesonline.com/wp-content/uploads/2007/02/orthodox-creed.pdf" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "wget" "-qO-" "https://youtube.com/watch?v=f41aB2y8CvQ&t=604" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "wget" "-qO-" "https://www.logos.com/grow/bsm-literal-bible-translation/" "#" "<==" "pen-ci"
