cd /volumes/home/shane/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "rev-parse" "--show-toplevel" "#" "<==" "pen-ssh-host"
cd /volumes/home/shane/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "rev-parse" "--show-cdup" "#" "<==" "pen-ssh-host"
cd /volumes/home/shane/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "rev-parse" "--show-cdup" "#" "<==" "pen-ssh-host"
cd /volumes/home/shane/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "rev-parse" "--show-toplevel" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/bible-books/bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/bible-books/bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/bible-books/bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/bible-books/bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/bible-books/bible-book" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/tmp;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.pen/tmp;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.pen/tmp/emacs-stdin-.e3yeMtj" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/pen" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.emacs.d/host/pen.el/scripts/pen" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "scripts/pen" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "pen" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/prompting;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/prompting;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/prompting/ii" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/prompting;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.emacs.d/host/pen.el/scripts/prompting/ii" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "scripts/prompting/ii" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/prompting;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "ii" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/prompting;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/prompting;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.emacs.d/host/pen.el/scripts/utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "scripts/utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/utils.sh" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "bible-book" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/bible-books;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/scripts/bible-books/bible-book" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "timeit"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "timeit"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /;  "cterm-ssh" "-ssh" "-t" "-M" "sh" "#" "<==" "tclsh8.6"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes/ws;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /volumes/home/shane/var/smulliga/source/git/emacs-mirror/emacs;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--abbrev-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /volumes/home/shane/var/smulliga/source/git/emacs-mirror/emacs;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--abbrev-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /volumes/home/shane/var/smulliga/source/git/emacs-mirror/emacs;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /volumes/home/shane/var/smulliga/source/git/emacs-mirror/emacs;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "config" "--get-all" "credential.helper" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/eshell;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/eshell;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/eshell;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/eshell/alias" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/eshell;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/eshell/alias" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/eshell;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.emacs.d/eshell/alias" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/eshell;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.emacs.d/eshell/alias" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/eshell;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/eshell/alias" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/eshell;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/eshell/alias" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/elpa/tree-sitter-langs-20231013.651;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--show-toplevel" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/elpa/tree-sitter-langs-20231013.651;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--show-toplevel" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/build;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/melpa;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "remote" "show" "-n" "origin" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/melpa;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "fetch" "--tags" "origin" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/melpa;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "remote" "show" "origin" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/melpa;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "cat-file" "-e" "origin/master" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/melpa;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "checkout" "origin/master" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/melpa;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "submodule" "sync" "--recursive" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/melpa;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "submodule" "update" "--init" "--recursive" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/quelpa/melpa;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "log" "--first-parent" "-n1" "--pretty=format:'%ci'" ".dir-locals.el" ".git" ".github" ".gitignore" "CONTRIBUTING.org" "LICENSE.md" "Makefile" "README.md" "docker" "html" "html-stable" "logo" "package-build" "packages" "packages-stable" "recipes" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/src/pen.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.emacs.d/host/pen.el/src/pen.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "src/pen.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "pen.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff-index" "--exit-code" "-U0" "-p" "HEAD" "--" "pen.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/src/pen.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/src/pen-editing.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.emacs.d/host/pen.el/src/pen-editing.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "src/pen-editing.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "pen-editing.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/programs/tmux/capture;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/programs/tmux/capture;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.emacs.d/host/pen.el/src/pen-documents.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.emacs.d/host/pen.el/src/pen-documents.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "src/pen-documents.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "pen-documents.el" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.pen/glossaries/babylonia.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.pen/glossaries/babylonia.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "babylonia.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "babylonia.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.pen/glossaries/australian.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.pen/glossaries/australian.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "australian.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "australian.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.pen/glossaries/china.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.pen/glossaries/china.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "china.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "china.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--is-inside-work-tree" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "diff" "--no-color" "--no-ext-diff" "-U0" "/root/.pen/glossaries/chinese-fables.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "check-attr" "-z" "-a" "/root/.pen/glossaries/chinese-fables.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "ls-files" "-c" "-z" "--" "chinese-fables.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "status" "--porcelain" "-z" "--untracked-files" "--ignored" "--" "chinese-fables.txt" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "rev-parse" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/glossaries;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--no-pager" "symbolic-ref" "HEAD" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "timeit"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "-v" "-M" "--" "zsh" "#" "<==" "shx"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "-v" "--" "zsh" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "timeit"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/src;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "timeit"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "timeit"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "timeit"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--git-dir" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "status" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "rev-parse" "--show-toplevel" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/config;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "shx"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/container;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts/container;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.emacs.d/host/pen.el/scripts;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "debug"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "--" "hello-world" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
cd /root/.pen/documents/notes;  "cterm-ssh" "-ssh-to-host" "y" "-ssh" "git" "--version" "#" "<==" "pen-ssh-host"
