;;; eshell-toggle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eshell-toggle.el

(autoload 'eshell-toggle "eshell-toggle" "\
Show eshell at the bottom of current window and cd to current buffer's path.
(1) If eshell-toggle'd buffer is already visible in frame for
current buffer then select (toggled) eshell window.
(2) If current window is (toggled) eshell itself then hide it.
(3) If KEEP-VISIBLE is non-nil, (toggled) eshell window will stay
visible and will not be hidden.

(fn &optional KEEP-VISIBLE)" t)
(register-definition-prefixes "eshell-toggle" '("eshell-toggle-"))

;;; End of scraped data

(provide 'eshell-toggle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eshell-toggle-autoloads.el ends here
