;;; notmuch-indicator-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from notmuch-indicator.el

(defvar notmuch-indicator-mode nil "\
Non-nil if Notmuch-Indicator mode is enabled.
See the `notmuch-indicator-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `notmuch-indicator-mode'.")
(custom-autoload 'notmuch-indicator-mode "notmuch-indicator" nil)
(autoload 'notmuch-indicator-mode "notmuch-indicator" "\
Display mode line indicator with `notmuch-count(1)' output.

For the search terms and the label that can accompany them, refer
to the user option `notmuch-indicator-args'.

To control how often the indicator is updated, check the user
option `notmuch-indicator-refresh-count'..

This is a global minor mode.  If called interactively, toggle the
`Notmuch-Indicator mode' mode.  If the prefix argument is
positive, enable the mode,  and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='notmuch-indicator-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "notmuch-indicator" '("notmuch-indicator-"))

;;; End of scraped data

(provide 'notmuch-indicator-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; notmuch-indicator-autoloads.el ends here
