cd /root/.pen/documents/notes;  "hsqc" "ved" "# <==" "hsqc"
cd /root/.pen/documents/notes;  "hsqc" "ved" "-m" "# <==" "hsqc"
cd /root/.pen/documents/notes;  "hsqc" "ved -m" "# <==" "hsqc"
cd /root/.pen/documents/notes;  "hsqc" "ved" "# <==" "hsqc"
cd /root/.pen/documents/notes;  "hsqc" "ved" "# <==" "hsqc"
cd /root/.pen/documents/notes;  "hsqc" "ved" "# <==" "hsqc"
cd /root/.pen/documents/notes;  "hsqc" "ved" "# <==" "hsqc"
cd /root/.pen/documents/notes;  "hsqc" "vedm" "# <==" "hsqc"
