Firstly, my measuring stick for affirming people to be in Christ is I would affirm anyone who, firstly, openly confesses Jesus Christ is the Son of God to me, secondly I would affirm anyone who is trusting on the Lord Jesus Christ, God's Only-Begotten Son for their salvation, with a will to do God's will, obedient to Jesus Christ's teaching of repentance from sin, repentance from dead work (work not done in faith), turning towards obedience and loving service towards God.

Secondly, we are collectively being sanctified in the Truth. Within Christ, Jesus, the head of the body of Christ, has the perfect vision:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%207%3A3-5&version=ESV][Matthew 7:3-5]]* - Why do you see the speck that is in your brother's eye, but do not notice the log that is in your own eye? Or how can you say to your brother, Let me take the speck out of your eye, when there is the log in your own eye? You hypocrite, first take the log out of your own eye, and then you will see clearly to take the speck out of your brother's eye. (ESV)
#+END_QUOTE

Then You have Father God, who as Jesus was in the flesh and at that time, Jesus referred to as having knowledge of the end, which Jesus, God's Son, didn't have in that moment:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%2024%3A36&version=ESV][Matthew 24:36]]* - But concerning that day and hour no one knows, not even the angels of heaven, nor the Son, but the Father only. (ESV)
#+END_QUOTE

I believe that Jesus is the Alpha and the Omega. This declaration in Revelation shows that Jesus now sees the end:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Revelation%2022%3A13-15&version=ESV][Revelation of John 22:13-15]]* - I am the Alpha and the Omega, the first and the last, the beginning and the end. Blessed are those who wash their robes, so that they may have the right to the tree of life and that they may enter the city by the gates. Outside are the dogs and sorcerers and the sexually immoral and murderers and idolaters, and everyone who loves and practices falsehood. (ESV)
#+END_QUOTE

We are sanctified by obedience to the Truth, and God's Word does say we are sanctified by obedience to the Truth including through the washing of the blood of Jesus Christ through obedience to Jesus, and that includes faith in Jesus, Him washing us first, Jesus being pre-eiminent. Jesus sanctified Himself so we may be sanctified.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2017%3A17&version=ESV][John 17:17]]* - Sanctify them in the truth; your word is truth. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2017%3A19&version=ESV][John 17:19]]* - And for their sake I consecrate myself, that they also may be sanctified in truth. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Peter%201%3A22&version=ESV][I Peter 1:22]]* - Having purified your souls by your obedience to the truth for a sincere brotherly love, love one another earnestly from a pure heart, (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2013%3A8&version=ESV][John 13:8]]* - Peter said to him, You shall never wash my feet. Jesus answered him, If I do not wash you, you have no share with me. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A10-11&version=ESV][I John 4:10-11]]* - In this is love, not that we have loved God but that he loved us and sent his Son to be the propitiation for our sins. Beloved, if God so loved us, we also ought to love one another. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A19&version=ESV][I John 4:19]]* - We love _because he first loved us._ (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Colossians%201%3A15&version=ESV][Colossians 1:15]]* - He is the image of the invisible God, the firstborn (*[[https://biblehub.com/interlinear/colossians/1-15.htm][4416. prototokos]]*) of all creation. (ESV)
#+END_QUOTE

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  prototokos: first-born
  Original Word: πρωτότοκος, ον
  Part of Speech: Adjective
  Transliteration: prototokos
  Phonetic Spelling: (pro-tot-ok'-os)
  Definition: first-born
  Usage: first-born, eldest.
  HELPS Word-studies

  4416 prōtótokos (from 4413 /prṓtos, "first, pre-eminent" and 5088 /tíktō, "bring forth") – properly, first in time ([[https://www.biblegateway.com/passage/?search=Matthew%201%3A25&version=ESV][Mt 1:25]]; Lk 2:7); hence, pre-eminent (Col 1:15; Rev 1:5).

  4416 /prōtótokos ("firstly") specifically refers to Christ as the first to experience glorification, i.e. at His resurrection (see [[https://www.biblegateway.com/passage/?search=Hebrews%2012%3A23&version=ESV][Heb 12:23]]; Rev 1:5). For this (and countless other reasons) Jesus is "preeminent" (4416 /prōtótokos) – the unequivocal Sovereign over all creation ([[https://www.biblegateway.com/passage/?search=Colossians%201%3A16&version=ESV][Col 1:16]]).

  [4416 (prōtótokos) refers to "the first among others (who follow)" – as with the preeminent, glorified Christ, the eternal Logos who possesses self-existent life ([[https://www.biblegateway.com/passage/?search=John%205%3A26&version=ESV][Jn 5:26]]).]
#+END_SRC

That being said, I don't affirm these opinionated 'thought-for-thought' translations of the Bible as 'Scripture':

- NLT (New Living Translation)
  - I do not consider this Bible as Scripture, because I have found that it rewrites verses entirely to suit an opinionated 'faith-mutually-excluding-obedience' theology. It may be useful as an opinionated thought-for-thought translation, but isn't in the same league as the more literal translations such as NASB, ESV, and KJV.

- NWT (New World Translation)
  - I think that Bible translations such as the ESV, correctly are reserved about printing the LORD's name inline throughout the whole Bible. The JW, as they consolidate their Bible translation (NWT) using the LORD's name, seems to me either like an effort to try to engineer God, or self-affirm their own understanding, which is self-exalting but may (especially by those in their congregation) be done in ignorance. I do not affirm the NWT translation, but I do affirm the doctrine of [[https://www.reformationbiblecollege.org/blog/the-five-solas][Sola Scriptura]].
