*** Eternity
- eternal chains      :: *Jude 1:6* -And the angels who did not stay within their own position of authority, but left their proper dwelling, he has kept in eternal chains under gloomy darkness until the judgment of the great day—           
- eternal comfort     :: *II Thessalonians 2:16* -Now may our Lord Jesus Christ himself, and God our Father, who loved us and gave us eternal comfort and good hope through grace,                                                              
- eternal covenant    :: *Hebrews 13:20* -Now may the God of peace who brought again from the dead our Lord Jesus, the great shepherd of the sheep, by the blood of the eternal covenant,                                                       
- eternal destruction :: *II Thessalonians 1:9* -They will suffer the punishment of eternal destruction, away from the presence of the Lord and from the glory of his might,                                                                    
- eternal dominion    :: *I Timothy 6:16* -who alone has immortality, who dwells in unapproachable light, whom no one has ever seen or can see. To him be honor and eternal dominion. Amen.                                                     
- eternal dwellings   :: *Luke 16:9* -And I tell you, make friends for yourselves by means of unrighteous wealth, so that when it fails they may receive you into the eternal dwellings.                                                        
- eternal fire        :: *Matthew 25:41* -Then he will say to those on his left, Depart from me, you cursed, into the eternal fire prepared for the devil and his angels.                                                                       
- eternal glory       :: *II Timothy 2:10* -Therefore I endure everything for the sake of the elect, that they also may obtain the salvation that is in Christ Jesus with eternal glory.                                                        
- eternal gospel      :: *Revelation of John 14:6* -Then I saw another angel flying directly overhead, with an eternal gospel to proclaim to those who dwell on earth, to every nation and tribe and language and people.                       
- eternal home        :: *II Corinthians 5:1* -For we know that if the tent, which is our earthly home, is destroyed, we have a building from God, a house not made with hands, eternal in the heavens.                                         
- eternal inheritance :: *Hebrews 9:15* -Therefore he is the mediator of a new covenant, so that those who are called may receive the promised eternal inheritance, since a death has occurred that redeems them from the transgressions committed under the first covenant. 
- eternal judgment    :: *Hebrews 6:2* -and of instruction about washings, the laying on of hands, the resurrection of the dead, and eternal judgment.                                                                                          
- eternal kingdom     :: *II Peter 1:11* -For in this way there will be richly provided for you an entrance into the eternal kingdom of our Lord and Savior Jesus Christ.                                                                       
- eternal life        :: *Jude 1:21* -keep yourselves in the love of God, waiting for the mercy of our Lord Jesus Christ that leads to eternal life.                                                                                            
- eternal power       :: *Romans 1:20* -For his invisible attributes, namely, his eternal power and divine nature, have been clearly perceived, ever since the creation of the world, in the things that have been made. So they are without excuse. 
- eternal punishment  :: *Matthew 25:46* -And these will go away into eternal punishment, but the righteous into eternal life.                                                                                                                  
- eternal purpose     :: *Ephesians 3:11* -This was according to the eternal purpose that he has realized in Christ Jesus our Lord,                                                                                                             
- eternal redemption  :: *Hebrews 9:12* -he entered once for all into the holy places, not by means of the blood of goats and calves but by means of his own blood, thus securing an eternal redemption.                                        
- eternal salvation   :: *Hebrews 5:9* -And being made perfect, he became the source of eternal salvation to all who obey him,                                                                                                                  
- eternal sin         :: *Mark 3:29* -but whoever blasphemes against the Holy Spirit never has forgiveness, but is guilty of an eternal sin—                                                                                                    

- everlasting arms :: *Deuteronomy 33:27* - The eternal God is your dwelling place, and underneath are the everlasting arms. And he thrust out the enemy before you and said, Destroy.
- everlasting burnings :: *Isaiah 33:14* - The sinners in Zion are afraid; trembling has seized the godless: Who among us can dwell with the consuming fire? Who among us can dwell with everlasting burnings?
- everlasting contempt :: *Daniel 12:2* - And many of those who sleep in the dust of the earth shall awake, some to everlasting life, and some to shame and everlasting contempt.
- everlasting covenant :: *Genesis 9:16* - When the bow is in the clouds, I will see it and remember the everlasting covenant between God and every living creature of all flesh that is on the earth.
- everlasting desolation :: *Jeremiah 25:9* - behold, I will send for all the tribes of the north, declares the Lord, and for Nebuchadnezzar the king of Babylon, my servant, and I will bring them against this land and its inhabitants, and against all these surrounding nations. I will devote them to destruction, and make them a horror, a hissing, and an everlasting desolation.
- everlasting dominion :: *Daniel 7:14* - And to him was given dominion and glory and a kingdom, that all peoples, nations, and languages should serve him; his dominion is an everlasting dominion, which shall not pass away, and his kingdom one that shall not be destroyed.
- everlasting joy :: *Isaiah 51:11* - And the ransomed of the Lord shall return and come to Zion with singing; everlasting joy shall be upon their heads; they shall obtain gladness and joy, and sorrow and sighing shall flee away.
- everlasting kingdom :: *Daniel 7:27* - And the kingdom and the dominion and the greatness of the kingdoms under the whole heaven shall be given to the people of the saints of the Most High; their kingdom shall be an everlasting kingdom, and all dominions shall serve and obey them.
- everlasting life :: *Daniel 12:2* - And many of those who sleep in the dust of the earth shall awake, some to everlasting life, and some to shame and everlasting contempt.
- everlasting light :: *Isaiah 60:20* - Your sun shall no more go down, nor your moon withdraw itself; for the Lord will be your everlasting light, and your days of mourning shall be ended.
- everlasting love :: *Isaiah 54:8* - In overflowing anger for a moment I hid my face from you, but with everlasting love I will have compassion on you, says the Lord, your Redeemer.
- everlasting name :: *Isaiah 56:5* - I will give in my house and within my walls a monument and a name better than sons and daughters; I will give them an everlasting name that shall not be cut off.
- everlasting possession :: *Genesis 17:8* - And I will give to you and to your offspring after you the land of your sojournings, all the land of Canaan, for an everlasting possession, and I will be their God.
- everlasting reproach :: *Jeremiah 23:40* - And I will bring upon you everlasting reproach and perpetual shame, which shall not be forgotten.
- everlasting King :: *Jeremiah 10:10* - But the Lord is the true God; he is the living God and the everlasting King. At his wrath the earth quakes, and the nations cannot endure his indignation.
- everlasting righteousness :: *Daniel 9:24* - Seventy weeks are decreed about your people and your holy city, to finish the transgression, to put an end to sin, and to atone for iniquity, to bring in everlasting righteousness, to seal both vision and prophet, and to anoint a most holy place.
- everlasting rock :: *Isaiah 26:4* - Trust in the Lord forever, for the Lord God is an everlasting rock.
- everlasting ruins :: *Psalms 9:5-6* - You have rebuked the nations; you have made the wicked perish; you have blotted out their name forever and ever. The enemy came to an end in everlasting ruins; their cities you rooted out; the very memory of them has perished.
- everlasting salvation :: *Isaiah 45:17* - But Israel is saved by the Lord with everlasting salvation; you shall not be put to shame or confounded to all eternity.
- everlasting shame :: *Psalms 78:66* - And he put his adversaries to rout; he put them to everlasting shame.
- everlasting sign :: *Isaiah 55:13* - Instead of the thorn shall come up the cypress; instead of the brier shall come up the myrtle; and it shall make a name for the Lord, an everlasting sign that shall not be cut off.
- everlasting waste :: *Jeremiah 49:33* - Hazor shall become a haunt of jackals, an everlasting waste; no man shall dwell there; no man shall sojourn in her.
- everlasting ways :: *Habakkuk 3:6* - He stood and measured the earth; he looked and shook the nations; then the eternal mountains were scattered; the everlasting hills sank low. His were the everlasting ways.
