* Valentinus
[[https://www.earlychristianwritings.com/text/valentinian.html][A Valentinian Exposition]]

** Refutations
*** Refutation of All Heresies (Hippolytus)

[[https://www.newadvent.org/fathers/050106.htm][CHURCH FATHERS: Refutation of All Heresies, Book VI {Hippolytus}]]

* WATV - World Mission Society Church of God
- Positives:
  - They believe obedience is important to faith.
- Problems:
  - They believe the Father is the Son exactly
  - They believe in God the Mother
  - They believe Gentiles are under the Mosaic law.

* Calvinism
Heresies:
- bad interpretation of the Bible
- cheap grace

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  "Cheap grace is the preaching of forgiveness
  without requiring repentance, baptism without
  church discipline.

  Communion without confession.

  Cheap grace is grace without discipleship,
  grace without the cross, grace without Jesus
  Christ."
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  "Costly grace confronts us as a gracious call
  to follow Jesus, it comes as a word of
  forgiveness to the broken spirit and the
  contrite heart.

  It is costly because it compels a man to
  submit to the yoke of Christ and follow him;
  it is grace because Jesus says: "My yoke is
  easy and my burden is light."
#+END_SRC

I believe that in many ways Calvinism has gone
too far with not believing that repentance is
something we must do for our own salvation-sake.

“Forgiveness does not mean excusing.” ~C.S. Lewis

** The Calvinistic heresy regarding regeneration
#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  John 1:12
#+END_SRC

#+RESULTS:
#+begin_src text
John 1:12
‾‾‾‾‾‾‾‾‾
But to all who did receive him, who believed
in his name, he gave the right to become
children of God,

(ESV)
#+end_src

That is, people are not given the right to become children of God until they believe in Christ.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Galatians 3:26
#+END_SRC

#+RESULTS:
#+begin_src text
Galatians 3:26
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
for in Christ Jesus you are all sons of God,
through faith.

(ESV)
#+end_src

But Calvinists have it backwards. Under Calvinism a person cannot believe
until he's been born of God. They get the order of faith and regeneration _backwards._
