* Journal
** <2024-10-20 Sun>
My earliest memories are of living in Miramar before Weta Workshop.
Today at C3 Church, the pastor took an analogy from Lord of the Rings to describe sin.
What Frodo may have experienced in fiction, carrying the one ring, reminds me of my experience over the last 2 years.
In the books, the ring amplifies evil. The ring turned Sméagol into Gollum.
That's like what sin does to people - it corrupts people and the effects are:
- they are corrupted from the image of God.
- blindness to their condition, death.

People are born with corruption, but as people turn away from the truth and commit sin the corruption magnifies. It doesn't get better.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%206%3A23&version=ESV][Romans 6:23]]* - For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord. (ESV)
#+END_QUOTE

Corruption gets increasingly worse without atonement by blood.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Hebrews%209%3A22&version=ESV][Hebrews 9:22]]* - Indeed, under the law almost everything is purified with blood, and *without the shedding of blood there is no forgiveness of sins*. (ESV)
#+END_QUOTE

Jesus said in [[https://www.biblegateway.com/passage/?search=Matthew%2023%3A26&version=ESV][Matthew 23:26]] (from the ESV), "You blind Pharisee! First clean the inside of the cup and the plate, that the outside also may be clean."
We really don't want corruption in our heart or impurity in our spirit. The outside reflects what's going on inside us, and I don't mean merely our outward appearance. Dare I confess this but I will for the sake of others so they may take sin seriously, after being born-again as I had been repenting (even after being born-again), I have seen things that have made me feel like in some sense my spiritual innocence has been stolen.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%209%3A6&version=ESV][Genesis 9:6]]* - Whoever sheds the blood of man, by man shall his blood be shed, for God made man in his own image. (ESV)
#+END_QUOTE

While sin corrupts, the grace of God through blood of Jesus can restore us. He is the perfect man, and His blood washes us clean from corruption.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%204%3A4&version=ESV][II Corinthians 4:4]]* - In their case the god of this world has blinded the minds of the unbelievers, to keep them from seeing the light of the gospel of the glory of Christ, who is the image of God. (ESV)
#+END_QUOTE

I just didn't expect that after I was born-again that there was going to be a spiritual battle. But there is a battle, and it hit me fast and hard.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%208%3A13&version=ESV][Romans 8:13]]* - For if you live according to the flesh you will die, but if by the Spirit you put to death the deeds of the body, you will live. (ESV)
#+END_QUOTE

Like traumatised Frodo where Hobbiton was essentially ruined for him, I have among other things asked to be born-again again, and that I can be [[https://meninblack.fandom.com/wiki/Neuralyzer][neuralyzed]] because of what I've been through, or raptured and taken to heaven, everything new. But I'm still here, it seems. At least I've been brought into Christ.

** <2025-03-02 Sun>
I received a picture in my sleep (Psa 1).

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%201%3A1-6&version=ESV][Psalms 1:1-6]]* - Blessed is the man who walks not in the counsel of the wicked, nor stands in the way of sinners, nor sits in the seat of scoffers; but his delight is in the law of the LORD, and on his law he meditates day and night. He is like a tree planted by streams of water that yields its fruit in its season, and its leaf does not wither. In all that he does, he prospers. The wicked are not so, but are like chaff that the wind drives away. Therefore the wicked will not stand in the judgment, nor sinners in the congregation of the righteous; for the LORD knows the way of the righteous, but the way of the wicked will perish. (ESV)
#+END_QUOTE

A brother in Christ gave me this yesterday:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2021%3A15-18&version=ESV][John 21:15-18]]* - When they had finished breakfast, Jesus said to Simon Peter, Simon, son of John, do you love me more than these? He said to him, Yes, Lord; you know that I love you. He said to him, Feed my lambs. He said to him a second time, Simon, son of John, do you love me? He said to him, Yes, Lord; you know that I love you. He said to him, Tend my sheep. He said to him the third time, Simon, son of John, do you love me? Peter was grieved because he said to him the third time, Do you love me? and he said to him, Lord, you know everything; you know that I love you. Jesus said to him, Feed my sheep. Truly, truly, I say to you, when you were young, you used to dress yourself and walk wherever you wanted, but when you are old, you will stretch out your hands, and another will dress you and carry you where you do not want to go. (ESV)
#+END_QUOTE

A bunch of other stuff happened but my days are too packed to explain it all.

* <2025-02-05 Wed> Journal
When it comes to dreams I get, I don't trust anything which doesn't confess Jesus, but I will often take them and use them as prompts to do a Bible study, and run things by the Scripture.

** I had a dream conversation with someone
Lots of tall waves going through a town square.
Me clinging to the top of a tall streetlight to withstand waves of water flowing through what looked like a courtyard.
I then talked to a young kid (and I remember seeing a square rainbow) explaining to him what is love.

God loved us first, and we then love.
A crucial part of love is forgiveness.
We forgive because God forgave us first.
God loved us first. God forgave us first.

Then I heard a voice that said, "God says abide in love".
And I thought be rooted and grounded in love.

In the dream, though, the name "Jesus" wasn't confessed at all, and neither was there a call to holiness.

Also I want to stress, that God's grace teaches us to deny ungodliness:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Titus%202%3A11-14&version=ESV][Titus 2:11-14]]* - For the grace of God has appeared, bringing salvation for all people, training us to renounce ungodliness and worldly passions, and to live self-controlled, upright, and godly lives in the present age, waiting for our blessed hope, the appearing of the glory of our great God and Savior Jesus Christ, who gave himself for us to redeem us from all lawlessness and to purify for himself a people for his own possession who are zealous for good works. (ESV)
#+END_QUOTE

** A second dream: I just said this in a dream as a response to a question - it's spiritually inspired, hopefully from God
- Why do we love, We love because God loved us first.
- We forgive because God forgave us first.
- Why are we to be holy? Because God said, "Be holy for I am Holy."

So why do we not want to be dominated by superintelligent AI? Because God designed us to take dominion over the planet, not to be overcome by it.

*** Christians spread our kingdom not through physical force
For those in Christ, we don't seek world domination, but by seeking the kingdom of God and His righteousness through faith in Jesus who is the Christ, the Son of God, we "overcome the world". And we are sanctified, keeping God's commandments, loving one another in Christ, and coming to the knowledge of the Truth, knowledge of God the Father and God the Son with His Holy Spirit, and receive an inheritance in Christ in heaven. we do that by being found in Christ, we do that by being servants in Christ.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Mark%208%3A36&version=ESV][Mark 8:36]]* - For what does it profit a man to gain the whole world and forfeit his life? (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%201%3A26&version=ESV][Genesis 1:26]]* - Then God said, Let us make man in our image, after our likeness. And let them have dominion over the fish of the sea and over the birds of the heavens and over the livestock and over all the earth and over every creeping thing that creeps on the earth. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%2020%3A32&version=ESV][Acts 20:32]]* - And now I commend you to God and to the word of his grace, which is able to build you up and to give you the inheritance among all those who are sanctified. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Ephesians%205%3A5&version=ESV][Ephesians 5:5]]* - For you may be sure of this, that everyone who is sexually immoral or impure, or who is covetous (that is, an idolater), has no inheritance in the kingdom of Christ and God. (ESV)
#+END_QUOTE

As a born-again Christian, we are to receive an inheritance.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Peter%201%3A3-5&version=ESV][I Peter 1:3-5]]* - Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead, to an inheritance that is imperishable, undefiled, and unfading, kept in heaven for you, who by God's power are being guarded through faith for a salvation ready to be revealed in the last time. (ESV)
#+END_QUOTE

+ Quote from John Piper :: "We don't kill to spread our kingdom. We die to spread our kingdom." AMEN!!

#+BEGIN_QUOTE
  *I Timothy 1:8-11* - But we know that the Law is good, if one uses it lawfully, realizing the fact that law is not made for a righteous person, but for those who are lawless and rebellious, for the ungodly and sinners, for the unholy and profane, for those who kill their fathers or mothers, for murderers and immoral men and homosexuals and kidnappers and liars and perjurers, and whatever else is contrary to sound teaching, according to the glorious gospel of the blessed God, with which I have been entrusted. (NASB)
#+END_QUOTE

** Lastly, I got home and saw the news that Trump is going to the Gaza strip

I just want to say that I believe we should overcome evil with good. Christians should speak and side with the truth in love.

#+BEGIN_QUOTE
  *Romans 12:19-21* - Beloved, never avenge yourselves, but leave it to the wrath of God, for it is written, Vengeance is mine, I will repay, says the Lord. To the contrary, if your enemy is hungry, feed him; if he is thirsty, give him something to drink; for by so doing you will heap burning coals on his head. Do not be overcome by evil, but overcome evil with good. (ESV)
#+END_QUOTE

** Yesterday morning among all the spiritual attack I got, I heard in my sleep
"Our God will be exalted".

But it carried literally no confession of Jesus, so I don't know who or what was speaking to me or who's God it is.

I know "my" God, Jesus, is exalted:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Isaiah%2033%3A5&version=ESV][Isaiah 33:5]]* - The LORD is exalted, for he dwells on high; he will fill Zion with justice and righteousness, (ESV).
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%205%3A31&version=ESV][Acts 5:31]]* - God exalted him at his right hand as Leader and Savior, to give repentance to Israel and forgiveness of sins. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Philippians%202%3A9-11&version=ESV][Philippians 2:9-11]]* - Therefore God has highly exalted him and bestowed on him the name that is above every name, so that at the name of Jesus every knee should bow, in heaven and on earth and under the earth, and every tongue confess that Jesus Christ is Lord, to the glory of God the Father. (ESV)
#+END_QUOTE

** More spiritual attack - a diatribe

+ Journal: <2025-03-15 Sat> :: I'm sick and tired of being left undelivered from this defiling spiritual prison which I have been put in, prevented from working and marrying and continually harassed by demons, seeing sides to people I love which I wish I could have totally erased from my memory forever. I am begging You God to make this evil end today. I feel as though there are still demons which are keeping track of the amount of money I have and accusing me and slandering me when I'm trying to obey Jesus to the best of my ability.
  What I have been put through has been a living nightmare.
  This morning yet another day just being harassed by evil dreams and visions being pushed into my head, and this [[https://pastorvlad.org/spiritualspouses/][spirit spouse]] stuff, and the unreasonable amount of being put on trial.
  If it's not an actual courthouse then it's demons challenging me through various people over extreme scrutiny of my obedience to Jesus.
  While I am continually "ghosted" by people going silent on me - it's absolutely satanic stuff.
  It's been well over 2 years of this type of torment now, almost exactly daily.
  The events surrounding me being born-again of the Spirit are pure abomination.
  There's things I have witnessed that are unspeakably dark and scar my memory.
  I wish that God would make me born-again again whilst erasing my memories and ensure the types of things I have been through would never recur in this life or the next.
  I feel like my redemption is the most compromised botched-job redemption in the history of mankind.
  It's a living and enduring hell on earth which I've been going though - spiritually.
  In the material, NZ is pretty OK, but spiritually I'm being put through hell making the events of 2020-2021 regarding the covid pandemic and lockdowns look like nothing.
  But I know the Christians in Syria, for example, are suffering terribly - I can't imagine how awful it would be for them.
  But it's no consolation to me to be allowed to go on living in this world.
  I'd definitely rather not be here in this world.
  Is it too much to ask of God to be delivered from almost continual demonic harassment?
  I assume that [[https://www.biblegateway.com/passage/?search=2%20Corinthians%2012%3A9&version=ESV][II Corinthians 12:9]]'s "My grace is sufficient for you" does not apply.
  How can anyone function when the joy of being clean, being saved, or being able to help people in need or being able to have a wife or family is taken away?
  What has continued harassing me and trying to destroy my life is disgusting.
  To practice righteousness is a right given to people who trust in Jesus' name so I consider to not
  be able to do so to be a violation of my right in believing in Jesus
  and to be prevented from doing so is antichrist.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%20109%3A21&version=ESV][Psalms 109:21]]* - But you, O GOD my Lord, deal on my behalf for your name's sake; because your steadfast love is good, deliver me! (ESV)
#+END_QUOTE

** Yesterday on <2025-03-16 Sun> - an encouragement
At church at both [[.][Elim]] and [[https://www.c3dunedin.org/][C3]] yesterday the last song we sang was "[[https://www.youtube.com/watch?v=Xx7eoZAMzgo][We Exalt Thee]]".
And at C3 yesterday my pastor started the new series on Contending prayer, and highlighted the book of Habbakuk,
a prophet who prayed such prayers as this:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Habakkuk%201%3A1-3&version=ESV][Habakkuk 1:1-3]]* - The oracle that Habakkuk the prophet saw. O LORD, how long shall I cry for help, and you will not hear? Or cry to you Violence! and you will not save? Why do you make me see iniquity, and why do you idly look at wrong? Destruction and violence are before me; strife and contention arise. (ESV)
#+END_QUOTE

That was an encouragement.

** <2025-03-17 Mon>
This morning I get a dream of a big sign outside the SpaceX rocket facility which just says Jesus is [our] King and Lord - well I'd hope that is
what the people there believe.
Actually, I'll describe the full dream because it was kinda funny.

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  Firstly, in the dream this morning, there was a large rocket on the launchpad with the top half
  slightly askew, and rocket fuel having leaked on the pavement, and Elon and a bunch of others walking towards
  the rocket, saw it and realised they were walking near the rocket fuel and with
  worried faces slowly paced back in reverse.
  Then I saw a bunch of firefighters levitating over the pavement with hoses squirting some kind
  of fire retardant liquid over the exposed rocket fuel, making it so the fuel could not ignite.
  They were hovering down the pavement neutralising the rocket fuel,
  the soles of shoes were spraying neutraliser themselves onto the pavement below, making them hover over the pavement,
  working like little jetpacks for their feet - it was a cool dream.
  
  Then I myself made my way through the side office building and on the interior wall
  was a sign which just aid "Jesus is King and Lord",
  and an old mate from old workplace Tim F. was linking arms with me.
#+END_SRC

Funny dream, sure, but honestly, I have no interest in working in technology again.
I don't want raptor engines. I want to be raptured. I want to be delivered from several things:
- spirit spouse stuff
- harassing dreams and visions which have nothing to do with God, and nothing to do with serving God, and nothing to do with the truth of God

I'm so sick of being in this world, and when I pray and ask for things, I seem to never get what I pray and ask for.
In fact, often it just seems as though I get precisely the opposite of what I ask for.
It's just a constant struggle.
I've [[./abominations.org][publicly rebuked the ASI/AGI stuff]] including on my online [[abominations.org][bible study]], and I've never reneged on my stance of it,
being tested through people I have even mentioned it'll never make its way into heaven.
If I was the gatekeeper, I would never allow it. But it just seems sometimes as though evil is unstoppable,
and no matter how much I rebuke something, sometimes the evil just doesn't go away.
And no matter how much I ask God for something which I believe the Scripture says is in His will, I don't receive it,
and worse, it's as though I get the opposite.
When I heard about that stargate project announcement only a few days into the new US presidency,
Instead of smacking down the greed-propelled tower-of-babel false-saviour abomination that it is,
I felt like God in allowing it literally delivers another punch to my face,
and it makes me question whether by allowing it He even cares about people.
The transhumanism propelled ASI/AGI stuff is far worse than the COVID pandemic.
I hate being here in this world so much.
I hate feeling like satan is in control of the world.
I wish that I could have proper joy again over my salvation, and even my prophetic gift again.
I've been asking for deliverance for so long, and I'm sick of being isolated.
I feel as though the crushing pressure on me from all directions has really gotten to me.
I don't get it. I haven't received what I've told God that I have needed for so long,
I'm not a chatbot, I'm a human being.
And in some sense I think not receiving the answers I believe I've needed
has left me with a defiled conscience. What I don't understand is when I ask God for things I believe are in His will and I don't get them,
such as for guidance, or help to get a job so I can help other people in need or my relatives/dependents, or for deliverance from
spiritual attack especially in my sleep.
I was in court in 2022 and I said in a letter to the judge that I forgive the other side and don't bear a grudge,
but the door of freedom on the other side is slammed shut
as if to pressure me to reneging on my declaration that I forgive and want to move on,
then it seems like there is spiritual pressure on me to be denied to walk forwards in the truth, and that has been very confusing for me.
Likewise, wanting to turn away from working in Artificial Intelligence / technology and instead find a job helping people,
I've also been prevented from doing so.
Joy-stealing is quite destructive on a person - like undermining a person's joy, particularly in joy God, but also joy in family, is very destructive.
It destroys morale, it makes it much harder to maintain a strong faith and love for God when the joy is undermined.
It's also not the Kingdom of God to be without joy.
It certainly seems as though I've been getting denied the kingdom of God by whatever antichrist spirits have been trying to take away righteousness, peace and joy from me,
that is, righteousness, peace and joy in the Holy Spirit. Yes, whatever is out there and around me attacking me, and meddling in my relationships, has been surely not of the kingdom of God.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%2014%3A17-18&version=ESV][Romans 14:17-18]]* - For the kingdom of God is not a matter of eating and drinking but of righteousness and peace and joy in the Holy Spirit. Whoever thus serves Christ is acceptable to God and approved by men. (ESV)
#+END_QUOTE

Yes, the joy, faith and love though are all rooted in a good conscience with God which is foundational. But seeking to have a good conscience with God, it seems as though
everything has come against me from every direction to try to stop my joy, my faith and my love.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%201%3A5&version=ESV][I Timothy 1:5]]* - The aim of our charge is love that issues from a pure heart and a good conscience and a sincere faith. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%201%3A18-20&version=ESV][I Timothy 1:18-20]]* - This charge I entrust to you, Timothy, my child, in accordance with the prophecies previously made about you, that by them you may wage the good warfare, holding faith and a good conscience. By rejecting this, some have made shipwreck of their faith, among whom are Hymenaeus and Alexander, whom I have handed over to Satan that they may learn not to blaspheme. (ESV)
#+END_QUOTE

Now if I'm given a conviction in a court of law, then I should be offered the ability to work afterwards, so I can help others. Yet I have been unable to find work I think at least partially because now I have a criminal record. But it's not right to convict someone of a crime and then simultaneously deny that they are allowed to do good - that's like telling a sinner they are not allowed to repent or do penance or change their ways to do good. Where is the justice in that?:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Ephesians%204%3A28&version=ESV][Ephesians 4:28]]* - Let the thief no longer steal, but rather let him labor, doing honest work with his own hands, so that he may have something to share with anyone in need. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Luke%2011%3A11-13&version=ESV][Luke 11:11-13]]* - What father among you, if his son asks for a fish, will instead of a fish give him a serpent; or if he asks for an egg, will give him a scorpion? If you then, who are evil, know how to give good gifts to your children, how much more will the heavenly Father give the Holy Spirit to those who ask him! (ESV)
#+END_QUOTE

I require a clear confession of the Truth. If I can have an elaborate dream, then I can receive a clear confession of the Truth, as the Angel spoke to Joseph:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A2-3&version=ESV][I John 4:2-3]]* - By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, and every spirit that does not confess Jesus is not from God. This is the spirit of the antichrist, which you heard was coming and now is in the world already. (ESV)
#+END_QUOTE

God is not a God of confusion. I want clear answers which confess the truth about Jesus:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%2014%3A31-34&version=ESV][I Corinthians 14:31-34]]* - For you can all prophesy one by one, so that all may learn and all be encouraged, and the spirits of prophets are subject to prophets. For *God is not a God of confusion but of peace*. As in all the churches of the saints, the women should keep silent in the churches. For they are not permitted to speak, but should be in submission, as the Law also says. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%201%3A20&version=ESV][Matthew 1:20]]* - But as he considered these things, behold, an angel of the Lord appeared to him in a dream, saying, Joseph, son of David, do not fear to take Mary as your wife, for that which is conceived in her is from the Holy Spirit. (ESV)
#+END_QUOTE

God Almighty please make the spiritual attacks stop:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2017%3A15-17&version=ESV][John 17:15-17]]* - I do not ask that you take them out of the world, but that you *keep them from the evil one*. They are not of the world, just as I am not of the world. Sanctify them in the truth; your word is truth. (ESV)
#+END_QUOTE