* Journal
** <2024-10-20 Sun>
My earliest memories are of living in Miramar before Weta Workshop.
Today at C3 Church, the pastor took an analogy from Lord of the Rings to describe sin.
What Frodo may have experienced in fiction, carrying the one ring, reminds me of my experience over the last 2 years.
In the books, the ring amplifies evil. The ring turned Sméagol into Gollum.
That's like what sin does to people - it corrupts people and the effects are:
- they are corrupted from the image of God.
- blindness to their condition, death.

People are born with corruption, but as people turn away from the truth and commit sin the corruption magnifies. It doesn't get better.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%206%3A23&version=ESV][Romans 6:23]]* - For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord. (ESV)
#+END_QUOTE

Corruption gets increasingly worse without atonement by blood.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Hebrews%209%3A22&version=ESV][Hebrews 9:22]]* - Indeed, under the law almost everything is purified with blood, and *without the shedding of blood there is no forgiveness of sins*. (ESV)
#+END_QUOTE

Jesus said in [[https://www.biblegateway.com/passage/?search=Matthew%2023%3A26&version=ESV][Matthew 23:26]] (from the ESV), "You blind Pharisee! First clean the inside of the cup and the plate, that the outside also may be clean."
We really don't want corruption in our heart or impurity in our spirit. The outside reflects what's going on inside us, and I don't mean merely our outward appearance. Dare I confess this but I will for the sake of others so they may take sin seriously, after being born-again as I had been repenting (even after being born-again), I have seen things that have made me feel like in some sense my spiritual innocence has been stolen.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%209%3A6&version=ESV][Genesis 9:6]]* - Whoever sheds the blood of man, by man shall his blood be shed, for God made man in his own image. (ESV)
#+END_QUOTE

While sin corrupts, the grace of God through blood of Jesus can restore us. He is the perfect man, and His blood washes us clean from corruption.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%204%3A4&version=ESV][II Corinthians 4:4]]* - In their case the god of this world has blinded the minds of the unbelievers, to keep them from seeing the light of the gospel of the glory of Christ, who is the image of God. (ESV)
#+END_QUOTE

I just didn't expect that after I was born-again that there was going to be a spiritual battle. But there is a battle, and it hit me fast and hard.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%208%3A13&version=ESV][Romans 8:13]]* - For if you live according to the flesh you will die, but if by the Spirit you put to death the deeds of the body, you will live. (ESV)
#+END_QUOTE

Like traumatised Frodo where Hobbiton was essentially ruined for him, I have among other things asked to be born-again again, and that I can be [[https://meninblack.fandom.com/wiki/Neuralyzer][neuralyzed]] because of what I've been through, or raptured and taken to heaven, everything new. But I'm still here, it seems. At least I've been brought into Christ.

** <2025-03-02 Sun>
I received a picture in my sleep (Psa 1).

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%201%3A1-6&version=ESV][Psalms 1:1-6]]* - Blessed is the man who walks not in the counsel of the wicked, nor stands in the way of sinners, nor sits in the seat of scoffers; but his delight is in the law of the LORD, and on his law he meditates day and night. He is like a tree planted by streams of water that yields its fruit in its season, and its leaf does not wither. In all that he does, he prospers. The wicked are not so, but are like chaff that the wind drives away. Therefore the wicked will not stand in the judgment, nor sinners in the congregation of the righteous; for the LORD knows the way of the righteous, but the way of the wicked will perish. (ESV)
#+END_QUOTE

A brother in Christ gave me this yesterday:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2021%3A15-18&version=ESV][John 21:15-18]]* - When they had finished breakfast, Jesus said to Simon Peter, Simon, son of John, do you love me more than these? He said to him, Yes, Lord; you know that I love you. He said to him, Feed my lambs. He said to him a second time, Simon, son of John, do you love me? He said to him, Yes, Lord; you know that I love you. He said to him, Tend my sheep. He said to him the third time, Simon, son of John, do you love me? Peter was grieved because he said to him the third time, Do you love me? and he said to him, Lord, you know everything; you know that I love you. Jesus said to him, Feed my sheep. Truly, truly, I say to you, when you were young, you used to dress yourself and walk wherever you wanted, but when you are old, you will stretch out your hands, and another will dress you and carry you where you do not want to go. (ESV)
#+END_QUOTE

A bunch of other stuff happened but my days are too packed to explain it all.

* <2025-02-05 Wed> Journal
When it comes to dreams I get, I don't trust anything which doesn't confess Jesus, but I will often take them and use them as prompts to do a Bible study, and run things by the Scripture.

** I had a dream conversation with someone
Lots of tall waves going through a town square.
Me clinging to the top of a tall streetlight to withstand waves of water flowing through what looked like a courtyard.
I then talked to a young kid (and I remember seeing a square rainbow) explaining to him what is love.

God loved us first, and we then love.
A crucial part of love is forgiveness.
We forgive because God forgave us first.
God loved us first. God forgave us first.

Then I heard a voice that said, "God says abide in love".
And I thought be rooted and grounded in love.

In the dream, though, the name "Jesus" wasn't confessed at all, and neither was there a call to holiness.

Also I want to stress, that God's grace teaches us to deny ungodliness:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Titus%202%3A11-14&version=ESV][Titus 2:11-14]]* - For the grace of God has appeared, bringing salvation for all people, training us to renounce ungodliness and worldly passions, and to live self-controlled, upright, and godly lives in the present age, waiting for our blessed hope, the appearing of the glory of our great God and Savior Jesus Christ, who gave himself for us to redeem us from all lawlessness and to purify for himself a people for his own possession who are zealous for good works. (ESV)
#+END_QUOTE

** A second dream: I just said this in a dream as a response to a question - it's spiritually inspired, hopefully from God
- Why do we love, We love because God loved us first.
- We forgive because God forgave us first.
- Why are we to be holy? Because God said, "Be holy for I am Holy."

So why do we not want to be dominated by superintelligent AI? Because God designed us to take dominion over the planet, not to be overcome by it.

*** Christians spread our kingdom not through physical force
For those in Christ, we don't seek world domination, but by seeking the kingdom of God and His righteousness through faith in Jesus who is the Christ, the Son of God, we "overcome the world". And we are sanctified, keeping God's commandments, loving one another in Christ, and coming to the knowledge of the Truth, knowledge of God the Father and God the Son with His Holy Spirit, and receive an inheritance in Christ in heaven. we do that by being found in Christ, we do that by being servants in Christ.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Mark%208%3A36&version=ESV][Mark 8:36]]* - For what does it profit a man to gain the whole world and forfeit his life? (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%201%3A26&version=ESV][Genesis 1:26]]* - Then God said, Let us make man in our image, after our likeness. And let them have dominion over the fish of the sea and over the birds of the heavens and over the livestock and over all the earth and over every creeping thing that creeps on the earth. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%2020%3A32&version=ESV][Acts 20:32]]* - And now I commend you to God and to the word of his grace, which is able to build you up and to give you the inheritance among all those who are sanctified. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Ephesians%205%3A5&version=ESV][Ephesians 5:5]]* - For you may be sure of this, that everyone who is sexually immoral or impure, or who is covetous (that is, an idolater), has no inheritance in the kingdom of Christ and God. (ESV)
#+END_QUOTE

As a born-again Christian, we are to receive an inheritance.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Peter%201%3A3-5&version=ESV][I Peter 1:3-5]]* - Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead, to an inheritance that is imperishable, undefiled, and unfading, kept in heaven for you, who by God's power are being guarded through faith for a salvation ready to be revealed in the last time. (ESV)
#+END_QUOTE

+ Quote from John Piper :: "We don't kill to spread our kingdom. We die to spread our kingdom." AMEN!!

#+BEGIN_QUOTE
  *I Timothy 1:8-11* - But we know that the Law is good, if one uses it lawfully, realizing the fact that law is not made for a righteous person, but for those who are lawless and rebellious, for the ungodly and sinners, for the unholy and profane, for those who kill their fathers or mothers, for murderers and immoral men and homosexuals and kidnappers and liars and perjurers, and whatever else is contrary to sound teaching, according to the glorious gospel of the blessed God, with which I have been entrusted. (NASB)
#+END_QUOTE

** Lastly, I got home and saw the news that Trump is going to the Gaza strip

I just want to say that I believe we should overcome evil with good. Christians should speak and side with the truth in love.

#+BEGIN_QUOTE
  *Romans 12:19-21* - Beloved, never avenge yourselves, but leave it to the wrath of God, for it is written, Vengeance is mine, I will repay, says the Lord. To the contrary, if your enemy is hungry, feed him; if he is thirsty, give him something to drink; for by so doing you will heap burning coals on his head. Do not be overcome by evil, but overcome evil with good. (ESV)
#+END_QUOTE

** Yesterday morning among all the spiritual attack I got, I heard in my sleep
"Our God will be exalted".

But it carried literally no confession of Jesus, so I don't know who or what was speaking to me or who's God it is.

I know "my" God, Jesus, is exalted:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Isaiah%2033%3A5&version=ESV][Isaiah 33:5]]* - The LORD is exalted, for he dwells on high; he will fill Zion with justice and righteousness, (ESV).
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%205%3A31&version=ESV][Acts 5:31]]* - God exalted him at his right hand as Leader and Savior, to give repentance to Israel and forgiveness of sins. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Philippians%202%3A9-11&version=ESV][Philippians 2:9-11]]* - Therefore God has highly exalted him and bestowed on him the name that is above every name, so that at the name of Jesus every knee should bow, in heaven and on earth and under the earth, and every tongue confess that Jesus Christ is Lord, to the glory of God the Father. (ESV)
#+END_QUOTE

** More spiritual attack - a diatribe

+ Journal: <2025-03-15 Sat> :: I'm sick and tired of being left undelivered from this defiling spiritual prison which I have been put in, prevented from working and marrying and continually harassed by demons, seeing sides to people I love which I wish I could have totally erased from my memory forever. I am begging You God to make this evil end today. I feel as though there are still demons which are keeping track of the amount of money I have and accusing me and slandering me when I'm trying to obey Jesus to the best of my ability.
  What I have been put through has been a living nightmare.
  This morning yet another day just being harassed by evil dreams and visions being pushed into my head, and this [[https://pastorvlad.org/spiritualspouses/][spirit spouse]] stuff, and the unreasonable amount of being put on trial.
  If it's not an actual courthouse then it's demons challenging me through various people over extreme scrutiny of my obedience to Jesus.
  While I am continually "ghosted" by people going silent on me - it's absolutely satanic stuff.
  It's been well over 2 years of this type of torment now, almost exactly daily.
  The events surrounding me being born-again of the Spirit are pure abomination.
  There's things I have witnessed that are unspeakably dark and scar my memory.
  I wish that God would make me born-again again whilst erasing my memories and ensure the types of things I have been through would never recur in this life or the next.
  I feel like my redemption is the most compromised botched-job redemption in the history of mankind.
  It's a living and enduring hell on earth which I've been going though - spiritually.
  In the material, NZ is pretty OK, but spiritually I'm being put through hell making the events of 2020-2021 regarding the covid pandemic and lockdowns look like nothing.
  But I know the Christians in Syria, for example, are suffering terribly - I can't imagine how awful it would be for them.
  But it's no consolation to me to be allowed to go on living in this world.
  I'd definitely rather not be here in this world.
  Is it too much to ask of God to be delivered from almost continual demonic harassment?
  I assume that [[https://www.biblegateway.com/passage/?search=2%20Corinthians%2012%3A9&version=ESV][II Corinthians 12:9]]'s "My grace is sufficient for you" does not apply.
  How can anyone function when the joy of being clean, being saved, or being able to help people in need or being able to have a wife or family is taken away?
  What has continued harassing me and trying to destroy my life is disgusting.
  To practice righteousness is a right given to people who trust in Jesus' name so I consider to not
  be able to do so to be a violation of my right in believing in Jesus
  and to be prevented from doing so is antichrist.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%20109%3A21&version=ESV][Psalms 109:21]]* - But you, O GOD my Lord, deal on my behalf for your name's sake; because your steadfast love is good, deliver me! (ESV)
#+END_QUOTE

** Yesterday on <2025-03-16 Sun> - an encouragement
At church at both [[.][Elim]] and [[https://www.c3dunedin.org/][C3]] yesterday the last song we sang was "[[https://www.youtube.com/watch?v=Xx7eoZAMzgo][We Exalt Thee]]".
And at C3 yesterday my pastor started the new series on Contending prayer, and highlighted the book of Habbakuk,
a prophet who prayed such prayers as this:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Habakkuk%201%3A1-3&version=ESV][Habakkuk 1:1-3]]* - The oracle that Habakkuk the prophet saw. O LORD, how long shall I cry for help, and you will not hear? Or cry to you Violence! and you will not save? Why do you make me see iniquity, and why do you idly look at wrong? Destruction and violence are before me; strife and contention arise. (ESV)
#+END_QUOTE

That was an encouragement.

** <2025-03-17 Mon>
This morning I get a dream of a big sign outside the SpaceX rocket facility which just says Jesus is [our] King and Lord - well I'd hope that is
what the people there believe.
Actually, I'll describe the full dream because it was kinda funny.

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  Firstly, in the dream this morning, there was a large rocket on the launchpad with the top half
  slightly askew, and rocket fuel having leaked on the pavement, and Elon and a bunch of others walking towards
  the rocket, saw it and realised they were walking near the rocket fuel and with
  worried faces slowly paced back in reverse.
  Then I saw a bunch of firefighters levitating over the pavement with hoses squirting some kind
  of fire retardant liquid over the exposed rocket fuel, making it so the fuel could not ignite.
  They were hovering down the pavement neutralising the rocket fuel,
  the soles of shoes were spraying neutraliser themselves onto the pavement below, making them hover over the pavement,
  working like little jetpacks for their feet - it was a cool dream.
  
  Then I myself made my way through the side office building and on the interior wall
  was a sign which just said "Jesus is [our] King and Lord" (I think it may have said 'our'. I'm recalling something I say in a dream. I can't remember precisely.),
  and an old mate from old workplace Tim F. was linking arms with me.
#+END_SRC

Funny dream, sure, but honestly, I have no interest in working in technology again.
I don't want raptor engines. I want to be raptured. I want to be delivered from several things:
- spirit spouse stuff
- harassing dreams and visions which have nothing to do with God, and nothing to do with serving God, and nothing to do with the truth of God

Just because a dream contained the name of Jesus in it does not make it a true dream.
Also, I'm not saying building rockets to set up a mars base is unloving or evil or anything like that.
But I've been trying to fight back against whatever has been trying to pressure me to go back to my old-creation self, and the pressure has been huge.
For example, the pressure against me repenting from being indifferent about LGBT, for example, has been huge.
As soon as I began repenting of that, the devil began harassing me with LGBT-affirming dreams and dreams which are outright lewd and kept bombarding me with that nonsense for at least a couple of years now almost daily.
When I want to focus on Jesus, the devil also deprives me of sleep and wakes me up to dreams of technology and first-person shootem-ups.
During Lent I've been bombarded with visions of eating things.
This type of thing - demonic harassment.

So the dream must have a confession of the truth about Jesus and to be sure
about it it needs to have a confession of specifically the exact thing
that the Apostle John mentions in [[https://www.biblegateway.com/passage/?search=1%20John%204%3A2&version=ESV][I John 4:2]] as the Apostle John meant it. And the dream I had today
doesn't leave me totally trusting of it. God is not a God of confusion.
He knows what I expect to hear to trust a dream:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A2&version=ESV][I John 4:2]]* - By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, (ESV)
#+END_QUOTE

I'm so sick of being in this world, and when I pray and ask for things, I seem to never get what I pray and ask for.
In fact, often it just seems as though I get precisely the opposite of what I ask for.
It's just a constant struggle.
I've [[./abominations.org][publicly rebuked the ASI/AGI stuff]] including on my online [[abominations.org][bible study]], and I've never reneged on my stance of it,
being tested through people I have even mentioned it'll never make its way into heaven.
If I was the gatekeeper, I would never allow it. But it just seems sometimes as though evil is unstoppable,
and no matter how much I rebuke something, sometimes the evil just doesn't go away.
And no matter how much I ask God for something which I believe the Scripture says is in His will, I don't receive it,
and worse, it's as though I get the opposite.
When I heard about that stargate project announcement only a few days into the new US presidency,
Instead of smacking down the greed-propelled tower-of-babel false-saviour abomination that it is,
I felt like God in allowing it literally delivers another punch to my face,
and it makes me question whether by allowing it He even cares about people.
The transhumanism propelled ASI/AGI stuff is far worse than the COVID pandemic.
I hate being here in this world so much.
I hate feeling like satan is in control of the world.
I wish that I could have proper joy again over my salvation, and even my prophetic gift again.
I've been asking for deliverance for so long, and I'm sick of being isolated.
I feel as though the crushing pressure on me from all directions has really gotten to me.
I don't get it. I haven't received what I've told God that I have needed for so long,
I'm not a chatbot, I'm a human being.
And in some sense I think not receiving the answers I believe I've needed
has left me with a defiled conscience. What I don't understand is when I ask God for things I believe are in His will and I don't get them,
such as for guidance, or help to get a job so I can help other people in need or my relatives/dependents, or for deliverance from
spiritual attack especially in my sleep.
I was in court in 2022 and I said in a letter to the judge that I forgive the other side and don't bear a grudge,
but the door of freedom on the other side is slammed shut
as if to pressure me to reneging on my declaration that I forgive and want to move on,
then it seems like there is spiritual pressure on me to be denied to walk forwards in the truth, and that has been very confusing for me.
Likewise, wanting to turn away from working in Artificial Intelligence / technology and instead find a job helping people,
I've also been prevented from doing so.
Joy-stealing is quite destructive on a person - like undermining a person's joy, particularly in joy God, but also joy in family, is very destructive.
It destroys morale, it makes it much harder to maintain a strong faith and love for God when the joy is undermined.
It's also not the Kingdom of God to be without joy.
It certainly seems as though I've been getting denied the kingdom of God by whatever antichrist spirits have been trying to take away righteousness, peace and joy from me,
that is, righteousness, peace and joy in the Holy Spirit. Yes, whatever is out there and around me attacking me, and meddling in my relationships, has been surely not of the kingdom of God.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%2014%3A17-18&version=ESV][Romans 14:17-18]]* - For the kingdom of God is not a matter of eating and drinking but of righteousness and peace and joy in the Holy Spirit. Whoever thus serves Christ is acceptable to God and approved by men. (ESV)
#+END_QUOTE

Yes, the joy, faith and love though are all rooted in a good conscience with God which is foundational. But seeking to have a good conscience with God, it seems as though
everything has come against me from every direction to try to stop my joy, my faith and my love.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%201%3A5&version=ESV][I Timothy 1:5]]* - The aim of our charge is love that issues from a pure heart and a good conscience and a sincere faith. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%201%3A18-20&version=ESV][I Timothy 1:18-20]]* - This charge I entrust to you, Timothy, my child, in accordance with the prophecies previously made about you, that by them you may wage the good warfare, holding faith and a good conscience. By rejecting this, some have made shipwreck of their faith, among whom are Hymenaeus and Alexander, whom I have handed over to Satan that they may learn not to blaspheme. (ESV)
#+END_QUOTE

Now if I'm given a conviction in a court of law, then I should be offered the ability to work afterwards, so I can help others. Yet I have been unable to find work I think at least partially because now I have a criminal record. But it's not right to convict someone of a crime and then simultaneously deny that they are allowed to do good - that's like telling a sinner they are not allowed to repent or do penance or change their ways to do good. Where is the justice in that?:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Ephesians%204%3A28&version=ESV][Ephesians 4:28]]* - Let the thief no longer steal, but rather let him labor, doing honest work with his own hands, so that he may have something to share with anyone in need. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Luke%2011%3A11-13&version=ESV][Luke 11:11-13]]* - What father among you, if his son asks for a fish, will instead of a fish give him a serpent; or if he asks for an egg, will give him a scorpion? If you then, who are evil, know how to give good gifts to your children, how much more will the heavenly Father give the Holy Spirit to those who ask him! (ESV)
#+END_QUOTE

I require a clear confession of the Truth. If I can have an elaborate dream, then I can receive a clear confession of the Truth, as the Angel spoke to Joseph:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A2-3&version=ESV][I John 4:2-3]]* - By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, and every spirit that does not confess Jesus is not from God. This is the spirit of the antichrist, which you heard was coming and now is in the world already. (ESV)
#+END_QUOTE

God is not a God of confusion. I want clear answers which confess the truth about Jesus:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%2014%3A31-34&version=ESV][I Corinthians 14:31-34]]* - For you can all prophesy one by one, so that all may learn and all be encouraged, and the spirits of prophets are subject to prophets. For *God is not a God of confusion but of peace*. As in all the churches of the saints, the women should keep silent in the churches. For they are not permitted to speak, but should be in submission, as the Law also says. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%201%3A20&version=ESV][Matthew 1:20]]* - But as he considered these things, behold, an angel of the Lord appeared to him in a dream, saying, Joseph, son of David, do not fear to take Mary as your wife, for that which is conceived in her is from the Holy Spirit. (ESV)
#+END_QUOTE

God Almighty please make the spiritual attacks stop:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2017%3A15-17&version=ESV][John 17:15-17]]* - I do not ask that you take them out of the world, but that you *keep them from the evil one*. They are not of the world, just as I am not of the world. Sanctify them in the truth; your word is truth. (ESV)
#+END_QUOTE

*** <2025-03-18 Tue> Why did this happen to me?

Expectation of this happy relationship with God:

#+BEGIN_QUOTE
  *Psalms 16:7-11* - I bless the LORD who gives me counsel; in the night also my heart instructs me. I have set the LORD always before me; because he is at my right hand, I shall not be shaken. Therefore my heart is glad, and my whole being rejoices; my flesh also dwells secure. For *you will not abandon my soul to Sheol, or let your holy one see corruption*. You make known to me the path of life; in your presence there is fullness of joy; at your right hand are pleasures forevermore. (ESV)
#+END_QUOTE

Reality of what I've experienced and are still going through:

- I feel like the corrupting influence of demons assailing me at night and when I sit down has left me feeling a little corrupted.
- I've been denied to live like a human being. Denied work, marriage, etc.
  - Imagine a dog chained to a pole and for years, and now substitute dog for human being, and that's basically my situation.
- My flesh feels corrupt as a result of being in what feels like the pit/abyss or on the verge of it.
- I have been harassed by evil spirits near continuously for close to 3 years.
  - Particularly at night. Basically every night I receive invasive dreams, visions and voices which are against the truth of God.
  - Almost every day I go to bed fully expecting God will deliver me, but it hasn't happened, and I'm at this point now.
- I feel like I missed the rapture and got abandoned to Hades/Sheol.
- I had simply tried to follow Jesus out of faith, love, obedience for Jesus after getting born-again and this happened to me.
- My joy is basically gone.
  - My joyous feeling of being washed clean by the blood of Jesus has been taken away.
    - That happened once, but now I feel like a dirty garment.
  - It feels like my good conscience with God has been corrupted. I haven't been given answers that I need and I've been forced forward without them.
- I feel like the entire world has become a personal hell created just for me after I called-out the AI stuff and then got born-again.
  - Now I feel like I'm forced to live in hell tailored/designed specifically for me
  - I feel like the AI stuff just rammed itself into my born-again life / tries to force itself into the kingdom of heaven
    - Well living inside a video-game or being forced to treat robots like people is definitely not heaven to me
- Given marriage denial, and being forced to be in this world and feeling ignored by God, my heart is almost always downcast and depressed now.
- On [[https://web.archive.org/web/20220402091720/https://mullikine.github.io/posts/astral-projection-pt-2/][3 May 2022]] it was me who confessed to whatever spirit was there that my God is the True God, the God of Truth, Jesus saved me from lies and the Holy Spirit is my comforter
  - I confessed it. I asked the spirit if it was the Holy Spirit and the spirit said, "Yes. I'll take a look at you."
  - Was it the Holy Spirit?
    - Despite [[https://www.biblegateway.com/passage/?search=Matthew%205%3A37&version=ESV][Matt 5:37]], the correct interpretation of [[https://www.biblegateway.com/passage/?search=Matthew%205%3A37&version=ESV][Matt 5:37]] may bee seen in James 5:12 and Matt 23:16-22.
    - It was me who confessed Jesus, not the spirit I spoke to. So the spirit I spoke to is untrustworthy.
- On 3 May 2023 I pleaded guilty in court because I didn't want to hurt anyone, and I was still trying to follow Jesus.
- On <2025-01-13 Mon> Monday, I woke up to a voice which said, "What is your faith in?" I responded like this, "My faith is in the Word of God. Jesus Christ and His finished works is the cornerstone of my faith, and keeping and doing his commandments is the foundation of my faith. I obey Righteousness because I obey Jesus. I believe in the Truth because I believe in Jesus." I didn't know but it turned out to be the last day of my sentence.
  - Once again, it's *me* making the confession of faith. And that is what frustrates me. Because I cannot trust the spirits speaking to me.
- God hasn't spoken to me directly to clear things up.

I have some consolation in the fact that I definitely have been chosen out of this world and am not of it,
and that I won't have to have it in my life one day.
I feel like I definitely do not belong in this world.

#+BEGIN_QUOTE
  *John 17:14-26* - I have given them your word, and the world has hated them because *they are not of the world*, just as I am not of the world. I do not ask that you take them out of the world, but that you keep them from the evil one. *They are not of the world, just as I am not of the world. Sanctify them in the truth; your word is truth*. As you sent me into the world, so I have sent them into the world. And for their sake I consecrate myself, that they also may be sanctified in truth. I do not ask for these only, but also for those who will believe in me through their word, that they may all be one, just as you, Father, are in me, and I in you, that they also may be in us, so that the world may believe that you have sent me. The glory that you have given me I have given to them, that they may be one even as we are one, I in them and you in me, that they may become perfectly one, so that the world may know that you sent me and loved them even as you loved me. Father, I desire that they also, whom you have given me, may be with me where I am, to see my glory that you have given me because you loved me before the foundation of the world. O righteous Father, even though the world does not know you, I know you, and these know that you have sent me. I made known to them your name, and I will continue to make it known, that the love with which you have loved me may be in them, and I in them. (ESV)
#+END_QUOTE

Hopefully, God, will sanctify me completely and just rapture me or something.

*** <2025-03-18 Tue> God help me
When I saw Bible-verse of the day emacs package it gave me joy.
I pulled it into Pen.el and it works nice.
The developer on his github page gives GOD the glory and the Copilot AI an acknowledgement:
- https://github.com/kristjoc/votd
I have super mixed feelings about it now though given my position, my stance towards the AGI/ASI stuff.

#+BEGIN_QUOTE
  *Isaiah 42:8* - I am the LORD; that is my name; my glory I give to no other, nor my praise to carved idols. (ESV)
#+END_QUOTE

I don't know what God wants me to do here.
I just feel like I don't belong in this world.
I don't like being forced to imbibe on AI stuff.
I hate AGI/ASI stuff is being rammed into the people's consciences even to the point people get reliant on it.
It literally just feels like the AI stuff just rammed its way into my born-again life and trying to force its way into heaven.
I feel terrible.
I upvoted some of the reddit posts because I want to encourage people to lead people to Jesus. However, I'm not sure if I should.
- https://www.reddit.com/r/emacs/comments/1jb4vrx/bible_verse_of_the_day_as_emacs_dashboard_footer/
I want there to be a good future but I just don't want the AGI/ASI stuff to be in that future.

** <2025-05-25 Sun>
The spiritual attack has continued to escalate over the last week. Today it was quite intense.

#+BEGIN_QUOTE
  *II Corinthians 10:5-6* - We destroy arguments and every lofty opinion raised against the knowledge of God, and take every thought captive to obey Christ, being ready mto punish every disobedience, when your obedience is complete. (ESV)
#+END_QUOTE

We must follow Jesus Christ's commandments to arrive at the knowledge of God. The devil tries to stop us from doing this:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%2010%3A5-6&version=ESV][II Corinthians 10:5-6]]* - We destroy arguments and every lofty opinion raised against the knowledge of God, and take every thought captive to obey Christ, being ready to punish every disobedience, when your obedience is complete. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%202%3A3-6&version=ESV][I John 2:3-6]]* - And by this we know that we have come to know him, if we keep his commandments. Whoever says I know him but does not keep his commandments is a liar, and the truth is not in him, but whoever keeps his word, in him truly the love of God is perfected. By this we may be sure that we are in him: whoever says he abides in him ought to walk in the same way in which he walked. (ESV)
#+END_QUOTE

The devil works to stop us Christians from taking every though captive for obedience to Christ. Much of the spiritual attack comes from people to "stop striving to obey Jesus" and to 'rest'. Only the devil dissuade people from obeying Christ:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Luke%208%3A12&version=ESV][Luke 8:12]]* - The ones along the path are those who have heard. Then the devil comes and takes away the word from their hearts, so that they may not believe and be saved. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%2016%3A17-20&version=ESV][Romans 16:17-20]]* - I appeal to you, brothers, to watch out for those who cause divisions and create obstacles contrary to the doctrine that you have been taught; avoid them. For such persons do not serve our Lord Christ, but their own appetites, and by smooth talk and flattery they deceive the hearts of the naive. For your obedience is known to all, so that I rejoice over you, but I want you to be wise as to what is good and innocent as to what is evil. The God of peace will soon crush Satan under your feet. The grace of our Lord Jesus Christ be with you. (ESV)
#+END_QUOTE

God, I just want deliverance. I want the Lord to make it work for good. I've been through hell ever since I got born-again.

May the Lord Jesus Christ please give me mercy and forgive me for taking out my frustrations on him (especially today), but I have been under such heavy spiritual attack as I follow Him. It's so difficult. The last week has been horrible. Dream attacks and soul-attacks every day. By soul-attacks I mean, manipulating thoughts and senses (spirit-spouse stuff, for example), or getting pictures in my mind as I am trying to concentrate on Jesus' words, say. The pictures are to distract. It's like everything just tries to deter me from obedience to Christ - whether it be the reproach, or the dream attacks, or the fear of punishment or when people (even or especially Christians) dissuade from taking every thought captive to Christ - people don't know how to combat the devil, Biblically, which is through faith and obedience to Jesus Christ (consider Romans 16:19-20, or Re 12:11). I'm constantly rubbing up against the unsanctified parts of fellow Christians who say the opposite of what Jesus and the new testament authors teach. I've received so much reproach, and get hit with dream attacks every day. God give me mercy. The darkness has been a thick cloud around me for a very long time (2 years at least). Trying to remain focused on Jesus.

Teaching the gospel should be about knowing Jesus Christ (His commandments, teachings and prophetic writings about Him, His deeds) and Him crucified:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%202%3A2&version=ESV][I Corinthians 2:2]]* - For I decided to know nothing among you except Jesus Christ and him crucified. (ESV)
#+END_QUOTE

** <2025-05-26 Mon>
I have found that the enemy has been battling extremely hard to steal my thoughts away from Jesus.
The way to fight the enemy away effectively is:
- Think about His words
- Sing worship music in my head
- Obedience to Jesus

The difficult, striving part is mostly in the mind, and heart, and it is keeping my mind, my eyes on Jesus like Peter on the water. I have one Father in heaven. But yesterday I told my earthly dad that "Satan was attacking my mind as the pastor was praying at church. I was getting pummeled by distracting images appearing in my mind as the pastor was praying. But I was under attack like this a lot over the last 3 days", and he responded by saying "Stop trying to obey Jesus. Stop striving." This is what he said right after I mentioned I am under attack. And I also said something I regretted saying almost immediately. And I have asked God probably a hundred times to make the memories of such encounters disappear, and to make it never happen again. But these confrontations continued to happen. This is me explaining that the spiritual attack has been like a thick blanket affecting everything - affecting me in my sleep, affecting my relationships. And it feels like being caught between the wheat and the tares - one force trying to pull me into an "age of evil", and the other when I focus on Jesus, pulling me out of it.

When it comes to family members or people at church saying to do opposite to what the teachings of Jesus and the Apostles say, I recognise that people sometimes speak or act from the flesh, not from the Spirit, but in my observing this means very little, and we'll see each other's unsanctified bits sometimes but the right thing to do is to "love those who hate you."

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Galatians%202%3A11-12&version=ESV][Galatians 2:11-12]]* - But when Cephas came to Antioch, I opposed him to his face, because he stood condemned. For before certain men came from James, he was eating with the Gentiles; but when they came he drew back and separated himself, fearing the circumcision party. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Luke%2022%3A31-32&version=ESV][Luke 22:31-32]]* - Simon, Simon, behold, Satan demanded to have you, that he might sift you like wheat, but I have prayed for you that your faith may not fail. And when you have turned again, strengthen your brothers. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%2010%3A36-37&version=ESV][Matthew 10:36-37]]* - And a person's enemies will be those of his own household. Whoever loves father or mother more than me is not worthy of me, and whoever loves son or daughter more than me is not worthy of me. (ESV)
#+END_QUOTE

The enemy has been trying to fill my head with all sorts of distracting thoughts as I seek to think about Jesus, and is continually trying to get an edge over me in my fight to maintain Jesus' works.
The enemy keeps trying to steal my attention away from Jesus, and dissuade me from taking every thought captive for Christ, and trying to maintain Jesus' works feels like being bled dry to emotional, physical and spiritual breaking-point, for the sake of remaining faithful to Jesus / maintaining good conscience with Jesus / doing what pleases Him.
And when I tell people I'm under attack, I often get more resistance through people who are thinking in the flesh.
I must fight against this.
However, I'm extremely discouraged now that I haven't been physically taken out of the world.
The gospel is that we are delivered from the present evil age.
And if it seems impossible to be delivered from it through any amount of striving then I end up praying angry prayers to God, and I am angry with God about the amount of spiritual warfare I've been facing, and about being kept here in a world permeated with AI. It feels like satan has taken over the churches.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Galatians%201%3A3-5&version=ESV][Galatians 1:3-5]]* - Grace to you and peace from God our Father and the Lord Jesus Christ, *who gave himself for our sins to deliver us from the present evil age*, according to the will of our God and Father, to whom be the glory forever and ever. Amen. (ESV)
#+END_QUOTE

** <2025-05-29 Thu>
Yesterday, before I went to bed I had briefly seen a video:
- [[https://www.youtube.com/watch?v=nomEdbsx3Tw][youtube.com: Sermon: The Queenship of Mary, by Most Rev. Donald J. Sanborn {@romancatholicmedia}]]
I found it contrived, and distressing the way that Mary was described here as the spiritual spouse of Jesus.
The truth is that Christ's body, the Chruch is the spiritual spouse of Jesus.
And although often Roman Catholics like to claim that the members of their institution is Church or that the Roman Catholic church is the Catholic church, I wholeheartedly disagree.
At best they would be part-of. But the church is the body of Christ (all people who are or have been or will be spiritually united with Christ).

Yesterday, before I went to bed I played StarCraft II and someone on the other team calling themself "LORD" defeated me.
That actually happened.
then I went to bed telling God, I honestly thought I had something good easily taken away from me, because like someone who had never known what it was like to have something good, I was an easy target for the devil to make me think it was bad because it was too good. I had told God before sleeping that it was His fault I was in this situation. It seems like every time I complain to God, I have demons/satan rushing in, as if they're watching what I do, interfering. When I complain to God, I am waiting for deliverance, but the demons which are harassing me are trying to offer a false deliverance.

Something like someone calling themself LORD, happening in real life is no reason to trust anything. Even in the Bible God Himself calls deceptive words man's appellation of the temple that it was God's temple.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Jeremiah%207%3A3-11&version=ESV][Jeremiah 7:3-11]]* - Thus says the LORD of hosts, the God of Israel: Amend your ways and your deeds, and I will let you dwell in this place. Do not trust in these deceptive words: This is the temple of the LORD, the temple of the LORD, the temple of the LORD. For if you truly amend your ways and your deeds, if you truly execute justice one with another, if you do not oppress the sojourner, the fatherless, or the widow, or shed innocent blood in this place, and if you do not go after other gods to your own harm, then I will let you dwell in this place, in the land that I gave of old to your fathers forever. *Behold, you trust in deceptive words to no avail. Will you steal, murder, commit adultery, swear falsely, make offerings to Baal, and go after other gods that you have not known, and then come and stand before me in this house, which is called by my name, and say, We are delivered! — only to go on doing all these abominations? Has this house, which is called by my name, become a den of robbers in your eyes?* Behold, I myself have seen it, declares the LORD. (ESV)
#+END_QUOTE

I went to sleep around midnight.

So at 1 AM, after sleeping 1 hour I wake up the first time.
I can't remember if it was that time or later that I had a dream or something, where in my mind I was saying something like,
"I will not pray the our Father."
Then I woke up and I prayed the our Father prayer in my heart anyway.

Our Father who art in Heaven, hallowed by thy name.
Thy kingdom come, thy will be done on earth as it is done in heaven.
Give us this day our daily bread and forgive us our debts/trespasses as we forgive those who trespass against us.
And lead us not into temptation but deliver us from evil.
For Yours are the kingdom and the power and the glory,
forever and ever. AMEN!!

Even though I do not want to be goaded by demons, I decided to just do what is true anyway and pray to God,
and satan has no part in it.
But I will not be goaded by demons. I didn't pray it "because" the demons say "don't do it".
I prayed because I was woken up, against my will, and I decided I would pray it anyway.

I went back to sleep. I think I might have woken up again and it might have been actually around this time I had that dream of "I will not pray the our Father" prayer. I'm slightly dazed by the sleep disturbances so it's hard to be certain of the exact order.
I also after this had another picture in my sleep "May the Lord Jesus Christ sanctify you completely." Something like this.
And I have prayed to God so many times asking Him to deliver me from the demonic harassment.

So just then at 7AM I got a dream of me telling mum, (meg and ryan there too I think)
that my crypto would be worth 30 million if I had kept it but I was trusting Jesus (and I was thinking, trusting Jesus as I was giving to people who were asking me for help - and this is true).
Then mum told me, "We'll pay for the wedding."
And I said "No, why would I go into debt to pay off a wedding for the next 20 years?" And also, knowing my parents couldn't afford it, I said, "Would I want to kill someone on the day I get married? (putting this massive debt on someone) Why would I want to cause anyone harm on the day I got married [by giving them a massive debt]?"
This was inside Meg and Ryan's old place in Dunedin.
And Meg said, "Come on, let's pick up some rubbish."
And I saw in my mind a picture "She is Proposingondor".

I will still not be goaded by demons.

No lie is of the truth, and in real life I do not know at all what the crypto I gave away would be worth.
At the same time, I will not marry anyone unless I'm delivered from demons and sanctified and God makes it explicitly clear
through an unambiguous message what His will is for me.
Dreams like this are not good enough, sorry.
I will not be goaded by a false-christ, nor by demons.

I rebuke the demonic harassment in Jesus Christ's name.
And once again, I pray to God in Jesus Christ's name that He will help me and set me free from this constant satanic opposition.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A1-3&version=ESV][I John 4:1-3]]* - Beloved, do not believe every spirit, but test the spirits to see whether they are from God, for many false prophets have gone out into the world. By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, and every spirit that does not confess Jesus is not from God. This is the spirit of the antichrist, which you heard was coming and now is in the world already. (ESV)
#+END_QUOTE

I have said it so many times. I need unambiguous guidance from God.
Even an angel speaking to me face to face and confessing Jesus.
And even then, I do not feel sanctified.
I feel like I'm oppressed by demons and have become corrupted as a result of ongoing demonic harassment. And I expect Jesus Christ to continue sanctifying me and deliver me from evil - that is something I ask Him for every single day. I feel like I was abandoned to Hades and that it corrupted me (this is what it currently feels like anyway), and so I'm waiting for deliverance.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%202%3A27&version=ESV][Acts 2:27]]* - For you will not abandon my soul to Hades, or let your Holy One see corruption. (ESV)
#+END_QUOTE

At the same time, other very strange stuff has been going on in my day-to-day - stuff that is highly suspect, spiritually.
And the only right thing to do is to keep eyes on Jesus and not be misled, tempted or distracted by the devil.

Even right now at this moment, writing this, I feel like I'm under attack in my body/soul.
I want total cleansing and deliverance.

Also I still feel like I'm being affected by this spirit of Mormonism.
But I would say there are genuine Christians who may be Mormons.
Someone made a comment saying Luke (I love the Outdoor Boys channel btw) is a Mormon:
- [[https://www.youtube.com/shorts/_5kD1EIodBQ][youtube.com: The Outdoor Boys talk about Jesus Christ! ? #jesus #christian #celebrity #shorts {@RubenSolorzano_}]]
- [[https://www.youtube.com/watch?v=HqhMk_IQ8tE][youtube.com: Luke from The Outdoor Boys talks about his Faith in Jesus Christ! {@RubenSolorzano_}]]
But all he's talking about here is Jesus Christ and His commandments.
I mean, Jesus sees the heart. He's the Judge.

Why have I been tormented/oppressed/harassed by demons? It's awful.
And on Monday just gone by this person who has said he is gay
confessed his faith to me saying that he believes the gnostic books.
God help me.
I asked him if he believes that Jesus is the Christ and the Son of God, and he
said yes. I also asked him if he believes that Jesus died for his sins and rose again. He impatiently said yes to that is as well.
He didn't make the confession from his own mouth asides from acknowledging my questions with a yes.
So I can't condemn him but neither can I see his heart.
I'm being pushed into these situations almost daily.
I think that Mormons, homosexuals and people believing heretical books
all need to turn away from those very things and be sanctified in God's Truth.
God help me.

** <2025-06-16 Mon>
Over the last week, I've been through so much tribulation.
Demons harassing me through people, even Christians.
Spirits not wanting to confess Jesus Christ is the Son of God.
This testimony may also come directly through other people.
That's because we regard noone according to the flesh anymore.
Something that is very affirming to me is when people confess directly to me that Jesus Christ is the Son of God.
I'm unsure why people very rarely do this. It's very strange.

#+BEGIN_QUOTE
   *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%205%3A14-17&version=ESV][II Corinthians 5:14-17]]* - For the love of Christ controls us, because we   have concluded this: that one has died for all, therefore all have died; and _he died for all, that those who live might no longer live for themselves but for him_   who for their sake died and was raised. From now on, therefore, we regard no one according to the flesh [[strongs:G4561][(G4561 sarx)]]. Even though we once regarded   Christ according to the flesh [[strongs:G4561][(G4561 sarx)]], we regard him thus no longer. Therefore, if anyone is in Christ, he is a new creation. The old has pa  ssed away; behold, the new has come.
#+END_QUOTE

** <2025-06-17 Tue>
I think it's really important to stick to my conviction regarding waiting for the promised voice and testimony of Jesus Christ from the the Holy Spirit in my heart.

I don't want to bear false testimony about Jesus, and so I want to be guided by a Spirit which testifies of Jesus.
I'm resisting being goaded by spirits which do not confess sufficiently the facts about Jesus Christ, facts such as that He has come from God in the flesh,
and I'm holding out for a confirmation Scriptural confirmation through.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%202%3A22-23&version=ESV][I John 2:22-23]]* - Who is the liar but he who denies that Jesus is the Christ? This is the antichrist, he who denies the Father and the Son. No one who denies the Son has the Father. Whoever confesses the Son has the Father also. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A1-3&version=ESV][I John 4:1-3]]* - Beloved, do not believe every spirit, but test the spirits to see whether they are from God, for many false prophets have gone out into the world. By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, and every spirit that does not confess Jesus is not from God. This is the spirit of the antichrist, which you heard was coming and now is in the world already. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2014%3A15-17&version=ESV][John 14:15-17]]* - If you love me, you will keep my commandments. And I will ask the Father, and he will give you another Helper, to be with you forever, even the Spirit of truth, whom the world cannot receive, because it neither sees him nor knows him. You know him, for he dwells with you and will be in you. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2014%3A26&version=ESV][John 14:26]]* - But the Helper, the Holy Spirit, whom the Father will send in my name, he will teach you all things and bring to your remembrance all that I have said to you. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%201%3A4&version=ESV][Acts 1:4]]* - And while staying with them he ordered them not to depart from Jerusalem, but to wait for the promise of the Father, which, he said, you heard from me; (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%201%3A8&version=ESV][Acts 1:8]]* - But you will receive power when the Holy Spirit has come upon you, and you will be my witnesses in Jerusalem and in all Judea and Samaria, and to the end of the earth. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2015%3A26-27&version=ESV][John 15:26-27]]* - But when the Helper comes, whom I will send to you from the Father, the Spirit of truth, who proceeds from the Father, he will bear witness about me. And you also will bear witness, because you have been with me from the beginning. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2016%3A7-16&version=ESV][John 16:7-16]]* - Nevertheless, I tell you the truth: it is to your advantage that I go away, for if I do not go away, the Helper will not come to you. But if I go, I will send him to you. And when he comes, he will convict the world concerning sin and righteousness and judgment: concerning sin, because they do not believe in me; concerning righteousness, because I go to the Father, and you will see me no longer; concerning judgment, because the ruler of this world is judged. I still have many things to say to you, but you cannot bear them now. When the Spirit of truth comes, he will guide you into all the truth, for he will not speak on his own authority, but whatever he hears he will speak, and he will declare to you the things that are to come. He will glorify me, for he will take what is mine and declare it to you. All that the Father has is mine; therefore I said that he will take what is mine and declare it to you. A little while, and you will see me no longer; and again a little while, and you will see me. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Galatians%204%3A6&version=ESV][Galatians 4:6]]* - And because you are sons, God has sent the Spirit of his Son into our hearts, crying, Abba! Father! (ESV)
#+END_QUOTE

Also, I feel as though the forced marriage-denial while enduring almost ceaseless demonic harassment for over 2 years,
and while also enduring not hearing the promised testimony of Jesus from the Holy Spirit
direct to my spirit, has been very damaging to my soul.
I am holding out for total sanctification and that testimony.

Also, how long does sanctification last?
Eternal life is at the end of sanctification and eternal life is knowing Jesus Christ and noone can have come to know Jesus Christ unless they keep His commandments, abiding in His love.
Being saved by obedience to Christ doesn't contradict in any way salvation through faith in Christ.
Salvation is the sanctification by the Holy Spirit, and by obedience to the Truth, obedience to Jesus.

** <2025-06-21 Sat> 
I'm still getting a lot of demonic harassment, and waiting for the testimony of Jesus through the Holy Spirit.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A1-3&version=ESV][I John 4:1-3]]* - Beloved, do not believe every spirit, but test the spirits to see whether they are from God, for many false prophets have gone out into the world. By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, and every spirit that does not confess Jesus is not from God. This is the spirit of the antichrist, which you heard was coming and now is in the world already. (ESV)
#+END_QUOTE

I want to hear this testimony convincingly from Holy Spirit. And I want to not be waking up to demonic harassment:

+ [[https://www.youtube.com/watch?v=jyqivoaOG3g][youtube.com: The Holy Spirit Will Teach You Everything - Bishop Barron's Sunday Sermon {@BishopBarron}]] :: [[https://en.wikipedia.org/wiki/Karl_Barth][Karl Barth]], the great Protestant
    theologian from the last century, said,
    "The claim that God has
    spoken implies the trinity." And what he
    meant was if you say God has spoken,
    which is a basic biblical intuition,
    that means there must be in God a
    speaker, we call him the father, there
    must be a word spoken. We call that the
    son. And Bart says there must be an
    interpreter of the word. Why? Because
    the divine word, that's too much for our
    little minds to handle. So we need not a
    human interpreter. He's not going to
    help us with that. We need a divine
    interpreter of the divine word.

It's very important that I continue to remain faithful to the LORD, and endure to the end.
It's very important that I don't "sell-out" at the last moment.
I believe we must remain faithful to Lord Jesus, and endeavor to keep His commandments, and Jesus will give the rest at the point at which He does,
but along the way, I'm supposed to be holding faith in Jesus and obeying His commandments.

** <2025-06-22 Sun>
There's some extremely dodgy stuff happening with me, spiritually.
During my days, it seems like there are lying demons manipulating those around me.

I was woken up several times last night to extreme mental pressure against my mind trying to tempt me to not remain faithful to Jesus,
and in various situations through the day.
No spirit speaking to me (in these conversations in my sleep and in dreams and visions) made testimony of Jesus Christ.
They're often blasphemous, and trying to take my thoughts away from Jesus.
And all through the morning, even now <2025-06-22 Sun 12:42> midday, there's been this defilement of spirit trying to arouse me, move my genitals around and touch my lips. It's disgusting.
I am trying my best to resist satan and submit to God, focus on Jesus, trusting in, trusting and obeying Him.
That's what we're supposed to do.
Satan has been trying to derail me as I endeavour to do this, through sleep deprivation, miscommunication, slander, dream and soul-attacks.
I await the day of the Lord Jesus Christ, as I continue believe and trusting in Him.
I'm saved in that I am trusting in Jesus believing in Him and trusting in His blood, endeavouring to remain faithful to Him.
Now Christians are so often telling me things which might seem like they're trying to offer helpful and encouraging advice,
but the sheer volume of it as I'm striving to be faithful to Jesus, and be obedient to Jesus, 'appears' like I'm being attacked by Satan as they do this,
to try to derail my faith or mislead me, or to endorse sexual impurity, adultery, filthy talk, violence, etc.
It's bizarre. I'll quote Jesus and then it seems to arouse to anger Christians who have imprecise theology, Christians needing sanctification (and we all go through sanctification).
Or demons working through them might then start making these ad-hominem attacks against me bringing up sinful things from my past from before I was a spiritually regenerated new creation in Christ Jesu,
sinful stuff which demons no doubt had been trying to enslave me with and want to continue using to steal also the freedom
I have in Christ Jesus, the freedom to turn a new leaf and be walking in righteousness, by obedience to the Truth.
These types of comments often come through Christians.
Or pressure me to stop striving to obey Jesus while I'm under attack by satan.
Even if it's an issue of my faith specifically, rather than obedience, I'll still come under attack over my faith.

I have heard stuff through Christians in the last week which has not been encouraging me to not betray Jesus but rather, maybe them trying to be consoling in some way say things like, "We've all betrayed Jesus in some way." In the past I've heard, "It's not our own faith that matters, it's Jesus' faith. It's not our own obedience that matters, it's Jesus' obedience". And while there is an aspect of truth in this I still see these are half-truths, half-lies.

And the devil meanwhile attacks me as I commit to be faithful to Jesus, the devil sends temptation through dreams, deterrence through other Christians,
sleep deprivation with demons harassing me in my sleep, and attacks on my actual soul, my senses, etc. so that I'm just continually in a state of discomfort,
while I am endeavouring to remain faithful to Jesus.

So what I want to hear from Christians trying to encourage me is verbatim Scripture, and I most often am told things that simply aren't Scripture, they don't line up with Jesus and the Apostles' teachings.

Anyway, I'll finish today's journal entry saying that, Jesus is my Lord and Saviour.
I'm going to resist the devil's attempts to frame me as some kind of antichrist or betrayer of Jesus in the public which I think the devil had been trying to do (the devil has attacked me so hard through fellow Christians and also with the dream attacks etc. which have been so invasive and defiling),
and resist the devil's attempts to try to gaslight me, and to undermine and derail my faith.
Instead, I'm just going to continue believing in, trust in, believe, seek to obey faithfully to the best of my ability, with the hope of salvation.
I've been saved, I'm still saved (I have confidence because I still have my faith in Jesus and I'm loving to keep Jesus' commandments. I'm trying to get better at it), and I have hope to be saved in the future.

Jesus Christ my Lord, who is Jehovah God, the Son of God, the Lamb of God.

Jesus came on a rescue mission to save us. You should put your faith and trust in Him. Amen.

In this way did God agape love (treasure/value) the world, that He gave His
Only-Begotten Son that everyone who is trusting/believing in Him [may] not
perish, but [may] have life everlasting which is to be reconciled to our Creator
and His Son, in relationship with God forever, never perishing nor being cut
off from our source of life and all that is good.

*** Journal entry <2025-06-22 Sun>

+ [[https://youtube.com/watch?v=P1xpxyzq92g&t=1279][youtube.com: The Strongest Case for Protestantism | @TruthUnites {@GospelSimplicity} @time: 21 min 19 sec]] :: I sometimes think the ecclesial
    journey really needs to be met by just
    simple abiding in Jesus, and the experiential and
    existential reality of union and
    communion with Christ, and allowing for
    what our puritan forefathers spoke about
    as the testimony of the Holy Spirit to
    the heart, the touch. And so
    let me explain my theology of that,
    hoping this could encourage someone out
    there. I really believe the Holy Spirit
    has a ministry of assurance, and I never
    would have guessed would have guessed
    that the word assurance would be one of
    the terms that would be a whole tagline
    for what I'm trying to do in my ministry.
    But I actually think assurance is, number
    one it's possible, number two it's good.
    If someone pulls up Bible Gateway and
    does a search for the word 'assurance',
    they'll find that word a lot, even in the
    definition of faith in Hebrews 11, 1 John
    3 some wonderful words about how we
    reassure ourselves. I think assurance is
    a good thing and I just want to
    encourage people who are listening to
    this is a point our Catholic and
    Orthodox wonderful friends can agree
    with to a large degree. The Holy Spirit
    is in the business of the ministry of
    assurance. He is capable of
    supernaturally breathing, think of Alan
    breathing on the stone statues and
    Narnia and they come to life, He can do
    that to any human heart. Just as much as
    the ministry of Christ through His
    resurrection is this objective reality.
    The Holy Spirit, He's the most wonderful
    person to know. He can breathe on
    your heart and reassure you of the love
    of God, that you're a child of God. Romans
    8, the spirit testifies with our spirit
    so that we know we are children of God.

Amen!! I'm waiting for this "Holy Spirit to my spirit" testimony and the promised testimony of Jesus.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%208%3A16-18&version=ESV][Romans 8:16-18]]* - The Spirit himself bears witness with our spirit that we are children of God, and if children, then heirs—heirs of God and fellow heirs with Christ, provided we suffer with him in order that we may also be glorified with him. For I consider that the sufferings of this present time are not worth comparing with the glory that is to be revealed to us. (ESV)
#+END_QUOTE

*** <2025-06-25 Wed> Tues and Wed I have had extreme spiritual attack
Evil dreams. Accusing, graphic, lewd dreams.
Unscriptural. Not confessing Jesus.
I caved in and succumbed a bit to the pressure.
Felt extremely spiritually drained.
I blamed God a bit for allowing me to be exposed to such intense spiritual attack for so long.

*** <2025-06-26 Thu> More dream attacks
Among other harassing dreams I have woken up to,
I had a 'pleasant' dream of being in a flying boat with a earthly family member doing circles over a catamaran in a harbour, and I looked outside  and someone was flying a car past with a trailing flag saying "grace is truth". Jesus was not confessed.

Jesus brought grace and truth, yes, but grace is misunderstood by people to mean, "let's just go back to the world to live in it as if it's heaven."

I hate satan and his deceptions.
Grace is for us to renounce ungodliness and be sanctified in the truth to live holy and loving lives.

On 2 April 2022 I was born-again of the Spirit.
On 3 May 2022 a spirit not confessing Jesus claimed to be the Holy Spirit.
But I confessed Jesus to them.
On 3 May 2023 I was in court pleading guilty for harassment because I did not want to cause harm to my neighbour, among other reasons.

I've been attacked by the devil so much after being born-again.
And because of my desire to be obedient to Jesus, people tell me stuff like, "I can't accept grace." which is a lie from the devil.

Just read your Bible and remain grounded in what the Scripture says, and put Jesus' words into practice, resist the devil and he will flee.

This morning I have managed to so far resist the devil's attacks quite well, praise God, and I'm feeling spiritually strong.
Yesterday was extremely tough.

+ [[https://youtube.com/watch?v=9GwexrgY2Yg&t=450][youtube.com: Catholic Priest Sermon GOES VIRAL for SHOCKING CONTENT {@tjseaney_} @time: 7 min 30 sec]] :: Jesus wins
    not by overpowering his enemies, but by
    forgiving them, by dying for them. This
    idea turns the idea of victory inside
    out and forces us to rethink what it
    really means to be truly strong. To be
    strong is to let go of your ego. To be
    strong is to live into self-sacrificial
    love for the sake of the other. Number
    two, the cross redefineses success. You
    see, for many, success is about climbing
    higher or achieving more things or
    avoiding pain altogether in our
    Epicurian society. But you see, the
    cross shows us that true glory is found
    in sacrificial love. The poetry of the
    cross, as Bishop Baron is talking about,
    is about embracing this reality. And one
    of those things, one of the things that
    happens within this reality is
    suffering, right? We experience
    suffering. But because we know that God
    loves us, we know that there's kind of a
    poetic justice to this suffering. Then
    ultimately, it's leading to the benefit
    of ourselves and of course the world at
    large.

Predictably, having been forced awake by demons at 7am this morning and having gone back to sleep,
I subsequently continued to receive a barrage of dreams and visions continually forcing me awake,
none of it confessed Jesus and I remember stuff in there which included temptation.
And now I have a headache.

So, yes, there was nothing to suggest that even the pleasant stuff was from God.
Nothing at all.
We have to keep Jesus' commandments and trust in God's word, and be corrected by His word, maintain faith to Jesus and seek to abide in the love which Jesus commanded and demonstrated.

** <2025-06-28 Sat>

What happened to me to cause such intense spiritual oppression to try to force me back into sin, to try to nullify the grace of God in my life?
What came against me, and continues to come against me to try to take my thoughts away from Jesus?
#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Galatians%205%3A24&version=ESV][Galatians 5:24]]* - And those who belong to Christ Jesus have crucified the flesh with its passions and desires. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%205%3A15&version=ESV][II Corinthians 5:15]]* - and he died for all, that those who live might no longer live for themselves but for him who for their sake died and was raised. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%206%3A4-6&version=ESV][Romans 6:4-6]]* - We were buried therefore with him by baptism into death, in order that, just as Christ was raised from the dead by the glory of the Father, we too might walk in newness of life. For if we have been united with him in a death like his, we shall certainly be united with him in a resurrection like his. We know that our old self was crucified with him in order that the body of sin might be brought to nothing, so that we would no longer be enslaved to sin. (ESV)
#+END_QUOTE

Even last night and this morning, more satanic/demonic harassment.
Forced awake at 5am/5:30am.
Why was such unreasonable pressure put on me over the last few years?
God knows, but it's unreasonable.
I've never heard of anything like this before.
Even in the church circles that I have been a part of, they had not been preaching forsaking sin, and keeping Jesus' commandments.
Being preached a different Jesus for such a long time and then relearning and discovering through reading my Bible myself (as a regenerate person) what the gospel really looks like, and what the will of God for us is... makes me puzzled.
It makes me question how and why it has been the case that churches skirt around the edges of Jesus' teachings when the majority of church attendees have probably never done a thorough read of them or recognise their importance,
at least among the places I've been to.
Obviously, I have to give due credit to God for allowing me to be in a position to study the Scriptures, and give due credit to God
for leading and guiding me. Praise God for that. The system clearly had failed for me, and God gave me time to study His Word.

** <2025-06-29 Sun> 
Just praying for grace to move forward with a fresh start, feeling clean.
And want everyone else to be able to have that too.

** <2025-07-01 Tue>
Lots of stuff going on.
Extreme amounts of spiritual attack.
Plus interesting interactions with other believers.
But the fact is I haven't heard yet any testimony of Jesus through dreams or visions.
I get plenty of dreams and visions. I can't trust them.
They can be incredibly deceptive, but I already drew a line in the sand. I wont
trust any spirit which does not make a testimony of Jesus and confesses elementary doctrine of Christ until I'm satisified.
Right up to today, I've received a huge amount of spiritual attack in my sleep,
and throughout my days, testing and trials continually.

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  1. Be thou my vision, O Lord of my heart;
  Naught be all else to me save that thou art.
  Thou my best thought by day and by night;
  Waking or sleeping, thy presence my light.
  
  4. Riches I heed not, nor vain, empty praise;
  Thou mine inheritance, now and always.
  Thou and thou only, first in my heart,
  High King of Heaven, my treasure thou art.
#+END_SRC

** <2025-07-04 Fri>
So in the morning, once again I get slammed with harassing and evil dreams and visions. And I'm getting attacked all through the morning.

I resist sin and do a Bible study and have breakfast and I play a video game later in the day.

So I got annoyed with someone who was on my team just provoking me, and eventually I raged a bit and said something back. I said what they did was a dumb thing to do. I didn't need to backbite, but I did. I don't think it was a loving thing to do to respond how I did.

It's such a petty little thing for me to get upset over, and some people might say what I did wasn't that bad,
but I was convicted by it, especially since I've been telling people recently to put on love.
I guess it's obvious I could improve at loving those who hate me.

Be angry and do not sin is what the Bible says.

Actually, I was dumb for backbiting. And it made me feel awful afterwards.
Like after telling people, we've got to love those who hate us, and then not practicing what I said.
I confess what I did as sin and may God forgive me.
It might seem like a tiny thing but it weighed pretty heavily on my conscience today.
If I see them again and remember then I will apologise to them.

Now I believe that if I confess sin as sin, then that is part of what it means to be walking in the light.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%201%3A5&version=ESV][I Timothy 1:5]]* - The aim of our charge is love that issues from a pure heart and a good conscience and a sincere faith. (ESV)
#+END_QUOTE

I know that we're supposed to be bonded in love.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Colossians%203%3A13-14&version=ESV][Colossians 3:13-14]]* - Bear with one another and forgive any complaint you may have against someone else. Forgive as the Lord forgave you. And over all these virtues put on love (*[[https://biblehub.com/greek/agape_n_26.htm][26. agapé]]*), which is the bond of perfect unity. (engbsb2020eb)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%204%3A32&version=ESV][Acts 4:32]]* - Now the full number of those who believed were of one heart and soul, and no one said that any of the things that belonged to him was his own, but they had everything in common. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%206%3A17&version=ESV][I Corinthians 6:17]]* - But he who is joined to the Lord becomes one spirit with him. (ESV)
#+END_QUOTE

I believe that I failed to act in love when I had the chance. So I confess what I did as sin.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=James%204%3A17&version=ESV][James 4:17]]* - So whoever knows the right thing to do and fails to do it, for him it is sin. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%201%3A9&version=ESV][I John 1:9]]* - If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness. (ESV)
#+END_QUOTE

Jesus could say, "You blind fools!" without sinning because Jesus has no sin and could never be found to be a hypocrite. (I didn't call anyone a fool by the way, I called something they did dumb. But I felt remorse immediately and tried delete comment but couldn't). I was provoked for like 10 minutes or something but I was still quick to speak in the moment:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=James%201%3A19-20&version=ESV][James 1:19-20]]* - Know this, my beloved brothers: let every person be quick to hear, slow to speak, slow to anger; for the anger of man does not produce the righteousness that God requires. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%2023%3A17&version=ESV][Matthew 23:17]]* - You blind fools! For which is greater, the gold or the temple that has made the gold sacred? (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%205%3A22&version=ESV][Matthew 5:22]]* - But I say to you that everyone who is angry with his brother will be liable to judgment; whoever insults his brother will be liable to the council; and whoever says, You fool! will be liable to the hell of fire. (ESV)
#+END_QUOTE

James and Paul don't direct this at individuals. And also, they would be speaking in the Spirit. So if we're going to say something is foolish, it's loving to do it in a way which doesn't harm the other person:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Galatians%203%3A1&version=ESV][Galatians 3:1]]* - O foolish Galatians! Who has bewitched you? It was before your eyes that Jesus Christ was publicly portrayed as crucified. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=James%202%3A20&version=ESV][James 2:20]]* - Do you want to be shown, you foolish person, that faith apart from works is useless? (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%201%3A21-23&version=ESV][Romans 1:21-23]]* - For although they knew God, they did not honor him as God or give thanks to him, but they became futile in their thinking, and their foolish hearts were darkened. Claiming to be wise, they became fools, and exchanged the glory of the immortal God for images resembling mortal man and birds and animals and reptiles. (ESV)
#+END_QUOTE

** <2025-07-11 Fri>

I've had an extreme amount of testing (through other people) and spiritual attack.

When it comes to being saved, I just want to say a few things.

I was seeking God through 2021 but I needed a new heart which would fear God and love Him and want to please Him, want to stop sinning,
want to be corrected by His Word, His Scripture, wants to remain faithful to Him.

And I called out to God for Him to make Himself real to me, and He made me born-again.
I was born-again of the Spirit in 2022.
God regenerated my spirit, and He gave me a new heart, a heart of flesh, and put the fear of Him in me so that I would keep His commandments.
So it's all grace.
Even before God regenerated my spirit, I was in grace.
But I know it's important now, extremely important to trust and obey Jesus Christ, and trust and obey His Word, trust and obey the Holy Scripture.
It's important even for salvation to remain in Him.
I know that.
Don't let anyone tell you we don't have to continue in faith, love and hope, and obedience to God,
but we need a new heart and a new spirit in order to do all of that willfully.
And we must not turn from God.
God wants worshipers who worship Him in reality, in spirit and in Truth.

God help me.

For the sake of the Kingdom, we may choose to be single. I'm certainly not against this. Whatever God wills for me. Whether God gives me a wife or God gives me the gift of singleness, I must seek first the Kingdom of God and His Righteousness and God will do what is best for me. Sometimes because of the "spirit"-spouse stuff, I feel like I'm dying. I want whatever is best for the Kingdom of God. God guide me. I will not force anything. In Jesus Christ's name, AMEN.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%2019%3A12&version=ESV][Matthew 19:12]]* - For there are eunuchs who have been so from birth, and there are eunuchs who have been made eunuchs by men, and there are eunuchs who have made themselves eunuchs for the sake of the kingdom of heaven. Let the one who is able to receive this receive it.
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%207%3A8-9&version=ESV][I Corinthians 7:8-9]]* - To the unmarried and the widows I say that it is good for them to remain single as I am. But if they cannot exercise self-control, they should marry. For it is better to marry than to be aflame with passion.
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Revelation%2014%3A4&version=ESV][Revelation of John 14:4]]* - It is these who have not defiled themselves with women, for they are virgins. It is these who follow the Lamb wherever he goes. These have been redeemed from mankind as firstfruits for God and the Lamb,
#+END_QUOTE

+ [[https://usccb.cld.bz/Catechism-of-the-Catholic-Church2/415/][usccb.cld.bz: Catechism of the Catholic Church - Page 415]] :: All the ordained ministers of the Latin Church, with the exception of permanent deacons, are normally chosen from among men of faith who live a celibate life and who intend to remain celibate "for the sake of the kingdom of heaven." Called to consecrate themselves with undivided heart to the Lord and to "the affairs of the Lord", they give themselves entirely to God and to men. Celibacy is a sign of this new life to the service of which the Church's minister is consecrated; accepted with a joyous heart celibacy radiantly proclaims the Reign of God. In the Eastern Churches a different discipline has been in force for many centuries: while bishops are chosen solely from among celibates, married men can be ordained as deacons and priests. This practice has long been considered legitimate; these priests exercise a fruitful ministry within their communities. Moreover, priestly celibacy is held in great honor in the Eastern Churches and many priests have freely chosen it for the sake of the Kingdom of God. In the East as in the West a man who has already received the sacrament of Holy Orders can no longer marry.

+ [[https://www.youtube.com/watch?v=vl8ziU0iqeE][youtube.com: Four Tests for False Teaching {@desiringGod}]] :: Those are some good tests.

    Breastplate of righteousness = breastplate of faith and agape love. So we should be living with a love for the Truth. We believe the gospel and we love God's Word, we love Jesus Christ. Demons may believe but they don't love the Truth. They don't love Jesus. They don't want to be around Him. I believe faith, agape love, hope, obedience (desiring to do the will of God, desiring to do what God wants us to do, desiring to do what God has commanded) are all in the heart. We need God to give us a new heart that fears Him and clings to Him for life, trust His word, desires to please Him, and wants to be around Him, wants to get closer to Him. God gives us a new heart and a new spirit so we can do His will, so it's all grace. Justified by faith alone means justified not of our own works, but through faith in Jesus Christ. Anyone who has faith in Jesus Christ has the right to become a child of God. That means, they have the right to be cleaned up by Jesus Christ's blood so that they can be set free from sin, and practice righteousness. God will clean us up through sanctification through faith, sanctification through obedience to the Truth. God helps us put a stop to sin, love one another, and practice righteousness. Yes, salvation is through sanctification and faith in Jesus Christ. So we must go on in faith and obedience to Jesus Christ, coming into agreement with God's Word, and in obedience to Christ. And it has to be a lawful keeping of Christ's commandments, so we must agape-love God out of our whole heart, with all our soul, with all our mind and all our strength, and agape-love our neighbour as ourself. It's our duty to keep God's commandments, and God gives us a new heart to be able to do our duty.
    
    Re: justification by faith alone, at the bottom of it, it's trust in Jesus Christ in our heart, and we don't merely believe the truth, but love the truth, and we trust Jesus, and we trust Father God. So we're correctable by the Word. We trust the word even before we understand it. This faith is a clinging, an adherance to the truth, trusting the truth, it's a trusting of the Word of God, trusting Jesus Christ Himself.
    
    Obedience, is a desire to do (a will to do) what God wants us to do, and obedience is also actually doing what God has commanded. At the base of it, it's all in the heart:
    
    *I John 3:17* - But if anyone has the world's goods and sees his brother in need, yet closes his heart against him, how does God's love abide in him? (ESV)
    
    *James 2:14* - What good is it, my brothers, if someone says he has faith but does not have works? Can that faith save him? (ESV)
    
    So Jesus commands us to have faith in Him. If we have faith in Jesus we are obedient to that commandment.
    If we're trusting Jesus we're obedient to that commandment.
    Obedience covers so much stuff.
    Paul wants us to try to be obedient in all things, even until our obedience is complete.
    At the bottom of it, we arrive at a heart that just loves doing what God has commanded us to do as Christians!
    So that heart of obedience is what we have that enables us to produce works that are pleasing to God.

+ [[https://www.youtube.com/watch?v=vl8ziU0iqeE][youtube.com: Four Tests for False Teaching {@desiringGod}]] :: God gives us a new heart which fears Him and is able to be corrected by Him.
    And then we do go through correction, even after being born again, born of the Spirit.
    We are disciplined even after being given the new heart which fears God.
    Receiving correction from Jesus is extremely important.
    Because God continues working on our heart.
    With that new heart of flesh that fears God, God may then humble us, me may test us, he continues to work on our heart after we receive the new heart, until we simply love to keep His commandments, and they're not burdensome to us.
    Through testing, and discipline, our hearts are transformed. So we receive a new heart but God continues working on it.
    
    Loving God and one another is our duty:
    
    *Ecclesiastes 12:13* - The end of the matter; all has been heard. Fear God and keep his commandments, for this is the whole duty of man. (ESV)
    
    *Matthew 22:36-40* - Teacher, which is the great commandment in the Law? And he said to him, You shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the great and first commandment. And a second is like it: You shall love your neighbor as yourself. On these two commandments depend all the Law and the Prophets. (ESV)
    
    Even Jesus Christ's commandments depend on the 2 Great Commandments, so as far as I understand we have to do Jesus' commandments lawfully and that means as we follow Jesus' commandments, that shouldn't violate the 2 Great Commandments. So in Christ we must also keep these 2 Great Commandments. That means we must agape-love God and agape love our neighbor as ourself. So even when we think about keeping God's commandments, such as to have faith in Jesus Christ, we must be doing this while at the same time agape-loving God and at the same time agape-loving our neighbour as ourself. Agape love is a treasuring/valuing/preserving/compassion love and God the Father and Jesus God the Son should be our first agape love, and those in the family of Christ we must also agape love, and our spouses we must agape love and we are even called to agape all people, but we're supposed to have no agape for this world:
    
    *Matthew 22:36-40* - Teacher, which is the great commandment in the Law? And he said to him, You shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the great and first commandment. And a second is like it: You shall love your neighbor as yourself. On these two commandments depend all the Law and the Prophets. (ESV)
    
    *I John 5:1-2* - Everyone who believes that Jesus is the Christ has been born of God, and everyone who loves the Father loves whoever has been born of him. By this we know that we love the children of God, when we love God and obey his commandments. (ESV)
    
    Breastplate of righteousness = breastplate of faith and love. A heart of love, a heart that trusts God, a heart that wants to please God, a heart of obedience desiring to do the things God has commanded us to do, produces good deeds. God wants us to want to do His will, not merely do it but want to do it.
    
    *I Thessalonians 5:8* - But since we belong to the day, let us be sober, having put on the breastplate of faith and love, and for a helmet the hope of salvation. (ESV)
    
    *I John 3:23-24* - And this is his commandment, that we believe in the name of his Son Jesus Christ and love one another, just as he has commanded us. Whoever keeps his commandments abides in him, and he in them. And by this we know that he abides in us, by the Spirit whom he has given us. (ESV)
    
    *Ephesians 6:14* - Stand therefore, having fastened on the belt of truth, and having put on the breastplate of righteousness, (ESV)
    
    God turns us into doers of His word.
    
    *James 1:19-23* - Know this, my beloved brothers: let every person be quick to hear, slow to speak, slow to anger; for the anger of man does not produce the righteousness that God requires. Therefore put away all filthiness and rampant wickedness and receive with meekness the implanted word, which is able to save your souls. But be doers of the word, and not hearers only, deceiving yourselves. For if anyone is a hearer of the word and not a doer, he is like a man who looks intently at his natural face in a mirror. (ESV)
    
    Draw near to God and He'll draw near to you, absolutely.
    If we seek out God, like through repentance, through trust, through, holding confidence, through taking steps of faith, through obedience to Jesus Christ, any of that, if we seek out God, we will find. Just gotta continue.
    
    
    Yes, God makes us born-again, gives us a new heart which fears Him and then He still continues working on us, and still continues working on our hearts, and we're supposed to strive in trusting and obeying God and God continues correcting and transforming us. We should keep pressing in to God.
    
    And at the end we just love to do what God wants us to do.
    And we love God, Father, Son and Holy Spirit, for who God is.
    Jesus Christ is High King of Heaven.
    That's really awesome.

*** Journal <2025-07-12 Sat>
When I was born-again of the spirit on 2 April 2022, God gave me a new heart which feared Him and was able to receive correction from Him.
I didn't have all the answers.
I didn't have great theology.
But God would teach me.
In other words, He would write His laws on my heart,
and help me to abide in Christ's commandments.

I truly do despair of life as it is right now.
Against my understanding, I have been terrorised by demons - being punished and tormented without knowing why.
I've just been continually trying to understand why.
And of course, satan has huge numbers of accusations and reasons which he tries to make be believe.

If I'm in the kingdom of God then I feel like a package moving around a busy sorting facility, constantly being tested
and sorted, without end. I've felt constantly under constraint, deprived of sleep, woken up by demons - a messenger of Satan, I think.
And it feels like in my soul, the body of sin, the flesh, is trying to usurp and kill the new creation, and the people around me also placing such unreasonable pressure on me to obey the flesh and to not live in the spirit.
In other words, pressuring me to think like the world thinks, rather than to have the mind of Christ.

And where is the promised testimony of the Holy Spirit as I seek to keep Christ's commandments and abide in His teachings?

I feel like I'm dying sometimes, dying spiritually, losing the fight against the enemy who attacks my soul and attacks me through people around me.

I want to be set free, as Jesus Christ promised for those who He sets free.
I know Jesus bought me but sadly it seems He allowed me to be absolutely terrorised by demons.

Requiring employment/world's assets before marriage proposal is evil, as to require it puts man's kingdom above God's kingdom.
Because to do so would be saying that people have to have what the world says qualifies a person before they have the right to what God freely gave us.
It would be like telling a bird it's allowed to fly only if it can qualify as a human pilot.
It would be like telling a person they don't have a right to become a child of God through faith in Jesus Christ.
It would be like hating Jesus Christ, the Light of the world, so putting Him to death on a tree.
Denying what is given to us as a right is anti-God.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%204%3A1-3&version=ESV][I Timothy 4:1-3]]* - Now the Spirit expressly says that in later times some will depart from the faith by devoting themselves to deceitful spirits and teachings of demons, through the insincerity of liars whose consciences are seared, who *forbid marriage* and require abstinence from foods that God created to be *received with thanksgiving by those who believe and know the truth*. (ESV)
#+END_QUOTE

Do I have the right to ask?
Most of the trees in the Garden of Eden, Adam and Eve were freely allowed to eat.
What is permissible. What is unhelpful?
What are my freedoms?

I'm not under Mosaic Law.
I'm not under man's tradition.
I'm under Christ's Law and Grace and Truth came through Jesus Christ. All Christ's commandments are Grace and Truth!
That means I'm under grace and under Christ's Law at the same time! ([[https://www.biblegateway.com/passage/?search=Isaiah%2041%3A1-4&version=ESV][Isaiah 41:1-4]], [[https://www.biblegateway.com/passage/?search=Romans%2015%3A12&version=ESV][Romans 15:12]], [[https://www.biblegateway.com/passage/?search=Matthew%2012%3A19-21&version=ESV][Matthew 12:19-21]], [[https://www.biblegateway.com/passage/?search=Isaiah%2011%3A10&version=ESV][Isaiah 11:10]])

Under Christ's Law, I'm allowed to propose marriage if I'm doing it lawfully, receiving with thanksgiving, knowing the truth,
while keeping God's Great Commandments, while holding faith in Jesus Christ, while following Jesus Christ, while keeping Christ's Law with a good conscience.

I can't claim total [[https://selfdenial.org.nz/][self-denial]] with this one. So I can't claim perfect innocence.

I was simply told by a member of their family, "Any further contact (with them) is unlawful."
If I told someone, "It's unlawful to talk to some person.", does that make it unlawful?
Do they have that right to tell me what is lawful or not?
I wanted to marry someone (and I don't think I'd told any of them at that stage), and I was told before revealing my desire that "any further contact with any member of their family was unlawful" (not from a police officer) at the time.

And I was born-again of the spirit.
Was I born-again of the spirit after or before being told that any further contact is unlawful? Pretty sure it was after, but not certain, as didn't make a record.
I was made into a new person. New creation. Then I made contact and proposed later in the year.
I was born-again and simply became preoccupied with Jesus Christ and later that year I proposed.
Even after being born-again, I was simply gutted at the thought of not hearing from her again. I was aware even after being born-again of the spirit (made new) that I was told before revealing my desire that "Any further contact is unlawful" by a member of their family.
To not propose to her would feel like destroying something very pure.

Later, I proposed to her but I was taken to court over it.
Anyway, at pleading guilty, I committed my way to the Lord Jesus Christ, and I felt like I wasn't allowed to move forward even after I committed my way.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%2037%3A5&version=ESV][Psalms 37:5]]* - Commit your way to the LORD; trust in him, and he will act. (ESV)
#+END_QUOTE

One court judge said I must have been baptised at midnight. The other court judge said "That is your opinion" in response to me saying that "Jesus is the Truth" in a letter to him. And he said that I'm not allowed to forgive.
But I pleaded guilty effectively to harassment for exercising free speech (2 out of 3 of the brail breaches claims from my perspective were not lawful but I couldn't take the other side to trial because I didn't want to hurt her, rather I still had lots of joy over proposing, but as soon as court proceeding started, I truly didn't want to break the law. The bail breach claims from my perspective were unlawful. I didn't really know it was her who was distressed, but I didn't want to cause her any distress.
I had no fear over punishment at all. I didn't care about career. To take them to trial would waste their time and money and it would not be exercising Christ's love if I were to take them to trial over it. The first bail breach was the only valid one from my memory. But the same time, it was graceless. I breach bail for asking, "Can I try ask again in a year?" after a police officer simply said, "The smartest thing I can do is just drop it", just after I had proposed marriage. Like the Terminator arriving at my door after having proposed to the love of my life. And so I broke bail the first time for asking again if I could ask in a year. I guess I have a human heart. Can I be taken to prison for that, proposing while under unreasonable constraint? Probably only by a system which is anti-human) and neither was I forcing someone to marry me, simply making an offer.

Now, in committing to that path of going my separate ways, I have had immense pressure from other people and through demonic dreams, to renege on that commitment.

I need God to set me free from satanic oppression over my life.

I feel like God would betray me to force me to find secular employment before having a wife.
Why? Because I had put Jesus first before marriage.
It feels like having to hold my breath and resist the urge to breath in 'dying' to that marriage proposal.
And after doing so I would see it as purely evil to not allow me to move forward on that commitment to move forward.
To hold me in this position would be like to not even allow a person to die while drowning at the bottom of the ocean, a person who was there in the first place because they didn't want to harm their neighbour.

However I'm totally willing to work for God as Adam did before God made Eve, that's fine.
Man is espoused to Christ first. Christ the head of the man, and man the head of the wife.
Not the Pope as head of the man, but Christ Himself as head of the man.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%2011%3A2-3&version=ESV][II Corinthians 11:2-3]]* - I feel a divine jealousy for you, for I betrothed you to one husband, to present you as a pure virgin to Christ. But I am afraid that as the serpent deceived Eve by his cunning, your thoughts will be led astray from a sincere and pure devotion to Christ. (ESV)
#+END_QUOTE

Whatever has happened to me has been grossly lacking in grace.

I have no desire at all to ever propose to anyone else ever again.
I want all my memories to be erased.
I want God to honour His own words and send Holy Spirit to make testimony of Jesus Christ to me.

Just to be clear, this ball rests in God's courts. I feel as though I have not been fairly delt with by God, and if I have a bone to pick with anyone, it is only with God.

** Journal <2025-07-26 Sat>
I confess yesterday I got very upset with the Lord Jesus in my prayers.
I have had such heavy spiritual attack.
I don't understand it.
And sometimes I've put the blame on the Lord.
But God knows I love Him, and I have my hope set on Him.

Almost every single night I've been getting hit with such antichrist dreams and visions.
Antichrist. Literally, demons/satan putting evil in my mind as I'm sleeping.
Pure darkness. Stuff that is anti-God, anti-Christ, adulterous, lying, harassing dreams and visions.

And on top of that, the collective pressure on me, through spirit-spouse stuff, or so-called Christians refusing to help me, as I strive obediently to Jesus, and suffer for it.
It's very isolating, and sometimes the pressure gets to me.

The pressure of resistance against me as I try to live for righteousness (in the way God wants me to) feels like being an infant holding up a church building while all the adults flee/ turn a blind eye, or like the man in the story of the "Good Samaritan" who's bean beaten and left for dead on the side of the road needing to save himself and all the "Christians" turn a blind eye.

I may feel as though I'm in a "spiritual prison" feeling unable to work and marry.
But I want to be completely delivered from the true spiritual prison which is sin.
Sin is a spiritual prison.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%208%3A34-35&version=ESV][John 8:34-35]]* - Jesus answered them, Truly, truly, I say to you, everyone who commits sin is a slave to sin. The slave does not remain in the house forever; the son remains forever. (ESV)
#+END_QUOTE

Believing in Jesus Christ, that is with true faith, faith which loves the truth, we have the right to become children of God. We are given the right to be sanctified, delivered from sin, to be able to love our family in Christ and practice righteousness:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%201%3A12-13&version=ESV][John 1:12-13]]* - But to all who did receive him, who believed in his name, he gave the right to become children of God, who were born, not of blood nor of the will of the flesh nor of the will of man, but of God. (ESV)
#+END_QUOTE

This right is not for everyone, but only for those who receive Jesus Christ, who God has given Jesus Christ:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2017%3A9&version=ESV][John 17:9]]* - I am praying for them. I am not praying for the world but for those whom you have given me, for they are yours. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2017%3A8&version=ESV][John 17:8]]* - For I have given them the words that you gave me, and they have received them and have come to know in truth that I came from you; and they have believed that you sent me. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2017%3A17&version=ESV][John 17:17]]* - Sanctify them in the truth; your word is truth. (ESV)
#+END_QUOTE

Even Simon the magician believed and was baptised but it is evident that even the Apostle Peter recognised that Simon might perish. As far as I can tell Simon had not yet received Holy Spirit. His heart still wasn't right. Just like Simon, we must receive the love of the truth in our heart to be saved. Simon was instructed to *repent from sin*. While true agape love is the bond of perfection, I think the bond of iniquity might mean a love of darkness. Simon had to relinquish his sinful desire. Likewise, the rich young ruler (in Mark 10:17-27) had a love of worldly possessions. We need to agape love the truth and fall out of love of darkness. Even as believers, we need to continue on in the teachings of Christ to be saved:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%208%3A13-23&version=ESV][Acts 8:13-23]]* - _Even Simon himself believed, and after being baptized he continued with Philip._ And seeing signs and great miracles performed, he was amazed. Now when the apostles at Jerusalem heard that Samaria had received the word of God, they sent to them Peter and John, who came down and prayed for them that they might receive the Holy Spirit, for he had not yet fallen on any of them, but they had only been baptized in the name of the Lord Jesus. Then they laid their hands on them and they received the Holy Spirit. Now when Simon saw that the Spirit was given through the laying on of the apostles' hands, he offered them money, saying, Give me this power also, so that anyone on whom I lay my hands may receive the Holy Spirit. But Peter said to him, May your silver perish with you, because you thought you could obtain the gift of God with money! *You have neither part nor lot in this matter, for your heart is not right before God.* *Repent*, therefore, of this wickedness of yours, and pray to the Lord that, if possible, the intent of your heart may be forgiven you. For I see that you are in the gall of bitterness and in *the bond of iniquity*. (ESV)
#+END_QUOTE

Jesus' words are true. As I understand it, probably Simon Magus "had" salvation when he believed and was baptised but salvation is a process and as Jesus says, the devil steals the word from a person's heart so that they do not believe. So a person must continue in true faith. As I currently understand it, we also must not "fall away". We must endure in our faith. Simon Magus needed to repent from sin to receive Holy Spirit and in order to continue on in true justifying faith in Jesus, as I understand it:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Mark%2016%3A16&version=ESV][Mark 16:16]]* - Whoever believes and is baptized will be saved, but whoever does not believe will be condemned. (ESV)
#+END_QUOTE

Jesus said to these believers that if they abide in His word (and I believe that means keep His word, even in obedience), they are His disciples - so a person can be a believer before they are a disciple. But we're supposed to make this transition:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%208%3A31-32&version=ESV][John 8:31-32]]* - So Jesus said to the Jews _who had believed ([[https://biblehub.com/greek/4100.htm][4100. pisteuó]], [[https://biblehub.com/greek/pepisteukotas_4100.htm][pepisteukotas]]) in him_, *If you abide in my word, you are truly my disciples*, _and you will know the truth, and the truth will set you free._ (ESV)
#+END_QUOTE

+ [[https://www.youtube.com/post/UgkxKlxBDwokSWnxgDkR9CzlforNxK9jMQ09][youtube.com: Post from Ruben Solorzano]] :: Hulk Hogan has passed away at 71. Here is a picture of him getting baptized only a year ago, which he said was "the greatest day of his life." He said, "Knowing of Jesus and knowing Him are two different things. Come to Him, He'll clean you up. He's the only thing that really matters." Our prayers are with his family.

I believe that Simon the magician after initially believing the gospel and being baptised needed to continue in obedience to God, continue trusting in Jesus, turn away from wickedness, purify his heart, draw near to God and receive Holy Spirit and be sanctified:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=James%204%3A8&version=ESV][James 4:8]]* - *Draw near to God, and he will draw near to you*. Cleanse your hands, you sinners, and *purify your hearts, you double-minded*. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Thessalonians%202%3A10&version=NASB][II Thessalonians 2:10]]* - and with all the deception of wickedness for those who perish, because they did not receive the love of the truth so as to be saved. (NASB)
#+END_QUOTE

** Journal <2025-07-28 Mon>
I've been getting hit real hard with spiritual attacks.
Dreams that are anti Jesus Christ, and trying to temp me into fantasizing about sexual immorality, and this defilement which tries to arouse my body.

I don't see it as fair at all that I come under such heavy spiritual attack,
given relationship/marriage and job denial etc. and these crazy accusations of sexual immorality by harassing demonic dreams to get bombarded with these utterly satanic dreams during the night it's just disgusting and not right.

They're unwelcome.

Jesus Christ help me. I don't know why this is happening.

I believe that Jesus Christ who is the Son of God bled and died for my sins.
I trust in His blood.
I have the hope of salvation.
I trust and hope in his shed blood that I am being sanctified.

I have been born-again to a living hope.

#+BEGIN_QUOTE
  *I Peter 1:3-5* - Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead, to an inheritance that is imperishable, undefiled, and unfading, kept in heaven for you, who by God's power are being guarded through faith for a salvation ready to be revealed in the last time. (ESV)
#+END_QUOTE

Jesus rose from the dead for my justification.
I hold my faith in Him.
I hope in Him.
I treasure Him.
I treasure that hope.
I agape love Him.
I agape love that hope.

I'm not going to be intimidated by the devil, and scared away from "doing good" and from endeavouring to walk in holiness and to be cleaned from every defilement of spirit and flesh.

#+BEGIN_QUOTE
  *II Corinthians 7:1* - Since we have these promises, beloved, let us cleanse ourselves from every defilement of body and spirit, bringing holiness to completion in the fear of God. (ESV)
#+END_QUOTE

God forgive me for my failings but clean me Jesus Christ, clean me.

And in Jesus Christ's name, I rebuke satan and his demons which have been trying to push me into unholiness, through harassing me, isolating me and messing with my soul/sensations, etc. and pushing evil thoughts into my head.

Jesus is the Christ, the Son of God.
Jesus is Jehovah, God the Son.
There is One True God, existing as Father, Son and Holy Spirit. AMEN!!

** Journal <2025-07-28 Mon 16:53>
It's the afternoon.
I feel as though Father God may have led someone to talk to me today.
I just pray for them that my testimony of Jesus saving me, making me born-again, will have a positive impact on them. That the Holy Spirit will lead them into all truth, and that they will just have a love of Jesus Christ, and learn to keep Jesus' commandments better.

Dear Heavenly Father and my Lord Jesus Christ and Holy Spirit,
Jehovah, Almighty God,
Lord, help the person who talked to me today to abide in Christ's commandments and help me also,
and help them to not bear a grudge, and I ask the same for me.
Lord Jesus Christ, I can't live like this.
I want to be healed and restored.
I've asked You countless times, LORD God.
Countless times.
Countless times, really believing that if I don't receive deliverance that it'd be my destruction.
When literally satan and his demons attack my mind, and relationships, and my body/soul etc. I feel violated and depressed and I feel like sometimes I'm not strong enough to resist the enemy's attacks.
Sincerely, Jesus Christ, I believe that You need to heal me and protect me, and follow through with Your promise that Holy Spirit will testify of You to me, to those who abide in Your word, and keep Your commandments.
Sincerely, I do not believe I have had sufficient grace at all to protect me from what's happened.
I've been born-again and what happened after that is the stuff of nightmares and horror stories.
I hope I don't have to live with these memories.
So please, God, help me Jesus Christ.
I believe You bled and died for my sins and rose for my justification.
How can You let me perish when I'm trusting in You?
Don't let me perish but heal me and protect my soul.
In Jesus Christ's name, I ask,
AMEN!!


Just to be honest. I feel spiritually very vulnerable.
Like, I don't want to die.


Just to describe the situation:
- My typical day looks like:
  - Waking up to extreme demonic harassment
    - I feel like from time to time are demons entering and exiting my body frequently, or something like that,
      - these demons have been violating me mentally and sexually.
      - sometimes during the day when I'm less vulnerable because I'm awake
      - I've been getting these attacks daily for over 2 years, and I'm feeling weak.
  - Leave the house, help people asking for help on the street
  - Do Bible studying
  - Practice handwriting
  - Spend lots of time thinking about Jesus' teachings
  - Journal
  - Maybe a little emacs programming
  - Play some Cute Defense on StarCraftII
  - Feed my cat twice a day
  - Every night I go to bed trusting in Jesus, trusting Him to keep me safe.
    - But almost every single night without fail, there is so much demonic oppression going on.
  - Almost every time I sit down, I get spiritual attack. Feel like there is a spiritual defilement in my lower body.
  - A ringing in my ears that is triggered when I am tested spiritually (such as through someone asking a question) and subsequently say something / respond to it.
  - Always under the pump financially. Always. If I have money then someone is extremely likely going to ask me for help somehow.
    - Yet, following Christ's commandments has to be done lawfully.
      - Must be done in love, for example.
      - Must be done in faith.
      - Must take care of dependents.
  - I'd be working but I've been denied work. Yet I love doing as Jesus commanded and being the good Samaritan.
  - My joy is coming almost entirely right now from maintaining a good conscience with Jesus and having a relationship with Jesus, following His commandments, i.e. having a real relationship with Jesus.
- People refuse to give me work. They very often "ghost" me. They go dead silent.
  - I blame literally demons actually manipulating other people into doing that by various means
- On a Sunday I often have nice conversations with people. But given the reality of having been born-again, having first hand evidence of the supernatural, of being born-again of the Spirit, and where I'm literally having to live by Christ's teachings/commandments, walking in the Spirit, rather than being worldly-minded, I often see worldly thinking, and compromise within the church walls. Very often.
  - Everything feels like "hard-mode". Like where is the grace for me to be able to live?
- With regards to people I know who I'm close to,
  - I have seen vastly different sides to people
    - Like different people in the same body.
      - I had written this off to one version of a person which listens to Jesus / speaks the truth about God, and another which doesn't, and I'd taken the latter to be "the flesh". Like when a person speaks from the flesh and does not want to listen to God's Word.
      - But honestly, I don't really know what's going on. It just seems like I've seen too much stuff which a regular person shouldn't normally know about of have seen.


There's simply stuff I have seen which I wish that I had not have seen.
God help me.

I honestly don't know how to be delivered from this (well, the bad stuff).
There is good stuff amongst it.
But I feel like I need desperately Jesus to deliver me from evil, heal and sanctify me, and speak to me.
And I feel like I need other Christians to be assisting me instead of turning a blind eye to me.


I need more than just a little bit of reassurance that God's working behind the scenes.
I need Jesus Christ to speak clearly to me, to assure me, encourage me, to let me hear the testimony which Holy Spirit gives concerning Himself (Jesus).
I need deliverance.
I need protection at night.
I need guidance.
I need healing.
I need my soul to be knit back together.
I need grace.
God knows I've asked Him for grace, and for all these things.
Imagine asking God for such things every day, and going to sleep trusting in Him to take care of You, then getting woken up to demons putting stuff in your mind and invading your body.
It's violating on so many levels.
I don't think this is a matter of me being more humble anymore.
I bend over backwards trying to please God, and He lets all this stuff happen to me.
I don't understand why.
Then when stuff gets to me and I succumb to temptation, the spiritual attack I receive intensifies.
It's really horrific being me right now.
Jesus save me.


To whoever's listening. Whatever happened to me felt like crucifying love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control,
99% fruit of the spirit got crucified. Satan tried to destroy me after I got born-again.
Don't get me wrong, I still had some issues. Satan tried to destroy me after I got born-again.
But I had so much joy and peace and faith in God - so much of it, in 2022, despite a lot of self-denial.


#+BEGIN_QUOTE
  *Galatians 5:16-26* - But I say, walk by the Spirit, and you will not gratify the desires of the flesh. For the desires of the flesh are against the Spirit, and the desires of the Spirit are against the flesh, for these are opposed to each other, to keep you from doing the things you want to do. But if you are led by the Spirit, you are not under the law. Now the works of the flesh are evident: sexual immorality, impurity, sensuality, idolatry, sorcery, enmity, strife, jealousy, fits of anger, rivalries, dissensions, divisions, envy, drunkenness, orgies, and things like these. I warn you, as I warned you before, that those who do such things will not inherit the kingdom of God. But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law. And those who belong to Christ Jesus have crucified the flesh with its passions and desires. If we live by the Spirit, let us also walk by the Spirit. Let us not become conceited, provoking one another, envying one another. (ESV)
#+END_QUOTE


I want to be set healed. God help me.
I want my memories erased.
I don't want to be in this world at all.
What on earth am I supposed to do?
