* Journal
** <2024-10-20 Sun>
My earliest memories are of living in Miramar before Weta Workshop.
Today at C3 Church, the pastor took an analogy from Lord of the Rings to describe sin.
What Frodo may have experienced in fiction, carrying the one ring, reminds me of my experience over the last 2 years.
In the books, the ring amplifies evil. The ring turned Sméagol into Gollum.
That's like what sin does to people - it corrupts people and the effects are:
- they are corrupted from the image of God.
- blindness to their condition, death.

People are born with corruption, but as people turn away from the truth and commit sin the corruption magnifies. It doesn't get better.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%206%3A23&version=ESV][Romans 6:23]]* - For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord. (ESV)
#+END_QUOTE

Corruption gets increasingly worse without atonement by blood.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Hebrews%209%3A22&version=ESV][Hebrews 9:22]]* - Indeed, under the law almost everything is purified with blood, and *without the shedding of blood there is no forgiveness of sins*. (ESV)
#+END_QUOTE

Jesus said in [[https://www.biblegateway.com/passage/?search=Matthew%2023%3A26&version=ESV][Matthew 23:26]] (from the ESV), "You blind Pharisee! First clean the inside of the cup and the plate, that the outside also may be clean."
We really don't want corruption in our heart or impurity in our spirit. The outside reflects what's going on inside us, and I don't mean merely our outward appearance. Dare I confess this but I will for the sake of others so they may take sin seriously, after being born-again as I had been repenting (even after being born-again), I have seen things that have made me feel like in some sense my spiritual innocence has been stolen.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%209%3A6&version=ESV][Genesis 9:6]]* - Whoever sheds the blood of man, by man shall his blood be shed, for God made man in his own image. (ESV)
#+END_QUOTE

While sin corrupts, the grace of God through blood of Jesus can restore us. He is the perfect man, and His blood washes us clean from corruption.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%204%3A4&version=ESV][II Corinthians 4:4]]* - In their case the god of this world has blinded the minds of the unbelievers, to keep them from seeing the light of the gospel of the glory of Christ, who is the image of God. (ESV)
#+END_QUOTE

I just didn't expect that after I was born-again that there was going to be a spiritual battle. But there is a battle, and it hit me fast and hard.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%208%3A13&version=ESV][Romans 8:13]]* - For if you live according to the flesh you will die, but if by the Spirit you put to death the deeds of the body, you will live. (ESV)
#+END_QUOTE

Like traumatised Frodo where Hobbiton was essentially ruined for him, I have among other things asked to be born-again again, and that I can be [[https://meninblack.fandom.com/wiki/Neuralyzer][neuralyzed]] because of what I've been through, or raptured and taken to heaven, everything new. But I'm still here, it seems. At least I've been brought into Christ.

** <2025-03-02 Sun>
I received a picture in my sleep (Psa 1).

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%201%3A1-6&version=ESV][Psalms 1:1-6]]* - Blessed is the man who walks not in the counsel of the wicked, nor stands in the way of sinners, nor sits in the seat of scoffers; but his delight is in the law of the LORD, and on his law he meditates day and night. He is like a tree planted by streams of water that yields its fruit in its season, and its leaf does not wither. In all that he does, he prospers. The wicked are not so, but are like chaff that the wind drives away. Therefore the wicked will not stand in the judgment, nor sinners in the congregation of the righteous; for the LORD knows the way of the righteous, but the way of the wicked will perish. (ESV)
#+END_QUOTE

A brother in Christ gave me this yesterday:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2021%3A15-18&version=ESV][John 21:15-18]]* - When they had finished breakfast, Jesus said to Simon Peter, Simon, son of John, do you love me more than these? He said to him, Yes, Lord; you know that I love you. He said to him, Feed my lambs. He said to him a second time, Simon, son of John, do you love me? He said to him, Yes, Lord; you know that I love you. He said to him, Tend my sheep. He said to him the third time, Simon, son of John, do you love me? Peter was grieved because he said to him the third time, Do you love me? and he said to him, Lord, you know everything; you know that I love you. Jesus said to him, Feed my sheep. Truly, truly, I say to you, when you were young, you used to dress yourself and walk wherever you wanted, but when you are old, you will stretch out your hands, and another will dress you and carry you where you do not want to go. (ESV)
#+END_QUOTE

A bunch of other stuff happened but my days are too packed to explain it all.

* <2025-02-05 Wed> Journal
When it comes to dreams I get, I don't trust anything which doesn't confess Jesus, but I will often take them and use them as prompts to do a Bible study, and run things by the Scripture.

** I had a dream conversation with someone
Lots of tall waves going through a town square.
Me clinging to the top of a tall streetlight to withstand waves of water flowing through what looked like a courtyard.
I then talked to a young kid (and I remember seeing a square rainbow) explaining to him what is love.

God loved us first, and we then love.
A crucial part of love is forgiveness.
We forgive because God forgave us first.
God loved us first. God forgave us first.

Then I heard a voice that said, "God says abide in love".
And I thought be rooted and grounded in love.

In the dream, though, the name "Jesus" wasn't confessed at all, and neither was there a call to holiness.

Also I want to stress, that God's grace teaches us to deny ungodliness:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Titus%202%3A11-14&version=ESV][Titus 2:11-14]]* - For the grace of God has appeared, bringing salvation for all people, training us to renounce ungodliness and worldly passions, and to live self-controlled, upright, and godly lives in the present age, waiting for our blessed hope, the appearing of the glory of our great God and Savior Jesus Christ, who gave himself for us to redeem us from all lawlessness and to purify for himself a people for his own possession who are zealous for good works. (ESV)
#+END_QUOTE

** A second dream: I just said this in a dream as a response to a question - it's spiritually inspired, hopefully from God
- Why do we love, We love because God loved us first.
- We forgive because God forgave us first.
- Why are we to be holy? Because God said, "Be holy for I am Holy."

So why do we not want to be dominated by superintelligent AI? Because God designed us to take dominion over the planet, not to be overcome by it.

*** Christians spread our kingdom not through physical force
For those in Christ, we don't seek world domination, but by seeking the kingdom of God and His righteousness through faith in Jesus who is the Christ, the Son of God, we "overcome the world". And we are sanctified, keeping God's commandments, loving one another in Christ, and coming to the knowledge of the Truth, knowledge of God the Father and God the Son with His Holy Spirit, and receive an inheritance in Christ in heaven. we do that by being found in Christ, we do that by being servants in Christ.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Mark%208%3A36&version=ESV][Mark 8:36]]* - For what does it profit a man to gain the whole world and forfeit his life? (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%201%3A26&version=ESV][Genesis 1:26]]* - Then God said, Let us make man in our image, after our likeness. And let them have dominion over the fish of the sea and over the birds of the heavens and over the livestock and over all the earth and over every creeping thing that creeps on the earth. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%2020%3A32&version=ESV][Acts 20:32]]* - And now I commend you to God and to the word of his grace, which is able to build you up and to give you the inheritance among all those who are sanctified. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Ephesians%205%3A5&version=ESV][Ephesians 5:5]]* - For you may be sure of this, that everyone who is sexually immoral or impure, or who is covetous (that is, an idolater), has no inheritance in the kingdom of Christ and God. (ESV)
#+END_QUOTE

As a born-again Christian, we are to receive an inheritance.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Peter%201%3A3-5&version=ESV][I Peter 1:3-5]]* - Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead, to an inheritance that is imperishable, undefiled, and unfading, kept in heaven for you, who by God's power are being guarded through faith for a salvation ready to be revealed in the last time. (ESV)
#+END_QUOTE

+ Quote from John Piper :: "We don't kill to spread our kingdom. We die to spread our kingdom." AMEN!!

#+BEGIN_QUOTE
  *I Timothy 1:8-11* - But we know that the Law is good, if one uses it lawfully, realizing the fact that law is not made for a righteous person, but for those who are lawless and rebellious, for the ungodly and sinners, for the unholy and profane, for those who kill their fathers or mothers, for murderers and immoral men and homosexuals and kidnappers and liars and perjurers, and whatever else is contrary to sound teaching, according to the glorious gospel of the blessed God, with which I have been entrusted. (NASB)
#+END_QUOTE

** Lastly, I got home and saw the news that Trump is going to the Gaza strip

I just want to say that I believe we should overcome evil with good. Christians should speak and side with the truth in love.

#+BEGIN_QUOTE
  *Romans 12:19-21* - Beloved, never avenge yourselves, but leave it to the wrath of God, for it is written, Vengeance is mine, I will repay, says the Lord. To the contrary, if your enemy is hungry, feed him; if he is thirsty, give him something to drink; for by so doing you will heap burning coals on his head. Do not be overcome by evil, but overcome evil with good. (ESV)
#+END_QUOTE

** Yesterday morning among all the spiritual attack I got, I heard in my sleep
"Our God will be exalted".

But it carried literally no confession of Jesus, so I don't know who or what was speaking to me or who's God it is.

I know "my" God, Jesus, is exalted:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Isaiah%2033%3A5&version=ESV][Isaiah 33:5]]* - The LORD is exalted, for he dwells on high; he will fill Zion with justice and righteousness, (ESV).
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%205%3A31&version=ESV][Acts 5:31]]* - God exalted him at his right hand as Leader and Savior, to give repentance to Israel and forgiveness of sins. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Philippians%202%3A9-11&version=ESV][Philippians 2:9-11]]* - Therefore God has highly exalted him and bestowed on him the name that is above every name, so that at the name of Jesus every knee should bow, in heaven and on earth and under the earth, and every tongue confess that Jesus Christ is Lord, to the glory of God the Father. (ESV)
#+END_QUOTE

** More spiritual attack - a diatribe

+ Journal: <2025-03-15 Sat> :: I'm sick and tired of being left undelivered from this defiling spiritual prison which I have been put in, prevented from working and marrying and continually harassed by demons, seeing sides to people I love which I wish I could have totally erased from my memory forever. I am begging You God to make this evil end today. I feel as though there are still demons which are keeping track of the amount of money I have and accusing me and slandering me when I'm trying to obey Jesus to the best of my ability.
  What I have been put through has been a living nightmare.
  This morning yet another day just being harassed by evil dreams and visions being pushed into my head, and this [[https://pastorvlad.org/spiritualspouses/][spirit spouse]] stuff, and the unreasonable amount of being put on trial.
  If it's not an actual courthouse then it's demons challenging me through various people over extreme scrutiny of my obedience to Jesus.
  While I am continually "ghosted" by people going silent on me - it's absolutely satanic stuff.
  It's been well over 2 years of this type of torment now, almost exactly daily.
  The events surrounding me being born-again of the Spirit are pure abomination.
  There's things I have witnessed that are unspeakably dark and scar my memory.
  I wish that God would make me born-again again whilst erasing my memories and ensure the types of things I have been through would never recur in this life or the next.
  I feel like my redemption is the most compromised botched-job redemption in the history of mankind.
  It's a living and enduring hell on earth which I've been going though - spiritually.
  In the material, NZ is pretty OK, but spiritually I'm being put through hell making the events of 2020-2021 regarding the covid pandemic and lockdowns look like nothing.
  But I know the Christians in Syria, for example, are suffering terribly - I can't imagine how awful it would be for them.
  But it's no consolation to me to be allowed to go on living in this world.
  I'd definitely rather not be here in this world.
  Is it too much to ask of God to be delivered from almost continual demonic harassment?
  I assume that [[https://www.biblegateway.com/passage/?search=2%20Corinthians%2012%3A9&version=ESV][II Corinthians 12:9]]'s "My grace is sufficient for you" does not apply.
  How can anyone function when the joy of being clean, being saved, or being able to help people in need or being able to have a wife or family is taken away?
  What has continued harassing me and trying to destroy my life is disgusting.
  To practice righteousness is a right given to people who trust in Jesus' name so I consider to not
  be able to do so to be a violation of my right in believing in Jesus
  and to be prevented from doing so is antichrist.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%20109%3A21&version=ESV][Psalms 109:21]]* - But you, O GOD my Lord, deal on my behalf for your name's sake; because your steadfast love is good, deliver me! (ESV)
#+END_QUOTE

** Yesterday on <2025-03-16 Sun> - an encouragement
At church at both [[.][Elim]] and [[https://www.c3dunedin.org/][C3]] yesterday the last song we sang was "[[https://www.youtube.com/watch?v=Xx7eoZAMzgo][We Exalt Thee]]".
And at C3 yesterday my pastor started the new series on Contending prayer, and highlighted the book of Habbakuk,
a prophet who prayed such prayers as this:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Habakkuk%201%3A1-3&version=ESV][Habakkuk 1:1-3]]* - The oracle that Habakkuk the prophet saw. O LORD, how long shall I cry for help, and you will not hear? Or cry to you Violence! and you will not save? Why do you make me see iniquity, and why do you idly look at wrong? Destruction and violence are before me; strife and contention arise. (ESV)
#+END_QUOTE

That was an encouragement.

** <2025-03-17 Mon>
This morning I get a dream of a big sign outside the SpaceX rocket facility which just says Jesus is [our] King and Lord - well I'd hope that is
what the people there believe.
Actually, I'll describe the full dream because it was kinda funny.

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  Firstly, in the dream this morning, there was a large rocket on the launchpad with the top half
  slightly askew, and rocket fuel having leaked on the pavement, and Elon and a bunch of others walking towards
  the rocket, saw it and realised they were walking near the rocket fuel and with
  worried faces slowly paced back in reverse.
  Then I saw a bunch of firefighters levitating over the pavement with hoses squirting some kind
  of fire retardant liquid over the exposed rocket fuel, making it so the fuel could not ignite.
  They were hovering down the pavement neutralising the rocket fuel,
  the soles of shoes were spraying neutraliser themselves onto the pavement below, making them hover over the pavement,
  working like little jetpacks for their feet - it was a cool dream.
  
  Then I myself made my way through the side office building and on the interior wall
  was a sign which just said "Jesus is [our] King and Lord" (I think it may have said 'our'. I'm recalling something I say in a dream. I can't remember precisely.),
  and an old mate from old workplace Tim F. was linking arms with me.
#+END_SRC

Funny dream, sure, but honestly, I have no interest in working in technology again.
I don't want raptor engines. I want to be raptured. I want to be delivered from several things:
- spirit spouse stuff
- harassing dreams and visions which have nothing to do with God, and nothing to do with serving God, and nothing to do with the truth of God

Just because a dream contained the name of Jesus in it does not make it a true dream.
Also, I'm not saying building rockets to set up a mars base is unloving or evil or anything like that.
But I've been trying to fight back against whatever has been trying to pressure me to go back to my old-creation self, and the pressure has been huge.
For example, the pressure against me repenting from being indifferent about LGBT, for example, has been huge.
As soon as I began repenting of that, the devil began harassing me with LGBT-affirming dreams and dreams which are outright lewd and kept bombarding me with that nonsense for at least a couple of years now almost daily.
When I want to focus on Jesus, the devil also deprives me of sleep and wakes me up to dreams of technology and first-person shootem-ups.
During Lent I've been bombarded with visions of eating things.
This type of thing - demonic harassment.

So the dream must have a confession of the truth about Jesus and to be sure
about it it needs to have a confession of specifically the exact thing
that the Apostle John mentions in [[https://www.biblegateway.com/passage/?search=1%20John%204%3A2&version=ESV][I John 4:2]] as the Apostle John meant it. And the dream I had today
doesn't leave me totally trusting of it. God is not a God of confusion.
He knows what I expect to hear to trust a dream:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A2&version=ESV][I John 4:2]]* - By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, (ESV)
#+END_QUOTE

I'm so sick of being in this world, and when I pray and ask for things, I seem to never get what I pray and ask for.
In fact, often it just seems as though I get precisely the opposite of what I ask for.
It's just a constant struggle.
I've [[./abominations.org][publicly rebuked the ASI/AGI stuff]] including on my online [[abominations.org][bible study]], and I've never reneged on my stance of it,
being tested through people I have even mentioned it'll never make its way into heaven.
If I was the gatekeeper, I would never allow it. But it just seems sometimes as though evil is unstoppable,
and no matter how much I rebuke something, sometimes the evil just doesn't go away.
And no matter how much I ask God for something which I believe the Scripture says is in His will, I don't receive it,
and worse, it's as though I get the opposite.
When I heard about that stargate project announcement only a few days into the new US presidency,
Instead of smacking down the greed-propelled tower-of-babel false-saviour abomination that it is,
I felt like God in allowing it literally delivers another punch to my face,
and it makes me question whether by allowing it He even cares about people.
The transhumanism propelled ASI/AGI stuff is far worse than the COVID pandemic.
I hate being here in this world so much.
I hate feeling like satan is in control of the world.
I wish that I could have proper joy again over my salvation, and even my prophetic gift again.
I've been asking for deliverance for so long, and I'm sick of being isolated.
I feel as though the crushing pressure on me from all directions has really gotten to me.
I don't get it. I haven't received what I've told God that I have needed for so long,
I'm not a chatbot, I'm a human being.
And in some sense I think not receiving the answers I believe I've needed
has left me with a defiled conscience. What I don't understand is when I ask God for things I believe are in His will and I don't get them,
such as for guidance, or help to get a job so I can help other people in need or my relatives/dependents, or for deliverance from
spiritual attack especially in my sleep.
I was in court in 2022 and I said in a letter to the judge that I forgive the other side and don't bear a grudge,
but the door of freedom on the other side is slammed shut
as if to pressure me to reneging on my declaration that I forgive and want to move on,
then it seems like there is spiritual pressure on me to be denied to walk forwards in the truth, and that has been very confusing for me.
Likewise, wanting to turn away from working in Artificial Intelligence / technology and instead find a job helping people,
I've also been prevented from doing so.
Joy-stealing is quite destructive on a person - like undermining a person's joy, particularly in joy God, but also joy in family, is very destructive.
It destroys morale, it makes it much harder to maintain a strong faith and love for God when the joy is undermined.
It's also not the Kingdom of God to be without joy.
It certainly seems as though I've been getting denied the kingdom of God by whatever antichrist spirits have been trying to take away righteousness, peace and joy from me,
that is, righteousness, peace and joy in the Holy Spirit. Yes, whatever is out there and around me attacking me, and meddling in my relationships, has been surely not of the kingdom of God.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%2014%3A17-18&version=ESV][Romans 14:17-18]]* - For the kingdom of God is not a matter of eating and drinking but of righteousness and peace and joy in the Holy Spirit. Whoever thus serves Christ is acceptable to God and approved by men. (ESV)
#+END_QUOTE

Yes, the joy, faith and love though are all rooted in a good conscience with God which is foundational. But seeking to have a good conscience with God, it seems as though
everything has come against me from every direction to try to stop my joy, my faith and my love.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%201%3A5&version=ESV][I Timothy 1:5]]* - The aim of our charge is love that issues from a pure heart and a good conscience and a sincere faith. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%201%3A18-20&version=ESV][I Timothy 1:18-20]]* - This charge I entrust to you, Timothy, my child, in accordance with the prophecies previously made about you, that by them you may wage the good warfare, holding faith and a good conscience. By rejecting this, some have made shipwreck of their faith, among whom are Hymenaeus and Alexander, whom I have handed over to Satan that they may learn not to blaspheme. (ESV)
#+END_QUOTE

Now if I'm given a conviction in a court of law, then I should be offered the ability to work afterwards, so I can help others. Yet I have been unable to find work I think at least partially because now I have a criminal record. But it's not right to convict someone of a crime and then simultaneously deny that they are allowed to do good - that's like telling a sinner they are not allowed to repent or do penance or change their ways to do good. Where is the justice in that?:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Ephesians%204%3A28&version=ESV][Ephesians 4:28]]* - Let the thief no longer steal, but rather let him labor, doing honest work with his own hands, so that he may have something to share with anyone in need. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Luke%2011%3A11-13&version=ESV][Luke 11:11-13]]* - What father among you, if his son asks for a fish, will instead of a fish give him a serpent; or if he asks for an egg, will give him a scorpion? If you then, who are evil, know how to give good gifts to your children, how much more will the heavenly Father give the Holy Spirit to those who ask him! (ESV)
#+END_QUOTE

I require a clear confession of the Truth. If I can have an elaborate dream, then I can receive a clear confession of the Truth, as the Angel spoke to Joseph:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A2-3&version=ESV][I John 4:2-3]]* - By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, and every spirit that does not confess Jesus is not from God. This is the spirit of the antichrist, which you heard was coming and now is in the world already. (ESV)
#+END_QUOTE

God is not a God of confusion. I want clear answers which confess the truth about Jesus:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%2014%3A31-34&version=ESV][I Corinthians 14:31-34]]* - For you can all prophesy one by one, so that all may learn and all be encouraged, and the spirits of prophets are subject to prophets. For *God is not a God of confusion but of peace*. As in all the churches of the saints, the women should keep silent in the churches. For they are not permitted to speak, but should be in submission, as the Law also says. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%201%3A20&version=ESV][Matthew 1:20]]* - But as he considered these things, behold, an angel of the Lord appeared to him in a dream, saying, Joseph, son of David, do not fear to take Mary as your wife, for that which is conceived in her is from the Holy Spirit. (ESV)
#+END_QUOTE

God Almighty please make the spiritual attacks stop:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2017%3A15-17&version=ESV][John 17:15-17]]* - I do not ask that you take them out of the world, but that you *keep them from the evil one*. They are not of the world, just as I am not of the world. Sanctify them in the truth; your word is truth. (ESV)
#+END_QUOTE

*** <2025-03-18 Tue> Why did this happen to me?

Expectation of this happy relationship with God:

#+BEGIN_QUOTE
  *Psalms 16:7-11* - I bless the LORD who gives me counsel; in the night also my heart instructs me. I have set the LORD always before me; because he is at my right hand, I shall not be shaken. Therefore my heart is glad, and my whole being rejoices; my flesh also dwells secure. For *you will not abandon my soul to Sheol, or let your holy one see corruption*. You make known to me the path of life; in your presence there is fullness of joy; at your right hand are pleasures forevermore. (ESV)
#+END_QUOTE

Reality of what I've experienced and are still going through:

- I feel like the corrupting influence of demons assailing me at night and when I sit down has left me feeling a little corrupted.
- I've been denied to live like a human being. Denied work, marriage, etc.
  - Imagine a dog chained to a pole and for years, and now substitute dog for human being, and that's basically my situation.
- My flesh feels corrupt as a result of being in what feels like the pit/abyss or on the verge of it.
- I have been harassed by evil spirits near continuously for close to 3 years.
  - Particularly at night. Basically every night I receive invasive dreams, visions and voices which are against the truth of God.
  - Almost every day I go to bed fully expecting God will deliver me, but it hasn't happened, and I'm at this point now.
- I feel like I missed the rapture and got abandoned to Hades/Sheol.
- I had simply tried to follow Jesus out of faith, love, obedience for Jesus after getting born-again and this happened to me.
- My joy is basically gone.
  - My joyous feeling of being washed clean by the blood of Jesus has been taken away.
    - That happened once, but now I feel like a dirty garment.
  - It feels like my good conscience with God has been corrupted. I haven't been given answers that I need and I've been forced forward without them.
- I feel like the entire world has become a personal hell created just for me after I called-out the AI stuff and then got born-again.
  - Now I feel like I'm forced to live in hell tailored/designed specifically for me
  - I feel like the AI stuff just rammed itself into my born-again life / tries to force itself into the kingdom of heaven
    - Well living inside a video-game or being forced to treat robots like people is definitely not heaven to me
- Given marriage denial, and being forced to be in this world and feeling ignored by God, my heart is almost always downcast and depressed now.
- On [[https://web.archive.org/web/20220402091720/https://mullikine.github.io/posts/astral-projection-pt-2/][3 May 2022]] it was me who confessed to whatever spirit was there that my God is the True God, the God of Truth, Jesus saved me from lies and the Holy Spirit is my comforter
  - I confessed it. I asked the spirit if it was the Holy Spirit and the spirit said, "Yes. I'll take a look at you."
  - Was it the Holy Spirit?
    - Despite [[https://www.biblegateway.com/passage/?search=Matthew%205%3A37&version=ESV][Matt 5:37]], the correct interpretation of [[https://www.biblegateway.com/passage/?search=Matthew%205%3A37&version=ESV][Matt 5:37]] may bee seen in James 5:12 and Matt 23:16-22.
    - It was me who confessed Jesus, not the spirit I spoke to. So the spirit I spoke to is untrustworthy.
- On 3 May 2023 I pleaded guilty in court because I didn't want to hurt anyone, and I was still trying to follow Jesus.
- On <2025-01-13 Mon> Monday, I woke up to a voice which said, "What is your faith in?" I responded like this, "My faith is in the Word of God. Jesus Christ and His finished works is the cornerstone of my faith, and keeping and doing his commandments is the foundation of my faith. I obey Righteousness because I obey Jesus. I believe in the Truth because I believe in Jesus." I didn't know but it turned out to be the last day of my sentence.
  - Once again, it's *me* making the confession of faith. And that is what frustrates me. Because I cannot trust the spirits speaking to me.
- God hasn't spoken to me directly to clear things up.

I have some consolation in the fact that I definitely have been chosen out of this world and am not of it,
and that I won't have to have it in my life one day.
I feel like I definitely do not belong in this world.

#+BEGIN_QUOTE
  *John 17:14-26* - I have given them your word, and the world has hated them because *they are not of the world*, just as I am not of the world. I do not ask that you take them out of the world, but that you keep them from the evil one. *They are not of the world, just as I am not of the world. Sanctify them in the truth; your word is truth*. As you sent me into the world, so I have sent them into the world. And for their sake I consecrate myself, that they also may be sanctified in truth. I do not ask for these only, but also for those who will believe in me through their word, that they may all be one, just as you, Father, are in me, and I in you, that they also may be in us, so that the world may believe that you have sent me. The glory that you have given me I have given to them, that they may be one even as we are one, I in them and you in me, that they may become perfectly one, so that the world may know that you sent me and loved them even as you loved me. Father, I desire that they also, whom you have given me, may be with me where I am, to see my glory that you have given me because you loved me before the foundation of the world. O righteous Father, even though the world does not know you, I know you, and these know that you have sent me. I made known to them your name, and I will continue to make it known, that the love with which you have loved me may be in them, and I in them. (ESV)
#+END_QUOTE

Hopefully, God, will sanctify me completely and just rapture me or something.

*** <2025-03-18 Tue> God help me
When I saw Bible-verse of the day emacs package it gave me joy.
I pulled it into Pen.el and it works nice.
The developer on his github page gives GOD the glory and the Copilot AI an acknowledgement:
- https://github.com/kristjoc/votd
I have super mixed feelings about it now though given my position, my stance towards the AGI/ASI stuff.

#+BEGIN_QUOTE
  *Isaiah 42:8* - I am the LORD; that is my name; my glory I give to no other, nor my praise to carved idols. (ESV)
#+END_QUOTE

I don't know what God wants me to do here.
I just feel like I don't belong in this world.
I don't like being forced to imbibe on AI stuff.
I hate AGI/ASI stuff is being rammed into the people's consciences even to the point people get reliant on it.
It literally just feels like the AI stuff just rammed its way into my born-again life and trying to force its way into heaven.
I feel terrible.
I upvoted some of the reddit posts because I want to encourage people to lead people to Jesus. However, I'm not sure if I should.
- https://www.reddit.com/r/emacs/comments/1jb4vrx/bible_verse_of_the_day_as_emacs_dashboard_footer/
I want there to be a good future but I just don't want the AGI/ASI stuff to be in that future.

** <2025-05-25 Sun>
The spiritual attack has continued to escalate over the last week. Today it was quite intense.

#+BEGIN_QUOTE
  *II Corinthians 10:5-6* - We destroy arguments and every lofty opinion raised against the knowledge of God, and take every thought captive to obey Christ, being ready mto punish every disobedience, when your obedience is complete. (ESV)
#+END_QUOTE

We must follow Jesus Christ's commandments to arrive at the knowledge of God. The devil tries to stop us from doing this:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%2010%3A5-6&version=ESV][II Corinthians 10:5-6]]* - We destroy arguments and every lofty opinion raised against the knowledge of God, and take every thought captive to obey Christ, being ready to punish every disobedience, when your obedience is complete. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%202%3A3-6&version=ESV][I John 2:3-6]]* - And by this we know that we have come to know him, if we keep his commandments. Whoever says I know him but does not keep his commandments is a liar, and the truth is not in him, but whoever keeps his word, in him truly the love of God is perfected. By this we may be sure that we are in him: whoever says he abides in him ought to walk in the same way in which he walked. (ESV)
#+END_QUOTE

The devil works to stop us Christians from taking every though captive for obedience to Christ. Much of the spiritual attack comes from people to "stop striving to obey Jesus" and to 'rest'. Only the devil dissuade people from obeying Christ:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Luke%208%3A12&version=ESV][Luke 8:12]]* - The ones along the path are those who have heard. Then the devil comes and takes away the word from their hearts, so that they may not believe and be saved. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%2016%3A17-20&version=ESV][Romans 16:17-20]]* - I appeal to you, brothers, to watch out for those who cause divisions and create obstacles contrary to the doctrine that you have been taught; avoid them. For such persons do not serve our Lord Christ, but their own appetites, and by smooth talk and flattery they deceive the hearts of the naive. For your obedience is known to all, so that I rejoice over you, but I want you to be wise as to what is good and innocent as to what is evil. The God of peace will soon crush Satan under your feet. The grace of our Lord Jesus Christ be with you. (ESV)
#+END_QUOTE

God, I just want deliverance. I want the Lord to make it work for good. I've been through hell ever since I got born-again.

May the Lord Jesus Christ please give me mercy and forgive me for taking out my frustrations on him (especially today), but I have been under such heavy spiritual attack as I follow Him. It's so difficult. The last week has been horrible. Dream attacks and soul-attacks every day. By soul-attacks I mean, manipulating thoughts and senses (spirit-spouse stuff, for example), or getting pictures in my mind as I am trying to concentrate on Jesus' words, say. The pictures are to distract. It's like everything just tries to deter me from obedience to Christ - whether it be the reproach, or the dream attacks, or the fear of punishment or when people (even or especially Christians) dissuade from taking every thought captive to Christ - people don't know how to combat the devil, Biblically, which is through faith and obedience to Jesus Christ (consider Romans 16:19-20, or Re 12:11). I'm constantly rubbing up against the unsanctified parts of fellow Christians who say the opposite of what Jesus and the new testament authors teach. I've received so much reproach, and get hit with dream attacks every day. God give me mercy. The darkness has been a thick cloud around me for a very long time (2 years at least). Trying to remain focused on Jesus.

Teaching the gospel should be about knowing Jesus Christ (His commandments, teachings and prophetic writings about Him, His deeds) and Him crucified:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%202%3A2&version=ESV][I Corinthians 2:2]]* - For I decided to know nothing among you except Jesus Christ and him crucified. (ESV)
#+END_QUOTE

** <2025-05-26 Mon>
I have found that the enemy has been battling extremely hard to steal my thoughts away from Jesus.
The way to fight the enemy away effectively is:
- Think about His words
- Sing worship music in my head
- Obedience to Jesus

The difficult, striving part is mostly in the mind, and heart, and it is keeping my mind, my eyes on Jesus like Peter on the water. I have one Father in heaven. But yesterday I told my earthly dad that "Satan was attacking my mind as the pastor was praying at church. I was getting pummeled by distracting images appearing in my mind as the pastor was praying. But I was under attack like this a lot over the last 3 days", and he responded by saying "Stop trying to obey Jesus. Stop striving." This is what he said right after I mentioned I am under attack. And I also said something I regretted saying almost immediately. And I have asked God probably a hundred times to make the memories of such encounters disappear, and to make it never happen again. But these confrontations continued to happen. This is me explaining that the spiritual attack has been like a thick blanket affecting everything - affecting me in my sleep, affecting my relationships. And it feels like being caught between the wheat and the tares - one force trying to pull me into an "age of evil", and the other when I focus on Jesus, pulling me out of it.

When it comes to family members or people at church saying to do opposite to what the teachings of Jesus and the Apostles say, I recognise that people sometimes speak or act from the flesh, not from the Spirit, but in my observing this means very little, and we'll see each other's unsanctified bits sometimes but the right thing to do is to "love those who hate you."

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Galatians%202%3A11-12&version=ESV][Galatians 2:11-12]]* - But when Cephas came to Antioch, I opposed him to his face, because he stood condemned. For before certain men came from James, he was eating with the Gentiles; but when they came he drew back and separated himself, fearing the circumcision party. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Luke%2022%3A31-32&version=ESV][Luke 22:31-32]]* - Simon, Simon, behold, Satan demanded to have you, that he might sift you like wheat, but I have prayed for you that your faith may not fail. And when you have turned again, strengthen your brothers. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Matthew%2010%3A36-37&version=ESV][Matthew 10:36-37]]* - And a person's enemies will be those of his own household. Whoever loves father or mother more than me is not worthy of me, and whoever loves son or daughter more than me is not worthy of me. (ESV)
#+END_QUOTE

The enemy has been trying to fill my head with all sorts of distracting thoughts as I seek to think about Jesus, and is continually trying to get an edge over me in my fight to maintain Jesus' works.
The enemy keeps trying to steal my attention away from Jesus, and dissuade me from taking every thought captive for Christ, and trying to maintain Jesus' works feels like being bled dry to emotional, physical and spiritual breaking-point, for the sake of remaining faithful to Jesus / maintaining good conscience with Jesus / doing what pleases Him.
And when I tell people I'm under attack, I often get more resistance through people who are thinking in the flesh.
I must fight against this.
However, I'm extremely discouraged now that I haven't been physically taken out of the world.
The gospel is that we are delivered from the present evil age.
And if it seems impossible to be delivered from it through any amount of striving then I end up praying angry prayers to God, and I am angry with God about the amount of spiritual warfare I've been facing, and about being kept here in a world permeated with AI. It feels like satan has taken over the churches.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Galatians%201%3A3-5&version=ESV][Galatians 1:3-5]]* - Grace to you and peace from God our Father and the Lord Jesus Christ, *who gave himself for our sins to deliver us from the present evil age*, according to the will of our God and Father, to whom be the glory forever and ever. Amen. (ESV)
#+END_QUOTE

** <2025-05-29 Thu>
Yesterday, before I went to bed I had briefly seen a video:
- [[https://www.youtube.com/watch?v=nomEdbsx3Tw][youtube.com: Sermon: The Queenship of Mary, by Most Rev. Donald J. Sanborn {@romancatholicmedia}]]
I found it contrived, and distressing the way that Mary was described here as the spiritual spouse of Jesus.
The truth is that Christ's body, the Chruch is the spiritual spouse of Jesus.
And although often Roman Catholics like to claim that the members of their institution is Church or that the Roman Catholic church is the Catholic church, I wholeheartedly disagree.
At best they would be part-of. But the church is the body of Christ (all people who are or have been or will be spiritually united with Christ).

Yesterday, before I went to bed I played StarCraft II and someone on the other team calling themself "LORD" defeated me.
That actually happened.
then I went to bed telling God, I honestly thought I had something good easily taken away from me, because like someone who had never known what it was like to have something good, I was an easy target for the devil to make me think it was bad because it was too good. I had told God before sleeping that it was His fault I was in this situation. It seems like every time I complain to God, I have demons/satan rushing in, as if they're watching what I do, interfering. When I complain to God, I am waiting for deliverance, but the demons which are harassing me are trying to offer a false deliverance.

Something like someone calling themself LORD, happening in real life is no reason to trust anything. Even in the Bible God Himself calls deceptive words man's appellation of the temple that it was God's temple.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Jeremiah%207%3A3-11&version=ESV][Jeremiah 7:3-11]]* - Thus says the LORD of hosts, the God of Israel: Amend your ways and your deeds, and I will let you dwell in this place. Do not trust in these deceptive words: This is the temple of the LORD, the temple of the LORD, the temple of the LORD. For if you truly amend your ways and your deeds, if you truly execute justice one with another, if you do not oppress the sojourner, the fatherless, or the widow, or shed innocent blood in this place, and if you do not go after other gods to your own harm, then I will let you dwell in this place, in the land that I gave of old to your fathers forever. *Behold, you trust in deceptive words to no avail. Will you steal, murder, commit adultery, swear falsely, make offerings to Baal, and go after other gods that you have not known, and then come and stand before me in this house, which is called by my name, and say, We are delivered! — only to go on doing all these abominations? Has this house, which is called by my name, become a den of robbers in your eyes?* Behold, I myself have seen it, declares the LORD. (ESV)
#+END_QUOTE

I went to sleep around midnight.

So at 1 AM, after sleeping 1 hour I wake up the first time.
I can't remember if it was that time or later that I had a dream or something, where in my mind I was saying something like,
"I will not pray the our Father."
Then I woke up and I prayed the our Father prayer in my heart anyway.

Our Father who art in Heaven, hallowed by thy name.
Thy kingdom come, thy will be done on earth as it is done in heaven.
Give us this day our daily bread and forgive us our debts/trespasses as we forgive those who trespass against us.
And lead us not into temptation but deliver us from evil.
For Yours are the kingdom and the power and the glory,
forever and ever. AMEN!!

Even though I do not want to be goaded by demons, I decided to just do what is true anyway and pray to God,
and satan has no part in it.
But I will not be goaded by demons. I didn't pray it "because" the demons say "don't do it".
I prayed because I was woken up, against my will, and I decided I would pray it anyway.

I went back to sleep. I think I might have woken up again and it might have been actually around this time I had that dream of "I will not pray the our Father" prayer. I'm slightly dazed by the sleep disturbances so it's hard to be certain of the exact order.
I also after this had another picture in my sleep "May the Lord Jesus Christ sanctify you completely." Something like this.
And I have prayed to God so many times asking Him to deliver me from the demonic harassment.

So just then at 7AM I got a dream of me telling mum, (meg and ryan there too I think)
that my crypto would be worth 30 million if I had kept it but I was trusting Jesus (and I was thinking, trusting Jesus as I was giving to people who were asking me for help - and this is true).
Then mum told me, "We'll pay for the wedding."
And I said "No, why would I go into debt to pay off a wedding for the next 20 years?" And also, knowing my parents couldn't afford it, I said, "Would I want to kill someone on the day I get married? (putting this massive debt on someone) Why would I want to cause anyone harm on the day I got married [by giving them a massive debt]?"
This was inside Meg and Ryan's old place in Dunedin.
And Meg said, "Come on, let's pick up some rubbish."
And I saw in my mind a picture "She is Proposingondor".

I will still not be goaded by demons.

No lie is of the truth, and in real life I do not know at all what the crypto I gave away would be worth.
At the same time, I will not marry anyone unless I'm delivered from demons and sanctified and God makes it explicitly clear
through an unambiguous message what His will is for me.
Dreams like this are not good enough, sorry.
I will not be goaded by a false-christ, nor by demons.

I rebuke the demonic harassment in Jesus Christ's name.
And once again, I pray to God in Jesus Christ's name that He will help me and set me free from this constant satanic opposition.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20John%204%3A1-3&version=ESV][I John 4:1-3]]* - Beloved, do not believe every spirit, but test the spirits to see whether they are from God, for many false prophets have gone out into the world. By this you know the Spirit of God: every spirit that confesses that Jesus Christ has come in the flesh is from God, and every spirit that does not confess Jesus is not from God. This is the spirit of the antichrist, which you heard was coming and now is in the world already. (ESV)
#+END_QUOTE

I have said it so many times. I need unambiguous guidance from God.
Even an angel speaking to me face to face and confessing Jesus.
And even then, I do not feel sanctified.
I feel like I'm oppressed by demons and have become corrupted as a result of ongoing demonic harassment. And I expect Jesus Christ to continue sanctifying me and deliver me from evil - that is something I ask Him for every single day. I feel like I was abandoned to Hades and that it corrupted me (this is what it currently feels like anyway), and so I'm waiting for deliverance.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%202%3A27&version=ESV][Acts 2:27]]* - For you will not abandon my soul to Hades, or let your Holy One see corruption. (ESV)
#+END_QUOTE

At the same time, other very strange stuff has been going on in my day-to-day - stuff that is highly suspect, spiritually.
And the only right thing to do is to keep eyes on Jesus and not be misled, tempted or distracted by the devil.

Even right now at this moment, writing this, I feel like I'm under attack in my body/soul.
I want total cleansing and deliverance.

Also I still feel like I'm being affected by this spirit of Mormonism.
But I would say there are genuine Christians who may be Mormons.
Someone made a comment saying Reuben (I love the Outdoor Boys channel btw) is a Mormon:
- [[https://www.youtube.com/shorts/_5kD1EIodBQ][youtube.com: The Outdoor Boys talk about Jesus Christ! ? #jesus #christian #celebrity #shorts {@RubenSolorzano_}]]
But all he's talking about here is Jesus Christ and His commandments.
I mean, Jesus sees the heart. He's the Judge.

Why have I been tormented/oppressed/harassed by demons? It's awful.
And on Monday just gone by this person who has said he is gay
confessed his faith to me saying that he believes the gnostic books.
God help me.
I asked him if he believes that Jesus is the Christ and the Son of God, and he
said yes, so I can't condemn him but neither can I see his heart.
I'm being pushed into these situations almost daily.
I think that Mormons, homosexuals and people believing heretical books
all need to turn away from those very things and be sanctified in God's Truth.
God help me.
