* The Truth
Jesus is the only Mediator between us and God.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  I Timothy 2:5
#+END_SRC

** The only Biblical Vicar of Christ is the Holy Spirit

** Christ's unending High Priesthood in Heaven

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Hebrews 7:22-28
#+END_SRC

#+RESULTS:
#+begin_src text
Hebrews 7:22-28
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
This makes Jesus the guarantor of a better
covenant.

The former priests were many in number,
because they were prevented by death from
continuing in office, but he holds his
priesthood permanently, because he continues
forever.

Consequently, he is able to save to the
uttermost those who draw near to God through
him, since he always lives to make
intercession for them.

For it was indeed fitting that we should have
such a high priest, holy, innocent, unstained,
separated from sinners, and exalted above the
heavens.

He has no need, like those high priests, to
offer sacrifices daily, first for his own sins
and then for those of the people, since he did
this once for all when he offered up himself.

For the law appoints men in their weakness as
high priests, but the word of the oath, which
came later than the law, appoints a Son who
has been made perfect forever.

(ESV)
#+end_src

** We have the Holy Spirit

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  II Timothy 3:16-17
#+END_SRC

#+RESULTS:
#+begin_src text
2 Timothy 3:16-17
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
All Scripture is breathed out by God and
profitable for teaching, for reproof, for
correction, and for training in righteousness,
that the man of God may be competent, equipped
for every good work.

(ESV)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Matt 16:18-19
#+END_SRC

#+RESULTS:
#+begin_src text
Matthew 16:18-19
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
And I tell you, you are Peter, and on this
rock I will build my church, and the gates of
hell shall not prevail against it.

I will give you the keys of the kingdom of
heaven, and whatever you bind on earth shall
be bound in heaven, and whatever you loose on
earth shall be loosed in heaven.

(ESV)
#+end_src

John 21

** Refutation of ecumenism
#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  Isaiah 2:6-8
#+END_SRC

#+RESULTS:
#+begin_src text
Isaiah 2:6-8
‾‾‾‾‾‾‾‾‾‾‾‾
For you have rejected your people, the house
of Jacob, because they are full of things from
the east and of fortune-tellers like the
Philistines, and they strike hands with the
children of foreigners.

Their land is filled with silver and gold, and
there is no end to their treasures; their land
is filled with horses, and there is no end to
their chariots.

Their land is filled with idols; they bow down
to the work of their hands, to what their own
fingers have made.

(ESV)
#+end_src

#+BEGIN_QUOTE
  *I Corinthians 15:25* - For He must reign until He has put all His enemies under His feet.
#+END_QUOTE

#+BEGIN_QUOTE
  *I Corinthians 15:27* - For He has put all things in subjection under His feet. But when He says, "All things are put in subjection," it is evident that He is excepted who put all things in subjection to Him.
#+END_QUOTE

+ [[https://youtube.com/watch?v=zNKdyvKEfAI&t=206][youtube.com: John MacArthur: The Challenge of Science @time: 3 min 26 sec]] :: When the creator wrote His book and revealed
    reality regarding His creation He would be
    able to communicate it accurately and truly,
    not dependent upon any discovery at any time
    in history.
    
    So, if we find a book that is a true and accurate
    representation of the way things really are
    in the universe, then we will know that the
    God who created it wrote it.
    
    To approach that another way, whoever created
    reality would never say this: "The moon is
    fifty thousand leagues higher than the sun
    and has its own light.
    
    The earth is flat and triangular composed
    of seven stages, one of honey, one of sugar,
    one of butter, one of wine, and the earth
    sits on the heads of countless elephants who
    produce earthquakes when they shake."
    That is the Hindu holy writings.
    So we know the creator didn't write that.
    
    The Hindu Panishad says the sun is the source
    of all energy in the universe.
    So we know the creator didn't write that.
    
    The creator would never say that there are
    only thirteen members of the body through
    which death can come, as the Taoist holy book
    says.
    So we know He didn't write that.
    
    The Buddhist book says earthquakes are caused
    by wind moving water and water moving land.
    So we know He didn't write that.
    
    The book of Mormon says that Adam fell in
    order that men might come into existence.
    So we know He didn't write that.
    
    The book of Mormon also says in Alma 7:10
    that Jesus was born in Jerusalem.
    So we know He didn't write that.
    
    He would not write what is written in science
    and health and key to the scriptures, that
    "man is not made", I quote "of brain, blood,
    bones and other material elements.
    And man is incapable of sin, sickness and
    death."
    So we know God did not write that.
    
    Christian Science it's called.
    Its like Grape Nuts, they're not grapes and
    they're not nuts, and it's not Christian and
    it’s not scientific either.
    
    Well, I think you get the point.
    That should be enough to make the point that
    we need to check the holy books and see if
    we can't find a book that is accurate, that
    is historically accurate, morally accurate
    and that is scientifically accurate when assessed
    by true science.
    The true creator is going to tell us the truth.
    
    The true creator is an infinitely intelligent
    information and communication genius.
    And He is not going to make mistakes in His
    book, because He has created this entire universe
    to function on a complex unfathomable, inscrutable,
    information system.
    
    The whole universe and all the life that is
    within it depends on information, on the communication
    of precise information.
    So we would expect the book written by the
    eternal and infinite communication genius,
    not to say stupid things, and ridiculous things,
    and things that are not true.
    
    The scripture claims to be that book.
    It claims to be the word of the living God
    who is the creator, sustainer, and consummator
    of the universe.
    The scripture claims to be the inspired revelation
    of God.
    It claims to be accurate in everything it
    says.
    It claims to be inerrant no matter what it
    says because God knows and He has designed
    and developed the information and He has disseminated
    the information on the pages of scripture.
    So, its veracity and its accuracy must be
    sustained under the most intense examination.
    
    The Bible is not a textbook on science.
    It is not a technical book, but wherever it
    intersects with science, wherever it intersects
    with scientific reality, it must be completely
    true and accurate.
    
    True science, the way things really are, can
    have no argument with the scripture written
    by the one who made things the way they really
    are.
    
    The creator is the author.

+ [[https://www.earlychristianwritings.com/text/justinmartyr-resurrection.html][Saint Justin Martyr: Fragments of the Lost Work of Justin on the Resurrection {Roberts-Donaldson}]] :: And God, the Father of the universe, who is the perfect intelligence, is the truth. And the Word, being His Son, came to us, having put on flesh, revealing both Himself and the Father, giving to us in Himself resurrection from the dead, and eternal life afterwards. And this is Jesus Christ, our Saviour and Lord. He, therefore, is Himself both the faith and the proof of Himself and of all things. Wherefore *those who follow Him, and know Him, having faith in Him as their proof, shall rest in Him*. But since the adversary does not cease to resist many, and uses many and divers arts to ensnare them, that he may /seduce the faithful from their faith, and that he may prevent the faithless from believing/, *it seems to me necessary that we also, being armed with the invulnerable doctrines of the faith, do battle against him in behalf of the weak.*
