* Polycarp
[[https://www.earlychristianwritings.com/text/polycarp-lightfoot.html][Polycarp to the Philippians {Lightfoot translation}]]

- [[https://www.youtube.com/watch?v=SkFKQUzH4xI][How Polycarp Gives us Evidence For the Early Use of the New Testament - YouTube]]

Polycarp doesn't contradict the New Testament and doesn't reference books outside of the New Testament.

I think we can take a page from Polycarp in the way the New Testament is read, not accepting teachings which contradict Jesus or the Apostles.

I think this is how we should apply the Epistles.

It's good to read and apply the Bible in a way to not contradict.

* Ignatius
** [[http://persweb.wabash.edu/facstaff/royaltyr/AncientCities/web/bradleyj/Project%201/The%20Epistle%20of%20Ignatius%20to%20the%20Magnesians.htm][The Epistle of Ignatius to the Magnesians]]
Not under the law:

Ignatius to the Magnesians 8* - Be not deceived with strange doctrines, nor with old fables, which are unprofitable. For if we still live according to the Jewish law, we acknowledge that we have not received grace. For the divinest prophets lived according to Christ Jesus. On this account also they were persecuted, being inspired by His grace to fully convince the unbelieving that there is *one God, who has manifested Himself by Jesus Christ His Son, who is His eternal Word*, not proceeding forth from silence, and who in all things pleased Him that sent Him.

Let us live with Christ:

Ignatius to the Magnesians 9* - If, therefore, those who were brought up in the ancient order of things have come to the possession of a newhope, no longer observing the Sabbath, but living in the observance of the Lord's Day, on which also our life has sprung up again by Him and by His death-whom some deny, by which mystery we have obtained faith, and therefore *endure, that we may be found the disciples of Jesus Christ, our only Master*-how shall we be able to live apart from Him, whose disciples the prophets themselves in the Spirit did wait for Him as their Teacher? And therefore He whom they rightly waited for, being come, raised them from the dead.

But we should still die to sin and be His disciples:

Ignatius to the Magnesians 10* - Let us not, therefore, be insensible to His kindness. For were He to reward us according to our works, we should cease to be. Therefore, *having become His disciples, let us learn to live according to the principles of Christianity*. For whosoever is called by any other name besides this, is not of God. Lay aside, therefore, the evil, the old, the sour leaven, and be ye changed into the new leaven, which is Jesus Christ. Be ye salted in Him, lest any one among you should be corrupted, since by your savour ye shall be convicted. It is absurd to profess Christ Jesus, and to Judaize. For _Christianity did not embrace Judaism, but Judaism Christianity, that so every tongue which believeth might be gathered together to God_.

* Irenaeus

