#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

url="$1"

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

pager() {
    if is_tty; then
        vs $@
    else
        cat
    fi
}

{
    if test -f "$url"; then
        ci -E "scrape-and-summarize.py $(aqf "$url") | ttp"
    else
        ci -E "scrape-and-summarize.py $(aqf "$url") | ttp"
    fi
} | pager
