#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

pat="$1"
pathpat="$2"

{
if test -n "$pathpat"; then
    # find . -type f -name "${pathpat}" 1>&2
    find . -type f -name "${pathpat}" -exec cat1 {} \;
else
    find . -type f -exec cat1 {} \;
fi
} | scrape "$pat" | pavs
