cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Isaiah" "5:14-15" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Isaiah" "7:14-15" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Isaiah" "7:18-25" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Isaiah" "64:4" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "Isaiah" "64:4" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/docs/theology;  "Isaiah" "55:11" "#" "<==" "zsh"
