#!/bin/bash
export TTY

. $SCRIPTS/lib/hs

pkg="$1"
test -n "$pkg" || exit 1

x -sh swipl -e "?- " -s "pack_install($pkg)." -c m -e "Y/n" -s Y -e "Create directory" -c m -e "?- " -c d -i

# To get the expect script
# x -n -sh swipl -e "?- " -s "pack_install($pkg)." -c m -e "Y/n" -s Y -e "Create directory" -c m -e "?- " -c d -i | pavs
