* 
- [[https://www.youtube.com/watch?v=btuczasDLPg][youtube.com: Praise and Worship Songs | Christian Songs {@uLearnByJAP}]]
- [[https://www.youtube.com/watch?v=sIaT8Jl2zpI][youtube.com: Lauren Daigle - You Say {Official Music Video} {@laurendaiglemusic}]]

* 
[[https://www.youtube.com/watch?v=TqUwcpu_v-k][youtube.com: Salvation Belongs To Our Lord]]

* 
[[https://www.youtube.com/watch?v=GLugRDi7uH0][youtube.com: The Rock Church]]

* This is a good message
[[https://www.youtube.com/watch?v=dTCV6uWjWn0][youtube.com: The Old Serpent Is Out To Get The Believer -  Mar Mari Emmanuel]]

* Repentance is necessary
#+BEGIN_QUOTE
  *Romans 2:1-8* - Therefore you have no excuse, O man, every one of you who judges. For in passing judgment on another you condemn yourself, because you, the judge, practice the very same things. We know that the judgment of God rightly falls on those who do such things. Do you suppose, O man—you who judge those who do such things and yet do them yourself—that you will escape the judgment of God? Or do you presume on the riches of his kindness and forbearance and patience, not knowing that God's kindness is meant to lead you to repentance? But because of your hard and impenitent heart you are storing up wrath for yourself on the day of wrath when God's righteous judgment will be revealed. He will render to each one according to his works: to those who by patience in well-doing seek for glory and honor and immortality, he will give eternal life; but for those who are self-seeking and do not obey the truth, but obey unrighteousness, there will be wrath and fury. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *Romans 2:9-16* - There will be tribulation and distress for every human being who does evil, the Jew first and also the Greek, but glory and honor and peace for everyone who does good, the Jew first and also the Greek. For God shows no partiality. For all who have sinned without the law will also perish without the law, and all who have sinned under the law will be judged by the law. For it is not the hearers of the law who are righteous before God, but the doers of the law who will be justified. For when Gentiles, who do not have the law, by nature do what the law requires, they are a law to themselves, even though they do not have the law. They show that the work of the law is written on their hearts, while their conscience also bears witness, and their conflicting thoughts accuse or even excuse them on that day when, according to my gospel, God judges the secrets of men by Christ Jesus. (ESV)
#+END_QUOTE

* 
[[https://www.youtube.com/watch?v=N22Bcdc07p8][youtube.com: Dave Dobbyn - Loyal]]

* 
[[https://www.youtube.com/watch?v=D4x6Svur63o][youtube.com: Whatever is Not United With the Lord is Not Saved]]

* Phillip the Evangelist
[[https://www.youtube.com/watch?v=9avCy47rcZ8][youtube.com: I tried so many times to come back to God and failed. | Phillip Blair]]

* 
#+BEGIN_QUOTE
  *I Corinthians 14:15* - What am I to do? I will pray with my spirit, but I will pray with my mind also; I will sing praise with my spirit, but I will sing with my mind also. (ESV)
#+END_QUOTE

Worship music.

* Visit Reece at corrections <2024-08-19 Mon> at 10.30am

* 
[[https://www.youtube.com/watch?v=vQLpFrmQZRs][youtube.com: Truth Triumphs Through Providence]]

* 
[[https://www.youtube.com/watch?v=6dB9hygVhRc][youtube.com: God Is Our Savior from What? 1 Timothy 1:1-2, Part 2]]

* Jehovah Jireh is enough
[[https://www.youtube.com/watch?v=mC-zw0zCCtg&list=PLGvkktFFaDOMQS0vAWVGGzF7846GCKf3G][youtube.com: Jireh | Elevation Worship & Maverick City]]

I will be content in every circumstance.

Forever enough.
More than enough.

* Humility and the value of authentic service
- [[https://www.youtube.com/watch?v=l3jTRB5B9zM][youtube.com: C.S Lewis | "Never Tell People What You Do" | C.s Lewis Motivational Speech]]

Death and life are in the power of the tongue.

* 
- [[https://www.youtube.com/watch?v=6TOLfSucl-o][youtube.com: God Is Eager to Work for You]]
- [[https://www.youtube.com/watch?v=MEYSRQCfIHc][youtube.com: Christ Appeared for Our Sake]]
- [[https://www.youtube.com/watch?v=u68syvK8wso][youtube.com: The Staggering Commandment of Neighbor Love]]
- [[https://www.youtube.com/watch?v=8xLYOKSW_4g][youtube.com: My Servant Will Prosper]]
- [[https://www.youtube.com/watch?v=Gzor3DIfh3k][youtube.com: Who Is Our Enemy?]]
- [[https://www.youtube.com/watch?v=-KJ0287UCdw][youtube.com: Dying Daily and the Call to Love]]

* Watch
e:/volumes/home/shane/var/smulliga/source/git/semiosis/notes-on-sermons/notes-on-sermons.org

- [[https://www.youtube.com/watch?v=dwOm7kov7r0][youtube.com: Keep Rejoicing]]
- [[https://www.youtube.com/watch?v=gB0zlUzJt_M][youtube.com: Christ Has Purchased Global Praise: The Blood, the Beast, and the Boast of Race]]

* John Piper on Faith and Law-Keeping
- [[https://www.youtube.com/watch?v=clrbUjkbNsM][youtube.com: How Our Faith and Law-Keeping Work Together in the Christian Life]]

We're all going to be judged by the divine standards that we have access to, and everybody has access to divine standards that we fall short of:

#+BEGIN_QUOTE
  *Romans 2:11-12* - For *God shows no partiality*. For all who have sinned without the law will also perish without the law, and all who have sinned under the law will be judged by the law. (ESV)
#+END_QUOTE

It's not "having (having possession of) the law" which counts, but "doing it":

#+BEGIN_QUOTE
  *Romans 2:13* - For it is not the hearers of the law who are righteous before God, but the doers of the law who will be justified. (ESV)
#+END_QUOTE

We of course may be /imperfect/ doers of the law, especially as Christians because we are justified by our faith in Jesus:

+ [[https://youtube.com/watch?v=clrbUjkbNsM&t=336][Quote by John Piper]] :: A person today may be a doer of the law who trusts Jesus as the only basis of their justification before God, who in the power of that faith by the Spirit walks in a manner worthy of the LORD and then at the last judgement Christ will be the basis of our acceptance - Christ alone, the basis of our acceptance with the Father and our life of obedience doing the law will be brought in to confirm that our faith was real, because faith works through love. So "doing the law" will not be the _basis_ of our being in God's favour, but the evidence that we are trusting Christ, united to Christ, and thus necessary at the last day.

AMEN!! This has totally been my stance, but John Piper hit the nail on the head with this one.

We can certainly "be obedient to God's commandments" and that is "doing":

#+BEGIN_QUOTE
  *I Peter 1:14-16* - As obedient children, do not be conformed to the passions of your former ignorance, but as he who called you is holy, you also be holy in all your conduct, since it is written, You shall be holy, for I am holy. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *Titus 3:3* - For we ourselves were once foolish, disobedient, led astray, slaves to various passions and pleasures, passing our days in malice and envy, hated by others and hating one another. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *James 1:22* - But be doers of the word, and not hearers only, deceiving yourselves. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *Hebrews 11:31* - By faith Rahab the prostitute did not perish with those who were disobedient, because she had given a friendly welcome to the spies. (ESV)
#+END_QUOTE

Perfect obedience though is something Jesus reached but I certainly have not:

#+BEGIN_QUOTE
  *Philippians 2:8* - And being found in human form, he humbled himself by becoming obedient to the point of death, even death on a cross. (ESV)
#+END_QUOTE

The nations have a form of God's law written on our hearts:

#+BEGIN_QUOTE
  *Romans 2:14-16* - For when Gentiles, who do not have the law, by nature do what the law requires, they are a law to themselves, even though they do not have the law. They show that the work of the law is written on their hearts, while their conscience also bears witness, and their conflicting thoughts accuse or even excuse them on that day when, according to my gospel, God judges the secrets of men by Christ Jesus. (ESV)
#+END_QUOTE

** 
#+BEGIN_QUOTE
  *Romans 3:28-29* - For we hold that one is justified by faith apart from works of the law. Or is God the God of Jews only? Is he not the God of Gentiles also? Yes, of Gentiles also, (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *Romans 5:1-2* - Therefore, since we have been justified by faith, we have peace with God through our Lord Jesus Christ. Through him we have also obtained access by faith into this grace in which we stand, and we rejoice in hope of the glory of God. (ESV)
#+END_QUOTE

* TODO [#A] Watch - I should really keep watching such videos and taking notes on them, etc.

e:/volumes/home/shane/var/smulliga/source/git/semiosis/notes-on-sermons/notes-on-sermons.org

* 
[[https://www.youtube.com/watch?v=eMgX_rQgIvo][youtube.com: The Effort Needed to Fight Sin: Living Out Identity in Christ, Part 2]]

* This
[[https://www.youtube.com/watch?v=D_kwDdDZH3Q][youtube.com: The War in the Christian Soul: Galatians 5:16-18, Part 4]]

Because the spirit desires against the flesh,
if we walk by the spirit then we will not
fulfill the desires of the flesh - whatever things we want [by the flesh] we do not do.

That's quite cool.

God help me.

* 
[[https://www.youtube.com/watch?v=s423TgHeSmo][youtube.com: How a Will Embraces God]]
[[https://www.youtube.com/watch?v=WwrA7Usa6uc][youtube.com: Does Providence Eliminate My Will?]]

* Yeah, I do actually think this is true
[[https://www.youtube.com/watch?v=A30MDo1HLts][youtube.com: God Will Take Care Of Your Material Needs If You Seek The Kingdom First]]

* 
[[https://www.youtube.com/watch?v=vIyh05QP0mo][youtube.com: Resurrection Power for Our Pain]]

* 
[[https://www.youtube.com/watch?v=6EQM3I1s2yw&list=RDyN1RZBxXX_I&index=5][youtube.com: Worthy of It All | feat. Michael Bethany | Gateway Worship]]

* TODO Today I should learn some chemistry or something
- https://github.com/topics/chemistry-education

- https://github.com/itsmeuttu/chemistry-notes

* 
[[https://www.youtube.com/watch?v=ZrZlMtHf6Yw][youtube.com: CATAN Strategy Guide: How to win at Catan / Tips and Tricks / Advanced strategy / Settlers of Catan]]

* TODO Fast and pray
I should fast and pray to stop:
- spiritual attacking
- orgasming

* I am a child of God
- [[https://www.youtube.com/watch?v=lKw6uqtGFfo][youtube.com: Who You Say I Am - Hillsong Worship]]

* Trusting Jesus
- [[https://www.youtube.com/watch?v=v2ZzULDM-XM][youtube.com: Trust In Jesus]]

I just feel like trusting Jesus involves obeying Him:
- Yes, we trust that Jesus will pull through for us.
- Yes, we can't do anything without Him.
  - But with Him we *can* do things.
    - Obedience!

* Chemistry calculators
https://www.omnicalculator.com/chemistry

* Chemistry NCEA
** NCEA 1
[[https://www.youtube.com/watch?v=nV1Vl71-XIo&list=PLLOEf4zj7b-rXi4ya1SIv73zoJckqiBEC&index=1][youtube.com: NCEA Level 1 Science 2014 Acids and Bases Paper 90944]]

* This is interesting
[[https://www.youtube.com/watch?v=aRNsQrdQ2ro][youtube.com: Why Sin Gets Worse After We Find Christ {w/ Fr. Seraphim Aldea}]]

* 
[[https://www.youtube.com/watch?v=ZsSUZfhQWeI][youtube.com: New Testament Greek Lesson 1: The Alphabet]]

* This quote is cool
- [[https://youtube.com/watch?v=ZiivY7VtsAU&t=344][youtube.com: TFP: He Is No Longer Optimus Prime : Are You Certain I Am Worthy? @time: 5 min 44 sec]]
- [[https://youtube.com/watch?v=ZiivY7VtsAU&t=367][youtube.com: TFP: He Is No Longer Optimus Prime : Are You Certain I Am Worthy? @time: 6 min 7 sec]]
- [[https://youtube.com/watch?v=ZiivY7VtsAU&t=378][youtube.com: TFP: He Is No Longer Optimus Prime : Are You Certain I Am Worthy? @time: 6 min 18 sec]]

* 
[[https://www.youtube.com/watch?v=j-AAjuN2YOg][youtube.com: The Faith That Counts Produces Fruit: Galatians 5:1-6, Part 8]]

* Jesus: The Word of God
- [[https://www.youtube.com/watch?v=buZm8hUguEc][Jesus: The Word of God - YouTube]]

* This prophet lady's explanation of why she shares visions (being obedient to Jesus) sounds legit
- [[https://www.youtube.com/watch?v=WjGk2WyHvGI][The Blue Door Dream 5-20-24 to 5-22-24 {Shared 5-24-24} - YouTube]]

* This was awesome
[[https://www.youtube.com/watch?v=kPHOZSZW584][God's Own Name - YouTube]]

* 
[[https://www.youtube.com/watch?v=tYPYAcscivw][Don't Turn Back to Slavery: Galatians 5:1-6, Part 1 - YouTube]]

* Distinctive differences
[[https://www.youtube.com/watch?v=J3VMbr3ZcPo][Kingdom of the Cults {Jehovah's Witnesses, Mormons, 7th Day Adventism & Christian Science} - YouTube]]

* 
Biblically, however, a heavenly destiny awaits *all* who believe in Christ:

#+BEGIN_QUOTE
  *John 14:1-3* - Let not your hearts be troubled. Believe in God; believe also in me. In my Father's house are many rooms. If it were not so, would I have told you that I go to prepare a place for you? And if I go and prepare a place for you, I will come again and will take you to myself, that where I am you may be also. (ESV)
#+END_QUOTE

* 
[[https://www.youtube.com/watch?v=PgmAkM39Zt4][We Studied Water in the Bible {Here's What We Found} - YouTube]]

* 
[[https://www.youtube.com/watch?v=qeBosrQMkcw][Young man BOLDLY preaches Gospel in WALMART on Easter Day - YouTube]]

* I want to be raptured
[[https://www.youtube.com/watch?v=8Z5TAs0htLA][RAPTURE ALERT!,    We are going home. God is speaking..I will bring my own to me - YouTube]]

I don't want to be here.
It feels like living inside the matrix or something, but I know about it.

* 
#+BEGIN_QUOTE
  *Luke 8:21* - But he answered them, My mother and my brothers are those who hear the word of God and do it. (ESV)
#+END_QUOTE

* This was good - AMEN!!
** A prayer for answers
[[https://www.youtube.com/watch?v=vCGb1qE5Lrg][I Heard, "Answers" ?? - YouTube]]

* Hmm. I agree with Derek Prince here
[[https://www.youtube.com/watch?v=QbqdtXY3eoY][Spiritual Conflict - Results of Adam's Fall Part 6 A {6:1} - YouTube]]

* This
[[https://www.youtube.com/watch?v=bFpB9F5JeLQ][Don't Go Back To Your Own Vomit ? - YouTube]]

* This
[[https://www.youtube.com/watch?v=S9WkPD5KXCk][Prayer To Break Demonic Crown | Prayer For The Battle  Of The Mind - YouTube]]

* 
[[https://www.youtube.com/watch?v=csA7iS8XrJ0][Tell my people, "I Love Them. I Know Them. And I'm Coming For Them." #jesuschrist #propheticword - YouTube]]

* 
[[https://www.youtube.com/watch?v=TnFyA9qKp7k][Shifting from Legal to Experiential Salvation: Galatians 3:1-5, Part 1 - YouTube]]

* This!
[[https://www.youtube.com/watch?v=hcxCRyu3nyg][PRAISE | Elevation Worship | Drum Cover - YouTube]]

* LORD God, please help me to know
[[https://www.youtube.com/watch?v=pBoYW1qj6E4][Kingdom Spouse: ?Just a moment?! #prophetic #Godstimingisperfect #ready #joy #restoration - YouTube]]

Is satan trying to destroy everything with Melee? I think it's likely.
But it's far more important that Melee comes out OK.
Me getting married to her is not important at all.
What really matters is people's (including her) salvation and coming to know the Lord Jesus Christ.

Please deliver me God.
Please win this battle.
God, You are the one in control of everything.
Lord Jesus, You are seated in power.
I believe if I honour You then You'll help me here.
I need to know what's from You.

** LORD God, please just take me to heaven
[[https://www.youtube.com/watch?v=JJ5mFN-T1O8][Rapture Dream Jesus is definitely coming soon - YouTube]]

* 
[[https://www.youtube.com/watch?v=P-JPOVsak7s][What Does It Mean to Cry, 'Abba, Father'? - YouTube]]

* Wikipedia TUI
https://github.com/Builditluc/wiki-tui

* TODO Set up some wikipedia study tools in emacs
This is what is available for wikipedia in emacs:
- wiki-summary
- helm-wikipedia
- wikinfo

mx:helm-wikipedia-suggest

** This is quite good

| kb            | f                  |              |
|---------------+--------------------+--------------|
| =M-l M-/ M-w= | =wikipedia-search= | =global-map= |

** eww browser is actually quite nice for opening from mx:helm-wikipedia-suggest but it is too slow

j:helm-wikipedia-suggest

* Must build house on the rock
Must not build house on the sand.

#+BEGIN_QUOTE
  *Matthew 7:24-27* - Everyone then who hears these words of mine and does them will be like a wise man who built his house on the rock. And the rain fell, and the floods came, and the winds blew and beat on that house, but it did not fall, because it had been founded on the rock. And everyone who hears these words of mine and does not do them will be like a foolish man who built his house on the sand. And the rain fell, and the floods came, and the winds blew and beat against that house, and it fell, and great was the fall of it. (ESV)
#+END_QUOTE

* Listen
- [[https://www.youtube.com/watch?v=ElNB3tldviA][Mere Christianity by C.S. Lewis - YouTube]]
- [[https://www.youtube.com/watch?v=-vOGxGce3OM][The High Cost of Following Christ | Billy Graham Classic Sermon - YouTube]]
- [[https://www.youtube.com/watch?v=0fTh18JZG9k][Discovering the Gospel in Ruth a?? Tim Keller - YouTube]]

#+BEGIN_QUOTE
  *Luke 14:27-33* - Whoever does not bear his own cross and come after me cannot be my disciple. For which of you, desiring to build a tower, does not first sit down and count the cost, whether he has enough to complete it? Otherwise, when he has laid a foundation and is not able to finish, all who see it begin to mock him, saying, This man began to build and was not able to finish. Or what king, going out to encounter another king in war, will not sit down first and deliberate whether he is able with ten thousand to meet him who comes against him with twenty thousand? And if not, while the other is yet a great way off, he sends a delegation and asks for terms of peace. So therefore, any one of you who does not renounce all that he has cannot be my disciple. (ESV)
#+END_QUOTE

* Stick to wholesome stuff
[[https://www.youtube.com/watch?v=qZ4ZuZthw7Q][Cute Baby Goats - A Cutest And Funny  Goats Baby Videos Compilation|| NEW HD - YouTube]]

* 
[[https://www.youtube.com/watch?v=Tl1tZIUdG_w][The Lord Confirm Me That Time Is Very Short - YouTube]]

Dear Heavenly Father, Jehovah God,
Please, God. Please, Jesus, rapture me.
I don't want to be here on earth, LORD God.
Also, please prepare me to be ready.
In Jesus Christ's name I ask,
AMEN!!

* OK, see this
[[https://www.youtube.com/watch?v=DZPkTZK3k48][FALSE RELIGIONS: WORD FROM ABBA FATHER {10th Apr} - YouTube]]

It's time that these be brought low.

False religions:
- sending God's people straight to hell
- false institutions
- false gods
- hide behind a facade of piety
- they make you feel good because you're grouped with like-minded people
- they give you a false peace to remain in your false doctrine and false-religion
- takes away accountability and responsibility for seeking God's face
- the institutions feed the flesh
- like marrying a harlot
- gives spiritual pride
  - this is very serious

By real humility we need to come to the reality of who we are and come to repentance.

Religion makes a barrier to getting to God.

God's children lay it all bare and come to God's feet in true humility, asking to be saved, and asking for their hearts to be exposed so God can do the work in them.

* This
[[https://www.youtube.com/watch?v=yENsZ-Fsj4I][The Spirit in Us Cries 'Abba Father': Galatians 4:1-7, Part 5 - YouTube]]

* Walk in the Spirit
[[https://www.youtube.com/watch?v=5H-l4Byj8EU][God wants you to EMBRACE his spirita??i,? - YouTube]]

* Cool! Very cute
[[https://www.youtube.com/watch?v=2qtGpQnT-Hw][YOU'LL BE IN MY HEART FROM DISNEY'S TARZAN - LIVE COVER BY 4-YEAR-OLD CLAIRE RYANN AND DAD - YouTube]]

[[https://www.youtube.com/watch?v=kd7KC3PaEaA][Can't Help Falling In Love on a Kalimba - YouTube]]

* Hm.
[[https://www.youtube.com/watch?v=k5g7Y8UUjnw]["Stay close to me." Received from: the One True Living God, The Lord Jesus Christ on April 2nd 2024 - YouTube]]

This is a good message.

* Watch!
[[https://www.youtube.com/watch?v=kdXXd2cNunw][His Only Son - YouTube]]

* Cat sanctuary
[[https://www.youtube.com/watch?v=VkNP1TdsllU&t=767][Forever home. Maybe. - YouTube]]

* 
[[https://www.youtube.com/watch?v=bX77k_0vqpg][The Single Most Important Word For 2024 #dailyprophetic - YouTube]]

Glorify Jesus.
Thank You, LORD Jesus.
We acknowledge what You have done for us on the cross.
Lord, Jesus.
We praise You Jesus, and give You the glory!
If it wasn't for Christ rising from the grave, our faith would be in vain.
Only Jesus was able to rise from the grave.
We serve the One and only living God.
Jesus Christ can be known.
We must acknowledge what Jesus has done for us and give Him honour and praise.
It's because of Jesus that we get to do what we do today.
We want to bless Your name Lord Jesus. We thank You and glorify Your name, for everything You have done.
Thank You for being near to us Lord God.
AMEN!!

#+BEGIN_QUOTE
  *Matthew 28:1-6* - Now after the Sabbath, toward the dawn of the first day of the week, Mary Magdalene and the other Mary went to see the tomb. And behold, there was a great earthquake, for an angel of the Lord descended from heaven and came and rolled back the stone and sat on it. His appearance was like lightning, and his clothing white as snow. And for fear of him the guards trembled and became like dead men. But the angel said to the women, Do not be afraid, for I know that you seek Jesus who was crucified. He is not here, for he has risen, as he said. Come, see the place where he lay. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *I Corinthians 15:14* - And if Christ has not been raised, then our preaching is in vain and your faith is in vain. (ESV)
#+END_QUOTE

* This
[[https://www.youtube.com/watch?v=p1AClpOsm5g][Resurrection Sunday | Benny Hinn - YouTube]]

* This
[[https://www.youtube.com/watch?v=qZ4O-1VYv4c][The Probability Monad - YouTube]]

* Cool movie!
[[https://www.youtube.com/watch?v=_07ktacEGo8][LEAVE NO TRACE | Official Trailer - YouTube]]

* 
[[https://www.youtube.com/watch?v=BCQX4R1mFAk][The a??Cheap Gracea?? Gospel From HELLa?| - YouTube]]

* 
[[https://www.youtube.com/watch?v=tZ5YeHbpeJU][Timeline of the Life of Jesus - YouTube]]

* Listen
[[https://www.youtube.com/watch?v=zm4gbLvya4c][C.S. Lewis' Thoughts On Easter - YouTube]]

* I think I might need to really move on from the past
[[https://www.youtube.com/watch?v=Q8lTH6bIZS8][Your New Environment Requires A New Identity - YouTube]]

* This is cool
[[https://www.youtube.com/watch?v=5USsyIXQ9gw][boy reveals Jesus in every book of the bible - YouTube]]

* Watch
[[https://www.youtube.com/watch?v=A469zsqgNPQ][Is Your Hope in Jesus, or in Your Expectations? | Becky Haag - YouTube]]
[[https://www.youtube.com/watch?v=mG4_jqX2RLc][There is a Battle Raging Between the Old You & the New You - YouTube]]

* Elliot's life
[[https://www.youtube.com/watch?v=JQskyJGbfq8][How To Please God - Hebrews 11:6 - YouTube]]

* Awesome!
[[https://www.youtube.com/watch?v=f2oxGYpuLkw][Praise {feat. Brandon Lake, Chris Brown & Chandler Moore} | Elevation Worship - YouTube]]

* This is awesome
[[https://www.youtube.com/watch?v=M9EbSw8O6uc][Free from Judgment, Fighting Sin, Full Assurance - YouTube]]

* This
[[https://www.youtube.com/watch?v=cAsTwftk0OE][The Way Into the Holiest  - Four Great Blessings of the New Covenant Part 7 B {7:2} - YouTube]]

* Watch
[[https://www.youtube.com/watch?v=GAsDbZhVMtE][Only One Life: Christa??s Invincible Gospel and Global Mission - YouTube]]

** Classic TV!
https://archive.org/details/classic_tv

https://archive.org/details/television

*** For example:
https://archive.org/details/startrektheanimatedseries

https://archive.org/details/FireballXL51x04

* Yup
[[https://www.youtube.com/watch?v=K6WPp_pHFYw][Orthodox Sermon - The Last Judgment: Act Now - YouTube]]

* 
[[https://www.youtube.com/watch?v=g-rD6-C4fXw][How to Repent correctly after you Sin. Mar Mari Emmanuel - YouTube]]

* 
[[https://www.youtube.com/watch?v=Wpjpemdu9R4][God Spoke To Me "YOU MUST KNOW ME OR YOU WON'T SURVIVE WHAT'S COMING" {URGENT PROPHETIC WORD!} - YouTube]]

* John Piper
- [[https://www.youtube.com/watch?v=a2xzr8ZJpn8][How Do Gentiles Become Sons of Abraham? Galatians 3:6a??9, Part 3 - YouTube]]

* Watch
- [[https://www.youtube.com/watch?v=DgcN1Qc2kJg][The Hour Has Come a?? Part One - YouTube]]
- [[https://www.youtube.com/watch?v=gh6hTjz9A80&t=1s][The Hour Has Come a?? Part Two - YouTube]]

* I agree with this guy
[[https://www.youtube.com/watch?v=aEsQdxAoR3Y][Christianity is God saves us & we respond to obey, not the other way - YouTube]]

- I should make lots of links for people which I agree with.
- That is a really good idea, actually.

It's definitely worth curating this.

* Bishop Emmanuel Mar Mari
- [[https://www.youtube.com/watch?v=ZL3fjExbWhY][Questions And Answers  | Bishop Emmanuel Mar Mari - YouTube]]
- [[https://www.youtube.com/watch?v=fSZio_uz9T8][Listen to God, not this World. Mar Mari Emmanuel - YouTube]]

* 
[[https://www.youtube.com/watch?v=yRaDEQmUr3g][All the aspects of justification {salvation} God's Word guarantees to ALL believers! - YouTube]]

* 
[[https://www.youtube.com/watch?v=1tN4DUSkjjk][Paul the Apostal: Journey to Jerusalem. Acts 21 - YouTube]]

* 
#+BEGIN_QUOTE
  *Genesis 8:22* - While the earth remains, seedtime and harvest, cold and heat, summer and winter, day and night, shall not cease. (ESV)
#+END_QUOTE

* Watch this
[[https://www.youtube.com/watch?v=TdPYMlaYGrg][Why Is THIS The First Thing Noah Does Off The Ark? | Bible Study in Genesis 8:14-20 - YouTube]]

* Spiritual warfare scriptures
#+BEGIN_SRC bash -n :i bash :f "bible-show-verses -m NASB -pp" :async :results verbatim code :lang text
  Psalms 91:11
  ‾‾‾‾‾‾‾‾‾‾‾‾
  For He will give His angels charge concerning
  you, To guard you in all your ways.

  James 4:7
  ‾‾‾‾‾‾‾‾‾
  Submit therefore to God. Resist the devil and he
  will flee from you.

  I John 4:4
  ‾‾‾‾‾‾‾‾‾‾
  You are from God, little children, and have
  overcome them; because greater is He who is in
  you than he who is in the world.

  II Corinthians 10:3
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  For though we walk in the flesh, we do not war
  according to the flesh,

  II Corinthians 10:4
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  for the weapons of our warfare are not of the
  flesh, but divinely powerful for the destruction
  of fortresses.

  II Corinthians 10:5
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  We are destroying speculations and every lofty
  thing raised up against the knowledge of God, and
  we are taking every thought captive to the
  obedience of Christ,

  I Peter 5:8
  ‾‾‾‾‾‾‾‾‾‾‾
  Be of sober spirit, be on the alert. Your
  adversary, the devil, prowls around like a
  roaring lion, seeking someone to devour.

  I Peter 5:9
  ‾‾‾‾‾‾‾‾‾‾‾
  But resist him, firm in your faith, knowing that
  the same experiences of suffering are being
  accomplished by your brethren who are in the
  world.

  Isaiah 54:17
  ‾‾‾‾‾‾‾‾‾‾‾‾
  “No weapon that is formed against you will
  prosper; And every tongue that accuses you in
  judgment you will condemn. This is the heritage
  of the servants of the LORD, And their
  vindication is from Me,” declares the LORD.

  Ephesians 6:11
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  Put on the full armor of God, so that you will be
  able to stand firm against the schemes of the
  devil.

  Ephesians 6:12
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  For our struggle is not against flesh and blood,
  but against the rulers, against the powers,
  against the world forces of this darkness,
  against the spiritual forces of wickedness in the
  heavenly places.

  Ephesians 6:13
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  Therefore, take up the full armor of God, so that
  you will be able to resist in the evil day, and
  having done everything, to stand firm.

  Ephesians 6:14
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  Stand firm therefore, having girded your loins
  with truth, and having put on the breastplate of
  righteousness,

  Ephesians 6:15
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  and having shod your feet with the preparation of
  the gospel of peace;

  Ephesians 6:16
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  in addition to all, taking up the shield of faith
  with which you will be able to extinguish all the
  flaming arrows of the evil one.

  Ephesians 6:17
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  And take the helmet of salvation, and the sword
  of the Spirit, which is the word of God.

  I Corinthians 15:57
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  but thanks be to God, who gives us the victory
  through our Lord Jesus Christ.

  Zechariah 4:6
  ‾‾‾‾‾‾‾‾‾‾‾‾‾
  Then he said to me, “This is the word of the
  LORD to Zerubbabel saying, ‘Not by might nor by
  power, but by My Spirit,’ says the LORD of
  hosts.

  II Thessalonians 3:3
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  But the Lord is faithful, and He will strengthen
  and protect you from the evil one.

  Luke 10:19
  ‾‾‾‾‾‾‾‾‾‾
  Behold, I have given you authority to tread on
  serpents and scorpions, and over all the power of
  the enemy, and nothing will injure you.

  John 10:10
  ‾‾‾‾‾‾‾‾‾‾
  The thief comes only to steal and kill and
  destroy; I came that they may have life, and have
  it abundantly.

  Matthew 18:18
  ‾‾‾‾‾‾‾‾‾‾‾‾‾
  Truly I say to you, whatever you bind on earth
  shall have been bound in heaven; and whatever you
  loose on earth shall have been loosed in heaven.

  Matthew 18:19
  ‾‾‾‾‾‾‾‾‾‾‾‾‾
  “Again I say to you, that if two of you agree
  on earth about anything that they may ask, it
  shall be done for them by My Father who is in
  heaven.

  Deuteronomy 28:7
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  “The LORD shall cause your enemies who rise up
  against you to be defeated before you; they will
  come out against you one way and will flee before
  you seven ways.

  John 16:33
  ‾‾‾‾‾‾‾‾‾‾
  These things I have spoken to you, so that in Me
  you may have peace. In the world you have
  tribulation, but take courage; I have overcome
  the world.”

  I Corinthians 10:13
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  No temptation has overtaken you but such as is
  common to man; and God is faithful, who will not
  allow you to be tempted beyond what you are able,
  but with the temptation will provide the way of
  escape also, so that you will be able to endure
  it.

  John 8:32
  ‾‾‾‾‾‾‾‾‾
  and you will know the truth, and the truth will
  make you free.”

  Romans 12:21
  ‾‾‾‾‾‾‾‾‾‾‾‾
  Do not be overcome by evil, but overcome evil
  with good.

  Revelation of John 12:11
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  And they overcame him because of the blood of the
  Lamb and because of the word of their testimony,
  and they did not love their life even when faced
  with death.

  I Timothy 6:12
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  Fight the good fight of faith; take hold of the
  eternal life to which you were called, and you
  made the good confession in the presence of many
  witnesses.

  Matthew 16:18
  ‾‾‾‾‾‾‾‾‾‾‾‾‾
  I also say to you that you are Peter, and upon
  this rock I will build My church; and the gates
  of Hades will not overpower it.

  I John 3:8
  ‾‾‾‾‾‾‾‾‾‾
  the one who practices sin is of the devil; for
  the devil has sinned from the beginning. The Son
  of God appeared for this purpose, to destroy the
  works of the devil.

  Isaiah 40:31
  ‾‾‾‾‾‾‾‾‾‾‾‾
  Yet those who wait for the LORD Will gain new
  strength; They will mount up with wings like
  eagles, They will run and not get tired, They
  will walk and not become weary.

  Joshua 23:10
  ‾‾‾‾‾‾‾‾‾‾‾‾
  One of your men puts to flight a thousand, for
  the LORD your God is He who fights for you, just
  as He promised you.

  Deuteronomy 3:22
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  Do not fear them, for the LORD your God is the
  one fighting for you.’

  Romans 8:31
  ‾‾‾‾‾‾‾‾‾‾‾
  What then shall we say to these things? If God is
  for us, who is against us?

  Psalms 44:5
  ‾‾‾‾‾‾‾‾‾‾‾
  Through You we will push back our adversaries;
  Through Your name we will trample down those who
  rise up against us.

  Joshua 1:9
  ‾‾‾‾‾‾‾‾‾‾
  Have I not commanded you? Be strong and
  courageous! Do not tremble or be dismayed, for
  the LORD your God is with you wherever you go.”

  Psalms 18:39
  ‾‾‾‾‾‾‾‾‾‾‾‾
  For You have girded me with strength for battle;
  You have subdued under me those who rose up
  against me.

  Psalms 91:1
  ‾‾‾‾‾‾‾‾‾‾‾
  He who dwells in the shelter of the Most High
  Will abide in the shadow of the Almighty.

  Psalms 91:2
  ‾‾‾‾‾‾‾‾‾‾‾
  I will say to the LORD, “My refuge and my
  fortress, My God, in whom I trust!”

  Psalms 91:3
  ‾‾‾‾‾‾‾‾‾‾‾
  For it is He who delivers you from the snare of
  the trapper And from the deadly pestilence.

  Psalms 91:4
  ‾‾‾‾‾‾‾‾‾‾‾
  He will cover you with His pinions, And under His
  wings you may seek refuge; His faithfulness is a
  shield and bulwark.

  II Chronicles 20:15
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  and he said, “Listen, all Judah and the
  inhabitants of Jerusalem and King Jehoshaphat:
  thus says the LORD to you, ‘Do not fear or be
  dismayed because of this great multitude, for the
  battle is not yours but God’s.

  Matthew 16:23
  ‾‾‾‾‾‾‾‾‾‾‾‾‾
  But He turned and said to Peter, “Get behind
  Me, Satan! You are a stumbling block to Me; for
  you are not setting your mind on God’s
  interests, but man’s.”

  Leviticus 26:8
  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
  five of you will chase a hundred, and a hundred
  of you will chase ten thousand, and your enemies
  will fall before you by the sword.

  Psalms 23:1
  ‾‾‾‾‾‾‾‾‾‾‾
  The LORD is my shepherd, I shall not want.

  Psalms 23:2
  ‾‾‾‾‾‾‾‾‾‾‾
  He makes me lie down in green pastures; He leads
  me beside quiet waters.

  Psalms 23:3
  ‾‾‾‾‾‾‾‾‾‾‾
  He restores my soul; He guides me in the paths of
  righteousness For His name’s sake.

  Psalms 23:4
  ‾‾‾‾‾‾‾‾‾‾‾
  Even though I walk through the valley of the
  shadow of death, I fear no evil, for You are with
  me; Your rod and Your staff, they comfort me.

  Psalms 23:5
  ‾‾‾‾‾‾‾‾‾‾‾
  You prepare a table before me in the presence of
  my enemies; You have anointed my head with oil;
  My cup overflows.

  Psalms 23:6
  ‾‾‾‾‾‾‾‾‾‾‾
  Surely goodness and lovingkindness will follow me
  all the days of my life, And I will dwell in the
  house of the LORD forever.

  Nahum 1:7
  ‾‾‾‾‾‾‾‾‾
  The LORD is good, A stronghold in the day of
  trouble, And He knows those who take refuge in
  Him.

  Psalms 140:1
  ‾‾‾‾‾‾‾‾‾‾‾‾
  Rescue me, O LORD, from evil men; Preserve me
  from violent men

  (NASB)
#+END_SRC

#+RESULTS:
#+begin_src text
Psalms 91:11
‾‾‾‾‾‾‾‾‾‾‾‾
For He will give His angels charge concerning
you, To guard you in all your ways.

James 4:7
‾‾‾‾‾‾‾‾‾
Submit therefore to God. Resist the devil and he
will flee from you.

I John 4:4
‾‾‾‾‾‾‾‾‾‾
You are from God, little children, and have
overcome them; because greater is He who is in
you than he who is in the world.

II Corinthians 10:3
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
For though we walk in the flesh, we do not war
according to the flesh,

II Corinthians 10:4
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
for the weapons of our warfare are not of the
flesh, but divinely powerful for the destruction
of fortresses.

II Corinthians 10:5
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
We are destroying speculations and every lofty
thing raised up against the knowledge of God, and
we are taking every thought captive to the
obedience of Christ,

I Peter 5:8
‾‾‾‾‾‾‾‾‾‾‾
Be of sober spirit, be on the alert. Your
adversary, the devil, prowls around like a
roaring lion, seeking someone to devour.

I Peter 5:9
‾‾‾‾‾‾‾‾‾‾‾
But resist him, firm in your faith, knowing that
the same experiences of suffering are being
accomplished by your brethren who are in the
world.

Isaiah 54:17
‾‾‾‾‾‾‾‾‾‾‾‾
“No weapon that is formed against you will
prosper; And every tongue that accuses you in
judgment you will condemn. This is the heritage
of the servants of the LORD, And their
vindication is from Me,” declares the LORD.

Ephesians 6:11
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Put on the full armor of God, so that you will be
able to stand firm against the schemes of the
devil.

Ephesians 6:12
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
For our struggle is not against flesh and blood,
but against the rulers, against the powers,
against the world forces of this darkness,
against the spiritual forces of wickedness in the
heavenly places.

Ephesians 6:13
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Therefore, take up the full armor of God, so that
you will be able to resist in the evil day, and
having done everything, to stand firm.

Ephesians 6:14
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Stand firm therefore, having girded your loins
with truth, and having put on the breastplate of
righteousness,

Ephesians 6:15
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
and having shod your feet with the preparation of
the gospel of peace;

Ephesians 6:16
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
in addition to all, taking up the shield of faith
with which you will be able to extinguish all the
flaming arrows of the evil one.

Ephesians 6:17
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
And take the helmet of salvation, and the sword
of the Spirit, which is the word of God.

I Corinthians 15:57
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
but thanks be to God, who gives us the victory
through our Lord Jesus Christ.

Zechariah 4:6
‾‾‾‾‾‾‾‾‾‾‾‾‾
Then he said to me, “This is the word of the
LORD to Zerubbabel saying, ‘Not by might nor by
power, but by My Spirit,’ says the LORD of
hosts.

II Thessalonians 3:3
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
But the Lord is faithful, and He will strengthen
and protect you from the evil one.

Luke 10:19
‾‾‾‾‾‾‾‾‾‾
Behold, I have given you authority to tread on
serpents and scorpions, and over all the power of
the enemy, and nothing will injure you.

John 10:10
‾‾‾‾‾‾‾‾‾‾
The thief comes only to steal and kill and
destroy; I came that they may have life, and have
it abundantly.

Matthew 18:18
‾‾‾‾‾‾‾‾‾‾‾‾‾
Truly I say to you, whatever you bind on earth
shall have been bound in heaven; and whatever you
loose on earth shall have been loosed in heaven.

Matthew 18:19
‾‾‾‾‾‾‾‾‾‾‾‾‾
“Again I say to you, that if two of you agree
on earth about anything that they may ask, it
shall be done for them by My Father who is in
heaven.

Deuteronomy 28:7
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
“The LORD shall cause your enemies who rise up
against you to be defeated before you; they will
come out against you one way and will flee before
you seven ways.

John 16:33
‾‾‾‾‾‾‾‾‾‾
These things I have spoken to you, so that in Me
you may have peace. In the world you have
tribulation, but take courage; I have overcome
the world.”

I Corinthians 10:13
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
No temptation has overtaken you but such as is
common to man; and God is faithful, who will not
allow you to be tempted beyond what you are able,
but with the temptation will provide the way of
escape also, so that you will be able to endure
it.

John 8:32
‾‾‾‾‾‾‾‾‾
and you will know the truth, and the truth will
make you free.”

Romans 12:21
‾‾‾‾‾‾‾‾‾‾‾‾
Do not be overcome by evil, but overcome evil
with good.

Revelation of John 12:11
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
And they overcame him because of the blood of the
Lamb and because of the word of their testimony,
and they did not love their life even when faced
with death.

I Timothy 6:12
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Fight the good fight of faith; take hold of the
eternal life to which you were called, and you
made the good confession in the presence of many
witnesses.

Matthew 16:18
‾‾‾‾‾‾‾‾‾‾‾‾‾
I also say to you that you are Peter, and upon
this rock I will build My church; and the gates
of Hades will not overpower it.

I John 3:8
‾‾‾‾‾‾‾‾‾‾
the one who practices sin is of the devil; for
the devil has sinned from the beginning. The Son
of God appeared for this purpose, to destroy the
works of the devil.

Isaiah 40:31
‾‾‾‾‾‾‾‾‾‾‾‾
Yet those who wait for the LORD Will gain new
strength; They will mount up with wings like
eagles, They will run and not get tired, They
will walk and not become weary.

Joshua 23:10
‾‾‾‾‾‾‾‾‾‾‾‾
One of your men puts to flight a thousand, for
the LORD your God is He who fights for you, just
as He promised you.

Deuteronomy 3:22
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Do not fear them, for the LORD your God is the
one fighting for you.’

Romans 8:31
‾‾‾‾‾‾‾‾‾‾‾
What then shall we say to these things? If God is
for us, who is against us?

Psalms 44:5
‾‾‾‾‾‾‾‾‾‾‾
Through You we will push back our adversaries;
Through Your name we will trample down those who
rise up against us.

Joshua 1:9
‾‾‾‾‾‾‾‾‾‾
Have I not commanded you? Be strong and
courageous! Do not tremble or be dismayed, for
the LORD your God is with you wherever you go.”

Psalms 18:39
‾‾‾‾‾‾‾‾‾‾‾‾
For You have girded me with strength for battle;
You have subdued under me those who rose up
against me.

Psalms 91:1
‾‾‾‾‾‾‾‾‾‾‾
He who dwells in the shelter of the Most High
Will abide in the shadow of the Almighty.

Psalms 91:2
‾‾‾‾‾‾‾‾‾‾‾
I will say to the LORD, “My refuge and my
fortress, My God, in whom I trust!”

Psalms 91:3
‾‾‾‾‾‾‾‾‾‾‾
For it is He who delivers you from the snare of
the trapper And from the deadly pestilence.

Psalms 91:4
‾‾‾‾‾‾‾‾‾‾‾
He will cover you with His pinions, And under His
wings you may seek refuge; His faithfulness is a
shield and bulwark.

II Chronicles 20:15
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
and he said, “Listen, all Judah and the
inhabitants of Jerusalem and King Jehoshaphat:
thus says the LORD to you, ‘Do not fear or be
dismayed because of this great multitude, for the
battle is not yours but God’s.

Matthew 16:23
‾‾‾‾‾‾‾‾‾‾‾‾‾
But He turned and said to Peter, “Get behind
Me, Satan! You are a stumbling block to Me; for
you are not setting your mind on God’s
interests, but man’s.”

Leviticus 26:8
‾‾‾‾‾‾‾‾‾‾‾‾‾‾
five of you will chase a hundred, and a hundred
of you will chase ten thousand, and your enemies
will fall before you by the sword.

Psalms 23:1
‾‾‾‾‾‾‾‾‾‾‾
The LORD is my shepherd, I shall not want.

Psalms 23:2
‾‾‾‾‾‾‾‾‾‾‾
He makes me lie down in green pastures; He leads
me beside quiet waters.

Psalms 23:3
‾‾‾‾‾‾‾‾‾‾‾
He restores my soul; He guides me in the paths of
righteousness For His name’s sake.

Psalms 23:4
‾‾‾‾‾‾‾‾‾‾‾
Even though I walk through the valley of the
shadow of death, I fear no evil, for You are with
me; Your rod and Your staff, they comfort me.

Psalms 23:5
‾‾‾‾‾‾‾‾‾‾‾
You prepare a table before me in the presence of
my enemies; You have anointed my head with oil;
My cup overflows.

Psalms 23:6
‾‾‾‾‾‾‾‾‾‾‾
Surely goodness and lovingkindness will follow me
all the days of my life, And I will dwell in the
house of the LORD forever.

Nahum 1:7
‾‾‾‾‾‾‾‾‾
The LORD is good, A stronghold in the day of
trouble, And He knows those who take refuge in
Him.

Psalms 140:1
‾‾‾‾‾‾‾‾‾‾‾‾
Rescue me, O LORD, from evil men; Preserve me
from violent men

(NASB)
#+end_src

* This is good
[[https://www.youtube.com/watch?v=1Y0hkjK7ZYs][Spirit Of A Servant And Service Prt 2 | Bishop Mar Mari Emmanuel - YouTube]]

I should also recite the Lord's prayer every day, along with the Nicene creed.

* 
https://www.youtube.com/watch?v=puYG5sItvn8&ab_channel=ChristianSermonsandAudioBooks

* 
*1 Corinthians 13:13* - So now faith, hope, and love abide, these three; but the greatest of these is love.  (ESV)

* Abiding in the Truth
#+BEGIN_QUOTE
  *John 6:56* - He who eats My flesh and drinks My blood abides in Me, and I in him.
#+END_QUOTE

Get intimate with Jesus - really intimate.

#+BEGIN_QUOTE
  *John 8:31* - So Jesus said to the Jews who had believed in him, If you abide in my word, you are truly my disciples,
#+END_QUOTE

#+BEGIN_QUOTE
  *John 14:17* - that is the Spirit of truth, whom the world cannot receive, because it does not see Him or know Him, but you know Him because He abides with you and will be in you.
#+END_QUOTE

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  John 15:4-10
#+END_SRC

#+RESULTS:
#+begin_src text
John 15:4-10
‾‾‾‾‾‾‾‾‾‾‾‾
Abide in me, and I in you.

As the branch cannot bear fruit by itself,
unless it abides in the vine, neither can you,
unless you abide in me.

I am the vine; you are the branches.

Whoever abides in me and I in him, he it is
that bears much fruit, for apart from me you
can do nothing.

If anyone does not abide in me he is thrown
away like a branch and withers; and the
branches are gathered, thrown into the fire,
and burned.

If you abide in me, and my words abide in you,
ask whatever you wish, and it will be done for
you.

By this my Father is glorified, that you bear
much fruit and so prove to be my disciples.

As the Father has loved me, so have I loved
you.

Abide in my love.

If you keep my commandments, you will abide in
my love, just as I have kept my Father's
commandments and abide in his love.

(ESV)
#+end_src

#+BEGIN_QUOTE
  *John 15:16* - You did not choose me, but I chose you and appointed you that you should go and bear fruit and that your fruit should abide, so that whatever you ask the Father in my name, he may give it to you.
#+END_QUOTE

* John Piper
[[https://www.youtube.com/watch?v=qYqlwid_Tqk][What Does It Mean to Serve God? - YouTube]]

[[mx:bible-search reward ESV phrase]]

* 
[[https://www.youtube.com/watch?v=B0RCg2ZTFeM][How To Uncomplicate The Gospel.i? 1/4  - YouTube]]

Keep my eyes on Jesus and that will uncomplicate things.

Deny the flesh because I understand where that will lead me.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  John 8:44
#+END_SRC

#+RESULTS:
#+begin_src text
John 8:44
‾‾‾‾‾‾‾‾‾
Ye are of your father the devil, and the lusts
of your father ye will do.

He was a murderer from the beginning, and
abode not in the truth, because there is no
truth in him.

When he speaketh a lie, he speaketh of his
own: for he is a liar, and the father of it.

(RLT)
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code :lang text
  1 Corinthians 14:33
#+END_SRC

#+RESULTS:
#+begin_src text
1 Corinthians 14:33
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
For God is not the author of confusion, but of
peace, as in all Assemblies of the saints.

(RLT)
#+end_src
