I've just put together todays and yesterdays notes which I have made.

Acts 13:48 - And when the Gentiles heard this, they began rejoicing and glorifying the word of the Lord, and as many as were appointed to eternal life believed. (ESV)

I'm thinking about belief, faith, works, law and receiving the Holy Spirit today!
I have some more ideas into a monologue which I have been writing yesterday and today.It's a bit of a mishmash of verses along with my thoughts.
Please let me know what you think if you have the time.I'm trying to get clearer on this.

My thoughts and bible references regarding:

** The law

Matthew 19:4-9 - He answered, Have you not read that he who created them from the beginning made them male and female, and said, Therefore a man shall leave his father and his mother and hold fast to his wife, and they shall become one flesh? So they are no longer two but one flesh. What therefore God has joined together, let not man separate. They said to him, Why then did Moses command one to give a certificate of divorce and to send her away? He said to them, Because of your hardness of heart Moses allowed you to divorce your wives, but from the beginning it was not so. And I say to you: whoever divorces his wife, except for sexual immorality, and marries another, commits adultery. (ESV)

Matthew 5:14-20 - You are the light of the world. A city set on a hill cannot be hidden. Nor do people light a lamp and put it under a basket, but on a stand, and it gives light to all in the house. In the same way, let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven. Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfill them. For truly, I say to you, until heaven and earth pass away, not an iota, not a dot, will pass from the Law until all is accomplished. Therefore whoever relaxes one of the least of these commandments and teaches others to do the same will be called least in the kingdom of heaven, but whoever does them and teaches them will be called great in the kingdom of heaven. For I tell you, unless your righteousness exceeds that of the scribes and Pharisees, you will never enter the kingdom of heaven. (ESV)

Leviticus 18:22 - You shall not lie with a male as with a woman; it is an abomination. (ESV)

Romans 7:22 - For I delight in the law of God, in my inner being, (ESV)

*** The law may be pursued by faith. Justification through faith

         Faith 
       /       \
  Those who     Gentiles
pursue the law
  by faith

Romans 9:31-32 - but that Israel who pursued a law that would lead to righteousness did not succeed in reaching that law. Why? Because they did not pursue it by faith, but as if it were based on works. They have stumbled over the stumbling stone, (ESV)

The most important thing though is faith because it applies to both the adherent of the law and also the Gentile who has faith.

Romans 4:16 - That is why it depends on faith, in order that the promise may rest on grace and be guaranteed to all his offspring—not only to the adherent of the law but also to the one who shares the faith of Abraham, who is the father of us all, (ESV)

Matthew 21:32 - For John came to you in the way of righteousness, and you did not believe him, but the tax collectors and the prostitutes believed him. And even when you saw it, you did not afterward change your minds and believe him. (ESV)

To follow the law by faith, I think, is to not lie, commit adultery, idolize, etc. in truth and reality, keeping yourself accountable to God.

** Anyone who believes in Him receives forgiveness of sins
Acts 10:43: Of Him all the prophets bear witness that through His name everyone who believes in Him receives forgiveness of sins.”

** Her faith saved her / is forgiven because she loved much

Luke 7:47 - Therefore I tell you, her sins, which are many, are forgiven—for she loved much.  But he who is forgiven little, loves little.  (ESV)

** Gay marriage
I currently believe this means that grace exists for gay people who have faith in Jesus but those who annul and teach others to break the law will be called least in the kingdom. i.e. those who keep God's commandments and AND the righteousness of faith / the testimony of Jesus will be called great in the kingdom.
This is my current understanding. Is this correct?

Also, the Kingdom stretches from heaven to earth, so gay 'marriage' may happen on earth but such a thing could never exist in heaven.
But neither does marriage between man and woman even exist in heaven.

Matthew 6:10 - Your kingdom come, your will be done, on earth as it is in heaven.

The question is, which I do not have the answer for, is there any place for it in God's kingdom anywhere down?

God's original design is male and female union and also the law reflects the spiritual reality.

I saw a dark spot around my rib when I was born-again.
I think this indicates I am male, and there's a kingdom partner out there for me!

https://web.archive.org/web/20220402091720/https://mullikine.github.io/posts/astral-projection/

** I do not endorse gay marriage
I personally do not endorse gay marriage. When I have in the past, I repent of
that. In the manner in which I judge, I know I will be judged. So I believe
that because I do not / no longer endorse gay marriage for others, I do not
endorse it for myself, and I'll be held to that standard.

I know I am called to exercise personal righteousness/holiness as
the light of the world. I believe that God's grace extends to all who put their
faith in Jesus and have Jesus' righteousness imputed onto them, the
righteousness of faith in Jesus Christ God's Son who has paid through his blood
the price for our sin.

I also currently believe that one's response to
forgiveness must be like the woman Jesus mentions in Luke 7:47 - with a PROPROTIONAL love for Jesus.

I believe one must know that God's law is right and when presented with God's law, they recognise that the law is right
and recognise their transgression.

** Belief comes before or at the time of receiving the Holy Spirit
I believe that the Holy Spirit goes to those who obey God. I believe belief in Jesus comes first.

Acts 2:38 - And Peter said to them, Repent and be baptized every one of you in the name of Jesus Christ for the forgiveness of your sins, and you will receive the gift of the Holy Spirit. (ESV)

Acts 5:32 - And we are witnesses to these things, and so is the Holy Spirit, whom God has given to those who obey him. (ESV)

Belief in Jesus comes first but receiving the Holy Spirit and baptism may happen in any order after that.

I think this is generally the order of things.

** God is sovereign to reveal Himself.

Romans 10:20 - Then Isaiah is so bold as to say, I have been found by those who did not seek me; I have shown myself to those who did not ask for me. (ESV)

I also believe 1 Cor 12:3.

** Outside of the Holy Spirit, noone can say Jesus is Lord

1 Corinthians 12:3 - Therefore I want you to understand that no one speaking in the Spirit of God ever says Jesus is accursed! and no one can say Jesus is Lord except in the Holy Spirit. (ESV)


** Works accompany the true believers
Mark 16:16-17 - Whoever believes and is baptized will be saved, but whoever does not believe will be condemned. And these signs will accompany those who believe: in my name they will cast out demons; they will speak in new tongues; (ESV)

** Those that reject the gospel are not the same as those who haven't heard the gospel
Mark 6:11: And if any place will not receive you and they will not listen to you, when you leave, shake off the dust that is on your feet as a testimony against them.
John 13:20: Truly, truly, I say to you, whoever receives the one I send receives me, and whoever receives me receives the one who sent me.
Matthew 10:40: “He who receives you receives Me, and he who receives Me receives Him who sent Me.
Mark 9:37: “Whoever receives one child like this in My name receives Me; and whoever receives Me does not receive Me, but Him who sent Me.”

Actually, I prefer this interpretation:

People who hear the gospel and reject it / reject Jesus / choose to not believe are condemned.

People who hear the gospel and reject it / choose to not believe are condemned.

** I believe that repentance is important in faith and faithfulness to God (lots of people say these days that following the law in faith is self-righteousness; they believe good is evil)
Matthew 21:32 - For John came to you in the way of righteousness, and you did not believe him, but the tax collectors and the prostitutes believed him. And even when you saw it, you did not afterward change your minds and believe him. (ESV)

Acts 2:38 - And Peter said to them, Repent and be baptized every one of you in the name of Jesus Christ for the forgiveness of your sins, and you will receive the gift of the Holy Spirit. (ESV)

Basic repentance is 'metanoia' (a change of mind) - it's part of belief.
But this is what repentance looks like.

Joel 2:12-13 - Yet even now, declares the LORD, return to me with all your heart, with fasting, with weeping, and with mourning; and rend your hearts and not your garments. Return to the LORD, your God, for he is gracious and merciful, slow to anger, and abounding in steadfast love; and he relents over disaster. (ESV)

And repentance has the fruit of in your heart truly deciding to tell the truth, not commit adultery, etc. - being accountable to God, knowing that He sees.

Matthew 3:8 - Bear fruit in keeping with repentance.  (ESV)

This is following the law by faith, I think; Truly loving God and one's neighbour.

** Celebrating/endorsing sin / error is not right

If a newly born-again Christian is spending all their time with sinners though and endorsing continually instead of being discipled, then they can
have their mind conformed to the sinners instead of being strengthened in the truth. This is why I think it's not especially great to, immediately after getting born-again,
be overly exposed to unbelievers and sinners.

Jesus ate with sinners but Jesus was the special guest. Think of Nicodemus inviting Jesus over.

** Faith has substance to it, and an amount to it, usually drawn out over time
Hebrews 11:1 - Now faith is the substance of things hoped for, the evidence of things not seen. (KJV)

For me, I was acting in faith ever since I was born-again, resulting in a huge chain of events and confirmations!

** Faith believes God and hopes in invisible things, and is convicted of them

But at the end of the day, justification by faith in Jesus justifies the ungodly sinner - but it is faith that justifies and not faithlessness. It's the type of belief that recognises one's sin, and results in love for Jesus, and it's obedient and submissive to God - it's repentant.

Hebrews 11:6 - And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him. (ESV)

Where we are unfaithful, though, God is faithful. God wants us to choose Him. He wants us to repent.

** Who chooses who? I believe Jesus chose me and I also chose Jesus
John 15:16 - You did not choose me, but I chose you and appointed you that you should go and bear fruit and that your fruit should abide, so that whatever you ask the Father in my name, he may give it to you. (ESV)

** Structure of the Kingdom

The law still exists. A thought I have : "Perhaps structure of God's kingdom might be determined by the law and Jesus' words."

Revelation of John 20:4 - Then I saw thrones, and seated on them were those to whom the authority to judge was committed. Also I saw the souls of those who had been beheaded for the testimony of Jesus and for the word of God, and who had not worshiped the beast or its image and had not received its mark on their foreheads or their hands. They came to life and reigned with Christ for a thousand years.

** There is no sexual immorality in heaven, no violence, no sinners.

Revelation 21:22-27 - And I saw no temple in the city, for its temple is the Lord God the Almighty and the Lamb. And the city has no need of sun or moon to shine on it, for the glory of God gives it light, and its lamp is the Lamb. By its light will the nations walk, and the kings of the earth will bring their glory into it, and its gates will never be shut by day—and there will be no night there. They will bring into it the glory and the honor of the nations. But nothing unclean will ever enter it, nor anyone who does what is detestable or false, but only those who are written in the Lamb's book of life. (ESV)

Isaiah 11:6 - The wolf shall dwell with the lamb, and the leopard shall lie down with the young goat, and the calf and the lion and the fattened calf together; and a little child shall lead them. (ESV)

Matthew 22:30: For in the resurrection they neither marry nor are given in marriage, but are like angels in heaven.

** Adhering to the law like a Pharisee - pursuing the law by works
But adhering to the law like a Pharisee is like strapping yourself to a razor blade, but that doesn't mean the law is wrong.

Romans 3:20: For by works of the law no human being will be justified in his sight, since through the law comes knowledge of sin.

** Follow the law mercifully and without self-righteousness, accountable to God, like a servant
So as to not become a hypocrite or condemn the innocent.
Accountable to God - a relationship with God.
Without self-righteousness.

Acts 23:3: Then Paul said to him, God is going to strike you, you whitewashed wall! Are you sitting to judge me according to the law, and yet contrary to the law you order me to be struck?

Matthew 12:3-8 - He said to them, Have you not read what David did when he was hungry, and those who were with him: how he entered the house of God and ate the bread of the Presence, which it was not lawful for him to eat nor for those who were with him, but only for the priests?  Or have you not read in the Law how on the Sabbath the priests in the temple profane the Sabbath and are guiltless?  I tell you, something greater than the temple is here.  And if you had known what this means, I desire mercy, and not sacrifice, you would not have condemned the guiltless.  For the Son of Man is lord of the Sabbath.

** All the law is still used
The law is good and it still exists, and God still uses the law. All of it. We are supposed to stand for truth and live righteously as the light of the world.

That being said, we all fall short of the glory of God.
Jesus Christ is the end of the law to all who believe, but grace isn't an excuse to sin.

** Justification by faith - Jews + Gentiles, and in-between
Justification by faith is the correct teaching but the promise is for the gentiles AND the adherent of the law but they all must have faith, and pursuing the law as if by works is the problem, but pursuing the law by faith is ok.

I believe in-between is OK, so long as it is by faith.

Romans 7:22 - For I delight in the law of God, in my inner being, (ESV)

Romans 9:30-32 - What shall we say, then? That Gentiles who did not pursue righteousness have attained it, that is, a righteousness that is by faith; but that Israel who pursued a law that would lead to righteousness did not succeed in reaching that law. Why? Because they did not pursue it by faith, but as if it were based on works. They have stumbled over the stumbling stone, (ESV)

Romans 4:15-16 - For the law brings wrath, but where there is no law there is no transgression. That is why it depends on faith, in order that the promise may rest on grace and be guaranteed to all his offspring—not only to the adherent of the law but also to the one who shares the faith of Abraham, who is the father of us all, (ESV)

Matthew 5:17-25 - Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfill them. For truly, I say to you, until heaven and earth pass away, not an iota, not a dot, will pass from the Law until all is accomplished. Therefore whoever relaxes one of the least of these commandments and teaches others to do the same will be called least in the kingdom of heaven, but whoever does them and teaches them will be called great in the kingdom of heaven. For I tell you, unless your righteousness exceeds that of the scribes and Pharisees, you will never enter the kingdom of heaven. You have heard that it was said to those of old, You shall not murder; and whoever murders will be liable to judgment. But I say to you that everyone who is angry with his brother will be liable to judgment; whoever insults his brother will be liable to the council; and whoever says, You fool! will be liable to the hell of fire. So if you are offering your gift at the altar and there remember that your brother has something against you, leave your gift there before the altar and go. First be reconciled to your brother, and then come and offer your gift. Come to terms quickly with your accuser while you are going with him to court, lest your accuser hand you over to the judge, and the judge to the guard, and you be put in prison. (ESV)

The settling with the adversary literally happened to me - Marriage proposal after getting born-again.

** Theoretically belief usually comes before or at the time receiving the Holy Spirit
But for me I believe before I was born-again and before I was baptised in the Holy Spirit.

Acts 19:1-7 - And it happened that while Apollos was at Corinth, Paul passed through the inland country and came to Ephesus.  There he found some disciples.  And he said to them, Did you receive the Holy Spirit when you believed?  And they said, No, we have not even heard that there is a Holy Spirit.  And he said, Into what then were you baptized?  They said, Into John's baptism.  And Paul said, John baptized with the baptism of repentance, telling the people to believe in the one who was to come after him, that is, Jesus. On hearing this, they were baptized in the name of the Lord Jesus. And when Paul had laid his hands on them, the Holy Spirit came on them, and they began speaking in tongues and prophesying. There were about twelve men in all.  (ESV)

* Receive through the hearing of the word and faith
Galatians 3:2 - Let me ask you only this: Did you receive the Spirit by works of the law or by hearing with faith? (ESV)

Not just by hearing but by hearing with faith.

** The promised Spirit is received through faith
Galatians 3:14 - so that in Christ Jesus the blessing of Abraham might come to the Gentiles, so that we might receive the promised Spirit through faith.  (ESV)

*** Over easter
**** 2 years before being born again - prayer - proving belief came before being born-again
https://web.archive.org/web/20220402091720/https://mullikine.github.io/posts/prayer/

Not that I have to prove it though!

**** Being born-again
https://web.archive.org/web/20220402091720/https://mullikine.github.io/posts/astral-projection/

**** Meeting with the Holy Spirit
https://web.archive.org/web/20220402091720/https://mullikine.github.io/posts/astral-projection-pt-2/

**** I wrote about following the law by faith, also law written on my heart.

https://web.archive.org/web/20220703044748/https://mullikine.github.io/posts/the-tapestry-of-truth/

**** Baptised in the Holy Spirit
https://web.archive.org/web/20220806085237/https://mullikine.github.io/posts/astral-projection-pt-3/

** Later in the year
https://web.archive.org/web/20220402091720/https://mullikine.github.io/posts/dream-the-way-the-truth-the-life/

** Justification by faith for the both adherents of the law and the gentiles
Justification by faith is the correct teaching but the promise is for the gentiles AND the adherent of the law but they all must have faith, and pursuing the law as if by works is the problem, but pursuing the law by faith is ok.

Romans 7:22 - For I delight in the law of God, in my inner being, (ESV)

Romans 9:30-32 - What shall we say, then? That Gentiles who did not pursue righteousness have attained it, that is, a righteousness that is by faith; but that Israel who pursued a law that would lead to righteousness did not succeed in reaching that law. Why? Because they did not pursue it by faith, but as if it were based on works. They have stumbled over the stumbling stone, (ESV)

Romans 4:15-16 - For the law brings wrath, but where there is no law there is no transgression. That is why it depends on faith, in order that the promise may rest on grace and be guaranteed to all his offspring—not only to the adherent of the law but also to the one who shares the faith of Abraham, who is the father of us all, (ESV)

** Paul used the law to judge back, but without hypocrisy
Matthew 23:27: Woe to you, scribes and Pharisees, hypocrites! For you are like whitewashed tombs, which outwardly appear beautiful, but within are full of dead people's bones and all uncleanness.

Acts 23:3: Then Paul said to him, God is going to strike you, you whitewashed wall! Are you sitting to judge me according to the law, and yet contrary to the law you order me to be struck?

** Justified by faith alone
Predestined, called, justified, glorified - sounds like election.

Romans 8:30 - And those whom he predestined he also called, and those whom he called he also justified, and those whom he justified he also glorified. (ESV)

*** Then, glorification

Proverbs 19:11 - Good sense makes one slow to anger, and it is his glory to overlook an offense. (ESV)

Ephesians 4:32 - Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you. (ESV)

Jesus Christ is Lord! :)
