* Installation
These setup instructions are designed for Debian 10 or Ubuntu 20.04.

** Dependencies
- emacs 28

** Tutorial
https://semiosis.github.io/posts/pen-tutorial/

** =AIx= API key (for GPT-J-6b)

** =OpenAI= API key (for GPT-3)
You will need your own OpenAI API key.

The shell command =openai-complete.sh= requires =OPENAI_API_KEY= to be
provided to at as an environment variable.

It's up to you to provide this to the script.

[[./scripts/openai-complete.sh]]

Alternatively, the script will look for it here =$HOME/.pen/openai_api_key=.

** Setup script for a Debian 10 docker image
[[./scripts/setup.sh]]

Adjust this script for your own installation.

** Emacs =.emacs= / =init.el=
The following emacs init file contains the
base requirements to run =pen.el= in a vanilla
emacs.

[[./src/init.el]]

*** Configure =pen.el=
See the above =init.el= file for an example of
where to load your config (after all
dependencies are loaded).

**** Example emacs config
[[./src/pen-example-config.el]]

** Running =pen.el=
This is tested to run on a Debian 10 docker image.

[[./scripts/run.sh]]

*** Add scripts to PATH
=pen.el= requires some external scripts to be in the path.

- https://github.com/semiosis/pen.el/tree/master/scripts