* Setup
** Set the =openai= API key using emacs' =custom=
#+BEGIN_SRC text -n :async :results verbatim code
  M-x customize-group
#+END_SRC

*** =pen-openai-key=
Setting this variable will save your key to the file specified by
=pen-openai-key-location=.

If =pen-openai-key-location= is not set then it wil<l ask you to name that path first.

The =pen-openai-key= is stored in plain text, but that's better than storing
directly within an emacs variable as we can't guarantee you keep your emacs
repository private.

Make it a secure location.

*** =pen-openai-key-location=
This variable is automatically set when setting =pen-openai-key=, but if you
choose to set =pen-openai-key-location= instead, =pen-openai-key= will be
loaded from this file.

*** Alternatively, create a wrapper script around =openai= and export the key
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  #!/bin/bash

  export OPENAI_API_KEY="$(cat $HOME/.myrc.yaml | yq -r '.openai_api_key')"
  
  /usr/local/bin/openai "$@"
#+END_SRC

* Usage
** Enable =pen-mode= globally (on all buffers)
- http://github.com/semiosis/pen.el/blob/master/pen-example-config.el

[[./pen-example-config.el]]

* Default Key Bindings
| key binding    | description    |
|----------------+----------------|
| <kbd>SPC</kbd> | =pen-run-prompt-function= |

** Free prompts to use
https://github.com/semiosis/prompts/