cd /root/notes;  "colvs" "#" "<==" "pen-pa"
cd /root/.emacs.d/host/pen.el/scripts;  "colvs" "#" "<==" "pen-pa"
cd /root/.emacs.d/host/pen.el/scripts;  "colvs" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
