cd /root/.pen/documents/notes/ws/lists/peniel;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
cd /root/notes;  "colvs" "-nls" "#" "<==" "pen-pa"
