cd /root/.emacs.d/host/pen.el/src;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_0c08367d5a_psalms-40-3.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_0c08367d5a_psalms-40-3.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_b37651e44b_matthew-5-15-16.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_661e0b7432_acts-12-14.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_b37651e44b_matthew-5-15-16.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_c11ea2f8d6_james-1-2.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_f2c855a6a1_luke-11-28.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_74b0ac7bf4_galatians-5-1.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_661e0b7432_acts-12-14.txt" "#" "<==" "pen-xa"
