cd /root/.emacs.d/host/pen.el/scripts;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.emacs.d/host/pen.el/scripts/container;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.emacs.d/host/pen.el/scripts;  "colvs" "#" "<==" "pa"
cd /root/.emacs.d/host/pen.el/src;  "colvs" "#" "<==" "pa"
cd /root/.emacs.d/host/pen.el/src;  "colvs" "#" "<==" "pa"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/notes;  "colvs" "-nls" "-num" "/root/.pen/tmp/tf_temp_b82afecb55_1-john.txt" "#" "<==" "pen-xa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
cd /root/.pen/documents/notes;  "colvs" "#" "<==" "pa"
