(require 'vterm)

;; (setq vterm-keymap-exceptions
;;       '("C-c" "C-x" "C-u" "C-g" "C-h" "C-l" "M-x" "M-o" "C-v" "M-v" "C-y" "M-y"))

(defun vterm-send-meta-colon ()
  "Send `M-:' to the libvterm."
  (interactive)
  (vterm-send-key ":" nil t))

(defun vterm-send-meta-semicolon ()
  "Send `M-:' to the libvterm."
  (interactive)
  (vterm-send-key ";" nil t))

(setq vterm-keymap-exceptions
      '("C-c"))

;; (define-key key-translation-map (kbd "C-M-]") (kbd "<help>"))
;; (global-set-key (kbd "C-M-o") (kbd "DEL"))
;; (define-key helm-map (kbd "C-h") nil)
;; (define-key helm-map (kbd "C-h c") nil)
;; (define-key helm-map (kbd "C-h C-d") nil)
;; (define-key helm-map (kbd "C-h") (kbd "DEL"))
;; (define-key isearch-mode-map (kbd "C-h") #'isearch-delete-char)
;; (define-key global-map (kbd "C-h") (kbd "DEL"))
;; (global-set-key (kbd "C-c h") help-map)

(defset vterm-mode-map
        (let ((map (make-sparse-keymap)))
          (vterm--exclude-keys map vterm-keymap-exceptions)
          (define-key map (kbd "C-]")                 #'vterm--self-insert)
          (define-key map (kbd "M-<")                 #'vterm--self-insert)
          (define-key map (kbd "M->")                 #'vterm--self-insert)
          (define-key map [tab]                       #'vterm-send-tab)
          (define-key map (kbd "TAB")                 #'vterm-send-tab)
          (define-key map [backtab]                   #'vterm--self-insert)
          (define-key map [backspace]                 #'vterm-send-backspace)
          (define-key map (kbd "DEL")                 #'vterm-send-backspace)
          (define-key map (kbd "C-h")                 #'vterm-send-C-h)
          (define-key map (kbd "C-a")                 #'vterm-send-C-a)
          (define-key map (kbd "C-M-u")               #'vterm-send-delete)
          (define-key map (kbd "C-M-o")               #'vterm-send-backspace)
          (define-key map [delete]                    #'vterm-send-delete)
          (define-key map [M-backspace]               #'vterm-send-meta-backspace)
          (define-key map (kbd "M-DEL")               #'vterm-send-meta-backspace)
          (define-key map [C-backspace]               #'vterm-send-meta-backspace)
          (define-key map [return]                    #'vterm-send-return)
          (define-key map (kbd "RET")                 #'vterm-send-return)
          (define-key map (kbd "M-o")                    #'vterm-send-M-o)
          (define-key map (kbd "M-k")                    #'vterm-send-M-k)
          (define-key map [C-left]                    #'vterm-send-M-b)
          (define-key map [M-left]                    #'vterm-send-M-b)
          (define-key map [C-right]                   #'vterm-send-M-f)
          (define-key map [M-right]                   #'vterm-send-M-f)
          (define-key map [C-up]                      #'vterm-send-up)
          (define-key map [C-down]                    #'vterm-send-down)
          (define-key map [left]                      #'vterm-send-left)
          (define-key map [right]                     #'vterm-send-right)
          (define-key map [up]                        #'vterm-send-up)
          (define-key map [down]                      #'vterm-send-down)
          (define-key map [prior]                     #'vterm-send-prior)
          (define-key map [S-prior]                   #'scroll-down-command)
          (define-key map [next]                      #'vterm-send-next)
          (define-key map [S-next]                    #'scroll-up-command)
          (define-key map [home]                      #'vterm--self-insert)
          (define-key map [end]                       #'vterm--self-insert)
          (define-key map [C-home]                    #'vterm--self-insert)
          (define-key map [C-end]                     #'vterm--self-insert)
          (define-key map [escape]                    #'vterm--self-insert)
          (define-key map [remap yank]                #'vterm-yank)
          (define-key map [remap xterm-paste]         #'vterm-xterm-paste)
          (define-key map [remap yank-pop]            #'vterm-yank-pop)
          (define-key map [remap mouse-yank-primary]  #'vterm-yank-primary)
          (define-key map (kbd "C-SPC")               #'vterm--self-insert)
          (define-key map (kbd "S-SPC")               #'vterm-send-space)
          (define-key map (kbd "C-_")                 #'vterm--self-insert)
          (define-key map (kbd "C-/")                 #'vterm-undo)
          (define-key map (kbd "M-.")                 #'vterm-send-meta-dot)
          (define-key map (kbd "M-,")                 #'vterm-send-meta-comma)
          (define-key map (kbd "M-:")                 #'vterm-send-meta-colon)
          (define-key map (kbd "M-;")                 #'vterm-send-meta-semicolon)
          (define-key map (kbd "C-c C-y")             #'vterm--self-insert)
          (define-key map (kbd "C-c C-c")             #'vterm-send-C-c)
          (define-key map (kbd "C-c C-l")             #'vterm-clear-scrollback)
          (define-key map (kbd "C-l")                 #'vterm-clear)
          (define-key map (kbd "C-\\")                #'vterm-send-ctrl-slash)
          (define-key map (kbd "C-c C-g")             #'vterm-send-C-g)
          (define-key map (kbd "C-c C-u")             #'vterm-send-C-u)
          (define-key map [remap self-insert-command] #'vterm--self-insert)
          (define-key map (kbd "C-c C-r")             #'vterm-reset-cursor-point)
          (define-key map (kbd "C-c C-n")             #'vterm-next-prompt)
          (define-key map (kbd "C-c C-p")             #'vterm-previous-prompt)
          (define-key map (kbd "C-c M-x")             #'pen-counsel-M-x)
          (define-key map (kbd "C-c C-t")             #'vterm-copy-mode)
          map))

(defset vterm-copy-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-t")        #'vterm-copy-mode)
    (define-key map [return]               #'vterm-copy-mode-done)
    (define-key map (kbd "RET")            #'vterm-copy-mode-done)
    (define-key map (kbd "C-c C-r")        #'vterm-reset-cursor-point)
    (define-key map (kbd "C-a")            #'vterm-beginning-of-line)
    (define-key map (kbd "C-e")            #'vterm-end-of-line)    
    (define-key map (kbd "C-c C-n")        #'vterm-next-prompt)
    (define-key map (kbd "C-c C-p")        #'vterm-previous-prompt)
    map))

;; Objectives:
;; Get all bindings working:
;; - meta bindings

(define-key vterm-mode-map (kbd "C-c C-t") 'vterm-copy-mode)

(provide 'pen-vterm)
