cd /root/.pen/documents/notes;  "nasb" "-s" "might" "be" "fulfilled" "in" "us," "who" "do" "not" "walk" "#" "<==" "zsh"
cd /;  "nasb" "Romans" "8:4" "#" "<==" "sh"
cd /;  "nasb" "Matt" "19:5" "#" "<==" "sh"
cd /;  "nasb" "Isaiah" "43:18-19" "#" "<==" "sh"
cd /;  "nasb" "Heb." "9:14-17" "#" "<==" "sh"
cd /;  "nasb" "Mark" "7:28-29" "#" "<==" "sh"
cd /;  "nasb" "John" "14:2-3" "#" "<==" "sh"
cd /;  "nasb" "Genesis" "15:12" "#" "<==" "sh"
cd /;  "nasb" "Genesis" "15:17" "#" "<==" "sh"
cd /;  "nasb" "2nd" "Timothy" "1:9" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "2nd" "Timothy" "1:9" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "2nd" "Timothy" "1" "#" "<==" "zsh"
cd /;  "nasb" "2" "Timothy" "1:9" "#" "<==" "sh"
cd /;  "nasb" "Hebrews" "10:14" "#" "<==" "sh"
cd /;  "nasb" "Philippians" "3:12-13" "#" "<==" "sh"
