cd /root/notes;  "nasb" "Genesis" "13" "#" "<==" "tmux: server"
cd /root/.pen/documents/notes;  "nasb" "-s" "gospel" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "-s" "Peniel" "#" "<==" "zsh"
cd /;  "nasb" "Genesis" "32:30" "#" "<==" "sh"
cd /;  "nasb" "Proverbs" "19:17" "#" "<==" "sh"
cd /root/notes;  "nasb" "I" "Cor" "2" "#" "<==" "tmux: server"
cd /;  "nasb" "Romans" "13" "#" "<==" "sh"
cd /;  "nasb" "I" "Cor" "#" "<==" "sh"
cd /;  "nasb" "Romans" "13:8" "#" "<==" "sh"
cd /;  "nasb" "I" "Tim" "#" "<==" "sh"
cd /;  "nasb" "Romans" "13:8" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "Romans" "#" "<==" "Romans"
cd /root/.pen/documents/notes;  "nasb" "Hebrews" "9:27" "#" "<==" "Hebrews"
cd /root/.pen/documents/notes;  "nasb" "II" "Peter" "2:4" "#" "<==" "II"
cd /root/.pen/documents/notes;  "nasb" "Second" "Peter" "2:4" "#" "<==" "Second"
cd /root/.pen/documents/notes;  "nasb" "Second" "Peter" "2:4" "#" "<==" "Second"
cd /;  "nasb" "Deuteronomy" "15:7" "#" "<==" "sh"
cd /;  "nasb" "Proverbs" "19:17" "#" "<==" "sh"
cd /;  "nasb" "Job" "31:16" "#" "<==" "sh"
cd /;  "nasb" "Isaiah" "58:7" "#" "<==" "sh"
cd /;  "nasb" "Isaiah" "58:10" "#" "<==" "sh"
cd /;  "nasb" "Matthew" "5:42" "#" "<==" "sh"
cd /;  "nasb" "Matthew" "6:1" "#" "<==" "sh"
cd /;  "nasb" "Matthew" "25:35" "#" "<==" "sh"
cd /;  "nasb" "Luke" "10:35" "#" "<==" "sh"
cd /;  "nasb" "Luke" "11:41" "#" "<==" "sh"
cd /;  "nasb" "Luke" "12:33" "#" "<==" "sh"
cd /;  "nasb" "Luke" "14:13" "#" "<==" "sh"
cd /;  "nasb" "Luke" "18:22" "#" "<==" "sh"
cd /;  "nasb" "Luke" "19:8" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "Acts" "3:2" "#" "<==" "sh"
cd /;  "nasb" "Acts" "3:10" "#" "<==" "sh"
cd /;  "nasb" "Acts" "9:36" "#" "<==" "sh"
cd /;  "nasb" "Acts" "10:2" "#" "<==" "sh"
cd /;  "nasb" "Acts" "10:31" "#" "<==" "sh"
cd /;  "nasb" "Acts" "24:17" "#" "<==" "sh"
cd /;  "nasb" "1" "Corinthians" "16:1" "#" "<==" "sh"
cd /;  "nasb" "2" "Corinthians" "8:11" "#" "<==" "sh"
cd /;  "nasb" "2" "Corinthians" "9:6" "#" "<==" "sh"
cd /;  "nasb" "2" "Corinthians" "9:6" "#" "<==" "sh"
cd /;  "nasb" "Galatians" "2:10" "#" "<==" "sh"
cd /;  "nasb" "Ephesians" "4:28" "#" "<==" "sh"
cd /;  "nasb" "1" "Timothy" "6:18" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /root/.pen/documents/notes;  "nasb" "John" "3:17" "#" "<==" "1"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /;  "nasb" "John" "3:17" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "1" "John" "3" "#" "<==" "1"
cd /;  "nasb" "1" "John" "3:17" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "Hebrews" "4" "#" "<==" "Hebrews"
cd /root/notes;  "nasb" "Psalm" "95" "#" "<==" "tmux: server"
cd /;  "nasb" "Romans" "14:23" "#" "<==" "sh"
cd /;  "nasb" "James" "1:12" "#" "<==" "sh"
cd /;  "nasb" "Psalms" "112" "#" "<==" "sh"
cd /;  "nasb" "Matthew" "6:3" "#" "<==" "sh"
cd /;  "nasb" "John" "4:8" "#" "<==" "sh"
cd /;  "nasb" "II" "Corinthians" "9:7" "#" "<==" "sh"
cd /;  "nasb" "Matthew" "6:2" "#" "<==" "sh"
cd /;  "nasb" "Matthew" "6:2-3" "#" "<==" "sh"
cd /;  "nasb" "Luke" "11:38-42" "#" "<==" "sh"
cd /;  "nasb" "Luke" "11:39-42" "#" "<==" "sh"
cd /;  "nasb" "I" "Corinthians" "8" "#" "<==" "sh"
cd /root/notes;  "nasb" "I" "Corinthians" "8" "#" "<==" "tmux: server"
cd /;  "nasb" "II" "Corinthians" "8" "#" "<==" "sh"
cd /root/notes;  "nasb" "II" "Corinthians" "8" "#" "<==" "tmux: server"
cd /;  "nasb" "II" "Corinthians" "8" "#" "<==" "sh"
cd /;  "nasb" "James" "2:15-16" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "Matthew" "15:21" "#" "<==" "Matthew"
cd /root/.pen/documents/notes;  "nasb" "Matthew" "15:21" "#" "<==" "Matthew"
cd /root/notes;  "nasb" "Matthew" "15:21" "#" "<==" "Matthew"
