cd /root/notes;  "nasb" "II" "Thessalonians" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "II" "Thessalonians" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "II" "Thessalonians" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "II" "Thessalonians" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "II" "Thessalonians" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "II" "Thessalonians" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "II" "Thessalonians" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "Gen" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "Gen" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "Ps" "31" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "Ps" "5" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "Ps" "5" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "Ps" "5" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "Genesis" "5:1" "#" "<==" "Genesis"
cd /root/.pen/documents/notes;  "nasb" "Romans" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "John" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "Psalms" "30:1" "#" "<==" "Psalms"
cd /root/.pen/documents/notes;  "nasb" "-s" "Ezra" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "-s" "Ezra" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "-s" "Ezra" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "-s" "Ezra" "10:1" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "Ezra" "10:1" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "-s" "Ezra" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "I" "Chronicles" "4:17" "#" "<==" "zsh"
cd /root/notes;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "-s" "living" "God" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "Isaiah" "37:15" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "Isaiah" "37:14-16" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "Isaiah" "37:15-16" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "Isaiah" "37:15" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "Isaiah" "37:14-16" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "Isaiah" "37:15" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "Isaiah" "37:14" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/src;  "nasb" "Isaiah" "37:14" "#" "<==" "Isaiah"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "-s" "preach the gospel" "#" "<==" "zsh"
cd /;  "nasb" "-s" "preach the gospel" "#" "<==" "sh"
cd /root/notes;  "nasb" "-s" "preach the gospel" "#" "<==" "tmux: server"
cd /;  "nasb" "-s" "preach the gospel" "#" "<==" "sh"
cd /root/notes;  "nasb" "-s" "preach the gospel" "#" "<==" "tmux: server"
cd //;  "nasb" "Romans" "5:5" "#" "<==" "Romans"
cd //;  "nasb" "Romans" "5:5" "#" "<==" "Romans"
cd //;  "nasb" "Romans" "5" "#" "<==" "Romans"
cd //;  "nasb" "Romans" "#" "<==" "Romans"
cd /;  "nasb" "Ezekiel" "40:36" "#" "<==" "Ezekiel"
cd /;  "nasb" "Ezekiel" "40:36" "#" "<==" "Ezekiel"
cd /root/.pen/documents/notes;  "nasb" "Song" "of" "Solomon" "5:15" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "Song" "of" "Solomon" "5:15" "#" "<==" "zsh"
cd /;  "nasb" "Psalm" "22" "#" "<==" "zsh"
cd /;  "nasb" "Genesis" "2:22" "#" "<==" "zsh"
cd //;  "nasb" "Revelation" "#" "<==" "zsh"
cd /root/notes;  "nasb" "Isaiah" "37:14" "#" "<==" "Isaiah"
cd /root/notes;  "nasb" "Isaiah" "#" "<==" "Isaiah"
cd /root/notes;  "nasb" "Psalms" "41" "#" "<==" "tmux: server"
cd /root/.pen/glossaries;  "nasb" "-s" "Holy" "One" "of" "Israel" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "-s" "tree" "of" "life" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "-s" "Holy" "One" "of" "Israel" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nasb" "-s" "tree" "of" "life" "#" "<==" "zsh"
cd /root/notes;  "nasb" "Ecclesiastes" "5" "#" "<==" "tmux: server"
cd /;  "nasb" "Matthew" "5:21-24" "#" "<==" "sh"
cd /;  "nasb" "Matthew" "5:21-24" "#" "<==" "sh"
cd /root/notes;  "nasb" "Acts" "5" "#" "<==" "tmux: server"
cd /;  "nasb" "Acts" "5" "#" "<==" "sh"
cd /root/.pen/documents/notes;  "nasb" "Micah" "#" "<==" "bible-book"
cd /root/.pen/documents/notes;  "nasb" "Revelation of John" "#" "<==" "bible-book"
cd /root/.pen/documents/notes;  "nasb" "Judges" "#" "<==" "bible-book"
cd /root/notes;  "nasb" "Genesis" "#" "<==" "bible-book"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "Jude" "#" "<==" "bible-book"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "Jude" "#" "<==" "bible-book"
cd /root/.emacs.d/host/pen.el/scripts;  "nasb" "Jude" "#" "<==" "bible-book"
cd /root/.pen/documents/notes;  "nasb" "Hebrews" "#" "<==" "bible-book"
cd /root/.pen/documents/notes;  "nasb" "Gen" "2:22" "#" "<==" "zsh"
