cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 7:14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1004" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "wander fro" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 20:13;Psalms 119:10;Psalms 119:21;Isaiah 63:17;Amos 8:12;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 597" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 597" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 598" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 597" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Timothy 4:4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 938" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 9:14-15" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 9:14-17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 938" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 938" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 13:3" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 13:1-3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "friend of God" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "James 2:23;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1148" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "friend" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 38:12;Genesis 38:20;Exodus 33:11;Deuteronomy 13:6;Judges 5:31;Ruth 4:1;I Samuel 30:26;II Samuel 3:8;II Samuel 13:3;II Samuel 15:37;II Samuel 16:16;II Samuel 16:17;I Kings 4:5;I Kings 16:11;II Kings 10:11;I Chronicles 12:17;I Chronicles 27:33;II Chronicles 20:7;Esther 5:10;Esther 5:14;Esther 6:13;Job 2:11;Job 6:14;Job 6:27;Job 12:4;Job 16:20;Job 17:5;Job 19:14;Job 19:19;Job 19:21;Job 24:17;Job 29:4;Job 32:3;Job 35:4;Job 42:7;Job 42:10;Psalms 7:4;Psalms 15:3;Psalms 25:14;Psalms 35:14;Psalms 37:3;Psalms 38:11;Psalms 41:9;Psalms 55:13;Psalms 55:20;Psalms 88:18;Proverbs 7:4;Proverbs 14:20;Proverbs 16:28;Proverbs 17:9;Proverbs 17:17;Proverbs 18:24;Proverbs 19:4;Proverbs 19:6;Proverbs 19:7;Proverbs 22:11;Proverbs 22:24;Proverbs 27:6;Proverbs 27:9;Proverbs 27:10;Song of Solomon 5:1;Song of Solomon 5:16;Isaiah 41:8;Jeremiah 3:4;Jeremiah 6:21;Jeremiah 12:6;Jeremiah 13:21;Jeremiah 20:4;Jeremiah 20:6;Jeremiah 20:10;Jeremiah 38:22;Lamentations 1:2;Micah 7:5;Zechariah 3:8;Zechariah 13:6;Matthew 11:19;Matthew 20:13;Matthew 22:12;Matthew 26:50;Mark 5:19;Luke 7:6;Luke 7:34;Luke 11:5;Luke 11:6;Luke 11:8;Luke 12:4;Luke 14:10;Luke 14:12;Luke 15:6;Luke 15:9;Luke 15:29;Luke 16:9;Luke 21:16;Luke 23:12;John 3:29;John 11:11;John 15:13;John 15:14;John 15:15;John 19:12;Acts 4:23;Acts 10:24;Acts 19:31;Acts 24:23;Acts 27:3;Hebrews 11:31;James 2:23;James 4:4;III John 1:14;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1012" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "5:36-37" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalm" "86:15" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 5:36-37" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1086" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 8-12" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1086" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 4:2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 4:11" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Thessalonians 5:18" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Genesis 5:24" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 28:49-68" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Leviticus 26:27-39" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Kings 2:1" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 11:7" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Colossians 1:16" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 24:24" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 44:24" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 8:14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 15:50-57" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 5:6-9" "#" "<==" "in-pen"
