cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Jeremiah 31:7" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 1:38" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 3:3-8" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 3:8" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1154" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Peter 3:6" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Proverbs 28:13" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "James 4:3" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 7:26" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Garment of Praise" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Isaiah 61:3;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 61:3" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah 61:3" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 4:4" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Samuel 15:23" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 12:31-32" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Genesis 24:12" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Daniel 2:20-23" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 3:14-21" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 6:41" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 6:48" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 6:51" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 8:12" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 9:5" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 10:7" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 10:9" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 10:11" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 10:14" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 10:14-15" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 11:25" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 15:1" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 15:5" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 10:10" "#" "<==" "in-pen"
