cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 14:14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 14:14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 14:14" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Ephesians 6:12" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 1:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "John 14:14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "/root/ pen/tmp/tf_temp437m942 txt 4:26" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "I Corinthians 1:30" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Romans 10:9-10" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Philippians 1:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "John 3:19" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Matthew 6:33" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Isaiah 53:5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "I Peter 1:1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 21:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 719" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Isaiah 40:11" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Isaiah 40:30" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 4:5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1098" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ezekiel 10:16-17" "#" "<==" "in-pen"
