cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Romans 8:1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes/ws/peniel;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/peniel;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/peniel;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/peniel;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1054" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2631" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3551" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2222" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "266" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2288" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4561" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5426" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1515" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1410" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1343" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2198" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2983" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5206" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4828" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2937" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1680" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4982" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1679" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2588" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1504" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "26" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "746" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1411" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1180" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1411" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1849" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2288" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1410" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4633" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4637" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3528" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1100" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2222" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4102" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1799" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4592" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4442" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1504" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2198" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1401" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4678" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 7:13-14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1058" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3870" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2198" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2378" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "165" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2307" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5046" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5485" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5426" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4102" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "26" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5360" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1680" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5429" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2570" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1799" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4442" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3528" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1014" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1849" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4561" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "166" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2222" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1097" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "228" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5048" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3056" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4487" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2983" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5479" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3404" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "225" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1107" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 12:33-37" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans 8:1" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans 8:4" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Romans 8:1" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Romans 8:4" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 8:4" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 8:31-32" "#" "<==" "in-pen"
