cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1133" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 18:1" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 2:4-7" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "James 1:27" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 1:10" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs/theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 15:8" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs/theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 15:8-9" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs/theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Samuel 16:7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "angels" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 19:1;Genesis 19:15;Genesis 28:12;Genesis 32:1;Job 4:18;Psalms 78:25;Psalms 78:49;Psalms 91:11;Psalms 103:20;Psalms 148:2;Matthew 4:6;Matthew 4:11;Matthew 13:39;Matthew 13:41;Matthew 13:49;Matthew 16:27;Matthew 18:10;Matthew 22:30;Matthew 24:31;Matthew 24:36;Matthew 25:31;Matthew 25:41;Matthew 26:53;Mark 1:13;Mark 8:38;Mark 12:25;Mark 13:27;Mark 13:32;Luke 2:15;Luke 4:10;Luke 9:26;Luke 12:8;Luke 12:9;Luke 15:10;Luke 16:22;Luke 20:36;Luke 24:23;John 1:51;John 20:12;Acts 7:53;Romans 8:38;I Corinthians 4:9;I Corinthians 6:3;I Corinthians 11:10;I Corinthians 13:1;Galatians 3:19;Colossians 2:18;II Thessalonians 1:7;I Timothy 3:16;I Timothy 5:21;Hebrews 1:4;Hebrews 1:5;Hebrews 1:6;Hebrews 1:7;Hebrews 1:13;Hebrews 2:2;Hebrews 2:5;Hebrews 2:7;Hebrews 2:9;Hebrews 2:16;Hebrews 12:22;Hebrews 13:2;I Peter 1:12;I Peter 3:22;II Peter 2:4;II Peter 2:11;Jude 1:6;Revelation of John 1:20;Revelation of John 3:5;Revelation of John 5:11;Revelation of John 7:1;Revelation of John 7:2;Revelation of John 7:11;Revelation of John 8:2;Revelation of John 8:6;Revelation of John 8:13;Revelation of John 9:14;Revelation of John 9:15;Revelation of John 12:7;Revelation of John 12:9;Revelation of John 14:10;Revelation of John 15:1;Revelation of John 15:6;Revelation of John 15:7;Revelation of John 15:8;Revelation of John 16:1;Revelation of John 17:1;Revelation of John 21:9;Revelation of John 21:12;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 732" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/docs/theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Colossians 1:15" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs/theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Timothy 3:15" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs/theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Timothy 3:15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 20:2" "#" "<==" "in-pen"
cd /root/notes/ws/lists/peniel;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 20:2" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Proverbs 30" "#" "<==" "in-pen"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd //;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "what must I do" "#" "<==" "emacs"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Mark 10:17;Luke 18:18;Acts 16:30;" "#" "<==" "emacs"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 967" "#" "<==" "emacs"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 991" "#" "<==" "emacs"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1034" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 3:5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 5:13" "#" "<==" "in-pen"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1127" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1164" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 3:4-5" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 3:4-6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 3:4-6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 5:13" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1102" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 2:8-9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 2:8-9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 5:21" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1098" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1099" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1123" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 5:21" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 1:29" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 12:2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 10:12" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 3:5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 2:9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 3:10" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 3:23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 19:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 64:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Acts 16:31" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Timothy 4:1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 6:28-29" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1123" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1123" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 11:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 11:28-29" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 4:10" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 2:8" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 6:44" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 60:11" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 60:11" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 2:12" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "appeal" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "II Kings 8:3;II Kings 8:5;Job 9:15;Psalms 77:10;Matthew 8:5;Matthew 26:53;Luke 4:38;Acts 25:11;Acts 25:12;Acts 25:21;Acts 25:25;Acts 26:32;Acts 28:19;Romans 11:2;Romans 12:1;Romans 15:30;Romans 16:17;I Corinthians 1:10;II Corinthians 5:20;II Corinthians 6:1;II Corinthians 8:17;I Thessalonians 2:3;Philemon 1:9;Philemon 1:10;Hebrews 13:22;I Peter 3:21;Jude 1:3;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1154" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1154" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1154" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1154" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1154" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 14:17" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1159" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Peter 3:10" "#" "<==" "in-pen"
