cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Ephesians 4:15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "John 8:31-32" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Revelation of John 12:11" "#" "<==" "in-pen"
cd //;  "diatheke" "-b" "RLT" "-o" "w" "-f" "internal" "-k" "Genesis 985" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "internal" "-k" "Genesis 934" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Matthew 5:1-2" "#" "<==" "in-pen"
cd /root/.pen/host/snippets/org-mode;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Matthew 5:1-2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 5:1-2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 5:1-2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke 1:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 1:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 1:35" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 1:16" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke 1:16" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke 1:35" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Exodus 20:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 103:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Genesis 17:7" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 145:19" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 118:4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Exodus 34:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 103:11" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 1:50" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke 1:38" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ASV" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Luke 1:8" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Luke 1:8-9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Luke 1:12" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 1:20" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Proverbs 15:29" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 1:14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 12:1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "I Corinthians 6:20" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke 23:32-43" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke 23:39-43" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Luke 23:39-43" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 1:50-51" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 1:50-52" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Matthew 18:4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Matthew 18:3-4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Matthew 18:3-4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ASV" "-o" "w" "-f" "plain" "-k" "Matthew 18:3-4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 5:17-20" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 5:17-22" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 5:1-2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Luke 2:15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Luke 2:14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 976" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.pen/documents/bible-notes/verse;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 102" "#" "<==" "emacs"
cd /root/.pen/documents/bible-notes/verse;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Leviticus 12:1-4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Luke 2:24" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Hebrews 9:14-27" "#" "<==" "in-pen"
cd /root/.pen/documents/bible-notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "internal" "-k" "Genesis 1142" "#" "<==" "emacs"
cd /root/.pen/documents/bible-notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Hebrews 9:14-27" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Hebrews 5:7-8" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "I Corinthians 15:22" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "II Corinthians 5:19" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II Corinthians 5:19" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "I Peter 1:20" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "I John 2:2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "II Peter 3:9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Hebrews 1:3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 145:18-20" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 145:18-20" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "internal" "-k" "Genesis 1105" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "to .*be .*grasped" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Judges" "16:28;Philippians" "2:6" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "to .*be .*grasped" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "to .*be .*grasped" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Ezekiel" "21:11;Philippians" "2:6" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Philippians" "2:6;Ezekiel" "21:11" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1105" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Philippians 2:5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "internal" "-k" "Genesis 18" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "entertained .*angels" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Hebrews" "13:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "entertained .*angels" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Hebrews" "13:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "entertained .*angels" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Hebrews" "13:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Hebrews" "13:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1146" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Deuteronomy 10:18" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Deuteronomy 10:17-18" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Deuteronomy 24:17-19" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Deuteronomy 31:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Hebrews 13:5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Revelation of John 22:2-3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Hebrews 5:7-8" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "trusting" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II" "Chronicles" "32:10;Psalms" "112:7;Jeremiah" "7:8;John" "2:24;Philippians" "1:14;I" "Peter" "2:23" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "trusting" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Psalms" "112:7" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "trusting" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "II" "Kings" "18:20;II" "Kings" "18:21;Psalms" "112:7;Isaiah" "30:12;Isaiah" "36:5;Isaiah" "36:6;Jeremiah" "7:8" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II" "Chronicles" "32:10;Psalms" "112:7;Jeremiah" "7:8;John" "2:24;Philippians" "1:14;I" "Peter" "2:23;II" "Kings" "18:20;II" "Kings" "18:21;Isaiah" "30:12;Isaiah" "36:5;Isaiah" "36:6" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "repay" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Deuteronomy" "7:10;Deuteronomy" "32:6;Deuteronomy" "32:41;I" "Samuel" "26:23;II" "Samuel" "3:39;II" "Kings" "9:26;Job" "21:19;Job" "21:31;Job" "41:11;Psalms" "28:4;Psalms" "35:12;Psalms" "38:20;Psalms" "41:10;Psalms" "137:8;Proverbs" "6:31;Proverbs" "19:17;Proverbs" "20:22;Isaiah" "59:18;Isaiah" "65:6;Jeremiah" "16:18;Jeremiah" "32:18;Jeremiah" "50:29;Jeremiah" "51:24;Jeremiah" "51:56;Ezekiel" "7:9;Daniel" "11:18;Hosea" "4:9;Hosea" "12:2;Matthew" "16:27;Matthew" "18:25;Matthew" "18:26;Matthew" "18:29;Matthew" "18:34;Luke" "7:42;Luke" "10:35;Luke" "14:12;Luke" "14:14;Romans" "12:19;I" "Thessalonians" "5:15;II" "Thessalonians" "1:6;II" "Timothy" "4:14;Philemon" "1:19;Hebrews" "10:30" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "repay" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Deuteronomy" "7:10;Job" "21:31;Job" "41:11;Proverbs" "13:21;Isaiah" "59:18;Luke" "10:35;Romans" "12:19;Philemon" "1:19" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "repay" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Genesis" "50:15;Exodus" "22:1;Leviticus" "25:27;Leviticus" "25:28;Deuteronomy" "7:10;Deuteronomy" "32:6;Deuteronomy" "32:35;Deuteronomy" "32:41;Deuteronomy" "32:43;Ruth" "2:12;I" "Samuel" "26:23;II" "Samuel" "3:39;II" "Samuel" "16:12;II" "Samuel" "19:36;I" "Kings" "8:39;II" "Kings" "9:26;II" "Chronicles" "6:30;II" "Chronicles" "20:11;II" "Chronicles" "32:25;Job" "21:19;Job" "21:31;Job" "34:11;Job" "34:33;Job" "41:11;Psalms" "10:14;Psalms" "28:4;Psalms" "31:23;Psalms" "35:12;Psalms" "37:21;Psalms" "38:20;Psalms" "41:10;Psalms" "62:12;Psalms" "69:4;Psalms" "109:5;Psalms" "116:12;Psalms" "137:8;Proverbs" "19:17;Proverbs" "24:12;Proverbs" "24:29;Isaiah" "59:18;Isaiah" "65:6;Isaiah" "66:6;Jeremiah" "16:18;Jeremiah" "25:14;Jeremiah" "50:29;Jeremiah" "51:24;Jeremiah" "51:56;Ezekiel" "7:3;Ezekiel" "7:8;Ezekiel" "23:49;Hosea" "4:9;Hosea" "12:2;Hosea" "12:14;Joel" "2:25;Matthew" "16:27;Matthew" "18:34;Luke" "6:34;Luke" "7:42;Luke" "10:35;Luke" "14:14;Luke" "19:8;Romans" "2:6;Romans" "11:35;Romans" "12:17;Romans" "12:19;I" "Thessalonians" "5:15;II" "Thessalonians" "1:6;I" "Timothy" "5:4;II" "Timothy" "4:14;Philemon" "1:19;Hebrews" "10:30;I" "Peter" "3:9;Revelation" "of" "John" "2:23" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Deuteronomy" "7:10;Deuteronomy" "32:6;Deuteronomy" "32:41;I" "Samuel" "26:23;II" "Samuel" "3:39;II" "Kings" "9:26;Job" "21:19;Job" "21:31;Job" "41:11;Psalms" "28:4;Psalms" "35:12;Psalms" "38:20;Psalms" "41:10;Psalms" "137:8;Proverbs" "6:31;Proverbs" "19:17;Proverbs" "20:22;Isaiah" "59:18;Isaiah" "65:6;Jeremiah" "16:18;Jeremiah" "32:18;Jeremiah" "50:29;Jeremiah" "51:24;Jeremiah" "51:56;Ezekiel" "7:9;Daniel" "11:18;Hosea" "4:9;Hosea" "12:2;Matthew" "16:27;Matthew" "18:25;Matthew" "18:26;Matthew" "18:29;Matthew" "18:34;Luke" "7:42;Luke" "10:35;Luke" "14:12;Luke" "14:14;Romans" "12:19;I" "Thessalonians" "5:15;II" "Thessalonians" "1:6;II" "Timothy" "4:14;Philemon" "1:19;Hebrews" "10:30;Proverbs" "13:21;Genesis" "50:15;Exodus" "22:1;Leviticus" "25:27;Leviticus" "25:28;Deuteronomy" "32:35;Deuteronomy" "32:43;Ruth" "2:12;II" "Samuel" "16:12;II" "Samuel" "19:36;I" "Kings" "8:39;II" "Chronicles" "6:30;II" "Chronicles" "20:11;II" "Chronicles" "32:25;Job" "34:11;Job" "34:33;Psalms" "10:14;Psalms" "31:23;Psalms" "37:21;Psalms" "62:12;Psalms" "69:4;Psalms" "109:5;Psalms" "116:12;Proverbs" "24:12;Proverbs" "24:29;Isaiah" "66:6;Jeremiah" "25:14;Ezekiel" "7:3;Ezekiel" "7:8;Ezekiel" "23:49;Hosea" "12:14;Joel" "2:25;Luke" "6:34;Luke" "19:8;Romans" "2:6;Romans" "11:35;Romans" "12:17;I" "Timothy" "5:4;I" "Peter" "3:9;Revelation" "of" "John" "2:23" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "submitted" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Lamentations" "5:6;Galatians" "2:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "submitted" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "I" "Chronicles" "29:24;Psalms" "81:15;Romans" "10:3" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "submitted" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Genesis" "49:15;Lamentations" "5:6" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Lamentations" "5:6;Galatians" "2:2;I" "Chronicles" "29:24;Psalms" "81:15;Romans" "10:3;Genesis" "49:15" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "I Peter 2:23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I Peter 2:23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I Peter 2:22-23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I Peter 2:21-23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I Peter 2:21-24" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "entrusting" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "2:24;I" "Peter" "2:23" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "entrusting" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "entrusting" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "2:24;I" "Peter" "2:23" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "internal" "-k" "Genesis 1094" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1094" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Galatians 3:10" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Galatians 3:13-14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "works .*of .*the .*law" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "3:20;Romans" "3:28;Galatians" "2:16;Galatians" "3:2;Galatians" "3:5;Galatians" "3:10" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "works .*of .*the .*law" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "9:32;Galatians" "2:16;Galatians" "3:2;Galatians" "3:5;Galatians" "3:10" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "works .*of .*the .*law" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Romans" "3:20;Romans" "3:28;Galatians" "2:16;Galatians" "3:2;Galatians" "3:10" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "3:20;Romans" "3:28;Galatians" "2:16;Galatians" "3:2;Galatians" "3:5;Galatians" "3:10;Romans" "9:32" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1049" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 3:28-29" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Ephesians 2:8-9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 8:4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 13" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 8:3-4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 8:3-4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Mark 14:62" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Matthew 24:30" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Daniel 7:13" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Matthew 26:64" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Acts 7:56" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Son of Man" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 50:23;Numbers 23:19;Numbers 27:1;Numbers 32:39;Numbers 32:40;Numbers 32:41;Numbers 36:1;Deuteronomy 3:14;Joshua 13:31;Joshua 17:3;Judges 18:30;I Kings 4:13;I Chronicles 7:17;Job 25:6;Job 35:8;Psalms 8:4;Psalms 80:17;Psalms 144:3;Isaiah 51:12;Isaiah 56:2;Jeremiah 49:18;Jeremiah 49:33;Jeremiah 50:40;Jeremiah 51:43;Ezekiel 2:1;Ezekiel 2:3;Ezekiel 2:6;Ezekiel 2:8;Ezekiel 3:1;Ezekiel 3:3;Ezekiel 3:4;Ezekiel 3:10;Ezekiel 3:17;Ezekiel 3:25;Ezekiel 4:1;Ezekiel 4:16;Ezekiel 5:1;Ezekiel 6:2;Ezekiel 7:2;Ezekiel 8:5;Ezekiel 8:6;Ezekiel 8:8;Ezekiel 8:12;Ezekiel 8:15;Ezekiel 8:17;Ezekiel 11:2;Ezekiel 11:4;Ezekiel 11:15;Ezekiel 12:2;Ezekiel 12:3;Ezekiel 12:9;Ezekiel 12:18;Ezekiel 12:22;Ezekiel 12:27;Ezekiel 13:2;Ezekiel 13:17;Ezekiel 14:3;Ezekiel 14:13;Ezekiel 15:2;Ezekiel 16:2;Ezekiel 17:2;Ezekiel 20:3;Ezekiel 20:4;Ezekiel 20:27;Ezekiel 20:46;Ezekiel 21:2;Ezekiel 21:6;Ezekiel 21:9;Ezekiel 21:12;Ezekiel 21:14;Ezekiel 21:19;Ezekiel 21:28;Ezekiel 22:2;Ezekiel 22:18;Ezekiel 22:24;Ezekiel 23:2;Ezekiel 23:36;Ezekiel 24:2;Ezekiel 24:16;Ezekiel 24:25;Ezekiel 25:2;Ezekiel 26:2;Ezekiel 27:2;Ezekiel 28:2;Ezekiel 28:12;Ezekiel 28:21;Ezekiel 29:2;Ezekiel 29:18;Ezekiel 30:2;Ezekiel 30:21;Ezekiel 31:2;Ezekiel 32:2;Ezekiel 32:18;Ezekiel 33:2;Ezekiel 33:7;Ezekiel 33:10;Ezekiel 33:12;Ezekiel 33:24;Ezekiel 33:30;Ezekiel 34:2;Ezekiel 35:2;Ezekiel 36:1;Ezekiel 36:17;Ezekiel 37:3;Ezekiel 37:9;Ezekiel 37:11;Ezekiel 37:16;Ezekiel 38:2;Ezekiel 38:14;Ezekiel 39:1;Ezekiel 39:17;Ezekiel 40:4;Ezekiel 43:7;Ezekiel 43:10;Ezekiel 43:18;Ezekiel 44:5;Ezekiel 47:6;Daniel 7:13;Daniel 8:17;Matthew 8:20;Matthew 9:6;Matthew 10:23;Matthew 11:19;Matthew 12:8;Matthew 12:32;Matthew 12:40;Matthew 13:37;Matthew 13:41;Matthew 16:13;Matthew 16:27;Matthew 16:28;Matthew 17:9;Matthew 17:12;Matthew 17:22;Matthew 18:11;Matthew 19:28;Matthew 20:18;Matthew 20:28;Matthew 24:27;Matthew 24:30;Matthew 24:37;Matthew 24:39;Matthew 24:44;Matthew 25:31;Matthew 26:2;Matthew 26:24;Matthew 26:45;Matthew 26:64;Mark 2:10;Mark 2:28;Mark 8:31;Mark 8:38;Mark 9:9;Mark 9:12;Mark 9:31;Mark 10:33;Mark 10:45;Mark 13:26;Mark 14:21;Mark 14:41;Mark 14:62;Luke 5:24;Luke 6:5;Luke 6:22;Luke 7:34;Luke 9:22;Luke 9:26;Luke 9:44;Luke 9:56;Luke 9:58;Luke 11:30;Luke 12:8;Luke 12:10;Luke 12:40;Luke 17:22;Luke 17:24;Luke 17:26;Luke 17:30;Luke 18:8;Luke 18:31;Luke 19:10;Luke 21:27;Luke 21:36;Luke 22:22;Luke 22:48;Luke 22:69;Luke 24:7;John 1:51;John 3:13;John 3:14;John 5:27;John 6:27;John 6:53;John 6:62;John 8:28;John 9:35;John 12:23;John 12:34;John 13:31;Acts 7:56;Hebrews 2:6;Revelation of John 1:13;Revelation of John 14:14;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 50:23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Numbers 23:19" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "410" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "John 21:16" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 3" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 4" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 3" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 3:25" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 3:25" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1049" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1049" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 3:25-26" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Isaiah 53:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 53:1-3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 14:1-3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 3:10-12" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 53" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Psalms 14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 53" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 53:2" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 14:2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 14:2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 53:2" "#" "<==" "in-pen"
