cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Obadiah 1:3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Revelation of John 15:4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Song of Solomon 2:5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 673" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II Samuel 8:17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts 5:3" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Jeremiah 18:7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Zephaniah 2:8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Proverbs 28:18" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 889" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Zephaniah 3:9" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 27:1" "#" "<==" "in-pen"
