cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "758" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1410" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4592" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "281" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1080" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1208" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5204" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4561" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1097" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3140" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2983" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2032" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "166" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2222" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3439" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4982" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5457" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4655" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3404" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "225" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "907" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5479" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "227" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4487" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 701" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3801" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 701" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 701" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 746" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3548" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6942" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 778" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8034" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 581" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8034" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 12:1-2" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts 5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 12" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 12" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 12" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 6:35" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 19:30" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 19:30" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Philippians 3:4-14" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah 33:6" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah 11:3" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Philippians 2:12" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 20:20" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Proverbs 6:16-19" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 12:9" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Hebrews 1:9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1014" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1849" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4561" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "166" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2222" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1097" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "228" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5048" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3056" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4487" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2983" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5479" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3404" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "225" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1107" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "26" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "emacs"
cd /volumes/home/shane/notes/ws/fgbmfi-full-gospel-business-mens-fellowship-international;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 118" "#" "<==" "in-pen"
cd /volumes/home/shane/notes/ws/fgbmfi-full-gospel-business-mens-fellowship-international;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 596" "#" "<==" "emacs"
cd /volumes/home/shane/notes/ws/fgbmfi-full-gospel-business-mens-fellowship-international;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /volumes/home/shane/notes/ws/fgbmfi-full-gospel-business-mens-fellowship-international;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /volumes/home/shane/notes/ws/fgbmfi-full-gospel-business-mens-fellowship-international;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8130" "#" "<==" "emacs"
cd /volumes/home/shane/notes/ws/fgbmfi-full-gospel-business-mens-fellowship-international;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8034" "#" "<==" "emacs"
cd /volumes/home/shane/notes/ws/fgbmfi-full-gospel-business-mens-fellowship-international;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "410" "#" "<==" "emacs"
cd /volumes/home/shane/notes/ws/fgbmfi-full-gospel-business-mens-fellowship-international;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 118:16-18" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I John 3:4" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I John 3:4" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 8" "#" "<==" "in-pen"
