cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Hebrews 1:3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 1:4-5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 1:14" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 4:12-16" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 1:9" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah 5:20-21" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 1:18-23" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:26-28" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 5:36" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Ephesians 2:10" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 8:29-30" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 934" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3870" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1343" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2588" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5457" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2545" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5087" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3614" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2570" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3551" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "281" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1785" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4442" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3056" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4202" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "935" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2983" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "154" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3404" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2246" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5046" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3551" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 935" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1097" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5368" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2374" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2307" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1411" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "165" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3900" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1035" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4655" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1410" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5590" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 934" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Matthew 5:5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Matthew 5:6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Matthew 5:10" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Matthew 5:11" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Matthew 5:12" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "strongs-get-wor"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Matthew 5:13" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 933" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2198" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4487" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2413" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1781" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2288" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "757" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3340" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2098" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 934" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 933" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "907" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "266" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "908" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5204" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 933" "#" "<==" "emacs"
cd /tmp;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 933" "#" "<==" "emacs"
cd /tmp;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 934" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "I Corinthians" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II Corinthians 6:14" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 12:30" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Ephesians 2:16-20" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 5" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 10:11-16" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 8" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Colossians 1:15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Colossians 1:15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1108" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2307" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4103" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5485" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1515" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4102" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "26" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1680" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3056" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "225" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2098" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "154" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1922" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4678" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1411" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5479" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5457" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1849" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4655" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "859" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "266" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1504" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "517" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2937" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "746" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4138" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4716" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4561" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2288" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3466" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "165" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1107" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5046" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1108" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3972" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "652" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5095" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "80" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2857" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2168" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4336" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3842" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "191" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2192" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1223" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "606" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4257" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3918" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2531" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2532" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2592" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "837" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "575" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1921" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3129" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "27" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1249" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5228" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1213" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3778" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3973" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4137" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4152" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4907" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4043" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "516" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "699" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "18" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1412" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2596" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2904" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5281" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3115" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2427" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3310" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2819" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4506" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3179" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5207" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "629" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4416" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2936" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1093" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3707" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1535" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2362" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2963" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4253" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4921" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2776" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4983" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1577" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3498" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2443" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "846" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1096" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4409" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2106" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "604" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1517" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4218" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "526" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2190" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1271" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1161" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3570" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3936" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2714" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "299" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "410" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1487" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1065" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1961" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2311" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1476" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3334" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2784" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5259" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3568" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5463" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3804" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "466" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3588" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5303" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2347" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3622" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1325" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1519" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "613" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1074" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5319" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2309" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5101" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4149" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1722" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1484" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2605" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3560" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "444" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1321" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2872" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "75" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1754" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4416" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 13:10-14" "#" "<==" "in-pen"
