cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "foundation" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Deuteronomy 32:22;Joshua 6:26;II Samuel 22:8;II Samuel 22:16;I Kings 5:17;I Kings 6:37;I Kings 7:9;I Kings 7:10;I Kings 16:34;II Chronicles 8:16;II Chronicles 23:5;Ezra 3:6;Ezra 3:10;Ezra 3:11;Ezra 3:12;Ezra 4:12;Ezra 5:16;Ezra 6:3;Job 4:19;Job 22:16;Job 38:4;Psalms 11:3;Psalms 18:7;Psalms 18:15;Psalms 82:5;Psalms 89:14;Psalms 97:2;Psalms 102:25;Psalms 104:5;Psalms 137:7;Proverbs 8:29;Isaiah 6:4;Isaiah 24:18;Isaiah 28:16;Isaiah 40:21;Isaiah 44:28;Isaiah 48:13;Isaiah 51:13;Isaiah 51:16;Isaiah 54:11;Isaiah 58:12;Jeremiah 31:37;Jeremiah 51:26;Lamentations 4:11;Ezekiel 13:14;Ezekiel 30:4;Ezekiel 41:8;Micah 1:6;Micah 6:2;Haggai 2:18;Zechariah 4:9;Zechariah 8:9;Matthew 13:35;Matthew 25:34;Luke 6:48;Luke 6:49;Luke 11:50;Luke 14:29;John 17:24;Acts 16:26;Romans 15:20;I Corinthians 3:10;I Corinthians 3:11;I Corinthians 3:12;I Corinthians 3:14;Ephesians 1:4;Ephesians 2:20;I Timothy 6:19;II Timothy 2:19;Hebrews 1:10;Hebrews 4:3;Hebrews 6:1;Hebrews 9:26;Hebrews 11:10;I Peter 1:20;Revelation of John 13:8;Revelation of John 17:8;Revelation of John 21:14;Revelation of John 21:19;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 6:11-15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 6:1-2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1099" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 2:19-21" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1065" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 3:10-15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1061" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 15:18-21" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 987" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 14:27-30" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 979" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 6:46-49" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 11:10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "designer is God" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "builder is God" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Hebrews 11:10;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1144" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 11:8-10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "striving" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Ecclesiastes 1:14;Ecclesiastes 1:17;Ecclesiastes 2:11;Ecclesiastes 2:17;Ecclesiastes 2:22;Ecclesiastes 2:26;Ecclesiastes 4:4;Ecclesiastes 4:6;Ecclesiastes 4:16;Ecclesiastes 6:9;Philippians 1:27;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1104" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 1:27-30" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "strive" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 32:28;Exodus 21:22;Proverbs 28:4;Isaiah 41:11;Isaiah 45:9;Luke 13:24;Romans 15:30;I Corinthians 14:12;I Timothy 4:10;Hebrews 4:11;Hebrews 12:14;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 986" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 13:24" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 45:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Timothy 4:10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Proverbs 28:4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 12:14" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 4:11" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1061" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 15:30-32" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1137" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1136" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "faith comes" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Romans 10:17;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1056" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "striving" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Ecclesiastes 1:14;Ecclesiastes 1:17;Ecclesiastes 2:11;Ecclesiastes 2:17;Ecclesiastes 2:22;Ecclesiastes 2:26;Ecclesiastes 4:4;Ecclesiastes 4:6;Ecclesiastes 4:16;Ecclesiastes 6:9;Philippians 1:27;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Psalms 46:8-11" "#" "<==" "in-pen"
