cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 3" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 4" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 5" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 4" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 3" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 4" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 5" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 6" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 9" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 10" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 11" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 12" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 3" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 4" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 5" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 6" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 6" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Ezekiel 36:26-27" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Ezekiel 36:26-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "I Timothy" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 974" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Galatians 3:23-24" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Romans 10:1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1163" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1025" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "bronze .*serpent" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Numbers" "21:9;II" "Kings" "18:4" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "bronze .*serpent" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "bronze .*serpent" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Numbers" "21:9;II" "Kings" "18:4" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Colossians 2:14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Micah 6:8" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "behold .*the .*Son" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Numbers" "24:17;Judges" "4:22;II" "Samuel" "13:24;II" "Kings" "15:11;II" "Kings" "15:26;Psalms" "11:7;Jeremiah" "13:13" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "behold .*the .*Son" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Genesis" "22:7;Genesis" "22:13;Genesis" "27:2;I" "Samuel" "18:17;II" "Samuel" "4:8;II" "Samuel" "13:24;II" "Samuel" "18:26;Job" "25:5;Psalms" "102:19;Ezekiel" "8:5;Ezekiel" "8:7;Ezekiel" "8:10;Ezekiel" "11:1;Matthew" "17:5;Matthew" "18:10;Luke" "22:47;Revelation" "of" "John" "14:14" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "behold .*the .*Son" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Numbers" "24:17;Psalms" "8:3;I" "John" "3:1" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Numbers" "24:17;Genesis" "22:13;II" "Samuel" "4:8;Ezekiel" "11:1;Matthew" "17:5;Revelation" "of" "John" "14:14;I" "John" "3:1" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "beholds .*the .*Son" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "6:40" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "beholds .*the .*Son" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "beholds .*the .*Son" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "6:40" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 39" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 40" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 39" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Genesis 39:21" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "everlasting .*dominion" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms" "145:13;Daniel" "4:3;Daniel" "4:34;Daniel" "7:14;Daniel" "7:27" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "everlasting .*dominion" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Psalms" "145:13;Daniel" "4:3;Daniel" "4:34;Daniel" "7:14;Daniel" "7:27" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "everlasting .*dominion" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Psalms" "145:13;Daniel" "4:34;Daniel" "7:14" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms" "145:13;Daniel" "4:3;Daniel" "4:34;Daniel" "7:14;Daniel" "7:27" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "The .*Lord .*has .*made .*everything .*for .*Himself" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "The .*Lord .*has .*made .*everything .*for .*Himself" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "The .*Lord .*has .*made .*everything .*for .*Himself" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Before .*all .*things." "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 593" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "is .*before .*all .*things" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "24:8;Colossians" "1:17;I" "John" "3:19" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "is .*before .*all .*things" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Ecclesiastes" "1:10;Ecclesiastes" "9:1;Lamentations" "1:6;Daniel" "2:9;Acts" "10:32;Acts" "26:2;Colossians" "1:17" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "is .*before .*all .*things" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Jeremiah" "16:9;Colossians" "1:17" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "24:8;Colossians" "1:17;Acts" "26:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Remember .*the .*former .*things" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah" "46:9" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Remember .*the .*former .*things" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Isaiah" "43:18;Isaiah" "46:9" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Remember .*the .*former .*things" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah" "46:9;Isaiah" "43:18" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "made .*everything .*for .*Himself" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "made .*everything .*for .*Himself" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "made .*everything .*for .*Himself" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "firstborn .*of .*many .*brethren" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "firstborn .*of .*many .*brethren" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "firstborn .*of .*many .*brethren" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "firstborn .*among .*many .*brethren" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "8:29" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "firstborn .*among .*many .*brethren" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "8:29" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "firstborn .*among .*many .*brethren" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "8:29" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "bring .*forth .*more .*fruit" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "bring .*forth .*more .*fruit" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "John" "15:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "bring .*forth .*more .*fruit" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "15:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Philippians 3:12-14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "reign .*with .*Him" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Deuteronomy" "32:12;I" "Kings" "11:8;Daniel" "11:39;II" "Timothy" "2:12;Revelation" "of" "John" "20:6" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "reign .*with .*Him" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "II" "Samuel" "3:21;II" "Kings" "11:3;II" "Kings" "25:27;I" "Chronicles" "29:30;Jeremiah" "52:31;Daniel" "2:1;II" "Timothy" "2:12;Revelation" "of" "John" "20:6" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "reign .*with .*Him" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Deuteronomy" "32:12;I" "Kings" "11:8;Jeremiah" "52:31;II" "Timothy" "2:12;Hebrews" "11:9;Revelation" "of" "John" "20:6" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/sermons;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Deuteronomy" "32:12;II" "Timothy" "2:12;Revelation" "of" "John" "20:6;Daniel" "2:1;Hebrews" "11:9" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Yemin" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Yemin" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Yemin" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "yeman" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "yeman" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "yeman" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Yamin" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Yamin" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Yamin" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Sheban" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I" "Chronicles" "15:24;Nehemiah" "9:4;Nehemiah" "9:5;Nehemiah" "10:4;Nehemiah" "10:10;Nehemiah" "10:12;Nehemiah" "12:14" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Sheban" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "I" "Chronicles" "15:24;Nehemiah" "9:4;Nehemiah" "9:5;Nehemiah" "10:4;Nehemiah" "10:10;Nehemiah" "10:12;Nehemiah" "12:14" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Sheban" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "I" "Chronicles" "15:24;Nehemiah" "9:4;Nehemiah" "9:5;Nehemiah" "10:4;Nehemiah" "10:10;Nehemiah" "10:12;Nehemiah" "12:14" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I" "Chronicles" "15:24;Nehemiah" "9:4;Nehemiah" "9:5;Nehemiah" "10:4;Nehemiah" "10:10;Nehemiah" "10:12;Nehemiah" "12:14" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 353" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "yemen" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "yaman" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "teman" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 36:11;Genesis 36:15;Genesis 36:34;Genesis 36:42;I Chronicles 1:36;I Chronicles 1:45;I Chronicles 1:53;Job 2:11;Job 4:1;Job 15:1;Job 22:1;Job 42:7;Job 42:9;Jeremiah 49:7;Jeremiah 49:20;Ezekiel 20:46;Ezekiel 25:13;Amos 1:12;Obadiah 1:9;Habakkuk 3:3;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 906" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "sheba" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 10:7;Genesis 10:28;Genesis 21:14;Genesis 21:31;Genesis 21:32;Genesis 21:33;Genesis 22:19;Genesis 25:3;Genesis 26:23;Genesis 26:33;Genesis 28:10;Genesis 46:1;Genesis 46:5;Exodus 6:23;Joshua 7:5;Joshua 15:28;Joshua 19:2;Judges 20:1;I Samuel 3:20;I Samuel 8:2;II Samuel 3:10;II Samuel 11:3;II Samuel 12:24;II Samuel 17:11;II Samuel 20:1;II Samuel 20:2;II Samuel 20:6;II Samuel 20:7;II Samuel 20:10;II Samuel 20:13;II Samuel 20:21;II Samuel 20:22;II Samuel 24:2;II Samuel 24:7;II Samuel 24:15;I Kings 1:11;I Kings 1:15;I Kings 1:16;I Kings 1:28;I Kings 1:31;I Kings 2:13;I Kings 2:18;I Kings 2:19;I Kings 4:25;I Kings 10:1;I Kings 10:4;I Kings 10:10;I Kings 10:13;I Kings 19:3;II Kings 11:2;II Kings 12:1;II Kings 23:8;I Chronicles 1:9;I Chronicles 1:22;I Chronicles 1:32;I Chronicles 4:28;I Chronicles 5:13;I Chronicles 15:24;I Chronicles 21:2;II Chronicles 9:1;II Chronicles 9:3;II Chronicles 9:9;II Chronicles 9:12;II Chronicles 19:4;II Chronicles 24:1;II Chronicles 30:5;Nehemiah 9:4;Nehemiah 9:5;Nehemiah 10:4;Nehemiah 10:10;Nehemiah 10:12;Nehemiah 11:27;Nehemiah 11:30;Nehemiah 12:14;Job 6:19;Psalms 72:10;Psalms 72:15;Isaiah 60:6;Jeremiah 6:20;Ezekiel 27:22;Ezekiel 27:23;Ezekiel 38:13;Amos 5:5;Amos 8:14;Zechariah 1:7;Matthew 1:6;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 376" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Solomon" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "II Samuel 5:14;II Samuel 12:24;I Kings 1:10;I Kings 1:11;I Kings 1:12;I Kings 1:13;I Kings 1:17;I Kings 1:19;I Kings 1:21;I Kings 1:26;I Kings 1:30;I Kings 1:33;I Kings 1:34;I Kings 1:37;I Kings 1:38;I Kings 1:39;I Kings 1:43;I Kings 1:46;I Kings 1:47;I Kings 1:50;I Kings 1:51;I Kings 1:52;I Kings 1:53;I Kings 2:1;I Kings 2:12;I Kings 2:13;I Kings 2:17;I Kings 2:19;I Kings 2:22;I Kings 2:23;I Kings 2:25;I Kings 2:27;I Kings 2:29;I Kings 2:41;I Kings 2:45;I Kings 2:46;I Kings 3:1;I Kings 3:3;I Kings 3:4;I Kings 3:5;I Kings 3:6;I Kings 3:10;I Kings 3:15;I Kings 4:1;I Kings 4:7;I Kings 4:11;I Kings 4:15;I Kings 4:21;I Kings 4:22;I Kings 4:25;I Kings 4:26;I Kings 4:27;I Kings 4:29;I Kings 4:30;I Kings 4:34;I Kings 5:1;I Kings 5:2;I Kings 5:7;I Kings 5:8;I Kings 5:10;I Kings 5:11;I Kings 5:12;I Kings 5:13;I Kings 5:15;I Kings 5:16;I Kings 5:18;I Kings 6:1;I Kings 6:2;I Kings 6:11;I Kings 6:14;I Kings 6:21;I Kings 7:1;I Kings 7:8;I Kings 7:13;I Kings 7:14;I Kings 7:40;I Kings 7:45;I Kings 7:47;I Kings 7:48;I Kings 7:51;I Kings 8:1;I Kings 8:2;I Kings 8:5;I Kings 8:12;I Kings 8:22;I Kings 8:54;I Kings 8:63;I Kings 8:65;I Kings 9:1;I Kings 9:2;I Kings 9:10;I Kings 9:11;I Kings 9:12;I Kings 9:15;I Kings 9:16;I Kings 9:17;I Kings 9:19;I Kings 9:21;I Kings 9:22;I Kings 9:23;I Kings 9:24;I Kings 9:25;I Kings 9:26;I Kings 9:27;I Kings 9:28;I Kings 10:1;I Kings 10:2;I Kings 10:3;I Kings 10:4;I Kings 10:10;I Kings 10:13;I Kings 10:14;I Kings 10:16;I Kings 10:21;I Kings 10:23;I Kings 10:24;I Kings 10:26;I Kings 10:28;I Kings 11:1;I Kings 11:2;I Kings 11:4;I Kings 11:5;I Kings 11:6;I Kings 11:7;I Kings 11:9;I Kings 11:11;I Kings 11:14;I Kings 11:25;I Kings 11:26;I Kings 11:27;I Kings 11:28;I Kings 11:31;I Kings 11:40;I Kings 11:41;I Kings 11:42;I Kings 11:43;I Kings 12:2;I Kings 12:6;I Kings 12:21;I Kings 12:23;I Kings 14:21;I Kings 14:26;II Kings 21:7;II Kings 23:13;II Kings 24:13;II Kings 25:16;I Chronicles 3:5;I Chronicles 3:10;I Chronicles 6:10;I Chronicles 6:32;I Chronicles 14:4;I Chronicles 18:8;I Chronicles 22:5;I Chronicles 22:6;I Chronicles 22:7;I Chronicles 22:9;I Chronicles 22:17;I Chronicles 23:1;I Chronicles 28:5;I Chronicles 28:6;I Chronicles 28:9;I Chronicles 28:11;I Chronicles 28:20;I Chronicles 29:1;I Chronicles 29:19;I Chronicles 29:23;I Chronicles 29:24;I Chronicles 29:25;I Chronicles 29:28;II Chronicles 1:1;II Chronicles 1:2;II Chronicles 1:3;II Chronicles 1:5;II Chronicles 1:6;II Chronicles 1:7;II Chronicles 1:8;II Chronicles 1:11;II Chronicles 1:13;II Chronicles 1:14;II Chronicles 1:16;II Chronicles 2:1;II Chronicles 2:2;II Chronicles 2:3;II Chronicles 2:11;II Chronicles 2:17;II Chronicles 3:1;II Chronicles 3:3;II Chronicles 4:11;II Chronicles 4:16;II Chronicles 4:18;II Chronicles 4:19;II Chronicles 5:1;II Chronicles 5:2;II Chronicles 5:6;II Chronicles 6:1;II Chronicles 6:13;II Chronicles 7:1;II Chronicles 7:5;II Chronicles 7:7;II Chronicles 7:8;II Chronicles 7:10;II Chronicles 7:11;II Chronicles 7:12;II Chronicles 8:1;II Chronicles 8:3;II Chronicles 8:6;II Chronicles 8:8;II Chronicles 8:9;II Chronicles 8:10;II Chronicles 8:11;II Chronicles 8:12;II Chronicles 8:16;II Chronicles 8:17;II Chronicles 8:18;II Chronicles 9:1;II Chronicles 9:2;II Chronicles 9:3;II Chronicles 9:9;II Chronicles 9:10;II Chronicles 9:12;II Chronicles 9:13;II Chronicles 9:14;II Chronicles 9:15;II Chronicles 9:20;II Chronicles 9:22;II Chronicles 9:23;II Chronicles 9:25;II Chronicles 9:28;II Chronicles 9:29;II Chronicles 9:30;II Chronicles 9:31;II Chronicles 10:2;II Chronicles 10:6;II Chronicles 11:3;II Chronicles 11:17;II Chronicles 12:9;II Chronicles 13:6;II Chronicles 13:7;II Chronicles 30:26;II Chronicles 33:7;II Chronicles 35:3;II Chronicles 35:4;Ezra 2:55;Ezra 2:58;Nehemiah 7:57;Nehemiah 7:60;Nehemiah 11:3;Nehemiah 12:45;Nehemiah 13:26;Proverbs 1:1;Proverbs 10:1;Proverbs 25:1;Song of Solomon 1:1;Song of Solomon 1:5;Song of Solomon 3:7;Song of Solomon 3:9;Song of Solomon 3:11;Song of Solomon 8:11;Song of Solomon 8:12;Jeremiah 52:20;Matthew 1:6;Matthew 1:7;Matthew 6:29;Matthew 12:42;Luke 11:31;Luke 12:27;John 10:23;Acts 3:11;Acts 5:12;Acts 7:47;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "wives" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 4:19;Genesis 4:23;Genesis 6:2;Genesis 6:18;Genesis 7:7;Genesis 7:13;Genesis 8:16;Genesis 8:18;Genesis 11:29;Genesis 28:9;Genesis 30:26;Genesis 31:17;Genesis 31:50;Genesis 32:22;Genesis 34:29;Genesis 36:2;Genesis 36:6;Genesis 37:2;Genesis 45:19;Genesis 46:5;Genesis 46:26;Exodus 1:15;Exodus 1:17;Exodus 1:18;Exodus 1:19;Exodus 1:20;Exodus 1:21;Exodus 22:24;Exodus 32:2;Numbers 14:3;Numbers 16:27;Numbers 32:26;Deuteronomy 3:19;Deuteronomy 17:17;Deuteronomy 21:15;Deuteronomy 29:11;Joshua 1:14;Judges 3:6;Judges 8:30;Judges 21:7;Judges 21:16;Judges 21:18;Judges 21:23;Ruth 1:4;I Samuel 1:2;I Samuel 25:43;I Samuel 27:3;I Samuel 30:3;I Samuel 30:5;I Samuel 30:18;II Samuel 2:2;II Samuel 5:13;II Samuel 12:8;II Samuel 12:11;II Samuel 19:5;I Kings 11:3;I Kings 11:4;I Kings 11:8;I Kings 20:3;I Kings 20:5;I Kings 20:7;II Kings 4:1;II Kings 24:15;I Chronicles 4:5;I Chronicles 7:4;I Chronicles 8:8;I Chronicles 14:3;I Chronicles 23:22;II Chronicles 11:21;II Chronicles 11:23;II Chronicles 13:21;II Chronicles 20:13;II Chronicles 21:14;II Chronicles 21:17;II Chronicles 24:3;II Chronicles 29:9;II Chronicles 31:18;Ezra 9:2;Ezra 10:3;Ezra 10:10;Ezra 10:11;Ezra 10:14;Ezra 10:17;Ezra 10:18;Ezra 10:19;Ezra 10:44;Nehemiah 4:14;Nehemiah 5:1;Nehemiah 10:28;Isaiah 13:16;Jeremiah 6:12;Jeremiah 8:10;Jeremiah 14:16;Jeremiah 18:21;Jeremiah 29:6;Jeremiah 29:23;Jeremiah 35:8;Jeremiah 38:23;Jeremiah 44:9;Jeremiah 44:15;Jeremiah 44:25;Daniel 5:2;Daniel 5:3;Daniel 5:23;Daniel 6:24;Zechariah 12:12;Zechariah 12:13;Zechariah 12:14;Matthew 19:8;Acts 21:5;I Corinthians 7:29;Ephesians 5:22;Ephesians 5:24;Ephesians 5:25;Ephesians 5:28;Colossians 3:18;Colossians 3:19;I Peter 3:1;I Peter 3:7;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "concubines" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 25:6;II Samuel 5:13;II Samuel 15:16;II Samuel 16:21;II Samuel 16:22;II Samuel 19:5;II Samuel 20:3;I Kings 11:3;I Chronicles 3:9;II Chronicles 11:21;Esther 2:14;Ecclesiastes 2:8;Song of Solomon 6:8;Song of Solomon 6:9;Daniel 5:2;Daniel 5:3;Daniel 5:23;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 302" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "period" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 50:3;Leviticus 8:33;Leviticus 15:25;Judges 19:2;I Chronicles 29:27;Ezekiel 18:6;Daniel 4:16;Daniel 4:23;Daniel 4:25;Daniel 4:32;Daniel 4:34;Daniel 7:12;Daniel 8:19;Daniel 8:23;Acts 1:3;Acts 3:21;Acts 13:18;Acts 20:31;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 105" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Matthew 1:21-22" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Matthew 1:21-23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 171" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "everything I have spoken" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 672" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 676" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 676" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 676" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "935" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1588" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "269" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3618" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "717" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4753" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5973" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1314" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "398" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3293" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1706" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8354" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3196" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2461" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7453" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7937" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1730" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3463" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3820" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5782" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6963" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1849" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6605" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7474" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3123" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8535" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7218" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4390" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6977" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7447" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3915" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6584" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3801" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "351" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3847" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7364" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 676" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 732" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "Leviticus 15:29" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "John 5:43" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 5:43" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "RLT" "-o" "w" "-f" "plain" "-k" "John 5" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 18" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 19" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 18" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 17" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 18" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 171" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ASV" "-o" "w" "-f" "internal" "-k" "Genesis 171" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Genesis 171" "#" "<==" "emacs"
