cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "8" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "7" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "5" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "10" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "11" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "14" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "12" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "13" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/vimbible;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans" "16" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 13" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1053" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1053" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 890" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 892" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ABP" "-o" "w" "-f" "plain" "-k" "Jonah" "3:4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "gospel" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Matthew 4:23;Matthew 9:35;Matthew 11:5;Matthew 24:14;Matthew 26:13;Mark 1:1;Mark 1:14;Mark 1:15;Mark 8:35;Mark 10:29;Mark 13:10;Mark 14:9;Mark 16:15;Luke 3:18;Luke 4:18;Luke 7:22;Luke 9:6;Luke 16:16;Luke 20:1;Acts 8:25;Acts 8:40;Acts 14:7;Acts 14:15;Acts 14:21;Acts 15:7;Acts 16:10;Acts 20:24;Romans 1:1;Romans 1:9;Romans 1:15;Romans 1:16;Romans 2:16;Romans 11:28;Romans 15:16;Romans 15:19;Romans 15:20;Romans 16:25;I Corinthians 1:17;I Corinthians 4:15;I Corinthians 9:12;I Corinthians 9:14;I Corinthians 9:16;I Corinthians 9:18;I Corinthians 9:23;I Corinthians 15:1;II Corinthians 2:12;II Corinthians 4:3;II Corinthians 4:4;II Corinthians 8:18;II Corinthians 9:13;II Corinthians 10:14;II Corinthians 10:16;II Corinthians 11:4;II Corinthians 11:7;Galatians 1:6;Galatians 1:7;Galatians 1:8;Galatians 1:9;Galatians 1:11;Galatians 2:2;Galatians 2:5;Galatians 2:7;Galatians 2:14;Galatians 3:8;Galatians 4:13;Ephesians 1:13;Ephesians 3:6;Ephesians 6:15;Ephesians 6:19;Philippians 1:5;Philippians 1:7;Philippians 1:12;Philippians 1:16;Philippians 1:27;Philippians 2:22;Philippians 4:3;Philippians 4:15;Colossians 1:5;Colossians 1:23;I Thessalonians 1:5;I Thessalonians 2:2;I Thessalonians 2:4;I Thessalonians 2:8;I Thessalonians 2:9;I Thessalonians 3:2;II Thessalonians 1:8;II Thessalonians 2:14;I Timothy 1:11;II Timothy 1:8;II Timothy 1:10;II Timothy 2:8;Philemon 1:13;I Peter 1:12;I Peter 4:6;I Peter 4:17;Revelation of John 14:6;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Peniel" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 32:30;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 32" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 32" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6439" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3478" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7971" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis" "32:30" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Proverbs" "19:17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1064" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "13" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I" "Cor" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "13:8" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I" "Tim" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "13:8" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1047" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1048" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1142" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1158" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1158" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1158" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Deuteronomy" "15:7" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Proverbs" "19:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Job" "31:16" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah" "58:7" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah" "58:10" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "5:42" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "6:1" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "25:35" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke" "10:35" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke" "11:41" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke" "12:33" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke" "14:13" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke" "18:22" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke" "19:8" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "3:2" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "3:10" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "9:36" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "10:2" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "10:31" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "24:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "1" "Corinthians" "16:1" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "2" "Corinthians" "8:11" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "2" "Corinthians" "9:6" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "2" "Corinthians" "9:6" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Galatians" "2:10" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Ephesians" "4:28" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "1" "Timothy" "6:18" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "1" "John" "3:17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 32" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1137" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1136" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 573" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "phrase" "-k" "Lord Jesus Christ" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "diatheke" "-b" "" "-o" "w" "-f" "plain" "-k" "Acts" "11:17;Acts" "15:26;Acts" "20:21;Acts" "28:31;Romans" "1:7;Romans" "5:1;Romans" "5:11;Romans" "13:14;Romans" "15:6;Romans" "15:30;Romans" "16:24;I" "Corinthians" "1:2;I" "Corinthians" "1:3;I" "Corinthians" "1:7;I" "Corinthians" "1:8;I" "Corinthians" "1:10;I" "Corinthians" "6:11;I" "Corinthians" "15:57;II" "Corinthians" "1:2;II" "Corinthians" "1:3;II" "Corinthians" "8:9;II" "Corinthians" "13:14;Galatians" "1:3;Galatians" "6:14;Galatians" "6:18;Ephesians" "1:2;Ephesians" "1:3;Ephesians" "1:17;Ephesians" "5:20;Ephesians" "6:23;Ephesians" "6:24;Philippians" "1:2;Philippians" "3:20;Philippians" "4:23;Colossians" "1:3;I" "Thessalonians" "1:1;I" "Thessalonians" "1:3;I" "Thessalonians" "5:9;I" "Thessalonians" "5:23;I" "Thessalonians" "5:28;II" "Thessalonians" "1:1;II" "Thessalonians" "1:2;II" "Thessalonians" "1:12;II" "Thessalonians" "2:1;II" "Thessalonians" "2:14;II" "Thessalonians" "2:16;II" "Thessalonians" "3:6;II" "Thessalonians" "3:12;II" "Thessalonians" "3:18;I" "Timothy" "6:3;I" "Timothy" "6:14;Philemon" "1:3;Philemon" "1:25;James" "1:1;James" "2:1;I" "Peter" "1:3;II" "Peter" "1:8;II" "Peter" "1:14;II" "Peter" "1:16;Jude" "1:17;Jude" "1:21;" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "phrase" "-k" "Lord Jesus Christ" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Acts" "11:17;Acts" "15:26;Acts" "20:21;Acts" "28:31;Romans" "1:7;Romans" "5:1;Romans" "5:11;Romans" "13:14;Romans" "15:6;Romans" "15:30;Romans" "16:24;I" "Corinthians" "1:2;I" "Corinthians" "1:3;I" "Corinthians" "1:7;I" "Corinthians" "1:8;I" "Corinthians" "1:10;I" "Corinthians" "6:11;I" "Corinthians" "15:57;II" "Corinthians" "1:2;II" "Corinthians" "1:3;II" "Corinthians" "8:9;II" "Corinthians" "13:14;Galatians" "1:3;Galatians" "6:14;Galatians" "6:18;Ephesians" "1:2;Ephesians" "1:3;Ephesians" "1:17;Ephesians" "5:20;Ephesians" "6:23;Ephesians" "6:24;Philippians" "1:2;Philippians" "3:20;Philippians" "4:23;Colossians" "1:3;I" "Thessalonians" "1:1;I" "Thessalonians" "1:3;I" "Thessalonians" "5:9;I" "Thessalonians" "5:23;I" "Thessalonians" "5:28;II" "Thessalonians" "1:1;II" "Thessalonians" "1:2;II" "Thessalonians" "1:12;II" "Thessalonians" "2:1;II" "Thessalonians" "2:14;II" "Thessalonians" "2:16;II" "Thessalonians" "3:6;II" "Thessalonians" "3:12;II" "Thessalonians" "3:18;I" "Timothy" "6:3;I" "Timothy" "6:14;Philemon" "1:3;Philemon" "1:25;James" "1:1;James" "2:1;I" "Peter" "1:3;II" "Peter" "1:8;II" "Peter" "1:14;II" "Peter" "1:16;Jude" "1:17;Jude" "1:21;" "#" "<==" "xargs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "14:23" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "James" "1:12" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms" "112" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "6:3" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John" "4:8" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II" "Corinthians" "9:7" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "6:2" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "6:2-3" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke" "11:38-42" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Luke" "11:39-42" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I" "Corinthians" "8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1070" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1069" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "I" "Corinthians" "7:36" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "I" "Corinthians" "7:36" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "I" "Corinthians" "7:37" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "I" "Corinthians" "7:37" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II" "Corinthians" "8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1086" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II" "Corinthians" "8" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "James" "2:15-16" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "13:24-43" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "13:24-43" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "13:24-43" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 944" "#" "<==" "emacs"
