cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Hebrews 13:2" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Hebrews 9:14" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Galatians 5:14" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 798" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/vim-universal-highlight;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 798" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 26" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 6:28" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 6:28-29" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 6:34" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 8:14-17" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 8:14" "#" "<==" "in-pen"
