cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1163" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "whole world" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Job 34:13;Isaiah 27:6;Matthew 16:26;Matthew 24:14;Matthew 26:13;Mark 8:36;Mark 14:9;Luke 9:25;Romans 3:19;Colossians 1:6;I John 2:2;I John 5:19;Revelation of John 3:10;Revelation of John 12:9;Revelation of John 16:14;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1170" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Revelation of John 3:10-12" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 5:19" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "darkness" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1:2;Genesis 1:4;Genesis 1:5;Genesis 1:18;Genesis 15:12;Exodus 10:21;Exodus 10:22;Exodus 14:20;Exodus 20:21;Deuteronomy 4:11;Deuteronomy 5:22;Deuteronomy 5:23;Deuteronomy 28:29;Joshua 24:7;I Samuel 2:9;II Samuel 22:10;II Samuel 22:12;II Samuel 22:29;I Kings 8:12;II Chronicles 6:1;Job 3:4;Job 3:5;Job 3:6;Job 5:14;Job 10:21;Job 10:22;Job 11:17;Job 12:22;Job 15:22;Job 15:23;Job 15:30;Job 16:16;Job 17:12;Job 17:13;Job 18:18;Job 19:8;Job 20:26;Job 22:11;Job 22:13;Job 23:17;Job 24:17;Job 26:10;Job 28:3;Job 29:3;Job 30:26;Job 34:22;Job 37:19;Job 38:9;Job 38:17;Job 38:19;Psalms 18:9;Psalms 18:11;Psalms 18:28;Psalms 82:5;Psalms 88:12;Psalms 88:18;Psalms 91:6;Psalms 97:2;Psalms 104:20;Psalms 105:28;Psalms 107:10;Psalms 107:14;Psalms 112:4;Psalms 139:11;Psalms 139:12;Psalms 143:3;Proverbs 2:13;Proverbs 4:19;Proverbs 7:9;Proverbs 20:20;Ecclesiastes 2:13;Ecclesiastes 2:14;Ecclesiastes 5:17;Ecclesiastes 6:4;Ecclesiastes 11:8;Isaiah 5:20;Isaiah 5:30;Isaiah 8:22;Isaiah 9:2;Isaiah 29:18;Isaiah 42:7;Isaiah 42:16;Isaiah 45:3;Isaiah 45:7;Isaiah 45:19;Isaiah 47:5;Isaiah 49:9;Isaiah 50:10;Isaiah 58:10;Isaiah 59:9;Isaiah 60:2;Jeremiah 2:6;Jeremiah 2:31;Jeremiah 13:16;Jeremiah 23:12;Lamentations 3:2;Lamentations 3:6;Ezekiel 32:8;Ezekiel 34:12;Daniel 2:22;Joel 2:2;Joel 2:31;Amos 4:13;Amos 5:8;Amos 5:18;Amos 5:20;Micah 3:6;Micah 7:8;Nahum 1:8;Zephaniah 1:15;Matthew 4:16;Matthew 6:23;Matthew 8:12;Matthew 22:13;Matthew 25:30;Matthew 27:45;Mark 15:33;Luke 1:79;Luke 11:34;Luke 11:35;Luke 22:53;Luke 23:44;John 1:5;John 3:19;John 8:12;John 12:35;John 12:46;Acts 2:20;Acts 13:11;Acts 26:18;Romans 2:19;Romans 13:12;I Corinthians 4:5;II Corinthians 4:6;II Corinthians 6:14;Ephesians 5:8;Ephesians 5:11;Ephesians 6:12;Colossians 1:13;I Thessalonians 5:4;I Thessalonians 5:5;Hebrews 12:18;I Peter 2:9;II Peter 2:4;II Peter 2:17;I John 1:5;I John 1:6;I John 2:8;I John 2:9;I John 2:11;Jude 1:6;Jude 1:13;Revelation of John 16:10;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 2:10-12" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "stumb" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Leviticus 19:14;Leviticus 26:37;II Samuel 6:6;I Chronicles 13:9;Job 4:4;Job 18:12;Psalms 9:3;Psalms 27:2;Psalms 35:15;Psalms 73:2;Psalms 105:37;Psalms 116:8;Psalms 119:16;Proverbs 3:23;Proverbs 4:12;Proverbs 4:16;Proverbs 4:19;Proverbs 24:11;Proverbs 24:16;Proverbs 24:17;Isaiah 3:8;Isaiah 5:27;Isaiah 8:14;Isaiah 8:15;Isaiah 28:7;Isaiah 31:3;Isaiah 59:10;Isaiah 59:14;Isaiah 63:13;Jeremiah 6:21;Jeremiah 13:16;Jeremiah 18:15;Jeremiah 20:11;Jeremiah 31:9;Jeremiah 46:6;Jeremiah 46:12;Jeremiah 46:16;Jeremiah 50:32;Ezekiel 3:20;Ezekiel 7:19;Ezekiel 14:3;Ezekiel 14:4;Ezekiel 14:7;Ezekiel 21:15;Ezekiel 36:15;Ezekiel 44:12;Daniel 11:19;Daniel 11:33;Daniel 11:34;Daniel 11:35;Hosea 4:5;Hosea 5:5;Hosea 14:1;Hosea 14:9;Nahum 2:5;Nahum 3:3;Malachi 2:8;John 11:9;John 11:10;Romans 9:32;Romans 9:33;Romans 11:9;Romans 11:11;Romans 14:13;Romans 14:20;Romans 14:21;I Corinthians 1:23;I Corinthians 8:9;I Corinthians 8:13;James 3:2;I Peter 2:8;I John 2:10;Jude 1:24;Revelation of John 2:14;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1167" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Jude 1:22-23" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Jude 1:20-23" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 14:20-21" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1060" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 14:1-23" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "strength" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 4:12;Genesis 31:6;Genesis 48:2;Genesis 49:3;Exodus 15:2;Exodus 15:13;Leviticus 26:20;Numbers 11:6;Deuteronomy 3:28;Deuteronomy 21:17;Deuteronomy 33:25;Joshua 14:11;Judges 3:12;Judges 7:11;Judges 8:21;Judges 9:24;Judges 16:5;Judges 16:6;Judges 16:9;Judges 16:15;Judges 16:17;Judges 16:19;Judges 16:28;Judges 16:30;Judges 19:5;Judges 19:8;I Samuel 2:1;I Samuel 2:4;I Samuel 2:10;I Samuel 2:31;I Samuel 23:16;I Samuel 28:20;I Samuel 28:22;I Samuel 30:4;I Samuel 30:6;II Samuel 11:25;II Samuel 16:21;II Samuel 22:40;I Kings 19:8;I Kings 20:22;II Kings 9:24;II Kings 19:3;II Kings 19:26;I Chronicles 16:11;I Chronicles 16:27;I Chronicles 16:28;I Chronicles 19:13;I Chronicles 29:12;II Chronicles 11:17;II Chronicles 17:1;II Chronicles 24:13;II Chronicles 28:20;II Chronicles 32:5;Nehemiah 2:18;Nehemiah 4:10;Nehemiah 6:9;Nehemiah 8:10;Job 4:3;Job 6:11;Job 6:12;Job 9:4;Job 9:19;Job 12:16;Job 16:5;Job 16:15;Job 18:12;Job 26:2;Job 30:2;Job 36:5;Job 36:19;Job 39:11;Job 39:21;Job 40:16;Job 41:12;Job 41:22;Psalms 8:2;Psalms 10:17;Psalms 18:1;Psalms 18:32;Psalms 18:39;Psalms 21:1;Psalms 21:13;Psalms 22:15;Psalms 28:7;Psalms 28:8;Psalms 29:1;Psalms 29:11;Psalms 31:10;Psalms 32:4;Psalms 33:16;Psalms 38:10;Psalms 46:1;Psalms 59:9;Psalms 59:16;Psalms 59:17;Psalms 65:6;Psalms 68:35;Psalms 71:9;Psalms 73:26;Psalms 78:51;Psalms 81:1;Psalms 84:5;Psalms 84:7;Psalms 86:16;Psalms 88:4;Psalms 89:17;Psalms 89:21;Psalms 90:10;Psalms 93:1;Psalms 96:6;Psalms 96:7;Psalms 102:23;Psalms 104:15;Psalms 105:4;Psalms 105:36;Psalms 118:14;Psalms 119:28;Psalms 138:3;Psalms 140:7;Psalms 147:10;Psalms 147:13;Proverbs 5:10;Proverbs 8:14;Proverbs 14:4;Proverbs 20:29;Proverbs 24:5;Proverbs 24:10;Proverbs 31:3;Proverbs 31:17;Proverbs 31:25;Ecclesiastes 7:19;Ecclesiastes 10:10;Ecclesiastes 10:17;Isaiah 10:13;Isaiah 12:2;Isaiah 28:6;Isaiah 30:15;Isaiah 35:3;Isaiah 37:3;Isaiah 37:27;Isaiah 40:9;Isaiah 40:29;Isaiah 40:31;Isaiah 41:1;Isaiah 41:7;Isaiah 41:10;Isaiah 44:12;Isaiah 45:24;Isaiah 49:4;Isaiah 49:5;Isaiah 51:9;Isaiah 52:1;Isaiah 54:2;Isaiah 57:10;Isaiah 63:1;Jeremiah 16:19;Jeremiah 17:5;Jeremiah 23:14;Jeremiah 48:45;Jeremiah 51:30;Lamentations 1:6;Lamentations 1:11;Lamentations 1:14;Lamentations 1:19;Ezekiel 30:24;Ezekiel 30:25;Ezekiel 34:4;Ezekiel 34:16;Daniel 10:8;Daniel 10:16;Daniel 10:17;Daniel 10:18;Daniel 10:19;Daniel 11:1;Daniel 11:6;Daniel 11:15;Daniel 11:17;Hosea 7:9;Hosea 7:15;Amos 2:14;Amos 6:13;Micah 5:4;Nahum 1:12;Nahum 2:1;Nahum 3:9;Nahum 3:14;Habakkuk 3:19;Haggai 2:22;Zechariah 10:6;Zechariah 12:5;Mark 5:4;Mark 12:30;Mark 12:33;Luke 1:51;Luke 10:27;Luke 21:36;Luke 22:32;Luke 22:43;Acts 9:19;Acts 9:22;Acts 14:22;Acts 15:32;Acts 15:41;Acts 16:5;Acts 18:23;Acts 27:34;Romans 1:11;Romans 16:25;II Corinthians 1:8;Ephesians 3:16;Ephesians 3:18;Ephesians 6:10;Philippians 4:13;Colossians 1:11;I Timothy 1:12;II Timothy 2:1;II Timothy 4:17;Hebrews 12:12;Hebrews 13:9;I Peter 4:11;I Peter 5:10;Revelation of John 1:16;Revelation of John 3:2;Revelation of John 14:10;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1170" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Revelation of John 3:1-5" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1170" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1169" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Revelation of John 2:18-25" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1168" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1167" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "strength" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 4:12;Genesis 31:6;Genesis 48:2;Genesis 49:3;Exodus 15:2;Exodus 15:13;Leviticus 26:20;Numbers 11:6;Deuteronomy 3:28;Deuteronomy 21:17;Deuteronomy 33:25;Joshua 14:11;Judges 3:12;Judges 7:11;Judges 8:21;Judges 9:24;Judges 16:5;Judges 16:6;Judges 16:9;Judges 16:15;Judges 16:17;Judges 16:19;Judges 16:28;Judges 16:30;Judges 19:5;Judges 19:8;I Samuel 2:1;I Samuel 2:4;I Samuel 2:10;I Samuel 2:31;I Samuel 23:16;I Samuel 28:20;I Samuel 28:22;I Samuel 30:4;I Samuel 30:6;II Samuel 11:25;II Samuel 16:21;II Samuel 22:40;I Kings 19:8;I Kings 20:22;II Kings 9:24;II Kings 19:3;II Kings 19:26;I Chronicles 16:11;I Chronicles 16:27;I Chronicles 16:28;I Chronicles 19:13;I Chronicles 29:12;II Chronicles 11:17;II Chronicles 17:1;II Chronicles 24:13;II Chronicles 28:20;II Chronicles 32:5;Nehemiah 2:18;Nehemiah 4:10;Nehemiah 6:9;Nehemiah 8:10;Job 4:3;Job 6:11;Job 6:12;Job 9:4;Job 9:19;Job 12:16;Job 16:5;Job 16:15;Job 18:12;Job 26:2;Job 30:2;Job 36:5;Job 36:19;Job 39:11;Job 39:21;Job 40:16;Job 41:12;Job 41:22;Psalms 8:2;Psalms 10:17;Psalms 18:1;Psalms 18:32;Psalms 18:39;Psalms 21:1;Psalms 21:13;Psalms 22:15;Psalms 28:7;Psalms 28:8;Psalms 29:1;Psalms 29:11;Psalms 31:10;Psalms 32:4;Psalms 33:16;Psalms 38:10;Psalms 46:1;Psalms 59:9;Psalms 59:16;Psalms 59:17;Psalms 65:6;Psalms 68:35;Psalms 71:9;Psalms 73:26;Psalms 78:51;Psalms 81:1;Psalms 84:5;Psalms 84:7;Psalms 86:16;Psalms 88:4;Psalms 89:17;Psalms 89:21;Psalms 90:10;Psalms 93:1;Psalms 96:6;Psalms 96:7;Psalms 102:23;Psalms 104:15;Psalms 105:4;Psalms 105:36;Psalms 118:14;Psalms 119:28;Psalms 138:3;Psalms 140:7;Psalms 147:10;Psalms 147:13;Proverbs 5:10;Proverbs 8:14;Proverbs 14:4;Proverbs 20:29;Proverbs 24:5;Proverbs 24:10;Proverbs 31:3;Proverbs 31:17;Proverbs 31:25;Ecclesiastes 7:19;Ecclesiastes 10:10;Ecclesiastes 10:17;Isaiah 10:13;Isaiah 12:2;Isaiah 28:6;Isaiah 30:15;Isaiah 35:3;Isaiah 37:3;Isaiah 37:27;Isaiah 40:9;Isaiah 40:29;Isaiah 40:31;Isaiah 41:1;Isaiah 41:7;Isaiah 41:10;Isaiah 44:12;Isaiah 45:24;Isaiah 49:4;Isaiah 49:5;Isaiah 51:9;Isaiah 52:1;Isaiah 54:2;Isaiah 57:10;Isaiah 63:1;Jeremiah 16:19;Jeremiah 17:5;Jeremiah 23:14;Jeremiah 48:45;Jeremiah 51:30;Lamentations 1:6;Lamentations 1:11;Lamentations 1:14;Lamentations 1:19;Ezekiel 30:24;Ezekiel 30:25;Ezekiel 34:4;Ezekiel 34:16;Daniel 10:8;Daniel 10:16;Daniel 10:17;Daniel 10:18;Daniel 10:19;Daniel 11:1;Daniel 11:6;Daniel 11:15;Daniel 11:17;Hosea 7:9;Hosea 7:15;Amos 2:14;Amos 6:13;Micah 5:4;Nahum 1:12;Nahum 2:1;Nahum 3:9;Nahum 3:14;Habakkuk 3:19;Haggai 2:22;Zechariah 10:6;Zechariah 12:5;Mark 5:4;Mark 12:30;Mark 12:33;Luke 1:51;Luke 10:27;Luke 21:36;Luke 22:32;Luke 22:43;Acts 9:19;Acts 9:22;Acts 14:22;Acts 15:32;Acts 15:41;Acts 16:5;Acts 18:23;Acts 27:34;Romans 1:11;Romans 16:25;II Corinthians 1:8;Ephesians 3:16;Ephesians 3:18;Ephesians 6:10;Philippians 4:13;Colossians 1:11;I Timothy 1:12;II Timothy 2:1;II Timothy 4:17;Hebrews 12:12;Hebrews 13:9;I Peter 4:11;I Peter 5:10;Revelation of John 1:16;Revelation of John 3:2;Revelation of John 14:10;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 994" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 21:19" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "plain" "-k" "John 3:14-21" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "plain" "-k" "John 3:32-36" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "internal" "-k" "Genesis 1001" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "internal" "-k" "Genesis 1001" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1001" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1001" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1001" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1001" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1001" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "internal" "-k" "Genesis 1001" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "John 5:24" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "John 5:24" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "plain" "-k" "John 5:24" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "John 1:12" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "1Thess 5:9" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "John 3:15-16" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Eph 5:6" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "1John 5:10-13" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 5:9" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "John 8:51" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "John 10:28" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 1:17-18" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 1:17-18" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Romans 1:17-18" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "John 3:3" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "1Thess 1:10" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rev 21:8" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Thessalonians 1:9-10" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Revelation of John 21:8" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "1John 3:14-15" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "I John 3:14-15" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Num 32:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Numbers 32:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Numbers 32:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "plain" "-k" "Numbers 32:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Ps 36:9" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Gal 3:10" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Ps 49:19" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "John 6:47-54" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 8:1" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Ps 106:4-5" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rev 6:16-17" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Ps 2:12" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Heb 2:3" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 2:3" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 2:1-3" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 2:1-4" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 8:24-25" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Job 33:28" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Heb 10:29" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 10:29" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Hab 2:4" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Habakkuk 2:4" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Luke 3:6" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 976" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 4:15" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Luke 2:30" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1050" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "internal" "-k" "Genesis 1050" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 4:13-17" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "YLT" "-o" "w" "-f" "plain" "-k" "Romans 4:13-17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "end of the law" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Romans 10:4;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Gal 3:24" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 8:3-4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Matt 5:17-18" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Acts 13:38-39" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "John 1:17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Heb 10:14" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Col 2:17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 7:1-4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 3:22" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1049" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Heb 10:8-12" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "1Cor 1:30" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Rom 3:25-31" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Isa 53:11" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 53:11" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Col 2:10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Matt 3:15" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "internal" "-k" "Heb 9:7-14" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1142" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 9:13-14" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "consciences" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "I Timothy 4:2;Titus 1:15;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1123" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Timothy 4:1-5" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "consciences" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "I Timothy 4:2;Titus 1:15;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1130" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1131" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 1:13-16" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 2:1-8" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "testify that" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Acts 10:42;I John 4:14;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "works are evil" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 7:7;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 7:7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "three witnesses" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Deuteronomy 17:6;Deuteronomy 19:15;Matthew 18:16;II Corinthians 13:1;I Timothy 5:19;Hebrews 10:28;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 18:16" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 947" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1188" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Revelation of John 21:10-11" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Revelation of John 21:24-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1187" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1186" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1187" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1188" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1187" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Revelation of John 20:11-15" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "milstone" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "stone" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 2:12;Genesis 11:3;Genesis 28:11;Genesis 28:18;Genesis 28:22;Genesis 29:2;Genesis 29:3;Genesis 29:8;Genesis 29:10;Genesis 31:45;Genesis 31:46;Genesis 35:14;Genesis 49:24;Exodus 7:19;Exodus 8:26;Exodus 15:5;Exodus 15:16;Exodus 17:4;Exodus 17:12;Exodus 19:13;Exodus 20:25;Exodus 21:18;Exodus 21:28;Exodus 21:29;Exodus 21:32;Exodus 24:10;Exodus 24:12;Exodus 25:7;Exodus 28:9;Exodus 28:10;Exodus 28:11;Exodus 28:12;Exodus 28:17;Exodus 28:21;Exodus 31:5;Exodus 31:18;Exodus 34:1;Exodus 34:4;Exodus 35:9;Exodus 35:27;Exodus 35:33;Exodus 39:6;Exodus 39:7;Exodus 39:10;Exodus 39:14;Leviticus 14:40;Leviticus 14:42;Leviticus 14:43;Leviticus 14:45;Leviticus 20:2;Leviticus 20:27;Leviticus 24:14;Leviticus 24:16;Leviticus 24:23;Leviticus 26:1;Numbers 14:10;Numbers 15:35;Numbers 15:36;Numbers 33:52;Numbers 35:17;Numbers 35:23;Deuteronomy 4:13;Deuteronomy 4:28;Deuteronomy 5:22;Deuteronomy 8:9;Deuteronomy 9:9;Deuteronomy 9:10;Deuteronomy 9:11;Deuteronomy 10:1;Deuteronomy 10:3;Deuteronomy 13:10;Deuteronomy 17:5;Deuteronomy 21:21;Deuteronomy 22:21;Deuteronomy 22:24;Deuteronomy 24:6;Deuteronomy 27:2;Deuteronomy 27:4;Deuteronomy 27:5;Deuteronomy 27:6;Deuteronomy 27:8;Deuteronomy 28:36;Deuteronomy 28:64;Deuteronomy 29:17;Deuteronomy 29:23;Joshua 4:3;Joshua 4:5;Joshua 4:6;Joshua 4:7;Joshua 4:8;Joshua 4:9;Joshua 4:20;Joshua 4:21;Joshua 7:25;Joshua 7:26;Joshua 8:29;Joshua 8:31;Joshua 8:32;Joshua 10:11;Joshua 10:18;Joshua 10:27;Joshua 15:6;Joshua 18:17;Joshua 24:26;Joshua 24:27;Judges 6:26;Judges 9:5;Judges 9:18;Judges 9:53;Judges 20:16;I Samuel 6:14;I Samuel 6:15;I Samuel 6:18;I Samuel 7:12;I Samuel 14:33;I Samuel 17:40;I Samuel 17:49;I Samuel 17:50;I Samuel 20:19;I Samuel 20:41;I Samuel 25:37;II Samuel 11:21;II Samuel 12:30;II Samuel 16:6;II Samuel 16:13;II Samuel 18:17;II Samuel 20:8;I Kings 1:9;I Kings 5:15;I Kings 5:17;I Kings 5:18;I Kings 6:7;I Kings 6:18;I Kings 6:36;I Kings 7:9;I Kings 7:10;I Kings 7:11;I Kings 7:12;I Kings 8:9;I Kings 10:2;I Kings 10:10;I Kings 10:11;I Kings 10:27;I Kings 12:18;I Kings 15:22;I Kings 18:31;I Kings 18:32;I Kings 18:38;I Kings 19:6;I Kings 21:10;I Kings 21:13;I Kings 21:14;I Kings 21:15;II Kings 3:19;II Kings 3:25;II Kings 12:12;II Kings 16:17;II Kings 19:18;II Kings 22:6;I Chronicles 12:2;I Chronicles 20:2;I Chronicles 22:2;I Chronicles 22:14;I Chronicles 22:15;I Chronicles 29:2;I Chronicles 29:8;II Chronicles 1:15;II Chronicles 2:14;II Chronicles 3:6;II Chronicles 9:1;II Chronicles 9:9;II Chronicles 9:10;II Chronicles 9:27;II Chronicles 10:18;II Chronicles 16:6;II Chronicles 24:21;II Chronicles 26:14;II Chronicles 26:15;II Chronicles 32:27;II Chronicles 34:11;Ezra 5:8;Ezra 6:4;Nehemiah 4:2;Nehemiah 4:3;Nehemiah 9:11;Esther 1:6;Job 5:23;Job 6:12;Job 8:17;Job 14:19;Job 22:24;Job 28:6;Job 38:6;Job 38:30;Job 41:24;Job 41:28;Psalms 18:12;Psalms 18:13;Psalms 91:12;Psalms 102:14;Psalms 118:22;Proverbs 17:8;Proverbs 20:15;Proverbs 24:31;Proverbs 26:8;Proverbs 26:27;Proverbs 27:3;Ecclesiastes 3:5;Ecclesiastes 10:9;Song of Solomon 4:4;Isaiah 5:2;Isaiah 8:14;Isaiah 9:10;Isaiah 14:19;Isaiah 19:13;Isaiah 27:9;Isaiah 28:16;Isaiah 30:30;Isaiah 37:19;Isaiah 47:2;Isaiah 54:11;Isaiah 54:12;Isaiah 57:6;Isaiah 60:17;Isaiah 62:10;Jeremiah 2:27;Jeremiah 3:9;Jeremiah 25:10;Jeremiah 43:9;Jeremiah 43:10;Jeremiah 51:26;Jeremiah 51:63;Lamentations 3:9;Lamentations 3:53;Lamentations 4:1;Ezekiel 11:19;Ezekiel 13:11;Ezekiel 13:13;Ezekiel 16:40;Ezekiel 20:32;Ezekiel 23:47;Ezekiel 26:12;Ezekiel 27:22;Ezekiel 28:13;Ezekiel 28:14;Ezekiel 28:16;Ezekiel 36:26;Ezekiel 38:22;Ezekiel 40:42;Daniel 2:34;Daniel 2:35;Daniel 2:45;Daniel 5:4;Daniel 5:23;Daniel 6:17;Daniel 11:38;Hosea 12:11;Amos 5:11;Micah 1:6;Habakkuk 2:11;Habakkuk 2:19;Haggai 2:15;Zechariah 3:9;Zechariah 4:7;Zechariah 5:4;Zechariah 9:15;Zechariah 10:4;Zechariah 12:3;Matthew 3:9;Matthew 4:3;Matthew 4:6;Matthew 7:9;Matthew 18:6;Matthew 21:35;Matthew 21:42;Matthew 21:44;Matthew 23:37;Matthew 24:2;Matthew 27:60;Matthew 27:66;Matthew 28:2;Mark 5:5;Mark 9:42;Mark 12:10;Mark 13:1;Mark 13:2;Mark 15:46;Mark 16:3;Mark 16:4;Luke 3:8;Luke 4:3;Luke 4:11;Luke 13:34;Luke 17:2;Luke 19:40;Luke 19:44;Luke 20:6;Luke 20:17;Luke 20:18;Luke 21:5;Luke 21:6;Luke 22:41;Luke 23:53;Luke 24:2;John 2:6;John 8:5;John 8:7;John 8:59;John 10:31;John 10:32;John 10:33;John 11:8;John 11:38;John 11:39;John 11:41;John 19:13;John 20:1;Acts 4:11;Acts 5:26;Acts 7:58;Acts 14:5;Acts 14:19;Acts 17:29;Acts 19:35;Romans 9:32;Romans 9:33;I Corinthians 3:12;II Corinthians 3:3;II Corinthians 3:7;II Corinthians 11:25;Ephesians 2:20;Hebrews 11:37;Hebrews 12:20;I Peter 2:4;I Peter 2:5;I Peter 2:6;I Peter 2:7;I Peter 2:8;Revelation of John 2:17;Revelation of John 9:20;Revelation of John 16:21;Revelation of John 18:21;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 990" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 17:3-4" "#" "<==" "in-pen"
