cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 9" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 10" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 11" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 12" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 13" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 14" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 15" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 16" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 17" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 18" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 19" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 20" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 21" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 22" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 23" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 24" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 25" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 26" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 27" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 28" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 29" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 30" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 31" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 32" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 33" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 34" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 35" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 36" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8034" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 37" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3801" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8130" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 38" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 39" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 40" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 41" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3548" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 42" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 43" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "410" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 44" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 45" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 46" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 47" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 48" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 49" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 50" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 51" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 52" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 53" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 54" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 55" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 56" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 57" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 58" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 59" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 60" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 61" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 62" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 63" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6942" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 64" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 65" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4687" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 67" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 68" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 69" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 70" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8544" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 71" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 72" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 73" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 74" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 75" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 76" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 77" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 78" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 79" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 80" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 81" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "746" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3056" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2222" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3140" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "166" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2842" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5479" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5457" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4655" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "225" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "266" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4103" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5583" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1097" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1785" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "26" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5048" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "227" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "228" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3404" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3528" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4561" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2307" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "165" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1343" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1080" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1680" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "53" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "458" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2288" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5087" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5590" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1100" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2588" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "154" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1799" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1160" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 8:1" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 8:33" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "266" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1097" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1785" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5583" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "225" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3056" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "26" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5048" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "746" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "227" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "228" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5457" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3404" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3528" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4561" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2307" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "165" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "166" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2222" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1343" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1080" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1680" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "53" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "458" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2288" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5087" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5590" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1100" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2588" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "154" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1799" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1163" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5578" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3439" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2198" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3140" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4990" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5046" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5399" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1164" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4102" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5204" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1497" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1165" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5485" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1515" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3614" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1679" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5479" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1164" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1163" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2842" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4655" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4103" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5457" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1161" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1163" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:2" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4561" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:3" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:3" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:6" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "225" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:8" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "26" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:8" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "26" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:1" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5578" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5578" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:1" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5578" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5578" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "I John 4:6" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "225" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "strongs-get-wor"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1164" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1165" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1164" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1163" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1162" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6942" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8034" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 3" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3801" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 4" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 5" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 4" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 5" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 6" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 9" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 10" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 11" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 10" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 9" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 6" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "559" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5146" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "935" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8392" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3605" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7200" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6662" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2088" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1755" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3947" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "929" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7651" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "376" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "802" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8147" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1571" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5775" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8064" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2145" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5347" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2421" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2233" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "776" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5750" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3117" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4305" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "705" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3915" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4229" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "127" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3351" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6213" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6680" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8337" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3967" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8141" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3999" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4325" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1961" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4480" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7430" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2425" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8145" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2320" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6240" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4599" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7227" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8415" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1234" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "699" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6605" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1653" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6106" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8035" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2526" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3315" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7969" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4327" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7431" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3671" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6833" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1320" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "834" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7307" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5462" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1157" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7235" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5375" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7311" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1396" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3966" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1980" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1364" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2022" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8478" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3680" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2568" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "520" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4605" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1478" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8318" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8317" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "120" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2724" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "639" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5397" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4191" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "389" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7604" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2572" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7651" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7:4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7651" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5750" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3117" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4305" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4305" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "776" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "705" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3117" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "705" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3915" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4229a" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "127" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3605" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3351" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3351" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6213a" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7:4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7651" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5750" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3117" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4305" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4305" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "776" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "705" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3117" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "705" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3915" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4229a" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "127" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3605" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3351" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3351" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6213a" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7:1" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "559" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5146" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "935" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8392" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3605" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7200" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6662" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2088" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1755" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7651" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7:1" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 7" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 8" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 9" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 10" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8034" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 11" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 11" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Deuteronomy 2:22" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2:22" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Romans 12:1" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3870" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2198" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2378" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "strongs-get-wor"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Romans 12:8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3870" "#" "<==" "strongs-get-wor"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I John 1:9-10" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Deuteronomy 1:39" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Jonah 4:11" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "II Samuel 12:23" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah 7:16" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Isaiah 7:16" "#" "<==" "in-pen"
