cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 497" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Psalms 51" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "jew inwardly" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "inwardly" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Psalms 62:4;Proverbs 23:7;Matthew 7:15;Acts 10:17;Romans 2:29;Romans 8:23;" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1048" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1050" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 3:9-10" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 3:9" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1094" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1092" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 9:8" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1055" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1037" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Acts 19:2-6" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 3:14-18" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "do to be saved" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Acts 16:30;" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1034" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Acts 16:30-32" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 18:18-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "works of Abraham" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "works that Abraham did" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Abraham did" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 8:39;John 8:40;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 8:39-40" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1005" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "raise up" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 38:8;Deuteronomy 18:15;Deuteronomy 18:18;I Samuel 2:35;II Samuel 7:12;II Samuel 12:11;I Kings 14:14;I Chronicles 17:11;Isaiah 44:26;Isaiah 49:6;Isaiah 58:12;Isaiah 61:4;Jeremiah 23:5;Jeremiah 30:9;Amos 6:14;Amos 9:11;Matthew 3:9;Matthew 22:24;Mark 12:19;Luke 3:8;Luke 20:28;Acts 3:22;Acts 7:37;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 976" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 3:8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "son of Abraham" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 1:1;Luke 3:34;Luke 19:9;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 992" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 19:9-10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 19:8-10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "believe in the lord" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "II Kings 17:14;II Chronicles 20:20;Acts 16:31;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1034" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Acts 16:30-34" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1035" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "shipwreck" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "II Corinthians 11:25;I Timothy 1:19;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "to repentance" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Luke 5:32;Romans 2:4;Hebrews 6:4;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 978" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 529" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 529" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 529" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 497" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Peter 1:1-2" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1055" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "your servants" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 42:10;Genesis 42:11;Genesis 42:13;Genesis 44:7;Genesis 44:9;Genesis 44:16;Genesis 44:21;Genesis 44:23;Genesis 44:31;Genesis 46:34;Genesis 47:3;Genesis 47:4;Genesis 50:18;Exodus 5:15;Exodus 5:16;Exodus 8:3;Exodus 8:4;Exodus 8:9;Exodus 8:11;Exodus 8:21;Exodus 9:14;Exodus 9:30;Exodus 10:6;Exodus 11:8;Exodus 32:13;Numbers 31:49;Numbers 32:4;Numbers 32:5;Numbers 32:25;Numbers 32:27;Numbers 32:31;Deuteronomy 9:27;Joshua 9:8;Joshua 9:9;Joshua 9:11;Joshua 9:24;Joshua 10:6;Judges 19:19;Ruth 2:13;I Samuel 12:19;I Samuel 16:16;I Samuel 17:9;I Samuel 22:14;I Samuel 25:8;II Samuel 9:10;II Samuel 11:24;II Samuel 14:31;II Samuel 15:15;II Samuel 19:5;II Samuel 19:7;II Samuel 19:14;I Kings 1:27;I Kings 2:39;I Kings 5:6;I Kings 8:23;I Kings 8:32;I Kings 8:36;I Kings 10:8;I Kings 12:7;I Kings 20:6;I Kings 22:49;II Kings 2:16;II Kings 6:3;II Kings 10:5;II Kings 18:26;II Kings 22:9;II Chronicles 2:8;II Chronicles 2:10;II Chronicles 6:14;II Chronicles 6:23;II Chronicles 6:27;II Chronicles 9:7;II Chronicles 10:7;II Chronicles 34:16;Ezra 4:11;Ezra 9:11;Nehemiah 1:6;Nehemiah 1:10;Nehemiah 1:11;Psalms 79:2;Psalms 79:10;Psalms 89:50;Psalms 90:13;Psalms 90:16;Psalms 102:14;Psalms 102:28;Psalms 119:91;Isaiah 36:11;Isaiah 37:24;Isaiah 63:17;Jeremiah 22:2;Jeremiah 37:18;Daniel 1:12;Daniel 1:13;Daniel 2:4;Daniel 9:6;Acts 4:29;II Corinthians 4:5;Revelation of John 11:18;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1082" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 4:5" "#" "<==" "in-pen"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1016" "#" "<==" "emacs"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 19:26-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1016" "#" "<==" "emacs"
