cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "is your father" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 43:7;Leviticus 18:8;Leviticus 18:12;Ezekiel 20:27;Matthew 23:9;John 8:19;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 43:7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 8:19" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Leviticus 18:12" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 108" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 952" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5368" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3614" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3551" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4102" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "458" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3140" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "281" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 315" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 952" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5368" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3614" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3551" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4102" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "458" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3140" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "281" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 952" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5368" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3614" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3551" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4102" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "458" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3140" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3485" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "281" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:11" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans 12-16" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans 12" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Romans 12:1" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1073" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1504" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1849" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3313" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3614" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1242" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2288" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "129" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Job 23:10-12" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Job 1:21" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 3:1-4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 14:13-14" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:1" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:3" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:6" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:12" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:1" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:2" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:3" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 23:5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I Chronicles 28:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "John 15:18-27" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:1" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3340" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "907" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "266" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "908" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1410" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2570" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4442" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5204" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "40" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 3:10" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2250" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 932" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 933" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2198" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4487" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2413" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1781" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2730" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5457" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2288" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "757" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2098" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 934" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3870" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2588" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2545" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5087" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3614" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3551" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "281" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1785" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3056" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4202" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "935" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "154" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3404" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2246" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1342" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5046" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew 5:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:12" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:10" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis 1:16" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Proverbs 21:25" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Proverbs 19:24" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Proverbs 12:27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Proverbs 21:25" "#" "<==" "in-pen"
