cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:17" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:15-16" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1094" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "doers of the law" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Romans 2:13;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/src;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1048" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 2" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 3" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "milk is for" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "milk is for" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "milk" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 18:8;Genesis 32:15;Genesis 49:12;Exodus 3:8;Exodus 3:17;Exodus 13:5;Exodus 23:19;Exodus 33:3;Exodus 34:26;Leviticus 20:24;Numbers 13:27;Numbers 14:8;Numbers 16:13;Numbers 16:14;Deuteronomy 6:3;Deuteronomy 11:9;Deuteronomy 14:21;Deuteronomy 26:9;Deuteronomy 26:15;Deuteronomy 27:3;Deuteronomy 31:20;Deuteronomy 32:14;Joshua 5:6;Judges 4:19;Judges 5:25;I Samuel 6:7;I Samuel 6:10;Job 10:10;Job 21:24;Proverbs 27:27;Proverbs 30:33;Song of Solomon 4:11;Song of Solomon 5:1;Song of Solomon 5:12;Isaiah 7:22;Isaiah 28:9;Isaiah 55:1;Isaiah 60:16;Jeremiah 11:5;Jeremiah 32:22;Lamentations 4:7;Ezekiel 20:6;Ezekiel 20:15;Ezekiel 25:4;Joel 3:18;I Corinthians 3:2;I Corinthians 9:7;Hebrews 5:12;Hebrews 5:13;I Peter 2:2;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1138" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1137" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1138" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1139" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1140" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1139" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 6:1-10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1138" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Hebrews 5:9-14" "#" "<==" "in-pen"
