cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Psalms 40:6-8" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 3:12" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Genesis 4:3e280935" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Genesis 4:3-5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 4" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Acts 5:5" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Acts 5:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Acts 5:3-5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "strange" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 42:7;Exodus 12:48;Exodus 12:49;Leviticus 16:29;Leviticus 17:8;Leviticus 17:10;Leviticus 17:12;Leviticus 17:13;Leviticus 18:26;Leviticus 19:33;Leviticus 19:34;Leviticus 20:2;Leviticus 25:23;Leviticus 25:35;Leviticus 25:45;Leviticus 25:47;Numbers 9:14;Numbers 15:14;Numbers 15:15;Numbers 15:16;Numbers 15:26;Numbers 15:29;Numbers 19:10;Numbers 35:15;Deuteronomy 25:5;Deuteronomy 32:16;Joshua 20:9;I Chronicles 29:15;Job 15:19;Job 19:13;Job 19:15;Job 19:17;Psalms 54:3;Psalms 58:3;Psalms 69:8;Psalms 81:9;Psalms 109:11;Psalms 114:1;Proverbs 5:10;Proverbs 5:17;Proverbs 6:1;Proverbs 11:15;Proverbs 14:10;Proverbs 20:16;Proverbs 23:33;Proverbs 27:2;Proverbs 27:13;Ecclesiastes 6:2;Isaiah 1:4;Isaiah 17:10;Isaiah 28:11;Isaiah 28:21;Isaiah 43:12;Isaiah 61:5;Jeremiah 14:8;Lamentations 5:2;Ezekiel 14:5;Ezekiel 14:7;Ezekiel 16:32;Hosea 7:9;Hosea 8:7;Hosea 8:12;Joel 3:17;Obadiah 1:11;Matthew 25:35;Matthew 25:38;Matthew 25:43;Matthew 25:44;Matthew 27:7;John 10:5;Acts 17:20;I Corinthians 14:21;Ephesians 2:12;Ephesians 2:19;Hebrews 11:13;Hebrews 13:2;Hebrews 13:9;I Peter 4:12;III John 1:5;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 120" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 120" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Nadab" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Exodus 6:23;Exodus 24:1;Exodus 24:9;Exodus 28:1;Leviticus 10:1;Numbers 1:7;Numbers 2:3;Numbers 3:2;Numbers 3:4;Numbers 7:12;Numbers 7:17;Numbers 10:14;Numbers 26:60;Numbers 26:61;Ruth 4:19;Ruth 4:20;I Samuel 7:1;I Samuel 16:8;I Samuel 17:13;I Samuel 31:2;II Samuel 6:3;II Samuel 13:3;II Samuel 13:5;II Samuel 13:32;II Samuel 13:35;I Kings 4:11;I Kings 4:14;I Kings 14:20;I Kings 15:25;I Kings 15:27;I Kings 15:31;II Kings 10:15;II Kings 10:23;I Chronicles 2:10;I Chronicles 2:13;I Chronicles 2:28;I Chronicles 2:30;I Chronicles 6:3;I Chronicles 6:22;I Chronicles 8:30;I Chronicles 8:33;I Chronicles 9:36;I Chronicles 9:39;I Chronicles 10:2;I Chronicles 13:7;I Chronicles 15:10;I Chronicles 15:11;I Chronicles 24:1;I Chronicles 24:2;Jeremiah 35:6;Jeremiah 35:8;Jeremiah 35:10;Jeremiah 35:14;Jeremiah 35:16;Jeremiah 35:18;Jeremiah 35:19;Matthew 1:4;Luke 3:33;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 100" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 99" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1023" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1022" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1023" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Acts 5:1-5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Melchizidek" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Melch" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis" "14:18;Psalms" "110:4;Luke" "3:24;Luke" "3:28;Hebrews" "5:6;Hebrews" "5:10;Hebrews" "6:20;Hebrews" "7:1;Hebrews" "7:10;Hebrews" "7:11;Hebrews" "7:15;Hebrews" "7:17" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Melch" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Genesis" "14:18;I" "Samuel" "14:49;Psalms" "110:4;Jeremiah" "21:1;Luke" "3:24;Luke" "3:28;Hebrews" "5:6;Hebrews" "5:10;Hebrews" "6:20;Hebrews" "7:1;Hebrews" "7:10;Hebrews" "7:11;Hebrews" "7:15;Hebrews" "7:17;Hebrews" "7:21" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Melch" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Genesis" "14:18;Genesis" "14:20;Psalms" "110:4;Luke" "3:24;Luke" "3:28;Hebrews" "5:6;Hebrews" "5:10;Hebrews" "6:20;Hebrews" "7:1;Hebrews" "7:4;Hebrews" "7:6;Hebrews" "7:8;Hebrews" "7:10;Hebrews" "7:11;Hebrews" "7:15;Hebrews" "7:17" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Melch" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Genesis" "14:18;Psalms" "110:4;Luke" "3:24;Luke" "3:28;Hebrews" "5:6;Hebrews" "5:10;Hebrews" "6:20;Hebrews" "7:1;Hebrews" "7:10;Hebrews" "7:11;Hebrews" "7:15;Hebrews" "7:17" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis" "14:18;Psalms" "110:4;Luke" "3:24;Luke" "3:28;Hebrews" "5:6;Hebrews" "5:10;Hebrews" "6:20;Hebrews" "7:1;Hebrews" "7:10;Hebrews" "7:11;Hebrews" "7:15;Hebrews" "7:17;I" "Samuel" "14:49;Jeremiah" "21:1;Hebrews" "7:21;Genesis" "14:20;Hebrews" "7:4;Hebrews" "7:6;Hebrews" "7:8" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 14" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Isaac" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 17:19;Genesis 17:21;Genesis 21:3;Genesis 21:4;Genesis 21:5;Genesis 21:8;Genesis 21:10;Genesis 21:12;Genesis 22:2;Genesis 22:3;Genesis 22:6;Genesis 22:7;Genesis 22:9;Genesis 24:4;Genesis 24:14;Genesis 24:62;Genesis 24:63;Genesis 24:64;Genesis 24:66;Genesis 24:67;Genesis 25:5;Genesis 25:6;Genesis 25:9;Genesis 25:11;Genesis 25:19;Genesis 25:20;Genesis 25:21;Genesis 25:26;Genesis 25:28;Genesis 26:1;Genesis 26:6;Genesis 26:8;Genesis 26:9;Genesis 26:12;Genesis 26:16;Genesis 26:17;Genesis 26:18;Genesis 26:19;Genesis 26:20;Genesis 26:25;Genesis 26:27;Genesis 26:31;Genesis 26:32;Genesis 26:35;Genesis 27:1;Genesis 27:5;Genesis 27:20;Genesis 27:21;Genesis 27:22;Genesis 27:26;Genesis 27:27;Genesis 27:30;Genesis 27:32;Genesis 27:33;Genesis 27:37;Genesis 27:39;Genesis 27:46;Genesis 28:1;Genesis 28:5;Genesis 28:6;Genesis 28:8;Genesis 28:13;Genesis 31:18;Genesis 31:42;Genesis 31:53;Genesis 32:9;Genesis 35:12;Genesis 35:27;Genesis 35:28;Genesis 35:29;Genesis 46:1;Genesis 48:15;Genesis 48:16;Genesis 49:31;Genesis 50:24;Exodus 2:24;Exodus 3:6;Exodus 3:15;Exodus 3:16;Exodus 4:5;Exodus 6:3;Exodus 6:8;Exodus 32:13;Exodus 33:1;Leviticus 26:42;Numbers 32:11;Deuteronomy 1:8;Deuteronomy 6:10;Deuteronomy 9:5;Deuteronomy 9:27;Deuteronomy 29:13;Deuteronomy 30:20;Deuteronomy 34:4;Joshua 24:3;Joshua 24:4;I Kings 18:36;II Kings 13:23;I Chronicles 1:28;I Chronicles 1:34;I Chronicles 16:16;I Chronicles 29:18;II Chronicles 30:6;Psalms 105:9;Jeremiah 33:26;Amos 7:9;Amos 7:16;Matthew 1:2;Matthew 8:11;Matthew 22:32;Mark 12:26;Luke 3:34;Luke 13:28;Luke 20:37;Acts 3:13;Acts 7:8;Acts 7:32;Romans 9:7;Romans 9:10;Galatians 4:28;Hebrews 11:9;Hebrews 11:17;Hebrews 11:18;Hebrews 11:20;James 2:21;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 22" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "in faith" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Joshua 24:14;I Kings 2:4;I Kings 3:6;II Kings 20:3;II Chronicles 19:9;Psalms 33:4;Psalms 119:75;Isaiah 7:9;Isaiah 16:5;Isaiah 38:3;Jeremiah 32:41;Hosea 2:20;Zechariah 8:8;Acts 11:23;Romans 4:19;Romans 14:1;II Corinthians 8:7;I Timothy 2:7;I Timothy 2:15;I Timothy 4:12;Titus 2:2;Hebrews 11:13;James 1:6;James 2:5;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "faith " "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Exodus 21:8;Leviticus 5:15;Leviticus 6:2;Numbers 5:6;Numbers 5:12;Numbers 5:27;Deuteronomy 32:51;Joshua 7:1;Joshua 22:16;Joshua 22:20;Joshua 22:22;Joshua 22:31;Judges 9:15;Judges 9:16;Judges 9:19;I Chronicles 2:7;I Chronicles 5:25;I Chronicles 10:13;Ezra 10:2;Ezra 10:10;Job 39:12;Psalms 106:24;Psalms 146:6;Isaiah 26:2;Matthew 9:22;Matthew 9:29;Matthew 17:20;Matthew 21:21;Mark 5:34;Mark 10:52;Mark 11:22;Luke 7:50;Luke 8:48;Luke 17:6;Luke 17:19;Luke 18:8;Luke 18:42;Luke 22:32;Acts 3:16;Acts 6:5;Acts 14:9;Acts 14:27;Acts 20:21;Acts 24:24;Acts 26:18;Acts 27:25;Romans 1:5;Romans 1:8;Romans 1:17;Romans 3:22;Romans 3:26;Romans 3:28;Romans 3:30;Romans 4:5;Romans 4:9;Romans 4:11;Romans 4:12;Romans 4:14;Romans 4:16;Romans 4:19;Romans 4:20;Romans 4:22;Romans 5:2;Romans 10:6;Romans 10:8;Romans 10:17;Romans 12:3;Romans 14:22;Romans 14:23;I Corinthians 2:5;I Corinthians 12:9;I Corinthians 15:14;I Corinthians 15:17;II Corinthians 4:13;II Corinthians 10:15;Galatians 1:23;Galatians 2:16;Galatians 2:20;Galatians 3:7;Galatians 3:9;Galatians 3:22;Galatians 3:23;Galatians 3:25;Galatians 5:6;Ephesians 1:15;Ephesians 3:12;Ephesians 4:13;Philippians 1:27;Philippians 3:9;Colossians 1:4;Colossians 2:5;Colossians 2:12;I Thessalonians 1:3;I Thessalonians 1:8;I Thessalonians 3:6;I Thessalonians 5:8;II Thessalonians 1:3;II Thessalonians 1:4;II Thessalonians 1:11;I Timothy 1:14;I Timothy 1:19;I Timothy 2:7;I Timothy 2:15;I Timothy 3:9;I Timothy 3:13;I Timothy 4:1;I Timothy 4:6;I Timothy 5:8;I Timothy 6:10;II Timothy 1:5;II Timothy 1:13;II Timothy 2:18;II Timothy 3:15;Titus 1:1;Philemon 1:5;Philemon 1:6;Hebrews 4:2;Hebrews 6:1;Hebrews 6:12;Hebrews 10:39;Hebrews 11:1;Hebrews 11:3;Hebrews 11:4;Hebrews 11:5;Hebrews 11:6;Hebrews 11:7;Hebrews 11:8;Hebrews 11:9;Hebrews 11:11;Hebrews 11:17;Hebrews 11:20;Hebrews 11:21;Hebrews 11:22;Hebrews 11:23;Hebrews 11:24;Hebrews 11:27;Hebrews 11:28;Hebrews 11:29;Hebrews 11:30;Hebrews 11:31;Hebrews 11:33;James 1:3;James 2:1;James 2:5;James 2:14;James 2:17;James 2:18;James 2:20;James 2:22;James 2:24;James 2:26;James 5:15;I Peter 1:5;I Peter 1:21;II Peter 1:1;II Peter 1:5;Jude 1:3;Revelation of John 2:13;Revelation of John 2:19;Revelation of John 13:10;Revelation of John 14:12;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1144" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 22:5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "abstain" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Leviticus 22:2;Zechariah 7:3;Acts 15:20;Acts 15:29;Acts 21:25;Romans 14:3;Romans 14:6;I Thessalonians 4:3;I Thessalonians 5:22;I Peter 2:11;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1033" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "do not judge" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 7:24;John 12:47;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "judge" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 16:5;Genesis 18:25;Genesis 19:9;Genesis 30:6;Genesis 31:53;Genesis 49:16;Exodus 2:14;Exodus 5:21;Exodus 18:13;Exodus 18:22;Exodus 18:26;Exodus 21:22;Leviticus 19:15;Numbers 25:5;Numbers 35:24;Deuteronomy 1:16;Deuteronomy 16:18;Deuteronomy 17:9;Deuteronomy 17:12;Deuteronomy 19:17;Deuteronomy 19:18;Deuteronomy 21:2;Deuteronomy 25:1;Deuteronomy 25:2;Joshua 8:33;Joshua 23:2;Joshua 24:1;Judges 2:16;Judges 2:17;Judges 2:18;Judges 2:19;Judges 3:10;Judges 10:2;Judges 10:3;Judges 11:27;Judges 12:7;Judges 12:8;Judges 12:9;Judges 12:11;Judges 12:13;Judges 12:14;Judges 15:20;Judges 16:31;Ruth 1:1;I Samuel 2:10;I Samuel 4:18;I Samuel 7:6;I Samuel 7:15;I Samuel 7:16;I Samuel 7:17;I Samuel 8:1;I Samuel 8:2;I Samuel 8:5;I Samuel 8:6;I Samuel 8:20;I Samuel 24:12;I Samuel 24:15;II Samuel 7:7;II Samuel 7:11;II Samuel 15:4;I Kings 8:32;II Kings 23:22;I Chronicles 16:33;I Chronicles 17:6;I Chronicles 17:10;I Chronicles 23:4;I Chronicles 26:29;II Chronicles 1:2;II Chronicles 6:23;II Chronicles 19:5;II Chronicles 19:6;Ezra 4:9;Ezra 7:25;Ezra 10:14;Job 9:24;Job 11:2;Job 12:17;Job 21:22;Job 22:13;Job 23:7;Job 31:11;Job 31:28;Job 36:31;Psalms 7:8;Psalms 7:11;Psalms 9:8;Psalms 9:19;Psalms 50:4;Psalms 50:6;Psalms 58:1;Psalms 58:11;Psalms 67:4;Psalms 72:2;Psalms 75:2;Psalms 82:2;Psalms 82:8;Psalms 94:2;Psalms 96:10;Psalms 96:13;Psalms 98:9;Psalms 119:84;Psalms 141:6;Proverbs 29:14;Proverbs 31:9;Ecclesiastes 3:17;Isaiah 1:26;Isaiah 2:4;Isaiah 3:2;Isaiah 3:13;Isaiah 5:3;Isaiah 11:3;Isaiah 11:4;Isaiah 16:5;Isaiah 33:22;Isaiah 51:5;Jeremiah 5:28;Jeremiah 11:20;Jeremiah 22:16;Lamentations 3:59;Ezekiel 7:3;Ezekiel 7:8;Ezekiel 7:27;Ezekiel 11:10;Ezekiel 11:11;Ezekiel 16:38;Ezekiel 18:30;Ezekiel 20:4;Ezekiel 21:30;Ezekiel 22:2;Ezekiel 23:24;Ezekiel 23:36;Ezekiel 24:14;Ezekiel 33:20;Ezekiel 34:17;Ezekiel 34:20;Ezekiel 34:22;Ezekiel 35:11;Ezekiel 36:19;Ezekiel 44:24;Joel 3:12;Micah 4:3;Micah 5:1;Micah 7:3;Zephaniah 3:3;Matthew 5:25;Matthew 7:1;Matthew 7:2;Matthew 12:27;Luke 6:37;Luke 7:43;Luke 11:19;Luke 12:14;Luke 12:57;Luke 12:58;Luke 18:2;Luke 18:6;John 5:22;John 5:30;John 7:24;John 7:51;John 8:15;John 8:16;John 8:26;John 8:50;John 12:47;John 12:48;John 16:11;John 18:31;Acts 4:19;Acts 7:7;Acts 7:27;Acts 7:35;Acts 10:42;Acts 13:20;Acts 13:46;Acts 16:15;Acts 17:31;Acts 18:15;Acts 23:3;Acts 24:10;Romans 2:1;Romans 2:3;Romans 2:12;Romans 2:16;Romans 3:4;Romans 3:6;I Corinthians 2:15;I Corinthians 4:3;I Corinthians 4:4;I Corinthians 5:12;I Corinthians 5:13;I Corinthians 6:2;I Corinthians 6:3;I Corinthians 10:15;I Corinthians 11:13;I Corinthians 11:31;I Corinthians 11:32;I Timothy 1:12;II Timothy 4:1;II Timothy 4:8;Hebrews 10:30;Hebrews 12:23;Hebrews 13:4;James 2:4;James 2:12;James 3:1;James 4:11;James 4:12;James 5:9;I Peter 1:17;I Peter 2:23;I Peter 4:5;I Peter 4:6;Revelation of John 6:10;Revelation of John 11:18;Revelation of John 18:8;Revelation of John 19:2;Revelation of John 19:11;Revelation of John 20:4;Revelation of John 20:12;Revelation of John 20:13;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 936" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "judge .*for .*yourselves" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I" "Corinthians" "11:13" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "judge .*for .*yourselves" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "judge .*for .*yourselves" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Ezekiel" "18:30;Luke" "12:57;Acts" "4:19;I" "Corinthians" "10:15;I" "Corinthians" "11:13" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "judge .*for .*yourselves" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke" "12:57;I" "Corinthians" "10:15;I" "Corinthians" "11:13" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "I" "Corinthians" "11:13;Luke" "12:57;Acts" "4:19;I" "Corinthians" "10:15" "#" "<==" "xargs"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 11:30-32" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1049" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1050" "#" "<==" "emacs"
cd //;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 722" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "tree good" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 12:33;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 29:29" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Jeremiah 29:11" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Ephesians 2:12-13" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/docs/theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 6:9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "5:13-14" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1025" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1025" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 58" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 8-17" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 58" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 59" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 60" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 61" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 62" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 63" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 64" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 65" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 65" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 64" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 65" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5265" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "362" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3605" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5712" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3478" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "935" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4057" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5512" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "834" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "996" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5514" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2568" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6240" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3117" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8145" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2320" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3318" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "776" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4714" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3885" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4872" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "175" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "559" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4310" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5414" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4191" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3027" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3427" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5518" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1320" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "398" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3899" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7648" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2088" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6951" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7458" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2009" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4305" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8064" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5971" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3950" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1697" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5254" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "518" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1980" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8451" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8345" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3559" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4932" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6153" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3045" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1242" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7200" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3519" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8085" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8519" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4100" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7646" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7126" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1961" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1696" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6437" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "413" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6051" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7958" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5927" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3680" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4264" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7902" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5439" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1851" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2636" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3713" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "376" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "251" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4478" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "402" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6680" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6310" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3947" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6016" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1538" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4557" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5315" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "168" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6213" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3651" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7235" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4591" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4058" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3808" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5736" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2637" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "408" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3498" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4480" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5704" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7426" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8438" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "887" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7107" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8121" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2552" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4549" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8147" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "259" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5387" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5046" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1931" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4279" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7677" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6944" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7676" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "644" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1310" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5117" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4931" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7415" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4672" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7704" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8337" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7637" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "575" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3985" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8104" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4687" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8478" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4725" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7673" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7121" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8034" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1407" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2233" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3836" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2940" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6838" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1706" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4393" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1755" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6803" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5715" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "705" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8141" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7097" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3667" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6224" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "374" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:4" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:11" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:36" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:24" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:28" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8451" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8451" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8451" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8104" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4687" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 16:1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 16:36" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 16:35" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 65" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 67" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1026" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1027" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Ananias" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Acts 5:1;Acts 5:3;Acts 5:5;Acts 9:10;Acts 9:12;Acts 9:13;Acts 9:17;Acts 22:12;Acts 23:2;Acts 24:1;" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1028" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1027" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1028" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1028" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1029" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1030" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1029" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1028" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1029" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1073" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1073" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/docs/theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 13:10" "#" "<==" "in-pen"
