cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Melchizidek" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 14" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "refined" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Deuteronomy 28:54;Deuteronomy 28:56;I Chronicles 28:18;I Chronicles 29:4;Psalms 12:6;Isaiah 25:6;Isaiah 48:10;Daniel 11:35;Daniel 12:10;Revelation of John 1:15;Revelation of John 3:18;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 862" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1168" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "works.*faith" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "works faith" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "faith" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 24:27;Genesis 24:49;Genesis 32:10;Exodus 21:8;Exodus 34:6;Leviticus 5:15;Leviticus 6:2;Numbers 5:6;Numbers 5:12;Numbers 5:27;Numbers 12:7;Numbers 14:33;Deuteronomy 7:9;Deuteronomy 28:1;Deuteronomy 32:4;Deuteronomy 32:20;Deuteronomy 32:51;Joshua 2:14;Joshua 7:1;Joshua 22:16;Joshua 22:20;Joshua 22:22;Joshua 22:31;Joshua 24:14;Judges 5:15;Judges 9:15;Judges 9:16;Judges 9:19;Judges 19:2;I Samuel 2:9;I Samuel 2:35;I Samuel 12:24;I Samuel 22:14;I Samuel 26:23;II Samuel 2:6;II Samuel 15:20;II Samuel 20:19;I Kings 2:4;I Kings 3:6;II Kings 20:3;I Chronicles 2:7;I Chronicles 5:25;I Chronicles 9:1;I Chronicles 10:13;II Chronicles 12:2;II Chronicles 19:9;II Chronicles 26:16;II Chronicles 28:19;II Chronicles 28:22;II Chronicles 29:6;II Chronicles 29:19;II Chronicles 30:7;II Chronicles 31:12;II Chronicles 31:15;II Chronicles 31:18;II Chronicles 31:20;II Chronicles 32:1;II Chronicles 33:19;II Chronicles 34:12;II Chronicles 36:14;Ezra 9:2;Ezra 9:4;Ezra 10:2;Ezra 10:6;Ezra 10:10;Nehemiah 1:8;Nehemiah 7:2;Nehemiah 9:8;Nehemiah 9:33;Job 39:12;Psalms 12:1;Psalms 25:10;Psalms 26:3;Psalms 30:9;Psalms 31:5;Psalms 31:23;Psalms 33:4;Psalms 36:5;Psalms 37:3;Psalms 40:10;Psalms 40:11;Psalms 50:5;Psalms 54:5;Psalms 57:3;Psalms 57:10;Psalms 61:7;Psalms 69:13;Psalms 71:22;Psalms 73:27;Psalms 78:8;Psalms 78:37;Psalms 79:2;Psalms 85:10;Psalms 85:11;Psalms 86:15;Psalms 88:11;Psalms 89:1;Psalms 89:2;Psalms 89:5;Psalms 89:8;Psalms 89:14;Psalms 89:24;Psalms 89:33;Psalms 89:37;Psalms 89:49;Psalms 91:4;Psalms 92:2;Psalms 96:13;Psalms 98:3;Psalms 100:5;Psalms 101:6;Psalms 106:24;Psalms 108:4;Psalms 111:7;Psalms 111:8;Psalms 115:1;Psalms 117:2;Psalms 119:30;Psalms 119:75;Psalms 119:90;Psalms 119:13;Psalms 119:15;Psalms 138:2;Psalms 143:1;Psalms 145:13;Psalms 146:6;Proverbs 3:3;Proverbs 12:22;Proverbs 13:17;Proverbs 14:5;Proverbs 14:22;Proverbs 16:6;Proverbs 20:6;Proverbs 20:28;Proverbs 25:13;Proverbs 27:6;Proverbs 28:20;Proverbs 29:14;Isaiah 1:21;Isaiah 1:26;Isaiah 7:9;Isaiah 11:5;Isaiah 16:5;Isaiah 25:1;Isaiah 26:2;Isaiah 38:3;Isaiah 38:18;Isaiah 38:19;Isaiah 42:3;Isaiah 49:7;Isaiah 61:8;Jeremiah 3:6;Jeremiah 3:8;Jeremiah 3:11;Jeremiah 3:12;Jeremiah 3:14;Jeremiah 3:22;Jeremiah 23:28;Jeremiah 31:3;Jeremiah 31:22;Jeremiah 32:41;Jeremiah 42:5;Jeremiah 49:4;Lamentations 3:23;Ezekiel 14:13;Ezekiel 15:8;Ezekiel 18:9;Daniel 6:4;Hosea 2:20;Hosea 4:1;Hosea 5:7;Hosea 6:7;Hosea 11:12;Micah 7:20;Habakkuk 2:4;Zechariah 8:3;Zechariah 8:8;Malachi 2:10;Malachi 2:11;Malachi 2:14;Malachi 2:15;Malachi 2:16;Matthew 6:30;Matthew 8:10;Matthew 8:26;Matthew 9:2;Matthew 9:22;Matthew 9:29;Matthew 14:31;Matthew 15:28;Matthew 16:8;Matthew 17:17;Matthew 17:20;Matthew 21:21;Matthew 21:22;Matthew 23:23;Matthew 24:45;Matthew 25:21;Matthew 25:23;Mark 2:5;Mark 4:40;Mark 5:34;Mark 9:19;Mark 10:52;Mark 11:22;Luke 5:20;Luke 7:9;Luke 7:50;Luke 8:25;Luke 8:48;Luke 9:41;Luke 12:28;Luke 12:42;Luke 12:46;Luke 16:10;Luke 16:11;Luke 16:12;Luke 17:5;Luke 17:6;Luke 17:19;Luke 18:8;Luke 18:42;Luke 19:17;Luke 22:32;Acts 3:16;Acts 6:5;Acts 6:7;Acts 11:23;Acts 11:24;Acts 13:8;Acts 14:9;Acts 14:22;Acts 14:27;Acts 15:9;Acts 16:5;Acts 16:15;Acts 20:21;Acts 24:24;Acts 26:18;Acts 27:25;Romans 1:5;Romans 1:8;Romans 1:12;Romans 1:17;Romans 1:31;Romans 3:3;Romans 3:22;Romans 3:25;Romans 3:26;Romans 3:27;Romans 3:28;Romans 3:30;Romans 3:31;Romans 4:5;Romans 4:9;Romans 4:11;Romans 4:12;Romans 4:13;Romans 4:14;Romans 4:16;Romans 4:19;Romans 4:20;Romans 4:22;Romans 5:1;Romans 5:2;Romans 9:30;Romans 9:32;Romans 10:6;Romans 10:8;Romans 10:17;Romans 11:20;Romans 12:3;Romans 12:6;Romans 14:1;Romans 14:22;Romans 14:23;Romans 16:26;I Corinthians 1:9;I Corinthians 2:5;I Corinthians 4:17;I Corinthians 10:13;I Corinthians 12:9;I Corinthians 13:2;I Corinthians 13:13;I Corinthians 15:14;I Corinthians 15:17;I Corinthians 16:13;II Corinthians 1:18;II Corinthians 1:24;II Corinthians 4:13;II Corinthians 5:7;II Corinthians 8:7;II Corinthians 10:15;II Corinthians 13:5;Galatians 1:23;Galatians 2:16;Galatians 2:20;Galatians 3:2;Galatians 3:5;Galatians 3:7;Galatians 3:8;Galatians 3:9;Galatians 3:11;Galatians 3:12;Galatians 3:14;Galatians 3:22;Galatians 3:23;Galatians 3:24;Galatians 3:25;Galatians 3:26;Galatians 5:5;Galatians 5:6;Galatians 5:22;Galatians 6:10;Ephesians 1:1;Ephesians 1:15;Ephesians 2:8;Ephesians 3:12;Ephesians 3:17;Ephesians 4:5;Ephesians 4:13;Ephesians 6:16;Ephesians 6:21;Ephesians 6:23;Philippians 1:25;Philippians 1:27;Philippians 2:17;Philippians 3:9;Colossians 1:2;Colossians 1:4;Colossians 1:7;Colossians 1:23;Colossians 2:5;Colossians 2:7;Colossians 2:12;Colossians 4:7;Colossians 4:9;I Thessalonians 1:3;I Thessalonians 1:8;I Thessalonians 3:2;I Thessalonians 3:5;I Thessalonians 3:6;I Thessalonians 3:7;I Thessalonians 3:10;I Thessalonians 5:8;I Thessalonians 5:24;II Thessalonians 1:3;II Thessalonians 1:4;II Thessalonians 1:11;II Thessalonians 3:2;II Thessalonians 3:3;I Timothy 1:2;I Timothy 1:4;I Timothy 1:5;I Timothy 1:12;I Timothy 1:14;I Timothy 1:19;I Timothy 2:7;I Timothy 2:15;I Timothy 3:9;I Timothy 3:11;I Timothy 3:13;I Timothy 4:1;I Timothy 4:6;I Timothy 4:12;I Timothy 5:8;I Timothy 5:12;I Timothy 6:10;I Timothy 6:11;I Timothy 6:12;I Timothy 6:21;II Timothy 1:5;II Timothy 1:13;II Timothy 2:2;II Timothy 2:13;II Timothy 2:18;II Timothy 2:22;II Timothy 3:8;II Timothy 3:10;II Timothy 3:15;II Timothy 4:7;Titus 1:1;Titus 1:4;Titus 1:13;Titus 2:2;Titus 2:10;Titus 3:15;Philemon 1:5;Philemon 1:6;Hebrews 2:17;Hebrews 3:2;Hebrews 3:5;Hebrews 3:6;Hebrews 4:2;Hebrews 6:1;Hebrews 6:12;Hebrews 10:22;Hebrews 10:23;Hebrews 10:38;Hebrews 10:39;Hebrews 11:1;Hebrews 11:3;Hebrews 11:4;Hebrews 11:5;Hebrews 11:6;Hebrews 11:7;Hebrews 11:8;Hebrews 11:9;Hebrews 11:11;Hebrews 11:13;Hebrews 11:17;Hebrews 11:20;Hebrews 11:21;Hebrews 11:22;Hebrews 11:23;Hebrews 11:24;Hebrews 11:27;Hebrews 11:28;Hebrews 11:29;Hebrews 11:30;Hebrews 11:31;Hebrews 11:33;Hebrews 11:39;Hebrews 12:2;Hebrews 13:7;James 1:3;James 1:6;James 2:1;James 2:5;James 2:14;James 2:17;James 2:18;James 2:20;James 2:22;James 2:24;James 2:26;James 5:15;I Peter 1:5;I Peter 1:7;I Peter 1:9;I Peter 1:21;I Peter 4:19;I Peter 5:9;I Peter 5:12;II Peter 1:1;II Peter 1:5;I John 1:9;I John 5:4;III John 1:5;Jude 1:3;Jude 1:20;Revelation of John 1:5;Revelation of John 2:10;Revelation of John 2:13;Revelation of John 2:19;Revelation of John 3:14;Revelation of John 13:10;Revelation of John 14:12;Revelation of John 17:14;Revelation of John 19:11;Revelation of John 21:8;" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1169" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1169" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 778" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "commandments" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 26:5;Exodus 15:26;Exodus 16:28;Exodus 20:6;Exodus 34:28;Leviticus 4:2;Leviticus 4:13;Leviticus 4:22;Leviticus 4:27;Leviticus 5:17;Leviticus 22:31;Leviticus 26:3;Leviticus 26:14;Leviticus 26:15;Leviticus 27:34;Numbers 15:22;Numbers 15:39;Numbers 15:40;Numbers 36:13;Deuteronomy 4:2;Deuteronomy 4:13;Deuteronomy 4:40;Deuteronomy 5:10;Deuteronomy 5:29;Deuteronomy 6:2;Deuteronomy 6:17;Deuteronomy 7:9;Deuteronomy 8:2;Deuteronomy 8:6;Deuteronomy 8:11;Deuteronomy 10:4;Deuteronomy 10:13;Deuteronomy 11:1;Deuteronomy 11:13;Deuteronomy 11:27;Deuteronomy 11:28;Deuteronomy 13:4;Deuteronomy 13:18;Deuteronomy 26:13;Deuteronomy 26:17;Deuteronomy 26:18;Deuteronomy 27:10;Deuteronomy 28:1;Deuteronomy 28:9;Deuteronomy 28:13;Deuteronomy 28:15;Deuteronomy 28:45;Deuteronomy 30:8;Deuteronomy 30:10;Deuteronomy 30:16;Joshua 22:5;Judges 2:17;Judges 3:4;I Samuel 15:11;I Kings 2:3;I Kings 3:14;I Kings 6:12;I Kings 8:58;I Kings 8:61;I Kings 9:6;I Kings 11:34;I Kings 11:38;I Kings 14:8;I Kings 18:18;II Kings 17:13;II Kings 17:16;II Kings 17:19;II Kings 18:6;II Kings 23:3;I Chronicles 28:7;I Chronicles 28:8;I Chronicles 29:19;II Chronicles 7:19;II Chronicles 17:4;II Chronicles 24:20;II Chronicles 31:21;II Chronicles 34:31;Ezra 7:11;Ezra 9:10;Ezra 9:14;Nehemiah 1:5;Nehemiah 1:7;Nehemiah 1:9;Nehemiah 9:13;Nehemiah 9:14;Nehemiah 9:16;Nehemiah 9:29;Nehemiah 9:34;Nehemiah 10:29;Psalms 78:7;Psalms 89:31;Psalms 103:18;Psalms 112:1;Psalms 119:6;Psalms 119:10;Psalms 119:19;Psalms 119:21;Psalms 119:32;Psalms 119:35;Psalms 119:47;Psalms 119:48;Psalms 119:60;Psalms 119:66;Psalms 119:73;Psalms 119:86;Psalms 119:11;Psalms 119:12;Psalms 119:13;Psalms 119:14;Psalms 119:15;Psalms 119:16;Psalms 119:17;Psalms 119:17;Proverbs 2:1;Proverbs 3:1;Proverbs 4:4;Proverbs 7:1;Proverbs 7:2;Proverbs 10:8;Ecclesiastes 12:13;Isaiah 48:18;Daniel 9:4;Daniel 9:5;Matthew 5:19;Matthew 15:9;Matthew 19:17;Matthew 22:40;Mark 7:7;Mark 10:19;Luke 1:6;Luke 18:20;John 14:15;John 14:21;John 15:10;Romans 10:5;Romans 13:9;I Corinthians 7:19;Ephesians 2:15;I John 2:3;I John 2:4;I John 3:22;I John 3:24;I John 5:2;I John 5:3;II John 1:6;Revelation of John 12:17;Revelation of John 14:12;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 26" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 70" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 65" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 84" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 65" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "instructions" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Deuteronomy 17:11;Acts 15:24;Acts 23:31;I Corinthians 11:17;Colossians 4:10;I Thessalonians 4:2;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "instructions" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus" "16:28;Esther" "9:26;Esther" "9:31;Matthew" "11:1;Mark" "16:20;I" "Corinthians" "7:10;Colossians" "4:10" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "instructions" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "instructions" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "Exodus" "16:4;Exodus" "16:28;I" "Samuel" "15:11;I" "Samuel" "15:13;I" "Samuel" "15:24;II" "Kings" "16:11;I" "Chronicles" "23:27;II" "Chronicles" "35:4;Ezra" "5:5;Esther" "9:26;Zechariah" "3:7;Matthew" "10:5;Luke" "12:47;Acts" "1:2;Acts" "17:15;I" "Corinthians" "11:17;I" "Corinthians" "11:34;Colossians" "4:10;I" "Thessalonians" "4:2;II" "Thessalonians" "3:14;I" "Timothy" "5:7;Hebrews" "11:22" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "instructions" "#" "<==" "diatheke-regex-"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy" "17:11;Acts" "15:24;Acts" "23:31;I" "Corinthians" "11:17;Colossians" "4:10;I" "Thessalonians" "4:2" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus" "16:28;Esther" "9:26;Esther" "9:31;Matthew" "11:1;Mark" "16:20;I" "Corinthians" "7:10;Colossians" "4:10;Exodus" "16:4;I" "Samuel" "15:11;I" "Samuel" "15:13;I" "Samuel" "15:24;II" "Kings" "16:11;I" "Chronicles" "23:27;II" "Chronicles" "35:4;Ezra" "5:5;Zechariah" "3:7;Matthew" "10:5;Luke" "12:47;Acts" "1:2;Acts" "17:15;I" "Corinthians" "11:17;I" "Corinthians" "11:34;I" "Thessalonians" "4:2;II" "Thessalonians" "3:14;I" "Timothy" "5:7;Hebrews" "11:22;Deuteronomy" "17:11;Acts" "15:24;Acts" "23:31" "#" "<==" "xargs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 66" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5265" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "362" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3605" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5712" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1121" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3478" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "935" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4057" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5512" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "834" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "996" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5514" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2568" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6240" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3117" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8145" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2320" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3318" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "776" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4714" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3885" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5921" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4872" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "175" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "559" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4310" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5414" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4191" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3068" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3027" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3427" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5518" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1320" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "398" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3899" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7648" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2088" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6951" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7458" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2009" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4305" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8064" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5971" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3950" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1697" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5254" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "518" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1980" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8451" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8345" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3559" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4932" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6153" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3045" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1242" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7200" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3519" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8085" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8519" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4100" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7646" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7126" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6440" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1961" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1696" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6437" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "413" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6051" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "430" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7958" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5927" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3680" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4264" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7902" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5439" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1851" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2636" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3713" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "376" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "251" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4478" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "402" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6680" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6310" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3947" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6016" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1538" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4557" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5315" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "168" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6213" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3651" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7235" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4591" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4058" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3808" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5736" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2637" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "408" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3498" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4480" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5704" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7426" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8438" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "887" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7107" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8121" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2552" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4549" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8147" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "259" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5387" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5046" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1931" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4279" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7677" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6944" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7676" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "644" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1310" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5117" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4931" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7415" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4672" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7704" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8337" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7637" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "575" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3985" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8104" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4687" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8478" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4725" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7673" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1004" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7121" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8034" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1407" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2233" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3836" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "2940" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6838" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1706" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "4393" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "1755" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6803" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "5715" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "705" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "8141" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "7097" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "3667" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "6224" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsHebrew" "-o" "w" "-f" "internal" "-k" "374" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:9" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Exodus 16:16" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "light of the world" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 5:14;John 8:12;John 9:5;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "divorce" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Leviticus 21:7;Leviticus 21:14;Leviticus 22:13;Numbers 30:9;Deuteronomy 22:19;Deuteronomy 22:29;Deuteronomy 24:1;Deuteronomy 24:3;Isaiah 50:1;Jeremiah 3:1;Jeremiah 3:8;Ezekiel 44:22;Malachi 2:16;Matthew 1:19;Matthew 5:31;Matthew 5:32;Matthew 19:3;Matthew 19:7;Matthew 19:8;Matthew 19:9;Mark 10:2;Mark 10:4;Mark 10:11;Mark 10:12;Luke 16:18;I Corinthians 7:11;I Corinthians 7:12;I Corinthians 7:13;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 948" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "love your enemies" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 5:44;Luke 6:27;Luke 6:35;" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 9:6-7" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 2:10" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1025" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 593" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 1:6,7" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 3:23" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 22:37-39" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Kings 3:17" "#" "<==" "in-pen"
