cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "the lord is my shepherd" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Psalms 23:1;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 501" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 501" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1115" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1011" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1110" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 497" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 662" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 935" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1129" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Timothy 4:18" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1181" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1180" "#" "<==" "emacs"
