cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Jehovah" "#" "<==" "diatheke-regex-"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Jehovah" "#" "<==" "diatheke-regex-"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "Genesis" "22:14;Exodus" "6:3;Exodus" "17:15;Judges" "6:24;Psalms" "83:18;Isaiah" "12:2;Isaiah" "26:4" "#" "<==" "xargs"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Jehovah" "#" "<==" "diatheke-regex-"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "none" "(engbsb2020eb)" "#" "<==" "xargs"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "ESV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "Jehovah" "#" "<==" "diatheke-regex-"
cd /root/.emacs.d/host/pen.el/scripts/racket-scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "none" "(ESV)" "#" "<==" "xargs"
cd /root/.emacs.d/host/pen.el/scripts/bible-mode-scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Nahum 1:7" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/bible-mode-scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Colossians 1:5" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts/bible-mode-scripts;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Zechariah 13:7" "#" "<==" "in-pen"
