cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 4:11-15" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1120" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Timothy 1:3-5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Timothy 1:18-20" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "unseen" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Psalms 77:19;II Corinthians 4:18;Hebrews 11:7;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 4:18" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 12:1-2" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Peter 3:21" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 8:4" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1164" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 5:9-13" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 5:20" "#" "<==" "in-pen"
