cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1148" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4102" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1391" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2424" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5547" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1438" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4190" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2889" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "932" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3739" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "25" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2570" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5055" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3551" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4160" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "266" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3956" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2919" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2041" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1410" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4982" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1515" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1140" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1097" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3962" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2379" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5048" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1343" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Galatians" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Genesis" "#" "<==" "in-pen"
cd /;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalms 91:1" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "James 2" "#" "<==" "in-pen"
