cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Leviticus 18:24-25" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 19:4-6" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "adultery" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Exodus 20:14;Leviticus 20:10;Deuteronomy 5:18;Proverbs 6:32;Jeremiah 3:9;Jeremiah 5:7;Jeremiah 7:9;Jeremiah 23:14;Jeremiah 29:23;Ezekiel 16:38;Ezekiel 23:37;Ezekiel 23:43;Hosea 2:2;Hosea 4:2;Hosea 4:13;Hosea 4:14;Matthew 5:27;Matthew 5:28;Matthew 5:32;Matthew 15:19;Matthew 19:9;Matthew 19:18;Mark 7:21;Mark 10:11;Mark 10:12;Mark 10:19;Luke 16:18;Luke 18:20;John 8:3;John 8:4;Romans 2:22;Romans 13:9;James 2:11;II Peter 2:14;Revelation of John 2:22;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 5:32" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 19:39-40" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 19:38-40" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 19:37-40" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "overcome the world" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 16:33;I John 5:4;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 16:33" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1164" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 5:3-5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "give us all things" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Romans 8:32;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1054" "#" "<==" "emacs"
