cd /root/.emacs.d/host/pen.el;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Matthew" "6:14-15" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Psalm" "141:3" "#" "<==" "xargs"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Psalms 141:3" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 6:14-15" "#" "<==" "in-pen"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1107" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1069" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1069" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1070" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1069" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 11:11" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 7:10-17" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 7:15" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 7:12-15" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 8:2" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 8:1-2" "#" "<==" "in-pen"
