cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 42:2" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 42:3" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 42:6" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 5:8-10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 6:5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 8:8" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 7:24-29" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 10:4-5" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Isaiah 41:10" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 20:4" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 8:38-39" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 20:19" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 20:19-20" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Exodus 20:18-20" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 488" "#" "<==" "emacs"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Psalms 10:1" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Psalms 10:12" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Psalms 10:10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1077" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Cephas" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 1:42;I Corinthians 1:12;I Corinthians 3:22;I Corinthians 9:5;I Corinthians 15:5;Galatians 1:18;Galatians 2:9;Galatians 2:11;Galatians 2:14;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:1-5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:6-9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:11-15" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:16-21" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "for freedom" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Galatians 5:1;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 5:1" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 5:21" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 5:19" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:21" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:20" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:16-19" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Galatians 2:16" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Galatians 2:13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "his own" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1:27;Genesis 5:3;Genesis 9:6;Genesis 10:5;Genesis 30:40;Genesis 40:5;Genesis 46:26;Exodus 18:27;Exodus 22:5;Leviticus 7:30;Leviticus 14:15;Leviticus 14:26;Leviticus 21:14;Leviticus 25:41;Leviticus 25:50;Numbers 1:52;Numbers 2:2;Numbers 27:3;Numbers 32:42;Deuteronomy 3:14;Deuteronomy 4:20;Deuteronomy 4:37;Deuteronomy 12:8;Deuteronomy 20:8;Deuteronomy 24:16;Joshua 2:19;Joshua 20:6;Joshua 24:30;Judges 8:29;Judges 8:30;Judges 17:6;Judges 21:25;I Samuel 3:2;I Samuel 13:14;I Samuel 18:1;I Samuel 18:3;I Samuel 20:17;I Samuel 25:39;I Samuel 28:3;I Samuel 31:4;II Samuel 4:11;II Samuel 12:4;II Samuel 12:20;II Samuel 14:24;II Samuel 17:23;II Samuel 18:17;II Samuel 18:18;II Samuel 19:8;II Samuel 19:39;II Samuel 23:21;I Kings 1:49;I Kings 2:32;I Kings 2:34;I Kings 3:1;I Kings 7:1;I Kings 7:8;I Kings 8:32;I Kings 8:38;I Kings 9:15;I Kings 11:19;I Kings 12:33;I Kings 13:30;I Kings 15:15;I Kings 17:19;II Kings 2:12;II Kings 12:18;II Kings 14:6;II Kings 18:31;II Kings 19:7;II Kings 23:30;I Chronicles 10:4;I Chronicles 11:23;I Chronicles 12:28;II Chronicles 6:23;II Chronicles 6:29;II Chronicles 7:11;II Chronicles 8:1;II Chronicles 11:15;II Chronicles 15:18;II Chronicles 25:4;II Chronicles 31:3;II Chronicles 32:21;Ezra 2:1;Nehemiah 3:23;Nehemiah 3:28;Nehemiah 3:29;Esther 1:22;Esther 2:7;Esther 2:15;Esther 9:25;Job 2:11;Job 14:22;Job 18:7;Job 18:8;Job 20:7;Job 32:1;Psalms 7:16;Psalms 15:4;Psalms 36:2;Psalms 52:7;Psalms 69:33;Psalms 135:4;Proverbs 11:5;Proverbs 11:29;Proverbs 12:15;Proverbs 15:27;Proverbs 16:2;Proverbs 18:1;Proverbs 19:8;Proverbs 20:6;Proverbs 21:2;Proverbs 22:16;Proverbs 26:5;Proverbs 26:6;Proverbs 26:12;Proverbs 26:16;Proverbs 26:17;Proverbs 28:10;Proverbs 28:11;Proverbs 28:26;Proverbs 29:24;Ecclesiastes 4:5;Ecclesiastes 4:14;Isaiah 9:20;Isaiah 13:14;Isaiah 14:18;Isaiah 17:8;Isaiah 36:16;Isaiah 37:7;Isaiah 47:15;Isaiah 53:6;Isaiah 56:11;Isaiah 57:17;Isaiah 59:16;Jeremiah 8:6;Jeremiah 23:17;Jeremiah 27:7;Jeremiah 31:30;Jeremiah 50:16;Jeremiah 51:9;Ezekiel 32:10;Ezekiel 33:4;Ezekiel 46:18;Daniel 6:17;Daniel 8:24;Daniel 8:25;Daniel 11:9;Daniel 11:19;Daniel 11:28;Micah 7:6;Habakkuk 2:5;Habakkuk 2:6;Habakkuk 2:18;Habakkuk 3:14;Haggai 1:9;Matthew 9:1;Matthew 10:36;Matthew 13:57;Matthew 27:31;Matthew 27:60;Mark 4:34;Mark 6:4;Mark 15:20;Luke 2:3;Luke 10:34;Luke 11:21;Luke 14:26;Luke 14:27;Luke 22:71;John 1:11;John 1:41;John 4:44;John 5:18;John 5:19;John 5:43;John 7:18;John 7:53;John 8:44;John 10:3;John 10:4;John 11:51;John 13:1;John 16:13;John 16:32;John 19:17;John 19:27;Acts 1:7;Acts 1:25;Acts 2:6;Acts 2:8;Acts 4:32;Acts 13:36;Acts 20:28;Acts 21:11;Acts 28:30;Romans 4:19;Romans 8:3;Romans 8:32;Romans 14:4;Romans 14:5;I Corinthians 6:18;I Corinthians 7:2;I Corinthians 7:4;I Corinthians 7:7;I Corinthians 9:7;I Corinthians 10:24;I Corinthians 11:21;I Corinthians 15:23;II Corinthians 8:17;Galatians 6:4;Galatians 6:5;Galatians 6:8;Ephesians 4:28;Ephesians 5:29;Philippians 2:4;Philippians 3:12;I Thessalonians 2:12;I Thessalonians 4:4;I Timothy 3:4;I Timothy 3:5;II Timothy 1:9;Titus 2:14;Titus 3:5;Hebrews 5:3;Hebrews 7:27;Hebrews 9:12;Hebrews 9:25;Hebrews 13:12;James 1:14;James 1:18;I Peter 2:9;II Peter 1:3;II Peter 2:16;I John 3:12;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1106" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 3:12" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 3:11" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 3:10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 3:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 3:8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 3:8-12" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 3:15" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Philippians 3:17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "use your freedom" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Galatians 5:13;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 5:13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "love one another" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 13:34;John 15:12;John 15:17;Romans 12:10;I Thessalonians 4:9;I Peter 1:22;I John 3:11;I John 3:23;I John 4:7;I John 4:11;I John 4:12;II John 1:5;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1093" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Galatians 2:19" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "that you may have life" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "John 5:40;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "that you may live" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 46:34;Leviticus 25:18;Deuteronomy 4:1;Deuteronomy 4:40;Deuteronomy 5:33;Deuteronomy 8:1;Deuteronomy 16:20;Deuteronomy 30:6;Deuteronomy 30:16;Deuteronomy 30:19;Deuteronomy 30:20;II Kings 18:32;Isaiah 55:3;Jeremiah 35:7;Amos 5:4;Amos 5:6;Amos 5:14;Ephesians 6:3;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 30:16" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 30:19" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 30:20" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 6:12" "#" "<==" "in-pen"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "Romans 6:12-13" "#" "<==" "in-pen"
