cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "tree good" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 12:33;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 12:33-35" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 12:33-36" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 12:33-37" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 12:33-39" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "cannot produce" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "bad fruit" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 7:17;Matthew 7:18;Luke 6:43;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 979" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 6:43-45" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "own eye" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Numbers 15:39;Deuteronomy 12:8;Judges 17:6;Judges 21:25;I Samuel 15:17;I Kings 1:48;I Kings 10:7;II Kings 7:2;II Kings 7:19;II Chronicles 9:6;II Chronicles 29:8;Job 21:20;Job 32:1;Psalms 36:2;Proverbs 3:7;Proverbs 12:15;Proverbs 16:2;Proverbs 21:2;Proverbs 26:5;Proverbs 26:12;Proverbs 26:16;Proverbs 28:11;Proverbs 30:12;Isaiah 5:21;Zechariah 9:8;Malachi 1:5;Matthew 7:3;Matthew 7:4;Matthew 7:5;Luke 6:41;Luke 6:42;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 979" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 6:41-42" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 980" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 979" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 6:46-49" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 941" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Matthew 12:48-50" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "every mouth" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "I Kings 19:18;Isaiah 9:17;Romans 3:19;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1049" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 3:19-25" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Romans 3:14-19" "#" "<==" "in-pen"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "light has come" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Isaiah 60:1;John 3:19;" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1000" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 3:16-21" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "lawless deed" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Romans 4:7;Hebrews 10:17;II Peter 2:8;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "lawlessness" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 7:23;Matthew 23:28;Matthew 24:12;Romans 6:19;II Corinthians 6:14;II Thessalonians 2:3;II Thessalonians 2:7;Titus 2:14;I John 3:4;" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1131" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1132" "#" "<==" "emacs"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 2:11-14" "#" "<==" "in-pen"
cd /root/.emacs.d/host/pen.el/scripts;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Titus 3:4-7" "#" "<==" "in-pen"
