cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1123" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1123" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "believed in vain" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "I Corinthians 15:2;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1077" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 15:17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 15:1-17" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "NASB" "-s" "regex" "-o" "w" "-f" "plain" "-k" "masquerades" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "NASB" "-o" "w" "-f" "plain" "-k" "none" "(NASB)" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "KJV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "masquerades" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "none" "(KJV)" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-s" "regex" "-o" "w" "-f" "plain" "-k" "masquerades" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "engbsb2020eb" "-o" "w" "-f" "plain" "-k" "II" "Corinthians" "11:14" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "regex" "-o" "w" "-f" "plain" "-k" "masquerades" "#" "<==" "diatheke-regex-"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "none" "(ESV)" "#" "<==" "xargs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1089" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1088" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1087" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1086" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1087" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1088" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1089" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1090" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1091" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1090" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1089" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1088" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1087" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1086" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1087" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1088" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1089" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1090" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1089" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1089" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1090" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1091" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "internal" "-k" "Genesis 1092" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "angel of light" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "II Corinthians 11:14;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1089" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "system" "-o" "w" "-f" "internal" "-k" "modulelist" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "YLT" "-o" "w" "-f" "internal" "-k" "Genesis 1089" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1077" "#" "<==" "emacs"
cd /root/.pen/documents/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1077" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 15:2" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "KJV" "-o" "w" "-f" "plain" "-k" "I Corinthians 15:1-2" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 15:1-2" "#" "<==" "in-pen"
