cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 934" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4434" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "4151" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3772" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3107" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "3996" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "1518" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "2316" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "StrongsGreek" "-o" "w" "-f" "internal" "-k" "5207" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 934" "#" "<==" "emacs"
cd /root/programs/tmux/capture;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 905" "#" "<==" "emacs"
cd /root/programs/tmux/capture;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 732" "#" "<==" "emacs"
cd /root/programs/tmux/capture;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 905" "#" "<==" "emacs"
cd /root/programs/tmux/capture;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 975" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1117" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1118" "#" "<==" "emacs"
cd /root/.emacs.d/manual-packages/bible-mode;  "diatheke" "-b" "NASB" "-o" "w" "-f" "internal" "-k" "Genesis 1119" "#" "<==" "emacs"
