cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 904" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Habakkuk 1:12-13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 905" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Habakkuk 2:2-4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 904" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 905" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 906" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 905" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 906" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 905" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Habakkuk 2:5" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Sheol" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 37:35;Genesis 42:38;Genesis 44:29;Genesis 44:31;Numbers 16:30;Numbers 16:33;Deuteronomy 32:22;I Samuel 2:6;II Samuel 22:6;I Kings 2:6;I Kings 2:9;Job 7:9;Job 11:8;Job 14:13;Job 17:13;Job 17:16;Job 21:13;Job 24:19;Job 26:6;Psalms 6:5;Psalms 9:17;Psalms 16:10;Psalms 18:5;Psalms 30:3;Psalms 31:17;Psalms 49:14;Psalms 49:15;Psalms 55:15;Psalms 86:13;Psalms 88:3;Psalms 89:48;Psalms 116:3;Psalms 139:8;Psalms 141:7;Proverbs 1:12;Proverbs 5:5;Proverbs 7:27;Proverbs 9:18;Proverbs 15:11;Proverbs 15:24;Proverbs 23:14;Proverbs 27:20;Proverbs 30:16;Ecclesiastes 9:10;Isaiah 5:14;Isaiah 7:11;Isaiah 14:9;Isaiah 14:11;Isaiah 14:15;Isaiah 28:15;Isaiah 28:18;Isaiah 38:10;Isaiah 38:18;Isaiah 57:9;Ezekiel 31:15;Ezekiel 31:16;Ezekiel 31:17;Ezekiel 32:21;Ezekiel 32:27;Hosea 13:14;Amos 9:2;Jonah 2:2;Habakkuk 2:5;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Numbers 16:30" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Deuteronomy 32:22" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 289" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Samuel 22:2-8" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 293" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Kings 2:1-7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 443" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 7:7-16" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 447" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 11:7-9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 453" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 450" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 14:13-14" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 453" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 457" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 21:7-13" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 460" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 24:19-25" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 462" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Job 26:5-7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 484" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "came from God" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 8:42;John 16:27;John 16:30;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1013" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 16:26-27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "you have come to do" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "Judas" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 10:4;Matthew 13:55;Matthew 26:14;Matthew 26:25;Matthew 26:47;Matthew 27:3;Mark 3:19;Mark 6:3;Mark 14:10;Mark 14:43;Luke 6:16;Luke 22:3;Luke 22:47;Luke 22:48;John 6:71;John 12:4;John 13:2;John 13:26;John 13:29;John 14:22;John 18:2;John 18:3;John 18:5;Acts 1:13;Acts 1:16;Acts 1:25;Acts 5:37;Acts 9:11;Acts 15:22;Acts 15:27;Acts 15:32;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1010" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 13:27" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1011" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1010" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 13:36-38" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1011" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 14:1-7" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "working together" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "II Corinthians 6:1;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "have life in his name" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 20:31;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1017" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 20:29-31" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "believe all" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Luke 24:25;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 24:25" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 997" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 24:25-26" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "woe to him" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Ecclesiastes 4:10;Isaiah 45:9;Isaiah 45:10;Jeremiah 22:13;Habakkuk 2:6;Habakkuk 2:9;Habakkuk 2:12;Habakkuk 2:15;Habakkuk 2:19;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "is betrayed" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Matthew 26:24;Matthew 26:45;Mark 14:21;Mark 14:41;Luke 22:22;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Mark 14:21" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "widow" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 38:11;Genesis 38:14;Genesis 38:19;Exodus 22:22;Exodus 22:24;Leviticus 21:14;Leviticus 22:13;Numbers 30:9;Deuteronomy 10:18;Deuteronomy 14:29;Deuteronomy 16:11;Deuteronomy 16:14;Deuteronomy 24:17;Deuteronomy 24:19;Deuteronomy 24:20;Deuteronomy 24:21;Deuteronomy 26:12;Deuteronomy 26:13;Deuteronomy 27:19;Ruth 4:5;Ruth 4:10;I Samuel 27:3;I Samuel 30:5;II Samuel 2:2;II Samuel 3:3;II Samuel 14:5;II Samuel 20:3;I Kings 7:14;I Kings 11:26;I Kings 17:9;I Kings 17:10;I Kings 17:20;Job 22:9;Job 24:3;Job 24:21;Job 27:15;Job 29:13;Job 31:16;Job 31:18;Psalms 68:5;Psalms 78:64;Psalms 94:6;Psalms 109:9;Psalms 146:9;Proverbs 15:25;Isaiah 1:17;Isaiah 1:23;Isaiah 9:17;Isaiah 10:2;Isaiah 47:8;Isaiah 47:9;Isaiah 54:4;Jeremiah 7:6;Jeremiah 15:8;Jeremiah 18:21;Jeremiah 22:3;Jeremiah 49:11;Lamentations 1:1;Lamentations 5:3;Ezekiel 19:7;Ezekiel 22:7;Ezekiel 22:25;Ezekiel 44:22;Zechariah 7:10;Malachi 3:5;Matthew 22:24;Mark 12:19;Mark 12:40;Mark 12:42;Mark 12:43;Luke 2:37;Luke 4:25;Luke 4:26;Luke 7:12;Luke 18:3;Luke 18:5;Luke 20:28;Luke 20:47;Luke 21:2;Luke 21:3;Acts 6:1;Acts 9:39;Acts 9:41;I Corinthians 7:8;I Timothy 5:3;I Timothy 5:4;I Timothy 5:5;I Timothy 5:9;I Timothy 5:11;I Timothy 5:14;I Timothy 5:16;James 1:27;Revelation of John 18:7;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 994" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "Luke 21:1-4" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "weakness" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Romans 8:26;I Corinthians 1:25;I Corinthians 2:3;I Corinthians 15:43;II Corinthians 11:30;II Corinthians 12:5;II Corinthians 12:9;II Corinthians 12:10;II Corinthians 13:4;Hebrews 4:15;Hebrews 5:2;Hebrews 7:18;Hebrews 7:28;Hebrews 11:34;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 12:9" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "grace of God" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Acts 11:23;Acts 13:43;Acts 14:26;Acts 20:24;Romans 5:15;I Corinthians 1:4;I Corinthians 3:10;I Corinthians 15:10;II Corinthians 1:12;II Corinthians 6:1;II Corinthians 8:1;II Corinthians 9:14;Galatians 2:21;Colossians 1:6;Titus 2:11;Hebrews 2:9;Hebrews 12:15;I Peter 5:12;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I Corinthians 15:10" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "II Corinthians 6:1" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "he loved us first" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "loved us" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Malachi 1:2;Romans 8:37;Ephesians 2:4;Ephesians 5:2;II Thessalonians 2:16;I John 4:10;I John 4:11;I John 4:19;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Genesis 1163" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 4:19" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 4:7-21" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "I John 4:21" "#" "<==" "in-pen"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "keeps my commandments" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "is the one who" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "Job 5:17;Psalms 32:1;Psalms 41:1;Psalms 68:35;Psalms 84:12;Proverbs 3:13;Proverbs 8:34;Proverbs 28:14;Jeremiah 10:16;Jeremiah 51:19;Matthew 11:6;Matthew 13:20;Matthew 13:22;Matthew 13:23;Luke 7:5;Luke 7:23;Luke 9:48;Luke 12:21;Acts 7:38;Romans 8:34;Romans 14:22;I Corinthians 1:20;Ephesians 4:10;I John 3:10;I John 5:6;Revelation of John 1:3;Revelation of John 16:15;Revelation of John 20:6;Revelation of John 22:7;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "one who loves me" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-s" "phrase" "-o" "w" "-f" "plain" "-k" "who loves me" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "internal" "-k" "John 14:21;" "#" "<==" "emacs"
cd /root/notes;  "diatheke" "-b" "ESV" "-o" "w" "-f" "plain" "-k" "John 14:21" "#" "<==" "in-pen"
