#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -ot) {
        subset=ot
        shift
        shift
    }
    ;;

    -nt) {
        subset=nt
        shift
        shift
    }
    ;;

    *) break;
esac; done

{
case "$subset" in
    ot) {
        sqlite3 $DUMP$NOTES/databases/kjv.db 'select distinct (book) from bible order by rowid limit 39'
    }
    ;;

    nt) {
        sqlite3 $DUMP$NOTES/databases/kjv.db 'select distinct (book) from bible where rowid >= 40 order by rowid'
    }
    ;;

    *) {
        sqlite3 $DUMP$NOTES/databases/kjv.db 'select distinct (book) from bible order by rowid'
    }
    ;;
esac
} | pavs
