#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

sn="$(basename -- "$0")"

help() {
    echo "$sn <book>" | hls red 1>&2
}

book="$1"
# : "${book:="Gen"}"
test -n "$book" || { help; exit 1; }

sqlite3 $DUMP$NOTES/databases/kjv.db "select max(chapter) as max_chapter from bible where book = \"$book\"" | pavs
