#!/bin/bash
export TTY

# ( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

help () {
    sn="$(basename -- "$0")"

    echo "$sn <book> <chapter>" | hls red 1>&2
}

book="$1"
# : "${book:="Gen"}"
test -n "$book" || { help; exit 1; }

chapter="$2"
# : "${chapter:="1"}"
test -n "$chapter" || { help; exit 1; }

sqlite3 $DUMP$NOTES/databases/kjv.db "select max(verse) as max_verse from bible where book = \"$book\" and chapter = $chapter" | pavs
