cd /root/.emacs.d/host/pen.el/src;  "rat" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "rat" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "rat" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "rat" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "rat" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "rat" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el;  "rat" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/config/rat;  "rat" "--help" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/config/rat;  "rat" "-h" "#" "<==" "zsh"
