;;; cpputils-cmake-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cpputils-cmake.el

(autoload 'cppcm-get-exe-path-current-buffer "cpputils-cmake" nil t)
(autoload 'cppcm-version "cpputils-cmake" nil t)
(autoload 'cppcm-compile "cpputils-cmake" "\
Compile the executable/library in current directory,
default compile command or compile in the build directory.
You can specify the sequence which compile is default
by customize `cppcm-compile-list'.

(fn &optional PREFIX)" t)
(autoload 'cppcm-recompile "cpputils-cmake" "\
Run 'make clean && compile'." t)
(autoload 'cppcm-reload-all "cpputils-cmake" "\
Reload and reproduce everything." t)
(register-definition-prefixes "cpputils-cmake" '("cppcm-"))

;;; End of scraped data

(provide 'cpputils-cmake-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cpputils-cmake-autoloads.el ends here
