#!/bin/bash
export TTY

# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# curl https://sh.rustup.rs -sSf | sh

echo-exec rustup component remove rls rls-preview
echo-exec rustup update
echo-exec rustup update stable
echo-exec rustup component add rustc rust-analysis rust-src rustfmt