#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

agt sqlite3-pcre || agi sqlite3-pcre &>/dev/null

# agi sqlite3-pcre
# cd /root/repos/aaronjohnsabu1999/bible-databases/DB;  "litecli" "/root/repos/aaronjohnsabu1999/bible-databases/DB/BSBBible_Database.db"

: "${regex:="$1"}"
# : "${regex:="blessed.*is"}"

test -n "$regex" || exit 1

for version in $(regex-bible-search-list-translations); do
    bible_regex_search.bb "$version" "$regex" | prepend-string "$version	"
done

# j:helm-regex-bible-search-all
