cd /root/notes;  "ew3m-quick" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=\"prolog consult\"\\nhttp://www.google.com/search?ie=utf-8&oe=utf-8&q=\"prolog consult\"\\nhttp://www.google.com/search?ie=utf-8&oe=utf-8&q=\"prolog consult\"\\nhttp://www.google.com/search?ie=utf-8&oe=utf-8&q=\"prolog consult\"" "#" "<==" "ff"
cd /root/.pen/documents/notes;  "ew3m-quick" "http://localhost" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "ew3m-quick" "http://localhost" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "ew3m-quick" "http://localhost" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "ew3m-quick" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=\"prolog consult\"" "#" "<==" "ff"
cd /root/notes;  "ew3m-quick" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=\"prolog make fact inside swipl repl\"" "#" "<==" "ff"
cd /root/notes;  "ew3m-quick" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20make%20fact%20inside%20swipl%20repl%22" "#" "<==" "ff"
cd /root/notes;  "ew3m-quick" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20make%20fact%20inside%20swipl%20repl%22" "#" "<==" "ff"
cd /root/notes;  "ew3m-quick" "http://www.google.com/search?ie=utf-8&oe=utf-8&q=%22prolog%20consult%22" "#" "<==" "ff"
cd /root/notes;  "ew3m-quick" "prolog consult" "#" "<==" "ff"
