cd /root/.pen/documents/notes/ws/vimbible;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/get-bible-book-chapter.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/get-bible-book-chapter.cl" "Jude" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2" "Tim" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2" "Tim" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Tim" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Samuel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Job" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Job" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Job" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Job" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Job" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Samuel" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Samuel" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Job" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Psalms" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Samuel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Samuel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Job" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Psalms" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Psalms" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Psalms" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Psalms" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Psalms" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Isaiah" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Isaiah" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Ezekiel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Matthew" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Mark" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Mark" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Galatians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Galatians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Galatians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Ephesians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Philippians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Colossians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Colossians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Thessalonians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Thessalonians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Thessalonians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Thessalonians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Thessalonians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Thessalonians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Titus" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Hebrews" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Hebrews" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Hebrews" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Hebrews" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "James" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "James" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "James" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "James" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "II Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Peter" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "I John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Jude" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Revelation of John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Exodus" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Proverbs" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Ezekiel" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "John" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Corinthians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Galatians" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Timothy" "#" "<==" "sbcl-ql"
cd /root/.pen/documents;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "3 John" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Tim" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Tim." "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Tim. 3" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Tim. 3:6-9" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "2 Tim." "#" "<==" "sbcl-ql"
