cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--help" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--help" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--help" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--help" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--script" "contemplate.lsp" "#" "<==" "sh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--script" "contemplate.lsp" "#" "<==" "sh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--script" "contemplate.lsp" "#" "<==" "sh"
cd /root/notes;  "sbcl" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "sbcl" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "sbcl" "--help" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--script" "contemplate.lsp" "#" "<==" "sh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--script" "contemplate.lsp" "#" "<==" "sh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--script" "contemplate.lsp" "#" "<==" "sh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--script" "contemplate.lsp" "#" "<==" "sh"
cd /volumes/home/shane/var/smulliga/source/git/google/lisp-koans;  "sbcl" "--script" "contemplate.lsp" "#" "<==" "sh"
