cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Romans" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Ephesians" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Acts" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Deuteronomy" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Exodus" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/scripts;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Jeremiah" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Genesis" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "John" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "James" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Exodus" "#" "<==" "sbcl-ql"
cd /root/.emacs.d/host/pen.el/src;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "John" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Galatians" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Ephesians" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Colossians" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 John" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Luke" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Peter" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Psalm" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Psalm" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Peter" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Malachi" "#" "<==" "sbcl-ql"
cd /root/notes;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Malachi" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "Colossians" "#" "<==" "sbcl-ql"
cd /;  "sbcl" "--load" "/root/.roswell/lisp/quicklisp/setup.lisp" "--script" "/root/.emacs.d/host/pen.el/scripts/canonicalise-bible-book-title.cl" "1 Thessalonians" "#" "<==" "sbcl-ql"
