cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "--help" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "--help" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "--help" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "nvim"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "tmux: server"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "tmux: server"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "tmux: server"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "tmux: server"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "--help" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "grepgithub.py" "-q" "serapeum:defalias" "#" "<==" "zsh"
