cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "Matt" "12:3" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "Matt" "12:3" "#" "<==" "zsh"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "Matthew" "5:17-18" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "Matthew" "5:17-18" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "Matthew" "5:17-18" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "Matthew" "5:17-18" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "Matthew" "5:17-18" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "Matthew" "5:17-18" "#" "<==" "bash"
