cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/agenda;  "nem" "nbd" "fast" "ebible" "-c" "-m" "ESV" "Genesis 1:22" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Matthew 7:21-23" "#" "<==" "pen-ci"
