cd /root/.pen/documents/notes;  "nem" "todayfile" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts;  "nem" "ead" "DEFAULT" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/scripts/babashka/utils;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Job 32:8" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Num 27:18" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Dan 5:14" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Dan 5:11" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Dan 4:18" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Dan 4:6" "#" "<==" "pen-ci"
