cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /;  "nem" "Matthew" "12:34-35" "#" "<==" "zsh"
cd /;  "nem" "kjv" "Matthew" "12:34-35" "#" "<==" "zsh"
cd /;  "nem" "onelined" "kjv" "Matthew" "12:34-35" "#" "<==" "zsh"
cd /;  "nem" "onelined" "decorated" "kjv" "Matthew" "12:34-35" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Romans 6:2-11" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/notes-on-sermons;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "I Peter 5:5-7" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/notes-on-sermons;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Galatians 5:22-26" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/notes-on-sermons;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/glossaries;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "2 Samuel 2:1" "#" "<==" "pen-ci"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/glossaries;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/glossaries;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
