cd /root/.pen/documents/notes;  "nem" "onelined" "decorated" "II" "Cor" "13:5" "#" "<==" "nod"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "onelined" "decorated" "Romans" "6:22-23" "#" "<==" "nod"
cd /root/.pen/documents/notes;  "nem" "onelined" "decorated" "Hebrews" "5:9-10" "#" "<==" "nod"
cd /root/.pen/documents/notes;  "nem" "onelined" "decorated" "Matthew" "24:13-14" "#" "<==" "nod"
cd /root/.pen/documents/notes;  "nem" "onelined" "decorated" "I" "Cor" "15:1-4" "#" "<==" "nod"
cd /root/.pen/documents/notes;  "nem" "onelined" "decorated" "John" "14:1" "#" "<==" "nod"
