cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Romans 8:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Romans 8:6" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Romans 8:11" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "I John 5:6" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Romans 8:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Romans 8:6" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Romans 8:2" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "I Peter 1:10" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "I Peter 1:21" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "I Peter 3:9" "#" "<==" "bash"
cd /root/notes;  "nem" "Mark" "7:12" "#" "<==" "zsh"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Esther 2:6" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Esther 2:16" "#" "<==" "bash"
