cd /root/.pen/documents/notes;  "nem" "onelined" "decorated" "Luke" "16:16" "#" "<==" "nod"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
