cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:2" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:2" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 49:3" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Numbers 28:11" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Deuteronomy 11:12" "#" "<==" "bash"
cd /root/.pen/documents;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:11" "#" "<==" "bash"
cd /root/.pen/documents;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:5" "#" "<==" "bash"
cd /root/.pen/documents;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:2" "#" "<==" "bash"
cd /root/.pen/documents;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:7" "#" "<==" "bash"
cd /root/.pen/documents;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:25" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:14" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:15" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:15" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 3:3" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 3:17" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 3:1" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 4:7" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 5:26" "#" "<==" "tmux: server"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:3" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:14" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-m" "NASB" "Genesis 1:7" "#" "<==" "tmux: server"
