cd /root/.emacs.d/host/pen.el/src;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:4" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/src;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 10:1" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/src;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 10:2" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
cd /root/.pen/documents/agenda;  "nem" "nbd" "fast" "ebible" "-ca" "-m" "NASB" "Genesis 1:1" "#" "<==" "pen-ci"
cd /root/.pen/documents/agenda;  "nem" "nbd" "fast" "ebible" "-ca" "-m" "NASB" "Genesis 1:2" "#" "<==" "pen-ci"
cd /root/.pen/documents/agenda;  "nem" "nbd" "fast" "ebible" "-ca" "-m" "NASB" "Genesis 1:3" "#" "<==" "pen-ci"
cd /root/.pen/documents/agenda;  "nem" "nbd" "fast" "ebible" "-ca" "-m" "NASB" "Genesis 1:4" "#" "<==" "pen-ci"
cd /root/.pen/documents/agenda;  "nem" "nbd" "fast" "ebible" "-ca" "-m" "NASB" "Genesis 1:5" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:10" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:11" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:12" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:14" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:15" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:16" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:17" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:18" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Romans 3:19" "#" "<==" "pen-ci"
