cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "John 14:1-3" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "I Cor 15:1-53" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "I Thes 4:13-18" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Romans 8:19" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "I Cor 1:7-8" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Phil 3:20-21" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Col 3:4" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "I Thes 1:10" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "I Thes 2:19" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "I Thes 4:9-10,23" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "II Thes 2:1,3" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "I Tim 6:14" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Heb 9:28" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "James 5:7-9" "#" "<==" "pen-ci"
cd /root/notes/ws/rapture;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes/ws/rapture;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes/ws/rapture;  "nem" "nbd" "fast" "ebible" "-c" "-m" "engbsb2020eb" "Rev 22:7,12,20" "#" "<==" "pen-ci"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
