cd /root/.emacs.d/host/pen.el/src;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Psalms 104:20" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Matthew 10:16-18" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Matthew 5:31" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Matthew 5:31-32" "#" "<==" "pen-ci"
