cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/notes;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el;  "nem" "nbd" "fast" "ebible" "-c" "-m" "ESV" "Genesis 3:1" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el;  "nem" "nbd" "fast" "ebible" "-c" "-m" "ESV" "Genesis 3:2" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes/ws/discipleship-group/weekly-journal;  "nem" "Matthew" "5:23-24" "#" "<==" "bash"
