cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
cd /root/.pen/documents/notes/ws/journal;  "nem" "todayfile" "#" "<==" "zsh"
cd /root/.pen/documents/notes/ws/journal;  "nem" "todayfile" "#" "<==" "zsh"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-m" "NASB" "I" "John" "2:4" "#" "<==" "pen-ci"
cd /root/.emacs.d/host/pen.el;  "nem" "nbd" "fast" "ebible" "-c" "-m" "NASB" "Genesis 2:2" "#" "<==" "pen-ci"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "todayfile" "#" "<==" "zsh"
