cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:20" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:21" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:11" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:14" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:11" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:10" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:7" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:7" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Daniel 5:11" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Genesis 1:4" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Genesis 1:4" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Genesis 1:16" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Romans 1:1" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Genesis 1:1" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/src;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Genesis 1:5" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "Hebrews 10:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:2" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:1" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:5" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "bash"
cd /root/notes;  "nem" "fast" "ebible" "-c" "-m" "NASB" "II Thessalonians 2:4" "#" "<==" "bash"
