cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /volumes/home/shane/var/smulliga/source/git/mullikine/prayers;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.emacs.d/host/pen.el/docs/theology;  "nem" "decorated" "onelined" "zsh" "#" "<==" "bash"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Luke 6:37-38" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Luke 11:2-4" "#" "<==" "pen-ci"
cd /root/.pen/documents/notes;  "nem" "nbd" "fast" "ebible" "-c" "-m" "KJV" "Matthew 6:14-15" "#" "<==" "pen-ci"
