cd /root/.pen/documents/notes;  "lsof" "-p" "6854" "#" "<==" "pen-tm"
cd /root/.pen/documents/notes;  "lsof" "-p" "6856" "#" "<==" "pen-tm"
cd /root/.pen/documents/notes;  "lsof" "-p" "6861" "#" "<==" "pen-tm"
cd /root/.pen/documents/notes;  "lsof" "-p" "6919" "#" "<==" "pen-tm"
cd /root/.pen/documents/notes;  "lsof" "-p" "6920" "#" "<==" "pen-tm"
