#+TITLE: D-Group journal weekly entry for 2024, week 16

* D-Group weekly session notes
Started working on it: <2024-04-20 Sat>

Listen to instrumental worship music:
[[https://www.youtube.com/watch?v=K5qgKMWbo4c&t=1s][Wait On The Lord : Piano Instrumental Music With Scriptures & Autumn Scene d???CHRISTIAN piano - YouTube]]

| Scripture Memory NT | NT260 Passage       | Foundations260 Passage | Scripture Memory OT | OT260 Passage |
|---------------------+---------------------+------------------------+---------------------+---------------|
| [[sh:bible-read-passage nasb Matthew 5:31-32 ][Matthew 5:31-32]]     | [[sh:bible-study-passage nasb I Corinthians 14-16 ][I Corinthians 14-16]] | [[sh:bible-study-passage nasb I Samuel 17-22 ][I Samuel 17-22]]         | [[sh:bible-study-passage nasb Psalm 77:11-12 ][Psalm 77:11-12]]      | [[sh:bible-study-passage nasb Leviticus 16 ][Leviticus 16]]  |
|                     | [[sh:bible-study-passage nasb II Corinthians 1-2 ][II Corinthians 1-2]]  | [[sh:bible-study-passage nasb Psalm 22 ][Psalm 22]]               |                     | [[sh:bible-study-passage nasb Leviticus 23 ][Leviticus 23]]  |
|                     |                     | [[sh:bible-study-passage nasb I Samuel 24-25 ][I Samuel 24-25]]         |                     | [[sh:bible-study-passage nasb Leviticus 26 ][Leviticus 26]]  |
|                     |                     | [[sh:bible-study-passage nasb I Samuel 28 ][I Samuel 28]]            |                     | [[sh:bible-study-passage nasb Numbers 11-12 ][Numbers 11-12]] |
|                     |                     | [[sh:bible-study-passage nasb I Samuel 31 ][I Samuel 31]]            |                     | [[sh:bible-study-passage nasb Psalm 76-78 ][Psalm 76-78]]   |

While doing the reading, write bullet points about the story.
Take note of verses which stand out to me and think about what
the writer may have been experiencing when they wrote those verses.
Keep in mind the context of the verse.

** Readings bullet points
Write bullet points for each of the readings, and optionally sub-bullet-points applications for applying to or making comparisons to my own life.

Story bullet points (over entire Foundations260 reading):
- 

Story bullet points (over entire NT260 Journals reading):
- 

** Scripture memory
*** NT
#+BEGIN_SRC bash -n :i bash :f "bible-show-verses -m NASB -pp" :async :results verbatim code :lang text
  Matthew 5:31-32
#+END_SRC

#+RESULTS:
#+begin_src text
Matthew 5:31
‾‾‾‾‾‾‾‾‾‾‾‾
“It was said, ‘Whoever sends his wife away,
let him give her a certificate of divorce’;

Matthew 5:32
‾‾‾‾‾‾‾‾‾‾‾‾
but I say to you that everyone who divorces his
wife, except for the reason of unchastity, makes
her commit adultery; and whoever marries a
divorced woman commits adultery.

(NASB)
#+end_src

Lord Jesus please forgive me.
Please, LORD God Almighty. Please help me to put to death all sexual immorality and impure thoughts.
Please, LORD, protect me.
Please, God, don't let me die.
Please never let me fall away from You, Lord Jesus.
Oh God.

Today was Mum and Dad's 40th wedding anniversary at Nicolini's.

*** OT
#+BEGIN_SRC bash -n :i bash :f "bible-show-verses -m NASB -pp" :async :results verbatim code :lang text
  Psalm 77:11-12
#+END_SRC

#+RESULTS:
#+begin_src text
Psalms 77:11
‾‾‾‾‾‾‾‾‾‾‾‾
I shall remember the deeds of the LORD; Surely I
will remember Your wonders of old.

Psalms 77:12
‾‾‾‾‾‾‾‾‾‾‾‾
I will meditate on all Your work And muse on Your
deeds.

(NASB)
#+end_src

** HEAR Journals
Go over the reading and make hear journal entries for any verses
that stood out for me.

+ H :: [h]ighlight a verse that stood out in the reading
+ E :: [e]xplain the context of the verse and what the writer/people in the story may have been experiencing when they wrote/experienced it
+ A :: write down how I can [a]pply this Bible verse in my own life
+ R :: [r]espond to the LORD in prayer

hear
