#+TITLE: D-Group journal weekly entry for 2024, week 12

* D-Group weekly session notes
Started working on it: <2024-03-21 Thu>

Listen to instrumental worship music:
[[https://www.youtube.com/watch?v=K5qgKMWbo4c&t=1s][Wait On The Lord : Piano Instrumental Music With Scriptures & Autumn Scene d???CHRISTIAN piano - YouTube]]

| Scripture Memory | NT260 Passage        | Foundations260 Readings |
|------------------+----------------------+-------------------------|
| [[sh:bible-read-passage nasb Matthew 5:23-24 ][Matthew 5:23-24]]  | [[sh:bible-study-passage nasb I Thessalonians 3-5 ][I Thessalonians 3-5]]  | [[sh:bible-study-passage nasb Deuteronomy 8-9 ][Deuteronomy 8-9]]         |
|                  | [[sh:bible-study-passage nasb II Thessalonians 1-2 ][II Thessalonians 1-2]] | [[sh:bible-study-passage nasb Deuteronomy 30-34 ][Deuteronomy 30-34]]       |
|                  |                      | [[sh:bible-study-passage nasb Joshua 1-4 ][Joshua 1-4]]              |

While doing the reading, write bullet points about the story.
Take note of verses which stand out to me and think about what
the writer may have been experiencing when they wrote those verses.
Keep in mind the context of the verse.

** Readings bullet points
Write bullet points for each of the readings, and optionally sub-bullet-points applications for applying to or making comparisons to my own life.

Story bullet points (over entire Foundations260 reading):
- 

Story bullet points (over entire NT260 Journals reading):
- 

** Scripture memory
#+BEGIN_SRC bash -n :i bash :f "bible-show-verses -m NASB -pp" :async :results verbatim code :lang text
  Matthew 5:23-24
#+END_SRC

#+RESULTS:
#+begin_src text
Matthew 5:23
‾‾‾‾‾‾‾‾‾‾‾‾
Therefore if you are presenting your offering at
the altar, and there remember that your brother
has something against you,

Matthew 5:24
‾‾‾‾‾‾‾‾‾‾‾‾
leave your offering there before the altar and
go; first be reconciled to your brother, and then
come and present your offering.

(NASB)
#+end_src

** HEAR Journals
Go over the reading and make hear journal entries for any verses
that stood out for me.

+ H :: [h]ighlight a verse that stood out in the reading
+ E :: [e]xplain the context of the verse and what the writer/people in the story may have been experiencing when they wrote/experienced it
+ A :: write down how I can [a]pply this Bible verse in my own life
+ R :: [r]espond to the LORD in prayer

hear
