#+TITLE: D-Group journal weekly entry for 2024, week 37

* D-Group weekly session notes
Started working on it: <2024-09-12 Thu>

Listen to instrumental worship music:
[[https://www.youtube.com/watch?v=z6vR_FV7s7c][youtube.com: 4 Hours Best TOP 27 Worship Piano Instrumental for Prayer and Meditation e,?e??i??i??]]

| Scripture Memory NT | NT260 Passage | Foundations260 Passage | Scripture Memory OT | OT260 Passage  |
|---------------------+---------------+------------------------+---------------------+----------------|
| [[sh:bible-read-passage nasb Matthew 6:31-32 ][Matthew 6:31-32]]     | [[sh:bible-study-passage nasb II Peter 3 ][II Peter 3]]    |                        | [[sh:bible-read-passage nasb Isaiah 9:6 ][Isaiah 9:6]]          | [[sh:bible-study-passage nasb Joel 2-3 ][Joel 2-3]]       |
|                     | [[sh:bible-study-passage nasb John 1-4 ][John 1-4]]      |                        |                     | [[sh:bible-study-passage nasb Isaiah 6 ][Isaiah 6]]       |
|                     |               |                        |                     | [[sh:bible-study-passage nasb Isaiah 9 ][Isaiah 9]]       |
|                     |               |                        |                     | [[sh:bible-study-passage nasb Isaiah 44 ][Isaiah 44]]      |
|                     |               |                        |                     | [[sh:bible-study-passage nasb Proverbs 24-28 ][Proverbs 24-28]] |

While doing the reading, write bullet points about the story.
Take note of verses which stand out to me and think about what
the writer may have been experiencing when they wrote those verses.
Keep in mind the context of the verse.

** Readings bullet points
Write bullet points for each of the readings, and optionally sub-bullet-points applications for applying to or making comparisons to my own life.

Story bullet points (over entire Foundations260 reading):
- 

Story bullet points (over entire NT260 Journals reading):
- 

** Scripture memory
*** NT
#+BEGIN_SRC bash -n :i bash :f "bible-show-verses -m NASB -pp" :async :results verbatim code :lang text
  Matthew 6:31-32
#+END_SRC

#+RESULTS:
#+begin_src text
Matthew 6:31
‾‾‾‾‾‾‾‾‾‾‾‾
Do not worry then, saying, ‘What will we
eat?’ or ‘What will we drink?’ or ‘What
will we wear for clothing?’

Matthew 6:32
‾‾‾‾‾‾‾‾‾‾‾‾
For the Gentiles eagerly seek all these things;
for your heavenly Father knows that you need all
these things.

(NASB)
#+end_src

*** OT
#+BEGIN_SRC bash -n :i bash :f "bible-show-verses -m NASB -pp" :async :results verbatim code :lang text
  Isaiah 9:6
#+END_SRC

#+RESULTS:
#+begin_src text
Isaiah 9:6
‾‾‾‾‾‾‾‾‾‾
For a child will be born to us, a son will be
given to us; And the government will rest on His
shoulders; And His name will be called Wonderful
Counselor, Mighty God, Eternal Father, Prince of
Peace.

(NASB)
#+end_src

** HEAR Journals
Go over the reading and make hear journal entries for any verses
that stood out for me.

+ H :: [h]ighlight a verse that stood out in the reading
+ E :: [e]xplain the context of the verse and what the writer/people in the story may have been experiencing when they wrote/experienced it
+ A :: write down how I can [a]pply this Bible verse in my own life
+ R :: [r]espond to the LORD in prayer

hear
