#+TITLE: D-Group journal weekly entry for 2024, week 4

* D-Group weekly session notes
Started working on it: <2024-01-26 Fri>

Listen to instrumental worship music:
[[https://www.youtube.com/watch?v=K5qgKMWbo4c&t=1s&ab_channel=CHRISTIANPiano][Wait On The Lord : Piano Instrumental Music With Scriptures & Autumn Scene рџЌЃCHRISTIAN piano]]

| Scripture Memory | NT260 Passage | Foundations260 Readings |
|------------------+---------------+-------------------------|
| [[sh:bible-read-passage esv Matthew 5:7-8 ][Matthew 5:7-8]]    | [[sh:bible-study-passage esv Luke 16-20 ][Luke 16-20]]    | [[sh:bible-study-passage esv Genesis 27-28 ][Genesis 27-28]]           |

While doing the reading, write bullet points about the story.
Take note of verses which stand out to me and think about what
the writer may have been experiencing when they wrote those verses.
Keep in mind the context of the verse.

** Readings bullet points
Write bullet points for each of the readings, and optionally sub-bullet-points applications for applying to or making comparisons to my own life.

Story bullet points (over entire Foundations260 reading):
- 

Story bullet points (over entire NT260 Journals reading):
- 

** Scripture memory
#+BEGIN_SRC bash -n :i bash :f "bible-show-verses -m ESV -pp" :async :results verbatim code :lang text
  esv Matthew 5:7-8
#+END_SRC

#+RESULTS:
#+begin_src text
Matthew 5:7
вЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕ
Blessed are the merciful, for they shall receive
mercy.

Matthew 5:8
вЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕвЂѕ
Blessed are the pure in heart, for they shall see
God.

(ESV)
#+end_src

** HEAR Journals
Go over the reading and make hear journal entries for any verses
that stood out for me.

+ H :: [h]ighlight a verse that stood out in the reading
+ E :: [e]xplain the context of the verse and what the writer/people in the story may have been experiencing when they wrote/experienced it
+ A :: write down how I can [a]pply this Bible verse in my own life
+ R :: [r]espond to the LORD in prayer

hear
