#+TITLE: D-Group journal weekly entry for 2024, week 8

* D-Group weekly session notes
Started working on it: <2024-02-21 Wed>

Listen to instrumental worship music:
[[https://www.youtube.com/watch?v=9oVSJUk9wDg][The Love Of God : Instrumental Worship, Meditation & Prayer Music with Nature d???CHRISTIAN piano - YouTube]]

| Scripture Memory | NT260 Passage | Foundations260 Readings |
|------------------+---------------+-------------------------|
| [[sh:bible-read-passage nasb Matthew 5:15-16 ][Matthew 5:15-16]]  | [[sh:bible-study-passage nasb Acts 12-14 ][Acts 12-14]]    | [[sh:bible-study-passage nasb Exodus 18-31 ][Exodus 18-31]]            |
|                  | [[sh:bible-study-passage nasb James 1-2 ][James 1-2]]     |                         |

While doing the reading, write bullet points about the story.
Take note of verses which stand out to me and think about what
the writer may have been experiencing when they wrote those verses.
Keep in mind the context of the verse.

** Readings bullet points
Write bullet points for each of the readings, and optionally sub-bullet-points applications for applying to or making comparisons to my own life.

Story bullet points (over entire Foundations260 reading):
- 

Story bullet points (over entire NT260 Journals reading):
- Herod jailed Peter but failed
  - Herod jailed Peter
  - The church prayed for Peter without ceasing
  - An angel of the Lord released Peter
  - Herod was smote by an angel of the Lord

** Scripture memory
#+BEGIN_SRC bash -n :i bash :f "bible-show-verses -m NASB -pp" :async :results verbatim code :lang text
  Matthew 5:15-16
#+END_SRC

#+RESULTS:
#+begin_src text
Matthew 5:15
‾‾‾‾‾‾‾‾‾‾‾‾
nor does anyone light a lamp and put it under a
basket, but on the lampstand, and it gives light
to all who are in the house.

Matthew 5:16
‾‾‾‾‾‾‾‾‾‾‾‾
Let your light shine before men in such a way
that they may see your good works, and glorify
your Father who is in heaven.

(NASB)
#+end_src

** HEAR Journals
Go over the reading and make hear journal entries for any verses
that stood out for me.

+ H :: [h]ighlight a verse that stood out in the reading
+ E :: [e]xplain the context of the verse and what the writer/people in the story may have been experiencing when they wrote/experienced it
+ A :: write down how I can [a]pply this Bible verse in my own life
+ R :: [r]espond to the LORD in prayer

hear
