;;; consult-notmuch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-notmuch.el

(autoload 'consult-notmuch "consult-notmuch" "\
Search for your email in notmuch, showing single messages.
If given, use INITIAL as the starting point of the query.

(fn &optional INITIAL)" t)
(autoload 'consult-notmuch-tree "consult-notmuch" "\
Search for your email in notmuch, showing full candidate tree.
If given, use INITIAL as the starting point of the query.

(fn &optional INITIAL)" t)
(autoload 'consult-notmuch-address "consult-notmuch" "\
Search the notmuch db for an email address and compose mail to it.
With a prefix argument, prompt multiple times until there
is an empty input.

(fn &optional MULTI-SELECT-P INITIAL-ADDR)" t)
(defvar consult-notmuch-buffer-source '(:name "Notmuch Buffer" :narrow (110 . "Notmuch") :hidden t :category buffer :face consult-buffer :history buffer-name-history :state consult--buffer-state :items consult-notmuch--interesting-buffers) "\
Notmuch buffer candidate source for `consult-buffer'.")
(register-definition-prefixes "consult-notmuch" '("consult-notmuch-"))

;;; End of scraped data

(provide 'consult-notmuch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-notmuch-autoloads.el ends here
