cd /volumes/home/shane/notes/ws/bible-studies;  "z" "faith-and-judgement.html"
cd /volumes/home/shane/notes/ws/bible-studies;  "z" "faith-and-judgement.pdf"
cd /volumes/home/shane/notes/ws/bible-studies;  "z" "faith-and-judgement.pdf"
cd /volumes/home/shane/notes/ws/bible-studies;  "z" "faith-and-judgement.pdf"
cd /volumes/home/shane/notes/ws/bible-studies;  "z" "faith-and-judgement.pdf"
cd /root/.emacs.d/host/pen.el/docs;  "z" "faith-and-judgement.pdf"
cd /root/.emacs.d/host/pen.el/docs;  "z" "faith-and-judgement.pdf"
cd /root/.emacs.d/host/pen.el/docs;  "z" "faith-and-judgement.pdf"
