cd /root/.pen/documents/notes/ws/fani;  "z" "17.06.24.pdf"
cd /root/.pen/documents/notes/ws/fani;  "z" "17.06.24.pdf"
cd /root/.pen/documents/notes/ws/fani;  "z" "17.06.24.pdf"
cd /root/.pen/documents/notes/ws/fani;  "z" "17.06.24.pdf"
cd /root/.pen/documents/notes/ws/fani;  "z" "17.06.24.pdf"
cd /root/.pen/documents/notes/ws/fani;  "z" "17.06.24.pdf"
cd /root/.pen/documents/notes/ws/fani;  "z" "cplint-17.06.24.pdf"
cd /root/.pen/documents/notes/ws/fani;  "z" "cplint-17.06.24.pdf"
cd /root/notes/ws/fani;  "z" "cplint-17.06.24.pdf"
cd /volumes/home/shane/notes/d-group-replicate;  "z" "Replicate - F260 Reading Plan.pdf"
cd /volumes/home/shane/notes/d-group-replicate;  "z" "Replicate - F260 Reading Plan.pdf"
