cd /volumes/home/shane/var/smulliga/source/git/emacs-mirror/emacs/etc/refcards;  "z" "calccard.pdf"
cd /root/notes;  "z" "calccard.pdf"
cd /root/notes;  "z" "calccard.pdf"
cd /root/notes;  "z" "calccard.pdf"
cd /root/notes;  "z" "calccard.pdf"
cd /volumes/home/shane/var/smulliga/source/git/emacs-mirror/emacs/etc/refcards;  "z" "calccard.pdf"
cd /volumes/home/shane/var/smulliga/source/git/emacs-mirror/emacs/etc/refcards;  "z" "gnus-logo.pdf"
cd /volumes/home/shane/var/smulliga/source/git/emacs-mirror/emacs/etc/refcards;  "z" "survival.pdf"
