cd /root/.pen/documents/notes;  "unison" "-batch=true" "/root/.emacs.d/elpa-light" "/root/.pen/elpa-light" "#" "<==" "sync-elpa-with-"
cd /;  "unison" "-batch=true" "/root/.emacs.d/elpa-light" "/root/.pen/elpa-light" "#" "<==" "sync-elpa-with-"
cd /;  "unison" "-batch=true" "/root/.emacs.d/elpa-light" "/root/.pen/elpa-light" "#" "<==" "sync-elpa-with-"
cd /;  "unison" "-batch=true" "/root/.emacs.d/elpa-light" "/root/.pen/elpa-light" "#" "<==" "sync-elpa-with-"
cd /;  "unison" "-batch=true" "/root/.emacs.d/elpa-light" "/root/.pen/elpa-light" "#" "<==" "sync-elpa-with-"
cd /;  "unison" "-batch=true" "/root/.emacs.d/elpa-light" "/root/.pen/elpa-light" "#" "<==" "sync-elpa-with-"
cd /volumes/home/shane/var/smulliga/source/git/semiosis/thoughts-on-theology;  "unison" "-batch=true" "/root/.emacs.d/elpa-light" "/root/.pen/elpa-light" "#" "<==" "sync-elpa-with-"
