;;; ivy-fuz-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ivy-fuz.el

(defalias 'ivy-fuz-regex-fuzzy #'ivy--regex-fuzzy)
(autoload 'ivy-fuz-sort-fn "ivy-fuz" "\
Sort CANDS according to PATTERN.

(fn PATTERN CANDS)")
(autoload 'ivy-fuz-highlight-fn "ivy-fuz" "\
Put highlight face on matched positions of the STR.

(fn STR)")
(register-definition-prefixes "ivy-fuz" '("ivy-fuz-"))

;;; End of scraped data

(provide 'ivy-fuz-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ivy-fuz-autoloads.el ends here
