#!/bin/bash
export TTY

# . $SCRIPTS/lib/hs

test -n "$1" && term="$1"
: "${term:="$TERM"}"
: "${term:="eterm-color"}"

paste <(infocmp -1 "$term" | sed -e '/^[^	]/d' -e 's/[,=].*//' -e 's/^	//') <(infocmp -1L "$term" | sed -e '/^[^	]/d' -e 's/[,=].*//' -e 's/^	//') | v
