#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

( hs "$(basename "$0")" "$@" "#" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

sn="$(basename -- "$0")"

# If I could memoise bash functions, that would be great!

. $PENEL_DIR/scripts/utils.sh

if ! { test "$istty" = 0 || test "$isstdoutpipe" = 0; }; then
    # e.g. (pen-snc "1John")
    in-pen unbuffer xt in-tm "$sn" "$@" & disown
    exit "$?"
fi

case "$sn" in
    bible-book) {
        if test "$istty" = 0; then
            book="$(list-bible-books | mfz -num -nv)"
            if test -z "$book"; then
                exit
            fi
        else
            book=Genesis
        fi
    }
    ;;

    *)
        book="$sn"
esac

export EMACS_BABEL
fargs=()
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -v) {
        version="$2"
        shift
        shift
    }
    ;;

    -f) {
        FAST=y
        shift
    }
    ;;

    -noemacs) {
        export NOEMACS=y
        shift
    }
    ;;

    -m) {
        fargs+=("$1" "$2")
        shift
        shift
    }
    ;;

    -*) {
        fargs+=("$1")
        shift
    }
    ;;

    *) break;
esac; done

# : "${version:="nasb"}"
: "${version:="rlt"}"

maybe_version="$(cmd-nice "$book" "$@" | bible-get-module-from-ref -df "$version")"
ref="$(cmd-nice "$book" "$@")"

# if test "$FAST" = "y"; then
#     ref="$(cmd-nice "$book" "$@")"
# else
#     # breaks "Psalm 22 | v"
#     ref="$(cmd-nice "$book" "$@" | scrape-bible-references | pen-sort line-length-desc | head -n 1)"
# fi

if test -n "$maybe_version"; then
    version="$maybe_version"
fi

# query="$@"
# 
# if test -n "$query"; then
#     if ! printf -- "%s\n" "$query" | grep -q -P ':'; then
#         query="$query:1"
#     fi
# fi

# "$version" "$book" "$query"

# "$version" "$book" "$@"

ebible -m "$version" "${fargs[@]}" "$ref"
