;;; eshell-did-you-mean-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eshell-did-you-mean.el

(autoload 'eshell-did-you-mean-setup "eshell-did-you-mean" "\
`eshell-did-you' setup.")
(register-definition-prefixes "eshell-did-you-mean" '("eshell-did-you-mean-"))

;;; End of scraped data

(provide 'eshell-did-you-mean-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eshell-did-you-mean-autoloads.el ends here
